### ISSUE TITLE
Increase comment length to 500 characters

### ISSUE THREAD

**Issue by cgome** [theCrag/website#100]
Increase comment length to 500 characters.

As per FB poll results and related email.

Apply truncation rules for other channels (eg Twitter) as appropriate.

Investigate options for the occasional longer post (eg FB notes?)- could be micro blogging on site, import from other blogs, other??? This can probably wait until we get into the social networking / accounts side of things.

**Comment by jedparkes** [comment]
i can't remember if there was another issue logged for this but i use the notes field to add all my beta and 500 characters often isn't enough, can this be increased?

**Comment by scd** [comment]
I have increased to 4096, which is as much as I can do without deeper thought. Please let me know if there are any problems with the update.

**Comment by jedparkes** [comment]
Great thanks, working perfectly.
Only other thing that has been annoying me is that the comments when viewed out of edit mode sometimes don't show line breaks? eg
https://www.thecrag.com/ascents/at/11745403/with-route-grade/AU:23:23/with-route-gear-style/sport/with-tick-type/redpoint/by/jedparkes/?sortby=when,desc

**Comment by scd** [comment]
@jedparkes, could you log this as a separate issue.

**Comment by jedparkes** [comment]
no worries, done
https://github.com/theCrag/website/issues/2192
