### ISSUE TITLE
Have ability / process to soft delete nodes

### ISSUE THREAD

**Issue by scd** [theCrag/website#1011]
Should soft delete nodes, rather than hard delete. In preparation for this I have created a Deleted node type.

Should deleted nodes should also have their parent field removed? 

Tasks:
* [ ] make a proper assessment on existing code (api, template json)
* [ ] faceted search
* [ ] full index query
* [ ] callbacks
* [ ] need a process to deal with the node graveyard.
* [ ] need to change status to deleted rather than removing the node from the database so that it works properly with a callback system
* [ ] need a mechanism to inform apps that the index structure has changed to remove deleted nodes. Actually quite complex and relates to reparenting and needs to fit in with any methodology we choose for syncing apps without getting the whole index.
* [ ] UI must be able to delete stuff at admin level with appropriate warnings about what other data is associated with that node, and a note on how the data is going to be dealt with.
* [ ] add menu items to action menu
* [ ] have grayed out menu item so people know it's possible but just need right permissions
* [ ] have clear docs / article around what roles can do this
* [ ] All soft deleted routes should be excluded from cpr.
* [ ] Deleted nodes should not have a link from event stream

Suggested 'heavy' delete business rules for when the node has references (eg ticks, photos etc)
* [ ] you are an admin at that node

Suggested 'lightweight' delete business rules for when the node has no references (eg no ticks or photos etc)
* [ ] if the route has only just been created AND you created it AND noone has ticked it, then you should be able to delete it
* [ ] if no-one has ticked it then a coordinator should be able to delete it. 

The trigger for all this work is the app syncing.

**Comment by brendanheywood** [comment]
Duplicated in https://github.com/theCrag/website/issues/1238

**Comment by brendanheywood** [comment]
Also duplicated in https://github.com/theCrag/website/issues/1471

**Comment by brendanheywood** [comment]
Also duplicated in https://github.com/theCrag/website/issues/1428

**Comment by brendanheywood** [comment]
There is a pseudo duplicate / root cause here of https://github.com/theCrag/website/issues/2888 - excluding that route / ascent from cpr is just a tiny bandaid, that route shouldn't exist at all. All soft deleted routes should be excluded from cpr.

**Comment by brendanheywood** [comment]
Mostly also a duplicate of https://github.com/theCrag/website/issues/1388 - but I won't close that as it also covers merges and moves.

**Comment by brendanheywood** [comment]
+1 from Matt

**Comment by scd** [comment]
Ulf comment.

```
I get a 404 for this one: https://www.thecrag.com/area/2213405721
It is linked to from https://www.thecrag.com/event/2213411619 
```

It looks like the hard delete function and streams are not playing nice. We need to turn the hard delete into a soft delete.

**Comment by Luen** [comment]
+1

**Comment by brendanheywood** [comment]
+1 from support

**Comment by scd** [comment]
Soft delete is done a while ago. Please create any outstanding bugs in separate issues.
