### ISSUE TITLE
Unable to elevate topo to an area level- target node does not appear

### ISSUE THREAD

**Issue by cgome** [theCrag/website#1015]
1. Unable to elevate topo to an area level- target node does not appear
   https://www.thecrag.com/climbing/australia/eastern-suburbs/area/226871868/topo#t238768413

I go

> Edit topo
> Add items
> Change Area
> Select Nielsen Park (Parent)
> Change Area
> Add routes
> Child routes of Let's get ready to rumble appear, Sibling node (Ring Side (Area)) appears, but 'Let's get ready to rumble! (Area)' does not appear.

Doesn't appear to be an error with area types as the sibling that appears has the same area type.

Maybe some kind of bug caused by the apostrophe or exclamation mark?

**Comment by rouletout** [comment]
This works now, closing
