### ISSUE TITLE
Unable to elevate topo to an area level- list of areas/routes too long

### ISSUE THREAD

**Issue by cgome** [theCrag/website#1016]
Unable to elevate topo to an area level- list of areas/routes too long

https://www.thecrag.com/climbing/australia/inner-west/area/243823113/topo#t243835683

and

https://www.thecrag.com/climbing/australia/inner-west/area/243823113/topo#t243835668

I go

> Edit topo
> Add items
> Change Area
> Inner West (Parent)
> Add routes

and the list is so long that 'The Boat Shed' doesn't make it on.

Looks like we either need to be able to scroll/click through long lists like this, or when you go down a level to the Boat Shed, it appears on the list of items that can be added?

**Comment by Mdemaillard** [comment]
List is now scrollable. Closing
