### ISSUE TITLE
Use a different icon for the 'Add topo' button? (Easily misread as 'add photo')

### ISSUE THREAD

**Issue by cgome** [theCrag/website#1017]
Use a different icon for the 'Add topo' button? (Easily misread as 'add photo')

In List View, area pages.

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76699278-c7c5d900-66b4-11ea-87fa-faad1883a6ff.png)
![image](https://user-images.githubusercontent.com/60388146/76699281-d0b6aa80-66b4-11ea-901f-6b0e37b18cbd.png)

Polishing, but still relevant in my opinion. Proposal:

- [ ] reuse the exisitng "camera icon" from topo button in Photo button. 
- [ ] replace topo button icon with something appropriate. Quick thought from base of a flash symbol.
![05 Flash-On](https://user-images.githubusercontent.com/60388146/76699417-f5f7e880-66b5-11ea-9809-93f92ec0dee8.jpg)

**Comment by brendanheywood** [comment]
I'd use the 'code-fork' icon in font awesome:

**Comment by lordyavin** [comment]
+1 for code-branch
![grafik](https://user-images.githubusercontent.com/1528540/76937751-af90cc80-68f5-11ea-9812-1342421078c3.png)

**Comment by killakalle** [comment]
@scd 
Could it be that you accidentally removed the icon completely (or that the new icon is not loaded properly)?

![image](https://user-images.githubusercontent.com/30682796/89391606-b4b9b100-d708-11ea-8c62-47867c51caf1.png)
https://www.thecrag.com/climbing/germany/berlin/area/233883189



![image](https://user-images.githubusercontent.com/30682796/89391713-d9ae2400-d708-11ea-9b5c-1dd256489a47.png)
https://www.thecrag.com/en/climbing/germany/berlin/area/3719572296

**Comment by scd** [comment]
We changed the icon, but I think I have stuffed something up in the release process. The image is pointing to:

https://static.thecrag.com/svg/add-topo

and it should be pointing to

https://www.thecrag.com/svg/add-topo

**Comment by scd** [comment]
The missing icon is fixed, but we are still working on getting the icon sizing right.

**Comment by rouletout** [comment]
Done, closing
