### ISSUE TITLE
add routes concurrency problem?

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#1022]
I added to a crag in France 4 sectors. Open an "add route form" for each sector with 20 routes. Then I went on the train from work to home and filled the 4 forms with routes for each sector.

At home is send the form data (i am offline at the train) as I have done this several times before. This time i did not wait with the second form until the first form was done. More or less i send all 4 forms at once (of course with minor time delay). The result was that two forms returned with some error (unfortunately i did not notice the error message it was an SQL error and something with locking of tables). I pressed reload for both forms and the next error was that all there are already routes with the same names for all routes.

Now the state is that all routes have been added but not some parents to not know about it.

Have a look to: http://www.thecrag.com/climbing/france/baume-rousse

1   Gauche Facile Sector    All Sport   17  0  
2   Gauche Compétition Sector  -   0   0  
3   Droite Compétition Sector  -   0   0  
4   Droite Initiation Sector    All Sport   20  0   

You see that sectors 2 and 3 have no routes. If you click on the name of the sector you go to the sector page and will not see any children. 
If you click on the "0" climbs you will go to the "search all routes in the node" page and you will see all routes.

Any Ideas?

Nicky

**Comment by scd** [comment]
Closing as this cannot be done without major re-architecting
