### ISSUE TITLE
add url slugs for routes

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1025]
I think we're all pretty happy with the new url slugs, they rock.

But we can always do better, the route names aren't in the url. For relatively famous routes I think having the name in the url will go a long way, but also I want to short circuit all the bullshit with duplicate name mapping to the same url. I'm thinking of a very quick, unobtrusive way to get these without doing almost any work.

Currently this works:

http://www.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/route/13343113

But so does this:

http://www.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/route/13343113/whatever

or more importantly this:

http://www.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/route/13343113/trajectory

I'm wondering what would be the upsides and downsides to just changing the templates to stick a sluggified name on the end, similar to what I did with the discussion posts. Zero back end changes.

ie:
http://www.thecrag.com/discussion/263249613
http://www.thecrag.com/discussion/263249613/blues-point--bp-has-love

**Comment by brendanheywood** [comment]
Just re-reading this spec, and probably the only thing I'd change it making the number part of a url slub appear at the end instead of the start so you'd have url's like:

http://www.thecrag.com/discussion/blues-point--bp-has-love-263249613
http://www.thecrag.com/climbing/australia/mount-wellington/organ-pipes/great-red-pointer-12373201

It just makes it slight faster for a human to parse and less likely to get the word parts truncated in a browser url bar. 

If for some reason we need to know the node type from the url, perhaps for router performance reasons then we could simple take a 1 char prefix onto the number so:

'r12373201' for route:

http://www.thecrag.com/climbing/australia/mount-wellington/organ-pipes/great-red-pointer-r12373201

Also just -reconfirming that there are no issues with google with all of this because we already have the canonical url stuff in place.

**Comment by scd** [comment]
I don't really want to do this. Closing
