### ISSUE TITLE
improve business rules for showing onsight grade on profile page and how it is calculated

### ISSUE THREAD

**Issue by scd** [theCrag/website#1028]
David Nott hardly does any onsights so does not want his onsight summary at the top to appear.

https://www.thecrag.com/climber/davidnn5

Also many people ask questions around why their onsight is not their hardest onsight when it is roughly 3 ascents at a certain grade. We intend to move this to a cpr based algorithm so if you have onsight ticked 2x 21 and 1x 24 your onsight grade might actually be 22 or 23 under the new system instead of either 21 (3rd highest ascent) or 24 (hardest onsight). Either way we need it to be much more clear about what the grade is supposed to represent

**Comment by brendanheywood** [comment]
This is probably the closest issue related to the display on onsight on the profile page so I've extended this slightly to include both when the onsight should appear also also how the stat is calculate, ie eventually move it to a cpr based grade.

**Comment by brendanheywood** [comment]
This is all done one way or another in the recent profile releases
