### ISSUE TITLE
GPS entry from bulk edit doesn't work

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1046]
Works when editing a single route, also works when batch inserting new routes

**Comment by brendanheywood** [comment]
From @rouletout via https://github.com/theCrag/website/issues/2209

When entering multiple routes through the Add Routes command latitude and longitude information is not stored for the route (if entered previously, it can't be edited). When entering a single route lat/long can be entered (at least occasionally).
Also, a hint if W or E is the negative value would help.

**Comment by Mdemaillard** [comment]
Clearing an existing GPS entry does not delete the location for a route, the old location is still visible in the index page (but not in the edit field).

**Comment by rouletout** [comment]
This works with the new bulk edit form, closing
