### ISSUE TITLE
"Warnings" field in climb node

### ISSUE THREAD

**Issue by morefigs** [theCrag/website#1055]
This climb has a warning about loose bolts written into the climb description: http://www.thecrag.com/climbing/australia/blue-mountains/bowens-creek/route/15440485. This doesn't really belong in the climb description as the loose bolts hopefully will be fixed, and the warning doesn't really stand out.

It seems like a better option could be to have an extra textfield named something like "warning(s)" that could mention the loose bolts. Visually this could stand out in a coloured box etc. This field would not be visible if there were no warnings (ie on nearly all climbs), but it would be important for dangerous climbs.

**Comment by brendanheywood** [comment]
I'm gonna make an exec call and close this. I think a markup approach is too esoteric and people won't know about it so it wouldn't have gotten used much. If and when we solve this problem it will be via a more structured way to flag issues via https://github.com/theCrag/website/issues/1865
