### ISSUE TITLE
How to delete geo location of node / area / cliff

### ISSUE THREAD

**Issue by scd** [theCrag/website#1075]
I cannot see how to use the current map UI to delete a location.

Is that a API problem or am I just missing something?

Areas to remove location:

* [x] https://www.thecrag.com/climbing/france/area/1451501298

* [ ] Back end script to remove locations ./remove-node-location 11902621

* [ ] fix related issue of antimeridian calculations with the bbox a cbbox

* [ ] merged nodes leaves behind a location

Delete the following locations

 * [ ] https://www.thecrag.com/climbing/united-states/santa-monica-mountains

**Comment by brendanheywood** [comment]
Copying a comment over from this duplicate: https://github.com/theCrag/website/issues/1745

> I have written a script to do this and installed on prod:
> ./remove-node-location 11902621
> Soft deletes.
> Also it was very obvious that we should not be asking for node location information for closed crags. The campaign triggers no longer trigger for closed crags.

This should be part of the new maps rewrite

**Comment by lordyavin** [comment]
+1 for complete deletion of location data.

**Comment by brendanheywood** [comment]
Can you please document the api delete

**Comment by scd** [comment]
We also need to be able to clear location when all located nodes are moved out of an area. In the following example there is no explicit location data, but the cascaded bounded box probably remains.

  * https://www.thecrag.com/climbing/france/area/1451501298

**Comment by brendanheywood** [comment]
To be deleted:

* [ ] https://www.thecrag.com/climbing/united-states/blue-mounds-state-park/area/14762275/locate

**Comment by brendanheywood** [comment]
Merging https://github.com/theCrag/website/issues/1076 into this one

I have also fixed up all remaining known bad locations document in this issue above. The only two left are a different issue with the bbox of oceania and polynesia overlapping the antimeridian so their cbbox is getting screwed up (https://github.com/theCrag/website/issues/3348)

**Comment by scd** [comment]
+1 delete this location https://www.thecrag.com/climbing/united-states/santa-monica-mountains

**Comment by brendanheywood** [comment]
+1 for https://www.thecrag.com/climbing/australia/the-you-yangs/area/11942395/locate

Deleted 7 dud locations which had been stretched out to fill all of the you yangs

**Comment by lordyavin** [comment]
This [area](https://www.thecrag.com/climbing/united-states/smith-rocks-state-park/area/12576673/locate) demands this feature too. IMHO the area is totally wrong and the shape has lots of points and it is hard to change it manually. 

BTW: Is there no way to remove a point of a shape?

**Comment by brendanheywood** [comment]
On the locate edit page it tells you how to:

> To delete a point, press 'D' or 'Delete' when hovering over a point

I just jumped into that area and simplified it and it took me 30 seconds. I'm not a local so have no idea how accurate it is but that outline looked fine to me, either before my edits or after.

**Comment by lordyavin** [comment]
Thanks for helping me read :see_no_evil:

**Comment by rouletout** [comment]
Another one to delete is here: https://www.thecrag.com/climbing/italy/arco/area/1957578132

I just no it is wrong but don't know the correct one

**Comment by Mdemaillard** [comment]
+1, deleting all points of a shape does not work for the last 2 it seems ?

**Comment by rouletout** [comment]
Thius is now available as admin function, closing
