### ISSUE TITLE
Weird logbook links and inconsistency / private account

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1105]
I was helping out Luc today and noticed weirdness with his profile, I suspect because he has a private account.
- [ ] First on his profile page it says 0 unique ascents and 0 distance climbed, but then on the right hand side shows a whole bunch of recent ascents.
- [ ] secondly, if I click on logbook, then I get this url which has a a title of '391,694 Ascents by' and show EVERY tick in the database!

https://www.thecrag.com/ascents/by/316855041/
- [ ] related to above: he joined in 2013, but the ticks are from 2009 to 2011

**Comment by scd** [comment]
This was fixed a while ago.
