### ISSUE TITLE
What to do about Flash tick type for bouldering - it currently appears as a lead climb

### ISSUE THREAD

**Issue by scd** [theCrag/website#1110]
I'm not sure what to do about this:
- [ ] create a separate boulder flash tick type
- [ ] remove flash from lead tick group, or remove lead tick group alltogether
- [ ] redesign the system and add extra conditions on lead tick group
- [ ] wait and see what other issues come up as we add other climbing styles then make a decision

In about 12 months we will have people adding ticks for many different styles including via Ferrata, gyms, mountaineering, ice, etc. I think we wait and see what other requirements pop up then make a decision.

**Comment by brendanheywood** [comment]
@scd can we close this?
