### ISSUE TITLE
Disable social media stuff (option in user profile)

### ISSUE THREAD

**Issue by theSCRAG** [theCrag/website#1119]
Reason:
many people don't like facebook, because violation of privacy protection.

add option(s) to user profile
[x] Disable social media stuff (like Facebook, Google+, ...)

Disable all plugins and remove not necessary links.

**Comment by MelwinQ** [comment]
Thanks for considering this issue.
However, I have disabled all connections, still Ghostery (anti-tracking add-in) shows that it has blocked "Facebook social Plugins" (above member photos).
Couldn't the Facebook-stuff be disabled alltogether?

**Comment by scd** [comment]
Yup I agree. Actually I might even go one step further and say that this facebook plugin is not the best use of that premium space, so maybe we should consider leaving it out for everybody.

**Comment by brendanheywood** [comment]
That facebook plugin is the primary way that most people see updates to the platform which we post on facebook. Until we have our own proper blog, or integrate new announcements into thecrag itself I wouldn't want to remove this.

If you want to use ghostery to block it that's fine, and we couldn't stop it anyway, but that's not a compelling reason to remove it for everyone. It serves an important purpose for us.

**Comment by scd** [comment]
But we could make it configurable for individual users.
