### ISSUE TITLE
Script to fix local grade context where it is wrong

### ISSUE THREAD

**Issue by scd** [theCrag/website#1122]
"Having trouble with the grade context: it seems at least some parts of Australia are set to American YDS context when adding a route, whereas it should be Ewbank.

For example - trying to add routes at Snake Rock http://www.thecrag.com/climbing/australia/gibraltar-peak-and-corin-road-crags/snake-rock

Any routes with a grade below 15 are registered as YDS"

Have a look at this route in particular, for example:

http://www.thecrag.com/climbing/australia/gibraltar-peak-and-corin-road-crags/snake-rock/route/323243478

**Comment by rouletout** [comment]
This seems fixed, closing
