### ISSUE TITLE
Topos attached to a parent node are not shown in List View (multiple topo parents)

### ISSUE THREAD

**Issue by oliverstory** [theCrag/website#1134]
I've spent a bit of time recently uploading topos and re-organising sub-areas.

In the process I've had difficulty deciding where a topo should be "parented" when it contains routes from more than one area. The in-site help suggests that a topo should generally be "parented" to the highest level common node. This seems a reasonable rule of thumb. However if you do this, then the topo does not show up in List View for the relevant child areas. It does show up in Guide View though, and I think this should be the behaviour for both types of view.

For example see this topo: https://www.thecrag.com/climbing/australia/gibraltar-peak-and-corin-road-crags/area/320279823/topo#t325023156

It has routes that are accessed from two or three different places, hence they are split into three different areas. For example it should show up here: https://www.thecrag.com/climbing/australia/gibraltar-peak-and-corin-road-crags/the-southern-tablelands but doesn't.

Cheers
Oli

**Comment by rouletout** [comment]
Topo shows at all required places - at least for the examples given here, closing
