### ISSUE TITLE
Quick keyboard shortcuts for changing ascent grades

### ISSUE THREAD

**Issue by scd** [theCrag/website#1138]
When I'm editing an ascent of mine, there is the whole list of systems and values in the dropdown-list "Ascent grades". I would like to insert 'FER' so the cursor could jump down to FERRATA, but it goes to F... and stops there. If I press F, F, F, F and so on... it continues it's steps through F-values.

**Comment by Mdemaillard** [comment]
in route creation the form has a context dropdown and then free text
![image](https://user-images.githubusercontent.com/60388146/76323625-9d0f0580-62ed-11ea-8027-c4baf2a42deb.png)

in both Log ascent form and Ascent edit forms there is a long drop down selector of all grades systems and values.
- [ ] that should be aligned with the route creation form, with context pre-filled by route context (or user preferred ?)

![image](https://user-images.githubusercontent.com/60388146/76323716-c0d24b80-62ed-11ea-9442-7d7c88e346f6.png)

**Comment by rouletout** [comment]
New ticking interface, closing this
