### ISSUE TITLE
brazilian grading systems

### ISSUE THREAD

**Issue by scd** [theCrag/website#1139]
- [ ] brazil has a grading system which looks like a fork from French which has diverged, similar to how south african diverged from australian. See #1139. This needs a whole new system, plus a whole new country context for brazil. Making matters worse it looks like they use the font 5A system for bouldering as well as the V grade. brazil is quite a mess, but with only 420 routes it's not a mess at scale and we should try to get things right here before the data grows too much more.

 - [ ] some south american countries should be use either the Brazilian grades or French grade, specifically: argentina, peru, but the waters are muddy because those two systems / contexts overlap.
http://en.wikipedia.org/wiki/Grade_%28climbing%29#Brazilian

Cannot implement until we find more explicit resource (this one is a little vague) and an explicit conversion table

**Comment by scd** [comment]
@henrique I have released the brazilian grades now. Are you able to start the manual upgrades. If there are a painfully large number of routes to upgrade in an area then let me know and we can use the spreadsheet method.

When that is done, please spread the word.

**Comment by henrique** [comment]
@scd many thanks again! I don't know what is easier but if it's not too complicated could you export http://www.thecrag.com/climbing/brazil/minas-gerais/area/500912871 for me? I can have a look this week or the next and get the correct grades, at least for the routes already listed.
Cheers

**Comment by henrique** [comment]
it looks like we have a encoding problem on "Please input the rating system grade details." > "* Range Limit" > "5Â°"
At least on my firefox on Ubuntu, we normally advise strict use of UTF-8 for non-english support but whatever works for you.
thx

**Comment by scd** [comment]
@henrique I have started another issue #1789 regarding the encoding. 

BTW, it will take about half an hour of my time to do the spreadsheet method, so if let's see what other areas require changes first.  I think that 21 might be easier to do using the painful online method.

**Comment by henrique** [comment]
Ok, no worries, I'll have a look on the bulk edit later on but can you guys at least change the "Local Grade Systems" of every route in brazil to your BRZ?
thank you

**Comment by henrique** [comment]
Hi @scd 
The bulk edit doesn't seem to add the grading system even when selected "BRZ", I've edited most routes but nothing happens on the front page.
Perhaps there is another way of doing it but editing each route manually requires a bunch of clicks per route which makes it impracticable.

**Comment by brendanheywood** [comment]
hi @henrique just a fyi that Simon is on holidays for a week so don't expect a quick reply.
