### ISSUE TITLE
grade bands not being updated after route grades been added

### ISSUE THREAD

**Issue by scd** [theCrag/website#1140]
In Poland a whole lot of routes were entered without a grade, while they were waiting for the Polish Grading System. After the grade was added the grade band was not updated.

http://www.thecrag.com/climbing/poland

They problem was manually fixed by reruning a stats baseline for each crag. But there is something missing from back end stats logic in the first place, when adding a registered grade.

**Comment by brendanheywood** [comment]
+1 via supporter

**Comment by scd** [comment]
This seems to work now. Closing
