### ISSUE TITLE
Refinements to maps api and node selection algorithm

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1145]
There is a growing number of common map use cases where the existing algorithm isn't working great. So collecting some test cases here to help inform improvements. I've got a new algorithm in mind which is only slightly different the current one which should fix all of these (after responsive, after topos, after....?):
- [ ] Siblings or uncles that are structurally valid https://www.thecrag.com/maps/climbing/australia/gibraltar-peak-and-corin-road-crags#-35.480948,148.969688,13,,terrain
- [x] cousins on either side of a border, but only one set is shown 
- [ ] lots of children but cluster too close so labels clash https://www.thecrag.com/maps/climbing/australia/nowra#-34.847681,150.537987,11,,hybrid

**Comment by scd** [comment]
@brendanheywood with this algorithm you are recursing if the dimensions are wider than X pixels. Do you also mean higher they Y pixels as well. Otherwise a vertically aligned thin area might not trigger but a horizontally alligned one will.

**Comment by scd** [comment]
I have just done a data migration to split bounded box from a single text field into separate number fields and I also added the long and lat angles for index optimisation.

I think the core query for this something like this:

```
SET @long1 = -180;
SET @lat1 = -90;
SET @long2 = 180;
SET @lat2 = 90;
SET @angle = 7;

SELECT SQL_NO_CACHE
  L.ID,
  L.NetworkNode AS NodeID

FROM
  NodeLocation AS L

WHERE
      L.ActiveFlag = 1
  AND L.BBoxPt2Long >= @long1 AND L.BBoxPt1Long <= @long2
  AND L.BBoxPt2Lat >= @lat1 AND L.BBoxPt1Lat <= @lat2
  AND L.LongAngle >= @angle
```

Which returns 227 location records, which sounds about right. Note that the `LongAngle` field is for index optimisation. Using a maths forula (long2 - long1) the query takes about 100ms, but using the indexed pre-calculated field this goes down to about 15ms.

Hopefully adding all the other info does not slow the query down to much.

**Comment by brendanheywood** [comment]
Yes the max width or max height, using either min or max depending on context. So assuming LongAngle is populated with the max of the width and height then all good

**Comment by brendanheywood** [comment]
Also need to test the international date line wrap around, we've had issues in the past with that

**Comment by scd** [comment]
Hmmm, international date line. The bounded box supplied to the api end point could be over the date line or the bounded box of nodes could be over the date line. I think the first is dealt with by detection and modifying the search query. The later could be done by detection on nodes at query time, but then this would lose a lot of efficiency. I am pretty sure we will need a field which says the bounded box goes over the datelline.

**Comment by scd** [comment]
Also there are a few other edge cases in the query, which I think I have mostly worked through and kept it relatively efficient

 - [ ] exclude test node
 - [ ] exclude hidden locations
 - [ ] exclude merged and deleted nodes (implemented the other way around, include specific node types)
 - [ ] if location is missing from parent node it should still be returned in the heirachy query

**Comment by scd** [comment]
I am going through the here algorithm logic, which I cannot fully follow. If the viewport is the whole world then the 5 points are [[0,0],[-60,-30],[-60,30],[60,-30],[60,30]] which leaves the here value pointing to Africa

```
                  "hereCount" : 3,
                  "bbox" : [
                     -27.6581187,
                     -41.1761476,
                     63.9678578,
                     40.3488
                  ],
                  "name" : "Africa",
                  "id" : "11737843",
```

@brendanheywood would this be what you expect?

**Comment by brendanheywood** [comment]
Yes that actually does make perfect sense following the algorithm. The choice of 1/3 the viewport in each direction is easier to explain with a diagram, but that value of 1/3 could be enlarged to as high as 1/2 and still be correct for the roundtrip node selection, so try tuning that first. Ideally I'd like to see that visually on the map and pan around and see how it actually feels.

**Comment by scd** [comment]
Tuning we can do later when we have the benefit of something visual, so I will leave it as it is. The main thing is that I wanted to confirm that I did not misunderstand.

I have gone with a pretty simple implementation which is to find the deepest nodes which pass the three point tests. If there are more than one then just use the closest centroid distance. If we need to enhance this then it will be clearer when we have that visual display.

Should the `here` variable be an id or a node with url etc.

**Comment by brendanheywood** [comment]
Just an id is fine. In the simplest case where the client does no caching, it will never pass in a set of nodeid's to start the search from, which should mean that the data for the here node is guaranteed to already be in the payload.

**Comment by brendanheywood** [comment]
I think it's worth tuning that 1/3 from .333 to .4, it's a safe change and will mean at the world view the world node will be 'here'
