### ISSUE TITLE
Refine 'setter' / 'set by' UI logic for when it can be used, ie not on boulders?

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1149]
In use for a bolter outside:

http://www.thecrag.com/climbing/australia/blue-mountains/bells-line-of-road/area/283558596

I think this is fine for examples where a route is still a project, or if the route was sent by a different person (as discussed elsewhere). 

Or maybe we just filter it out if there is a proper FA, but the logic for this could get hairy. Maybe it's just part of our 'quality checklist' and we just leave it as is.

See also #605 for original spec

**Comment by brendanheywood** [comment]
See also https://www.thecrag.com/discussion/1383572694/dreaming-frog--set-by

**Comment by Mdemaillard** [comment]
Counterexample of boulders with a setter, so if we decide to remove the dropdown for route type Boulder, there will be some data cleaning as well.

https://www.thecrag.com/climbing/uganda/insita/area/1558135833
https://www.thecrag.com/climbing/morocco/area/1123556424
For me these examples can (should) be cleaned

Here something where presumably someone "discovered" the boulders, and someone else sent the FA ?
https://www.thecrag.com/climbing/egypt/cairo/area/2942562999
https://www.thecrag.com/climbing/switzerland/cresciano/area/392099778

Clearly a change in possibility and/or eventual data retro-correction will hurt sensibilities.

**Comment by rouletout** [comment]
With the optional history fields this is not an issue anymore - closing
