### ISSUE TITLE
TLC definition refinement

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1155]
I was under the mistaken impression that a node that was not marked as a 'crag' could be considered as a TLC. eg a Cliff in the middle of nowhere which is the child of a region, in my mind this is semantically correct and should be treated as a TLC. Same with 'fields', or other node types which are directly under a region.

eg I recently ticked some stuff at wavely park, which is currently a 'boulder' (but should probably be a field or cliff, but not really a crag) - but in any case it should be treated as a TLC.

http://www.thecrag.com/climbing/australia/tasmania/area/162224700

ie in places the TLC name is used, but for these ticks it is blank:

![image](https://f.cloud.github.com/assets/187449/884015/bacef48c-f9a3-11e2-8771-60f08785c5d8.png)

**Comment by scd** [comment]
this is essentially done - see #1288
