### ISSUE TITLE
Should images be served from CDN, Prod, or Static?

### ISSUE THREAD

**Issue by scd** [theCrag/website#1160]
- [ ] Investigate costs - Adam thinks the following CDN is good value: http://www.incapsula.com/
 - [ ] How do we manage the propagation delay? Maybe serve from Prod for 1 hour?
 - [ ] Manage backups and unnecessary copies in dev?

**Comment by scd** [comment]
see also #2029

**Comment by scd** [comment]
@brendanheywood can we close this.

**Comment by brendanheywood** [comment]
yup

**Comment by nicHoch** [comment]
Am 12.03.2016 um 13:11 schrieb Brendan Heywood:

**Comment by brendanheywood** [comment]
@nicHoch is there something missing from that last comment of yours?

**Comment by nicHoch** [comment]
It was not my intention to add a comment to this issue. No idea why there
is an empty reply.
Nicky
Am 14.03.2016 00:34 schrieb "Brendan Heywood" <notifications@github.com>:
