### ISSUE TITLE
add avatar to following email notification

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1165]

**Comment by Mdemaillard** [comment]
to be closed, duplicate has more info

**Comment by scd** [comment]
@Mdemaillard I am fine with you closing things you think can be closed.

**Comment by Mdemaillard** [comment]
I would like to be able to label issues, maybe close if they are obvious,
but do not have writing rights on the repository.
It seems the github right system is not very granular so you can have a
look and decide if I get write access or not.
Cheers

**Comment by scd** [comment]
@Mdemaillard I have invited you to the project with Triage role. Please let me know if this is enough permissions to close issues.

**Comment by Mdemaillard** [comment]
It does for Labelling and Closing. I'll explore a bit what else.
