### ISSUE TITLE
Improve process for correcting grading systems

### ISSUE THREAD

**Issue by scd** [theCrag/website#1170]
From time to time the wrong grading system has been recorded for routes. Correcting this is currently a cumbersome process. 'Annoying' is the word our users are using.

It needs to be streamlined.

**Comment by Mdemaillard** [comment]
Currently bulk edit allows to modify route context of a bunch of routes.
![image](https://user-images.githubusercontent.com/60388146/76324880-4f939800-62ef-11ea-9ec9-f14227df1faf.png)

Local grade context is set at node level, not available to editor so should not be in scope (?)

Was this before the bulk edit was available ? Else is the suggestion to have a few default fields on top of a bulk edit, like on top of bulk ascent logging ?
i.e. : style of route (is not autopopulated when a crag doesn't have routes yet)
i.e. : grade context of route
...

**Comment by Mdemaillard** [comment]
I just did a few hundreds routes i Hong-Kong, really its not bad.
- filter all routes on a high level crag to what you are looking for
- select a single route if stand alone, or an area with route # manageable
- bulk edit

Note to self to test: 
changing crag context to the "overridden gradessystem" of the routes correct display. To verify on sandpit if it erase the override. 
I.E. to test massive changes: of say, UIAA context with tons of FR: overrides:
1. swap context to FR
2. update cache --> display sorted
3. swap context again to whatever
-> verify if original override is still there, or if all routes are nicely under the new context.

**Comment by scd** [comment]
Closing based on Marc's comments.
