### ISSUE TITLE
Make a universal grade input widget

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1180]
Principals:
* [ ] UX for adding a grade or editing is identical
* [ ] UX for above is the same regardless of which process or page we are on
* [ ] free text will always be the easiest, so work with it instead of getting in the way

Mockup of bulk edit page

![image](https://f.cloud.github.com/assets/187449/974712/59ecbc26-065f-11e3-805a-228390e1be57.png)

**Comment by scd** [comment]
This is pretty much done. Closing
