### ISSUE TITLE
clicking 'Log Ascent' in area list view without selecting a route

### ISSUE THREAD

**Issue by scd** [theCrag/website#1205]
What should happen if we click 'Log Ascent' in list view without selecting a route?

Currently you get taken to a page which asks you to select the routes. If this is what we want to happen then we should tidy up that page.

Alternatives:
- separate page to select route(s)
- warning asking you to select route(s)
- a drop down with a list of routes for you to select one.

**Comment by Mdemaillard** [comment]
I do not think the log ascent button is still available without selecting a route. Probably sine a revamp of the action menu ?
closing
