### ISSUE TITLE
Have profile stats option to weight everything by meter instead of # of routes

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1207]
From Scott Godwin:

> Is there a way to plot number of metres climbed, rather than number of routes climbed in the bar charts on your dashboard? If not I reckon this would be a cool thing to have. I climbed a lot of long routes this year but every time I look at those charts its makes me sad because it looks like I haven't done very much. I think one 400m route should be worth as much as twenty 20 m routes.
- [ ] I think stuff like this should be both a toggle that others can flip when looking at a profile and also a setting for your own profile.
- [ ] should this also sort the routes by height? Ie if you hardest onsight is 22, show your top 2 longest 22's?
- [ ] have a new column in the notable ascents table with cumulative height
- [ ] We should also make it easy to show and get people to fix missing heights, like the missing gear style drop down. I think this is mostly unfinished facet business, eg we should be able to search for ascents by Scott, that don't have a height. All the route filters should be in the ascent facet too

**Comment by Mdemaillard** [comment]
merging into #3197, closing here to prevent spreading of input.
