### ISSUE TITLE
Have proper 404 50x etc error pages for unrouted url's

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#121]
I had this idea of a error page graphic with a skull and cross bones but made from climbing gear:

Helmet as skull cap, with atc as nose bone with cam for teeth and quick draws for bones behind it.

Would be a fun couple hours in photoshop 

Tasks:

* [ ] http://www.thecrag.com/climber/idontexists
* [x] 503 http://dev.thecrag.com/ascents/at/17713597%2017713651/
* [x] 404 https://dev.thecrag.com/climbing/note-a-node

**Comment by brendanheywood** [comment]
@scd I've just implemented this for 500 errors. I can see at least 4 or 5 ways errors can get served this patch only covers one but it should cover the majority of cases, eg:

http://dev.thecrag.com/ascents/at/17713597%2017713651/

![image](https://cloud.githubusercontent.com/assets/187449/17828968/253179f4-66e2-11e6-9254-6f2f23c785f2.png)

There are still some other use cases not covered which I've found, this isn't handled:

http://dev.thecrag.com/notapage

Also at the moment the code doesn't distinguish between a 404 for info not found and a 500 for some exceptions. These really should be different, eg this should be a 404 and show something useful like a search page:

https://dev.thecrag.com/climbing/note-a-node

Can you please review: 7041fd8e5838

Also this isn't translated and I'm not sure if we should bother given that it needs to work even when things are fundamentally broken.

**Comment by scd** [comment]
It looks like the main logic is in WebPortal.pm. Can I just confirm that you did not have to change anything in the apache config file.

It seems to work on my dev.

Don't worry about the translation for this one.

**Comment by brendanheywood** [comment]
... and it's now doing 404 vs 503 properly:

503 http://dev.thecrag.com/ascents/at/17713597%2017713651/ 

vs
404 https://dev.thecrag.com/climbing/note-a-node

![image](https://cloud.githubusercontent.com/assets/187449/17829129/f0899b36-66e7-11e6-85e5-b86d1be37606.png)

Nope didn't touch apache conf, I had an issue with adding the image but I've manually preempted the build and release process and scp'ed it to the static server and referencing it from there.

**Comment by brendanheywood** [comment]
Simon can we access site config from there to inject the google analytics snippet? I'd really like to get that collected too before I close this off fully

**Comment by scd** [comment]
Yes we have google analytics queue for logging ga events without blocking
server process. What is the specs for the ga event you want to log. Fyi the
api logs ga events.
On Aug 20, 2016 15:26, "Brendan Heywood" <notifications@github.com> wrote:

Reopened #121 <https://github.com/theCrag/website/issues/121>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/theCrag/website/issues/121#event-761987778>, or mute
the thread

**Comment by brendanheywood** [comment]
I was thinking of client side like any other page, I'd just need access to the Api key. But backend would work fine too. It just needs to send a either a real front end or fake backend page view with the http code. Front side would be much better

**Comment by scd** [comment]
I have added the ga config to the error_page function (in repo). I have not included the javascript yet because I have run out of time right now. If you get a chance you can add it or I will later.

**Comment by brendanheywood** [comment]
ga is now working. Ok final thing which you can split into another issue if you want but seems small:

If you visit a missing climber page you get routed to an article instead which is pretty weird:

http://www.thecrag.com/climber/idontexists

This should go to the 404 or maybe later to a better user search page?

**Comment by scd** [comment]
split as separate issue #2331
