### ISSUE TITLE
Responsive process page (not ticking page)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1221]
Trying to get back for buck here, thinking each process can pass a responsive flag to the process template, just like the main templates. If present it pulls in an alternate stylesheet. We make minimal changes to the ticking form markup to get it into good shape to support this which will probably be 80% of the changes needed to support most of the other process pages. Then we can turn them on one by one and avoid re-implementing them all as template pages.

**Comment by scd** [comment]
This was done a while ago, closing.
