### ISSUE TITLE
Improve rollover tool tips for grade profile graph to include number of partial ascents

### ISSUE THREAD

**Issue by scd** [theCrag/website#1226]
It's creating confusion. For example the following user feedback:

There seems to be a bit of an issue with how climbs are counted - I can't quite work out what is the cause.
The example I have is here - if you look at my profile: http://www.thecrag.com/climber/snappy
For grade 26, the dashboard says 2 - 1 route and 1 boulder. Click on my assents and you'll see 1 26 and 3 V5s (which correlates to 26 on the dashboard.)
Any ideas?

**Comment by brendanheywood** [comment]
done
