### ISSUE TITLE
Increase visibility of Tick type definitions

### ISSUE THREAD

**Issue by cgome** [theCrag/website#1227]
Increase visibility of Tick type definitions- especially for international users.
- In tool tip on tick-type icon
- Help link to article (http://www.thecrag.com/article/TickTypes) next to tick type dropdown in the add ascent screen

User email:

I think it would be great if you could create a glossary with the difference between

-lead
-onsight
-flash
-red point
-pink point
-dog
Etc…

It could simply be a small text appearing when we put our mice on the text.
Because some of them are not clear for me and some of my friends. For example we didn’t find what is a “dog ascent”…

Thank you.

**Comment by brendanheywood** [comment]
As part of tick type release we'll do a matrix similar to the google doc, but in an article like the grade table

**Comment by brendanheywood** [comment]
Closing this, we have the tooltip, and we will have unique icons + translated tick type article
