### ISSUE TITLE
Trip default when logging ascents

### ISSUE THREAD

**Issue by cgome** [theCrag/website#1233]
Support email:

Just had a quick idea for logging ascents.

When you are logging a few/ a lot of assents for a particular day you can use the choose day button at the top to select the day for all of them

As i'm on a trip I thought this would be a good feature as well for trip selector so you don't have to click it on every climb.

Any way keep up the good work

**Comment by lordyavin** [comment]
Why the f... do you guys discuss issues on facebook? Please pull such discussions to theCrag. I'm not using facebook.

**Comment by brendanheywood** [comment]
Facebook is a great conduit for feedback, but we generally copy the stuff into github as needed. We have 2k followers on Facebook so it's not going anywhere

**Comment by lordyavin** [comment]
Looks like I need a facebook account... to stay up-to-date...

**Comment by brendanheywood** [comment]
We post to facebook which is embedded into the dashboard inside thecrag even if you don't have a FB account. And any meaningful discussion on FB which results in an action gets put into the github list. We accept feedback via email, FB, github, or whatever.

**Comment by lordyavin** [comment]
Please reactivate trips!
