### ISSUE TITLE
Focused / special route listings in PDF 

### ISSUE THREAD

**Issue by cgome** [theCrag/website#125]
Selected routes in PDF and Epub guides could be given a premium/expanded listing that could include (ranked in my order of priority)
- Full tag cloud image
- Lead style graph
- Climb quality graph

This would
- Attract reader attention to the best routes
- Demonstrate our key strengths/points of difference compared with normal printed guides, esp to people who maybe get the guide without knowing the site

It needn't have a big impact on the overall size of the guide.

Rules for selecting which routes get a premium listing could be based on:
- Grade Icons
- Quality (eg all 3 star climbs)
- Popularity (eg the top 10% most popular routes in teh guide)
- A combination of the above with a target or threshold of x premium listings per page

**Comment by brendanheywood** [comment]
Won't do, see https://github.com/theCrag/website/issues/3087
