### ISSUE TITLE
Add repeat tick type

### ISSUE THREAD

**Issue by scd** [theCrag/website#1259]
Pros:
- better stats? (we could auto downgrade repeated onsight / redpoint into 'clean' for purpose of stats, or warn / error when trying to log these)

Cons:
- more complexity, more ways people can get it wrong
- what about repeat dog, repeat top rope, repeat solo?

See also 'breaking these into flags' #1217

**Comment by brendanheywood** [comment]
I'm closing this as "won't do". It's pretty low value and obfuscates things for cpr, and what the repeat tick type was etc. Feel free to reopen if anyone disagrees
