### ISSUE TITLE
Make FA one line and inline with route when no other text is present and FA is short, and screen is big

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1262]
> The rest of my activities actually went without a glitch, despite messing around quite a bit and doing the bulk of it during the update. But there are some things that do bug me a bit. One is with the display of RS/FA in list of routes when that is the only additional information offered. There is a LOT white space showing:

![image](https://f.cloud.github.com/assets/187449/1319761/7d486db6-3312-11e3-8578-b6af0e4ef63e.png)

> It does look much more sensible and nicer when description is entered. Optimally I see RS/FA in line with route name and grade when

Yeah I agonised a lot over this one. There are always a lot of weird cases we'd got to handle - I like your idea of making it one line in some cases, but not all cases, eg some routes have 3 lines of FA text. I'd figure out some hybrid solution:

**Comment by Mdemaillard** [comment]
at least on desktop there can be optimization on the use of the 2 columns. I don't see a consistent logic here:
Is the 2nd column used if more than 3 or 4 lines? If less than that limit, it might be better to use full width

![image](https://user-images.githubusercontent.com/60388146/76296826-7e921580-62bf-11ea-8cd3-c46e6454f697.png)

![image](https://user-images.githubusercontent.com/60388146/76297152-0415c580-62c0-11ea-9c79-c1b8784478a7.png)

![image](https://user-images.githubusercontent.com/60388146/76297198-1b54b300-62c0-11ea-9400-6511386ce889.png)

![image](https://user-images.githubusercontent.com/60388146/76297223-2b6c9280-62c0-11ea-898b-b880ef58df3f.png)

**Comment by lordyavin** [comment]
Area label?

**Comment by Mdemaillard** [comment]
We need a new label Area:Display/Layout. I'll use it on a few other issues as well.
I don't have rights to do that.

**Comment by scd** [comment]
I have added the label

**Comment by Mdemaillard** [comment]
closing in profit of #3713
