### ISSUE TITLE
Link from mobile web to mobile app

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1267]
browser sniff, looking smart banner style JS, or full page splash pages

Need to nut out some business logic of when and how often it is shown. Are dismissals permanent, are they stored in session or account settings? both?

From @adam-g-pullen 

![screenshot_2013-09-16-08-51-45](https://f.cloud.github.com/assets/187449/1329958/ac325376-351f-11e3-9987-0e98cfe5ec04.png)

![screenshot_2013-09-16-08-50-54](https://f.cloud.github.com/assets/187449/1329960/c01937f6-351f-11e3-9c9d-8da2b62ba0b8.png)

**Comment by rouletout** [comment]
obsolete, closing
