### ISSUE TITLE
Periodic onboarding or 'did you know' emails

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1272]
I've been thinking about onboarding for a while, and some idea's I've had overlap slightly with #1196 for the signup and donate emails. Some emails like the discussions notifications should be independent but I'd say that most emails should be managed more holistically.

Principals:
- people get semi regular emails to keep them involved even if they aren't into any discussions, have no followers etc
- emails are timely, in that they learn new stuff as they need to, and don't get overwhelmed
- many features are never discovered, they need to be progressively exposed

What I have in mind:
- a set of triggers which are prioritized. So a trigger may be 'signed up more than a month ago' and have a priority of 100, or 'has not ticked any routes in 3 months' priority 50, 'signed up 3 months ago, but have logged in since, but haven't ticked 10 routes'
- each trigger has a version number and some template text as usual
- Once a month or fortnight for each person we see what triggers match for that person, pick the top one off the list and then send it out. 
- triggers can be single use or have a repeat period

So the we could easily knock up 5-6 onboarding emails with progressive more involved stuff. And what emails they get adapts so some emails may never be triggered ie 'signed up 3 months ago, but have logged in since, but haven't ticked 10 routes' may never trigger. If they haven't edited anything after 6 months we can encourage that. If they have edited topos then we can send out power tips on making topos. If not then we sent a beginner topo guide.

The big thing for me is transparency. If we develop this we need to be able to as an admin click on anyone and see what we've sent them and what we will next send. And have a page which shows a dry run of all the next emails to be queued.

And if we add a new feature, we just add a new trigger. Existing users who are maxed out of triggers will get the email next time, new users will get it in 10 emails when it is useful to them.

Almost all the content could / should be the same as the help articles. Would be good to write them carefully to work in both contexts and combine them. Also highlights the need to go back and update / curate the help pages, some are very crusty.

**Comment by Mdemaillard** [comment]
See #1103 for the signup followup

**Comment by rouletout** [comment]
Covered with campaigns, content taken over to card, closing here.
