### ISSUE TITLE
star ratings- one rating per user per route?

### ISSUE THREAD

**Issue by cgome** [theCrag/website#1285]
Support email:

Hi guys, with the quality ratings system, theres a problem that if someone thinks a crap route (e.g. one they bolted!) is awesome, and cuts laps on it all the time and records it in thecrag as "megaclassic" 17 times, that outweighs 5 people who do it once and each rate it as crap and never go back. So,
1) is it possible to have "one man one vote" for the quality of each route?
2) if not then maybe a partial fix would be for the form to not autocomplete the quality field when you retick a route by recycling your rating from your previous tick. Leaving it blank (or greying it out?!) might encourage people to simply not rate the route the second time they record a tick and skew the average...
cheers

**Comment by brendanheywood** [comment]
Just a random thought I had from seeing this widget on buzzfeed for voting on articles:

![image](https://cloud.githubusercontent.com/assets/187449/6500485/63a94990-c360-11e4-8f5d-856012d7ed2c.png)

Made me think that if we are going to decouple the vote from the ascent to make it one vote per person, would be be simpler if we also allowed votes without an ascent? If you log an ascent it would still show your last vote and you can set it again.

Also a counter example to the decoupling idea, some time I climb something in terrible conditions like it was wet or whatever, but I might repeat it later and give it a different vote. Should only my last vote be kept for the stats but we still keep the vote for each ascent?

**Comment by scd** [comment]
If you have not climbed it should you be able to vote?

If you have climbed it then why not log an ascent as well? 

Tying the voting to logging an ascent improves the data quality IMO. Also it encourages somebody to engage in the ticking process.

Maybe we can promote voting more in the index pages as a feed into logging ascents. 

Another example against decoupling. When I first start climbing I do a route and love it - mega classic. After years of climbing climbing awesome routes I come back to the original route, and find it a bit ordinary. Both those votes have value and are telling us something.

**Comment by brendanheywood** [comment]
> If you have not climbed it should you be able to vote?

There is also something to be said for rating a route that you haven't yet climbed, which overlaps a little with the wishlist stuff I guess.

> Tying the voting to logging an ascent improves the data quality IMO. Also it encourages somebody to engage in the ticking process.

yeah but this is a little self referential, the reason we want people to log, is so they provide ratings so we know what's good or not. So we can't say we don't want to have direct ratings as it won't improve the data quality.

So I think if we leave it as is, but make the stats only use the last rating then that solves the 1-vote issue.

**Comment by Drazhar** [comment]
I'm also the opinion, that there should only be one rating per person. Shouldn't it be easy to just take the rating of one ascent into the statistic?

For example always the newest ascent rating of a person is taken into account.

**Comment by brendanheywood** [comment]
Fixed in #560
