### ISSUE TITLE
More over zealous route autolinking

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1286]
Just in one discussion 3 bad links:

https://www.thecrag.com/discussion/387319842/bolting---data-base#m388052091

![image](https://f.cloud.github.com/assets/187449/1470435/8fdd1ed0-45ba-11e3-99aa-1c38f302273e.png)

'So' and 'The' I think are clear blacklist words. 'BM' I'm not so sure about as it could be a valid acronym and is all uppercase. In this case BM is actually the name of the route so could be seen as just a data issue not a code issue.

**Comment by scd** [comment]
I have blacklisted the following words

  * It
  * So
  * The
  * An

There is now a variable for this in the Markdown.pm file. Do we want to close this issue and add new black list words as they come up or be more proactive. I think we should just close and move on

**Comment by brendanheywood** [comment]
Nah that's good, now that it's in place it's trivial to add more as they crop up
