### ISSUE TITLE
Routes and unlocated areas don't link properly in maps tab

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1287]
Map tab is broken for route AND any areas that don't have locations. They are the same root cause,

eg go here:

https://www.thecrag.com/climbing/australia/shady-buttress-closed

Then click on the maps tab, and you end up at the world level instead of the 'scenic rim'

http://www.thecrag.com/maps/australia/shady-buttress-closed

http://www.thecrag.com/maps/australia/queensland/route/298873584

I think in both cases the 'startingNode' data should instead of a 'geometry' attribute get an 'inheritedGeometry', or maybe the whole startingNode should just be the nearest located ancestor. I prefer the first as in the second even though the map will be wrong you could still click to another tab and have it work with out booting you to the parent node.

There is a few other nested bugs too, even a raw route that is located doesn't get it's geometry returned in the 'staringNode':

http://www.thecrag.com/maps/australia/stonehenge/route/26956362

**Comment by scd** [comment]
This was a quick fix and just required hooking up inheritedGeometry in the node. The info was already there it was just a matter of standardizing how it is found.
