### ISSUE TITLE
Occasional Facebook tick logging locking up application daemon

### ISSUE THREAD

**Issue by scd** [theCrag/website#1297]
This has happened once since the first major release.

Cut to the chase: I am guessing that there is something in the Facebook ascent logging post that causes Facebook POST to timeout which is not handled properly by the daemon event handler. The daemon event handler uses POE framework, which I have found needs special care when interacting with files and external sockets. Solution:
- [ ] Check for a special POE handler for url calls
- [ ] Fork Facebook logging
- [ ] Do the same for Google Analytics API logging (although that just seems to work and is less fickle than Facebook).

Symptoms of this happening. The daily report will show the Callback queue building up, because the daemon has locked up. Short term solution is to just remove the next item in the Facebook publishing queue (Simon has to do this).

**Comment by rouletout** [comment]
This has been disabled - closing
