### ISSUE TITLE
Don't show lat long on route page if too inaccurate

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1304]
Ie in an unlocated crag it inherits upto queensland and shows the lat long for the centroid of qld:

Location:  
Located in Queensland approx:
Long/Lat: 144.659069,-20.977083

We should set some threshold (maybe 1km?) and if the bbox is greater than that hide it.

**Comment by rouletout** [comment]
Covered using the "fixing bad locations" script. Closing.
