### ISSUE TITLE
Tick height isn't calculating correct height with pitches + route data inheriting into ticks when changed

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1313]
Two scenarios:
- [x] IF a climb has multiple pitches, AND that route has got all pitches heights correctly entered, and you tick it but only log certain pitches, then the total height should be calculated correctly.
- [x] Maybe we also want to allow people to override the pitch heights, or ascent height if they did something weird like an alternate, or bailed or whatever. 

So I'm thinking we show a couple new height fields into the 'pitches' advanced section which default to the pitch height, or if it's missing they can be filled out.

![image](https://f.cloud.github.com/assets/187449/1867872/0835f082-785b-11e3-9c56-a2e056a318e4.png)
- [x] Also in a similar vein, we potentially know the grades of each pitch, but these aren't filled out as the default in the pitches either
- [ ] I didn't mockit up, but there should probably be a hidden height total that keeps tally as you change stuff and add/remove pitches (only shown if more than one pitch)
- [ ] I think this is mostly a multi pitch edge case, so not sure whether we bother with a height override for ticks without pitches. We could leave it under the 'pitches' toggle and you could still fill it out for single pitch climbs. In fact I kinda like extending this a little and turning 'pitches' into a sort of 'advanced' ticking page and then we can hide other stuff in there that's not common and is a little cluttered.

Raised by:
https://www.thecrag.com/ascents/by/maelgwn/
who ticked
https://www.thecrag.com/climbing/australia/arapiles/tiger-wall-area/route/12909985

**Comment by tomkjaerolsen** [comment]
*Bump* :)

What about to write a new issue, but this one pretty much covers it. 

Maintenance works would be super useful.

**Comment by brendanheywood** [comment]
Yeah this issue covers a whole bunch of stuff and needs to get broken up.

* This issue will remain as just the initial bug around heights not being calculated, and possibly also duplicating the route height into the ascent data
* Physical route history / maintenance is split off into: #1865

@tomkjaerolsen which issue were you actually referring to?

**Comment by tomkjaerolsen** [comment]
I was referring to what you put in #1865, maintenance works, bolt loose, tightened, anchor replaced etc.

**Comment by brendanheywood** [comment]
+1 again from another support email

**Comment by scd** [comment]
I have done the ascent logging part of this issue in my dev. When you log an ascent you now have the option of using the height of the route, or setting a specific height for your ascent. Note that if you use the height of the route then this will change in the future if the route height is updated.

![tc-tick-height-use-route](https://user-images.githubusercontent.com/373058/32202118-a2dd8a2e-be2e-11e7-8a78-314c996a70c4.png)

If you want to add your own height then deselect 'Use route length' and enter the height. If the height is not postfixed with either 'm' or 'ft' it is assumed to be meters.

![tc-tick-height-set](https://user-images.githubusercontent.com/373058/32202171-f116da9c-be2e-11e7-93a8-cf64e2834211.png)

This can also be set at a pitch basis. Opening pitch logging will automatically pre-populate the pitches with the height the system thinks is in each pitch (and also the grade). The height comes from setting the route height text to comma separated string for each pitch. 

![tc-tick-height-pitch](https://user-images.githubusercontent.com/373058/32202209-3dd8c462-be2f-11e7-9f7e-6d02ebbe273f.png)

Setting pitch heights overrides ascent height settings. If you don't set any pitch heights then the the ascent height settings are applied.

Finally I have updated the way pitches are displayed in the stream.

![tc-tick-height-show](https://user-images.githubusercontent.com/373058/32202247-73d815b8-be2f-11e7-9e95-dfc837e8819b.png)

**Comment by scd** [comment]
In Simon's dev I have fixed the core issue of being able to log explicit ascent heights if different from the route itself and to be able to do it on a per pitch basis.

All the other stuff should be in other issues.

Closing.

**Comment by brendanheywood** [comment]
This is great :)

* [ ] there is no relation with the 'lead by' and 'mentioned'. If you mention someone in the 'lead by' then they should auto be added to the 'with' box at the route level.

![image](https://user-images.githubusercontent.com/187449/32220875-6d98a2dc-be87-11e7-8ec1-624a135f8a6e.png)

* [ ] I was thinking maybe making the 'lead by' dropdown show a new section just on this page "with" which just merges in those who are already either in 'with' field so it's faster to add the same person again

**Comment by brendanheywood** [comment]
I've split that last one into https://github.com/theCrag/website/issues/2940
