### ISSUE TITLE
Multi pitch routes don't display pitch heights

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1314]
An easy low hanging fruit.

ie Skylark has correct pitch heights for each pitch, but this doesn't get displayed anywhere and isn't even in the template data. 

Mockup:
![image](https://f.cloud.github.com/assets/187449/1867962/a4f02f8a-785d-11e3-9fba-677b9928ec88.png)

**Comment by scd** [comment]
this is done on simons dev
