### ISSUE TITLE
Forum count in header needs tuning

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1315]
It looks like it's the # of threads which have unread messages, rather than the # of unread messages in those threads. I think the latter is what most people would expect? 

I can't see any performance difference between the two?

**Comment by Mdemaillard** [comment]
Forum header shows x of y messages read per discussion - implemented
![image](https://user-images.githubusercontent.com/60388146/76361031-ce57f780-6326-11ea-8baa-1a00f9099985.png)

Dashboard Orange pop up shows quantity of (watched / followed ?) discussions that are not (fully) read, e.g. 1 could have many unread messages.

closing
