### ISSUE TITLE
Prod bug with cache

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1322]
A once-off bug I just saw:

Apache Module Load Portal Error: Error: cannot flock files/database/persistance.cache.lock.file: Interrupted system call at /opt/CIDS/perllib/CIDS/Application/MyCache.pm line 191.

**Comment by Mdemaillard** [comment]
is this still relevant or can we close that ? i suppose since 2014 a lot has changed @brendanheywood  @scd
