### ISSUE TITLE
Deep link into ticking page from 3rd party external page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1323]
Just a _very_ high level thought. Jon Nermut has just released the latest version of thesarvo iPhone app and I just had a brief exchange about adding ticking to it using thecrag. Thinking it through the most painless way for this to work is for him to just link into the tick process, he just passes a list of id's for the routes, constructs a url and loads it in a webview and then the rest is on our side. Very similar to say how a 'mailto:blah@example.com' email link would open in gmail web app, or you link into a facebook share page.

Things needed for this to work:
- [ ] we store mapping from thesarvo id's to thecrag id's, similar to ACA mapping etc
- [ ] webview in app configured to remember cookies across sessions
- [ ] extend processmap to allow saying 'these id's are from thesarvo not local'
- [ ] after tick just shows logbook

The beauty of this is someone like Jon could add ticking to their app in a handful of lines of code and a couple hours and very little effort. On our side it seems like very little effort as well on top of work that we are already planning to do at some point.

Only downside, which is big, is that it would require network when the webview is fired, vs storing all the tick data locally and using the api.

**Comment by scd** [comment]
Nobody is currently asking for this, so closing
