### ISSUE TITLE
Forum routing issue with /forum

### ISSUE THREAD

**Issue by martinunger** [theCrag/website#1330]
Hello!

When I try to view the forum history, I get the following error message:
`Apache Module Load Portal Error: not a forum`

Steps to reproduce:
0.) Firefox 19. Login.
1.) Click Chat.
2.) Click 2.

Cheers
Martin

**Comment by Mdemaillard** [comment]
Can't reproduce.
the profilepage doesnt have a chat button. The "create new discussion" does work.
the Forum button does work

one in forum, there is no history button either, the various links do work
Closing
