### ISSUE TITLE
Playing around with site article responsive design

### ISSUE THREAD

**Issue by scd** [theCrag/website#1341]
Brendan, could you please pull from repo and install. Once done please let us know so we can discuss this particular article which I have been mucking around with.

http://dev.thecrag.com/article/EntryLevelSponsorship

I know that you have made some articles responsive, but I think we need to standardize. In particular:
- [ ] improve typography
- [ ] single column by default
- [ ] standardise headers
- [ ] use div to differentiate between article title and article body
- [ ] standarise bootstrap responsive integration

There are heaps of other things to discuss with articles, but I just want to get them looking better for our gym release.

All my trial classes for this have labels something like '.sd-something'. At some point we will ditch these and replace them with standard classes.

I only want to use my classes on specific articles so, I have hacked the Portal/WebPrimaryContent.pm to insert some custom inline css for particular help files. This is not the right way to do it, but problems with my dev versions means it is painful creating and installing css files. This is a temporary solution only.

**Comment by brendanheywood** [comment]
This has been responsive now for ages so closing
