### ISSUE TITLE
photo uploading for forums and articles

### ISSUE THREAD

**Issue by scd** [theCrag/website#1344]
From Brendan...

We already have photo uploading process working, it should just be a matter of smoothing the UI out. ie if someone drags a photo onto a markdown textarea, in the background it uploads it using the existing photo upload code, which publishes it at a url, and then it pastes that url into the markdown. Then when your save, or preview, the markdown turns the url into the embedded view of it. This is exactly how github uploading works.

See this animated gif if you've never used this:
https://github.com/blog/1347-issue-attachments

The questions are:
- are we happy with pics in forums to be treated the same as a normal photo?
- do we care about metadata as much, ie we can attach the node to the photo which is the same node as the forum node
- should pics in forums end up in the photos section? sometimes this might be weird but in most cases I think it makes sense
- if we care about metadata, eg who is climbing in the pic, we can optionally capture that as a modal popup when they are uploading

This will make previewing a post when authoring more important, which is already on the todo list.

**Comment by brendanheywood** [comment]
This has already been done
