### ISSUE TITLE
improve select all useability for reparenting

### ISSUE THREAD

**Issue by scd** [theCrag/website#1350]
Feedback from user:

Another little usability thing -- if I'm re-parenting most, but not all, of the children of a particular node I'll get a page with a "select all children" tick box at the top, then individual tick-boxes for each child.  It would be nice if the "select all" would, on that page, tick all the children tick-boxes, then allow me to just un-tick one or two that I don't want.  (e.g. if I want to move all the climbs to a newly created sector of the cliff).  Or, if I click next, put up a page where they're all tick-boxed, and I can untick one or two if active-updating that page itself is annoying to code.

**Comment by Mdemaillard** [comment]
Implemented
The "select all" tick gets automatically changed to a "-" when deselecting some child

![image](https://user-images.githubusercontent.com/60388146/77013502-da703480-6978-11ea-855c-91d4b74de0c5.png)
