### ISSUE TITLE
Ghost nodes for establishing delete, reparent and merge changes from old parent

### ISSUE THREAD

**Issue by scd** [theCrag/website#1388]
When you delete (or reparent or merge) a node is removed as a child from the old parent.

If an api client wants to know all the ancestor nodes that have changed, then we need a way of telling it that there use to be a node here but it is no longer here. For example an app will need to know nodes that have been deleted, so it can delete them from it's local storage.

This is currently an issue for reparenting, deleting and merging.

If we had a single table to identify when a node became a ghost node within the index structure then this would greatly simplify the logic.

We would need a date, node, parent and reason fields.

**Comment by brendanheywood** [comment]
@scd I think you are a decent way through this one, can we close this or is there a task list we can check off progress?

**Comment by scd** [comment]
closing
