### ISSUE TITLE
Classic crags should have a minimum utility

### ISSUE THREAD

**Issue by scd** [theCrag/website#1390]
It seems as though crags with little ascents are being tagged as classic crags.

From member:

The Devil's nose is listed as a classic crag within the Mt Crawford region. How's that? The crag has 8 routes and only 7 ascents. Surely a minimum number of ascents should be required? 50? 100? 500? And the ratings people have given the climbs aren't that good (mostly average, a couple of "good")

http://www.thecrag.com/climbing/australia/mt-crawford-area

**Comment by Mdemaillard** [comment]
Looks good to me in the areas i can judge (south africa).

**Comment by Mdemaillard** [comment]
Checked on a few countries (South africa, australia, france, norway, austria...) in all cases all classic crags 

- show a high amount of ascent compared to the country ascent total, 
- and most seem (from my very partial knowledge) to be well known areas

Closing
