### ISSUE TITLE
Ascent logging page should prioritise most correct grade system

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1400]
In grade drop down all systems and grades are shown. If a route is 'trad' and its in country 'X' then we should be able to figure out which grade system is most likely and move that group to the top of the dropdown

**Comment by Mdemaillard** [comment]
the ascent form does preselects the ascent grade  when:
- the route as a single grade 
- the route as a grade and an alt. grade -> both preselected
![image](https://user-images.githubusercontent.com/60388146/77014154-50c16680-697a-11ea-94e9-d3863be38cce.png)

Now for multiple weird cases with range grades or multiple grade input, the first one is preselected
ex 
20 6b ->20
20/21 ->21
20-24 ->20
5.10a/b ->5.10a

**Comment by rouletout** [comment]
New ticking interface, closing this
