### ISSUE TITLE
grade band missing for via ferrata ascents

### ISSUE THREAD

**Issue by scd** [theCrag/website#1411]
For example here:

https://www.thecrag.com/climbing/austria/salzburg-area/area/343047684
https://www.thecrag.com/climbing/austria/salzburg-area/area/318733368
https://www.thecrag.com/climbing/austria/salzburg-area/area/319079127
- [ ] Should via ferrata have a grade band?
- [ ] via ferrata 'unknown' in style band?
- [ ] I thought I did link via ferrata to the grade band - need to confirm?
- [ ] Investigate why this is not appearing if it should appear.
- [ ] Sometimes there are bugs where ascents are changed after they have been added. I have not ruled this out yet.

Also seasonality was not appearing for one of these (318733368) - logged via the app.

**Comment by rouletout** [comment]
I see a grade band - assume this came in with the new design? Closing
