### ISSUE TITLE
Geo locations lost after merging areas / routes

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#1427]
I merged "Val Lomasona" to "Val Lomasone". I had localized the former, in the merged node the localisation seems to be lost. I acknowledge that merging geodata is not trivial, but in this case the latter had no geoinformation, so the geodata of the former should rather be preserved.

**Comment by rouletout** [comment]
This works correctly, closing

**Comment by MelwinQ** [comment]
Re-tested it in the course of testing #3550, I confirm it's working correctly.
However, if both nodes have geodata, those of the destination node will be kept.
Wouldn't it be nice to warn about conflicting data or, ideally, have the user choose which data to keep in the merged results?

**Comment by rouletout** [comment]
Yes this would be nice :-) - it is pretty well explained in the help though
