### ISSUE TITLE
Look into adding CORS headers for domain for each api key

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1430]
Low priority, will become an issue when we get more api clients in the browser vs server to server

**Comment by quaestor** [comment]
This is a blocker for me currently; I am writing an API client with a web frontend and I cannot use any POST requests.

**Comment by quaestor** [comment]
I have a workaround now using a CORS proxy, but had to implement OAuth myself because the Javascript node implementation doesn't support adding a proxy.

**Comment by rouletout** [comment]
Will not be done, closing
