### ISSUE TITLE
Instant Karma processing time for supporters

### ISSUE THREAD

**Issue by scd** [theCrag/website#1437]
I think we still get a few queries about how long it takes to process karma. 

I would be comfortable to reduce the time lag from 8 days to 3 or 4 days. This would still achieve the anti-gaming objectives.

**Comment by scd** [comment]
If we make this a premium feature we should also 

 - [ ] reference the premium benefits in an article
 - [ ] update the donate url to sponsor
 - [ ] add the benefits to the donate page

**Comment by lordyavin** [comment]
Is "premium" different than "supporter"?

**Comment by scd** [comment]
No.

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by lordyavin** [comment]
So why using different terms?

**Comment by scd** [comment]
No reason in particular, I am just doing too many things at once and have
not taken care in my use of language. The language should be 'supporter'. I
want to move away from the language of 'donate' though.

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by scd** [comment]
Instant karma for supporters is done in simon's dev

![screenshot from 2018-03-27 17-03-56](https://user-images.githubusercontent.com/373058/37949675-5410dd98-31e1-11e8-845d-c5a7e5c0a13f.png)

![screenshot from 2018-03-27 17-05-50](https://user-images.githubusercontent.com/373058/37949678-5b029b50-31e1-11e8-96a5-7b5549e0e20b.png)
