### ISSUE TITLE
add tick process should encourage data entry

### ISSUE THREAD

**Issue by cgome** [theCrag/website#144]
add tick process should encourage data entry

eg either an expanded screen or a prompt 'can you add/confirm some details for this route'

FIrst priority is to fill gaps in the data

Second might be to get verification- eg a thumbs up / thumbs down against each field. Once you get x (3-5?) thumbs up you consider it verified and stop asking. If you get a thumbs down it prompts you to either edit the data or give specific comments that can then be reviewed by an editor/area coordinator

**Comment by brendanheywood** [comment]
Closed done, or closed not doing?

**Comment by scd** [comment]
Accidental need to reopen

**Comment by Mdemaillard** [comment]
+1. I would see priority Route type. There should never be an ascent on a route without gear style.
Then possibly # draws and length

**Comment by rouletout** [comment]
Covered using campaigns to encourage users to add info if they ticked in an area where info is missing. Closing.
