### ISSUE TITLE
Transparency about forum subscriptions / watching / leave / unsubscribe

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1449]
That email from cameron made me remember that that settings page about what forums you see. It's probably our number one complaint at the moment that people are getting too much forum traffic. I realised a couple things:

1) We have fav'ed Aus / world etc or other stuff up high so we see most things. As a result we don't really see issues around the forums like a normal user would

2) I'd completely forgotten that we show forums for places where you have climbed. In hind site that may not be a great default

3) There is no indication in any place I can find that you are subscribed to a crag when it is because you are an editor there, or have climbed there. ie I just tested in dev a post to Krabi which I have not fav'ed but have climbed. I got a note in my dashboard. But on the discussion page it says:
![image](https://cloud.githubusercontent.com/assets/187449/2870146/a38e69f6-d2b0-11e3-8a02-6c21e7ddf22f.png)

I think this is the guts of the issue that everyone mentions - ascent based forum subscriptions
- [x] when showing a list of forums in your dashboard, give a reason for why you see it, ie 'You see this because you have fav'ed Arap', 'You are subscribed to Grampians', 'You commented on this discussion', 'You manually watched this discussion'.
- [ ] Mark as read (present but not ajax)
- [ ] Unsubscribe from this discussion (see #783 github style discussion watching)
- [x] If manual: Unsubscribe from all message in XYZ
- [x] Turn off all notifications of message in fav|editor|ascent crags, this would be retrospective
- [ ] when you visit a particular discussion get the exact same message
- [ ] when you visit a forum page in a place where you are an editor or have climbed AND you have the editor or ascents tickbox checked in the dashboard settings page then it should show that. ie have the ability to edit subscription for this area inline and link off to settings for global defaults
- [ ] on the flip side if you are looking at a thread you should clearly see who is involved, and who is watching. But if someone has posted and then left we should see this too. @ mentions of these people in the forum should not re-add them.

**Comment by lordyavin** [comment]
+1 to get more infos why i get notifications.

**Comment by jedparkes** [comment]
I would not like to get to get any notification unless i subscribe to them
ATM i blankly ignore all notifications because they are just from random ascents i have logged.

**Comment by brendanheywood** [comment]
Just split the smaller and critical bug part of this off into #2452

**Comment by brendanheywood** [comment]
+1 from Paul via support query

**Comment by brendanheywood** [comment]
I think we should break this issue apart and simply removing the join to crag you have climbed at. This should be a very minor change and fix most of the 95% of the issues people are having. Then we can worry about turning this back into a user setting later.

**Comment by scd** [comment]
Hmm, don't know about this. We will effectively be turning off forums on the dashboard for most people. My preference is not to do anything until I can find the time to do it properly.

**Comment by brendanheywood** [comment]
+1 via https://github.com/theCrag/website/issues/3187

**Comment by brendanheywood** [comment]
+1 via https://www.thecrag.com/discussion/1886382390

**Comment by brendanheywood** [comment]
+1 from facebook support

**Comment by brendanheywood** [comment]
+1 from https://github.com/theCrag/website/issues/3232

**What happened?**

An favourited area shows the following forum info box (see screenshot)
<img width="383" alt="screen shot 2018-08-10 at 12 18 32" src="https://user-images.githubusercontent.com/19162952/43952958-bf0928a0-9c97-11e8-87db-b0f81704343f.png">


https://brendan.thecrag.com/climbing/united-states/idaho/area/1275465462/forum/?lang=yy


Ideally also provide screenshots:


**What you expected:**

Expect the lower part without button if it is favourited and thus I'm subscribed or the upper part of the message with the button if not.

**Comment by brendanheywood** [comment]
fyi the bulk of this is done for the next release, we have remove the confusing auto-subscriptions based on ticking and editing which was the main issue but also fixed a bunch of other stuff. Most of this is at the forum level, there is still more transparency work to be done at the thread level but that will be a later release.

**Comment by jedparkes** [comment]
Awesome, been waiting for this fix for a long time, thanks !
