### ISSUE TITLE
Error message when registering grade to route

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#1450]
I bulk-added some routes an forgot to set the grade for one (http://www.thecrag.com/climbing/italy/northern-italy/arco-trento-area/route/455233899)
I tried to add the grade afterward and got:

Software error:

DBD::mysql::st execute failed: Deadlock found when trying to get lock; try restarting transaction at /opt/CIDS/perllib/BSIS/Db.pm line 1213.

For help, please send mail to the webmaster (scd@thecrag.com), giving this error message and the time and date of the error. 

However, the grade seems to have been correctly registered.

**Comment by rouletout** [comment]
Closing until it comes up again (if it comes up).
