### ISSUE TITLE
Tag negation

### ISSUE THREAD

**Issue by scd** [theCrag/website#1451]
From user:

Some nitpicking: If a crag has parts that receive sun all day, and others that don't, should I still tag it as "all day sun"? From my point this would make sense, so a crag can have the tags "all day sun" and "always shady" at the same time. Perhaps this could somehow be clarified in the tagging docu. Inheritance generally makes sense to me. However, it would be great it inherited tags would be graphically distinguished (I know, hovering or when editing makes it clear), but if inherited tags would be displayed somewhat smaller, grey, or in quotes it would make things clearer. Especially in the abovementioned context this makes sense: I tagged a crag with some walk-off routes as "walk off". Now all routes inherited this tag, which may lead to a wrong conclusion when just looking at single routes.

New tag proposition: - Shade at base (as before, I'd argue for "yes" and "no" to distinguish missing information from negation)

**Comment by brendanheywood** [comment]
Closing as dup of https://github.com/theCrag/website/issues/1714
