### ISSUE TITLE
Some route additions not showing up for me in 'Recent Updates'

### ISSUE THREAD

**Issue by oliverstory** [theCrag/website#1452]
See, for example, 'Fish in a Barrel' at Safari Boulders, added after 6 April but not showing in Recent Updates: http://www.thecrag.com/climbing/australia/gibraltar-peak-and-corin-road-crags/area/12281893

Also 'Trojan' at Trojan Wall: http://www.thecrag.com/climbing/australia/orroral-ridge/trojan-wall

However my own additions seem to show up, at least for me - e.g. 'The First Echidna': http://www.thecrag.com/climbing/australia/gibraltar-peak-and-corin-road-crags/area/12281869

**Comment by brendanheywood** [comment]
@oliverstory have you seen this since? Can I close this?
