### ISSUE TITLE
Private logbooks should show that they are private

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1460]
eg a private profile like:
https://www.thecrag.com/climber/prinzz

links to:
https://www.thecrag.com/ascents/by/prinzz/
- [ ] the link should not exist (for non friends), as the link doesn't work
- [ ] the link should show no ascents, and a message saying this account is private, instead of showing the world ascents

**Comment by Mdemaillard** [comment]
Currently doe show no ascent, but no hint that the account is Private. So i am not sure if it was implemented, or the account has no ascent at all.

![image](https://user-images.githubusercontent.com/60388146/76310384-5f06e700-62d7-11ea-86d4-5321f64df95d.png)

**Comment by lordyavin** [comment]
+1 for closing
