### ISSUE TITLE
Photo cannot be deleted

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#1462]
I cannot delete the photo
http://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3APushReturnURL=%2F457360002&C%3AState=16159&D%3APhotoID=457360002&C%3AHideNavigation=1
For all other photos I uploaded I get some buttons on the bottom of the screen offering me (among other things)  to delete the photo. In this case, I only get the buttons "cancel" and "disable photo".
PS: The photo is OK, it does not need to be deleted.

**Comment by Mdemaillard** [comment]
Did you come around that one already ? 
(apologies if my currently rather frequents comments generate mails that bug people, i'm targeting old small matters which might have been done already but not closed)
