### ISSUE TITLE
UTF8 characters not working for facebook publishing

### ISSUE THREAD

**Issue by scd** [theCrag/website#1472]
Jed logged a task in issue #1438 

Notes for self, on escaping problem
Jed's ascent: http://www.thecrag.com/climbing/australia/arapiles/the-pharos/route/12919327/ascents/by/jedparkes/

First place to look for this problem is the initial post to Facebook. If UTF8 characters are not handled properly in perl then this could cause the problem.

**Comment by Mdemaillard** [comment]
how can we test that since UTF8 encoding was updated recently ?

**Comment by rouletout** [comment]
Facebook publishing is off - closing
