### ISSUE TITLE
YDS_ALT 5.10 possibly in wrong range

### ISSUE THREAD

**Issue by scd** [theCrag/website#1481]
From user. 

YDS_ALT has grades in the range 5.10-, 5.10, 5.10+ as opposed to standard YDS which does grades as 5.10a, 5.10b, 5.10c, 5.10d.  So, a YDS_ALT grade of 5.10 would be somewhere in the 5.10b - 5.10c range, and at least as hard as any 5.10b.  But, if I create a climb grades as 5.10, it is grade-banded as Intermediate (yellow), while a 5.10b climb is grade-banded as Experienced (orange).   I don't think that is correct

Simon Comment

Need to work out whether it is a config issue or a conversion issue. I am pretty sure it is a conversion issue. The 5.10 would span across both Intermediate and Experienced ranges. The conversion would pick the lower end of the ranges.

**Comment by brendanheywood** [comment]
@scd was this sorted a while back with the cpr mid point logic?

**Comment by scd** [comment]
Yes
