### ISSUE TITLE
Forum discussion badges should have a color for private and public.

### ISSUE THREAD

**Issue by scd** [theCrag/website#1488]
The forum discussion badges - 4/5 and 5, should have a different color for public and private forums. 

I really like the idea of our discussions being a mixture of public and private, but we should make sure it is branded clearly.

**Comment by brendanheywood** [comment]
Just read this and love the look of it 

https://m.signalvnoise.com/launch-a-brand-new-way-to-work-with-clients-in-basecamp-3-6a78b1175c5d?source=rss----668e14b18fb1---4

**Comment by brendanheywood** [comment]
done
