### ISSUE TITLE
Mark as read / mark all as read button should update forum count in header

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1495]
Just a nicety, update and/or potentially remove the orange number top right. Could be 'blind' and just decrement the count, or the mark as read api call could return the new count

**Comment by DaneEvans** [comment]
The "mark all as read" seems to have disappeared recently, was this deliberate or a bug?

**Comment by brendanheywood** [comment]
No that's a regression, I'm fixing that now

**Comment by brendanheywood** [comment]
![image](https://user-images.githubusercontent.com/187449/45939986-bbaa0f80-c019-11e8-8eca-2699693f3b84.png)
