### ISSUE TITLE
swatch gym ascent class should be implemented across the site

### ISSUE THREAD

**Issue by scd** [theCrag/website#1499]
- [x] swatch colors implemented in gyms
- [x] swatch color grade displayed in log ascent form
- [x] swatch color should override route grade band color in logbook
- [x] swatch color should override route grade band color in ascent & activity feeds
- [x] separate field for swatch color
- [x] input swatch color when creating routes
- [x] input swatch color when editing single route
- [x] input swatch color for bulk edit
- [x] update css so swatch colors work for logbook and feeds
- [x] javascript for helping select valid swatch colors
- [x] expand swatches to images and more complex backgrounds.
- [x] fix swatches here https://www.thecrag.com/climbing/germany/oberbayern/area/612795555/ascents

**Comment by brendanheywood** [comment]
So follow on thoughts from #2406 re internationalization of these. I think the end game here is that we can  setup a 'palette' of colors at any node (or maybe only TLC's) and it is this palette of swatches which provides the mapping from local names to the raw css colours. We would provide a default swatch at the world node which has a set of 20ish common colors like what we have now, and the color names would be localized. Then a gym could setup their own swatch to override this, which would also allow dual color etc. Ideally we do this in one step but we could break into two steps, but if we do that it means that we'd only be supporting named colors and people could no longer use rgb codes like #125690 in the mean time.

**Comment by brendanheywood** [comment]
This has partially been done, we just need to fix the display of routes in the facets:

This has colours:
https://www.thecrag.com/climbing/germany/oberbayern/area/612795555

but these do not and should:

https://www.thecrag.com/climbing/germany/oberbayern/area/400652121/routes
https://www.thecrag.com/climbing/germany/oberbayern/area/400652121/ascents

**Comment by brendanheywood** [comment]
done closing

![image](https://cloud.githubusercontent.com/assets/187449/25730223/32da0d48-317e-11e7-8744-4fd1326a748f.png)

**Comment by brendanheywood** [comment]
Reopening, as missing from here:

https://dev.thecrag.com/climbing/germany/oberbayern/area/400652121/ascents

**Comment by brendanheywood** [comment]
Just fixed the last missing bit here
