### ISSUE TITLE
ascent logging grades when route does not have a grade

### ISSUE THREAD

**Issue by scd** [theCrag/website#1500]
How should we handle the rather long list of grades when route does not have a grade in the ascent logging process.

Ideas:
- similar to #color in the route description, we could use #ewbanks 
- try and work this out by using the grade context and gear style of route- This will not be definitive.

I like the #ewbanks, because it is only really a concern for gyms and for routes without a grade.

**Comment by Mdemaillard** [comment]
closely linked to #1400

**Comment by scd** [comment]
This is resolved in the new tick flow release
