### ISSUE TITLE
Default tick list should be union of tick types in other tick drop downs

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1508]
ie if there are 3 ascents in logascents, and all are top rope in gym, then default tick list should be the same list as the top rope list.

As is the default list is an easy way to circumvent the tick type, ie to 'lead' a 'top rope'

Rather that just fix this issue, I reckon we should also go a bi further and go through each gear type and filter the ticks types to just the ones that make sense for ticking outside of the gym context.

**Comment by Mdemaillard** [comment]
Better covered in #3158 
Closing this one
