### ISSUE TITLE
Responsive ticking round 2

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1509]
More to document what I've just done than a todo list:
- [x] lots of layout tweaks so the fields stack better on small screens, ie one big field, then two smalls fields, then one big field, so can stack 2+1, 1+2 or 2, 1+1, 2
- [x] removed a lot more stuff in gyms: partial dates (don't need historical ascents in a gym), removed the ascent label (repeated and never gets changed like for multipitch or linkups)
- [ ] I'd like to filter the grades in gyms to just the grade system that is registered for a country, eg ewbanks - suggestions on best way to do this?
- [x] because vastly less fields in gyms, turn quality into radio because this is more important here, also made radio.

**Comment by brendanheywood** [comment]
More tweaks:

* [ ] The comment field changes width as you type which moves the Tick Type input over, I think we should either make the comments fixed width or swap the position so the tick type is to the left and doesn'tmove

* [ ] I think we should set the widths better on the 'who' tags for the pitch ticking so that the columns stay lined up (eg Berna pushes the first pitch to the right

* [ ] I think we should line the - and + buttons up correctly.

* [ ] All the pitch inputs should be vertically aligned to each other

* [ ] We should really fix the bug where it incorrectly copies the total route length into the first pitch https://github.com/theCrag/website/issues/3147

**Comment by Mdemaillard** [comment]
Last 3 boxes are ticked already. 
1st one open, 2nd one i don't understand.

![image](https://user-images.githubusercontent.com/60388146/76689001-b50ebe00-663a-11ea-8699-c4467717e53d.png)

**Comment by rouletout** [comment]
New ticking interface, closing this
