### ISSUE TITLE
Quality rating in gym's

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1510]
I would like to make rating quality in gyms really easy, the obvious candidate is a star rating system instead of the 7 word based ratings. I don't see this as a hard challenge as the rating of gym routes don't need to correlate in any way at all to the ratings of routes outside - I don't want to touch anything outside of gyms.

The 7 word based rating gets mapped in some way into a 3 star system, so if we went with a 3 star system then this mapping should be well understood and we can just use it directly without the mapping.

But if we go down the more normal 5 star rating system used almost everywhere, mobile apps, hotels, movies etc then I think we'd get more consistent feedback by users, especially given that gym users often are new to climbing and don't have any context of the 0-3 star system used predominantly on outside routes (at least in aus?)

I've just had a look into the scores in the DB and I think the 5 star rating system would actually fit exactly over the 7 words one but with 'average' and 'very good' removed:

```
 -10 Crap          *
  -5 Don't bother  **
   0 Good          ***
   5 Classic       ****
  10 Mega classic  *****
```

So I think implementing 5 stars would be super simple on the ticking side, and because it is just a rebrand of the existing levels with the same scores we should be able to get a combined score out using the same existing process and convert that back into a 5 star rating for display without too much work.

Another option is to simply have a thumbs up or thumbs down rating like youtube, and instead of showing an average rating you show a proportional rating, eg 72% thumbs up. This one has quite a lot of merit in the gym setting too.

Regardless of which way we go I don't think we need to over think it, as the impact is quite low as we only have one real gym, the turn over of gym routes is high, so any of kilter ratings will be not important within a month, and we can rejig the mapping easily and evolve it. Would want Chris's feedback on this

**Comment by Drazhar** [comment]
This is the topic where my question fits the most I think:

Why not change the rating system for natural also in just a star system? Most people I know are confused what word means what rating. A simple 0-3 Star would be easier. Or if this is hard to do afterwards (now), just add the star rating to the quality dropdown if you tick multiple routes. The same as they are of you log a single route. This should give the people a better understanding what quality results in what star rating.

**Comment by brendanheywood** [comment]
@Drazhar I've just done that, this is live right now:

![image](https://user-images.githubusercontent.com/187449/38931118-8358bc44-4355-11e8-9496-990451140515.png)

I think I'll close this issue completely
