### ISSUE TITLE
Skewed Popularity / one rating vote per person per route

### ISSUE THREAD

**Issue by willmonks** [theCrag/website#1511]
I was just looking thru pages pinnacle and was surprised to see some routes there have had 120+ ascents. Eg Green Room and Over the Falls (http://www.thecrag.com/climbing/australia/queensland/route/298905864). 

But upon closer inspection I see the stats are being skewed by some people logging eg 10 shots a day, on multiple days, and in fact only about 20 people have actually been on it. I think its fine if people want to record multiple laps on a single route (sometimes I do too) but IMO a route's "popularity" shouldn't really go up because someone is sieging the crap out of it (or doing training laps) and recording every lap ... it makes those 3 year old Pages Pinnacle 25s look as popular as old classic Arapiles 25s like have a good flight (129 ascents), and spasm (100 ascents) - which clearly they are not!! 

Just wondering if there's some way to "condense" multi-ticks like this ... ? maybe only count a max of one ascent per user towards the "popularity"? Or a compromise of a maximum of one ascent per user per day? 

This is a similar question to my previous suggestion of "one person one vote" towards route quality ratings, too. Cheers!

**Comment by brendanheywood** [comment]
Fixed in #560
