### ISSUE TITLE
Grade validation api endpoint

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1513]
Spec for new grade. Use cases:
- [ ] enter a free text grade, want to make sure it is valid, also want to know what system(s) and context(s) it matches under

In these examples I've tried to use real rawScores to make this clearer

```
/api/grade/lookup/au/5c
```

ie given a context 'au' and a single grade of '5c' this matches 2 grades:

```
[
 [
  {
   id: 7512034
   grade: '5c',
   band: 3,
   rawGrade: [178,185]
   system: 'FR',
   context: 'FR'
  }
 ],
 [
  {
   grade: '5c',
   band: 2,
   rawGrade: [234,267]
   system: 'UKT',
   context: 'UK'
  }
 ]
]
```

The order of the matched system reflects the priority dictated by the given context. A typical use case for this is to show these two options as an autocomplete, which sets the grade context in a form.

```
/api/grade/lookup/us/3
```

This will actually return 5 matches for systems AU, UIAA, FIN, NOR, POL

A dual grade lookup

```
/api/grade/lookup/uk/5c e6
```

```
[
 [
  {
   grade: '5c',
   band: 2,
   rawGrade: [234,267]
   system: 'UKT',
   context: 'UK'
  },
  {
   grade: 'e6',
   band: 2,
   rawGrade: [326,350]
   system: 'UK',
   context: 'UK'
  }
 ]
]
```

IMPORTANT: note that there is only 1 item in the outer array returned, because the grades  were found in the parseContext of the given gradeContext, but there are 2 items in the inner array, one for each grade part. 

```
/api/grade/lookup/au/26-28 M1
```

```
[
 [
  {
   grade: '26-28',
   partA: '26'
   partB: '28'
   band: 2,
   rawGrade: [314,350]
   system: 'AU',
   context: 'AU'
  },
  {
   grade: 'M1',
   band: 1,
   rawGrade: [34,67]
   system: 'AUAID',
   context: 'AU'
  }
 ]
]
```

I'm not fussed on the details of the json format or the query params coming in, just return the same structure that is in the api already or whatever is convenient.

**Comment by scd** [comment]
We have a grade api endpoint now
