### ISSUE TITLE
Historical pseudo accounts for FA history and guidebook people info AKA community managed profile

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1518]
A bit of a stretch goal, thinking out loud, very half baked. Almost all guide books have a section about people of interest either in the creation of the guide, or the development of the crag, or access etc.

We have a plan to link FA history to accounts, see #68 #558, but the reality is that for many older areas, and plenty of new areas, the people in the FA don't have accounts.

So when we get the nice FA linking to accounts working should be also consider the idea of creating a pseudo account which can be linked from the FA field? It could even be a real account record just with no password or email etc, and with some rules about who can edit the details.

Some things I think we'd need in order for this to work:
* [x] a flag that says an account isn't a real account, but is community managed
* [x] rules about who can make a pseudo account, probably highish levels eg coordinator
* [x] a way of claiming an account if someone joins later
* [x] a way to merge two accounts, we already have this on the list #1092 

There would also be functional differences with the real accounts:
* [x] profile page: 'member since' should be hidden
* [x] should be mention-able in FA, and markdown in beta fields, but the dropdown should clearly state that this is a pseudo account
* [ ] should not be able to be invited to forums
* [x] should be able to have a profile, but badge it in some way. eg in the hypothetical list of avatars in list view for 'area developers' as opposed to 'karma' people
* [x] their avatar should be clearly different in some way
* [ ] have fields for date of death as well as birthday
* [x] can you follow them? it would make sense to follow them so you can see updates about them as the community fills in data.
* [ ] the CPR graphs should end with the date of death.
* [x] have editor(s) for fake accounts, ie the real people who manage the info instead
* [x] figure out where emails go, if anywhere (forward to the editors?)

Ticking
* [x] Change text for community managed ascents in streams to make it clear that they climbing it, but didn't log it themselves,  "An ascent of {climberName} from the past was logged at {cragName}."

Then the bonus points goal is a way to add a chunk of text about a person, in the context of a crag, sorta like the profile blurb. This could be a new field / relation, or it could just be some more markdown extensions. Maybe something like @personsname in text would just expand into a link like a route name, but [@personsname] could expand into a profile summary card, and then you can add extra text about the person under or next to the card.

We don't really need the pseudo accounts for the guides, we can just get by with text and embedded pictures, but if we do the FA history linking with pseudo accounts then this extra step is icing on the top.

- [ ] Need to lock it down to fairly high level, maybe country coordinators or a highish level of karma
- [ ] When you create a profile for someone else it clearly shows that this is a 'community managed profile' 
- [ ] choose a sane account login even though it won't be used, will be used for mentions
- [ ] It clearly shows who created the profile, or the list of people who have edited it
- [ ] It wouldn't have any tick stats but would presumably have a bunch of FA's, need to show that on the profile (really all profiles anyway)
- [ ] Need to have clear instructions on how to claim the account (probably just email us)

Need to think about policy for how this interacts with #1757 (allow people to archive their accounts)

**Comment by brendanheywood** [comment]
Just thinking out loud for a few details with this:

* Need to lock it down to fairly high level, maybe country coordinators or a highish level of karma
* When you create a profile for someone else it clearly shows that this is a 'community managed profile' 
* choose a sane account login even though it won't be used, will be used for mentions
* It clearly shows who created the profile, or the list of people who have edited it
* It wouldn't have any tick stats but would presumably have a bunch of FA's, need to show that on the profile (really all profiles anyway)
* Need to have clear instructions on how to claim the account (probably just email us)

Need to think about policy for how this interacts with #1757 (allow people to archive their accounts)

**Comment by lordyavin** [comment]
New Pseudo Account for [Anderl Heckmaier](https://www.thecrag.com/climber/aheckmair)

**Comment by quaestor** [comment]
Just a thought: supporters get a purple frame around their profile picture. It would be nice if the community managed accounts would get the same thing in a different colour. This way, these accounts can be quickly distinguished from regular accounts.

**Comment by lordyavin** [comment]
I added † sign at the end of the displayed names. This should help for know. 
@scd: How much effort is necessary to implement the fields for date of death should have

**Comment by nicHoch** [comment]
community managed profiles should not only aim for dead climbers. Also contemporary climbers can be involved.

**Comment by brendanheywood** [comment]
I like the dagger sign, it's a nice touch. We have a few normal accounts whose owners have died and it could make sense (case by case, privacy etc) to convert these over to community managed.

**Comment by lordyavin** [comment]
There must be an option for the families of died persons to take over the account or shut it down, ...

**Comment by quaestor** [comment]
Maybe this is over the top, but facebook seemingly solves this by adding the option to either close the account after death or "memorialize" it. Moreover, one can specify "legacy contacts": users who are allowed to manage the profile once it has been "memorialized".

**Comment by scd** [comment]
Not over the top. We plan to be around a long time which means this will become a common issue, not just an edge case. 

I think there are two different cases - community managed and memorialized. I don't think we want the option of totally closing down accounts if the person has died and is listed as the first ascentionist of routes.

**Comment by lordyavin** [comment]
Bumb: Added another todo for this issue: The CPR graphs should end with the date of death.

**Comment by brendanheywood** [comment]
We've taken the first step to put the data model flag in place for this. At the moment it is purely visual, but we'll progressively leverage this more over time.

![image](https://user-images.githubusercontent.com/187449/51361872-84f68880-1b25-11e9-9c4e-887e96dd93f7.png)

![image](https://user-images.githubusercontent.com/187449/51361889-9475d180-1b25-11e9-9d0f-0afc73dae311.png)

@lordyavin what are your thoughts on this badge title?:

![image](https://user-images.githubusercontent.com/187449/51362481-ee779680-1b27-11e9-8746-f8fac500df3a.png)

**Comment by lordyavin** [comment]
Hey @brendanheywood what is the idea behind the "community champion" badge? I would lie if I said I wouldn't be happy to stand out from the crowd, but I don't think it's absolutely necessary. High karma and permissions are enough 😉

**Comment by brendanheywood** [comment]
@lordyavin the champ badge is just an idea we are kicking around. No worries :)

The community profiles are independent of whether they are deceased or not, at the moment they are the identical. I quite like your † workaround and we'll probably redo that in code once we add a deceased date to a profile. How we manage them for both normal accounts and community managed accounts is still on the checklist to figure out at the top of this issue.

**Comment by brendanheywood** [comment]
I've just flipped the bit on all those accounts list above. @lordyavin if you (or anyone else) add more, from now on add them as new comments here (instead of an edit) so we get the ping and update the community flag on them

**Comment by lordyavin** [comment]
Yes sir!

**Comment by lordyavin** [comment]
www.thecrag.com/climber/adamondra

**Comment by lordyavin** [comment]
@brendanheywood could you please enable the profile page editing for the new account?

**Comment by brendanheywood** [comment]
@lordyavin do mean allowing you to edit the community profiles using your own account? If so no, this isn't implemented yet. The first step here was just adding the flag so these accounts are shown differently, but they are still edited the same. The checklist at the very top of this issue shows what has been done and not yet done.

Right now all I'm doing is setting the flag for the accounts you've made (eg I've done ondra) so they are clearly separate, and so we have a proper way in the system to track them all.

**Comment by lordyavin** [comment]
No I meant the restrictions for new accounts to edit their profile page. I 
can't setup the profile page until the account hast 60 Karma points.

**Comment by brendanheywood** [comment]
Ah yes we've reviewed that and decided on a better path to help mitigate spam, so we've removed the 60 karma points limit for new accounts to edit their profile.

I have hotfixed this so please try again

**Comment by lordyavin** [comment]
New TODO item:
[ ] Change text for community managed ascents in streams: 
 "An ascent of {climberName} from the past was logged at {cragName}."

**Comment by lordyavin** [comment]
And another one:
 [ ] Adapt profile page template to community profile:
   [ ] ABOUT ME -> ABOUT {climberName}
   [ ] MY WEBSITE/BLOG -> {climberName}s WEBSITE/BLOG

**Comment by brendanheywood** [comment]
Most of these I'd be happy to change across the board for normal accounts too

**Comment by quaestor** [comment]
I wouldn't like to see "ABOUT ME" and "MY WEBSITE/BLOG" changed for normal accounts as indicated above. It feels somewhat odd seeing your name in so many places on a single page.

**Comment by brendanheywood** [comment]
Actually I just meant making it generic like ‘About’ instead of ‘About me’ and then it would work in both cases.

**Comment by lordyavin** [comment]
https://www.thecrag.com/climber/beatkammerlander

**Comment by brendanheywood** [comment]
I've added the community flag for that one and also made it public

**Comment by lordyavin** [comment]
Perfect


--
threema://add?id=AXT2ZYJ7
Am 14. März 2019 11:44:17 schrieb Brendan Heywood <notifications@github.com>:

**Comment by lordyavin** [comment]
Adding Beat I stumbled across accounts that use the name of Wolfgang Güllich:
* https://www.thecrag.com/climber/svillanu
* https://www.thecrag.com/climber/ropegun78

Do we need a mechanism to track that someone uses the name of a famous climber? What should we do if we are aware of such accounts?

**Comment by lordyavin** [comment]
Oh oh, first public [negative opinions](https://www.thecrag.com/ascent/2310279486) on this feature. Especially Lees comment is worriyng me.

**Comment by quaestor** [comment]
@lordyavin As you know, I also have reservations about this feature. I guess I'm okay with community managing historical ascents of deceased climbers, but the others always somehow creep me out. I can understand why people see this as a form of stalking. Only recently, a friend wrote me a message saying "oh look, Adam Ondra recently joined thecrag". He's not a thecrag user himself.

As Lee already said, it would be much better to encourage these people to join. In the long run, if you're adding more and more people, I also think that it won't be feasible to maintain all the accounts. Already a recurring 8a.nu export seems cheating, stealing, and yes, somewhat stalking.

**Comment by rouletout** [comment]
We will not do recurring 8a exports - the main goals here are 2-fold, to have a ranking that is as accurate as possible, so we will just record top ascents for these climbers, as they are reported in the press. That way we are nothing more than a "wikpedia" for climbing and I don't think that any climber feels stalked by having his entry on wikipedia. The second thing is historical ascents to reflect climbing history - same thing applies. Of course, the ultimate goal is to motivate everyone to maintain his or her own account.

**Comment by lordyavin** [comment]
https://www.thecrag.com/climber/arthuroswald

**Comment by brendanheywood** [comment]
flagged

**Comment by lordyavin** [comment]
* https://www.thecrag.com/climber/davidlama
* https://www.thecrag.com/climber/hansjoergauer
* https://www.thecrag.com/climber/jessroskelley

Please don't set them public. I'm not finished with the about pages.

**Comment by lordyavin** [comment]
https://www.thecrag.com/climber/mariettauhden

**Comment by rouletout** [comment]
done

**Comment by lordyavin** [comment]
www.thecrag.com/climber/alexanderhuber

**Comment by lordyavin** [comment]
https://www.thecrag.com/climber/paulpreuss

**Comment by lordyavin** [comment]
https://www.thecrag.com/climber/titapiaz

**Comment by rouletout** [comment]
@lordyavin both done

**Comment by rouletout** [comment]
Community profiles are pretty settled now, took 2 itmes out of this long issue and created a new one, closing this.
