### ISSUE TITLE
Nitpicking on alternative names

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#1526]
I like the concept of alternative names. However, could you perhaps clarify what "language" encompasses? I see two (in my opinion) different interpretations:
- a node has generic names in multiple languages because of geographic/ethnic/historic reasons 
- the translation of (local) names to make their interpretation possible for the non-local speaker (e.g. "Nordwand" = "north face")
  I guess the former case deserves to be listed in the current way (i.e. Španělská stěna / Spanische Wand), whereas the latter is useful, but should not be displayed this way. Probably a category "translation" would do the job.

**Comment by brendanheywood** [comment]
Closing see https://github.com/theCrag/website/issues/1748
