### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by JuergenBollinger** [theCrag/website#1528]
Hey there,my first post here after i've been hassling simon for a while... 
Just a suggestion for creating a wishlist. 
I think most users would like to be able to create a wishlist for crags and routes they wanna go to. (like with amazon just free:-)
could be under Your Dashboard/Your Profile/Your Logbook/Your WISHlist
two sections, routes, and crags.
cheers 
J

**Comment by brendanheywood** [comment]
@JuergenBollinger I'm just doing some tidy up, I'm closing this as a duplicate of  https://github.com/theCrag/website/issues/1318 - if you have anything extra to add please do it there, thanks!
