### ISSUE TITLE
add admin form for non-paypal manual payments from account

### ISSUE THREAD

**Issue by scd** [theCrag/website#1529]
If somebody direct credits our bank account we should easily be able to do a manual input of the transaction in the system using a single form. Currently the process for manual attribution is:
1. log in as super admin and create an account payment record (note there is a bug with this, as it does not allow you to put in a date).
2. log in as normal user with Account management role and adjust crag credits for user
3. Update the support attribution date in the account details page for the user.

Yuk

**Comment by Mdemaillard** [comment]
implemented via stripe

![image](https://user-images.githubusercontent.com/60388146/76319255-a301e800-62e7-11ea-817e-e159ce18f56c.png)

![image](https://user-images.githubusercontent.com/60388146/76319227-954c6280-62e7-11ea-9caf-f10e48f651cd.png)
