### ISSUE TITLE
In various markdown places add rel="nofollow" as needed (spam protection)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1534]
General principal is we want to avoid being used as a link farm, and trust the links that trusted contributors add.
- [ ] In profile descriptions - based on users karma
- [ ] In forum posts - based on users karma
- [ ] in ascents - based on users karma
- [ ] in node markdown - could be difficult, either always add nofollow (simple), or possibly based on the karma of the last person to edit each particular field.

See #1533

**Comment by brendanheywood** [comment]
+1 from support email

**Comment by scd** [comment]
This was done a while ago
