### ISSUE TITLE
Tab order on bulk edit page

### ISSUE THREAD

**Issue by oliverstory** [theCrag/website#1547]
For keyboard entry when adding route locations it would make sense for the field tab order to go 'Lat' -> 'Long'

On the bulk edit page it goes 'Lat' -> 'Route Name' ->.... 'Long'

**Comment by Mdemaillard** [comment]
Verified implemented.
![image](https://user-images.githubusercontent.com/60388146/76315229-f58bd600-62e0-11ea-93bf-0f736a2fd6e5.png)
