### ISSUE TITLE
inbetween grading in uiaa System

### ISSUE THREAD

**Issue by JuergenBollinger** [theCrag/website#1550]
I am adding lots of content at Frakenjura at the moment and i experience two issues here connected to  the grading system:
1. since the uiaa grading is rather coarse its common practice here to give routes an "inbetween" grade. 
for example:
7+/8-
its also necessary for the correct translation into the french or other grading systems.
for example:
7+/8- equals FR6c, or 22.
8+/9- equals FR7b, or 26
2. The grades don't convert correctly, like 9- in Franken should convert to 7b+ and not 7b! but i might be opening a can of worms here....
cheers

**Comment by brendanheywood** [comment]
@scd would consider the / part of this issue done?

**Comment by scd** [comment]
Yes I consider the slash part of this issue done. The conversion tables is a different issue. There may be parts of the site logic which are not fully utilising the new conversion logic, but I think we should start new issues for that.

**Comment by scd** [comment]
FYI,  I am pretty sure we will eventually need to go through some sort of statistical analysis for adjusting grade conversions and ranges.

**Comment by Mdemaillard** [comment]
@brendanheywood  you wanted to close this, i believe this is time.
