### ISSUE TITLE
pitch info - grade and linkup not being cloned with me too function

### ISSUE THREAD

**Issue by scd** [theCrag/website#1553]

**Comment by Mdemaillard** [comment]
me too function ?

**Comment by lordyavin** [comment]
![grafik](https://user-images.githubusercontent.com/1528540/76934615-bfa5ad80-68ef-11ea-899a-426436d36097.png)

![grafik](https://user-images.githubusercontent.com/1528540/76934681-e06e0300-68ef-11ea-907e-1ac9f205bc85.png)

Looks like this issue is fixed.

**Comment by scd** [comment]
We called it 'me too' for logging an ascent from a stream before the world claimed it for another cause. Now of course we cannot use this phrase.
