### ISSUE TITLE
How long to keep Custom PDFs?

### ISSUE THREAD

**Issue by scd** [theCrag/website#1554]
This will become an issue as soon as people start to generate a lot of PDFs.

My initial thesis was that disk space is so cheap it does not matter, however this is proving to be invalid and disk space usage is forcing us to upgrade servers.

I am not backing these up anywhere, so they are only on prod.

I presume we just want to pick a timeframe? or do we want a pick a disk usage? My preference is a timeframe because then we have documented evidence of what was delivered to somebody for a known time.

**Comment by brendanheywood** [comment]
Spoke to simon around this the other day and our terms say 1 month and there is a process for it so I think we can close this one
