### ISSUE TITLE
"Recent unread discussion you are following" on dashboard should exclude forums you are involved in

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1560]
Otherwise they double up:

![image](https://cloud.githubusercontent.com/assets/187449/3709359/21b54964-1454-11e4-9546-70e33131da30.png)
- [ ] exclude from list in dashboard
- [ ] exclude from total count in dashboard total

**Comment by scd** [comment]
This was fixed ages ago when we combined the two areas
