### ISSUE TITLE
Show annotation title in node resequence process

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1563]
As an annotation may now have a title, and no content, we need to show ideally both the title and the content in the re-order page.

**Comment by brendanheywood** [comment]
This should get exactly the same treatment as the topo linking process:

![image](https://user-images.githubusercontent.com/187449/59159291-e3d79100-8b0a-11e9-98e9-6a187140650f.png)

**Comment by rouletout** [comment]
This is done,closing
