### ISSUE TITLE
When editing annotations with title, the title should also appear in the preview on the right

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1565]

**Comment by Mdemaillard** [comment]
When single editing the Note, the process used IS bulk edit, but the Title is NOT included in the preview.
![image](https://user-images.githubusercontent.com/60388146/76402104-959e3980-638b-11ea-805b-692a2f2dcc3d.png)
Actually, the Note Title and AKA is similar to the Route Name and AKA, and they are not previewed either.

**Comment by rouletout** [comment]
This would really not be consistent with the rest of the forms (routes, areas, etc.), closing
