### ISSUE TITLE
Do we need to create a region grade context field

### ISSUE THREAD

**Issue by scd** [theCrag/website#1568]
- [ ] SAXON doesn't appear in the table anywhere, use it for germany? or investigate setting at region level, OR investigate making this context be used at german level and then adding other parseContexts to this context to make it work for germany, similar to the UIAA parseContext
- [ ] UIAA & FR grades often appear in the same country. Strictly they do not overlap, but when I implemented parsing UIAA accepts grades in a similar format to FR. I am not sure whether this is due to something I read somewhere, or just a mistake. We have since had advice that UIAA are always mutually exclusive. If they are not mutually exclusive then we will have to implement region contexts.

**Comment by brendanheywood** [comment]
Pretty sure this was done a while ago? @nicHoch can you confirm you can set the grade context at a crag or region level?

**Comment by scd** [comment]
You can set grade context at crag level. Edit crag -> look for 'Default area context' field

**Comment by scd** [comment]
![tc-default-context](https://cloud.githubusercontent.com/assets/373058/25780034/c8733f0e-3364-11e7-9289-83741896cc60.png)
