### ISSUE TITLE
random prize for gym competition participation

### ISSUE THREAD

**Issue by scd** [theCrag/website#1577]
Gym may wish to offer a random prize for participation in a competition. Criteria:
- log any ascent for each competition day gives you one entry point
- other manually awarded entry points by organiser

This could be implemented as a competition leaderboard, where at the end of the competition the organiser prints out the leaderboard, photocopies pages so that there is a physical avatar duplicated for each person that matches their leader board score (ie number of entries into the competition) then cuts out the avatars. These go into a bag for the final draw.

Gaps in the system:
- hasDayAscent score function
- manually add scores to accounts
- sufficient ID material on avatar

**Comment by rouletout** [comment]
On contest page, closing
