### ISSUE TITLE
Missing facet for search by fa history text

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1580]
Not urgent but nice to get done before we implement #1179 

ie /routes/by/law/ does a free text search in the FA field for 'law'

This url already exists but does nothing.

Later when we implement the history account linking then the same endpoint will work with both, eg:

/routes/by/law/ does a free text search in the FA field for 'law', as well as search for accounts whose name or username contains law, which are linked to the route.

/routes/by/@law/  on the other hand would do an exact search for routes linked to the 'law' account.

Probably best if when we implement #1179 we denormalise all the search text into one flat field so no extra joins.

**Comment by scd** [comment]
this is done. 

After this has been working for a while we should consider using this method for all account facet fields. Currently only 'friends' are discoverable for other account facet fields across all the facets. Also the current drop down list takes a lot of valuable screen space.

The only problem is the backend mostly cannot handle free text search (except for the fa filter).

Do we want to extend this method to all our account facet filter types?
