### ISSUE TITLE
Avoiding duplicate routes and areas - auto check when making new nodes

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#1583]
Duplicates (in routes or areas) are a nuisance to clean up. It would be great if some simple check could help people detect (and avoid) duplicates when entering new nodes: When submitting a new node, the next ancestor and sibling nodes could be searched for a similar name and issue a warning, in case anything is found.

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76317449-e575f580-62e4-11ea-9b34-aefef399eeb4.png)

Validation is implemented for sibling nodes, both for type Route  (e.g. new route with same name as existing route under same node) or Node (same but with Areas).

It is possible to nest 2 crag with identical names (no validation on parent node), or/and a route under a crag sharing same name. Here dummy example with crag>crag>route sharing unique name.
![image](https://user-images.githubusercontent.com/60388146/76318039-c62b9800-62e5-11ea-9866-1fe4de514ce2.png)

the duplicate name for crag&crag make sense to prevent, but often a route and parent node share name, for example in boulder fields.
Do we want to implement the parent check ? or close the issue ?
I suggest to close as is.

**Comment by rouletout** [comment]
Yes, closing
