### ISSUE TITLE
Detect and report IP ranges for known bots, filter them out for spam reporting

### ISSUE THREAD

**Issue by scd** [theCrag/website#1591]
Amazon's ip's:
https://forums.aws.amazon.com/ann.jspa?annID=1701 

This seems to be best list I can find with proper ip ranges instead of an enumerated list of ip's all in one place:
http://myip.ms/info/bots/Google_Bing_Yahoo_Facebook_etc_Bot_IP_Addresses.html

**Comment by brendanheywood** [comment]
For well behaved bots the right way to detect this is using the user agent not the ip address. For badly behaved bots all bets are off

If this is for the daily report then we should instead have a white list of bot useragent strings and if detected it replaces the ip address with the bot name. This would solve the grouping issue we currently have in the reporting with large ip ranges.

**Comment by scd** [comment]
can badly behaved bots pretend to be good bots?

**Comment by brendanheywood** [comment]
On reflection nothing that sensitive so dumping thoughts / tasks here:

* [ ] we want to know which ip's belong to which bots / services (could be not a bot). It seems the only robust way to do this with most bots is a reverse DNS lookup (eg https://support.google.com/webmasters/answer/80553 and https://www.bing.com/webmaster/help/how-to-verify-bingbot-3905dc26). This is slow, so lets post process the logs asynchronously using (either in piped mode, or as part of the rolling process - pros and cons?)

https://httpd.apache.org/docs/current/programs/logresolve.html

* [ ] for reporting and grouping purposes we don't want to full domain, we typically only want the TLD and the next level down to identify the company or service involved. The simplest would be to just grab to top two levels if a USA tld, and the top 3 if a non us TLD (ie has a country suffix). So in the report wherever we'd previously saw ip from googlebot it would instead be grouped and shown as 'googlebot.com'.

* [ ] If an ip doesn't have a reverse dns, then we treat it just like we did previously
* [ ] If it's reverse dns doesn't map back to itself, then we treat it with more suspicion

**Comment by scd** [comment]
Not required anymore. Closing
