### ISSUE TITLE
No more "Trip" dropdown when logging routes?

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#1600]
When logging routes I couldn't see the "trip" dropdown anymore. I knew it was there once. I would welcome it back.

**Comment by lordyavin** [comment]
So what is going on with the issue? What about assigning photos to trips? This isn't possible anymore.

**Comment by lordyavin** [comment]
Please reactivate trips!

**Comment by rouletout** [comment]
@lordyavin please let us know if there are aspects to lists that you miss in comparison to the former trips functionality. I close this one here as trips is deprecated and lists are now available.
