### ISSUE TITLE
Configure static server for dev

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1603]
I've found a couple bugs:

* [ ] some topo urls are being loaded from www instead of static, and worse their headers are not being set so they are not being cached
* [ ] some urls in dev are broken, but work in prod, like the og:image in the header, not much of an issue but I'm hesitant to fix them in case I get them working in dev but then they end up broken in prod

The root cause of both of these is inconsistent use of the static function, which in turn is hampered because in dev I have reduced visibility of whether it's properly working on not when looking at the output html.

How about we configure the dev.thecrag.com server to use it's own ip as the url base for it's static server? That way it's really obvious that the url's are being built correctly. Because it's a dedicated host and apache is listening on * this works just fine.

So instead of churning out a server relative link like: 

/image/topo/00001/fixedheightmedium/325842498.jpg
we'd get
http://27.32.153.207/image/topo/00001/fixedheightmedium/325842498.jpg

Only downside I can see so far is you'll get a https security warning on the page, which I think is fine for dev.

**Comment by scd** [comment]
see also #2029
