### ISSUE TITLE
click on Topo area shape where topo is both area topo and route topo

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1604]
If we are in an area inside a topo which contains us, then clicking on that shape should do nothing, instead of reloading the current page. But also if that shape also contains routes the whole shape should be sort of invisible and clicks and hovers over it will be ignored:

https://dev.thecrag.com/climbing/australia/booroomba-rocks/area/11830621

**Comment by rouletout** [comment]
I don't think this is still an issue - 1539 is also closed, so closing this
