### ISSUE TITLE
Show gear style colors for cluster, easily filter by gear style

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1610]
It would be nice if you could filter by style (sport, bouldering, trad) on the map view.

For example, if I am doing a trip to California and want to find climbing. I can look at the map and zoom in and see the number of climbs in various areas. But if I am only bring a sport rack or a bouldering pad or whatever then I don't really care about trad climbs. So seeing "500 climbs in this area" is not so useful if they are all trad.

Tom

**Comment by brendanheywood** [comment]
The gear styles will be shown in maps v2, but no filtering for the medium term. Closing this:

![image](https://user-images.githubusercontent.com/187449/48740847-28a1f480-ecad-11e8-8544-46005a808ca2.png)
