### ISSUE TITLE
Allow a gym to be configured with a list of valid tick types / allow seconding in gyms

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1631]
Should we just add this one tick type, or should we make this configurable?

**Comment by brendanheywood** [comment]
This should get sorted mostly with the tick release planned shortly, so only relevant tick types are show depending on 'sport' or 'toprope'. We could have some additional logic to filter even more when in a gym context, ie probably don't need the aid ticks

**Comment by brendanheywood** [comment]
Now that we have a more fine tuned list of ticks per gear style typ,e I'm wondering if we can close this? Is there anything else we have missed as part of this issue?

**Comment by scd** [comment]
I think close.
