### ISSUE TITLE
The lifecycle of a competition

### ISSUE THREAD

**Issue by scd** [theCrag/website#1632]
After having done our first competition I have a clearer picture on the lifecycle of a gym competition. I have defined some status codes which define each stage of the lifecycle.

An admin can change the lifecycle status.

**Develop**: The competition is still being configured online and in a pre release test phase. You can recalculate leaderboards for testing purposes. The competition is not linked to the gym node in this phase.

**Pending**: The competition is fully configured online and ready for marketing. It is linked to the gym node. You cannot recalculate leaderboards in this phase.

**Live**: The competition is underway. It is linked to the gym node, and you can recalculate leaderboards.

**Complete**: The competition is now finished so results can be finalised and published, you cannot recalculate leaderboards. The competition is still linked to the gym node

**Archive**: The competition is now past it's used by date and therefore should not be linked to the gym node. You cannot recalculated leaderboards.

**Comment by brendanheywood** [comment]
@scd anything actionable here? close?

**Comment by scd** [comment]
Close. Done ages ago
