### ISSUE TITLE
hash tagging article

### ISSUE THREAD

**Issue by scd** [theCrag/website#1642]
Missing work from last release. I was hoping to get some more tangible examples, but I have decided to start documenting this anyway.

dev.thecrag.com/article/HashTagging
- [ ] Campbell to review
- [ ] Screen shot of route search (possibly use Nicky's Alto Mijares after that goes online).
- [ ] Document x3 interesting examples of use in ascent logbook - with screen shots

**Comment by rouletout** [comment]
This exists, closing
