### ISSUE TITLE
Polish and formatting for user permissions lists settings page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1646]
Extra polish for user permissions / karma list done in #278

These two lists will by nature almost always overlap, so thinking they should be merged. Probably extend the permissions and then remove the top 10 karma list
- [ ] add karma count to permissions list
- [ ] add ancestor data to each crag in permissions list, will group crags by ancestors
- [ ] add sort by karma | index order | permission level, default sort probably index order - most people will only have a hand full of crags
- [ ] either add in-line, or link to article for explainable of what each role means

**Comment by Mdemaillard** [comment]
The 4 initial items seems implemented, candidate for closure ?
If need be the permission automatic rollup can be made a separate clean issue
