### ISSUE TITLE
Move the 'hide' and 'deselect' buttons into attribute panel when editing a topo

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1651]
This will mean you can properly edit features under where those buttons sit.
- [x] move hide and deselect buttons to attribute panel
- [x] Also move the panel zindex to sit on top of the topo when zoomed
- [x] make the panel draggable so you can put it where ever you want so it's not in the way

**Comment by lordyavin** [comment]
Updates?

**Comment by brendanheywood** [comment]
Uummm, well I've painted my house and put new flooring down, that's kinda progress of some kinda isn't it? :)

**Comment by lordyavin** [comment]
Yes it is some kind of progress :-) Which colour? Any idea when we will get that issue fixed for the public frontend?

**Comment by brendanheywood** [comment]
Mostly white. I hope to get back into a semi regular state of working on code again in the next few weeks. The priorities after that will be a bit mixed, the streams is high on our list. This is a reasonably small low hanging fruit so I'm moved it into that release.

**Comment by lordyavin** [comment]
Great. Looking forward to get the buttons out of the way.

**Comment by quaestor** [comment]
As a temporary workaround, would it be possible to make the buttons disappear while holding the shift key or something like that?

**Comment by brendanheywood** [comment]
+1 from @rouletout

**Comment by brendanheywood** [comment]
+1 from @birgander2 via closing #1844

**Comment by brendanheywood** [comment]
Half of this has been done, the hide and deselect buttons have been removed. This still works well on desktop but its not great on mobile (which has never been great anyway). The whole panel is not visible on mobile so I need to figure out whether I want to show it or add the buttons back along the top.

**Comment by brendanheywood** [comment]
Finished
