### ISSUE TITLE
Gym grade formatting cleanup

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1655]
after new grade colours:

![image](https://cloud.githubusercontent.com/assets/187449/4400733/2b8efe1a-4485-11e4-8df1-6c8c8d516d90.png)
- [ ] Need to add in the border and padding. 
- [ ] Also need to detect wether the color is mostly dark or light and change the text to white or black

**Comment by lordyavin** [comment]
Is this issue still valid?

**Comment by brendanheywood** [comment]
No I think this is all sorted now
