### ISSUE TITLE
Add mobile bookmark name to header for bookmarking

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1669]
```
<meta name="apple-mobile-web-app-title" content="Myname">

<meta name="application-name" content="Myname">
```

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76316837-e4909400-62e3-11ea-87bf-6d5f8addd2f4.png)

If i understood correctly, this is implemented. Bookmarking prefills the bookmark with some content related to the current page. ex works with Dashboard, or a crag (cf snap)
Not too sure if maybe the browser scrape that from the URL though ?

**Comment by rouletout** [comment]
This works, closing
