### ISSUE TITLE
profile stats oddness

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1673]
My stats:

https://dev.thecrag.com/climber/7727431
![image](https://cloud.githubusercontent.com/assets/187449/4499703/866462ec-4a86-11e4-9041-a2116f105f4d.png)

And yet if I add the 'repeat' filter I get more routes not less which is very counter intuitive:

https://dev.thecrag.com/climber/7727431?repeats=1
![image](https://cloud.githubusercontent.com/assets/187449/4499707/912bfb22-4a86-11e4-894e-d742935ef6cb.png)

So a couple thoughts:
- At very least the button should say 'include repeats' and the 'all' button is wrong as it is only unique ascents not all ascents. This is probably my fault because I misunderstood what was happening when we did this. Also the buttons should highlight
- I'd really expect this whole page to show all my ascents and then filter it down, so the default should be 'repeat' but renamed to 'all'.
- the big stat at the top swaps from 'ascents' to 'unique ascents' which is perfect, but the 'distance climbed' has the same label in both which is the one I find misleading by default because you get no hint that repeats are not included. I'd prefer it to default to 'unique ascents' and the total 'distance climber' not unique 'distance climbed'
- when I add a filter to onsight this seems weird / wrong:
  ![image](https://cloud.githubusercontent.com/assets/187449/4499791/9d4b3606-4a87-11e4-8ac4-907ce6a0478b.png)

**Comment by scd** [comment]
I have done the low hanging fruit for this issue:

- [x] distance is total distance climbed
- [x] provided a link to ascents where the route does not have height info

**Comment by brendanheywood** [comment]
the other parts of this are now redundant
