### ISSUE TITLE
Profile page recent contributions is empty

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1680]
https://www.thecrag.com/climber/brendanheywood/

![image](https://cloud.githubusercontent.com/assets/187449/4523202/414652e6-4d34-11e4-8734-f7dd60dbd845.png)

Template data is empty - is this supposed to be rendered at template time or pulled in after ajax?

btw this is half blocking completion of #585 because this activity template uses it

**Comment by scd** [comment]
fixed without streams
