### ISSUE TITLE
profile page design directions

### ISSUE THREAD

**Issue by scd** [theCrag/website#1686]
See also:

https://docs.google.com/document/d/1H16lSHemjK5KF9yw_h9ku6iOLe5XYW5AhvvsovrADpY/edit#

Before I start refactoring the profile page, I want to have a discussion about the design direction of the profile page. 

Some general ideas about the profile page, that I think we have a good common understanding of now are:
- [x] profile page should be based on a facet
- [ ] graphs/maps should be available for all facets (not just for profile page)
- [ ] there are potentially a lot of widgets/components (eg performance graphs) that we may want to provide for the profile page - some of them may be premium
- [ ] widgets/components of the profile page should also be embeddable, which means they come with their own url.

Should we be totally standardising the profile page or allow some configurability in the profile page(s)?

At the moment I am leaning toward configurability.

In fact I think we should let users define multiple profile page 'tabs' each profile page being associated with a different facet and each with a checklist of widgets (eg 'Bouldering' & 'Indoor'). If they don't configure anything they will get something similar to what they get now.

Is there any merit of having multiple tabs under the profile page?
(It think we do want multiple facets to represent a climber, rather than one facet for everything).

Do we want to allow this to be configured by the user?
(I like the idea of a climber being invloved in building their own profile, and maybe they will come up with things we don't think of. But I would also like to be able to see the same graphs on Brendan's profile page as is on mine).

See also:

https://github.com/theCrag/website/issues/3191

**Comment by scd** [comment]
Finally I have had time to think about this further and create a task list.
 - [ ] add favorite summary to second level nav, linking to favorite facet
 - [ ] remove inline favorites from left hand column
 - [ ] remove inline favorites from left hand column
 - [ ] order inline following in left hand column by karma and limit to 20 entries
 - [x] turn right hand recent ticks into a facet
 - [ ] make right hand recent ticks configurable in settings page allowing gym/outdoor, gear style and tick type to be set
 - [ ] make most of settings at bottom of the page configurable in the account settings page.
 - [x] fix recent contributions so it actually works
 - [ ] turn recent contributions into a stream (and remove recent ascents as this will be in the stream)

We need a more flexible way of storing account configuration. 
 - [ ] AccountConfiguration Table - account, key, value

**Comment by brendanheywood** [comment]
Ultimately the recent ticks, and the recent updates will all get merged into a single stream on this page so I wouldn't bother with too much effort into this, just focus on the stream stuff. the right column can just disappear completely.

As an end game I see the summary staff being very succinct, less that 'the fold' with the combined stream right underneath and the top visible for most devices. Then sub pages to drill down into followers, deeper stats, fav's etc

**Comment by scd** [comment]
> Ultimately the recent ticks, and the recent updates will all get merged into a single stream on this page so I wouldn't bother with too much effort into this, just focus on the stream stuff. the right column can just disappear completely.

Yup agree. I have taken off the task to make this configurable. I love having less work.

I have removed some of the stuff from the left hand column, which basically leaves a list of people the climber (or you) is following. I have order this by supporter status then karma then ascents.

**Comment by scd** [comment]
@brendanheywood I have got something worthwhile looking at before we make a few decisions. There are a number of updates worth while discussing.

1. Profile page filter settings are now updated and saved in the settings page

dev.thecrag.com/settings/filter

TODO on this page:
 - [ ] show a link to the actual profile page
 - [ ] add link to the settings general header menu
 - [ ] decide weather ascent style is checkbox or radio box (see discussion below)

2. The main section of the profile page is now based on a facet. Note that before it was based on a facet plus some specials. Now the facet comes from your settings page, plus any extra facets in the url, eg

dev.thecrag.com/climber/scd/with-route-gear-style/sport

While the settings page only stores a couple of generic settings, the url allows you to setup any ascent ascent style facet you want for your profile page. (more examples below)

The painful part of the the way it was done previously was the facet gave all tick types then we excluded some manually. Now the facet explicitly returns only certain tick types.


3. Labeling the profile page. For the lack of proper thought and design I have put a functional description of the profile page filter near the top. This label/description is close to a facet description with a few differences. It indicates wether it is based on standard settings and how close in some instances (ie one tick type different).

4. Dumped the general filter. I found it messy, and if we were to do something it would be similar to the facet filter anyway. I don't think that doing advanced filtering is important for this release, so I am happy to leave this discussion for later unless you feel strongly about advance filtering.

5. Moved the quick filter buttons to the bottom and changed them a little. Interesting changes:
 - Profile page based on a standard filter setting (ie no user settings): http://dev.thecrag.com/climber/scd?standard=1
 - Profile page based on your settings (ie you can see what somebody else's profile looks like with your settings): http://dev.thecrag.com/climber/manacubus?my-settings=1
 - Standard time based settings - last year and last 3 years: http://dev.thecrag.com/climber/manacubus/between/2014-2-1+2015-2-24?standard=1

The big issue which I need to discuss is whether we allow cross gear style profiles (eg trad+boulder). Because of our fabulous grade conversion engine the system does not care and can handle this. This is how it has been working, but has caused some confusion. I would be happy to at least make it difficult for the user to do a cross gear style filter (eg radio button in the settings page rather then checkbox and defaults to 'system decides' rather than all).

**Comment by brendanheywood** [comment]
> Profile page filter settings are now updated and saved in the settings page

cool - although I think these should be merged with the existing profile settings

> Now the facet comes from your settings page, plus any extra facets in the url

cool

> Labeling the profile page.

I think the main thing here is that whereever we stick a button like 'Customise your profile' that this text is right next to it

> Dumped the general filter.
yeah agree. It would be nice if we could re-use the templates for the widgets for these so they all match up. not important

> Moved the quick filter buttons to the bottom and changed them a little

yeah good enough to ship, but again would be better if this UI was identical to at least the UI in the settings page. Each set of mutually exclusive settings should be either a radio or a a button group and it should show what setting is selected (or default). Once we regig the whole profile design / layout I'd move these to the top and swap in the new stats without a reload.

a very quick and dirty mockup for what I think both should look like (not complete at all):
![image](https://cloud.githubusercontent.com/assets/187449/6345228/9d16e134-bc57-11e4-80d6-78903c8bf42e.png)

Don't worry about the styling but it should function like that. Ideally later the setting would also have a little checkbox 'Save these settings' which calls the same ajax as in the setting page.

> The big issue which I need to discuss is whether we allow cross gear style profiles

Can you break this apart I'm 100% what you mean. Are we talking filtering, or grade display, or grade translate?

**Comment by brendanheywood** [comment]
> The big issue which I need to discuss is whether we allow cross gear style profiles

Ah - I think you mean if I've done both bouldering and sport climbs showing two charts for say 'Ascents by grade and tick type', one with the sport routes and one for bouldering?

I'd be happy to defer this discussion, there are a whole bunch of more fundamental things about the profiles I'd like to talk through first, I think the priority is on getting the streams right first because I want them to be the main focus on the profile pages. And on top of that I think there are other higher priorities to look at first.

**Comment by scd** [comment]
> I'd be happy to defer this discussion, there are a whole bunch of more fundamental things about the profiles I'd like to talk through first

I would prefer to defer as well, but mainly because I have made some incremental changes and would like to see the feedback.

The fixes I have done now does allow somebody to save settings so that only their boulder routes are in their profile. Let's watch to see if people do this.

> yeah good enough to ship, but again would be better if this UI was identical to at least the UI in the

The buttons were meant to be quick and dirty way to get to interesting profiles with a single click. I think I will keep it simple for now, because there are some other aspects which could create a rabbit hole of complexity. At the end of the day the profile page may be just an option for the ascents facet page. So I guess the argument is similar to yours, there are higher priority issues.

**Comment by brendanheywood** [comment]
> I would prefer to defer as well, but mainly because I have made some incremental changes and would like to see the feedback.

I'm happy with what you'd gone and I think we should ship.

For the future discussion: I meant I have idea's for going back to the fundamentals and requestioning everything that's on the profile page from first principals and then rebuilding up a conceptually ideal profile page from there and then seeing what the gaps are. I have some rough ideas what I think that will turn out like, eg I think the stream will become the dominant body component with just the big summary stats and personal message above it, so the right column content will be merged in. Most of the charts are visually quite dense and could be easily shrunk without losing any value so could potentially fit in the right column so we could move the stream up to inside 'the fold' on desktop. The other thing to juggle and tidy up is the following list on the left, and showing followers you have in common. Now everything is available at a glance without scrolling that tells you the answers to key questions which I think are the critical purpose of the profile pages: what type of climber are they, do they climb near me, what grades are the climbing, how regularly do they climb, how much do they contribute, how do I know them, how can I contact them. The primary actions are: follow, and message - message should be moved to the header.

**Comment by scd** [comment]
I think I have done as much as I am going to do on this issue for first profile release - profile part A.

I have had a trawl through other issues we need to address for profile part B:
 - [ ] #1685 - addresses deficiencies with the notable ascents profile feature.
 - [ ] #1673 - some additional charts
 - [ ] #1627 - clearer display of grade context
 - [ ] #1220 - climbing days stat
 - [ ] #1207 - normalise graphs to meters
 - [ ] #1116 - aid component missing from grade display
 - [ ] #1028 - business rules for big stats
