### ISSUE TITLE
Alternate V grades for easy grades V00 V000 and VE

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1687]
Another thing that came up today from Mani: Seems to be a lot of variability of low end V grades under 0

Want to find some more examples in the wild to help inform this one

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/82840077-a9106980-9ed1-11ea-99b3-61dcd8bde425.png)

Pretty sure this is the implementation. If it is not, that issue didnt interest anyone in 4 years anyway. closing, but feel free to reopen if i am wrong.
