### ISSUE TITLE
Link to annotations from topos same as areas

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1693]
Now that annotations have title it make a whole lot more sense to be able to link to them in an identical fashion to an area. Almost zero code from the topos point of view, just need to make sure we pass from the annotation id and it's parents id to handle the case where it is linked from outside the parent area.

Must do Tasks:
* [x] select annotations for new topo (@scd) 
* [x] be able to select annotations link existing topo processe (@scd )
* [x] ensure topo numbering is still ok select/topo edit/topo node/pdf (TopoUtil + ??topo labels + ??pdf) (@scd)
* [x] when linking to an annotation we need both the annotation id as well as the parent page id (@scd )
* [x] pass whole parent object, if it is different?? or just pass url basic enough data for url
* [x] update the topo code so that annotations can be drawn in the same way as areas. We probably want some subtle difference in the rendering like a different color (@brendanheywood)
* [x] cursor linking when on the same page / same parent
* [x] decide business rules for number of topos in list view
* [x] decide business rules for locations of annotations, treat as areas too? what would we even show on a map? the outline makes sense to be the same as an area, but it itself contains no routes

Nice to have:
* [ ] ideally change the topo rendering to use xlinks instead of js events to make linking and right clicking work properly  (@brendanheywood)

Tests:
* [x] Link within a list view page:
https://brendan.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/the-fortress#t967640307

* [x] annotations in list view are broken (header + hash anchor)

* [x] From route detail page:
 https://brendan.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/the-fortress/route/959051805

* [x] Link within guide view
 https://brendan.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/the-fortress/guide

* [x] annotations in guide view are broken (header + hash anchor)

* [x] Links within topo detail view
https://brendan.thecrag.com/topo/967640307

**Comment by brendanheywood** [comment]
Got a perfect test case for this:

https://www.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/the-fortress

**Comment by brendanheywood** [comment]
+1 from @rouletout for this

**Comment by rouletout** [comment]
+1 again, I can't do what I want if I can't draw annotations in an area topo. Is that hard to add?

**Comment by brendanheywood** [comment]
@rouletout as you find example where you want it can you also add the urls to this issue so that when we implement this we can go back and fix them up as good examples to show case.

There is probably a days work for me here and work for @scd too, I'd guess max a day on his side

**Comment by rouletout** [comment]
examples are / will be here:

https://www.thecrag.com/climbing/united-states/colorado-shelf-road/area/16741327
https://www.thecrag.com/climbing/united-states/colorado-shelf-road/area/14385913 and its sub-areas set up as sectors

**Comment by brendanheywood** [comment]
+1 from private email

**Comment by brendanheywood** [comment]
+1 from gym

**Comment by scd** [comment]
@brendanheywood I have got some way with this, but I think we need to make some minor enhancements with the topo tool event handler.

THe annotation is in the list of topo objects but when I click on the annotation line the topo stops working. I suspect it is something to do with data-type="annotation" not being recognised. Is this something you can look into

In branch `scd/topo-annotation`

**Comment by brendanheywood** [comment]
I've found a few hours and done the bulk of the topo js work now:

https://brendan.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/the-fortress#contents

@scd I've added just the parentID to the annotation atom which is enough for anchor linking within the same page. But for the edge case where you link to an annotation on a different node, can you please add template data to the annotation atom for it's parents node details, just enough to build a url. If you prefer, please only do this is the annotations parent is different to the topos base node if you want to same data.

**Comment by scd** [comment]
this is great, i have done the parent

**Comment by brendanheywood** [comment]
We need to make a couple business decisions to close this one off:

1) numbering policy: ie do we include annotations in the numbering order. We don't need them to be included for any particular reason even if they are in the topos, so I think we should leave them as they were. Was there a reason this was changed?

2) annotation locations: I've temporarily commented out the new code which exposes the location or lack of a location of an annotation. This creates a large dependency on more changes to the maps code which we don't need to do now so I think this is already decided for us.

I've cleaned up all the remaining relative vs absolute anchor bugs in all the different topo contexts, so @scd  if you can sort the number stuff then I think we are done

**Comment by scd** [comment]
@brendanheywood this issue is now sorted as far as I am concerned. Please review and close.

final changes were:

  * Can create topo via existing photo so I can test the create topo process more easily :)
  * No topo route numbers displayed in topo route selection
  * Clearer display of routes (with grade etc), annotations and areas in topo route selection by hooking into existing templates.
  * For area topo page we use '-' instead of an annotation number
  * Topo object numbering only for routes and areas.

**Comment by brendanheywood** [comment]
Looks good, small task for myself:

* [ ] hover highlight events for annotations

The use of the route template looks great, we should migrate to that across the board in all the processes
