### ISSUE TITLE
can not edit location on mobile device

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#1694]
Several times I tried to update/edit locations of crags using the website but the map UI does not work for touch input. Please fix that.

Occurs on Sony Xperia Z Tablet using Chrome browser.

**Comment by lordyavin** [comment]
Any updates?

**Comment by scd** [comment]
@brendanheywood this seems fairly important. I cannot seem to manage to update a map using my andriod either. Any thoughts?

**Comment by brendanheywood** [comment]
This isn't so much a bug fix as a rewrite - there are whole legacy javascript libraries which were never designed for touch and are pretty dreadful. Vague plan is to probably use leaflet editing libraries. No eta

**Comment by lordyavin** [comment]
I understand. But editing on my tablet is as important as doing it on the desktop.

**Comment by brendanheywood** [comment]
Yeah I feel your pain, there are large parts of the site which need the guts ripped out to get proper mobile / touch support. Mobile is almost overtaking our desktop stats

**Comment by Mdemaillard** [comment]
revived in #3613 #3506 #3507 closing here as this was before the map rewite
