### ISSUE TITLE
Grade context of climber used instead of crag

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1703]
eg a person from malaysia (FR grades) just made a new route in the Gramps:

http://www.thecrag.com/climber/alvinknj
http://www.thecrag.com/climbing/australia/grampians/northern-wonderland-range/route/589803117

and it comes out with the wrong context:
![image](https://cloud.githubusercontent.com/assets/187449/4839039/d4068c2e-5ff7-11e4-93dd-7020d5a8452b.png)

There are two problems:
- [ ]  the context is wrong (this card)
- [ ] even where this happens the grade should still not show like this see and the system is in the local context (can't find card?)

**Comment by Mdemaillard** [comment]
Closing after Release 81. Test cases above display corerctly with & without the system wide conversion.
