### ISSUE TITLE
Icon replacement of hash tags and language tags

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#1708]
Is it possible to replace some hash tags and language tags with icons in the GUI?

**Comment by Mdemaillard** [comment]
The language tag need has disappeared with the global translation via account setting language selector.
Some gear type icons are available in the topo tool

The "replace well-used hash-tags with structured tags" will be a case by case study ? To go further someone needs to list candidate hash-tags, possibly scanning the database for usage ?

**Comment by rouletout** [comment]
This works as eg :es: as can be seen here: https://www.thecrag.com/de/klettern/spain/area/1846162401 - closing
