### ISSUE TITLE
paginating activity streams

### ISSUE THREAD

**Issue by scd** [theCrag/website#1725]
Easy answer is to do our normal pagination. 

We probably want a facebook style pagination that brings in more data incrementally using api or embedding.

Our standard pagination will have problems with an activity stream that is highly dynamic. For example by the time the user clicks on page 2 there may be new elements so some of the page 1 elements may move to page 2. This is resolved by paginating on time stamps and only allowing the next page one at a time. 

There is another complexity. The underlying query has a date range. Any pagination is done in that date range without considering activity before that range. A query may just return 1 element, but still we should be able to go back further. Going back further would require adjusting the date range to an earlier date range.

**Comment by scd** [comment]
The way I am doing discussions (ascent and forum) is that they have an event date associated with the latest contribution. This will create re-sequence issues across dates.

The concept is that a discussion is an event in itself. If somebody starts the discussion on Monday, and a second contribution is made on Wednesday then the event is not duplicated but rather appears on the Wednesday part of the feed. This sorts out duplicate problems at the SQL level and makes many other issues a lot easier.

However we now have a resequencing issue which is not just about 'today', but could be historical. In other words the issues in 'Advanced case 3' above also apply to 'Edge case 1'.

For now let's assume we are going with month boundaries for standard stream queries. I think some sort of date boundaries will be required for performance purposes and standardising creates more opportunities for caching.

Let's define a current stream as a query in the same month. For example if it is currently August then the current stream query would be:

/stream?start=2015-08-01&end=2015-08-31

And an historical stream query would be:

/stream?start=2015-07-01&end=2015-07-31

The use cases we need to cater for in the stream:
 - [ ] page refresh on current stream: happy with our caching as it is now, only reload if there is a change to the top entry
 - [ ] page refresh on historical stream: happy to use long lived expires, however this may not be accurate as a discussion may have been pulled from the long lived expired and put into the current. This also applies for other settings like people making switching themselves to private, or deleting ascents. Actually the private issue is possibly serious, so maybe we should think about this assumption a bit more. The browser caching solves two problems, data transfer and server resources. If we don't worry about server resources then we have more options for caching only if it is accurate (eg create a hash and only cache if the hash matches).
 - [ ] a month long stream query could return a lot of results so we need to paginate. As you discussed above want to do something better than record number pagination. Can we paginate on some sort of record identity. If order is invariant then yes we could, but order is not invariant in stream queries. Can we work around these issues? See notes below on invalidating a stream pagination result.
 - [ ] pagination boundary on a record that has had it's sequence moved to the top (for example another ascent added, or a discussion comment). The record was the 100th entry at the first pagination border. We expect the second page to return starting at the 101st entry next. However the record was updated and it now becomes the 1st entry, so the second page query now returns starting at the 2nd entry. 
 - [ ] pagination misses a record because it is resequenced from the second page to the first in the time between two queries. Streams do not have to be 100% accurate in this regard. I think we can safely ignore this edge case. Next time the person refreshes the current stream it will be back in.
 - [ ] empty stream result. If we are using a url then we should return an empty result, however maybe we should have javascript management which goes and gets the next month.
 - [ ] small stream result. Same as for empty stream query if it returns less than a minimum number of results.

The way I see it, is the biggest issue is resequencing of an event that occurs a pagination boarder. I think we just invalidate the query result and return an error and let the javascript worry about it. If we use the last update date to validate then we would be able to detect this case

/stream?start=2015-07-01:eventidentity:lastupdated&end=2015-07-31

If we paginate using a record identity and it's last updated date has changed then we know the results are bogus. Javascript then has to decide what to do, presumably it may refresh the stream again from the very beginning.

So pushing some of the issues into javascript land on our webpages could sort out some user experience issues, but what about embedding. We want people to be able to embed streams on the website. 

If somebody does a straight stream query without dates:

/stream

The server will use the current stream query which may be paginated or return none or few results. Pagination is absolutely fine for embedding. I guess I am also ok with no results being returned, and leave it up to the person embedding to create a more explicit time window. Eg blog or gym page:

/stream?windowsize=6months

which will expand the default current stream query from 1 month to 6 month window.

**Comment by scd** [comment]
I have done some testing using month windows for stream queries. Note that there are about 2500 events in a month of which we probably want to limit to 200 returned for any one query. Note that on my server a count(*) of these records is about 25mS.

The streams query is actually doing a lot and I have reworked it so it has select layers. 
 - [x] base select: the inner layer is a series of base queries (eg world, watching fav crags, following linked accounts), which can cause dups on event id 'why' field. About 50ms for the months data (it will be less than this because this includes saving the data to a file).
 - [x] union select: union of base select queries, dedup event, collate why, and collesce a last update date from create date and last updated date. No tangibile increase in processing time.
 - [x] permissions select: check privacy records for the privacy account associated with the event. Note that every event may have a privacy account associated with it. If this is set then we must check that accounts configuration to see if the person making the query can see the event. This involves two left joins - one to get privacy account settings and one to see if you are a linked account to the privacy account. This makes this a fairly expensive step and processing time goes to 150ms
 - [x] paginate select: if a pagination record has been set then we filter out all the records before and including the pagination record and return up to a limit of records. This means all the de-duping must be done. At this stage I have already done the privacy filtering and the privacy should really be done as well (maybe we could split the pagination so filter happens before the permissions step and the limit happens after the permissions step). Use of internal variables to make this happen. No tangible increase in processing time.
 - [x] collect activity select: the final step is to coalesce all the activity data associated with the event. This is a join with the activity records, plus another join on the account record to make sure the account has not been disabled. This query comes in at about 200ms.

The above tests were on world events. If I do the query on the crags I am watching and the people I am following then the query is a bit longer, but still comes in at less then 300ms.

This is on my server. I think timing will be significantly faster for our production server. We can also reduce the number of events down from 200, which is a lot. 

Of course we can greatly improve the speed if we had a smaller window, but then we would lose the caching benefits. I think we should press on with using the month window as a default.

I am actually pretty please with this as a first attempt.

**Comment by scd** [comment]
If we make the number of events returned a soft maximum limit (ie we ask for 50 records, but could get 30) then I can do some further optimisation by using a LIMIT on one of the inner queries before we do the expensive permissions check. Most events will be public, so if we make this 4x the soft limit then most of the time we will get a full 50 records in a page, but sometimes it may be less. I am still testing this, but it looks like I am getting a 30% improvement in performance. Doh, I have just noticed a bug as it is not returning some of the records it should be returning. The two benchmark queries I will complete are:
 - [ ] month query for world
 - [ ] month query for combined watching and following

(note that area queries should have similar performance to world queries because there is a direct index).

**Comment by brendanheywood** [comment]
Looks pretty solid. Did you want to tease apart the idea you had the other day for why we may still need to old feeds to hang around?

**Comment by scd** [comment]
see #1982

**Comment by scd** [comment]
Also I did the timing for the two critical queries and I am really happy (125ms and 210ms). I experimented with extending the month window into a 3 month window and it blows out more than proportionally for the later query. One month base window it is, for account streams.

**Comment by brendanheywood** [comment]
Out of curiosity what about the other way with a short window? What does 2 weeks turn out as?

**Comment by scd** [comment]
92ms & 138ms

**Comment by scd** [comment]
I have completed pagination work now - facebook style updates with a more button at the bottom of the screen. I need to update dev so you get the migrated table data before you see it in action.

Main components of the javascript implementation are:
 - [x] clicking the more button gets the stream html page (with pagination references) as an embedded document then appends the results to the stream.
 - [x] if somebody stuffs around with the last update date of the boundary pagination record then the emedded document will return an error rather than an incorrect list.
 - [x] when you get to the end of the current stream window javascript makes historical stream query.

**Comment by scd** [comment]
I am closing this, but happy to reopen if there is anything tangible left to do. There are still a lot of other stream issues to work through, this one is just the pagination.
