### ISSUE TITLE
Show informations grade and height on multipitch routes

### ISSUE THREAD

**Issue by theSCRAG** [theCrag/website#1732]
Some views have less or no information about multpitch routes.

View list of routes:
http://www.thecrag.com/climbing/austria/plombergstein/area/317822793
(only the length is a incator for a multipitch route)
Maybe a icon or number of pitches could shown? 

More worse is the view of a route:
http://www.thecrag.com/climbing/austria/plombergstein/route/363445101

e.g. "Äskulap" Height: 150m Pitches: 9 is shown in header.
There are no informations about each pitch. 
These fields could only seen in editing mode:
grade: 4+,1,3+,3+,3+,4+,3-,3+,2
length: 15,5,15,15,25,20,15,25,15
It's useless to add these informations if they are shown nowhere.

Shown detail informations on page like that:
*1.Pitch: 4+ 15m
2.Pitch: 1 5m
3.Pitch: 3+ 15m
...
8.Pitch: 3+ 25m
9.Pitch: 2 15m*

or in after order:

*9.Pitch: 2 15m
8.Pitch: 3+ 25m
...
3.Pitch: 3+ 15m
2.Pitch: 1 5m
1.Pitch: 4+ 15m*

**Comment by scd** [comment]
I have done this in repo. The template data now in includes a pitch field

pitch => [{
  grade => 'xxx',
  height => 'xxx'
}]

both height and grade are optional. If there is a grade in the list then the template formats using the 'Breakdown' label. If there are only heights in the field then the template puts the pitch heights next to the Height label as per issue #1314

The pitch information is obtained purely from the height and pitch data. Currently I do not do any parsing of the markdown. Once we have done #1769 then we get this for free.

**Comment by scd** [comment]
FYI, if you test this then the node cache needs rebuild, or edit the route then test.
