### ISSUE TITLE
General via ferrata issues

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1753]
See Cris's work here:

http://www.thecrag.com/climbing/italy/northern-italy/val-daosta/route/350885685

Some ideas:
- [x] relabel 'height' to 'length', possibly everywhere across the board
- [x] why are the long markdowns being show with class=oneline in a single column??
- [ ] another anoying tlc bug, we should not need a TLC above a via ferrata or anywhere:
  ![image](https://cloud.githubusercontent.com/assets/187449/5408653/f1afd9bc-8232-11e4-8059-2fc7d43b3cff.png)
- [x] paragraph indents look weird in this use case: #1760
  ![image](https://cloud.githubusercontent.com/assets/187449/5408681/65a096cc-8233-11e4-91c9-4c97beff9b53.png)

**Comment by rouletout** [comment]
This is actually all done, closing.
