### ISSUE TITLE
Make a semi regular process to remove / delete / disable / archive dud accounts

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1758]
There is a long tail of many users who login via FB or google, look around and never come back. If they have done nothing, then deleting their account means no data is really lost. If they haven't logged in for say a year I think this is pretty safe to do.

I'd probably do this side by side with an alternate email where people do have lots of data but haven't logged in for ages, a 'We've missed you' email.

**Comment by rouletout** [comment]
Not doing, closing
