### ISSUE TITLE
Show which grade systems in use, not just grade context in headline stats section

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1759]
Ie instead of showing just the context which is a concept specific to thecrag and a little arbitrary for most people, break it down into the grade systems.

So instead of this:
![untitled-1](https://cloud.githubusercontent.com/assets/8317061/5409123/7a16c1d2-8231-11e4-9fdd-4c10edbd6a51.jpg)

show this:
![image](https://cloud.githubusercontent.com/assets/187449/5422040/14a487e0-82c6-11e4-8f8d-d26206d6c451.png)

It would list the grade systems in the same order as the gear band order, and truncate when there are too many. I don't think we actually have the data yet to display this and we'd need a new set of statistics in parallel to the gear style stats. This probably needs a little thought to figure out what to store when multi systems are added for a single route, and could also be pretty useful for finding issues like wrong grades in a country, or V grades on a sport route etc

**Comment by rouletout** [comment]
Will not be done, closing
