### ISSUE TITLE
Help restructure

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1770]
From #1659 

Principals:
- try not to change the urls at all
- max of around 12 children per top level group
- top level groupings to promote discovery
- don't put too much info into top level pages as they will likely get skipped - make then just nice index pages with pics
- order of the top level groups should follow the typical user lifecycle, ie something like > getting around > downling guides > ticking > socializing > editing > embedding. same for children ordering
- grouped by how people use the features not by how they were implemented, ie move 'import and export' from 'extend' to 'climb (rename to 'log your climbs' 
- use the language of climbers / average users, eg 'geolocation' => 'Draw maps'
- **nothing** over the 1 year (need tools to help with this)
- decide on some fixed screen capture sizes and use it everywhere in the articles
- where possible use quick instant animated gifs instead of videos, find good tools for this (snagit?)

**Comment by brendan** [comment]
FWIW I get notifications for @brendan on Github since that's my username.
No biggie.  Just wanted you to know how that works.

**Comment by scd** [comment]
@brendan thanks for letting us know. We have already come foul of this before. It's one way of building a bigger community on github :) Anyway we will try and keep you out of it, but your name matches one of the developers, so it may happen from time to time.

@cgome, can you make sure you use @brendanheywood not `@brendan`.

**Comment by cgome** [comment]
Thanks, sorry.

On Friday, January 2, 2015, Brendan Baldwin <notifications@github.com>
wrote:

> FWIW I get notifications for @brendan on Github since that's my username.
> No biggie. Just wanted you to know how that works.
>
> On Mon, Dec 29, 2014 at 1:44 AM, cgome <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I just made some updates to
> >
> > https://github.com/theCrag/website/blob/master/Vision
> >
> > and then pressed 'commit changes'
> >
> > @brendan Can you confirm this worked as expected? Also is there a way
> for
> > me to do a WYSIWYG preview? Probably not a biggie but there's a chance
> > I'll
> > inadvertently delete a </p> pr something and tuff up the paragraphs.
> >
> > @simon The changes I've made are based on en edit Em did some time ago-
> > mainly getting rid of a few words, tidying punctuation, etc. Can you
> take
> > a
> > look at the para on Crag Guru and make any changes req'd. It mentions
> > 'Recommendations' and I think we were moving away from that. Do what we
> > used to call 'Recommendations' still appear? I seem to only be able to
> see
> > grade icons.
> >
> > Campbell
> >
> > On Fri, Dec 26, 2014 at 6:31 PM, Brendan Heywood <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> >
> > wrote:
> >
> > > Ok I'm gonna close this, all the content tweaks can flow through in
> > dribs
> > > and drabs
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/theCrag/website/issues/1770#issuecomment-68128652>.
>
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/theCrag/website/issues/1770#issuecomment-68243981>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theCrag/website/issues/1770#issuecomment-68511222>.
>


-- 
Campbell
