### ISSUE TITLE
Dead ascents page for Cris

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1781]
This ascent barfs the server:

http://www.thecrag.com/ascents/at/529383438/by/122728137

Can't reproduce in dev, will re-test after next release.

**Comment by scd** [comment]
Another link that is actually broken in dev

http://dev.thecrag.com/ascents/by/andreh/

This works:

http://dev.thecrag.com/ascents/by/andreh/?pageSize=1&page=5

This does not:

http://dev.thecrag.com/ascents/by/andreh/?pageSize=1&page=6

**Comment by scd** [comment]
I have just done a hot fix of this. Found an infinite loop in line 19 of crumbtrailPartial template. No stopping condition if there was no TLC in ancestor heirachy.

**Comment by brendanheywood** [comment]
doh!
