### ISSUE TITLE
Follow / unfollow button should have next to either a follow count / link to follow pages

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1782]
Either a blue link count like the fav count (which updates when you follow or unfollow)

OR a dropdown with links to both the follow and following pages

I think both would be too cluttered

**Comment by Mdemaillard** [comment]
Like the Favorites ? Then would you put there your follow count, or that person's follower counts ? (sort of a popularity score ? i don't feel thecrag needs to go there)
![image](https://user-images.githubusercontent.com/60388146/76700012-b3390f00-66bb-11ea-9112-e220fc25079f.png)

Maybe the drop down to your own follow/follower pages make sense.

**Comment by rouletout** [comment]
These numbers are shown on the profile page on top (clickable) and left (grey) - closing
