### ISSUE TITLE
at.js and select2 server / client side hybrid filter for speed

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1784]
From #1764 

> I think there is a strong argument to use exactly the same API call.

Functionally I agree. The only thing that sucks is the speed, which really we need to work on for both at.js and for select2. One thing I want to avoid is you type 'sc ... d' and the results for 'sc' come up, you press the down arrow to select it, and before you can press enter the next set of results comes in for 'scd' and blows your selection away. I think at.js does a slightly better job of merging these updated results and retaining your selection even if it has moved up, but I found select2 to be not as nice. In any case if you have typed '@sc' and only gotten 5 results, you know that you will never need to go back to the network for anything after that as you can filter it client side further and make it instant.

I don't have any problem loading 50 items straight up but only showing 10 if that means we only ever go to the network once. In almost every scenario's people will only have a couple dozen follows, and the crag context may have a couple dozen editors (if we only show editors or FA's, not just anyone with karma) so we could conceivably do this hybrid. All we need is to know is that the result set is complete, and add a bit more logic filtering client side - which I've more or less already implemented in my prototype anyway.

**Comment by scd** [comment]
We should test the speed on production server after release. If acceptable then close this issue.

**Comment by Mdemaillard** [comment]
no update since 5 years, closing.
