### ISSUE TITLE
brazillian grades encoded wrong in web forms

### ISSUE THREAD

**Issue by scd** [theCrag/website#1789]
From @henrique 

it looks like we have a encoding problem on "Please input the rating system grade details." > "* Range Limit" > "5Â°"
At least on my firefox on Ubuntu, we normally advise strict use of UTF-8 for non-english support but whatever works for you.

**Comment by scd** [comment]
@henrique, which page was this from so I can investige. I am assuming the issue is with web forms because it is right in the feed.

Behind the scenes, it was a massive time consumer getting the degrees working because it has both a latin and utf8 encoding. There was a long trail of fixes to make sure it was encoded utf8 everywhere. I am guessing the problem is that we have not specifed that it is utf8 encoded.

**Comment by henrique** [comment]
I was editing the routes here: http://www.thecrag.com/climbing/brazil/urca/area/12547147
One by one...
the page info encoding said win-1252, if i'm not wrong, but i didn't check anything else

**Comment by scd** [comment]
it looks like my response headers are not right for cgi-bin pages

returning 

Content-Type	text/html

Should return:

Content-Type	text/html; charset=utf-8

Note that it is ok for our template pages.

**Comment by scd** [comment]
ok fixed now. Please check again

**Comment by henrique** [comment]
it's good now, cheers
