### ISSUE TITLE
Second 'with' field in 'add shots' in ascent form isn't select2

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1794]
![image](https://cloud.githubusercontent.com/assets/187449/5611208/93bddad2-9517-11e4-99de-f3d1916f7496.png)

**Comment by scd** [comment]
Should be. I tested it and got it working. Maybe there is a regression bug

**Comment by scd** [comment]
hot fixed and in repo. 

Irritatingly I had changed function names just before the release and did not propagate the change to the other file. I was scratching my head for a while before the penny dropped.

**Comment by brendanheywood** [comment]
With these hot fixed js / css changes how does that work with the static filenames etc? Does this mean that the file is fixed, but the cache could be stale for some people unless they Ctrl+F5?

**Comment by scd** [comment]
No we have a procedure for that. I have bumped the version with an appended
'a'. So unless I have made a mistake it should be good
