### ISSUE TITLE
add #hashTag filter to photo faceted search

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#1795]
if in the long term hashTags should replace "trips" than a filter for hashTags in photo descriptions would be nice.

**Comment by scd** [comment]
@nicHoch this is mostly done as a hot fix in prod. I have not migrated existing photo description data. Could you please test this by uploading a new photo with a hash tag and updating an existing photo with a hash tag.

The facet search should pick up new and updated hash tags in photo descriptions from now. It will not pick hash tags before the hot fix as this will be subject to data migration. If is only a couple of photos then you can just update them and it should work.

Please let me know if you have a significant data migration issue with pre existing hash tags in your photos.

**Comment by nicHoch** [comment]
Hi Simon

both cases: update an existing photo and uploading a new one are working 
fine. Only issue is that the hashList in the photo search does not 
propose existing hashtags like in the ascent search - but if i enter a 
tag the filtering is working.

Nicky

**Comment by scd** [comment]
There might be some cases I did not test properly with the suggestions. Did you try uploading a photo at an area. 

See #1803 for hash tag suggestions in photos.

**Comment by nicHoch** [comment]
No the hash tag suggestions by writing the photo comments was working well.
But in the photo search form the hashTags are not proposed.

Nicky

**Comment by scd** [comment]
photo facet filter hash tag suggestions should in template data. 

I think this issue will be superceded by #1804, as we should be using select2.

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76395143-5833af00-637f-11ea-99a0-3f8ec8db0b0e.png)

seems select2 implemented. candidate for closure
