### ISSUE TITLE
Bug / differences in client vs server in mention suggestions

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1796]
I'm editing to replace Steve with ```@monty``` 'Stephen Hawkshaw'. Not only is he local karma, I've just edited 10 other routes and added him so he should also be in 'recently mentioned'.

Bulk editing context:

http://www.thecrag.com/climbing/australia/coffs-harbour/waihoo/area/157519482

'steph' doesn't work when it should:
![image](https://cloud.githubusercontent.com/assets/187449/5611283/c4a763ba-9518-11e4-9f71-d5f9ecd2adf1.png)

'st' does bring up some other random local karma person:
![image](https://cloud.githubusercontent.com/assets/187449/5611292/f9eed468-9518-11e4-9943-e1c9ec3ef358.png)

'monty' does work:

![image](https://cloud.githubusercontent.com/assets/187449/5611297/16651120-9519-11e4-991d-238e4a0140b9.png)

With several of these, he does flash up momentarily by the client side search, and then gets blown away by the server side search.

* [ ] So the client filter and server filter are different, the server filter appears to not be working with their name. The client regex matches anywhere in the name, but could be simplified to only match from the start of a word if that is what the server is doing (or will be / should be doing).

**Comment by scd** [comment]
yup the api call for both mentions and karma was missing the extra sql to also search for persons name. This was accidental for mentions but on purpose for karma.

I have fixed mentions for all cases. However I have fixed karma only if the search is in a top level crag (which it will be in most cases). The reason for this qualifier is that the persons name does not index nicely (left join) and it is a regex search (ie could be for last name), so I want to avoid full karma searches at world level. I think this is fine for crag level karma, but not region/country or world level karma.

The api component is hot fixed and in repo. Please test.

Do you want to do the word boundary client side? It would be an improvement, but not neccessary to hot fix.

**Comment by brendanheywood** [comment]
Yeah looks good. I'm happy with crag and below

**Comment by scd** [comment]
I have also added the word boundary in the display match. Hot fixed and in repo. So we can close this now
