### ISSUE TITLE
Tweak to select2 to make it clearer that unfound names can be added

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1799]
How to avoid Neil's confusion?

![image](https://cloud.githubusercontent.com/assets/187449/5638189/0f57d53a-9658-11e4-9d35-85c8c521273f.png)

Maybe make the blue highlighted row say "Add: 'unknown person'" ?

**Comment by brendanheywood** [comment]
I think this is a one liner option: selectOnBlur = true

**Comment by scd** [comment]
if it is that simple this needs to be hot fixed then

**Comment by scd** [comment]
I have hot fixed the bug and in repo. @brendanheywood  you want to add further help text?

**Comment by brendanheywood** [comment]
I'm not sure if we need to, that original thought was wrong until I got more info from Neil. So I'm happy to leave as is
