### ISSUE TITLE
Help restructure is different on prod to dev

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1801]
![image](https://cloud.githubusercontent.com/assets/187449/5641260/3b993568-9689-11e4-9863-d2646eaf425f.png)

This smells like a deeper issue with the new articles submodule, something isn't getting pulled right.

Or it could actually be a deploy problem. I think you deploy using rsync? Perhaps you are not deleting old files if they've been removed? If this is the case it might be worth reviewing this and moving to a git based deploy process.

**Comment by scd** [comment]
This is a little confusing and maybe I have missed something.

Prod is the same as my dev. 

I do a git pull-all as part of the release procedure.

I have set up my dev's articles as a git directory for articles and pull from our repo. I have just done another pull and it is up to date.

So either I have set something up wrong on my end or could you have forgotten to push?

**Comment by brendanheywood** [comment]
No the code is right, you can see that the 'labs' file is removed in the github UI. I don't think it's a git thing, I reckon's a deploy issue and I'm fairly confidant is an issue with however you are copying / rsyncing files to prod. It's the same reason there are a whole bunch of .swp files on prod as well because they get copied and never deleted.

**Comment by scd** [comment]
ahh gotcha. Actually I think it is how I am managing my local dev. It's wrong on my local dev, which is input to the prod release.

I will also check that the release does not introduce further errors.

I have probably forgotten a --delete somewhere.

**Comment by scd** [comment]
this should be ok now.
