### ISSUE TITLE
Grade context issue with Czech and Slovakia

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1802]
From new user:

> At first I would like to say, that I really appreciate amazing idea of thecrag.com.
> Then I would like to contribute with something. For this moment I will start with note about grading system:
> https://www.thecrag.com/article/Grades#context-US
> Czech Republic and Slovakia use UIAA grading system for routes and French Fontainebleau grading system for bouldering. At Czech republic is also used Saxon free rating system in sandstone areas near German borders.

Some of this is just the display of the context is misleading, see #1759, if instead of the context (US) it shows the systems in use (FR, or FB) some of it would make more sense.

But I think the contexts also needs some work:
1) The country context(s) are US, and should probably be either UIAA or French otherwise the UIAA grades will still appear as foreign
2) Even with that it doesn't solve the boulder issue, as French doesn't even use the Font boulder system in the FR context, and neither does the UIAA context, so boulder grades will appear as foreign
3) Same as above but with Saxon, not sure about this, would like to see data in the wild to help see if it matters

http://www.thecrag.com/climbing/czech-republic/area/246233400

**Comment by scd** [comment]
I think this has been done so I am closing. Although I cannot see what the default context is for Slovakia using the UI which I will raise as another issue.
