### ISSUE TITLE
convert hash tag facet search fields to select2

### ISSUE THREAD

**Issue by scd** [theCrag/website#1804]
- [ ] photos
- [ ] routes
- [ ] ascents

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76395236-8618f380-637f-11ea-9a68-d56ab1ae2a59.png)

![image](https://user-images.githubusercontent.com/60388146/76395251-903af200-637f-11ea-9d1d-cda635e66910.png)

![image](https://user-images.githubusercontent.com/60388146/76395279-9c26b400-637f-11ea-8191-a4f9c9b5e3ba.png)

Implemented. candidate for ticking boxes & closing
