### ISSUE TITLE
account karma for FA mention / completions for FA

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1809]
If someone is a prolific route developer, but not much of an online presence, they may have an account (user A) but never use it, or use it sparingly. So they may have zero karma, and importantly zero karma in a crag that they've done a lot of development in. Once someone (user B) has started to add them as the real linked FA, and someone else (user C) edits another route, then user A should pop up in the suggestions. One way we could do it is just add an extra search mode which is mentions by anyone, not just mentions by you, like this:

![image](https://cloud.githubusercontent.com/assets/187449/5694738/9c7f6b3c-99cb-11e4-8f30-c798df10424c.png)

One extra benefit of this is that we could even autocomplete for people who don't have accounts, ie show the top prolific FA'ers, to help fix spelling inconsistencies, and this is almost the start of the pseudo historical accounts #1518  

Or a completely different tack might be to assign some karma to the FA person so they crop up in the normal search. I think this is the first time we'd consider an action which assigns karma to someone else. But I think it would help reflect the real world contributions.

Some real examples, Gerry in Tas who put up essentially everything in northern tassie
http://www.thecrag.com/climbing/australia/fingal-bare-rock/route/622920282

And another prime example would be Mikl

This would really come into it's own in conjunction with the batch history editor #558 

Probably a few things to consider when setting the amount of karma. Would we say it's worth more to put up a 100m sport climb than a trad route? More again than a V2 boulder problem? How do we handle if the FA is changed? What is the type or height is edited? Should we just ignore this and make it a token minimal amount?

**Comment by rouletout** [comment]
History updates earn karma, closing
