### ISSUE TITLE
Change to ascent/grade band graph

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1813]
I think the ascent/grade band graph would look much better in a bar graph - similar to the seasonality graph - than in it's current form. Some more granularity would also be nice - maybe not a bar for every grade, but a couple of grades per bar? 

Or if you were to be super fancy, adjust the granularity depending how many climbs there are. 

Pretty minor thing, but I think it would be nice.

**Comment by brendanheywood** [comment]
I think would be good is some places, ie in the summary for an area, or as a chart when on someones profile, but the succinct thin bar works pretty well when there are lots of crags to show on one page like the normal list view. We could also experiment with a very slimline sparkline graph to see if it's could replace the band graph and still work when there is heaps of crags to show in a list.

Like this but still with the 5 colours:
![image](https://cloud.githubusercontent.com/assets/187449/5716111/ee856e30-9b39-11e4-8d37-a3537dbf358f.png)

**Comment by brendanheywood** [comment]
Notes to self, render as canvas and scale up a little:

https://developer.mozilla.org/en/docs/Web/CSS/image-rendering#Browser_compatibility

**Comment by brendanheywood** [comment]
This is already being done and selectively rolled out in various places

![image](https://user-images.githubusercontent.com/187449/41542504-752e0812-7358-11e8-9212-5af61e34954e.png)
