### ISSUE TITLE
Custom Grade Bands

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1814]
This may be more hassle than it's worth, but would it be possible to customize the grade bands per user?

For example, I think the low-end intermediate and beginner are indistinguishable (ie, I can't tell the difference between a 13 and 11 most of the time). 

So if I could adjust where the cut offs are for the different bands then the graphics would be more useful.

**Comment by brendanheywood** [comment]
Yeah this one is a hassle as it's tied to all the internal stats processing, it's not done on the fly as it would be way to slow so we can't personalise it.
