### ISSUE TITLE
Mentions suggestions should include 'you' especially for FA, area beta

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1815]
I thought we'd talked about this but couldn't find the issue, so add to make sure we don't lose:

![image](https://cloud.githubusercontent.com/assets/187449/5750767/533cfc66-9cad-11e4-9369-5415168c0fe3.png)

**Comment by scd** [comment]
This is a nice little improvement. I have added another category called 'You' which appears if your name or login matches. Only in repo at this stage.
