### ISSUE TITLE
Placeholder: review every topo in the system for labels

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1820]
Just using this to keep track of where I am up to:

Up to 1600 / 7000:
- [ ] http://www.thecrag.com/topos/has/mult-routes/?sortby=at,asc&pageSize=100&page=16

**Comment by brendanheywood** [comment]
Broken topos (malformed data)

http://www.thecrag.com/climbing/australia/nowra/new-nowra-braidwood-road/area/13247605/topo#t196043643

**Comment by brendanheywood** [comment]
http://www.thecrag.com/topos/has/mult-routes/?sortby=at,asc&pageSize=100&page=24

**Comment by brendanheywood** [comment]
http://www.thecrag.com/topos/has/mult-routes/?sortby=at,asc&pageSize=100&page=31

**Comment by brendanheywood** [comment]
http://www.thecrag.com/topos/has/mult-routes/?sortby=at,asc&pageSize=100&page=34

**Comment by brendanheywood** [comment]
http://www.thecrag.com/topos/has/mult-routes/?sortby=at,asc&pageSize=100&page=37

**Comment by brendanheywood** [comment]
http://www.thecrag.com/topos/has/mult-routes/?sortby=at,asc&pageSize=100&page=38

**Comment by brendanheywood** [comment]
An amusing topo:
http://www.thecrag.com/climbing/new-zealand/port-hills/area/394524225

**Comment by brendanheywood** [comment]
http://www.thecrag.com/topos/has/mult-routes/?sortby=at,asc&pageSize=100&page=43

**Comment by tomkjaerolsen** [comment]
Do you need a hand with this? Or is it easier with just one person doing it?

**Comment by brendanheywood** [comment]
That would have been sweet - but I've only got 5 pages left so I should finish that tonight.

As I go I am writing a bit of a 'best practice' guide to making great topos, and whenever I find something weird I fix it up and add it to the list.

Here is a rough checklist of things I am looking for and fixing, in no particular order:

For route topos:

* [ ] with link ups and shared segments move the labels onto the middle of the segment which is the most unique
* [ ]  on multiple pitch routes, if the label overlaps a belay from a previous route move it up so they don't overlap
* [ ] if two routes share a starting point, but no shared segments, move the labels away from each other to expose the start
* [ ] if routes share a segment the segments should exactly overlay each other. There is a new feature when drawing these where you can click on the first point they share, and then the last point they share and it will clone / copy all the shared points. But for existing routes but delete and re-add or drag them to where they should be. This is the most time consuming cleanup but makes a huge difference, and was mostly caused by a bug in the old topo where copied points where slightly off
* [ ] in some cases people have added 30+ points on a route, remove extra points that don't add any info. this makes the routes easier to edit and smoother
* [ ] some people have drawn a route upside down with the arrow head at the bottom (more common on topos made on the android app)
* [ ] some people have accidentally added 2,3 or up to 5 points which are all on top of each other, which forms a hard angle instead of a smooth curve. delete the extra points. Sometimes the hard angle is desirable so use some judgement on this one, but in most cases it's a mistake.
* [ ] on complex topos where multiple routes meet at an obvious belay, add the belay point which is much nicer than all the clustered arrow heads overlapping in different directions
* [ ] on long traverses it's useful to add multiple labels so it's easy to track the topo regardless of where you look without having to trace it back to the start
* [ ] it's really common for people to only draw the linkup section, but ideally all routes should be the full route, so clone the missing bottom and top segments
* [ ] sometimes routes near the edges have the label partially off screen, move the label up so it's fully in view


For area topos:
* [ ] simple shapes tend to look better, the shape should include the cliff and a bit more margin around the edges so it's not obscuring the cliff itself
* [ ] where the labels are better away from the shape, draw an extra connecting line to the label (much better than the 'arrow' option)

**Comment by tomkjaerolsen** [comment]
Definitely agree regarding the linkup (also applies to variant start, finish climbs).

**Comment by brendanheywood** [comment]
finally done. now to write up the checklist...

**Comment by brendanheywood** [comment]
fyi that topo article checklist is here, closing this one

https://github.com/theCrag/website/issues/2630
