### ISSUE TITLE
Recent contributions feed - profile page - not working

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1821]
If you go to someone's profile page:

eg: https://www.thecrag.com/climber/snappy

Scroll to the bottom, there is a "recent contributions" feed. Doesn't worker - feed is blank . This actually hasn't worked for a long time, I just never got around to reporting it before.

Tom

**Comment by brendanheywood** [comment]
Yeah we know this but won't fix this exactly. We are in the middle of a major rethink / rewrite of all the feeds into what we are calling 'stream's which combined all sorts of ticks, updates, etc. So under a profile you will see a stream of that persons ticks, updates, what they have fav'ed, where they have been mentioned etc all in one place without the different tabs.

Not sure if you've seen it but you can see the work in progress here:
http://www.thecrag.com/stream

This will probably take a few months to get right before we swap it over.

**Comment by tomkjaerolsen** [comment]
Is there an issue # for stream comments? I have been playing with it the last few days, mostly I think it's awesome, there a just a couple of slight interface tweaks I think could be made.

**Comment by scd** [comment]
We currently don't have a general issue for the stream improvements, but rather a number of specific issues that need to be looked at. Here is the search url for those:

https://github.com/theCrag/website/issues?q=is%3Aopen+stream

If there is anything that is not covered by these then create separate issue(s).

**Comment by brendanheywood** [comment]
Or feel free to tack more comment onto this issue, I've already moved it into the 'streams' milestone

Note the draft stream concept is only working at the dashboard level, but pretty the same thing will also be visible on a profile page for others to see (minus private stuff) and also at a crag level to see unified updates and ticks at that crag.

**Comment by scd** [comment]
As I am sorting out some profile page stuff I have fixed recent contributions on the profile page - low hanging fruit. I will convert to streams later when we have finished the streams work. I think we can close this issue
