### ISSUE TITLE
Removing spam messages may cause stale unread message numbers

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1822]
This has only just happened in the last couple hours since since the removal of that spam. Seems too much of a coincidence

![image](https://cloud.githubusercontent.com/assets/187449/5791305/78fcd78a-9f20-11e4-992a-9b8ff13298b2.png)

**Comment by scd** [comment]
I think there could be an edge failure case for some accounts for a limited period of time when I remove spam messages.

**Comment by scd** [comment]
I have added the last message updated to the cache key for counting unread messages. This means messages with status update will trigger a recount. In repo
