### ISSUE TITLE
Route descriptions replaced with ethics text in topo edit page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1823]
Lots of routes have a generic chunk of text as their description:

http://www.thecrag.com/climbing/australia/glasshouse-mountains/tibrogargan/area/12229051

![image](https://cloud.githubusercontent.com/assets/187449/5809544/c771b430-a08d-11e4-949d-25c22acc1a26.png)

This is not the text in the routes:

![image](https://cloud.githubusercontent.com/assets/187449/5809607/786baafc-a08e-11e4-8deb-02f14c205a47.png)

**Comment by scd** [comment]
doh, I missed this in the release. It is happening because ethic is now inherited down to the route level. There are places where this needs to be excluded in the templates, which assume a single route description. I thought I got them all, but obviously missed this one. Maybe there will be other places I missed as well.

Hot fixed and closing

**Comment by brendanheywood** [comment]
this isn't fixed in prod?

http://www.thecrag.com/climbing/australia/morialta/area/12317725/topo#t288932523

![image](https://cloud.githubusercontent.com/assets/187449/5816605/0abf7eb2-a0f6-11e4-8c75-e245560b9b55.png)

**Comment by scd** [comment]
actually different bug. this was the topo template, I fixed the route facet. Maybe you were refering to the topo template originally, but I assumed it was the facet.

Anyway there are probably a few other templates where this is lurking.

**Comment by scd** [comment]
BTW, hot fixed.

**Comment by brendanheywood** [comment]
yeah it was the topo page all along, thinking out load other places to check where route text is shown would be the update feed(s), streams

Also looking at the diff, is the inheritedFrom key guaranteed to be last after the main route desc? otherwise this would silently hide the main route desc

!$record->{beta}[0]->{inheritedFrom})

**Comment by brendanheywood** [comment]
quick audit: nodes search facet, route page meta tag description, kml and gpx export (if we cared) all look like places where this would leak. should refactor into a route markdown template and do it in a single place

**Comment by scd** [comment]
agreed, but I think it should be a beta template which works for areas, routes and annotations. This does not stop us doing a route template as well. If you agree please create another issue.

BTW the I am pretty sure the order of descriptions is consistent but this was never discussed as a hard and fast business rule so we should not rely on it in the long term. All other places I have put it in a for loop, it is just for the topo template I thought I would make it consistent with what was done for the area field. If I put it in a for loop then muliple descriptions will come through (in the area nodes), which I am not sure you want.
