### ISSUE TITLE
Crags vs regions cleanup bug with PDF

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1827]
Just ran into another issue with the region cleanup from @tomkjaerolsen 

https://www.thecrag.com/climbing/australia/northern-rivers-urbenville

This kinda should be a region, and was a crag, so I changed it - but then he couldn't download the PDF's for that node. So we should probably make the PDF logic linked to node size and not type, there is no reason why I shouldn't be able to get a region level PDF (apart from most of them being massive)

**Comment by brendanheywood** [comment]
See #1807

**Comment by scd** [comment]
Agreed.

Do we really want people to be able to create a PDF for say the whole Grampians - 10k routes. 

We toyed with the idea of limiting PDFs for supporters only. What about making limits like, somebody not logged in can get a PDF for up to 200 routes, logged in then they can get 500 routes, supporter then they can get up to 5000 routes?

**Comment by brendanheywood** [comment]
We already have a route limit in place, we just also have an node type limit as well. We should just remove the latter. The grampians is a reverse example, it's currently a Crag not a region, but regardless we probably shouldn't let people make a PDF from it.

I'm cool with the bigger pdf's for supporters idea but this will still have technical limits which we need to fix first in the pdf pipeline.

**Comment by scd** [comment]
Note that currently we cannot get a static pdf of a cliff, it has to be a crag. Now that we are using route numbers I propose to simplify this so that you can get a static pdf of any area as long as it has at least one route and not more than a maximum number of routes.

This means that the number of static PDFs will change from 14k to about 40k. This means, that in order to rebuild the static PDFs monthly we have to change the rate from 20 per hour to 60 per hour. I will got for 100 per hour to allow for some growth.

**Comment by brendanheywood** [comment]
I'm not too worried about the static ones, they could stay as is - as long as you can build a custom one at various levels that is probably enough.

**Comment by scd** [comment]
I have made a hot fix of this as it involves static and production server updates. It easier to just do the fix now then document all the fiddly bits to test and change during the upgrade. 

The other thing is the sooner we get the new static files generated the better. And I am pretty keen to get the message out there saying that some PDF features will be only available to financial supporters.

**Comment by scd** [comment]
Do we have any way of using Google Analytics for static PDF use, or do we have to go through the apache logs on static server for this. I have a feeling that the static pdfs get used a lot more than the custom ones. It sort of satisfies ones need for instant gratification.

**Comment by brendanheywood** [comment]
You can trigger a pseudo pageview event for any link, pretty easy

https://support.google.com/analytics/answer/1012044?hl=en#Download

**Comment by brendanheywood** [comment]
http://stackoverflow.com/questions/23538143/attach-onclick-analytics-tracking-code-in-a-href-link-using-jquery

**Comment by brendanheywood** [comment]
although it may actually be useful to not send the real url, but send something like

http://www.thecrag.com/climbing/australia/cape-raoul/11744779.pdf

instead of

https://static.thecrag.com/pdf/11744779.pdf

so we can better track where downloads are for and not some random opaque id

**Comment by scd** [comment]
The static server is just a dumb apache server without any of our smarts in it, so we will either need to make it fully functional, create a directory structure for pdfs being saved or use some clever url rewriting.

**Comment by brendanheywood** [comment]
no this is purely in JS land, nothing to do with apache at all. In js you intercept the click onthedownload, fire of the GA event, with a fake url, then allow the click to proceed to the url

GA doesn't know or care that the url isn't real

**Comment by scd** [comment]
Yes, I understand. Fake the url for GA, but continue to use our existing url for the actual download. Much easier.

**Comment by scd** [comment]
reopening as a place marker for the GA update.

**Comment by scd** [comment]
The GA stuff is done now. The fake url is:

/climbing/australia/arapiles/bushranger-bluff/download-11764447.pdf

ie normal area url followed by the '/download-ID.pdf' trailer.

Thinking out aloud we have a url:

/climbing/australia/arapiles/bushranger-bluff/pdf

Which is the unpublished direct link to pdf generated on the fly. Do you think we should just use that as our fake url?

**Comment by brendanheywood** [comment]
hmm it's appear in GA as /https://static.thecrag.com/pdf/11764447.pdf

debug in GA

https://www.google.com/analytics/web/?pli=1#realtime/rt-content/a18400027w37021774p36509867/

Real time > Content

or debug in chrome (tick preserve log in the js console or it will clear when you click on the download)

https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en

What fake url we use is pretty arbitrary, the main thing is it is different so we can tell it apart from other traffic.

**Comment by scd** [comment]
I think that was a bug I caught when first hot released. I stuffed around a little because of two typos which took me a while to see. So there are a few bad urls floating around.

It looks like it is coming through ok now though.

**Comment by brendanheywood** [comment]
yup re-tested and good
