### ISSUE TITLE
Forum usability low hanging fruit - leave discussion, mark all as read

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1828]
- [x] in the dashboard there should be a button to leave a discussion permanently
- [x] in the discussion there should be a button to leave a discussion permanently
- [x] in the dashboard the 'mark all as read' button should always show even if there is only 1 message, I use it almost every day, and when there is only a single message the button isn't there when I expect it to be
 - [x] review notification email logic ( email-discussion-notifications )

**Comment by scd** [comment]
leaving a discussion permanently may not be low hanging fruit. I need to look at the data structure and assess the cross impacts of deleting the record that connects you to a discussion. I think it will look like broken data in some instances. If somebody sent a message to you, the only way that you  can leave the discussion is to remove the record which originally made you the recipient of that messge.  I imagine I would need either another field, another state, or change logic using the disabled field. I think this is a similar problem to the 'watching' forums issue. Once I get started on this I will end up going down the rabbit hole. I propose to leave for a while.

Fixed the mark all as read for forums you are following. Question - do we also want to have  a mark all as read button for messages in your inbox? It means you could potentially mark a message sent to you as read without actually opening it. While this is totally fine for forums, I am reluctant to provide this functionality for inbox. I could be swayed by other arguments.

**Comment by brendanheywood** [comment]
1) I thought we already had leaving a conversation in place, I was expecting this to be purely cut and paste of a bit of UI that was elsewhere (but I can't find the UI I assumed existed) (guess this is covered by #783)

2) I'm fine without a mark all as read for inbox messages, they aren't the ones which are pseudo spam that I want to ignore. I'm also totally fine with allowing it to, eg gmail lets me do this with two clicks, one to select all and one to mark. I'd like to gradually move that into a more inbox style so the two step might make more sense in the future

**Comment by brendanheywood** [comment]
+1 from @lordyavin https://github.com/theCrag/website/issues/2853

**Comment by brendanheywood** [comment]
+1 from https://www.thecrag.com/discussion/1967360091/hey-everyone-i-have-just-noticed-a-few-places-with-top-rope-projects-and-top-rope-first-ascents-fo#m1996810644

**Comment by brendanheywood** [comment]
@scd given the previous round of forum polish, how much effort do you think is left to get this last bit sorted? Should we aim for this in the next release and that would tick off the last of the major items from https://github.com/theCrag/website/issues/1449

**Comment by scd** [comment]
There may be a data structure issue. There is a possibility that the system assumes the record we use to be involved in a forum is also required if you have either started the discussion or posted in the discussion. 

Given the list of things on the next release already, I don't think I can touch this just yet.

**Comment by brendanheywood** [comment]
Ahh there is also possible the most important part which may have been lost:

We need to show transparently why someone is getting notifications for a thread. This is mostly solved by the watching widget above, but we would need to refine it to properly show the cases where you are still in a default state of watching because of a node subscription. This is now vastly improved at the forum level but we don't yet have this in the thread itself. I think the reason for a notification should also be reflected directly in the dashboard too.

**Comment by lordyavin** [comment]
I like the need to opt-in if I get mentioned in a thread. Too much automatic subscriptions pollute the inbox and make it difficult to stay focused.

**Comment by brendanheywood** [comment]
This is still a high priority but will be moved to the next release

**Comment by brendanheywood** [comment]
Another +1 
https://www.thecrag.com/discussion/2007501846/world--climbing-graphic-designer-needed

**Comment by lordyavin** [comment]
+100 😉

**Comment by scd** [comment]
I have made a lot of progress with this one.

 - [ ] You can self join a discussion (ie without contributing and without being invited) so long as it is associated with a forum.
 - [ ] You can leave a discussion (and join back in) which means it will not come up on your dashboard. This is available on a discussion, dashboard and I have closed a consistency loop in personal messages.

![screenshot from 2019-02-05 15-59-31](https://user-images.githubusercontent.com/373058/52254242-d80f6e80-2960-11e9-81d1-5137edcf15f1.png)
![screenshot from 2019-02-05 15-58-50](https://user-images.githubusercontent.com/373058/52254243-d80f6e80-2960-11e9-9dc6-7ce66dc57a1f.png)
![screenshot from 2019-02-05 15-58-43](https://user-images.githubusercontent.com/373058/52254244-d8a80500-2960-11e9-8079-c97702007c39.png)
![screenshot from 2019-02-05 16-12-41](https://user-images.githubusercontent.com/373058/52254255-f37a7980-2960-11e9-8a43-a0926135a718.png)

**Comment by scd** [comment]
I think there are a few edge cases and the definitions are not quite the same as 

  * **watch** forum (eg release or area forum). Unread discussions from forum appears in your dashboard except for discussions you have left. If you are watching an area then ancestor area and descendant area/route discussions are include. 
  * **unwatch** is reversing a watch. You cannot unwatch an ancestor or descendant node to block discussions.
 * **invite** invites somebody to watch a discussion. The person has no opportunity to accept or decline, but can leave a discussion. 
 * **participates** means that an account has contributed a comment in a discussion. The account can leave a discussion that they have participated in.
 * **join** means that an account can self nominate themselves to a public discussion (associated with an area or topic forum) or join back into a discussion they have left.
 * **leave** means that an account has left a discussion so it will not appear in their dashboard regardless of whether or not they are watching a forum.

I think this is sufficient for now.

**Comment by scd** [comment]
Reopening because I should assess whether the notifications email excludes left discussions

**Comment by scd** [comment]
This is ready for release.
