### ISSUE TITLE
#4 #4s being erroneously picked up as hash tag

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1829]
Route descriptions or ascent descriptions that feature a reference to a cam/nut/etc size picks it up as a tag.

Eg: https://www.thecrag.com/climbing/australia/cape-raoul/route/416312391

This looks a bit odd. Could probably for a regex to ignore #{1..9} in the tag/# thing?

**Comment by brendanheywood** [comment]
I actually see this as potential feature, if there were existing known tags for certain brands and cam sizes etc then there would be more consistency in route descs for these things. Could mean searching for route based on gear etc. Not sure how much use there is in that.

If the downside mostly cosmetic? I can work on refining the tag style in this context so it's less jarring

Are you in tassie now/soon by any chance? I'm actually gonna be at cape raoul tommorow

**Comment by tomkjaerolsen** [comment]
Mostly cosmetic. If you're wanting to do gear sizes then there needs to be a way to distinguish between brands and types of gear. Eg, #4 nut =/= #4 cam. Similarly a 4 BD is not the same as a 4 WC. 

Nah, not heading to Tassie any time soon unfortunately .... just dreaming while at work :)

**Comment by tomkjaerolsen** [comment]
Is it possible to do a regex for #{1-9) and then have a drop down list with a little pic of a nut, hex and cam show up? I think that would be cool. 

In terms of how much use it would get...not sure, I could see it being fun if you just bought a #6 for the first time or something, but you never know, somebody might make use of it.

**Comment by scd** [comment]
+1 from me for the idea of tagging gear and brands. Maybe it will help encourage the big brands to get involved as sponsors. Can we link brands to a url if the brand was willing to pay for that link?

**Comment by tomkjaerolsen** [comment]
On top of hexes, nuts and cams, definitely need a little alien symbol for when you need small cams!

**Comment by rouletout** [comment]
This is not happening anymore, closing
