### ISSUE TITLE
Look into making at.js dropdowns grouped and ordered like select2

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1830]
Loving the grouped dropdowns and I sorely miss it in the textareas. Reckon we can get this working with At.js as well. I'll raise this with at the source to see if can be in core. 

https://github.com/ichord/At.js/issues/244

**Comment by AnandAyan** [comment]
hi @brendanheywood  do you have any example code of how to do dropdwons grouped?

**Comment by brendanheywood** [comment]
In general using vanilla html? Or specifically using at.js?

**Comment by AnandAyan** [comment]
Not in General, using at.js ,was looking for some kinda of auto-complete (grouped ) in a content editable div .

**Comment by brendanheywood** [comment]
Nope, I was going to investigate this and push a patch up to at.js and possible will in future. They didn't seem interested in it though.

Roughly should be:

* allow an extra option 'group' attribute in the model

* modify the sorter to sort by group if present and then by normal method:

https://github.com/ichord/At.js/blob/3377178a2a2d827dc56efbf041ec05b5c4568afb/dist/js/jquery.atwho.js#L1021

* change the view to render the groups:

https://github.com/ichord/At.js/blob/master/src/view.coffee#L106

**Comment by AnandAyan** [comment]
that sounds cool,thanks  for your time mate.

**Comment by AnandAyan** [comment]
Hi @brendanheywood 
   for(var k = 0; k < item.items.length; k++){
          var newItem = {'atwho-at': this.context.at, name: item.items[k]}
          li = this.context.callbacks("tplEval").call(this.context, tpl,newItem , "onDisplay");
          $li = $(this.context.callbacks("highlighter").call(this.context, li, this.context.query.text));
          $li.data("item-data",newItem);
          $ul.append($li);
        }

by adding the following code in prototype.render i got my desired result .Let me know if this lets u get dropdowns grouped .

**Comment by scd** [comment]
Closing because we have not done anything with this issue for a long time an it is likely that any future fix here will be because of a major javascript rewrite.
