### ISSUE TITLE
Stream formatting bug,missing annotation count in summary

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1831]
When you make multiple updates, something is going wrong, I get:

Tom Kjaer-Olsen updated a topo, a , an area and some routes at Urbenville • 405  • about an hour ago
Created 1 topo and updated 1 area and 13 routes.

A cliff maybe?

**Comment by brendanheywood** [comment]
Maybe an annotation?

**Comment by tomkjaerolsen** [comment]
That could be it, I did make a new annotation

**Comment by brendanheywood** [comment]
Yeah pretty sure that's it.

**Comment by scd** [comment]
seems to be working on my dev now. Closing
