### ISSUE TITLE
Stream - enhancement for ascent comments

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1832]
When someone comments on an ascent you get something like:

Rob Medlicott commented on an ascent by Wade Stewart • about 13 hours ago

It would be nice to know when the ascent was as well as when the comment was made.

Maybe "Rob Medlicott commented on an ascent by Wade Stewart on 23 January 2015 • about 13 hours ago"

Or

"Rob Medlicott commented on an ascent on 23 January 2015 by Wade Stewart • about 13 hours ago"

**Comment by scd** [comment]
I think this goes away with the recent changes to streams.
