### ISSUE TITLE
Batch edit ascents in logbook

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1835]
Is there a process page for this? Would like to wire up batch retro editing of ascents instead of very tedious one at a time. Main use case is for me fixing up old mentions which is a very low priority use case, but if it's easy and already exists then great

**Comment by scd** [comment]
Does not exist. Not easy, sorry.

**Comment by brendanheywood** [comment]
closing as dup of https://github.com/theCrag/website/issues/2787
