### ISSUE TITLE
Stream - ascent references log-time not climb-time

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1837]
Ascents are listed based on when they are logged:

Tom Kjaer-Olsen went climbing at Kangaroo Point • 4 minutes ago

That post refers to a new log for a climb I did 5 years ago:

https://www.thecrag.com/ascent/628651035

Not sure the best way to show that, but the current layout doesn't quite work for me.

**Comment by scd** [comment]
This one needs a lot more discussion. This is the same problem we have with cross posting to facebook tick events.

The options are to
 * update your stream for 5 years ago (which creates all sorts of problems),
 * make it clear that your stream activity is updating historical events.

Maybe we just need a different event template.

"Tom Kjaer-Olsen logged historical ticks"

What happens if it is a mixed event. Nothing in the system will separate this as two different events, but rather a mixture of historical and current ticks. My feeling is that if there is any historical ticks then we should just make it an historical update event.

**Comment by brendanheywood** [comment]
@tomkjaerolsen can you also dump screen shots for stuff like this into github, until we expose the stream in more ways we can't see what you see. Will make it a lot easier for all

For this particular issue I see this as just a copy tweak:

Tom Kjaer-Olsen went climbing 5 years ago at Kangaroo Point • 4 minutes ago

**Comment by tomkjaerolsen** [comment]
Yeah, how about something like:

<7 days
"Tom went climbing at KP"

>7 days

"Tom logged climbs at KP from 2 weeks ago/2 months ago/2 years ago (etc)"

If it's a mix of different times then maybe

"Tom logged climbs at KP from today, 2 weeks ago, ?" 

Not sure 100% how you could code that, but you would need to I guess quantize it into groups ( recent (< 7 days), weeks (7days<28days), months (1<12months), years(>12 months) - and then re-quantize it into groups from there, eg, 2 weeks, 3 weeks and 4 months. Or something.

I think you might be better just having multiple entries in the stream much like you would if someone went climbing at multiple crags?

**Comment by tomkjaerolsen** [comment]
Ah, my bad! 

<img src="http://www.chossfest.com/photos/640x171xmain.php,qg2_view=core.DownloadItem,ag2_itemId=37,ag2_serialNumber=2.pagespeed.ic.fqU_gKx9KE.jpg"></img>

**Comment by scd** [comment]
Multiple entries in the stream is something I want to avoid as there are very clear business rules about how entries are aggregated. I cannot see clear rules when considering the ascent date (eg no date logged, partial dates logged). The stream is based on the activity date on a single day. So ascents logged on the same day, by the same person in the same crag are automatically aggregated. If we wanted to say there were two types of ascents (current and historical) then an extra aggregating flag would be required. If we were going to have the flag, then we need clear rules about how it is triggered. For example if you were logging ascents you did on Sunday when you went to work on Monday morning, is this historical? This is a lot of work so we would need to be absolutely sure about going down this path before spending the time.

My preference is to get this working by just changing the text in the template, which is not a lot of work.

**Comment by brendanheywood** [comment]
If there is a mix of retro routes then a catch all like simon said would be the simplest:

Tom Kjaer-Olsen logged old ascents at Kangaroo Point • 4 minutes ago

**Comment by tomkjaerolsen** [comment]
That's probably the simplest, if it's a mix of old and new it could be something like:

Tom Kjaer-Olsen logged new and old ascents at Kangaroo Point • 4 minutes ago

I think the mix of dates is going to be fairly rare, so it's probably not worth putting a huge amount of effort into.

**Comment by scd** [comment]
I think this is resolved in the streams release.
