### ISSUE TITLE
Stream - re-sequence area  appears as a route update

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1838]
I re-sequenced an area in the Grampians

Dream time wall: https://www.thecrag.com/climbing/australia/grampians/dreamtime-wall

It appears in the Stream feed as:

Tom Kjaer-Olsen updated a route at Grampians • 10  • 18 minutes ago
Updated the route ? Dreamtime Wall Mixed

This should be crag not route.

Also, the "Dreamtime Wall" link is: https://www.thecrag.com/route/12999487

Which is a /route/ index and should probably be the link I posted above?

**Comment by scd** [comment]
This was fixed in the last log of changes. There is some data migration issues listed in #2081
