### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1839]
I think the issue is to do with when your display has rolled into 2 columns. 

See here: https://www.thecrag.com/climbing/australia/grampians/dreamtime-wall
With 1920x1080 resolution.

I get this:

<img src="http://www.chossfest.com/photos/main.php?g2_view=core.DownloadItem&g2_itemId=38&g2_serialNumber=1></img>

**Comment by brendanheywood** [comment]
dup of #1805

**Comment by brendanheywood** [comment]
fixed
