### ISSUE TITLE
Text search results order should be smarter

### ISSUE THREAD

**Issue by scd** [theCrag/website#1840]
exact matches should appear before partial matches, areas before routes, more popular first.

**Comment by scd** [comment]
Eg

http://www.thecrag.com/nodes/fuzzy-search/clean%20cut?S=clean+cut&ST=w

Full matches of clean cut should appear first.

**Comment by MelwinQ** [comment]
Nodes within/below the currently active node should appear first (local search, subsearch)

**Comment by brendanheywood** [comment]
Has been rebuilt from scratch in next release
