### ISSUE TITLE
Topo edit at top right corner is not possible hidden behind buttons

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1844]
It seems impossible to edit points after they have once been placed "under" the hide / deselect button. Possible solution: Move the two buttons outside of the actual topo, i.e. just some pixels higher.

**Comment by brendanheywood** [comment]
yeah the plan is to move these to the editing panel on the left, and then also make the editing panel float above the topo and also be dragable

**Comment by brendanheywood** [comment]
See duplicate #1651

**Comment by lordyavin** [comment]
Duplicate of #1651

**Comment by brendanheywood** [comment]
Yeah I think I'll just close this and track it in the older #1651
