### ISSUE TITLE
Create box not available after archiving all gym routes

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1845]
If a gym feature is empty, the usual "This feature doesn't have any sub-areas or routes yet! - Create" box is shown. This is not the case after all the routes are archived (to add new ones) - one needs to add all of them seperately by using the menu instead of using e.g. "add 10 routes".

**Comment by Mdemaillard** [comment]
The box is not visible after the last archive, but reappear on a refresh.

**Comment by rouletout** [comment]
On top of that the button to add routes (incl. 10 or 20) is available, closing
