### ISSUE TITLE
host power user scipts for Greasemonkey/Tampermonkey?

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#1851]
Greasemonkey is a Mozilla Firefox extension (Tampermonkey is for Chrome) that allows users to install scripts that make on-the-fly changes to web page content after or before the page is loaded in the browser (also known as augmented browsing). The changes made to the web pages are executed every time the page is viewed, making them effectively permanent for the user running the script.

Greasemonkey can be used for customizing page appearance, adding new functions to web pages (for example, embedding price comparisons within shopping sites), fixing rendering bugs, combining data from multiple web pages, and numerous other purposes.

**If we motivate power users to write and provide there own user scripts - collect, unify, verify and host them - others users might benefit as well.**

for example:

https://gist.github.com/nicHoch/263d75ca4bfa8e85e91e/raw/92086fe21b3234e44289fefcfa881731dab2a9d2/AddRoutesHotKeys.user.js

this script adds two short cuts to the "add multiple routes" page.
**ALT+KeyDown**: jumps to the next route from every given route detail input field 
**ALT+KeyUp**: jumps to the previous route

**Comment by scd** [comment]
Won't power users capable of doing this be motivated already?

What happens to scripts when we change things on the page. I would not want this to become a version control issue for our web pages.

I wondering if there is a way of tying this to our issues list for feature enhancement demonstrations.

**Comment by nicHoch** [comment]
Yes users can already do such kind of scripting. I used that hot key script since a while. 

All we have to do is to provide a help page with some links to useful user scripts. If we see that some of the scripts are very useful we can implement that ones at server side. 

So it is more some kind of sandbox for new and tiny add ons on GUI level.

**Comment by scd** [comment]
from the point of view of sandboxing I think it is pretty cool. Let's see if @brendanheywood has some further comments then you can write something up as an article.

**Comment by brendanheywood** [comment]
If something fixes a bug, then we should just absorb that code and fix it for everyone. If it does something cool or adds some new feature which has general for all users then it should be added to core. I don't see this being something we'd every support, but it is a way to quickly experiment with stuff. The only gray area I can see if for features that are expensive in terms of bandwidth or complexity or bugs, but which has some strong appeal for a subset of users, and in this case it would probably be better of in the core code but behind an account setting.

The keyboard shortcut stuff is a perfect example - this has a good amount of general appeal, and could be a lot better universally across the whole site. It's on the todo list and is just a matter of time and priorities to get it done. Getting people to install a grease monkey script is never going to be mainstream and isn't something I'd want to confuse general users with by even mentioning it, but is a great way for you to get a prototype working. Probably the easiest and best place for power nerd users to share scripts like this is in this issue itself.

**Comment by lordyavin** [comment]
@nicHoch thanks for sharing the script and pointing out that extension. I like short cuts and the adding mulitple routes were a pain in the ass because I had to use the mouse to jump to the next route. With your script its much more convenient. Thanks again. Do you have more scripts like that for theCrag?

I think a help page that lists some power user scripts would be a nice thing to have, but I should be editable by the users who write the scripts. This may be somehow dangerous because the scripts could be used to install malicious software on the executing clients. Accounting the help page shall be editable by trusted users only.

**Comment by nicHoch** [comment]
@lordyavin hi Kai check this out: #77

**Comment by lordyavin** [comment]
@nicHoch I tried to download the script again but the browser blocks it because the SSL certificate seams to be suspicious. Could you provide an alternative URL?

**Comment by nicHoch** [comment]
@lordyavin Hi Kai i added the script in plain text as well

**Comment by lordyavin** [comment]
Sorry, I meant the AddRoutesHotKeys.user.js

**Comment by nicHoch** [comment]
[AddRoutesHotKeys.user.js.txt](https://github.com/theCrag/website/files/137980/AddRoutesHotKeys.user.js.txt)

Download and rename to: AddRoutesHotKeys.user.js
Open in Firefox and the Plugin will ask you to import the script.

**Comment by birgander2** [comment]
Hey, cool script Nicky! Thanks for sharing, this is really useful. Unluckily, I don't speak java script.

**Comment by scd** [comment]
@nicHoch can this be closed?
