### ISSUE TITLE
Expose crag kudos metric as data attribute for DDG to parse

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1853]
Easy low hanging fruit, enabled duck duck go to display to most relevant area in sub crag search.

Need to add the kudos metric to the template data for each area list view page, then add it as a data attribute, ```<div data-nid="1234" data-kudos="1000" ... ```

**Comment by scd** [comment]
also add it to the facet search for areas

**Comment by brendanheywood** [comment]
If it's a stat with no lookup overhead then just add it to the atomArea and I'll take if from there

**Comment by brendanheywood** [comment]
Had a bit of a poke around to see if this was easy and got a bit lost in the stats code :(

**Comment by brendanheywood** [comment]
Any chance we can get this one sorted soon, even just in dev? The duckduckgo guys have got their end sorted and this is the only thing left that they need

**Comment by scd** [comment]
Starred in my email. This will be my next priority - probably tomorrow.

**Comment by scd** [comment]
This is done.

 - [x] added kudos to template data - in repo and prod
 - [x] added data-kudos to body tag (I presume you meant body not div above) - in repo and prod
 - [x] added kudos to area facet search sort - in repo

I think this means DDG guys should be right to go using prod. 

Please confirm and close.

**Comment by brendanheywood** [comment]
Look great. I'll close when I get confirmation on their side that its all good

**Comment by brendanheywood** [comment]
They have fixed their scraper to parse this now
