### ISSUE TITLE
Logging an ascent before 2005 not possible

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#1855]
I know, I am a bit behind the schedule, but I couldn't log an ascent with a date before 2005: the dropdown doesn't offer earlier years. After skipping backward month-wise in the calendar, the range of the dropdown increased at some point.
Restricting the dropdown makes sense, but couldn't the direct textfield be enabled as an alternative for prehistoric ascents like mine?

**Comment by nicHoch** [comment]
you can disable the datepicker with the "pen" icon next to the date. Or within the datepicker just click once to year 2005 and than again on the year and that will add 10 more years. Repeat that until the cows come home.

**Comment by brendanheywood** [comment]
@MelwinQ can you provide some more details, including browser version and platform and a screen short?

**Comment by MelwinQ** [comment]
My fault, I didn't look thoroughly. thanks to Nicky for the explanation, sorry for bothering you. Issue can be closed.
