### ISSUE TITLE
icon for data created by the api

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#1858]
![screenshot 355](https://cloud.githubusercontent.com/assets/2226714/6211446/49250b88-b5da-11e4-8970-1b73936bef20.png)

The general idea to show that an ascent was logged with the API is very good. But the mobile phone icon is to one-sided. Allow each API key to set up:
- [ ] a separate favicon
- [ ] a web link 

And then
- [ ] associate each API date entry with the key
- [ ] show favicon as link to a webadress in each activity stream

**Comment by rouletout** [comment]
More current in https://github.com/theCrag/website/issues/2229 - closing this one
