### ISSUE TITLE
add Mixed style to help page

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#1859]
at http://www.thecrag.com/article/styles

add something like:

mixed:  A trad route is labeld as mixed if there is at least one registered bolt/piton - so bring a trad rack and some quickdraws.

**Comment by nicHoch** [comment]
upps already there

**Comment by brendanheywood** [comment]
The problem with help pages is that very few people read them. I'm slowly coming around to the idea that we should just change the behaviour of this so it's more obvious and what people expect. Ie that mixed is it's own type and can be set manually. But then that has knock on effects for searching etc and needs a lot more hashing out
