### ISSUE TITLE
Review standard email header / footer etc

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1861]
* [x] make logo pic crisper and smaller and move to header
* [x] fix variable width issue

**Comment by scd** [comment]
The header and footer is html in the BSIS/Email.pm file which is not in our
git. Mock up and I will integrate. Make sure you let me know.

**Comment by brendanheywood** [comment]
got a fairly clean version working, please comment

**Comment by brendanheywood** [comment]
@nicHoch feedback? did you get the cc of the test email with the new header and footer?

**Comment by nicHoch** [comment]
Morning!
yes looks good and plain to me.

Maybe add a very simple statistic in the footer. 
xRoutes - yCrags - zTopos - uPhotos - vTopos

That is some kind of snapshot and the active user will see if  he compares with the last email.
Wow I joined 2 month ago and the index grows in some way.

I see index growing as some of our driving forces

**Comment by brendanheywood** [comment]
These are generic headers and footers for all sorts of emails so not sure they are total appropriate for all emails. But something like that I think would be great in the weekly or month status update email which we don't yet have but was in the strategy doc (and maybe some other google doc).

**Comment by brendanheywood** [comment]
Ok I'm pretty happy with, so closing. If anyone finds any rendering quirks in particular email clients please reopen this issue or make a new one

**Comment by scd** [comment]
Make sure you let me know if there are any tweaks, so I am triggered to
sync the code.

**Comment by brendanheywood** [comment]
Sorry I thought that comment above was enough, yes there so please go grab
em

Sent from my iPhone

On 22/02/2015, at 9:18 AM, Simon Dale <notifications@github.com> wrote:

Make sure you let me know if there are any tweaks, so I am triggered to
sync the code.
On Feb 21, 2015 11:37 PM, "Brendan Heywood" <notifications@github.com>
wrote:

> Closed #1861 <https://github.com/theCrag/website/issues/1861>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theCrag/website/issues/1861#event-239590858>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/theCrag/website/issues/1861#issuecomment-75396138>.

**Comment by scd** [comment]
Done already. I meant for future tweaks, as sometimes we things just after
it is finished.
