### ISSUE TITLE
PROD BUG: Dashboard not loading with message.pm error

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1866]
http://www.thecrag.com/dashboard

Apache Module Load Portal Error: Error: DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '636476652,636476556) ORDER BY M.CreateDate DESC' at line 1 at /opt/CIDS/perllib/CIDS/Application/CustomSQL/Message.pm line 882.

**Comment by brendanheywood** [comment]
Logged out and in and still there

**Comment by scd** [comment]
fixed. a message id was coming though as empty string rather than an id.
Not sure why, but cleaned the list so that there are no empty strings.

On Sun, Feb 22, 2015 at 6:48 PM, Brendan Heywood <notifications@github.com>
wrote:

> Logged out and in and still there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theCrag/website/issues/1866#issuecomment-75424337>.
>



-- 
http://thecrag.com/
