### ISSUE TITLE
allow gym admin to assign a category to a climber for a competition

### ISSUE THREAD

**Issue by scd** [theCrag/website#1869]
also allow leaderboards based on this category

**Comment by scd** [comment]
this is done, just waiting RockIt climbing gym feedback.

**Comment by brendanheywood** [comment]
Is this per comp, per gym, or global for that user?

**Comment by scd** [comment]
Somewhere in between. It is global for the gym (node)/user. This means that gym admin work will be preserved from tournament to tournament, but not effect other gyms.

This is all experimental. I think in the end there will be many forms of category 
 - [ ] global account categories (eg age and gender)
 - [ ] persistent gym/account categories (eg gym assiged ability)
 - [ ] competition category (eg 1st, teamA)

I am not creating additional data structures if I can avoid it. The ability to assign categories comes from the tournament json config. This is pragmatic and flexible for now.
