### ISSUE TITLE
round trip registered grades

### ISSUE THREAD

**Issue by scd** [theCrag/website#1874]
According to the general feedback the current implementation of registered grades is a bit complex. A simple text field would be preferred.

To do this we need to ensure that the round trip journey of all registered grades is consistent.

Related issue #1585 describes a mechanism of how to treat multiple grade contributions, which is dependent on this issue being completed. I don't want to change data models to resolve this issue. I want the scope to be limited to simplifying the UX for registered grades.

Related issue #1513 describes an API which returns multiple grade matches. Resolving this issue does require an API. I think if we work through this issue then the API requirements will fall out.

Parsing grades may give different results for the following:
 - [x] the context
 - [x] gear style (eg bouldering will prioritise Font grades)

Thinking out loud, some requirements:
 - [x] The registered grade input text is preserved. (As there is no grade input text for routes before this issue was resolved this will be a live generated field based on current grade configuration).
 - [x] At any point (eg new submission) the grade structure may change due to changed grade configuration (eg a context may now interpret 6a+ as a british tech. grade rather than french grade)
 - [x] You should be able to save a registered grade outside the context (eg an Australian grade in US context).
 - [x] Displaying grades should be unambiguous, add the grade system to the grade component if it is potentially ambiguous.
 - [x] Multiple pitches should not be used in registered grade. If mulitple pitch format is used then the overall grade should be returned
 - [x] Multiple grade components (eg free + aid, uk adj + tech) should be catered for.
 - [x] Multiple grading systems should be catered for eg register grade for both AU and FR grade for a route.
 - [x] API should return the parsed grade to be shown marked up in the UX

Maybe we could use select2, but this is for bonus marks.

**Comment by brendanheywood** [comment]
I think this is mostly a dup of Make a universal grade input widget #1180 so most comments should still be current. To recap:

* all grades should be free text. period. Drop downs or auto-suggest with the combinatorial complexity of grades would just be a mess. Even just auto complete would be a waste of time in the simple case of Australian ewbank, and say you want grade 24, you start typing '2' and get a dropdown of 11 grades (2, 20, 21, 22 ... 29) and now to select 24 you'd have to press down 4 times and then press enter .... or you could just press '4' and you are done. Then layer on all the other types of grades and this just becomes utterly useful clutter. So Select2, or datalists or whatever are just pointless.

* all grades should have a country context dropdown, but this should default to whatever country you are in and it should almost never change.

This will cover all of the points in your post above, 

> Changing the context or gear style means that the grade may be changed without changing the text.

Context yes, but gear style nope? Gear style should be independent?

>  Multiple pitches should not be used in registered grade. If multiple pitch format is used then the overall grade should be returned

I think this will be good, but we need to be careful with our semantics so we're sure we're talking about the right thing. The textbox that the person enter text grades into, lets call this the 'editable grade'. It's text, it's stored at text, it's exactly what they see when editing it next time. If that text data is changed then we parse it and store the parsed version into the existing principal grade data model. So the text field could be AU: '21,25,22' and afterwards the principal is 'AU:Ewbank:25' or it could be UK: 'HVS, 5a' which becomes UK:Adj:HSV + UK:Tech:5a. As far I can tell we are already storing what I call the 'editable grade' it is just ignored when you go to edit a route which is exactly what needs to be fixed.

> Multiple grading systems should be catered for eg register grade for both AU and FR grade for a route.

This is the one sticking point and where the current data model isn't sufficient to properly model reality. 

ie you could have a route which is UK: 'HVS, 5a' and those two grade compnents are intrinsically intertwined. There is no point talking about the 5a without the HSV, it doesn't make sense. Likewise you could have a route which is '22 M3' and at the same time is also '27'. Saying it is 'M3' by itself doesn't mean anything. If these all get parsed and squished together into principal grades you end up with '27' + 'M3' which is just wrong. Likewise the route could also be a highball boulder problem and go at V9, so '27' + 'M3' + 'V9' is wrong. This is exactly what I proposed fixing in #1585 by creating an extra layer called 'whole grades' to collect these together.

We don't need to implement the 'whole grades' concept to get here, but if we do the above as is without the whole grade concept then it means we have to drop the requirement to have 'register grade for both AU and FR grade for a route'.

I think we'll probably need some mockups to make this really clear.

**Comment by brendanheywood** [comment]
ah sorry just re-read this: 

>Parsing grades may give different results for the following:
>  the context
> gear style (eg bouldering will prioritise Font grades)

Is this something new? I didn't think this was the case at the moment, but it that's working now then great.

**Comment by scd** [comment]
Sorry I knew you had written some more stuff about this, but missed the issue when I reviewed.

> Is this something new? I didn't think this was the case at the moment, but it that's working now then great.

Been implemented for a while. If you type in a 4a+ bouldering grade in France (actually anywhere) then it is interpreted as a Font boundering grade not a french grade. I think we discussed this a while ago and there are a number of special similar cases with other gear types. I cannot see how we get away from this.

> This is the one sticking point and where the current data model isn't sufficient to properly model reality

A registered grade cannot currently be both a 27 and a '22 M3'. I think this is not a data model limitation, but an implementation limitation as registered grade as there is only one registered grade record contribution. I don't propose to fix this with this issue, but do acknowledge it is a real issue and will be fixed with #1585 

However there are cases where a route can have a 16 and a 5a+. This only requires one registered grade contribution because they are separate systems. One contribution can have multiple unique systems. (Note that the previous example of 27 and 22 M3 has two AU system entries, which is not possible with the current implementation.) The French and Australian registered grade contributions are currently in operation in Thailand and came from the early Thailand guidebooks which had both grades listed. If we don't cater for this in the round trip text then we will be losing data.

> all grades should be free text. period

Ok I am happy with this as I saw some difficulties with select2 implementation, but also some advantages. I am happy to make this a mandatory requirement, until we decide otherwise :)

> Likewise the route could also be a highball boulder problem and go at V9, so '27' + 'M3' + 'V9' is wrong. This is exactly what I proposed fixing in #1585 by creating an extra layer called 'whole grades' to collect these together

When we come to implement #1585 I think we will find that 'whole grades' concept is already there, but needs constraints on what grades can go together and needs an assumption lifted on there being only one whole grade.

There is no data model restriction as to why we have to drop the requirement for both AU and FR grade for a route. However we do need to represent it in one text field - '16 [FR 5a+]'.

> The textbox that the person enter text grades into, lets call this the 'editable grade'. It's text, it's stored at text, it's exactly what they see when editing it next time

This needs more discussion on how to implement. The registered grade currently has a blank input free text field. Here is my proposal:
 - [ ] on update forms, if there is no inputted free text field then use an automatically generated text field, otherwise use the inputted free text.
 - [ ] use an automatically generated grade text field in index pages.

This means we could accept have multi pitch grades in the registered grade, but the multiple pitch specification would not be visible in the streams and index pages.

**Comment by scd** [comment]
I have had my first go at an API endpoint.

/api/grade

input example:

```
{
  "data": [{
    "text": "19",
  },{
    "text": "V1",
  },{
    "text": "19 to 22",
    "context": "AU",
  },{
    "text": "4B+",
    "style": "boulder",
  }]
}
```

output example:

```
{
   "data" : [
      {
         "contextID" : "7516378",
         "input" : "19",
         "components" : {
            "19" : {
               "unambiguousContexts" : {
                  "7516384" : "AU"
               },
               "styleID" : 7510792,
               "style" : "Free",
               "interpretations" : [
                  {
                     "system" : "AU",
                     "grade" : "19",
                     "systemName" : "Australian Ewbanks",
                     "systemID" : "7510852"
                  },
                  {
                     "system" : "SA",
                     "grade" : "19",
                     "systemName" : "South African",
                     "systemID" : "7510912"
                  }
               ],
               "systemName" : "Australian Ewbanks",
               "systemLabel" : "AU",
               "systemID" : "7510852",
               "display" : "19"
            }
         },
         "style" : "Free",
         "grade" : "19",
         "score" : 209,
         "context" : "US",
         "gradeBand" : "Experienced",
         "gradeBandID" : "7511068"
      },
      {
         "contextID" : "7516378",
         "input" : "V1",
         "components" : {
            "V1" : {
               "unambiguousContexts" : {
                  "7516402" : "UIAA",
                  "7516390" : "UK",
                  "7516378" : "US",
                  "7516408" : "SA",
                  "7516396" : "FR",
                  "7516384" : "AU"
               },
               "styleID" : 7510804,
               "style" : "Boulder",
               "interpretations" : [
                  {
                     "system" : "BLDV",
                     "grade" : "V1",
                     "systemName" : "Bouldering Vermin V-scale",
                     "systemID" : "7510960"
                  }
               ],
               "systemName" : "Bouldering Vermin V-scale",
               "systemLabel" : "BLDV",
               "systemID" : "7510960",
               "display" : "V1"
            }
         },
         "style" : "Boulder",
         "grade" : "V1",
         "score" : 213,
         "context" : "US",
         "gradeBand" : "Experienced",
         "gradeBandID" : "7511068"
      },
      {
         "contextID" : "7516384",
         "input" : "19 to 22",
         "components" : {
            "19 to 22" : {
               "unambiguousContexts" : {
                  "7516384" : "AU"
               },
               "styleID" : 7510792,
               "style" : "Free",
               "interpretations" : [
                  {
                     "system" : "AU",
                     "grade" : "19 to 22",
                     "systemName" : "Australian Ewbanks",
                     "systemID" : "7510852"
                  },
                  {
                     "system" : "SA",
                     "grade" : "19 to 22",
                     "systemName" : "South African",
                     "systemID" : "7510912"
                  }
               ],
               "systemName" : "Australian Ewbanks",
               "systemLabel" : "AU",
               "systemID" : "7510852",
               "display" : "19 to 22"
            }
         },
         "style" : "Free",
         "grade" : "19 to 22",
         "score" : 209,
         "context" : "AU",
         "gradeBand" : "Experienced",
         "gradeBandID" : "7511068"
      },
      {
         "contextID" : "7516378",
         "input" : "4B+",
         "components" : {
            "4B+" : {
               "unambiguousContexts" : {
                  "208415296" : "FB"
               },
               "styleID" : 7510804,
               "style" : "Boulder",
               "interpretations" : [
                  {
                     "system" : "FR",
                     "grade" : "4b+",
                     "systemName" : "French",
                     "systemID" : "7510882"
                  },
                  {
                     "system" : "FB",
                     "grade" : "4B+",
                     "systemName" : "Fontainebleau Bouldering",
                     "systemID" : "208414621"
                  }
               ],
               "systemName" : "Fontainebleau Bouldering",
               "systemLabel" : "FB",
               "systemID" : "208414621",
               "display" : "4B+"
            }
         },
         "style" : "Boulder",
         "grade" : "4B+",
         "score" : 159,
         "context" : "US",
         "gradeBand" : "Intermediate",
         "gradeBandID" : "7511062"
      }
   ]
}
```

The substantial ideas in this api are 
 - [ ] the result is parsed into components
 - [ ] each component has the contexts in which the grade is unambiguously identified as a particular grading system. I am not sure whether or not to collapse this to a flag based on the input context. The input context may not be provided.
 - [ ] also each component has a list of other interpretations. I am not sure whether to make it strictly 'other' or have a full list including what was assigned.

**Comment by scd** [comment]
oh, I forgot to include an example with multiple components:

input:

```
{
  "data": {
    "text": "22 M3",
    "context": "AU",
  }
}
```

output:

```
{
   "data" : {
      "contextID" : "7516384",
      "input" : "22 M3",
      "components" : {
         "22" : {
            "unambiguousContexts" : {
               "7516384" : "AU"
            },
            "styleID" : 7510792,
            "style" : "Free",
            "interpretations" : [
               {
                  "system" : "AU",
                  "grade" : "22",
                  "systemName" : "Australian Ewbanks",
                  "systemID" : "7510852"
               },
               {
                  "system" : "SA",
                  "grade" : "22",
                  "systemName" : "South African",
                  "systemID" : "7510912"
               }
            ],
            "systemName" : "Australian Ewbanks",
            "systemLabel" : "AU",
            "systemID" : "7510852",
            "display" : "22"
         },
         "M3" : {
            "unambiguousContexts" : {
               "7516384" : "AU"
            },
            "styleID" : 7510798,
            "style" : "Aid",
            "interpretations" : [
               {
                  "system" : "AUAID",
                  "grade" : "M3",
                  "systemName" : "Australian Aid",
                  "systemID" : "7510942"
               },
               {
                  "system" : "MIXED",
                  "grade" : "M3",
                  "systemName" : "Mixed Rock/Ice",
                  "systemID" : "7511002"
               }
            ],
            "systemName" : "Australian Aid",
            "systemLabel" : "AUAID",
            "systemID" : "7510942",
            "display" : "M3"
         }
      },
      "style" : "Aid",
      "grade" : "22 M3",
      "score" : 188,
      "context" : "AU",
      "gradeBand" : "Experienced",
      "gradeBandID" : "7511068"
   }
}
```

**Comment by brendanheywood** [comment]
Can we make this just get params instead? I'm a bit confused about the input, I would expect the input to be as simple as 

/api/grade/?ctx=AU&grade=22 M3

or even just:

/api/grade/?AU:22 M3

**Comment by scd** [comment]
Yeah, the main reason why I went with POST is in case we want to do multiple parsing in one go, which I am pretty sure we will need one day. The POST is using our standard POST format, for example compare to markdown api. In our framework it makes no difference whether we call post or get, but I do see it making a difference for third parties.

Is there any reason why we cannot do both GET and POST versions?

**Comment by brendanheywood** [comment]
We can do both. I just don't like read api's that require a post, harder to debug, and importantly can't be cached. No reason why you can't have multiple params:

/api/grade/?grade=AU:22 M3&grade=AU:25&grade=UK:HSV 7b

..but this won't work generally for nest data use cases. Maybe we could do something generic across the whole api like (with some url escaping):

/api/grade?data={"text":"22 M3","context":"AU"}

but for safety only for read only calls?

**Comment by scd** [comment]
nice idea. I have implemented this, but it is enabled as a config parameter per endpoint.

**Comment by brendanheywood** [comment]
real example?

**Comment by scd** [comment]
Your example:

/api/grade?data={"text":"22 M3","context":"AU"}

Sorry, I just re-read and realised you made a number of examples.

**Comment by scd** [comment]
notes to self on forms to update:

 - [ ] single route update (will have demo to play with soon)
 - [ ] create route
 - [ ] bulk edit
 - [ ] export/import process

**Comment by brendanheywood** [comment]
Ignore the single route case, this needs to die and be exactly the same as
the bulk edit format. Kill 2 birds with one stone

Sent from my iPhone

On 05/03/2015, at 8:28 PM, Simon Dale <notifications@github.com> wrote:

notes to self on forms to update:

   -  single route update (will have demo to play with soon)
   -  create route
   -  bulk edit
   -  export/import process

—
Reply to this email directly or view it on GitHub
<https://github.com/theCrag/website/issues/1874#issuecomment-77332276>.

**Comment by scd** [comment]
There should be enough in repo to start testing - bulk edit, create route(s) and single route edit (note that I have decided to only kill one bird with this stone as testing was easier using the single route edit form and there are some other issues which need considering). 

I am going away for the weekend and pushed hard to get it done before I leave. There may be lots of bugs still.

**Comment by scd** [comment]
Note to self that there is a data migration requirement for this issue in regards to protection ratings.

- [ ] Make sure that protection ratings are part of the registered grades. I think they were previously picked up from the personal contributions and citations, so these should be migrated to the registered grade. This way they can be easily corrected without having to remove from a personal contribution. (#128 and #913)
- [ ] Also similar issue with brazillian distance and exposure grades - /climbing/brazil/urca/route/14267383

**Comment by brendanheywood** [comment]
I've pulled and deployed and don't think I'm seeing this?

This is what I see:

single / new:
![image](https://cloud.githubusercontent.com/assets/187449/6577286/c61fc750-c790-11e4-9210-21e39e7f0de6.png)

bulk:
![image](https://cloud.githubusercontent.com/assets/187449/6577292/d0518506-c790-11e4-8368-93564503ded3.png)

This is what I want:
![image](https://cloud.githubusercontent.com/assets/187449/6577406/e44e3d32-c791-11e4-85e8-4217b50066fa.png)

**Comment by scd** [comment]
are you sure you pulled properly - no branches, actually deployed and restarted apache?

It does not look like you have got any of the changes

**Comment by brendanheywood** [comment]
dozens of times debugging that email stuff last night. looks like not in git

```
bheywood@cidsbrendan:~/CIDS/CIDS/application/frontend/templates/html/thecrag$ git pull
Already up-to-date.
bheywood@cidsbrendan:~/CIDS/CIDS/application/frontend/templates/html/thecrag$ git branch | grep '*'
* master
```

Are you on master?

**Comment by scd** [comment]
simon@devsystem:/data/jobs/CIDS/CodeBase$ git branch
* master

**Comment by scd** [comment]
![bitbucket-commits](https://cloud.githubusercontent.com/assets/373058/6589015/fac04c48-c7ed-11e4-93ae-a4d53a5c26ef.png)

**Comment by scd** [comment]
I have also just had a look at the code in your home directory and it looks like at least some of it is there.

My guess is that you have pulled but forgotten to install on dev server directory and/or restart apache. I have done this before.

**Comment by brendanheywood** [comment]
Any can you send some screen shots of what I'm supposed to see?

**Comment by scd** [comment]
![thecrag-grade-1](https://cloud.githubusercontent.com/assets/373058/6590616/7fd5041a-c806-11e4-8df9-59a2d4ef396e.png)

![thecrag-grade-2](https://cloud.githubusercontent.com/assets/373058/6590617/7fddb8b2-c806-11e4-82df-7358dfa135de.png)

**Comment by scd** [comment]
more notes to self:
 - [ ] 5º not working in API and not working in registered grade
 - [ ] protection rating not showing up after data migration

**Comment by brendanheywood** [comment]
ok so I had this the whole time, it's just not what I was expecting visually. Some todos:

* [ ] combine the context and grade into one line like in the mockups

![image](https://cloud.githubusercontent.com/assets/187449/6612871/0176588a-c8d8-11e4-856f-269bfe7f7485.png)

* [ ] change the validation to work on keyup, don't bother with a throttle most grades only have a tiny number of chars in them, or make it very tight say < 50ms
* [ ] change the select to be a fixed short width around 50px or 4em, and change the option texts to be a 2 letter followed by a - and then the long desc, so we get the best of both worlds or a short summary but a long desc when selecting, something like this:

![image](https://cloud.githubusercontent.com/assets/187449/6612889/708e844a-c8d8-11e4-963a-3b7c19eca563.png)

* [ ] what is the story with the context, is there just one context per route, or is there one per grade? ie should the user grade contribution also have a context?

**Comment by scd** [comment]
OK here is my ramble.

Before you commit to putting the context next registered grade, also have a look at the create route page, in particular creating multiple routes. 

Technically the context is associated with contribution in the data model. Practically it has been managed as a route setting because the only context setting that makes a difference is the registered grade. All all the other contributions are mostly just hangers on and displayed as input, not as parsed with an exception for user stars. 

Really the context is a country setting and should only be overridden in specific situations, where certain crags have different we are currently doing this route-by-route. 

I would like to keep just one context per route on the UX, however the data model allows the UX to be expanded to be one context per grade if we choose.

 - [ ] I think it is important that we indicate that a context is different from the country assigned context.

For registered grades the context provides two functions 1) parsing and 2) adding grading systems when displaying.

 - [ ] We need to drop the Font context from the UX as this should not be settable. Instead you have to assign the route as a Boulder style.

So some decisions.
 - [ ] If we truely want the UX to show per contribution context the the current data model is fine.
 - [ ] We should consider moving the context to the route level.
 - [ ] We should consider adding a context to an area node so that we can override a country default (note the last two can be updated with a single field addition to the node table). I think this is my preferred model.

We don't have to change all this just to get it working. At the moment I have just got the same UX working with a free text, rather then a drop down. All the rest is bonus, but we should seriously consider doing it now as we are investing effort into the area. Note that there are some other issues I might try and tackle as well and to fix up the bulk edit properly (ie bolts and structured tags). In which case I will phase out the single edit page.

BTW, I thought you did not like a delay when processing key strokes. In this case I think a delay is appropriate because if somebody is typing 5.12a it is going to change dramatically as you type.

**Comment by brendanheywood** [comment]
> Before you commit to putting the context next registered grade, also have a look at the create route page, in particular creating multiple routes.

Yes having it at the top does make sense, I'd see this being a default similar to the ascents logging form. I'd really like to re-arrange the create form and the edit form so that they are almost identical in layout, and that this layout also matches as much as practical the layout of where each route component goes in list view. Changing the context is a fringe thing but I still want it to be super obvious and easy to do, which is why I want the select to use the abbreviated form and be a fixed small width.

> I would like to keep just one context per route on the UX, however the data model allows the UX to be expanded to be one context per grade if we choose.

I don't see how this would work with some edge cases, if I have a route and I want to give it both a british and french grade, but can only choose one context? This is where the 'whole grade' concept comes in and I'd want one context per whole grade, and not per route, or per grade system. So I would want the UI to look something like this with the current data model:

![image](https://cloud.githubusercontent.com/assets/187449/6631823/7dd30bd2-c980-11e4-8c23-1f6ad90d1e77.png)

and if and when we implement the idea of whole grades, we would be able to add new extra grades something like this:

![image](https://cloud.githubusercontent.com/assets/187449/6631893/8e00aebe-c981-11e4-92f8-73f8f2f3e023.png)

(btw I'm not worried about real estate left to right, I'd also like to move all the FA / Set stuff down to the bottom in the same place as it appears in list view. In fact I'd like to go one step further and stream line it even more like this:

![image](https://cloud.githubusercontent.com/assets/187449/6632176/232ac4bc-c986-11e4-9973-5704cce61eb7.png)

I think this solves a few problems, making it a little harder for people to add Set + FA + FFA, but using less room, but still allowing full flexible multiple history items

>  We need to drop the Font context from the UX as this should not be settable. Instead you have to assign the route as a Boulder style.

Does this mean we can actually do away with the Font context completely and just merge it with FR? This assumes that all french boulder problems use the Font scale? Would cause issues if in another country they use French climbing grades but V bouldering grades?

What is someone wanted to give a DWS route a french sport grade and a font bouldering grade? Maybe we just don't care about this.

> We should consider adding a context to an area node so that we can override a country default (note the last two can be updated with a single field addition to the node table). I think this is my preferred model.

I'm cool with this, but do you mean in addition to the route context, or replacing it? I think this would be perfect if it was treated as a default override, but still won't work if we want different whole grades at the route level each with their own context.


> BTW, I thought you did not like a delay when processing key strokes. In this case I think a delay is appropriate because if somebody is typing 5.12a it is going to change dramatically as you type.

Yeah you are right, the important thing is that you get a preview after you have finished typing but haven't yet tabbed to the next field. ie validation that you entered a valid grade in the current context. So a small throttle of say 200-400ms would be ok.

Also given that I'd like to make all create and update pages laid out like the mockups above realestate is at a premium, so what do you think about turning the validation into an outline like this:

Left mockup is a valid grade in this context, right on is a grade that just didn't parse at all.

![image](https://cloud.githubusercontent.com/assets/187449/6632103/e19a441a-c984-11e4-86d8-6b990c6a4860.png)

I'd probably also want one for the case where the grade parses but is in a 'foreign' context, but need to make sure that it looks like a warning and not like an orange intermediate grade. So what do you think about this which would mean that the context isn't right for this grade?

![image](https://cloud.githubusercontent.com/assets/187449/6632147/7f0c1d86-c985-11e4-9877-5e19c28b69d3.png)

**Comment by scd** [comment]
> I don't see how this would work with some edge cases, if I have a route and I want to give it both a british and french grade, but can only choose one context?

While the current solution does not properly cater for whole grades it does cater for some cases. In particular the case described here is catered for. If you are in UK context type in '6a V3 FR:7a'. All three components will be read in. Note that the 'FR:' refers to the french grading system not french context.

> This is where the 'whole grade' concept comes in and I'd want one context per whole grade, and not per route, or per grade system. So I would want the UI to look something like this with the current data model

Fair enough. If it is not an obscure edge case then we should cater for as you suggest.

> btw I'm not worried about real estate left to right

Yes I am seriously worried about this as well. Also I don't want this to become a rabbit hole of redesigning everything just to cater for converting grades from a drop down to a text field. Funny thing is that I always knew this would be a rabbit hole issue, which is why I have put it off for so long.

> Does this mean we can actually do away with the Font context completely and just merge it with FR?

Merging will break a constraint of grades being unique within a context. It is better just to treat FB context as a hidden context. Font bouldering grades are used outside france anyway.

At the moment a Font bouldering grade is consistent in any context because the gear style is set to Bouldering. 

There is no problems here at all, we just need to make sure people cannot set their context to FB, anywhere, which should be a trivial change.

> What is someone wanted to give a DWS route a french sport grade and a font bouldering grade?

6a+ FB:5A

> I'm cool with this, but do you mean in addition to the route context, or replacing it? I think this would be perfect if it was treated as a default override, but still won't work if we want different whole grades at the route level each with their own context.

I meant as an override to default context.

> Also given that I'd like to make all create and update pages laid out like the mockups above realestate is at a premium, so what do you think about turning the validation into an outline like this:

Don't forget we are also allowing multi-pitch grades '22,18,21 M1,13'. I think it is nice for the system to tell the user that it is going to assign an overall grade 22 M1. Also what about partial errors '25 then some garbage', or '5.12 A7'. 

Similar complexities also apply to foreign contexts where some of the grade components are local and some are foreign, eg in AU context '22 A3' (ie US aid grade, rather than an australian aid grade).

To keep the scope of work down in this issue I am making an executive decision for this issue - 'Whole Grades' are off the table, and will be dealt with some time down the track.

**Comment by scd** [comment]
FYI, doing round trip validation test on all registered grades, as I have come across some issues. I will just add them here:
 - [x] Bug with US Class X being incorrectly applied
 - [x] French grades migrated to Font grades where gear type is Boulder
 - [x] Deleted registered grade where they were assigned to '--'.

**Comment by brendanheywood** [comment]
>  If you are in UK context type in '6a V3 FR:7a'.

 and

> 6a+ FB:5A

Coolies. It's not idea as it's a little obscure but they are all fringe cases so I'm not worried by this.

> Don't forget we are also allowing multi-pitch grades '22,18,21 M1,13'. I think it is nice for the system to tell the user that it is going to assign an overall grade 22 M1. Also what about partial errors '25 then some garbage', or '5.12 A7'.

Good point. I think what you have done will work well as the overall grade is never big, but we can make the grade field reasonably big to make it easy to enter multi pitch grades.

> To keep the scope of work down in this issue I am making an executive decision for this issue - 'Whole Grades' are off the table, and will be dealt with some time down the track.

Yeah I've been assuming it's not getting done in this round but want to get it clear where I'd like to head eventually.

**Comment by scd** [comment]
I have just come across a class of problem which may throw a spanner in the works:

https://www.thecrag.com/climbing/united-kingdom/burbage-valley/burbage-north/route/21300703

This Boulder problem has both UK grades and Vemin V-scale grades. Actually the V-scale is irrelevant other then to demonstrate that it is a boulder problem.

The issue here is that the '6c' component is both a UK technical grade and a font grade. Our current rules say that it should be interpreted as a Font grade, but I think this is wrong in this situation.

**Comment by brendanheywood** [comment]
Maybe I misunderstand what you've actually implemented with the Font system. I've assumed that all the Font system still has all the same parsing logic as any other system, but on top of that it also only matches when the gear type is boulder.

If this is the case, then can't we just say the French context has priority systems in order: Font boulder grades,  French climbing grades,  Bouldering Vermin V-scale,  International French Adjectival System,  Aid,  Hammerless Aid,  Via Ferrata Schall System 

Then if it sees a 6c grade on a boulder inside France it is parsed as font as it's higher priority than french), but if you see a 6c sport route in france it shows as French climbing. If you have a 6c trad route in the UK it would get parsed at UK tech like it should. Unless there is a good reason the UK context would not even reference the Font system so it should never match there, so a 6c boulder in the UK would still be a UK tech grade

**Comment by scd** [comment]
Implementation is slightly different, but effectively the same. The Font context only has parsing for the Font system, however if it does not match it will go through another context in a pre-defined priority order. Effectively this gives each context a priority list of systems it tries.

Are you confirming that Font Bouldering grades are not used in UK? If so then there is no underlying clash of logic just a matter of finding a pragmatic implementation. For example if it is a UK context then we don't apply the Font Bouldering rule.

**Comment by scd** [comment]
I think this area here

- [ ] https://www.thecrag.com/climbing/hong-kong/tsuen-wan-boulders/guide will need a clean up post release.

**Comment by brendanheywood** [comment]
ukc suggests bouldering uses the tech grades:
http://www.rockfax.com/publications/grades/

But a quick trawl shows plenty of sites / blogs ref font grades in the uk, so maybe that's not a safe assumption. Need more local input

**Comment by scd** [comment]
In which case we should keep don't in the drop down contexts

**Comment by brendanheywood** [comment]
I assume you mean we should keep 'font' as an explicit context to choose? Yeah that seems the simplest to me too.

Just did a bit more digging on the Hong kong stuff and found this:
> Routes relying on traditional (natural) protection have been assigned British Traditional Grades, bolted routes have been graded in accordance with the French Sport Climbing Grades. Boulder problems have been given British Technical Grades, tentative efforts at assigning American V bouldering grades have also been made
http://hongkongclimbing.com/guide/

This is a bit of a pain as they will use french and UK grades side by side which overlap. We need to made a new grade context for 'Hong kong' but this isn't  enough to solve the problem unless we added extra special rules. This is the same problem as the Font grades but with Sport vs Trad. Perhaps a better data model is instead of making a system (eg Font) optionally only trigger for certain gear styles (eg Boulder) wherever that system is used, we instead make this config at the level where the system is associated with the context. ie for each 'priority system' attached to a context we also give each system an optional white list of gearstyles. Explicitly for the French context, the Font system would only apply to bouldering. In the UK context the Font system would not be a priority system at all so it would be an explicit context choice as mentioned above. And in the new Hong Kong context the UK Tech/Adj systems would only be applied to trad routes, and the French system only applied to Sport routes, the Font system would not be applied at all, the UK tech system would be applied to boulder problems, and the V grade system would be applied but wouldn't need any white listed gear style.

**Comment by scd** [comment]
So this means a cliff could have both sport and trad routes. Two routes next too each other could have a 6a UK trad and a 6a FR sport. Wow, this is crazy, but it is the way it is.

Yes, I think the obvious extension to the config is extra settings for gearStyle. Grade configuration is all held in the database in config tables. It means an extra table. I might opt for the two minute, 'if statement' solution for now and put the configuration on the to do list. 

- [ ] Add a Hong Kong context

**Comment by brendanheywood** [comment]
> Wow, this is crazy, but it is the way it is.

I that pretty well sums up grades globally in general :)

I'm cool with the if statement as long as the same logic gets embedded into the grades article

**Comment by scd** [comment]
- [ ] update grades article
 - [ ] add an grade test input box (+gear style +context) for people to trial grade inputs.

**Comment by scd** [comment]
I have decided to bite the bullet and do the full config, as I came across another bug which just disappears when we implement context/style system priority order.

As well as that, it looks like various bouldering areas under the UIAA system use UIAA grading or Font grading. There is an overlap with Font and UIAA. The logic for font grades come from FR grades, which includes an FR_ALT grade (eg 7). This clashes with UIAA. So in UIAA context for bouldering we should first try standard font then UIAA then alternate font.

**Comment by scd** [comment]
I am getting close to finishing this now. @brendanheywood please have a look at the grade article, which has been updated with the new logic discussed here.

There are two things outstanding:
 - [ ] minor formating changes to the bulk input screen
 - [ ] assess display changes where we are displaying grades (list view, route page header, route page contributions list).

@brendanheywood could you recommend any minor formating changes for the bulk edit form with regards to grades. This is not the end of it, as the bulk edit page is subject to other potential changes and I don't want to get too bogged down on this now. I just want to do the minimum.

**Comment by brendanheywood** [comment]
heads up that I'm heading to brisbane / rockhampton on fri for all of next week back 27th. So I'll aim to get feedback / tweaks done tonight.

**Comment by scd** [comment]
don't forget to do what I did and not push the articles. I keep on forgetting they are in a different repo.

Please keep the feedback to short term release focused. We can open a new issue for long term stuff.

**Comment by brendanheywood** [comment]
Grade article / config:

In general looks great, exposing the 'type' of each grade system now make it heaps clearer.

Some quick spot checks and odd things I noticed:
* [ ] Australia uses the Font for boulders? I wouldn't consider Font a primary grade system for the au context, looks like this appears in other contexts too. I would expect 
* [ ] Fontainbleau context still exists, isn't this now redundant and merged with french?
* [ ] HongKong is missing boulding Fontainbleau system
* [ ] US context has DWS safety grade mentioned twice, and Mixed Rock and ice - is this a mistake or the way the config needs to be?

**Comment by brendanheywood** [comment]
There is still a lot of inconsistencies between the various editing processes and cosmetic stuff but I think that can all wait. No show stoppers

**Comment by scd** [comment]
> Australia uses the Font for boulders? I wouldn't consider Font a primary grade system for the au context, looks like this appears in other contexts too. I would expect

We can remove it from the various contexts. However what does it mean if you type in a '5c' in a sport route in Australia? 

 - [ ] That configuration is just meant to be sufficient info for the system to parse correctly. Maybe I should rename the style grade to be 'Additional boulder systems'.

> Fontainbleau context still exists, isn't this now redundant and merged with french

We cannot do that because there are UK bouldering areas which use UK technical grades and other bouldering areas which use Font. Font bouldering grades seem to be used in random areas around the world.

> HongKong is missing boulding Fontainbleau system

This is correct because a Hong Kong bouldering area should default to UK technical.

> US context has DWS safety grade mentioned twice, and Mixed Rock and ice - is this a mistake or the way the config needs to be

 - [ ] I think I can remove the second instance. I had some general rules which I have turned mindlessly into configuration. This has exposed some minor issues.

**Comment by scd** [comment]
I have just added a thing about gym routes in the Grades articles and also updated the javascript so that it uses swatch color if supplied.

**Comment by brendanheywood** [comment]
> We can remove it from the various contexts. However what does it mean if you type in a '5c' in a sport route in Australia?

Good question, I don't think there is always a right answer. That's why I'm kinda leaning towards it showing as a warning and making people choose a context to be explicit what they meant. 

> We cannot do that because there are UK bouldering areas which use UK technical grades and other bouldering areas which use Font. Font bouldering grades seem to be used in random areas around the world.

If the font system is attached to the french context, and they want to use Font grades in say the UK or China, how would selecting the FR context not be sufficient? Either way they still have to choose a context to make it work in Font isn't a 'normal' system.

> This is correct because a Hong Kong bouldering area should default to UK technical.

ah yep I got confused

**Comment by scd** [comment]
The font system cannot be connected to the french context as a general parsing system because it is in conflict with the french system. The universe will implode!

The font system can however be connected to the french context via the bouldering style. In which case selecting the french system would be sufficient. Is it easier for the user to work out to use the french system or font system as their context. Maybe it is clear enough that if they want font then they should set the french context.

- [ ] That means we can hide the font system from the context selections.

I think we can take out font system from AU context as it is just not used. If things change we can put it back in. It only really matters when there is a confict to resolve.

- [ ] remove font from AU bouldering grades (any others?)

I have also made some display changes so that any grading system which is not configured in the context and is potentially ambiguous is then displayed with a UKT:5c+ (ie grading system prefix) to make it explicit. This goes for any component. This brings out an issue with AU grades - we are relying on the X and R protection ratings a fair bit, but they are now displayed as PROT:X and PROT:R. 

- [ ] add protection rating to AU context

Maybe we should quickly think about whether the AU context has it's own protection rating, as we really only use X & R or do we continue to piggy back on the US protection rating. I think the later.

BTW, I think we are getting close to resolving most of the grade issues we have been fighting over the last couple of years. It is highly likely that I will have to add a context to an area to complete this work, but I want to be sure before we do.
