### ISSUE TITLE
Favorites - Mobile Web Site (link to full list of favs)

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#1877]
I can't get to all my favorites via the mobile web site any more.

If I click index I get my top 15 and a link to "re-order your favorites", so anything past the first 15 I can't get to.

**Comment by scd** [comment]
I don't think I meant to take them out of dashboard just profile.

**Comment by scd** [comment]
I have added favorites back to your dashboad. This function is hotfixed. @tomkjaerolsen can you please confirm this works on your dashboard.

**Comment by brendanheywood** [comment]
This is sorted either way in the new design, either in the account menu top right, or from the dashboard in the hamburger menu. I think I'll also integrate this into the mobile search too
