### ISSUE TITLE
Idea for facilitated data snitching

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#1882]
Afaik you consider route names and respective grades "general knowledge", so it's OK to copy these from guidebooks or other websites. I totally agree on that. However, this is a tedious task even with simple copy-pasting, but ever more so when you have to type from a paper guidebook.
Here's my cheeky vision for an optimal solution to facilitate this process and help people to populate the route db:
- enter a URL into some form on thecrag. An additional frame or browser window opens, where one can navigate to the desired list of routes
- choose some kind of marker tool from a toolbar and highlight the route names
- choose another tool to highlight the corresponding grades
- press "process" to have the respective strings extracted and put into the regular bulk edit form for checking and "add routes"

Being able to perform this also with uploaded scanned images with some internal OCR would be the cherry on the cake.

I have no idea if this is technically possible, I just reckon it would boost the inflow of data.

**Comment by scd** [comment]
I think we have to be a little bit careful here. We cannot develop tools for wholesale copying without permission.
