### ISSUE TITLE
bulk edit required for ascents facets

### ISSUE THREAD

**Issue by scd** [theCrag/website#1885]
The motivation for this issue is the new feature suggesting routes that you could contribute height information for. We have had a request to update this in bulk :)

**Comment by scd** [comment]
also I might add a quick edit route link from the ascent facet

**Comment by brendanheywood** [comment]
Can't we just pass in a list of id's to bulk edit already? I thought we had this in place back in the day with the original faceted thingo I made using exhibit which linked of to the bulk edit page.

**Comment by scd** [comment]
Yes, with the ids. I thought you had done this with the ux, but it does not
arm to be there. The other issue is that we need to edit routes from the
ascent facet, or get a list of routes from the ascents facet?

**Comment by brendanheywood** [comment]
well I think this is pretty well done for the routes facet. I'd like to have one for the ascents facet too but not sure how many other facets would map to a bulk edit process. Just need to link it all together see #1888

**Comment by Mdemaillard** [comment]
more recent and complete duplicate as #2787
