### ISSUE TITLE
Search for both text FA and mention FA at same time

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1886]
Followup from you response to Neil's idea: I was thinking a quick workaround for this would be to search for ```neil, @neil``` to find both text and accounts. Would this search for routes with either of these or both of these? I'd probably say OR is more useful generally but I can also imaging looking for routes done by a combination of people. Maybe a little tick box under the select2 box to say Or vs AND ?

In any case it barfs and spits out an sql error:

https://www.thecrag.com/climbing/australia/routes/by/harris+@nmonteith/?sortby=at,desc

Apache Module Load Portal Error: Error: DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '9231481) AND HFA.ID=MNT.Entity AND N.ID=R.NetworkNode AND (N.ArchiveFlag IS NULL' at line 1 at /opt/CIDS/perllib/CIDS/Application/CustomSQL/Route.pm line 440.

**Comment by scd** [comment]
fixed in repo. OR functionality should now work

**Comment by brendanheywood** [comment]
sql works, title needs fixup:

![image](https://cloud.githubusercontent.com/assets/187449/6702985/8ab86a20-cd88-11e4-9bab-195d938d1b5b.png)

**Comment by scd** [comment]
should now be working
