### ISSUE TITLE
Refine the missing route height message and link

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1888]
I find this a little weird:

![image](https://cloud.githubusercontent.com/assets/187449/6655748/8104cd2e-cb5e-11e4-9847-f13ee1de43c4.png)

it links to here:

https://dev.thecrag.com/ascents/by/7727431/with-tick-type/7509964+7509970+7509976+7509982+7509988+7509994+7510000+283385698+7510012+7510018+7510036+333595990+333595996+7510042+276966013+7510054+7510060+7510030+7510066+167766430/route-missing/length

If we want to link in to a bulk edit page we should be dealing with routes not ascents, and the tick type shouldn't matter at all. I reckon it should say:
- [ ] '222 of the routes you have logged are missing height information. Fill in the gaps to get better profile stats and improve the info for others.
- [ ] and link to here instead https://dev.thecrag.com/routes/climbed-by/brendanheywood/missing/length/

A minor complication is the profile filtering. I'm not sure I care too much about getting it right and we could just link to the full list of routes without heights regardless of the profile filters. The worst that can happen is they see more routes, and then fix them :)

As part of #1887 I've done a clean up and adding back in some missing UI for facets that work but you couldn't get to them so the second part is good to go, but not sure how to stats side needs to change.

**Comment by brendanheywood** [comment]
I've added a bulk edit link from the routes facet page:

![image](https://cloud.githubusercontent.com/assets/187449/6655870/02252f50-cb66-11e4-9fac-ba508bf5cad5.png)

**Comment by scd** [comment]
Cool. Couple of things - max should align to the pageSize. Eg

http://dev.thecrag.com/climbing/australia/arapiles/routes?pageSize=50

Secondly, is there a permissions logic issue here, especially when we consider somebody editing routes from  around the world. We may of course have locked an area as well.

**Comment by scd** [comment]
Can you please push to the main repo, as it is not coming through to me.

**Comment by brendanheywood** [comment]
I'm afk for a couple days. Maybe sudo as me and push

**Comment by scd** [comment]
No urgent. Do it when you come back. Have fun away

**Comment by brendanheywood** [comment]
This is mostly done, @scd what was left to do here?

**Comment by scd** [comment]
It still has tick type. The message aligns with the filter in the profile. When you get up to it in the profile page just remove the tick types in the link.

**Comment by Mdemaillard** [comment]
merging into #2984
