### ISSUE TITLE
Resizing on edit boxes is a little broken on Google Chrome

### ISSUE THREAD

**Issue by oliverstory** [theCrag/website#1890]
Using Google Chrome, when editing a crag or route some of the edit fields have a resize handle on the bottom right. When I drag this handle to the right slightly, it will expand to the full window height (pushing all the subsequent edit fields off the page). Returning it to previous size won't then move the other edit fields back into view.

Only a small issue but a little annoying. This didn't used to happen so my guess is a regression sometime  in the last few months.

Cheers
Oliver

**Comment by brendanheywood** [comment]
Yeah root cause is crazy multi column css in chrome.

**Comment by brendanheywood** [comment]
fixed
