### ISSUE TITLE
Phantom FA's in routes, an fa with no name and no date

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1891]
![image](https://cloud.githubusercontent.com/assets/187449/6710661/4b689a5e-cdd6-11e4-99f3-76f1375b7823.png)

Root cause is there is still a 'Diary entry' in the FA but everything else has been remove. The diary entry isn't even visible in the bulk edit so can't be delete when someone deletes everything else.

Need to fix this before we get rid of the single edit process

**Comment by scd** [comment]
Do we event want the diary entry stuff?

I don't want to just can it, because you had some other ideas with route history and having a comment field might be useful.

I can fix this by removing the diary entry field in the database or adding the diary entry to the bulk enter form?

**Comment by brendanheywood** [comment]
Keep it, add to bulk edit and relayout the bulk edit so this is under the
route not to the side.

Sent from my iPhone

On 19/03/2015, at 7:57 AM, Simon Dale <notifications@github.com> wrote:

Do we event want the diary entry stuff?

I don't want to just can it, because you had some other ideas with route
history and having a comment field might be useful.

I can fix this by removing the diary entry field in the database or adding
the diary entry to the bulk enter form?

—
Reply to this email directly or view it on GitHub
<https://github.com/theCrag/website/issues/1891#issuecomment-83173257>.

**Comment by Mdemaillard** [comment]
is that still possible with the new history interface of FA/FFA/Set ?

**Comment by lordyavin** [comment]
I delete a history entry on [sandit]https://sandpit.thecrag.com/climbing/canada/british-columbia/route/3120440241) and [no phantom FA](https://sandpit.thecrag.com/climbing/canada/british-columbia/area/3120434679/routes) is listed.

![grafik](https://user-images.githubusercontent.com/1528540/76735232-c18f3580-6764-11ea-968f-167c609eb9fa.png)

Looks like this is fixed.

**Comment by Mdemaillard** [comment]
@scd i think it is your call, either try & scan the database for possible remaining phantom entries, or close the point.
Searching manually these possible phantoms doesn't seem feasible with the current search:
Routes
tick has History
sort by: FA date, ascending

but then ? can't search for empty by who

**Comment by scd** [comment]
If I understand the situation correctly, we can manually fix the issue if it is found on production.

Maybe it would take an hour to add a facet for searching for the phantom entries, I am really not finding an hour for anything that is not fairly high priority.

So my suggestion is to manually delete these when they are seen in the database.

**Comment by Mdemaillard** [comment]
ok, the bug is closed now anyway, its only data cleaning IF some wrong data is remaining. closing.
