### ISSUE TITLE
ultimate bulk enter form

### ISSUE THREAD

**Issue by scd** [theCrag/website#1892]
I am creating this issue as a long term target issue for the bulk enter form. I don't plan to knock this over for a while, but head there slowly. 

The main aims are:
- [x] include all area/route/annotation fields (including admin) and phase out single edit form
- [x] responsive design (cf ascent logging) and remove tables
- [x] selectable fields to bulk edit specific fields without the clutter
- [ ] tools to apply a change across all rows (maybe this is a different form all together)

Here are some changes to the form data fields:
- [x] change registered grade to be text input
- [ ] add publisher grade
- [x] add fa diary field back in
- [x] allow multiple fa fields or change our business rules to disallow this
- [x] add area admin fields
- [x] add area structured tags
- [x] add route structured tags
- [ ] add route maintenance

**Comment by brendanheywood** [comment]
This is all ideal end state in no real order:

> selectable fields to bulk edit specific fields

How much do we care about this one? Making it clean and responsive will be a lot easier if we only have to deal with on layout. Perhaps doing keyboard shortcuts to jump to fields #1172 will solve much of this?

* [ ] Grades: How about a tweak to the context dropdown to make it easy to see what the default it, and also make common contexts easy to get:

![image](https://cloud.githubusercontent.com/assets/187449/6880285/84946fd2-d57f-11e4-9bdd-d01b05a3f92c.png)

* [ ] rename height to length

* [ ] Merge FA stuff into a single row and make the FA/FFA/Set a drop down, mockup somewhere else. Can still add new ones with a + button but most routes should only have 1 so encourage that behaviour. 

* [ ] Tags. I'm wondering whether we can ditch some. Like most of the access and approach ones we could removed for routes. Flip flopping on this. I do think they should be left and right of each other and a little bit wider so they generally never wrap so take up less vertical space.

* [ ] lat/long should have a picker like a date picker which opens up a tiny map popover, single click to place, or drag to move

**Comment by brendanheywood** [comment]
* [ ] also get rid of the blue hover state border. If it's worth having then it should be permanent on all or based on focus state and not hover state so it works on touch devices.

**Comment by Mdemaillard** [comment]
These can be ticked on the different posts above:

- allow multiple fa fields or change our business rules to disallow this
- add area structured tags
- add route structured tags

- rename height to length
- Merge FA stuff into a single row and make the FA/FFA/Set a drop down, mockup somewhere else. Can still add new ones with a + button but most routes should only have 1 so encourage that behaviour.

- also get rid of the blue hover state border. If it's worth having then it should be permanent on all or based on focus state and not hover state so it works on touch devices.

**Comment by Mdemaillard** [comment]
Another End Goal: use that ultimate Enter form both to Edit AND Create routes ? see #1426

**Comment by rouletout** [comment]
@Mdemaillard I think a lot of this is done - would you mind going through it and take what is open to teh re-design of the form?

**Comment by rouletout** [comment]
Most of this is done with the harmonized form, the rest will be done with the new edit forms, closing
