### ISSUE TITLE
my discussion involving a particular person

### ISSUE THREAD

**Issue by scd** [theCrag/website#1893]
I have had a need where I have to find a discussion against a particular person. 

I have made a few quick backend changes so I can do this via a url, eg:

/climber/scd/messages/mine/cgome

No UX for this yet, but will be useful in many places.

**Comment by brendanheywood** [comment]
Yeah I cruelly meant to log this a while back. Is essentially for
continuing a discussion

Sent from my iPhone

On 21/03/2015, at 10:00 AM, Simon Dale <notifications@github.com> wrote:

I have had a need where I have to find a discussion against a particular
person.

I have made a few quick backend changes so I can do this via a url, eg:

/climber/scd/messages/mine/cgome

No UX for this yet, but will be useful in many places.

—
Reply to this email directly or view it on GitHub
<https://github.com/theCrag/website/issues/1893>.

**Comment by scd** [comment]
I have enhanced the profile page to add a button "X discussions in common" next to the leave a message button. Simple and nice.
