### ISSUE TITLE
Establishing community bona-fide's of a user

### ISSUE THREAD

**Issue by scd** [theCrag/website#1895]
Establishing somebodies bona fide's is useful in establishing permissions and knowing that you are talking to a real community member. We have already got Karma based area permissions and karma/ascents stats are always available on avatars.

The particular area we could improve is for starting and contributing to discussions in forums. This idea was brought up by @brendanheywood in #1864 but I want to separate it into it's own issue.

If somebody signs up to thecrag, how do we know that this person is a genuine community user. Basically it is way too easy for somebody to sign up and spam our forums. The great big spam kill admin button has helped reduce admin load when it happens, but does not stop it happening. There will be other aspects of the site we may wish to use the same business logic, but the forums seem like a good use case.

Proposed bona fide business rules: A user can start or contribute to a public discussion if:
- [ ] they have a minimum Karma (say 500 points- too many to spam updates with minor changes);
- [ ] they have a minimum number of logged ascents (say 30- too many to be bothered with bogus ticks)
- [ ] they are a financial supporter
- [ ] they have been endorsed by another bona fide member
- [ ] they have contributed to 10 forum topics already (this one is circular)

So what does this mean to the genuine user who has signed up to find a partner? Or has lost some gear and has signed up to retrieve it?

The rules will not stop them getting immediate satisfaction, but they may have to pay money or get a friend to put some effort in to endorse them. I'm totally ok with that.

**Comment by brendanheywood** [comment]
From #1898 In fact why not just make this a very simple 1-1 formula, you must have more karma than the number of subscribers? It removed a whole bunch of quasi bullshit logic about crags vs regions vs areas and makes it dynamic as areas grow and/or more people subscribe to them.

**Comment by tomkjaerolsen** [comment]
I like this idea. 

Just one thing, theCrag is used by legitimate users to find other climbs by users who have never logged anything or contributed. These people may not no anyone to verify them. 

There should be some way for these users to post. Maybe have a script page/thing. 

Looking for climbers page: Drop down to choose areas, drop down to choose dates, check boxes for kinds of climbing (sport, trad, bouldering, ice, multi etc) based on this an auto-generated "looking for climbers" post is made.... ?

**Comment by scd** [comment]
I think this is covered in other issues and is just a general discussion. I am closing.
