### ISSUE TITLE
Permissions bug: annotations created by Alex aren't editable by Alex

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1897]
Who:
http://www.thecrag.com/climber/amougenot

For:
http://www.thecrag.com/climbing/australia/queensland/toohey-forest

I've just continued editing The Junkyard, and I've been using annotations in the Pride and Mantle Training Area boulders. My trouble is that when I try and edit annotations that I've already made, I get this message: 

"You have insufficient index permissions to undertake this action. Please click the 'Request Editor Permissions for this Crag' button below to obtain editor permissions for this crag. The editor permissions may take ten minutes to take effect."

Even when I made the area :P The "action" it lists that I don't have permission to do is "Update Area"

Here's the link to the error message: http://www.thecrag.com/CIDS/cgi-bin/cids.cgi?R=%2F624842757&C%3APushReturnURL=%2F624842757&D%3ANetworkNodeID=648913521&C%3AState=19726&C%3AHideNavigation=1

**Comment by brendanheywood** [comment]
Another data point:

Hi there. I recently added a new area and some Boulder problems. Australia, nsw, Sydney metro, north shore, cremorne, primrose park, bum crag. I must have done something wrong, because now when I try to edit the problems it tells me I have insufficient index permissions to make this action.

**Comment by Mdemaillard** [comment]
any recent issue with this ? or was this corrected since by a permission system overhaul ?
@rouletout any idea ? I would close to clean-up.

**Comment by scd** [comment]
It is probably still broken. The issue came after a permissions overhaul.
Areas change permission levels as they get more content, and you can be
able to add an annotation one day and not the next.

**Comment by rouletout** [comment]
This is not fixed but considered "standard behaviour" when eg a crag changes from Emerging to normal... - we can close from my point of view

**Comment by Mdemaillard** [comment]
ahh, got it. 
While emerging, the access has very low restriction to encourage input. When updating to normal, restriction increases. 
So "regular editors" might have enough karma to continue, but "new editors"  won't. 
Which is easily countered by requesting editing rights for the area. 
I agree, closing.
