### ISSUE TITLE
responsive tables

### ISSUE THREAD

**Issue by scd** [theCrag/website#1901]
I just had a quick skim read of this article on responsive tables:

https://css-tricks.com/responsive-data-table-roundup/

Our technique has been to hide stuff, but I also like the idea of giving people the ability to put columns back in.

**Comment by brendanheywood** [comment]
I've tried to avoid ever hiding stuff as then it's just bytes for no reason. This would work where we have pure tabular data but that's actually fairly rare for us, but if we did use one I've had my eye on the filament group for a while.

If there is anything non-trivial that we would consider hiding then it should be there in the first place and we should progressively enhance it. There are a few in particular that I'd like to fix in this camp, like not loading google maps unless were on desktop
