### ISSUE TITLE
Location edit - hover label shows wrong node

### ISSUE THREAD

**Issue by oliverstory** [theCrag/website#1903]
When editing the location of an area in the map view, the hover label near the mouse shows the name of a sibling area (should show the name of the area being edited).

Looks like a 'count from 0 / count from 1' error.

I tried to create a screenshot but the hover label didn't show up - in this example I was editing 'North Buttress' at Booroomba Rocks, but the hover label showed 'Cave Wall', which is the preceding area.

![label bug 2015-04-04 09 34 56](https://cloud.githubusercontent.com/assets/4920113/6990021/81075cf0-daaf-11e4-8d3f-801491f4753a.png)

**Comment by brendanheywood** [comment]
+1 from @DaneEvans duplicate of #2530

**Comment by Mdemaillard** [comment]
+1 this is systematic. Distracting

**Comment by Mdemaillard** [comment]
Duplicate of #1295
