### ISSUE TITLE
Html email format ideas

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1908]
There have been a couple things that I've wanted to do in the recent email template clean up, eg ideas similar to this email from flickr:

![image](https://cloud.githubusercontent.com/assets/187449/7040874/14b55122-de17-11e4-946a-09941de5171d.png)

Ie show a bit more of a blurb about the purpose in the email, maybe some grade stats and recent ticks and shared following. But I didn't get real far on anything because I'm working text markdown which then gets inflated into html and not raw html. We get the cleanish text version of the email for free because of this.

I can embed html into the markdown but then this will get shown in raw in the plain text email. So I'm thinking a really simply solution is an extra markdown option which we only turn on in the email contexts something vaguely like this:

```
some text

<div class="htmlonly">
some html chunk
</div>

some more text
```

I don't really care what the delimiters are. In html this would be retained, when it is processed for text this gets stripped out.

**Comment by scd** [comment]
+1 but I will have to do the stripping part of this issue because it is in the BSIS code. Do everything else and wait until I get back or add it to the BSIS/Email.pm code keep a copy safe and remind me to sync back later.

**Comment by scd** [comment]
Managing our email templating internally. Closing
