### ISSUE TITLE
almost empty coments causes DB error

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#1910]
in the add multiple routes form:

if a comment only contains a line break (/n) than the insertion fails and there is no other way back the data form than the browser back/forth 
![2015-04-09 11_00_41-error _ thecrag](https://cloud.githubusercontent.com/assets/2226714/7063559/0ea7a898-dea8-11e4-8499-2929d153c855.png)

**Comment by scd** [comment]
hot fixed.

Also we are now standardising on removing leading and trailing spaces in descriptions.
