### ISSUE TITLE
Blurred topos due to scaling up of small versions of photos

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1911]
When uploading high-res photos as topo, resolution seems to get automatically reduced. While this understandable, the algorithm seems to be of very low quality, or a click on the topo does not open a better image!?

In the example below, I uploaded a (sharp) 20MPix photo. I tried also with a (nice-looking, sharp) version reduced to 1280x860, but always I get this blurred version as topo. When I click on it, it seems that only the very small "preview" gets enlarged, instead of showing a higher-resolution version.

http://www.thecrag.com/climbing/germany/sachsische-schweiz/gebiet-der-steine/area/15757363

**Comment by scd** [comment]
We store the original and create lower res versions of various sizes. It is good to have a couple of examples where our current techniques are inadequate.

@brendanheywood do you have any recommendations on selecting better image sizes from our pre-baked list

**Comment by brendanheywood** [comment]
@birgander2 first lets confirm that your actually seeing what you *should* be seeing. When I see that topo I get the small topo 212 x 320:

http://www.thecrag.com/image/topo/00002/fixedheightmedium/655669971.jpg

When I click on it, after a second or two the higher res zoomed version loads and replaces it (426 x 640):

http://www.thecrag.com/image/topo/00002/fixedheightoversize/655669971.jpg

So are you seeing the higher res version and you are simply not happy with this, OR are you not seeing the higher res version at all?

A follow-up question, when you view those images directly are you happy with the quality of the pic in terms of blurriness or jpeg compression artefacts, or is it only when it's zoomed in the context of the page that it looks blurry?

If you go to a 'old' and deprecated topo page:

http://www.thecrag.com/topo/655669971

Then it loads an even bigger image at 640 x 960, are you happy with this one?

http://www.thecrag.com/image/topo/00002/fixedwidthoversize/655669971.jpg

**Comment by birgander2** [comment]
All the versions you provided are fine. The small topo image is fine for me, too, but when I click on it I get something like:
![out](https://cloud.githubusercontent.com/assets/6367190/7102825/25ebd40a-e08f-11e4-9c44-4a6dc8c48bf3.jpg)

**Comment by brendanheywood** [comment]
Can you send me your brower details and also a screen of your entire window with all the browser chrome?

**Comment by birgander2** [comment]
Currently Google Chrome Version 41.0.2272.118 m on Windows, but looks quite the same on Firefox 37.0.1. on Linux (my usual platform).

![thecrag](https://cloud.githubusercontent.com/assets/6367190/7161325/d9cee8e8-e38e-11e4-9e4f-4fb90b55e6bc.jpg)

**Comment by brendanheywood** [comment]
Ah yep I know what's going on. When you zoom in it always chooses a size which is exactly double the size of the thumbnail regardless of how big your monitor is. But it always stretches it to try and fix the available space, and you've got a pretty big monitor.

My plan on this is to rewrite it at some point using image sets so it chooses it bases on the size and the pixel density of the device you are on.

**Comment by birgander2** [comment]
I am working in the image processing domain, therefore a simple hint: In such situations it is usually better to select something too big and then shrink it to the destination size. So as a simple solution would be to use a version with a base size of about 1500 pixels before rescaling - should be ok for all cases except for those brand new high density displays.

**Comment by brendanheywood** [comment]
Except that's an awful solution on mobile networks. We already have crags which take minutes to load, if they ever finish at all. It needs to be tailored to the device size so we're not wasting bandwidth.

**Comment by brendanheywood** [comment]
+1 from Philip

**Comment by Drazhar** [comment]
Yes, +1 from me. I think this really is important.
After uploading a topo, most of the time I'm not able to see where the route is, because it's to blurry. I always have to look at my original file and then try to guess what is correct. This makes it really hard for a 2nd person without the original to add a new route, especially at a stitched photo with a lot of perspective distortion.

**Comment by Drazhar** [comment]
+1 from Biba.
She uploaded her first photo topo and the first thing she mentioned is, that after uploading she had a hard time to recognize the route features because the image got to blurry.

**Comment by brendanheywood** [comment]
Our next release plan is all around image resizing, which needs to get sorted first which will fix the root cause issue of this one. See #2029

**Comment by quaestor** [comment]
+1 from me.

@brendanheywood about the problem with mobile networks: shouldn't it be easy to distinguish between mobile and desktop browsers and make a choice which image size to serve depending on that?

And I don't think it's a good idea to just serve images scaled for the device size. People (including me) might want to have the big image nevertheless (e.g. download it beforehand) to be able to get a more detailed view.

**Comment by brendanheywood** [comment]
> @brendanheywood about the problem with mobile networks: shouldn't it be easy to distinguish between mobile and desktop browsers and make a choice which image size to serve depending on that?

It's not just mobile / desktop, that's very black and white and there are really many shades of gray especially if we take into account pixel density and zoom level, which we should and currently don't which is the root cause of the issue here.

> And I don't think it's a good idea to just serve images scaled for the device size. People (including me) might want to have the big image nevertheless (e.g. download it beforehand) to be able to get a more detailed view.

There are currently 2 images used, the initial pic and then a larger one if you zoom into it. The inital pic size is a fixed size and is scaled in browser responsively depending on device. The second zoomed in pic is the one that we are talking about here and is currently simply double the first one but should be bigger if needed. Once #2029 is sorted this will be easy to address

**Comment by birgander2** [comment]
Somehow this problem is still not resolved. In fact, when adding lines to a topo on a (large) PC screen, fine features of the rock are not well visible. Often I open the file seperately in a graphic program just to be able to see, for example, where bolts are placed, etc. In the browser view, this is impossible.

**Comment by brendanheywood** [comment]
Ah! I think I've finally gotten to the bottom of this. I've just made a very simple change so that now the bigger version which is loaded in the background after you zoom in is now 3 x bigger, BUT the topo is still blurrier and it's because the being transformed in css, so it's just scaling up a scaled down version of the big photo as a bitmap so it's losing all the extra pixels! :(

So I need to change something more fundamental in the way that the topo zooms in, which is a little more work ... seeing just how much work..

**Comment by rouletout** [comment]
Ahh cool

**Comment by scd** [comment]
nice pickup, at least we now know

**Comment by brendanheywood** [comment]
I have a prototype which is scaling pixel perfect, I just need to sort out the animation side and do a bunch of maths to get the positioning right which

**Comment by brendanheywood** [comment]
+1 from @quaestor via https://github.com/theCrag/website/issues/3054

**Comment by brendanheywood** [comment]
+1 via https://github.com/theCrag/website/issues/3290

**Comment by brendanheywood** [comment]
+1 support (kinda related)

**Comment by brendanheywood** [comment]
+1 support (general touch issues on mobile, especially with editing)

**Comment by brendanheywood** [comment]
+1 https://www.thecrag.com/discussion/2612497389

**Comment by rouletout** [comment]
Zoom level increased, picture available in higher resolution as of now
