### ISSUE TITLE
Turn parent area references into links for node facet search

### ISSUE THREAD

**Issue by scd** [theCrag/website#1912]
in this search

https://www.thecrag.com/nodes/fuzzy-search/stalagmite%20...

the reference to Preludes Wall is actually linked to Preludes Wall.

**Comment by ajfclark** [comment]
Thanks.

**Comment by brendanheywood** [comment]
I've turned the crumb trail into links in dev:

![image](https://cloud.githubusercontent.com/assets/187449/7319979/e86ed7be-eadc-11e4-8e1d-2a29a5d14dd9.png)
