### ISSUE TITLE
Crags with Saxon grades need default context at crag level

### ISSUE THREAD

**Issue by scd** [theCrag/website#1915]
http://www.thecrag.com/climbing/germany/sachsische-schweiz/gebiet-der-steine/area/15757363

Germany has a default context of UIAA, but there are crags in Germany which are Saxon grades.

UIAA and Saxon grades clash.

We need a default context at the area level to resolve the display issue where grades are shown as "{SX} II".

**Comment by nicHoch** [comment]
I will provide a list of crags in Germany with saxon grades as default
soon. There might be a similar problem in Czech
Am 24.04.2015 00:10 schrieb "Simon Dale" <notifications@github.com>:

**Comment by birgander2** [comment]
Ah yes, Czech also use SX grades is some crags.

**Comment by scd** [comment]
What is the common Czech grade(s). We have set the context to US, possibly just from lack of knowledge.

FYI - context is a necessary evil. It tells theCrag which systems to prioritise when parsing free text grades. If it is set wrong the only thing it may do is interpret a grade as a  different system to what locals would expect.

**Comment by birgander2** [comment]
To my knowledge, Saxon grades are the most common, plus several Czech variations. UIAA is used, too. For sure not US. It's a bit chaotic because the pure difficulty is often only a second order problem - if you ever climbed on Czech sandstone you know what I mean.

**Comment by scd** [comment]
This is mostly done. I have added the ability to set a default context at an area level, but it will not be available until the next release. This issue will require release followup.

@birgander2 should we be setting the whole of Sächsische Schweiz to SX?

http://www.thecrag.com/climbing/germany/sachsische-schweiz

**Comment by birgander2** [comment]
Yes, to my knowledge whole Sächsische Schweiz uses Saxon grades - exept some very few sport climbing cliffs which use UIAA. In Bahratal there is quite some bouldering (not yet in database) using Fontainbleau grades.

**Comment by scd** [comment]
I have assigned the whole of Sächsische Schweiz to Saxon grading context. Le me know the areas which I have to assign it back to UIAA.

BTW, Font bouldering grades work under both Saxon and UIAA contexts.
