### ISSUE TITLE
Is sweden country context wrong?

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1916]
eg this ssems to suggest default should be norwegian not french?

http://www.thecrag.com/climbing/sweden/bohus/area/664165251

Some references seem to suggest the 'Norwegian' system should actually be called the Nordic system or Scandinavian system.

Some references seem to suggest french and nordic are used side by side in sweden for sport and trad respectively but depends on the crag.

http://www.sverigeforaren.se/gradsystem/

**Comment by birgander2** [comment]
No idea about default there, but the conversion table (a pdf) I usually use show me a Norwegian _and_ a Swedish system. Quite similar, but not identical.

**Comment by brendanheywood** [comment]
Can you provide that reference and any others you've seen?

**Comment by birgander2** [comment]
https://drive.google.com/file/d/0B1Q2uVOZIGDQY3FQblI5YTAyVlk/view?usp=sharing

**Comment by brendanheywood** [comment]
weird how it starts the same, diverges and then at the hard grades it matches back up again

**Comment by scd** [comment]
Let me try and summarise the changes here:
 - [ ] There is a grade context called 'Norwegian'. Leave this as it is.
 - [ ] Change the 'Norwegian' grading system to Nordic system. 
 - [ ] Create a new grade context called 'Swedish' (note if we are going to parse grades which look the same but have different meanings then we need a new context).
 - [ ] Create a new grading system called 'Swedish' and put it in the Swedish context.
 - [ ] Create grade conversions for Swedish system to be based on Norwegian system with some adjustments in the middle as per PDF document (which I have difficulty reading).

@brendanheywood and @birgander2 does this seem like a reasonable task list to you guys?

**Comment by brendanheywood** [comment]
Lets get some locals out to help:

http://www.thecrag.com/discussion/730468089

**Comment by birgander2** [comment]
Yes, sounds reasonable. As a side note: for bouldering Fontainebleau is used, at least in the Swedish crag I have been recently.

**Comment by davideroverso** [comment]
I don't believe there is a single answer to this question. About the Swedish grade system, you can use the following sources:
http://www.sverigeforaren.se/wp-content/uploads/2013/12/Graderingstabell.gif
http://www.ostersundskk.se/info/graderingar.gif
http://www.bohusbergen.se/media/54873/gradcall.gif
http://www.bohusbergen.se/lite-blandat/graderingsjamforelse
http://ukk.nu/?page_id=115
http://klattrarna.se/index.php/nyborjarguider/2-klattringens-graderingssystem

It is sometimes the case that trad routes are graded with the Swedish system, and bolted/sport routes are graded with the French system

**Comment by MadsAndreasen** [comment]
Hi, 
As david mentioned there probably isn't a single answer. 
However the Swedish spots that I've been to have followed the swedish grading system for trad, french for sport and Font for bouldering. So if if we are looking for a default, it's a pretty safe bet.

The norwegian system should stay as is.

As there is a comment for a nordic system, I should add that for Denmark (Bornholm) the swedish system, I have described above, is used.

**Comment by davideroverso** [comment]
Here are the grades as reported in two of the most recent climbing guides in Norway and Sweden respectively. 
![2015-09-15 19 51 31-1](https://cloud.githubusercontent.com/assets/4112626/9897904/ff351192-5c4d-11e5-8ed4-c4ed7c44b3aa.jpg)
![2015-09-15 19 52 30](https://cloud.githubusercontent.com/assets/4112626/9897910/081f29d2-5c4e-11e5-8aac-68aa8039796d.jpg)

**Comment by scd** [comment]
I have added the configuration in dev. 

After release I have to update context for Sweden
