### ISSUE TITLE
Weird gym tick type behaviour depends on previous history?

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1921]
From Roscoe:

Though now I observe an odd behavior, notice the popularity graph for each climb here:
http://www.thecrag.com/climbing/australia/inner-west/sydney-indoor-climbing-gym-st-peters/area/276357525

For the ones with any number of bars, I can only log General Ascents, Lead Ascents, or Attempted Ascents tick types.

For the other climbs, with no bars in the popularity graph, I can use all the regular types of tick.

(I removed my ascents as I was wondering if the transition from outdoor to indoor crag might have contributed to the problem).

eg this only has the gym ticks:

http://www.thecrag.com/climbing/australia/inner-west/sydney-indoor-climbing-gym-st-peters/route/276359838

but this has all tick types:
http://www.thecrag.com/climbing/australia/inner-west/sydney-indoor-climbing-gym-st-peters/route/276357702

Brendan: Sure we can fix this but it's probably worht reviewing the gym tick filtered subset idea as it has caused a few issues, I'm thinking we need to either may it only filtered for particular gyms which we setup when they come on board, and if not they default to the normal set of ticks, OR we still use the gym logic but instead of filtering we just reorder the tick types so the common ones are at the top but you can still use any tick type.

**Comment by birgander2** [comment]
And when fixing, remember to include the possibility of toprope ascents of gym sport routes...

**Comment by scd** [comment]
I think this is a bug when transitioning from an outdoor area to a gym. Some route information becomes stale in the route cache. There is no process to reset the cache for all ancestor routes when you change the area type.

I think it was just a coincidence that the routes with bars showed different tick types. Perhaps their cache was reset when people logged ascents. The cache fixes itself in about a week, so all routes now have the correctly limited tick types.

There is a manual process I can trigger if this happens again. This failure mode is rare and once off, so it is of lower priority to fix. It may be quite involved to fix as well. Maybe we should just close this issue.

FYI, I have added top rope tick types to gym sport routes.

**Comment by scd** [comment]
Closing. The work around is to manually refresh the cache when we change an area over from a crag to a gym.
