### ISSUE TITLE
Topo editing hidden segment/belay bug

### ISSUE THREAD

**Issue by ajfclark** [theCrag/website#1923]
Marking a segment as both a belay and hidden appears to work, but on reloading the topo, the segment is visible and a belay.

eg. Eskimo nell

![1](https://cloud.githubusercontent.com/assets/2166856/7448730/4c39fb9a-f265-11e4-84fa-196c92396071.jpg)

After marking the segment to the jetty as a belay looks fine in the editor:

![unnamed](https://cloud.githubusercontent.com/assets/2166856/7448757/06085fe4-f266-11e4-83c1-12fc8f5e490a.png)

but on reloading:

![2](https://cloud.githubusercontent.com/assets/2166856/7448737/9245239e-f265-11e4-92ff-c1a7fc47ecc6.jpg)

Marking another segment that was a belay visible as hidden results:

![3](https://cloud.githubusercontent.com/assets/2166856/7448740/a816bab6-f265-11e4-8183-13b03820643d.jpg)

Workaround is to add a very short segment between the belay and the hidden section.

**Comment by pmonks** [comment]
Just confirming that this bug is still occurring, and the workaround (adding a very short intermediate segment) isn't always possible.

**Comment by brendanheywood** [comment]
Fixed in dev
