### ISSUE TITLE
backend script for bulk update of pitch info

### ISSUE THREAD

**Issue by scd** [theCrag/website#1926]
from Dirk...

Hi Simon,

in this area almost all routes are single pitches:
http://www.thecrag.com/climbing/germany/frankenjura

Do you also think it's useful to set "Pitches" of routes to "1" in order to improve data quality?!

I think only 30 of over 10000 routes have more then one pitch.

I could check these ones after your bulk operation. It's easier than editing thousand of routes. :-)

Regards

**Comment by brendanheywood** [comment]
Isn't this a relatively safe assumption? Even if pitches is set to 1 this won't show anywhere except the edit page so is there much value in this?

**Comment by scd** [comment]
Not doing
