### ISSUE TITLE
Make snap marker form in locate page accept more formats

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1928]
I was trying to correct the location of some crags in Kochel, Germany
(which in the end didn't work due to a lack of editor rights) when I
came across this weird behavior:

I tried to set a Temporary snap marker with the following coordinates
47°37'42"N, 11°19'53"E
that should be at Atlantiswand in Kochel, Germany. theCrag put the
marker somewhere in Somalia at 11"19'53"N, 47°37'42"E. The system seems
to be messing up latitude and longitude of the snap markers.
The live coordinates underneath the map are correct though.

best regards
 bastimuc

**Comment by brendanheywood** [comment]
@scd did this one get fixed recently?

**Comment by scd** [comment]
I don't think so. I forgot about this issue when looking at the js file, so I am pretty sure this issue is still there.

**Comment by rouletout** [comment]
This works correctly, closing
