### ISSUE TITLE
use UX structured tag field to enter generic hash tags

### ISSUE THREAD

**Issue by scd** [theCrag/website#1931]
Should we allow people to enter generic hash tags into the structured tags field?

Given the recent changes to the UX it seems natural. It would have to be separated for the database. There will be a couple of issues to consider, but I think it would be doable using select2, a new database field and some logic to split and combine the hash tags in the UX

**Comment by brendanheywood** [comment]
Yup, seems ok - any existing tags added to the current node would get put into an 'other' group in the select2 drop downs. We'd need to make it clear that these tags are not inherited which is the main functional difference.

**Comment by rouletout** [comment]
We do not want that (anymore?) - closing
