### ISSUE TITLE
Deprioritize Ethics in route detail page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1933]
![image](https://cloud.githubusercontent.com/assets/187449/19267282/a565acfe-8ff9-11e6-9c1b-8a674c8d8a8d.png)

**Comment by Mdemaillard** [comment]
Implemented, Ethic comes fairly low.
![image](https://user-images.githubusercontent.com/60388146/76420374-b1650800-63aa-11ea-9381-78a660d68400.png)
Closing
