### ISSUE TITLE
Make FB publishing at the route level, not the loggin process level

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1935]
Same as the other bits, have a default checkbox, then a checkbox at each route level. (from Jed)

**Comment by scd** [comment]
Is this more about the fb sharing being broken. FB sharing is currently at the ascent level, with the default setting at the account level.

**Comment by brendanheywood** [comment]
No completely blue sky concept - I find myself wanting to share something like 'Brendan climbed 3 routes at Arapiles, including sending Kachoong' ie suspiciously close to the summary that we are working through for the streams stuff. So I think once we are done refining the streams stuff making the fb publish consistent. And also the atom feeds etc

I find myself constantly not publishing to FB because it's too spammy and fine grained if I've ticked 10 routes, and most people I've talked to say the same thing.

**Comment by scd** [comment]
ok, now I get it.

**Comment by brendanheywood** [comment]
Actually I've confused this with another card - above is still true, but this one is specially from Jed round making the FB publish something you can turn on and off for each route, not simply globally for all ticks. At the moment if you tick 10 things and want to publish 5 you have to do the ticking process twice, and this also messes up the order you tick them in. For this reason and others I almost always tick my routes individually and not as a batch, and Jed does the same

**Comment by scd** [comment]
Gotcha. I thought it was a stretch from the original description. Which other card were you referring to because this is a new concept in my mind. Maybe you have been thinking of it and have not recorded it yet.

So we want to move the Facebook checkbox being global for all bulk ascents to be next to each individual ascent.

The account settings will not change.

**Comment by brendanheywood** [comment]
Ideally it should be like the other settings like 'with' and date with a process level default, and route level override.

**Comment by brendanheywood** [comment]
Killing this as we've deprecated it. This is already technically back in an indirect way via sharing of the stream event page
