### ISSUE TITLE
Custom PDF failing for a particular account

### ISSUE THREAD

**Issue by scd** [theCrag/website#1936]
The system reporting an error status in the custom PDF management page.

http://www.thecrag.com/climber/luman

Problem exists for all areas with this account. Other accounts are working. Works on dev, but not on prod. At the time dev is significantly out of date. In particular the avatar has changed.

 - [ ] check to see if there are problems with the avatar for this account for pdf production.

**Comment by mindrunner** [comment]
+1

**Comment by scd** [comment]
FOP does not like the avatar for this account. The diagnostics for this software are so crap it is really not worth my time trying to figure out why. Instead I have commented out the avatar in all custom PDFs. Will bring back in after we replace the PDF stack.

**Comment by scd** [comment]
hot fixed

**Comment by mindrunner** [comment]
Too bad not being famous anymore on my guidebooks! :D Thanks for the Fix Simon, just checked and its working for me!!! :))
