### ISSUE TITLE
prod bug with streams from Tom KJ

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1937]
From @tomkjaerolsen

> On the phone, so awkward to log on github, but, stream page is not working:
Apache Module Load Portal Error: Error: Can't use an undefined value as an ARRAY reference at /opt/CIDS/cgi-bin/templates/html/thecrag/stream/event-customise line 6. Stack: [/opt/CIDS/cgi-bin/templates/html/thecrag/stream/event-customise:6] [/opt/CIDS/cgi-bin/templates/html/thecrag/stream/stream:160] [:104]

**Comment by scd** [comment]
hot fixed
