### ISSUE TITLE
Wrong display of "with" in trip view

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1938]
Instead of the names of my buddies, I get something like @395456196,@67561699 displayed in the "with" column. Also the grades have a gray background instead of the usual ones,

**Comment by brendanheywood** [comment]
Can you send a url of a page with this bug please?

**Comment by birgander2** [comment]
Sure:  http://www.thecrag.com/trip/649445799

**Comment by scd** [comment]
hot fixed
