### ISSUE TITLE
Filter for ascent date in logbook search

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1939]
I miss this feature, for example if I want to know what I have climbed in 2005. Every other detail can be filtered, but not a from->to interval for the ascents.

**Comment by brendanheywood** [comment]
This is an undocument feature which works but doesn't have an interface yet:

https://www.thecrag.com/ascents/by/brendanheywood/before/2014

https://www.thecrag.com/ascents/by/brendanheywood/after/2010

**Comment by brendanheywood** [comment]
Done a while back
