### ISSUE TITLE
Permissions not working for premium crags

### ISSUE THREAD

**Issue by scd** [theCrag/website#1941]
We had a rule which required at least coordinator permission for editing premium crags (a premium crag is one where we have assessed the information quality to be very well developed). 

This meant that when a crag went from high value to premium value people who previously had editor permissions were no longer able to edit. Hence the permissions requests in Blue Mountains.

There were a number of other issues:

 - [x] Premium value area has the same permissions requirement as High value area.
 - [x] You can no longer automatically get permissions for a Premium area, but if you have got editor permissions already you still have the capability of editing. Note that people will have to email us for permissions on high value areas.
 - [x] If you have an existing permission record which is insufficient then the request permissions process reports this rather than throwing a server error
 - [x] Made the request permissions process link to a consistent ancestor area as for admin grants and for system evaluating permissions.
 - [x] Updated the algorithm for assessing Premium crags to be a little more rigerous.

Hot fixed.

**Comment by brendanheywood** [comment]
The premium stuff automatically reducing rights is definitely an anti feature and a by product of the defunct business model for the dead app

**Comment by scd** [comment]
I cannot blame everything on the app, it was probably more about me not thinking it through correctly. We did not have any premium crags up until recently, so it was untested.

Being more protective of better developed crags I think is something we need to preserve. That is still in there and working ok. I am happy to discuss this further, I think that in this instance the reduction in permissions was way to harsh.

**Comment by brendanheywood** [comment]
We already have the concept of the locked crag, I don't see the need for the premium concept - or is this just the same stuff under the hood? Either way I don't think a high traffic and value crag should naturally progress into a more locked down state, this sends the wrong message to content creators and isn't conducing to community relations. It's not so much the apps fault but the mentality that went with it which is that we 'own' the content and we derive value by rent seeking which is just wrong, the community owns the content and we add value by helping share, publish and distribute it. From this perspective locking down the crag is obviously counter productive.

Locking a crag should be restricted to specific cases where there is physical issues with the crag that need to be catered for (eg private crag, gyms, banned crag), or where there is unfortunately some crap like flame wars going on purely online. And the latter I think we can better solve other ways and use this is just a last resort.

Either way it should be manual and used with care, definitely not automatic.

**Comment by scd** [comment]
I agree with that from the point of view of premium crags. It became very clear when we got all the support emails about losing blue mountains permissions. I imagine it would have been stressful for some people as well.

I am however I am now comfortable to not automatically grant permissions to premium crags. It is good to know the system will start to become more protective of our best crags even if we do nothing.

From the other end of the scale, having very loose permissions requirements for emerging crags and regions has been working. Or am I deceiving myself. For countries where there is virtually no content we don't really want to get involved in creating crags.

Maybe things are not working so well at the emerging end of the scale as well, and people are not emailing us with support queries.

Thinking out aloud, maybe the only thing that should change is how you get permissions. For example:
  * For emerging regions and crags you can automatically get editor permissions for regions and crags
  * For established regions we need to review your request before it is granted
  * For established crags you can still automatically get editor permissions
  * For premium crags we need to review your request before it is granted.

**Comment by brendanheywood** [comment]
A thought: Blue mountains as a crag is completely arbitrary, yes it may be 'established' but crags within it may be completely new and undeveloped. This happens across the board, Araps, gramps etc

I think the key issue here was really knowing what was going on, if a crag gets locked down for any reason it should be A) clear to someone trying to edit what is going on B) super clear to us C) if stuff changes we should get an email or whatever with what's changed. The transparency should be good regardless of what business rules we have in place for permissions

**Comment by scd** [comment]
agreed. I think further discussion and work is required in this area. I have fixed the critical stuff and imo the rest is lower priority and a distraction compared with streams and mobile app work.
