### ISSUE TITLE
Malformed topo data

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1944]
hhmm:

http://www.thecrag.com/climbing/australia/queensland/area/433051080

need to understand root cause of how this is happening

**Comment by scd** [comment]
I will look into this, this afternoon. I recon it is something I touched in my bug fixes.

**Comment by scd** [comment]
ok hot fixed.

It was related to #1934 but was to do with the other untested use cases that I was suspicious about. I think it is just a happy coincidence that it was discovered soon after I made the other changes as I did not touch the escape sequence for this particular use case.

So it is good that we found this and I am happy that we have the test scenario.

**Comment by Proxy0** [comment]
Not sure if this is the same Malformed JSON topo data problem...

https://www.thecrag.com/climbing/australia/nowra/new-nowra-braidwood-road/area/188637924

https://www.thecrag.com/188637924/topo?edit=701643000

Cannot assign routes to Topo 9971. Tried reloading the image and another similar in case problem was with the jpeg itself but issue persisted. Tried in both Chrome and Internet Explorer.

Cheers, Nathan

**Comment by scd** [comment]
there was a tab in one of the route names which caused the problem. I have created another issue to stop tabs getting into the route name in the first place #1955 

FYI, please reopen issue if you think it is not fixed.
