### ISSUE TITLE
Ascent facet filter via ascent grade instead of route grade

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1946]
From Jed 

https://www.thecrag.com/ascents/by/10765333/with-tick-type/7509964+7509970+7509976+7509982+7509988+7509994+7510000+283385698+7510012+7510018+7510036+333595990+333595996+7510042+276966013+7510054+7510060+7510030+7510066+167766430/with-route-grade/AU:26:26/

He wants it to show his grade not the route grade. Possibly half done with no ui, /with-route-grade/ vs /with-ascent-grade/

**Comment by scd** [comment]
not in back end.

Should be quick to implement if we want to restrict to the specified grading system. More difficult if we want to convert grading systems. Let me know which you would prefer.

**Comment by brendanheywood** [comment]
Probably makes sense to do the conversion to make it independent, the ui I'd imagine is just a tick box or toggle saying 'Your grade / Registered grade' so they should filter the same

**Comment by scd** [comment]
The conversion does not take into account boulder routes v trad routes. It
converts everything.

**Comment by brendanheywood** [comment]
yup, so if you want to filter to boulder you do it the same way as before, that's what I meant by keeping it independent. All facets should be independent

**Comment by jedparkes** [comment]
I think this is the same issue as
https://github.com/theCrag/website/issues/2257

**Comment by brendanheywood** [comment]
yup, I think I'll just close this duplicate, thanks @jedparkes
