### ISSUE TITLE
Markdown links don't work with hash anchors

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1948]
ie this doesn't link:

http://www.nationalparks.nsw.gov.au/visit-a-park/parks/kwiambal-national-park/Visitor-Info#Getting-there-and-parking

but this does:

http://www.nationalparks.nsw.gov.au/visit-a-park/parks/kwiambal-national-park/Visitor-Info

**Comment by brendanheywood** [comment]
Failing example in dev

http://dev.thecrag.com/climbing/kazakhstan/astana

**Comment by scd** [comment]
We get this regex from a perl library. The hash anchor fragment is missing from this code. I have done a regex on the regex to insert the fragment component. 

Hot fixed and in repo.
