### ISSUE TITLE
Internal links in crag description don't link

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1952]
When entering acrag description, preview correctly shows the (automatic) links, but on the final website nothing is linked. Example: http://www.thecrag.com/climbing/germany/allgaeu/area/700226571

**Comment by scd** [comment]
Note to self. The internal links are broken, eg 'Kraftwand' is not linking to the crag.

**Comment by scd** [comment]
After a little bit of testing I think this is to do with a miss alignment of top level crag settings between the two contexts.

**Comment by scd** [comment]
Actually upon further investigation it was not top level crag, just a coincidental initial diagnosis. In the bulk edit we are looking for parent node internal links, but in the index page we were not looking at parent node. This would only come up as a problem at the top level crag or above.

I have aligned the code and hot fixed.
