### ISSUE TITLE
do not geo locate features within a gym

### ISSUE THREAD

**Issue by scd** [theCrag/website#1957]
sub areas (features) of a gym should not have geo location

eg 
http://www.thecrag.com/climbing/australia/queensland/brisbane/rocksports-indoor-climbing/area/702224490

**Comment by brendanheywood** [comment]
I half agree, I think gym areas *could* be located, but it shouldn't complain if they are missing. And certainly not to an end user, only to admin staff if at all.

ie these are located:

http://www.thecrag.com/climbing/australia/inner-west/sydney-indoor-climbing-gym-st-peters

**Comment by scd** [comment]
yup it is totally reasonable that a gym covers a wide enough area that geo locating sub areas is appropriate. However the counter example I think should have never have been geolocated. In this case it looks strange and means you have to scroll further to get to the useful content.

Regardless your point is valid. I have hot fixed this. If somebody wants to geo locate a sub area of a gym then they can use the action button.
