### ISSUE TITLE
shorter urls for gym QR codes

### ISSUE THREAD

**Issue by scd** [theCrag/website#1958]
- [x] allow '/c/' instead of '/climbing/' to shorten the url
 - [x] the QR code template should select the shortest url
 - [x] set policy for url codes for gyms

**Comment by scd** [comment]
Hmmm, the google tracking stuff ads a lot. I recommend we dump the google tracking codes. 

https://www.thecrag.com/c/rs/2
vs
https://www.thecrag.com/c/rs/2?utm_source=gym%26utm_medium=qr%26utm_campaign=-

Here are three versions:

Optimised with google tracking:
http://chart.apis.google.com/chart?chs=200x200&cht=qr&choe=UTF-8&chl=https://www.thecrag.com/c/rs/2?utm_source=gym%26utm_medium=qr%26utm_campaign=-

Optimised without google tracking
http://chart.apis.google.com/chart?chs=200x200&cht=qr&choe=UTF-8&chl=https://www.thecrag.com/c/rs/2

Not optimised
http://chart.apis.google.com/chart?chs=200x200&cht=qr&choe=UTF-8&chl=https://www.thecrag.com/climbing/australia/queensland/brisbane/rocksports-indoor-climbing/room1/rope1?utm_source=gym%26utm_medium=qr%26utm_campaign=-

**Comment by scd** [comment]
OK I have just done it without the tracking code, and it is a vast improvement. The tracking code offers marginal benefits for a big cost in this particular use case. My vote is we dump the ga tracking codes for QR codes in gyms.

**Comment by scd** [comment]
I am happy with the gym policy of having an alternate abbreviate url stub
 - [ ] have a full cannocial url stub at the gym node 
 - [ ] have an alternate url stub at the gym node to claim the abbreviation (eg 'rs' for rocksports)
 - [ ] at each rope have the cannonical and alternate url stubs. The alternate will be something like 'rs/1' for rope 1.
 - [ ] don't have alternate stubs for inbetween areas, but do have cannonical for completeness.

**Comment by brendanheywood** [comment]
The point of the ga tracking is to know where it came from, which is redundant if only the qr codes ever use the short urls. Downside is we have to look in two places for page view stats, but we can fix this in the template by rewriting the URL we give to ga into the canonical version if we want
