### ISSUE TITLE
QR print code page to show all areas when nested

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1959]
ie 

http://www.thecrag.com/climbing/australia/queensland/brisbane/rocksports-indoor-climbing?gym=red,blue,green,purple,black

only shows the rooms, not the ropes which is what we need. At the moment you have to go to 6 pages to get what you need.

**Comment by scd** [comment]
This is a bit of a pain, as it needs different template data. Maybe rather
then children I get descendant features?

**Comment by brendanheywood** [comment]
This will easy if we call the alternate template from the crag guide page
as its all ready to go there. Will see how required it is first with this
gym, I have a feeling they might be doing custom tags??

Sent from my iPhone

On 19/07/2015, at 9:20 AM, Simon Dale <notifications@github.com> wrote:

This is a bit of a pain, as it needs different template data. Maybe rather
then children I get descendant features?
On Jul 19, 2015 8:24 AM, "Brendan Heywood" <notifications@github.com> wrote:

> ie
>
>
>
http://www.thecrag.com/climbing/australia/queensland/brisbane/rocksports-indoor-climbing?gym=red,blue,green,purple,black
>
> only shows the rooms, not the ropes which is what we need. At the moment
> you have to go to 6 pages to get what you need.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theCrag/website/issues/1959>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/theCrag/website/issues/1959#issuecomment-122604287>.

**Comment by scd** [comment]
I thought about doing it this way, but there is a bit of template swapping, then some code additions to the template to make sure you are showing the rope features. Also there are some historical arbtrary limitations on crag guide data (eg 500 routes) which I don't like, and is probably ok for smaller gyms.

I think the smallest code change will be replacing child query with descendant feature query in the same data template.

If Thomas is using this we should definitely fix it, if not then hold off. Do you want to ask Thomas how he is doing it.

**Comment by scd** [comment]
hot fixed. It was just a couple of lines to replace children with all area descendants when gym card trigger conditions are meet.

Actually as a useful by product we get all areas (not just ropes) including the gym itself.

**Comment by brendanheywood** [comment]
demo url? I couldn't see this working

**Comment by scd** [comment]
The url you posted above:

http://www.thecrag.com/climbing/australia/queensland/brisbane/rocksports-indoor-climbing?gym=red,blue,green,purple,black
