### ISSUE TITLE
gym spreadsheet bulk edit / update

### ISSUE THREAD

**Issue by scd** [theCrag/website#1962]
We may need a spreadsheet bulk edit method of updating gyms.

Dump from email discussion ...

```
    Yup, make their lives really really easy - in particular making updating the routes as easy as possible. I'd guess that most gyms with any sort of size will have it all done neatly in excel, so a bulk replacing upload of their existing files would be a good win here (and later dropbox sync etc).


The one difficult constraint here is that we need to archive old routes. In excel it is how it is, so we will have to work out whether we rename or archive.
```

Definitely archive so we don't screw up everything. We'd have to have some good heuristics in place to know when to leave something alone vs archive though, this does need a bit of thrashing out though.,I would suspect that to get the gyms working really well we'd probably introduce features like 'allow suggested grades' and 'allow suggested names' where the climbers can give feedback. So the original names uploaded might be something like 'Rope 7 \ 22 Green'. I guess if the suggested names are always added as alternates we can still match on the original name. But I can easily imagine a situation where a wall is stripped which had '22 Green' on it, and was replaced by another '22 Green' so we need a clear way to differentiate between them. Maybe the spreadsheet must require a set date because that's completely unambiguous. In any case we'd need some sort of 2 step form which shows the changes it's about to make so they can be confirmed.

**Comment by brendanheywood** [comment]
Also as part of chat with Thomas he said he was happy using us as the primary source of info, and the existing excel doc will disappear. So I think we back burner this one

**Comment by scd** [comment]
I think this will be the case for a lot of gyms, once they know they can archive properly using theCrag. It may be useful to use a spreadsheet for setup. If a gym has got more than about 100 routes, I can do the backend bulk import. Eventually we should get this bulk import working using the UI.

Also I am sure a few gyms will use a spreadsheet as input to other steps of their process. So I recon we should still plan a CSV/Excel export of gym data.

**Comment by brendanheywood** [comment]
The other part of the equation is who does it, which will differ from gym to gym. In his case he has between 3-6 setters who set on fridays, and often will be ring in's from elsewhere. So he manages the list of routes after the setting.

**Comment by scd** [comment]
Every friday - cool. With the amount of changes they are making, if we provide any benefits in this area then we are very good value.

**Comment by rouletout** [comment]
Closing this based on internal discussion that we don't want that
