### ISSUE TITLE
markup generating invalid xhtml corrupting pdf production when using strong html element

### ISSUE THREAD

**Issue by scd** [theCrag/website#1963]
https://www.thecrag.com/climbing/australia/south-australia/adelaide/the-enchanted-forest

**Comment by brendanheywood** [comment]
I think we really need to run all this through html tidy first to convert to xhtml. Fixing this in the templates is not always desirable or necessary for normal web output, and it's a very brittle way of fixing it as we may need to touch lots of tiny places.

**Comment by scd** [comment]
The problem here was manually written `<p>...</p>` html elements in the markdown. Our markdown conversion does not expect that for strong -> dt automated conversion. 

So yes our solution is extremely fickle in many ways. I am hoping to abandon the whole stack as soon as we find another solution.
