### ISSUE TITLE
single column pdf not working for enchanged forest

### ISSUE THREAD

**Issue by scd** [theCrag/website#1966]
http://www.thecrag.com/climbing/australia/south-australia/adelaide/the-enchanted-forest

Checked apache download file size limit to small for larger PDFs
Doubled from 2048000 to 4096000

**Comment by brendanheywood** [comment]
Is that 4meg? still seems pretty small for an image heavy pdf

**Comment by scd** [comment]
I mistyped it should be 40M, but I think 100M is better. I have not confirmed that this fixes Jake's problem. Running again now with 100M limit

**Comment by scd** [comment]
Hmmm, still did not work.

**Comment by scd** [comment]
It looks like a resource issue, but something is suspicious.

 * double column pdf works
 * xhtml works for single column
 * single column pdf works for each child
 * tried increasing timeout limit
 * tried increasing download size limit

**Comment by scd** [comment]
It also happens for other large areas such as Arapiles.

**Comment by brendanheywood** [comment]
Closing this as this node is bigger than the node / topo limit for pdfs
