### ISSUE TITLE
upgrade mysql collation character sets to utf4mb4 utf unicode 3 byte

### ISSUE THREAD

**Issue by scd** [theCrag/website#1968]
The collation, utf8, that we currently use, only accepts 3 byte unicode characters. For the full 4 byte unicode characters we need to upgrade to utf8mb4. A good write up of this upgrade procedure is here:

https://mathiasbynens.be/notes/mysql-utf8mb4

This is a significant piece of work and will take some time to write scripts and test and will probably involve a server outage for a significant period of time.

Steps to reproduce:

1) Post in forum this "```test 😤 test```"

2) It will look like it worked, and the preview will also work

3) save it and reload and it is truncated at the unicode char

Test cases:

https://www.thecrag.com/discussion/1763594205

https://www.thecrag.com/discussion/1761290085/kangaroo-point--the-big-traverse-info#m1762926813

https://www.thecrag.com/discussion/984095598/test-area--testing-possible-unicode-bug

https://trello.com/c/OZ17Rp1j

**Comment by lordyavin** [comment]
Bug or enhancement? Milestone?

**Comment by scd** [comment]
This is milestone in it's own right. Nothing else can be done in association with this and it will be time consuming. It needs to be done as it can cause some quite irritating bugs, but as we have survived for 4 years without even noticing it I am not dropping everything to do it. I will consider doing it after the next release.

**Comment by brendanheywood** [comment]
Dup in https://github.com/theCrag/website/issues/3151

**Comment by scd** [comment]
hack fix to remove 4byte utf characters in dev

**Comment by brendanheywood** [comment]
confirmed this is working

**Comment by Mdemaillard** [comment]
is this also leading to these ? 
#2158
#2821

**Comment by Mdemaillard** [comment]
implemented on new server, will be deployed when switching to it.

**Comment by scd** [comment]
done a while ago
