### ISSUE TITLE
Blue Mountains Topos gives Apache Error

### ISSUE THREAD

**Issue by AndreWurl** [theCrag/website#1969]
The link:
https://www.thecrag.com/climbing/australia/blue-mountains/topos

returns the error:
Apache Module Load Portal Error: Error: Not an ARRAY reference at line 210. Stack: [:210]

Ubuntu 14.04 (64-bit)
Browser: 
Chromium Version 43.0.2357.130 
and
Firefox 39.0

**Comment by scd** [comment]
hot fixed the apache error, but there is a deeper issue which I have documented here #1970
