### ISSUE TITLE
topo facet data corruption for topos automatically moved to world area

### ISSUE THREAD

**Issue by scd** [theCrag/website#1970]
This probably needs more research but I am guessing this is the problem with some a world topo being included in the blue mountains search. 

http://www.thecrag.com/climbing/australia/blue-mountains/topos

Actually this breaks some assumptions so initially this caused apache error, which I will hot fix.

**Comment by scd** [comment]
hot fixed the apache error. The first topo has no path, which is because it is assigned to the world node.

From previous work, if we move a route linked to a topo to our purgatory area (ie test node) then the topo will be reassigned to the lowest  common  parent, which is the world node in this case.

Firstly this should never happen. Secondly if it does happen the facet update should be triggered.

**Comment by rouletout** [comment]
No issue anymore, closing
