### ISSUE TITLE
put some restrictions around serious spam account

### ISSUE THREAD

**Issue by scd** [theCrag/website#1971]
Backend 
- [ ] cannot serious spam yourself
- [ ] cannot serious spam anybody with more than 10 ascents or 100 Karma points

Front end
- [ ] Hide serious spam button on private messages
- [ ] Hide serious spam button for yourself and anybody with more than 10 ascents or 100 Karma points.

**Comment by rouletout** [comment]
Spam account review and process implemented, closing
