### ISSUE TITLE
Gym icon in index

### ISSUE THREAD

**Issue by scd** [theCrag/website#1973]
@brendanheywood can you do a gym icon for the index. I think it is worthwhile distinguishing gyms clearly.

**Comment by brendanheywood** [comment]
What's the context and where would it be shown?

**Comment by scd** [comment]
List view. For example Rocksports is fairly list in Brisbane. It also makes
it clear we do gyms as well.

**Comment by scd** [comment]
Maybe we just use a tag in the index. I will have a play to see if there is something easy to implement here.

**Comment by scd** [comment]
i have just used a bootstrap label which now makes gym nodes more obvious when browsing index.
