### ISSUE TITLE
Listview dynamic menu stacking issue

### ISSUE THREAD

**Issue by scd** [theCrag/website#1975]
The problem exists for both non-touch screen and touch screen browsers, however it is a more irritating issue for touchscreen browsers. I have limited access to touchscreen so cannot provide screen shot currently, but the extra problem is that menus on other selected rows get in the way. 

Below is a screen shot of the problem for a non touch screen with topo underneath the route.

![tc-dynamic-menu-stacking](https://cloud.githubusercontent.com/assets/373058/8976799/6896a356-36d5-11e5-9178-016d98fcf87d.png)

**Comment by brendanheywood** [comment]
fixed
