### ISSUE TITLE
replace dasboard and profile page with feed

### ISSUE THREAD

**Issue by scd** [theCrag/website#1983]
- [x] embed stream so it does not effect initial download page
 - [x] stream should automatically embed itself
 - [x] dashboard should load your standard current stream and allow pagination
 - [x] profile should embed 'mine' stream and allow pagination
 - [ ] embed stream on main site home page

**Comment by scd** [comment]
This is mostly done. I think a 12 month current stream window for your 'mine' stream is appropriate. This is the stream which will be embedded in your profile and means that it will automatically pick up any activity up until 12 months ago.

There is one issue I think might be a phototopo issue with embedding which means the topos are not being shown correctly when the stream is embedded. @brendanheywood have a look at your profile.

Actually this is a total guess, and I don't quite have time to investigate right now, but instead am brain dumping some thoughts. We have not done event handling for dynamically loaded content very well in our javascript (at least I have not). Instead of binding events to a particular object we should be using 'on' with a sub selector: eg

$("body").on("click", ".fn-stream-next-events", function(e){

My guess is that there are a couple of event binding issues for topos that are loaded dyncamically. I appologise if I don't have any idea of what I am talking about, it's just a brain dump with very little time to investigate.

**Comment by scd** [comment]
you can pull from repo to see embedded streams in dashboard and profile

**Comment by brendanheywood** [comment]
This looks shit hot :)

The event bind question can be good or bad and depends on the event and the context. Binding the event to a parent can have some quite bad side effects when working with multiple events, like if you bind a 'click' then that means a pseudo click event via a touchstart event on mobiles needs to be registered there which means that normal scrolling get interfered with if you swipe your finger over an area that isn't actually a click target but is inside the bound event target. So just the short story is bind them as low as possible, ie the parent div or whatever isn't changing when stuff gets swapped out. Some js frameworks always bound events at the top level html element and performance quickly became terrible. The main two reasons you want the delegated binding is so you don't have to reattach new events (or clean them up when removing elements) and on really large pages reducing the number of event handlers. The latter isn't really a problem for us, and the former is fairly easy to jut re-add the new event handlers to the new chunk after we ajax it in, so unless there is a really good reason I'd keep it simple and not delegate, or delegate only fairly shallow stuff. This topic is something I've flip flopped on a bit over the years getting burnt in different ways :)

The topo issue looks like it is missing a wrapper div so bits of it are leaking out. I'm having a look now

**Comment by brendanheywood** [comment]
Ok fixed one issue with the action button hovers. I think I know what the loading issue is

**Comment by scd** [comment]
thanks for heads up with the flip flop delegation. I will take care. The streams will be super cool when we have finished. BTW, I am currently only returning 5 events while we are still debugging.

**Comment by brendanheywood** [comment]
Ok root cause is the topo init needs to get called on the new stuff. I've added that but there is a second deeper issue that the html in the chunk is malformed and so the topo is loading and not getting inserted into the dom correctly. Looks like a missing closing div somewhere but haven't tracked it down so far yet. Might get a bit more time tonight

**Comment by scd** [comment]
Thanks for getting onto this so quickly, it is great to have momentum again on a piece of work.

**Comment by scd** [comment]
I think I can close this. The outstanding tasks are not directly related to this issue.

**Comment by brendanheywood** [comment]
Ok the topos are all good now, pushed
