### ISSUE TITLE
mentions should trigger a person being involved in an event

### ISSUE THREAD

**Issue by scd** [theCrag/website#1985]
This is a reminder issue to complete the work. I think it is just a matter of passing the mentions to the activity logging function.

**Comment by scd** [comment]
Started on this. 

Where ever there is a mention change I will include that in the people involved in the event. This means:
 - [ ] if you mention somebody for the first time in a comment then they will be flagged as involved and the event will appear in their 'stream/mine'.
 - [ ] if somebody is already mentioned in a description and you change part of the description without changing the mention then that person will not be flagged as involved in the event.
 - [ ] if you remove a mention from a description then that mention will not be flagged as involved in the event. 

I think we will have to list all people in the event in the template. Some template changes for this.

**Comment by scd** [comment]
I think we could make the mentions more explicit in the event activity item in the template. 

Eg Simon Dale added a route ... mentioned Brendan Heywood.

I will have a play

**Comment by brendanheywood** [comment]
cool. Will this also pick up the FA links? That would be very cool to see when someone documents a route properly with your details and you get pinged

**Comment by scd** [comment]
It will pick up FA links and with links in ascents and climber links in photos. They actually look really cool as an event, so much more meat to it. However you don't get pinged, in fact you will not even see it in your own dashboard stream as it is currently set up. 

I think we need to add one more configuration item to the dashboard, which is 'myself' - see #1989 

@brendanheywood your challenge is to put your thinking cap on about pinging mentions yourself more explicitly. Maybe an email, once a day/week showing where you have been mentioned.

**Comment by scd** [comment]
The upload, tick and update event summary now looks something like this:

Simon Dale updated some areas and a route at Mt Hope and mentioned Brendan Heywood and Campbell Gome

**Comment by brendanheywood** [comment]
![image](https://cloud.githubusercontent.com/assets/187449/9214712/65b282cc-40e4-11e5-8e31-998c68fd08d8.png)

Bug: Evil brendan mentioned good brendan

**Comment by brendanheywood** [comment]
Should also markup and link to the mentioned persons.

Also probably need to think about layout for this, I can easily imagine doing an update to an area and fixing a bunch of old FA's into proper links, could be lots of people.  Maybe just leave it and see how it looks to inform what we want to change

**Comment by brendanheywood** [comment]
Seems the 'direct' / 'indirect' data or logic is a bit wrong?

**Comment by scd** [comment]
I think this is something to do with private accounts.

Which account were you logged in as? Is Good Brendan linked to Evil Brendan and vice versa?

I found a permissions bug issue where accounts have been disabled. Maybe pull and try again but I doubt I have fixed this.

I think we should just say "mentioned lot's of people" if there are more than 5 mentions. This will be an issue for all event types. The same goes for the avatars.

**Comment by scd** [comment]
Doh it was a simple bug which had nothing to do with the logic, I was just displaying the wrong variable under certain conditions. 

Also if a persons account makes it to the streams then they have already passed all the privacy checks, so I do not have to restrict template data for private accounts.

Pushed.
