### ISSUE TITLE
Stream involved avatar overflow

### ISSUE THREAD

**Issue by scd** [theCrag/website#1994]
There are a couple of use cases which can cause lots of avatars to be included in a stream event as being involved in the event.

1. Discussion where lots of people have contributed.
2. An editor has made lots of mentions

If you display too many avatars in the beginning of an event then this will look ridiculous as well as taking up server resources.

Limit the displayed avatars according to the following business rules:
 - [x] if there are more that 20 avatars show 15 followed by a tag +x others
 - [x] if there are less than 20 avatars show all 20

At this stage we prepare the data for all accounts and do the limiting at the template end. However if there cases where there are significantly more than 20 accounts then maybe we should limit earlier in the process to save server resources. I am happy to watch and see with this one.

This logic applies for every event.

**Comment by brendanheywood** [comment]
Got an example of this on dev? I haven't seen it in action yet but my gut feeling is that 20 is too big and it should be more like 5, did a quick mockup (was also toying with the overlapping styling - thoughts?):

![image](https://cloud.githubusercontent.com/assets/187449/9219864/5dad62e4-4121-11e5-850a-ba93c55aa5b6.png)

**Comment by scd** [comment]
overlap the other way, because the first on the list will be the prime (the contributor or the person who started the discussion). 

There are two parameters in stream template which control  how many  are shown (maybe change it down from 5 & 15 to 2 & 5. Which means if there are 7 or less then they are all shown and if there are more than 7 then only 5 will show. I will be guided by what you think. Note that it will apply to both updates and discussions.

**Comment by brendanheywood** [comment]
Ok had a play and found some forums with heaps of people:

http://dev.thecrag.com/climbing/australia/north-shore/area/12011275/stream

I've played made the overlap slowly more and more and tune the numbers so it looks good on destop and mobile:

![image](https://cloud.githubusercontent.com/assets/187449/9277798/c511e78c-42ef-11e5-81f4-cf7c41c7ed48.png)

I'm pretty happy with this

**Comment by scd** [comment]
Awesome.

Simon's UI work on this - boring text `+ 8 others`. Brendans work, turn avatars into progressively overlapping deck of cards. I find it amazing how, a painful edge case can now become a hero feature. Looks great, I hope you had fun with this one.
