### ISSUE TITLE
Number bolts field not editable on mobile device

### ISSUE THREAD

**Issue by scd** [theCrag/website#1996]
Feedback from a user. Need to investigate to confirm. He could edit the number of pitches.

**Comment by brendanheywood** [comment]
start with a screen shot, it may simply be a layout issue

**Comment by scd** [comment]
it worked for me, but not every time. I think this might also be the same issue with FastClick. With FastClick disabled it seemed to be work better. I think this will just go away when we disable FastClick

**Comment by scd** [comment]
I think this disappears with removal of FastClick. Closing
