### ISSUE TITLE
Convert atom feeds to streams

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1997]
This should be a relatively simple thing and in theory should mean we can deprecate and remove a whole chunk of templates and other related code and make it all the same.

Some things to think about / do:
* [ ] atom feeds may not have css or js, so need to make sure that unstyled events look semi decent (mostly just making sure they are wrapped in sane p tags etc, or li tags)
* [ ] no js, so no topos. Same as current. To be replaced at some point with either prerendered svg or prerendered images
* [ ] no js so no drop down edit menus. Make sure they just don't appear at all, nor any other non essential js dependant content
* [ ] one stream event per feed item. Need to be careful with the feed element id's - atom actually supports a feed item being updated so as our events evolve as more data is entered the atom feed should seamlessly keep up to date in downstream clients.

* [ ] a little academic as I haven't yet found a client for it, but we could implement http://activitystrea.ms/specs/atom/1.0/ fairly easily.

* [ ] need to think about feed urls. At the moment we have a bunch of different atom feed url's for updates, vs ascents, etc. Do we keep these and just map them over? That's probably the best scenario. We probably need either a new feed url which is the stream which has 'everything'

* [ ] do we care about personal customised atom streams? I think not for now but a spec is fairly easy, on the profile settings page we generate a random unique id which can be reset if needed, this becomes part of a secret url which they can subscribe to and has just their stuff in it. Like how google calendar makes private calendars work without auth.

**Comment by scd** [comment]
We should be using the same templates, so we may have to rework them a little?

We should keep the topos simple and replicate what we are doing for PDFs - images

**Comment by brendanheywood** [comment]
Yes templates should be exactly the same but I imagine only minor tweaks needed. Topos should just fall back to static images without extra work. We can cross the topo->jpg bridge much later, I also want that for OG images for embeddeding

**Comment by scd** [comment]
see also #2009

**Comment by scd** [comment]
Just to summarise where my head is at:

>    atom feeds may not have css or js, so need to make sure that unstyled events look semi decent (mostly just making sure they are wrapped in sane p tags etc, or li tags)

Turned the tagline div to a p. I think this was the only which needed to be changed.

There are still a log of wrapper div's in the html, but I presume the rss will just ignore them.


>    no js, so no topos. Same as current. To be replaced at some point with either prerendered svg or prerendered images

Keeping this at summary level. You will only see summary indicating that a topo has been edited. Way too many things to do to get topos displayed in the feed itself. Just click on the feed item link to get a full description of the event.


>    no js so no drop down edit menus. Make sure they just don't appear at all, nor any other non essential js dependant content

The menus are dynamic now anyway.


>    one stream event per feed item. Need to be careful with the feed element id's - atom actually supports a feed item being updated so as our events evolve as more data is entered the atom feed should seamlessly keep up to date in downstream clients.

Each event has it's own id and it's own webpage. 


>    a little academic as I haven't yet found a client for it, but we could implement http://activitystrea.ms/specs/atom/1.0/ fairly easily.

Not now. I am not yet even convinced of the need for RSS over our new website streams. The streams offer way more functionality so we should be pushing people there.

Some people are using RSS so we should keep a minimum commitment to it. There may be a case to ramp up the RSS work some time in the future.

The one useful thing I can see about RSS is that information from multiple sites can be combined into your feed. 

>    need to think about feed urls. At the moment we have a bunch of different atom feed url's for updates, vs ascents, etc. Do we keep these and just map them over? That's probably the best scenario. We probably need either a new feed url which is the stream which has 'everything'

I think we have agreed that we are now just mapping these over.

No new url with everything for this release. Once we re-introduce a way to subscribe to feeds back into the website we will need a url feed to everything as this will probably be the only thing you can subscribe to at the area level.


>    do we care about personal customised atom streams? I think not for now but a spec is fairly easy, on the profile settings page we generate a random unique id which can be reset if needed, this becomes part of a secret url which they can subscribe to and has just their stuff in it. Like how google calendar makes private calendars work without auth.

Nup.

Didn't you once warn me against security by obscurity?

**Comment by scd** [comment]
@brendanheywood please close when you have reviewed.

**Comment by brendanheywood** [comment]
Did we end up with a new feed which has everything?

old:
http://dev.thecrag.com/feed/activity/climber/7727431
http://dev.thecrag.com/feed/ascents/climber/7727431

new?
http://dev.thecrag.com/feed/all/climber/7727431

I'm happy if not just curious if this was implemented

**Comment by scd** [comment]
Not implemented, but it should be simple as all the work is now done in the feed query. I just kept my scope down because nobody is currently registered to an all feed and there is no way of currently registering. When you do a feed link somewhere in the system I will add the extra pattern match line to trigger 'all'.

**Comment by scd** [comment]
Closing. If you want the 'all' feed please create a new issue.
