### ISSUE TITLE
Can't edit photo I submitted

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#1998]
Can't edit settings of a photo I submitted: http://www.thecrag.com/photo/713432319

Could you please give me the rights?

**Comment by scd** [comment]
That is weird, you should be able to edit your own photos. What settings are you trying to change? Can you edit any other photos?

**Comment by lordyavin** [comment]
I wanted to update the attributes Photographer, climber, date etc. Problem is that I don't get the the edit buttons on the Review page.

I can edit photos where I'm set as photographer.

**Comment by scd** [comment]
Can you see the 'edit' button on the photo page?

![tc-edit-photo](https://cloud.githubusercontent.com/assets/373058/9263313/5eb178a8-425f-11e5-9643-e39499ea17a0.png)

**Comment by lordyavin** [comment]
Yes I see the edit button on the photo page.

---- Simon Dale schrieb ----

**Comment by scd** [comment]
Please send a screen shot where the system has problems. I think I have been looking into the wrong thing.

**Comment by lordyavin** [comment]
![phtot_review_missing_buttons](https://cloud.githubusercontent.com/assets/1528540/9269891/cb019836-426d-11e5-9d43-b75d08f28b0c.png)

https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3APushReturnURL=%2F713432319&C%3AState=16159&D%3APhotoID=713432319&C%3AHideNavigation=1

**Comment by scd** [comment]
Ta, I will take a deeper look. Hopefully I will get a chance this weekend. I am guessing there is a bad state on the photo record.

Are all your photos like this or just the one?

**Comment by lordyavin** [comment]
Nö, just this one.

---- Simon Dale schrieb ----

**Comment by scd** [comment]
It is what I thought it was. The upload status of the photo record did not get to it's proper state

mysql -e "Select P.ID,P.UploadStatus,C.Label FROM Photo AS P,Category AS C WHERE P.ID=713432319 AND C.ID=P.UploadStatus\G" cids
*************************** 1. row ***************************
          ID: 713432319
UploadStatus: 7273900
       Label: Initialised

This status should be 'Complete' for an upload that worked properly. Do you remember anything special about this upload?

**Comment by scd** [comment]
Upon closer inspection your image has this status information on it anyway, so I should have picked this up from the get go. I could just fix this with a sql statement, however I am using the opportunity to put in a simple fix that does not involved me if happens again. I have changed the form to allow updates buttons for photos in this incomplete state. If somebody makes an update the status will be changed to a 'complete' state.

I have not been able to test this properly yet. It should work if there were no errors in my code.

@lordyavin could please see if the buttons are now there and then please make an update and see if the Upload Status changes to Complete. Please close the issue if all works.

**Comment by lordyavin** [comment]
Buttons were available but when I saved the update I got this error message :

Cannot continue process: Internal Error: CategoryFunction not set

State: 15712

Error Code: 3

CodeReference: CIDS::Process::SupplyInformation::ReviewPhoto, /opt/CIDS/perllib/CIDS/Process/SupplyInformation/ReviewPhoto.pm, 1409

**Comment by scd** [comment]
try again now.

**Comment by lordyavin** [comment]
Its working.
