### ISSUE TITLE
stream - add some more activity log events

### ISSUE THREAD

**Issue by scd** [theCrag/website#2000]
- [ ] linking and unlinking routes to topos. Actually I am not to concerned with this unless that by unlinking you are removing a drawn line.
- [ ] move topo. I don't know if we need this, but documenting for completeness
- [ ] delete topo
- [ ] update and remove photo. 
- [ ] unlink and link photo
- [ ] update and remove ascent
- [ ] remove shortcut

I am not sure if we have to prioritise any of these for the first proper streams release. Thoughts?

**Comment by brendanheywood** [comment]
None seem critical, looks to me in rough priority order

**Comment by brendanheywood** [comment]
+1 for topo removal, or really for anything that should be considered an 'edit'. When you look at the stream you should be able to clearly see who did what recently and in many ways a delete is a much more important change than a minor edit

**Comment by brendanheywood** [comment]
Actually there is a little bit more to this, eg this event:

https://www.thecrag.com/event/2159740680

![image](https://user-images.githubusercontent.com/187449/50216423-d2be8a80-03d9-11e9-8c2a-ce484a9311c2.png)

This shows 4 topos, but one is flagged as 'Topo is now disabled.'. This is wrong, the stream event should be a snapshot of what that person did at that point in time. Ben did not disable this topo, he made it. It should just show the topo, as he added or edited it, at that point in time like the other topo stream edits. Then there should, as commented above, be a second new stream event by whoever the other person is who deleted the topo.

**Comment by scd** [comment]
I am closing this in favour of raising a separate issue for each missing stream event.  Other issues raised about what is displayed is separate and really requires a major rework. Closing.
