### ISSUE TITLE
Stream comments for ascents should include the climber?

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2001]
![image](https://cloud.githubusercontent.com/assets/187449/9277923/91683570-42f0-11e5-9339-b50f61907e02.png)

I see an ascent comment as the start of a conversation and those 3 are continuing it - so maybe we should stick 'Ro-boat' in as the first primary mention, or maybe fake it in the templates. Their name should not be in the text list as they are already at the end

**Comment by brendanheywood** [comment]
I guess whether we fake it or do it as mentions data would depend on who we want to see it. I think mention data would be better?

**Comment by scd** [comment]
There are a couple of things we need to do here in line with what you suggested. 
 - [ ] add the climber as the first involved
 - [ ] fake it in the streams so that they are part of the discussion. I think the paradigm here is that the ascent is the first comment.

Which brings up the question of people explicitly following a discussion. I don't think they should in the mentions.

**Comment by brendanheywood** [comment]
I think somewhere along the way a few concept may have been conflated, there is probably 4: 'primary' who ticked, 'mentioned' in this case who with, 'involved' who has commented and 'watching' could be a commenter has left.

Ie in the example above Ro boat is involved but is the primary so would not be show in the first list. A person who has started watching the discussion but hasn't comment would not be included anywhere. Some who has commented but then left would still be included exactly the same way, they just won't get notified.

**Comment by scd** [comment]
There is also 'invited', which I think is the 'watching' case you referred to. But we may have a genuine separate watching case.

 - [x] the example above Ro boat is involved but is the primary so would not be show in the first list. YES
 - [x] A person who has started watching the discussion but hasn't comment would not be included anywhere. - A person watching will not be in the Ro boat and the event would not be in their personal stream
 - [ ] Some who has commented but then left would still be included exactly the same way, they just won't get notified. HMMM, this is not right unless you are talking about the difference between discussion notifications and streams. I might be a bit confused by your meaning here.

Are you considering following individual events, or excluding yourself for an individual event. If somebody is mentioned in a history updated or a discussion then the logic should be the same. If we want somebody to be unlinked from and event then that is fine, but it should apply for update events as well as discussion events.

FYI, at the moment you cannot unfollow a discussion, which I know is on our todo list. For the next release I want to make sure there is no architectural stream implications on this aspect.

**Comment by brendanheywood** [comment]
Yeah I think I'm confused with discussion notifications, lets pick that up later when we sort the discussion unfollow stuff

**Comment by scd** [comment]
It turns out that making sure the privacy account gets added as the first involved account fixes this.

It will remain broken in historical stuff until I retest migration.
