### ISSUE TITLE
Route color swatch not overriding grade colors for streams

### ISSUE THREAD

**Issue by scd** [theCrag/website#2002]

**Comment by brendanheywood** [comment]
picking this up

**Comment by brendanheywood** [comment]
There was quite a lot of inconsistency across the whole site with diverged grade rending code, so cleaned that all up:

* fixed steams
* fixed ascent facet
* reworked gym swatch
* refactored all use of grades and swatches into a single template and remove swatch template
* refactored styles out of ascents.css and portal into grades.less
