### ISSUE TITLE
Stream event agregation node

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2004]
We are currently aggregating events at the TLC level, I'm wondering if we can change this to the bottom level crag instead? ie when looking at a route or cliff in a crag like below I was quite surprised to see the event for the other area which I thought was completely unrelated and a bit spammy:

http://dev.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/area/12094897/stream

**Comment by scd** [comment]
It is very important that we are happy about which ever way we do it before we release. It will be problematic if we change this on the fly after the release.

My thoughts are that changing to bottom level crag will introduce it's own problems. This spammy problem would still exist but to a lessor extent.

I think we should work harder at a UI which is ok for the case here. One thing we could do is filter out all the activities in the event not related to this node or it's descendant.

**Comment by brendanheywood** [comment]
Ok I agree that the aggregation should still be at the TLC level in terms of grouping related edits together. 

The other day we talked about whether routes and cliff level streams should include other stuff, and we decided that yes they should as it's much easier technically. If we do filter down to the route of cliff level then we are potentially losing most of the stream data which is sub optimal and seeing related edits in the surrounding cliffs I think is a feature. It's just where do you draw the line in crags that are so big they have crags inside crags like Araps or Gara. I would be happy to park this one and decide later but if it's problematic to change then lets hash it out. At the end of the day the streams are rocking and this is a small edge case so I'm not too stressed about it. If we can filter in it back to some nodes then I thing going back to the nearest common BLC is a good compromise and will get a good balance of showing related nearby edits without throwing out so much we empty the stream page and have to keep going back for more.

**Comment by scd** [comment]
+1 for filtering back to the bottom level crag

On Sun, Aug 16, 2015 at 8:18 PM, Brendan Heywood <notifications@github.com>
wrote:

> Ok I agree that the aggregation should still be at the TLC level in terms
> of grouping related edits together.
>
> The other day we talked about whether routes and cliff level streams
> should include other stuff, and we decided that yes they should as it's
> much easier technically. If we do filter down to the route of cliff level
> then we are potentially losing most of the stream data which is sub optimal
> and seeing related edits in the surrounding cliffs I think is a feature.
> It's just where do you draw the line in crags that are so big they have
> crags inside crags like Araps or Gara. I would be happy to park this one
> and decide later but if it's problematic to change then lets hash it out.
> At the end of the day the streams are rocking and this is a small edge case
> so I'm not too stressed about it. If we can filter in it back to some nodes
> then I thing going back to the nearest common BLC is a good compromise and
> will get a good balance of showing related nearby edits without throwing
> out so much we empty the stream page and have to keep going back for more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theCrag/website/issues/2004#issuecomment-131520645>.
>



-- 
http://thecrag.com/

**Comment by scd** [comment]
This is actually quite interesting and I think the bottom level crag solution is excellent. I have implemented this in repo.

Bottom level crag is triggered by a area type = 'Crag' between the top level crag and the node in question, including the node in question.

The filtering is done as SQL level so it only includes activity in an event that is also associated with the bottom level crag.

This means that the content associated with of an event id in a stream may be different between streams. Is that an issue? In particular I was thinking about RSS feeds.

@brendanheywood if you are happy with this then please close.

**Comment by brendanheywood** [comment]
Yeah looks pretty good. Rss should not be an issue as atom entry id's only make sense in the context of a feed so don't matter
