### ISSUE TITLE
Investigate tuning diff into a word boundary diff for streams

### ISSUE THREAD

**Issue by scd** [theCrag/website#2005]
I am separating this into it's own issue.  See also #662 #1918 #1995

**Comment by brendanheywood** [comment]
I think the ideal solutions would be a bit more sensitive to the context. So if the only diff was one letter in a word then I reckon wrap just the changed letter, but if it was one word add and remove then wrap them, but if it hit some threshold like 90% of a paragraph them wrap the whole block, not at the word level. This is how my git diff is setup, it does word level highlighting and then swaps to block level if too much has changed in any one line.

Also need to do some testing with markdown lists, links, bold etc so see if the del / ins mess it up.

**Comment by scd** [comment]
In turns out the perl module I chose was not so crash hot on the quality of the result for what we wanted. Luckily it used another third party module that does all the grunt work and is shit hot:

http://search.cpan.org/~tyemq/Algorithm-Diff-1.1903/lib/Algorithm/Diff.pm

This module provides the tools where we can implement our own diff algorithm specific to theCrag. So the pre-markup algorithm I implemented goes roughly as follows:
 - [x] Check for line differences first
 - [x] If one line should be changed with another then check for whole word differences withing the line
 - [x] If more that 30% of the words are different then stay at line level
 - [x] If one word should be changed then check at character level
 - [x] If there is only one character changed then continue to process at character level for that word, otherwise stay at word level
 - [x] If there are subsequent words with the same change (eg 5 words changed in a row) then combine these changes. (Note this does not work if there is more than one character between the words).

It is likely that there are a lot of edge cases, but it does the following.
 * If you change just one character in a description then just that character will be diffed.
 * If you make a substantive change to a word then the whole word will be diffed
 * If you make changes to multiple words in a row then those words will be grouped as a diff
 * If you make substantive changes to a line then the whole line will be diffed.

I am now convinced we need to stay in the pre markup stage for diffing. Eventually we can get smart enough to diff quotted words and `@usernames` so the markdown works properly. Proper HTML diffing is way more difficult in my opinion and html is hardly used in pre markup so I don't recon we need to worry about it. We have something that I am happy with for this release.

@brendanheywood please close if you are happy with this too. Also close any related issues that you think go away.

**Comment by scd** [comment]
in repo

**Comment by brendanheywood** [comment]
This is way way better - nice stuff :)
