### ISSUE TITLE
Forum subsets in streams

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2006]
http://dev.thecrag.com/climbing/australia/north-shore/area/12011275/stream

![image](https://cloud.githubusercontent.com/assets/187449/9292903/9f3842d4-4454-11e5-8895-17640e990f3b.png)

A few thoughts:
* [ ] I think this needs to be in forward crono order not reverse
* [ ] forums are the funny event where they move and it's a blurred bit of current state vs changed. I'm wondering wether it would be better to show take the event date into consideration to better tune the hidden 'earlier comments' and 'later comments', something like:

  * If there are less than X comments total then show them all
  * If there are more than X then filter but give preference to comments added today, perhaps showing just the last comment before today for more context.
  * only if there are still more than a page or so of comments then hide the later comments

* [ ]  a general thought: once we have the stream discussion template sorted, perhaps if we just add an internal flag 'never hide' and then we should be able use the same template for the discussion page and merge those two templates

Also a coding thing:

![image](https://cloud.githubusercontent.com/assets/187449/9292906/f22bd8b6-4454-11e5-9cd4-18f9bcd033b1.png)

Try to avoid an <a> link with no href, in almost all cases if you are creating links with js there is some sensible href fall-back url that should also work, in particular in cases like this if you should be able to right click and open it in a new tab

**Comment by scd** [comment]
I get the general thought about duplication of interfaces between a discuss event and a discussion page. I will not merge the two for this release. When we do this work we will have to consider that not all discussions have events. A private discussion between two people (or a group of people) does not create an event.

**Comment by scd** [comment]
@brendanheywood, the way I am tackling this is pretty similar to what you suggested. 

Yes crono order as per our normal forum.

This implementation of streams means that there is only one discussion event, event though a discussion may be over a number of days. This discussion event is associated date of the latest comment. Note that when somebody comments on an ascent there are two events, 1) the tick event and 2) the discussion event. All future comments get added to the discussion event. This is discussed more fully in #2022, but mentioned here to avoid confusion.

In our prototype we had a discussion event for every date that a comment was made. This was an artifact of the way we did the dynamic grouping and leads to dups in a stream.

Now that we have the event table there is just one event for each discussion. This means that a discussion will not appear on days other than the day associated with the latest comment. Which in turn means we no longer need to hide future comments. This greatly simplifies the UI.

I think we just don't worry about which day a comment came in and treat everything equally and go with something like if there are more than X routes we show the latest X and hide the rest. Actually I don't want to just hide one comment so I have a lower and upper bound for X.

The implementation as it now stands the server returns the html for all comments with the excess in a hidden div. This uses bandwidth. Ideally we want the more comments button to get the comments from the server, but I think I am ok with not bothering for now.

@brendanheywood please close if you are ok with what I have implemented. In repo.

**Comment by brendanheywood** [comment]
yeah lets go with it and see it in the wild
