### ISSUE TITLE
Server side limit on number of activity items processed for streams

### ISSUE THREAD

**Issue by scd** [theCrag/website#2011]
It is totally possible that somebody fully document a 1000 route crag in a day, especially if they use the bulk upload. This could generate thousands of activity items associated with the event. The server gets information for each of these activity logs and associated entities. This will slow down response time for that particular event, with the end result being the template just showing the summary.

I have put a limit on the number of activity logs that will be fully processed by the server for a stream. I am thinking of making this 100. If this limit is triggered for an event then no inflate information will be sent for the associated nodes associated with the activity log for that event. Instead a 'summary' displayMode will be set in the event which will force the template to display in summary mode.

All good so far, and works well for update events. Couple of use cases which we need to cater for:
 - [ ] Display an event in full detail on it's own page. In otherwords there is a mode which turns off summary mode detection.
 - [ ] I don't think we ever want forced summary mode for discuss events, or if we do then we still want to return some comments for the template.
 - [ ] Make sure forced summary mode is coded for each of the event types.

**Comment by brendanheywood** [comment]
Re discussions this overlaps a lot with comments I made somewhere around showing a more useful subset of comments. #2006

**Comment by scd** [comment]
This server limit will not apply for discuss events. the rest can be dealt with in #2006
