### ISSUE TITLE
progressive embeds

### ISSUE THREAD

**Issue by scd** [theCrag/website#2012]
There are scenarios where we may want to embed similar content incrementally where the first embed requires a bit more set up. Sometimes we want to embed in an iframe and other times we want to append some html segment.

This leads to defining embed levels (eg someurl?embed=1 or someurl?embed=2).

It may not be possible to standardise these embed level definitions, but I think we should try and give it a go.

Level 1: Is a full html page with with required css and javascript. It includes a thin html footer. Designed for iframe embedding on external sites.

Level 2: Same as level three but with javascript and css so the page can be viewed as an independed page in the browser. Useful for debugging - maybe something else as well.

Level 3: Just an HTML chunk. If it requires javascript or css then it will not function as an independent page. This is useful for appending an html chunk directly into a document.

**Comment by brendanheywood** [comment]
Ok how about we stop using numbers and swap to something more explicit as the list of embeds may not necessarily be a linear set of bigger to smaller results sets.

so how about: (and making up some potential future ones here)

/whatever - normal full page
/whatever?embed=html - slim but full html with css js for embed
/whatever?embed=chunk - same as above but just the div for ajax
/whatever?embed=card - basic summary of same info, just a html chunk
/whatever?embed=cardimg - basic summary of same info but baked into an img for really simple badges on eternal sites or use in non browser env's like feed readers. Would use this for topo OG images when embedding in facebook for example.

**Comment by scd** [comment]
+1

**Comment by scd** [comment]
I have now converted all existing embeds to this new format.

We are currently only using 

/whatever?embed=html
/whatever?embed=chunk

Because external resources are using the old method, the following are equivalent
/whatever?embed=html
/whatever?embed=1

Also 
/whatever?embed=off
/whatever?embed=none
/whatever?embed=0

Finally I have made a embed function helper so you can do things like this in the mason template:

% if ( embed('chunk') ) {  # if embeding a chunk
% unless ( embed() ) { # unless embeding anything
% if ( embed('chunk','html') { # if embedding chunk or html

Please close the issue if you think this is reasonably clear now
