### ISSUE TITLE
stream empty window behaviour

### ISSUE THREAD

**Issue by scd** [theCrag/website#2013]
When you get 'Load more' events in a stream the system will first try and load subsequent events from the current stream and if there are none load the previous stream time window (ie previous month). If there are no events in the previous window then the system does not try further back.

Ideally it would just keep going back until it found events, however this could cause some denial of service problems having a loop back forever code. And since we have difficulties detecting the end of a stream (see #2003) I am reluctant to go back further than one time period at a time.

This means that somebody can press the 'Load more' button and get nothing. I think it is better to have some indication that there is not a problem and they can press the 'Load more' button again. Functionally I am currently appending the following text above the button.

No events between 2015-06-01 and 2015-06-30 - click Load more to go back further

It would be nice to get a work around this but I currently see it a s fundamental limitation of our implementation and may take significant work to deal with properly for the same reasons as mentioned in #2003.

Also, while we are in dev mode I am appending the urls that we are fetching below the button. This makes it more explicit what we are doing and helped me catch a bug.

**Comment by brendanheywood** [comment]
got a solution to this, writing up now in #2003

**Comment by scd** [comment]
this is fixed with #2003, closing
