### ISSUE TITLE
stream pagination error

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2015]
https://dev.thecrag.com/climbing/australia/mt-coolum/stream?paginateAt=353470816&pageinateTime=1438616506&embed=chunk

Apache Module Load Portal Error: error - pagination failed

**Comment by scd** [comment]
fixed this and found another issue that I fixed

the way I assessed end of stream window with pagination was flawed given recent changes to the sql query which used optimisaiton limits. I now test by changing the pagination boundary to include the pagination event and check to see if it is the last.

Also embed=chunk was missing when getting the next stream time window
