### ISSUE TITLE
stream discussions have weird duplicate comments when opened up

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2017]
https://dev.thecrag.com/climber/brendanheywood/stream

If I look at my stream, there are a large number of discussions like this:

![image](https://cloud.githubusercontent.com/assets/187449/9390907/705947ae-47b7-11e5-94e1-315ef916bc08.png)

if I expand the comments I get duplicates:

![image](https://cloud.githubusercontent.com/assets/187449/9390922/8649e99c-47b7-11e5-9953-6f445e5ef477.png)

It happens with almost every discussion in my stream

**Comment by brendanheywood** [comment]
saved too quick, updated the issue above

**Comment by scd** [comment]
this was fixed with #2006 and was an artifact of changed assumptions from our prototype implementation to this implementation.
