### ISSUE TITLE
stream tick events should distinguish historical ticks versus current

### ISSUE THREAD

**Issue by scd** [theCrag/website#2018]
When a tick ascent date is more that 10 days older then the log date we should treat this as an historical event updating the persons logbook.

Rather then "went climbing" use "logged ascents".

Also in summary use "Logged 4 historical ascents" for example.

If it is a mixture then it should be treated as if they 'went climbing' but flag the historical events in the summary as 'logged an historical event'

**Comment by brendanheywood** [comment]
Ths is good for future past events, but for current retro generated events this will look like the event was logged back then?

**Comment by scd** [comment]
No I think it looks right because the log date clearly show. We will have to find some in the wild. I really don't want a current event to say 'Simon went climbing in Arapiles * 10 minutes ago' when I was logging historical events. I don't have time now but I will can an example

**Comment by brendanheywood** [comment]
Sorry I was talking about the retro dates generated just on the first run when we release this, but I think you've already sorted this in #2016 'Old dates in stream are wrong?'

**Comment by scd** [comment]
Ah, I see what you are getting at. I actually set a flag in the ascent template data if it was climbed more than 10 days earlier than logged. In this was we the template jut has to detect the existance of the flag in the ascent.

**Comment by scd** [comment]
closing
