### ISSUE TITLE
Internal links to routes with umlaut not working

### ISSUE THREAD

**Issue by scd** [theCrag/website#2019]
Right now it is not possible to create an internal link to a route which has a 'Umlaut' in its name like äöü, which

**Comment by scd** [comment]
Example here:

https://www.thecrag.com/climbing/switzerland/alpen/sarganserland/route/517765083

**Comment by brendanheywood** [comment]
Simplest would be to do the comparison by flattening to the 'simple' version of a name first, pretty sure we had some library that did this. So  'Früchte des Zorns' or  'Fruchte des Zorns' would both match and link. However we should be careful to also do a direct match as I can imagine a situation where there are two routes with similar names which both get simplified to the same, so need to match exact first as higher priority and then a more general match.

**Comment by scd** [comment]
I am surprised that umlauts break this in the first place.  I think it is a different issue matching non-umlauts with umlauts.

**Comment by scd** [comment]
I think this should be working now, but must check after next release. There were several problems in the chain. 

In the search for the problem I came across this, which would have caused problems with general unicode characters:

http://www.regular-expressions.info/unicode.html

Also our process utilises our internal search which has a dictionary for each node. It is very fast for matching routes under a node. Maybe this could be reworked so that it worked directly off MySQL live queries.

**Comment by scd** [comment]
works
