### ISSUE TITLE
Apache very very slow at serving images

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2021]
For some reason the images are super slow, there is some bottle neck somewhere:

![image](https://cloud.githubusercontent.com/assets/187449/9430795/8e30bf70-4a44-11e5-977f-c0e443b05ed2.png)
 
5 seconds for a 170k file is crazy slow, and the root cause of why topos are so slow to zoom in the high res version. Need to check wether this is bogging down in apache land, wether it is using sendfile at the OS level, or wether this is just some network bottleneck or what

**Comment by scd** [comment]
prod or dev?

**Comment by brendanheywood** [comment]
prod

**Comment by scd** [comment]
What about the benchmark when you just do the image.

**Comment by brendanheywood** [comment]
Same:

http://www.thecrag.com/image/topo/00003/fixedheightoversize/721264233.jpg

![image](https://cloud.githubusercontent.com/assets/187449/9431027/03118bd8-4a4c-11e5-875f-5522dd10dbd8.png)

Happens with every pic I've tried

**Comment by brendanheywood** [comment]
```
brendan@silverbirch 10:45:20 ~ $ wget http://www.thecrag.com/image/topo/00003/fixedheightoversize/721264233.jpg
--2015-08-24 10:45:24--  http://www.thecrag.com/image/topo/00003/fixedheightoversize/721264233.jpg
Resolving www.thecrag.com (www.thecrag.com)... 148.251.235.176
Connecting to www.thecrag.com (www.thecrag.com)|148.251.235.176|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 189478 (185K) [image/jpeg]
Saving to: '721264233.jpg'

100%[============================================================================================================================>] 189,478     64.2K/s   in 2.9s    

2015-08-24 10:45:28 (64.2 KB/s) - '721264233.jpg' saved [189478/189478]
```

**Comment by scd** [comment]
I don't think it is apache. How's this for doing the same thing from static server

```
root@theCrag-Dedicated-Static ~ # wget http://www.thecrag.com/image/topo/00003/fixedheightoversize/721264233.jpg
--2015-08-24 03:21:19--  http://www.thecrag.com/image/topo/00003/fixedheightoversize/721264233.jpg
Resolving www.thecrag.com (www.thecrag.com)... 148.251.235.176
Connecting to www.thecrag.com (www.thecrag.com)|148.251.235.176|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 189478 (185K) [image/jpeg]
Saving to: `721264233.jpg'

100%[============================================================================================================>] 189,478     --.-K/s   in 0.005s  

2015-08-24 03:21:19 (33.8 MB/s) - `721264233.jpg' saved [189478/189478]

root@theCrag-Dedicated-Static ~ # 
```

**Comment by scd** [comment]
My guess is there is a network bottleneck somewhere. Some thoughts:
 - Hetzner throttling us due to our account usage - there is no indication that this is happening, we use about 3 GB traffic a day, and we have up to 50TB per month before we are throttled.
 - Hetzner has a small connection to Australia
 - There are some local issues

Do you have access to a server in the US somewhere so we could do the test from there?

@nicHoch could you do a wget benchmark test for us from your server?

wget http://www.thecrag.com/image/topo/00003/fixedheightoversize/721264233.jpg

**Comment by brendanheywood** [comment]
Yup just did it:

http://www.webpagetest.org/result/150824_ZG_3FH/

**Comment by brendanheywood** [comment]
and it was also slow

**Comment by brendanheywood** [comment]
You can choose a whole bunch of servers and locations with webpagetest too btw

**Comment by scd** [comment]
I did it from Germany and it was 5x quicker.

http://www.webpagetest.org/result/150824_VB_6C2/

**Comment by scd** [comment]
This is implying that it is a bottleneck limit coming out of Hetzner, which probably means we have to live with this for a while.

**Comment by scd** [comment]
I think we will have to find a different host provider for photos other than Hetzner. This brings the whole static/CDN discussion back to life. There is lot's of testing and research to do before we go down this path.

**Comment by brendanheywood** [comment]
But this is affecting www not static, the would apply to everything not just images??

**Comment by scd** [comment]
It will be the same problem on static.

Ideally we will find an affordable host provider that has a big pipe to the whole Internet for both static and prod.

My gut feeling is that if we improve the speed of static resources and images then this will make a huge difference. Hopefully we can get our dynamic html down to a smaller size for most of the functions.

This is not an overnight fix.

**Comment by scd** [comment]
see also #2029

**Comment by scd** [comment]
@brendanheywood can you see if the image release has improved image serving. We might have to move our images to a server from another host provider

**Comment by brendanheywood** [comment]
The raw download speed is still pretty bad, but the new images caching headers make a massive difference now for most pages for repeat visits.

**Comment by scd** [comment]
I think the raw download speed has a significant bottleneck from our host to australia. I am betting that this speed is better in other parts of the world.

We may have to find a better host

**Comment by scd** [comment]
@brendanheywood can we close this or rename it if we are still unhappy with the speed.

**Comment by brendanheywood** [comment]
It's way way better now
