### ISSUE TITLE
how to display tick event and discussion event in same stream

### ISSUE THREAD

**Issue by scd** [theCrag/website#2022]
If you comment on somebodies ascent this will create a separate discuss event. Future comments will be added to the discuss events. When it comes to displaying these two events, the template for the tick event will know about the discussions and the template for the discuss event will know about the ascent.

Potentially these two events will look fairly similar and look like dups. 

We need to think about this because I plan to also allow comments against photos and events, so this will become noticeable issue.

If the discuss event and the tick event end up on separate days then they should be shown as two separate events.

If they are on the same day what should we do. I think we just show the discuss event because that will filter to the top.

Also should we make the discuss event and the tick event look the same?

**Comment by brendanheywood** [comment]
We may possibly want to treat a discussion of a tick, and a discussion of a photo the same way,  but a discussion in a crag differently. Comments on a tick, and the tick event with comments should be indistinguishable.

**Comment by scd** [comment]
yup there are two types of discussions with different behaviors:

1. crag/area/route forum discussion
2. comments on ascents/photos/events

I tend to agree that a discuss event for an ascent should look the same as a tick event with comments. I am currently thinking that I should call the tick event template rather than discuss event template and make sure that I get the right info. This would guarantee that the events are handled identically.

**Comment by scd** [comment]
BTW, the forum discussion events are aggregated by the discussion ID and the ascent comments are aggregated by the eventID of the ascent. So even the data structure is slightly different for the two event types.

I think this means if I get the source event for ascent comments then I can just process them as the tick event. Maybe we can event do it within the SQL query itself by replacing the event id of the discuss event with the source event id. If this works then this is awesome as it means very little code to deal with this use case. @brendanheywood if you understand my rambling here and think it is worthwhile persuing then please let me know.

**Comment by brendanheywood** [comment]
err yeah sure :)  Dunno it sounds like internals I'm really on top off so let you make a call.

**Comment by scd** [comment]
This works awesome but there are a few subtleties. Just so you know what is happening behind the scenes I have made the following changes to the SQL:
 - [x] I have added EffectiveID and EffectiveType if an event is a discussion of another event. These refer to the ID and type of the event being discussed. 
 - [x] The query gets the people involved in both the discuss event and the event that is being discussed
 - [x] The query gets the activity of the effective event, which means the source event can be duplicated.

In the templates:
 - [x] The icon remains a discuss icon, but the event text is almost identical to the source event.
 - [x] The avatars involved include both the discuss event and source event accounts
 - [x] The time has the qualifier 'discuss' so that it is clear that the time refers to the latest discussion not the time of the event
 - [x] The dropdown links to the full details of both the discuss event and the source event.
 - [x] If the discuss event has already appeared in window of events being returned then the source event is marked as discussed and not shown in stream. Note that this only applies to the current url page call, and if the discuss event and the source event appear in subsequent url pages then both will appear.

I am going to close this, but feel free to reopen or discuss further.
