### ISSUE TITLE
allow comments directly to stream event

### ISSUE THREAD

**Issue by scd** [theCrag/website#2024]
There is a bit of sorting out to do here.

 - [ ] comment on an event
 - [ ] do we still want people to comment on a specific ascent. shame to lose this, so I think yes. Do we want to allow this to happen in the streams. In otherwords if you noticed one particular hero ascent and wanted to comment on it then would we allow this in the streams. What would the UX look like?
 - [ ] ditto for commenting on photos. In fact I think it is pretty important to be able to comment on an individual photo.

**Comment by brendanheywood** [comment]
In FB land you can comment on an individual photo, or like a photo, but if they are uploaded as a batch you can also comment or like the whole batch. So while both modes would be allowed I think we encourage and show the batch one as primary. The devil is in the detail for how we show it in the stream where both are used, probably collapse the route or photo level ones into a summary vaguely like fb does: 

![image](https://cloud.githubusercontent.com/assets/187449/9509373/214611e8-4ca2-11e5-9aff-3bc844958196.png)

**Comment by scd** [comment]
The devil sure is in the details with this one. I have made some headway so we can have a little bit of a play.

 - [ ] In the backend we can message an event, ascent or photo.
 - [ ] You can message an ascent directly using the ascent page (this is as it was before)
 - [ ] You can also message an photo directly using the photo page
 - [ ] You can message an stream event via the stream.
 - [ ] Currently no way to message a specific ascent or photo via the streams. A lot of devil here.
 - [ ] A message to a photo/ascent will initially be delivered to the dashboard of the submittor
 - [ ] A message to an event will initially be delivered to the dashboard of everybody involved.
 - [ ] There is duplication between an ascent discussion page and the ascent page itself. Consider going straight to the ascent page
 - [ ] There is duplication between a photo discussion page and the photo page itself. Consider going straight to the photo page.
 - [ ] There is duplication between a event discussion page and the event page itself. Consider going straight to the event page.
 - [ ] Check what happens in the stream when you message an ascent/photo directly. At the moment I am assuming it will be like messaging an event and the stream item will pop up. However there may be some complexities here. I have to think about  this more.

@brendanheywood do you want to pull from repo and have a play. Certainly there is probably a lot we could do with making the UX neater here. I have really been concentrating on the functionality rather than neatness.

**Comment by brendanheywood** [comment]
Cool, I'm in brissy and probably can't do much til tues or wed night

**Comment by scd** [comment]
No worries, when you are ready. I might be close for you to do some release testing by then. The one issue I really do not have any idea about is replacing our rss feeds.

Also I have had a bit more of think about what it means to comment on an ascent. Let's say you comment on an ascent that was logged 4 years ago. This will majically work out what stream the ascent was associated with and bump it to the front. Great no problem except for:
  - [ ] some old ascents may not have a stream (ie before activity log was recording). 
  - [ ] what happens if there was an accent log error all those years ago and the stream ascent was never associated with a stream event
  - [ ] what happens if somebody updated the ascent 2 years ago and there are now two stream events.

My answer is simple and means that in some edge cases the stream event will not be created when you comment on an ascent. Firstly if there is no stream event associated with the ascent then do not create a discuss stream event (nothing is really lost because it still goes into the dashboard inbox). Secondly if there are multiple events then pick the oldest which is most likely to be the original create event (if it is an update event then so be it).

This means that a stream event could actually have multiple discussions. I don't think it really matters because it will be hidden in the display and they will mostly be comments consumed immediately as per facebook.

**Comment by scd** [comment]
@brendanheywood please close when you have reviewed.

**Comment by brendanheywood** [comment]
added auto focusing the textarea when you click comment, looks good
