### ISSUE TITLE
Batch edit multiple ascents, eg from facet pages

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#2030]
While logging multiple ascents at once, it is impossible to edit a batch of ascents once the save button is pressed. If, for example, you forget to set the date for all the ascents at the top, you need to edit every single ascent by hand to correct it.

It would be nice to have a way to edit multiple ascents. I like the way it is done for editing routes, where the overlay that appears to the right of the table containing the routes then just says "edit X routes".

**Comment by brendanheywood** [comment]
Yeah +1, I'd use this a lot. We have talked about this but hasn't gone anywhere yet

**Comment by lordyavin** [comment]
+1 from me

**Comment by Mdemaillard** [comment]
Closing to clean-up, all relevant info are on duplicate
