### ISSUE TITLE
Add Font traverse grade

### ISSUE THREAD

**Issue by scd** [theCrag/website#2038]
See issue #1913 

For conversions see

http://www.rockclimber.de/index.php?view=article&id=54:bouldering

Do we call the grade "7a+" or "7a+ trav"? 

OPTION 1: If we call it '7a+ trav' then there should be no parsing issues. However I don't think this is how it is being used.

OPTION 2: If we call it '7a+' then this looks exactly like the Font grade '7a+' in the same context and same route style type. The system has got a solution for this which to force the grade system when entering the grade (see #2036). For example 'FBTRAV:7a+' or maybe 'FBT:7a+'. There maybe some things we can do at the display level to make it look nicer. 

We need to make a business decision on this before I implement anything. I am strongly leaning toward OPTION 2, but would like the full discussion before committing.

**Comment by brendanheywood** [comment]
I think the core principal is that it needs to be entered the way it is used locally, the FBTRAV:7a+ isn't what people will naturally use so I don't think will get much take up because nobody would even know it's possible. I think we need more local input first

**Comment by scd** [comment]
The grade conversion should match French sport climbing.

As per Brendan's discussion point before we implement we also need to discuss adding a new route gear style - traverse. If we do this then we can simply use '7a+' and the system will work it all out because it is a traverse. This seems like the most user friendly approach.

**Comment by scd** [comment]
Conversion table:

http://www.dpmclimbing.com/articles/view/bouldering-there-and-back

**Comment by scd** [comment]
I think the only way to do this nicely is introducing a traverse gear style. @brendanheywood are you happy if we commit to this?

**Comment by brendanheywood** [comment]
Yeah I got the vibe from before that was probably going to be the best way too. Is it possibly we can only show this gear style in certain nodes that use that context so we don't pollute the world?

**Comment by scd** [comment]
You mean only show it for FR context for example? 

Or would you rather an admin flag for the area which 'allows traverse' for descendant routes?

**Comment by brendanheywood** [comment]
Only for FR context seems cleaner

**Comment by scd** [comment]
The thought I had is that if traversing is not in Australia then we will not see any problems it causes.

**Comment by brendanheywood** [comment]
I'm not sure I follow? Aus doesn't use the FR context so they gear style would not be available there?

**Comment by scd** [comment]
Exactly. If we are hiding this gear style in Australia then we will not see it in use locally.

If it is a hack that we are purely using for Font traverses then there is a whole lot of France where the traverse style will be available but not relevant. Because it is available people will start using it, but because it is not available in Australian we probably will not see it.

If there is some other usefulness of this gear style other then Font traverses then it would be good to see this emerge globally.

I think it should be universally available. Who are we to say that this feature should only be restricted to FR grade context. Also it is far simpler for us to release this gear style everywhere. Why spend effort reducing functionality.

Anyway I am probably rambling and I don't really feel like trying to make myself clearer. I will do it without restriction first then if it is unworkable we can make the appropriate restrictions.

**Comment by brendanheywood** [comment]
Yeah I'm not against it being everywhere, it just didn't seem that useful to places. How do we handle it if people start using it Australia with V grades, do we just collect them as boulders for stats? I assume in France we'd still count them as boulders?

**Comment by scd** [comment]
If there is a stats problem in Australia then there will be a stats problem in France. I am guessing we should just treat them as boulders.

**Comment by scd** [comment]
I have added Font trav on my prod and added a new gear style type. I want to get a feel for how this works and get some feedback, but at some point in the future we may need to do further tasks

 - [ ] limit traverse to certain nodes / contexts
 - [ ] update profile page to deal with traverses differently (eg combine traverse gear style with boulder). 

We can re-open or create separate issues for these potential tasks at a later point. For now closing
