### ISSUE TITLE
Schlossberg grade data migration tidy up

### ISSUE THREAD

**Issue by scd** [theCrag/website#2039]
http://www.thecrag.com/climbing/germany/oberbayern/area/439569120

Resolving this issue may depend on adding the capability of having a grading context assigned to a crag (issue #1915)

In this area should the default context just be French? Or should we be converting all the grades to UIAA?

**Comment by birgander2** [comment]
Normally, only UIAA is used in Oberbayern. Maybe contact one of the followers of this crag directly, they should know better (and seem to have edited a lot here)

**Comment by Mdemaillard** [comment]
Grade context is UIAA, but all routes are consistently displaying french grade e.g. {fr} 6b in the area mentioned and both siblings.

**Comment by Mdemaillard** [comment]
Alright, ich checked with Robert Busch - @sirrob which seems very activ in the area, his opinion is that the whole area should be changed from UIAA to FR, not only Schlossberg or Oberaudorf but wider.
In his words: (free translation from german) "nobody uses UIAA anymore, in a few guides you would still find some UIAA grades but it is simply not fitting current times anymore.
Not only Oberaudorf, also Bixlwand, Buchberg, Weigend Süd, Flintsbach, Bichlersee, Idealwand and Brünnstein should be converted to FR :-( "

Can someone please update the Oberaudorf context to FR, so at least the de-facto situation is corrected (context matching with systematic route grading in use ? Then we can close this issue.
If someone feels like changing other area we can open a forum discussion.

**Comment by scd** [comment]
@Mdemaillard I have granted you worldwide admin permissions. I cannot remember if this is enough to change contexts, but can you check if you now have 'Default area context' in the edit area form.

<img width="226" alt="Screen Shot 2020-03-27 at 9 06 00 am" src="https://user-images.githubusercontent.com/373058/77701461-7b5e8f80-700a-11ea-8951-a14006a78376.png">

My preference is to share this capability with you because we almost always go with local opinion and it is a common issue. 

If you do change it then you should be aware that there are some painful cache issues which can take a week or so to propagate down the index ancestors without dev intervention to reset the cache. Just let us know the url. Also you will see quite a few routes change their contect warning and end up with '{UIAA}' in front of the grade. This is a warning that the route is a different context to the area.

**Comment by Mdemaillard** [comment]
Awesome. I do see the World-Admin in my profile-
I do see a few more options here and there, like editing permissions for areas.
The area context field & URL Stub as seen above are not available.
I'll play a bit in sandpit to see what else is newly accessible

**Comment by birgander2** [comment]
I don't really see the problem here, you can always enter French grades in the UIAA context, they're recognized correctly and displayed without strange prefix. This only happens if the context is changed on a route's basis to French, which was unnecessarily done here.

Apart from that, the situation of using UIAA & French in Germany is indeed a bit strange. While basically all guidebooks and most low- to medium climbers use UIAA, in particular high-end climbers seem to prefer French to better compare to other foreign climbs. So it's not an easy decision which context is the best one.

**Comment by Mdemaillard** [comment]
Agreed, the point in case is he is listing lots of single crags where the majority if not all of routes are listed with french grade in a UIAAc ontext. So in that context, switching the context makes sense.

100%, i wouldn't change a crag where the situation if let's say 30% routes listed matching the context.

**Comment by Mdemaillard** [comment]
Uhhhh i was too quick on this one. So changing every individual route context from FR to UIAA while leaving the grade input as is (e.g. 6b) will solve the display issue... OK i see the point.
I'll try and deep dive a bit to understand how the context work and which grade system they accept before changing anything (if i get the access to it).

**Comment by birgander2** [comment]
Oh, you're right, but I'm pretty sure that this has been different in the past, French grades displayed as simple "8b" in the UIAA context. Since this is now different, probably forget what I said before.

**Comment by Mdemaillard** [comment]
OK, done in all areas except Bixlwand, since there is one sector full on IAA there.
will check with user if happy.

**Comment by birgander2** [comment]
I would like to suggest to change (back?) the behavior how french grades are interpreted in the UIAA context. They should simply be displayed as "8b" and not as "FR:8b". It already / still works pretty fine with Fb grades, they're displayed as "7B" and not "FB:7B".
