### ISSUE TITLE
Route numbers are screwed up by annotations in topo editing pages

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2040]
Topo numbers don't match route table numbers.

![image](https://cloud.githubusercontent.com/assets/187449/9724318/b2155588-5618-11e5-8abd-fb59ac934a82.png)

Also the numbers in the 'add route' process are also screwed

**Comment by scd** [comment]
This comes down to an inconsistency in the way we are dealing with annotation numbering for various modes in TopoUtil. In some modes we are counting annotations and in others we are not.

I am assuming that that we have not linked any annotations into a topo, in which case we should not be counting annotations in the numbering. I have made this fix.

Once we include topos in annotations then this we should always include annotations in numbering for all modes. But until we do this annotations will have no numbering.

**Comment by brendanheywood** [comment]
Wether we link topos or not shouldn't make a different to the numbering, annotations shouldn't get a number. Instead it should just show the annotation name / desc in the process

**Comment by scd** [comment]
I will not argue because I have made the change to work the way you suggest.
