### ISSUE TITLE
Profile doesn't show gear style band correctly

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2041]
My profile doesn't show gear style band correctly:

http://dev.thecrag.com/climber/brendanheywood

I only have boulder ascents and no trad or sport? Dev stats quirk or new bug?

![image](https://cloud.githubusercontent.com/assets/187449/9728743/7d2048bc-564d-11e5-980d-d45bb212d835.png)

**Comment by scd** [comment]
Now that I have looked into it I have worked out what this is. Check out your settings:

https://dev.thecrag.com/climber/brendanheywood/settings/filter

You have just boulder routes set. This is also the same on prod. I presume you are seeing the same symptoms on prod. Reset to all routes and let me know.

**Comment by brendanheywood** [comment]
doh, that wasn't obvious to me at all. Dunno what we need, closing and might add some language or something later

**Comment by scd** [comment]
Yes it is not obvious. This enhancement was based on a lot of user requests at the time. Maybe change the language around the 'Users' tab. Maybe call it 'Custom'.

**Comment by scd** [comment]
I have changed the default filter tab label from 'Users' to 'Custom' to make it clearer that the default tab is customisable by the user.
