### ISSUE TITLE
Convert facet filters for people into select2 inputs

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2043]
Routes:
- [ ] Been climbed by
- [ ] Never been climbed by
- [x] FA history (already done)

Ascents
- [ ] Been climbed by
- [ ] who with

Photos:
- [ ] uploaded
- [ ] taken by
- [ ] picture of

Topos:
- [ ] made by
- [ ] made by friends of

Climbers
- [ ] climber

**Comment by Mdemaillard** [comment]
These can all be ticked. They are all with the free text field that suggests as you type, which i assume is select2.
![image](https://user-images.githubusercontent.com/60388146/76510510-6c001380-645a-11ea-80d3-2a5fa26af711.png)

![image](https://user-images.githubusercontent.com/60388146/76510539-75897b80-645a-11ea-877a-3079a49621f9.png)

![image](https://user-images.githubusercontent.com/60388146/76510562-80441080-645a-11ea-86ab-1b6ab1e092df.png)

![image](https://user-images.githubusercontent.com/60388146/76510598-8c2fd280-645a-11ea-8838-239db0922737.png)

To be ticked and closed.

**Comment by rouletout** [comment]
Yes, closing
