### ISSUE TITLE
Our release summariser does not like open issues

### ISSUE THREAD

**Issue by scd** [theCrag/website#2045]
There are only two issues reported in issue 44 release summary:

https://www.thecrag.com/release/44-streams

My guess is because there were some open issues. If so this is a workflow problem because I have to keep some issues open for release followup.

**Comment by brendanheywood** [comment]
We can rebuild this at anytime, so I think we build it, release, then spend a bit on cleanup, close issues, rebuild, then advertise the release page

**Comment by scd** [comment]
When I have done a release I want to get stuck into a beer, and move on. We should work it so there is very little cleanup. Closing followup issues is something we cannot avoid.

I think we are becoming more disciplined with our issues, so this step should be very quick and painless.

Anyway there is something I have to look into here, which is why I could not publish the release summary url.

**Comment by brendanheywood** [comment]
Something else is messed up, the data is there, think it's a template issue

**Comment by brendanheywood** [comment]
ah ok so the script is doing what it's supposed to, pretty well none of the issues are tagged up right. Only 'new features' 'enhancements' and 'bug fixes' are shown in the release notes, the rest are usually internal technical stuff and not as interesting so filtered out. Perhaps we should relax that and show them all?

**Comment by brendanheywood** [comment]
doh, there is a second issue where we have hit githubs page size in their api so we are not returning all the records. Luckily we can set the page size, but it has a max of 100 and this release was 99 issues. Most releases don't get anywhere near this size and I couldn't be bother implementing the pagination right now.

I've also gone through and tagged up all of the things that I reckon should have them, and put a bit of love into #1679 as the 'primary' stream public facing issue with a screen shot

This new release page is now live:

https://www.thecrag.com/release/44-streams
