### ISSUE TITLE
Streams minor tweaks random small stuff

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2048]
Man streams total rock so much more than I was expected :) And I was expecting them to be awesome :)

This is all fine polish stuff, anything big or worth discussion I'll put into a different issue

* [x] if only one route then don't show the summary: http://www.thecrag.com/event/736067868

![image](https://cloud.githubusercontent.com/assets/187449/9811037/28b4702e-58b8-11e5-83cc-8bbff3791e03.png)

* [x] if no previous description, say 'Add desc' instead of 'updated desc'

* [ ] this event makes no sense to me: http://www.thecrag.com/event/736065921

* [x] if a stream contains a bunch of stuff, eg 25 new routes and 2 topos, give some sort of priority to the topos, so show the topos and don't show the routes, eg: http://www.thecrag.com/event/736065720

![image](https://cloud.githubusercontent.com/assets/187449/9811391/581d587e-58ba-11e5-9f26-8145a07ae0e4.png)

**Comment by Drazhar** [comment]
Hey, I really like the streams!

But is it on purpose, that the ascent history of a single route is removed and replaced with a activity stream? I would rather like to have the ascent history back and the stream underneath it, because typically I'm interested in the comments of the people who logged this route and not their whole ticklist of this day.

**Comment by brendanheywood** [comment]
The route feed was like that as a compromise to keep things really fast. However I think what we should do is just customise the display so it says something like 'ticked xyz with comment ... And also ticked 10 other routes Arapiles' so you still get context but get succinct event. We could possibly also do this at the crag level so we only show the full details for routes inside the current cliff. @scd thoughts?

**Comment by scd** [comment]
I think it is interesting knowing what else somebody climbed. I think the way to go is to adjust the display. Probably just do this at route level

**Comment by brendanheywood** [comment]
Did you do this? This seems to already be happening, at least in some cases like this:

ie only 1 route, the one whose page we are one:
![image](https://cloud.githubusercontent.com/assets/187449/9830467/75b09abe-5972-11e5-967e-cb419e8b2474.png)

Yet the stream event has a whole bunch:
https://www.thecrag.com/event/738062631

In other cases it contains many routes:
![image](https://cloud.githubusercontent.com/assets/187449/9830475/d12b8994-5972-11e5-917a-c7ef0cdd5720.png)

https://www.thecrag.com/event/736051914

Hmm...  I think this is due to the different crag structures and some being cliffs vs crags.

**Comment by brendanheywood** [comment]
How's this for a mockup compared to above? It gets rid of as much boiler plate as possible, and also makes you open up the full ascent list in order to expose the comment button.

![image](https://cloud.githubusercontent.com/assets/187449/9830528/b2c7c53c-5975-11e5-8dd8-575aa88e8f17.png)

**Comment by scd** [comment]
I have had a simpler approach to routes. I filter the route event to only include activity items directly related to that route. If you click on the full event you get all the ascents. It is a one liner and hot fixed.

**Comment by scd** [comment]
Hot fixed some of this stuff.

FYI, there is a use case where there are lot's of topos so they are hidden in summary mode. @brendanheywood is this a problem for your reviewing?

**Comment by scd** [comment]
BTW that strange event refered too routes that don't exist. Actually I have not fully checked that they are not disabled routes. I think that they were added then removed, but this is just a guess. I don't propose to do any further investigation. But if it happens more often then we should create a separate issue and I will investigate further.

Closing issue

**Comment by brendanheywood** [comment]
I don't think we should do too much just for my use case, for me as long as I know there is a topo to review that's enough to dig further

**Comment by nicHoch** [comment]
https://www.thecrag.com/event/746978877

No area name
Am 13.09.2015 11:41 schrieb "Brendan Heywood" <notifications@github.com>:

**Comment by brendanheywood** [comment]
This issue is closed, moving that to a new one: https://github.com/theCrag/website/issues/2073
