### ISSUE TITLE
Stream dates not right??

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2049]
![image](https://cloud.githubusercontent.com/assets/187449/9812076/4df838e2-58be-11e5-8544-73e1b8154fa8.png)

**Comment by brendanheywood** [comment]
This seems like the time the migration was run, I thought we had a workaround for this?

**Comment by scd** [comment]
I think I just fixed it when the time difference is on a different day or
two. This should just go away.

**Comment by brendanheywood** [comment]
Do you mean go away after the background processing is finished?

**Comment by scd** [comment]
Processing is finishes. Let's see if it is still a problem in two days.

**Comment by brendanheywood** [comment]
This is sorted :)

On Fri, Sep 11, 2015 at 10:29 PM, Simon Dale <notifications@github.com>
wrote:

> Processing is finishes. Let's see if it is still a problem in two days.
> On Sep 11, 2015 10:05 PM, "Brendan Heywood" <notifications@github.com>
> wrote:
>
> > Do you mean go away after the background processing is finished?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/theCrag/website/issues/2049#issuecomment-139529443>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theCrag/website/issues/2049#issuecomment-139533351>.
>



-- 
cheers
Brendan

http://thecrag.com/

http://github.com/brendanheywood
http://www.thecrag.com/climber/brendanheywood
