### ISSUE TITLE
Make a very simple static map preview for located nodes in stream

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2050]

**Comment by scd** [comment]
We have already got a simple map view in linkMap template. I have hooked this up. Task list for doing this included:

 - [ ] getting the historical bbox and boundary from the activity log
 - [ ] linking stream detail template to linkMap
 - [ ] sorted out a couple issues in linkMap which made some assumptions about the map having children
 - [ ] moved the css in the linkMap template to a staticmap.less file to be included in portal.css

Done in Simons dev.
