### ISSUE TITLE
Stream feedback from Rob / Neil: split 'following' into 'following' and 'FoaF'

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2052]
Note sure about what to label it, but they clearly don't want to see friend of a friend stuff

**Comment by scd** [comment]
We don't have friends of a friend. However if one of your friends is mentioned in, or comments on an ascent then you will see in in your feed. I wonder if this is what they are getting at?

**Comment by brendanheywood** [comment]
Yes this is exactly the issue, so I think the terminology that makes most sense in the settings page is 

Ticks: mine, by those you follow, involving those you follow, favs, etc

Either that or just for now reduce it to just 'by'

**Comment by scd** [comment]
There may be more then just wording here. Let's leave this one for a bit.

**Comment by scd** [comment]
@brendanheywood do you think this is still something we need to look into. There were a lot of things going on with the initial release of streams, of which I think this was very minor.

If we do need to keep this in then there is a structural database task that needs addressing. At the moment the query relies on people being involved in the event, however the involved table does not store how they are involved. While we can probably do additional joins to work out how they were involved this will lose performance.

Could you either close the issue (happy to re-open later) or confirm that you want to keep the issue open. If we keep the issue open then it needs to be re-labelled and discussed a little further.

**Comment by brendanheywood** [comment]
I think we just leave it open but do nothing for a month and then ask them (or everyone) who it's going now that they've had a bit of time to get used to the changes.

**Comment by Mdemaillard** [comment]
no input in 4 years, assumed stream system accepted by now. closing.
