### ISSUE TITLE
Configure level of detail in streams.

### ISSUE THREAD

**Issue by scd** [theCrag/website#2054]
Is it worthwhile allowing people to configure the level of detail they want to see in streams. For example they may want to see the full ascent info, but only the summary for updates.

**Comment by brendanheywood** [comment]
I'd probably say no, or at least defer this for a couple release until everything is polished. I think most issues are just what is in the feed, and tightening up the layout and copy in general

**Comment by scd** [comment]
Looking at the feedback I tend to agree that we may not have to do this.

I am closing. We can reopen if we want to do this in the future.
