### ISSUE TITLE
Change the stream defaults to not include favorite crags

### ISSUE THREAD

**Issue by scd** [theCrag/website#2055]
Maybe only updates from favorite crags.

The big complaint is people are seeing ascents and comments from others they do not know. If we remove ascent and discussion defaults from fav crags then this should fix the problem.

Crag discussions are still coming through on dashboard discussions, so this will be uneffected.

**Comment by scd** [comment]
I have changed the defaults so that if you are following people and watching crags then you do not get random peoples ticks. If you are just watching crags then you will get random peoples ticks.

**Comment by scd** [comment]
I have changed the defaults so that if you are following people and watching crags then you do not get random peoples ticks. If you are just watching crags then you will get random peoples ticks.

**Comment by brendanheywood** [comment]
Gold
