### ISSUE TITLE
'Know this route style?' behind topo images (minor bug)

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2058]
Hey,
just had a small bug when I have tried to assign a route style. I think the image shows what I mean:
![unbenannt-1](https://cloud.githubusercontent.com/assets/3040689/9835550/294f77ec-59f1-11e5-896a-79c170edd907.jpg)

**Comment by scd** [comment]
Actually we fixed this in issue #2042, but the fix missed the release. We decided not to hot release the correction as it was relatively minor. Thanks for reporting
