### ISSUE TITLE
Message single ascent in streams

### ISSUE THREAD

**Issue by scd** [theCrag/website#2062]
From Lee,

I want to be able to make a comment on an individual ascent (as per the old format, which would then often kick off a discussion - the best feature of the old format). It seems with the new format, if someone ticks say, 5 routes, I can comment on the entire lot (is this now called a 'stream event?', but not on one specific ascent

**Comment by scd** [comment]
The UX should also allow us to message a photo directly as well.

**Comment by brendanheywood** [comment]
So thoughts is to keep this as low key as possible so it's not visibly heavy as it will be repeated a lot.

Mockup:

![image](https://cloud.githubusercontent.com/assets/187449/9839640/e15f06d6-5ac3-11e5-8653-b9066ca86916.png)

Rough code:
```
<div class="pull-right"><a class="btn btn-mini btn-flat" href="#"><i class="icon-comment-alt"></i></a></div>
```

The comments themselves can just be inside a ```<div class="event-inset">``` under the route but apart from that keep it exactly the same as the other comments at the bottom.

**Comment by scd** [comment]
What about with photos. We use media grid with photos that means photos can stack across a row.

**Comment by brendanheywood** [comment]
Let deal with photos later that is a new use case, ticks is a regression case

**Comment by birgander2** [comment]
+1  

Why not adding a small dropdown as before? For example, before I could edit my own ascents, no not anymore. Something like Edit, Comment, Details, Target, Me too, etc.

**Comment by Drazhar** [comment]
+1 for the idea of birgander2. I miss these options too.

**Comment by brendanheywood** [comment]
+1 for edit etc, lets start with 'Comment', 'Edit', 'Tick this route'.

* Details is the link of the route so not needed
* 'Me too' I always felt was poorly names, so I think 'Tick this route'
* 'Target' we will do properly when we implement tick lists see #1318

**Comment by leecujes** [comment]
+1 for the idea of birgander2.

**Comment by scd** [comment]
I plan to work on this next week.

**Comment by leecujes** [comment]
Also, the RSS feed seems to now say "Lee Cujes went climbing in Kalymnos and ticked 3 routes". Previously it pushed ascents separately. People want detail!

**Comment by scd** [comment]
@leecujes how important is RSS to you? I want to get a feeling for how it is used and what value it creates for you. Just because I don't understand it, it does not mean there is not value in it. 

I would rather people come to their dashboard page where they can get the full featured stream with full markup, see private friends, formatting and the ability to make comments. At the moment the RSS feeds are set up with the minimum information as a trigger to get somebody to visit their dashboard.

**Comment by brendanheywood** [comment]
I thought we set ths up to re-use the same templates so it should be exactly the same as the dashboard event but without JS / topos etc. The route ascent details should be there in full?

**Comment by scd** [comment]
I just went for summary mode

**Comment by brendanheywood** [comment]
Ok so that should be trivial to flip over then

**Comment by scd** [comment]
Have to audit the detail to make sure it produces sensible markup (<p>)

**Comment by leecujes** [comment]
Hi Simon

RSS feeds are not super important to me personally. But they may be important to others, not sure. 

My philosophy on feeds is as a content aggregation service. IMO it's wrong to think of them as some kind of marketing tool to encourage people to go somewhere else. They won't. Remember, people actively subscribe to RSS feeds. If the feed doesn't contain the information, they won't subscribe. 

For example, I use Feedly to aggregate updates from many many sites so I don't have to visit hem individually. If thecrags feed lost its useful content (who climbed what and where), I would unsubscribe.

**Comment by scd** [comment]
@brendanheywood please pull from repo and test commenting on specific ascents.

You will notice that I have tightened up the screen space. Feel free to create more space again if you think it is too tight.

I have implemented a dynamic dropdown for each ascent which includes:
 - [x] comment on ascent
 - [x] view the ascent page
 - [x] view the route page
 - [x] view all ascents of the route
 - [x] edit your own ascent
 - [x] log an ascent of the same route

I have also moved the button to comment on an event next to the event dropdown.

**Comment by brendanheywood** [comment]
done. I've just tweaked a few bits of overlapping margin but all looks pretty nice

**Comment by scd** [comment]
great, that was quick. I have also just pushed removing summary mode in the rss feed. I needed to do a few other things to exclude stuff the rss is not handling. 

Closing now.
