### ISSUE TITLE
Stream duplicate information showing both summary and detail.

### ISSUE THREAD

**Issue by scd** [theCrag/website#2063]
For example on ascents:

![double-info](https://cloud.githubusercontent.com/assets/373058/9839330/c0a4b490-5ab9-11e5-8f99-9848ae70c978.png)

Should we streamline this to exclude the summary when the detail is shown. Personally I like to see the summary, but there is considerable feedback that the summary should not be shown if the detail is shown.

**Comment by brendanheywood** [comment]
I think the tagline and summary in almost all events types can be merged, ie in this case:

 'Josiah Hess onsighted 3 routes, redpointed a route, dogged 2 routes and seconded a route at Glasshouse mountains'

Even that is very wordy, I think we could prioritise the first 1 or 2 types of info and merge the rest into something like:

 'Josiah Hess onsighted 3 routes, and climbed 4 other routes at Glasshouse mountains'

**Comment by scd** [comment]
done for ascents. Need to also do this for updates

**Comment by scd** [comment]
done and hot fixed
