### ISSUE TITLE
Allow somebody to turn off updates in their public profile stream

### ISSUE THREAD

**Issue by scd** [theCrag/website#2066]
If somebody only wants their ascents shown in their public page then we should allow this. Feedback from Ben on Facebook.

**Comment by brendanheywood** [comment]
ie for when anyone looks at their profile? I'm not heaps keen on this in terms of openness and transparency of edits, so as long as it's easy for other to see their edits then ok

**Comment by scd** [comment]
I think it is more about how you want to present yourself by default.

The openness and transparency is still an unresolved issue though. I think a lot of people want to do edits privately. We should tread very carefully here. I am definitely in two minds about this. I certainly would not want people to hide behind private edits so they can do harm or break copyright.

**Comment by scd** [comment]
I have gone the other way with this. You set the configuration that you want to view other peoples account.
