### ISSUE TITLE
atom feed for recent gym ticks at world level is now showing all ticks

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2067]
I'm too worried about this directly but could be a sign of deeper stuff?

**Comment by scd** [comment]
The deeper level is we forgot to put in the gym tick filter in our streams. Maybe it is not such a big issue anymore. Let's see what the feedback is.

**Comment by Mdemaillard** [comment]
not easy to check now since all gyms are closed... i see at world level in the stream the Contain Covid 19 gym ticks, havent found other after a few clicks.
anyway anyone looking at world lvl shouldnt be miffed to find stuff he's not interested in ?
closing this one
