### ISSUE TITLE
More compressed layout for streams

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2068]
The new streams are really nice! They only waste really a lot of screen space. At the moment, for example, can only see 3 ascents without scrolling (and I have a huge screen) instead of maybe 15 before. It would be cool if you can improve the design a bit, or to offer optionally a "light" stream blending out most of the stuff.

Some points: font size in the stream is larger than the rest of the website, there are many new paragraphs with extendend linespace, date box requires a lot of vertical space, "make a comment" could be part of the drop down (for each route maybe).

**Comment by Drazhar** [comment]
+1

**Comment by brendanheywood** [comment]
Yes and I've already done a bit on dev for the next release on this front. More to come over time too

**Comment by scd** [comment]
Task list 
 - [ ] Some of the update detail items can be joined into one paragraph. Others will have their own paragraph.
 - [ ] Fonstize should be based on site fontsize not absolte. With exception of date box.
 - [ ] Reducing spacing above and below date box.
 - [ ] Add comment should be added to the front of dropdown and removed from end of event. If there are already comments then it should still be at the end of the event.
 - [ ] Spacing between topo description item then topo not right.

**Comment by scd** [comment]
done
