### ISSUE TITLE
labororious work going back in stream history for routes witch few ascents

### ISSUE THREAD

**Issue by scd** [theCrag/website#2070]
Eg

https://www.thecrag.com/climbing/australia/townsville/route/198015606

There is only ever one ascent a month, and sometimes that could be private. 

I am wondering if we should do a faceted search hear instead. I think there has been a lot of feedback about people wanting to know ascent comments so a facet search for ascents with comments would be perfect.

Alternatively we could work out a heuristic for the window opening size. For routes it defaults to 1 year, but for a route like this we could probably default to 10 years. Note that we can choose any window size for opening a stream, but going back further is a month at a time.

**Comment by brendanheywood** [comment]
I understand the problem, but isn't this exactly why we added the month by month indexing so we can look this all up quickly server side and skip back through many months of data if they are empty until we get meaningful data?

**Comment by brendanheywood** [comment]
and we should also fix the stats so they don't include private ticks so it's all consistent

**Comment by scd** [comment]
Yes the skipping back is working, but there is only one ascent per month, so we are pushing the more button for single ascents.

The private ascents is a deficiency in the way we are doing it. The problem is that we have no idea who the operator account is when we create the filter. What is private for one person may be available for another (for example your own ascents). This is a deficiency we discussed and agreed we could live with. It is just way more apparent on a use case like this.

**Comment by brendanheywood** [comment]
I was talking about the '12' in the top header on the route page, if there are private ascents they should be completely invisible, not half invisible. ie total stats should be consistent with facet count, and stream count.

I don't mind only getting a single ascent if it is a long way back in time. It isn't ideal, but it's not completely horrible. The thing that bugs me more is the pages which have a private tick and so don't show anything, so you clicked and got nothing.

We could implement a semi-iterative thing where if the page is under a certain number of events it pre-emptively grabs the next page. I'm in two minds about whether it's worth it. If we did I would want it to do some sort of time measurement of the processing time and keep on grabbing extra pages until either the # of events if above the min threshold (maybe 5?) or the time budget has been exceeded (eg 300 ms)

**Comment by brendanheywood** [comment]
Also the single event per page issue I think would be mitigated if and when we implement a timeline chooser thing, where instead of getting a simple 'Load more' you get the years / months which actually contain stuff to inflate. Def not critical, nice to have

**Comment by scd** [comment]
+1 for the stats. Sorry I misinterpreted. This is a long standing issue, maybe I should get on with it.

**Comment by Drazhar** [comment]
I like the current state, that the stats of private ascents are also counted in the two diagrams for the route quality and the ascent style.
In my opinion it's always good to have as many ratings as possible.

**Comment by scd** [comment]
Yup some stats should include private ascents and some should not.

**Comment by brendanheywood** [comment]
I'm more interested in consistency rather than hiding or showing. So the other option is we do show private ticks but anonymised and redacted like we used to.

**Comment by scd** [comment]
I have created a new ascent facet - 'has beta' - and linked to it from the route page. This will mitigate a couple of issues with the route stream, as I think this is what people were looking for in the old route ascent feed. 

I think what remains in this issue is the timeline chooser, which I cannot see logged elsewhere so am logging that in issue #2087
