### ISSUE TITLE
allow people to configure index streams

### ISSUE THREAD

**Issue by scd** [theCrag/website#2074]
I think there are a few people who would like to customise what is in their index stream in a similar fashon to dashboard.

If you never want to see updates then maybe you should be able to filter them out for example.

It should be failry straight forward to add index stream customisation in the streams customisation web form. Then when they browse the index, their stream config could be used.

**Comment by brendanheywood** [comment]
I reckon the best ui here would be next to 'activity' a drop down that shows a similar matrix of checkboxes, tick or untick and refresh inline. Saves and applies to all. Could do the same thing with the dashboard too

**Comment by brendanheywood** [comment]
I reckon we could even just go inline like this:

![image](https://cloud.githubusercontent.com/assets/187449/9951903/b0e19bcc-5e10-11e5-940f-605d07788aff.png)

**Comment by scd** [comment]
+1, but only for index. Dashboard is a configuration matrix. In particular you might want ascents of people you are following, but not from crags you are watching.

Also the Favorites is not easily separable with the ticks. For dashboard config we have lumped ticks and favorites together. Unfortunately I used that same paradigm to create the historical stream filter. Significant work to separate them again, but could be done and would have to be manged in it's own issue.

I think we also want the system to remember the config, in which case we may as well also put it in the settings to keep it transparent.

**Comment by brendanheywood** [comment]
Yeah I'm not fussed on what the tick boxes actually are, just that they are inline. I'd expect setting these in one area to be stored across the whole site, the settings could be duplicated in the settings page too I guess.

**Comment by scd** [comment]
This is done in repo (for both index and account public profile pages). 
 - [x] defaults set in account settings for both index and public profile pages
 - [x] checkboxes which reload the stream. Note I decided not to remember checkbox changes in the index, rather use account settings to set defaults. 
 - [x] done for area page, route page and account profile page.
