### ISSUE TITLE
Include dates for historical ascent display in streams

### ISSUE THREAD

**Issue by scd** [theCrag/website#2076]
See this event

http://www.thecrag.com/event/748346880

and this

http://www.thecrag.com/event/748309449

**Comment by brendanheywood** [comment]
Also not too keen on the ;historical ascent', it seems too close to an FA / FFA, maybe something like 'logged ascents from the past'. Also not sure if you did anything with ticks from yesterday or withing the last few days, these probably should have something different again as they aren't far in the distance past.

**Comment by scd** [comment]
I have changed the wording as you suggested. I did not pick up on the overloading of the word historical, so it was good to get a second pair of eyes on this.

BTW, the trigger for ascents from the past is 10 days. Basically it means you can go away for a period covering two weekends without being able to log ascents. This is something I use to do a lot.

Please let me know if you you think a different trigger period should be used.

**Comment by scd** [comment]
Closing, please reopen if you want to change the trigger period.
