### ISSUE TITLE
Do we want keyword colors in ascent comments

### ISSUE THREAD

**Issue by scd** [theCrag/website#2077]
I like them but it is potentially confusing for users not being able to control this. I am happy to turn this off and wee who comments

**Comment by brendanheywood** [comment]
Got an example of this in action? Is this legacy from before we added colours for gyms as a proper field?

**Comment by scd** [comment]
![tc-ascent-color-keyword](https://cloud.githubusercontent.com/assets/373058/9983550/3f5a8aec-6043-11e5-8b61-eac9f4a8baf0.png)

**Comment by brendanheywood** [comment]
Ah yeah. I dunno this is such an old part of the system and does make quickly parsing the message much quicker. What's the reason you want to remove it?

**Comment by scd** [comment]
Occasionally I look at it and am reminded of some feedback ages ago that was based on the assumption that the user could control this. The feedback was negative and target against the user. It was a long time ago.

Is the benefit of quickly seeing key concepts in an ascent comment greater than the loss of control the user has?

I am happy to either way. I was just in the code so thought I would start a discussion about it.

**Comment by brendanheywood** [comment]
I still think it adds value and I've never seen any complaints about it. +1 to keep

**Comment by scd** [comment]
ok back in. At least we have had the discussion so I can move on.

**Comment by nicHoch** [comment]
I also like the colors
Am 21.09.2015 06:33 schrieb "Simon Dale" <notifications@github.com>:
