### ISSUE TITLE
Have a button to reverse all the points in a topo route

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2078]
* ie select a route, somewhere in the panel have a 'Reverse line' button, maybe tucked under a menu as it's a small edge case

**Comment by brendanheywood** [comment]
Example in the wild:

https://www.thecrag.com/climbing/australia/nowra/new-nowra-braidwood-road/area/13247977/topo#t763548672

**Comment by scd** [comment]
Tasks:
 - [ ] UI needs a button added - 'Reverse points'
 - [ ] topo API reversePoints = 'all'. (later if we want to do it for just one route then we can use the route id)

**Comment by brendanheywood** [comment]
I was just going to reverse the points in js land, you may want to reverse a couple all in memory in the client and then save the lot along with other edits, the api won't be touched at all.

**Comment by scd** [comment]
Ok, that is probably easier.

**Comment by brendanheywood** [comment]
done, new context 

![image](https://cloud.githubusercontent.com/assets/187449/10531288/e2ba2b5e-73fb-11e5-9115-5de8a2b32fff.png)

Although this does work in the GUI there is an unrelated issue where the api call to save doesn't work. Fails even without this patch so ignoring but you might want to check whats going on:

![image](https://cloud.githubusercontent.com/assets/187449/10531340/544e6c9e-73fc-11e5-9331-c87a27bcc7fa.png)

**Comment by scd** [comment]
The API error was a google analytics queue file with the wrong permissions. It should be ok now
