### ISSUE TITLE
Ukraine appears to use french grades, tweak context mapping

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2080]
http://www.thecrag.com/climbing/ukraine/crimea/area/14263495

**Comment by birgander2** [comment]
And to link crimea to ukraine semms to be disputable nowadays, too...

**Comment by scd** [comment]
I am not sure what to do with Crimea. Move it up one level. Can we make it a country?

I have updated Ukraine to FR and Crimea to FR in case we move it around.

It may take a couple of days  for the cache to reset itself for routes in Ukraine. This will only be a temporary display issue.

**Comment by scd** [comment]
I am going to close this issue because the initial subject of the issue has been resolved.

@birgander2 if you want to persue the Crimea task further then we can open another issue, or just do it. Let me know if you need permissions.
