### ISSUE TITLE
Area in event mis-linked as a route

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2081]
http://www.thecrag.com/event/735638067

![image](https://cloud.githubusercontent.com/assets/187449/9989471/ee6e25fe-609b-11e5-867f-9f055442ffde.png)

Spider terrace is an area so the node url fails:
http://www.thecrag.com/climbing/australia/gara-gorge/dome-wall/route/13345147
it should be
http://www.thecrag.com/climbing/australia/gara-gorge/dome-wall/area/13345147

**Comment by scd** [comment]
This is a bit irritating, some configuration was wrong. Resequence Area activity log has been configured as a route activity which has propogated itself into the activity log. 

I have fixed the configuration issue, but it will need post release data migration to fix existing stream events.

**Comment by scd** [comment]
I don't think I am going to find the time to fix this where it is wrong in old stream events. It is good for new events so I am closing.
