### ISSUE TITLE
stream vs route vs facet page count of ascents is inconsistent and some ascents are missing in the stream events

### ISSUE THREAD

**Issue by scd** [theCrag/website#2082]
In this route there are 21 ascents

https://www.thecrag.com/climbing/australia/blue-mountains/mount-piddington/route/15394519

But only two in the stream.

Most of them are there in the faceted search

https://www.thecrag.com/climbing/australia/blue-mountains/mount-piddington/route/15394519/ascents

**Comment by brendanheywood** [comment]
Pre - log data ascents?

**Comment by scd** [comment]
of course.

**Comment by brendanheywood** [comment]
Fixed?

**Comment by scd** [comment]
Nope explained. Actually maybe we should make this clearer in the end of stream notice so we do not have to keep on explaining the deficiency to users. I will reopen.

**Comment by brendanheywood** [comment]
No we need to just fix it and retro generate the old log data. Nobody cares about our internal data structure, they care that data is missing

**Comment by scd** [comment]
Hmmm, nobody brought this up in 5 years with the ascent activity log. It is only because it is currently fashionable to bag the streams release that we are under the mircroscope.

Our previous discussion was that we were not going to retrograde activity log. I am happy to reopen that discussion based on new evidence, but there are significant implications. 

It is going to be very difficult to retro generating activity log properly as there is information missing. For example some updates we could work out (eg description changes) and others we will not be able to work out (eg change area type). Also we don't know the log date for ascents before system port in about 2010.

So retro generating is not going to be complete, which I find could be misleading.

Note that depending on how we do it he filter may have to be redone because it is based on a 2010 zero offset.

For example we may just decided to do one massive event at 2010 where everything is created at once, which will cause it's own issues performance issues. Alternatively we could could use the actual date the route was climbed, which will totally break the filter and the assumption that the filter has a zero time offset.

This is a huge amount of work and discussion. Most probably many dead ends when we uncover hidden issues.

**Comment by brendanheywood** [comment]
Nobody really looks at the activity log facet, only the ascent facet and the feeds in the area pages. The ascents and feed used to be consistent, now they are not. I don't think people are complaining because it's fashionable, its because there is a tangible step backwards in functionality. I don't think we need to tackle every update type, eg favs, updates, but we definitely need to sort ascents.

Using the facet url above as an example I don't see any critical data which is missing? As long as the event stream is essentially consistent with the facet page in terms of content and event ordering then all is good. the facet uses ascent date for order and then defaults to log date where missing, the event retro data should use the same logic

**Comment by scd** [comment]
Of course, I have miss remembered, ascents were a separate query unrelated to logs.

So we only retro generate ascents. This reduces the scope. But there is still a significant issue with the business rules you suggest. Using log date will cause a problem with the filter bitmap which starts at 2010.

If we want to use the Ascent Date to generate the stream calendar date then we will have to re-baseline the filter bitmap to another start date, which increases the size of the bitmap, but this should not be a major problem unless we want to go right back. Re-baselining the filter bitmap is a major data-migration issue as every filter entry will have to be rebuilt. If we do this then we will still have to pick a baseline date (eg 2000) where we cannot create stream calendar dates any earlier.

If we just use logdate as to generate a stream calander date then there will be a mass event of about 400k ascents created in one day in 2010 (when the system was ported). Some people will have thousands of ascents in one stream event. I think this will break some performance assumptions.

I understand that it is an issue and that we can reduce the scope of the retro generating to just ascents. But it is too much work to tackle in the next week. It is a significant unexpected work load.

We need to also sort out all the business logic before I start one line of code. What are the workable business rules for the retro grading. In particular how do we map to stream calander date.

**Comment by brendanheywood** [comment]
An ascent can be any time in the past, it looks like there is a bunch of crap data in there.

mysql> select CreateDate,LastUpdated,MySQLDate from Ascent  where MySQLDate is not null order by MySQLDate asc limit 20;

```
+------------+-------------+------------+
| CreateDate | LastUpdated | MySQLDate  |
+------------+-------------+------------+
| 1438481880 |        NULL | 0006-06-02 |
| 1419835700 |        NULL | 0006-12-16 |
| 1405201719 |        NULL | 0012-10-07 |
| 1404968676 |        NULL | 0014-06-26 |
| 1404968732 |        NULL | 0014-06-26 |
| 1404968757 |        NULL | 0014-06-26 |
| 1404968786 |        NULL | 0014-07-04 |
| 1408049441 |        NULL | 0014-08-09 |
| 1423448973 |        NULL | 0015-12-06 |
| 1420485855 |        NULL | 0200-01-05 |
| 1426387336 |        NULL | 1883-00-00 |
| 1338616833 |  1381363152 | 1902-01-01 |
| 1338616833 |  1381320156 | 1902-01-01 |
| 1338616833 |  1381336717 | 1902-01-01 |
| 1338616833 |  1381357619 | 1902-01-01 |
| 1338616833 |  1381355256 | 1902-01-01 |
| 1338616833 |  1381329415 | 1902-01-01 |
| 1338616833 |  1381341104 | 1902-01-01 |
| 1338617108 |  1381328732 | 1902-01-01 |
| 1338617108 |  1381321606 | 1902-01-01 |
+------------+-------------+------------+
```

In hindsight if we'd gone with separate records for each year with flags for months this issue wouldn't exist. I'm wondering now that we are using date ranges which are quite fast whether we could get away with a hybrid query for ascents which just looks at the ascents table only and not the huge bitmap? I don't like the idea of generating bits back 100 years but maybe it's not an issue. Also how would this behave if someone edits an old ascent?

**Comment by scd** [comment]
Yes, we designed the filter based on the assumption we were not going to retro generate. Hindsight is a wonderful thing.

Hybrid query will not be simple because all the streams code assumes there is an event with an event id in the background.

The problem which concerns me more is that these ascents will be missing from peoples personal streams. The ascents associated with routes is equivalent to a facet ascent search, which may be better anyway.

Editing an old ascent will not be a problem because we don't have any activity logging associated with this at the moment. When we do we will be associating the update with todays date and creating a new event, similar to the way we update routes. So no problems.

The major pain is that somebody is soon going to realise they cannot go back through all their ascents (pre 2010) using their stream.

My thoughts are that we bite the bullet and retro generate all ascents using the following rules:
 - [ ] use a derative of the log date not ascent date. This means that they will look like a tick event logging ascents from the past (in otherwords matches an existing pattern).
 - [ ] an extra field to indicate that it was a retro generated event so we can deal with this differently in the display if necessary (eg display the calendar date differently)
 - [ ] before we generate retro events try an make some sort of logical grouping of ascents. Make sure events are created in the right order. Where we can identify different groupings within a crag then assign consecutive dates (day 1, day 2, day 3) so at least separate events are created for each logical grouping.
 - [ ] where there are more than X number of ascents in an event split into separate groups. 
 - [ ] research whether a recent stream event create date will cause problems for retro generating.

I agree with you that the important thing is that the actual ascents are there, in a semi logical order. I don't think that it matters too much how they are grouped in events. There will always be issues about event grouping, so I don't think we should worry too much about that.

**Comment by brendanheywood** [comment]
> before we generate retro events try an make some sort of logical grouping of ascents. Make sure events are created in the right order. Where we can identify different groupings within a crag then assign consecutive dates (day 1, day 2, day 3) so at least separate events are created for each logical grouping.

I'm a bit lost on this one, shouldn't the logic for this be exactly the same as new events?ie group by crag + date + user? Consecutive days climbing will become different events the same as now

>  where there are more than X number of ascents in an event split into separate groups.

Again, why would this be any different to now? We don't split large tick sessions into groups today so why would be retro do it for the past?

**Comment by scd** [comment]
The main problem I see is that some users will have 2000+ ascents to retro generate events for, and I was thinking of the situation where there were lot's ascents for one crag. Upon reflection it is unlikely that any user has more than a couple of hundred ascents pre 2010 for one crag. This is probably not a major performance issue. I just did not want to create a single event with say 1000 ascents in it.

**Comment by brendanheywood** [comment]
This seems like a close (N4 ~= tlc but not really) enough query to see how bad this is:

mysql> select N4 as crag, Account,count(*), from_unixtime(Date) Dated,MySQLDate from Ascent group by Account,Date,MySQLDate,N0,N1,N2,N3,N4 having count(*) > 200   order by CreateDate desc;

That brings up 68 records, is it's > 100 that goes to 262 records.

If we strip out the ones which don't have any MySQLDate then this drops down to just 28 records.

Also fyi I'll be in sydney for the next couple days for work

**Comment by scd** [comment]
This is pretty old and I don't think we will ever get around to generating missing stream events. Closing for now, but may re-open if it ever becomes really important to create historical stream events.
