### ISSUE TITLE
Create timezone field for nodes from gps maps location

### ISSUE THREAD

**Issue by scd** [theCrag/website#2083]
We have got a perl module which does lat/long to timezone conversion, but I think it suffers from potential inaccuries. For example I had to edit the perl module to stop it crashing for some lat/longs (actually out of the box it crashed on about 25% of lat/longs). It uses boundaries and I think potentially suffers from holes. 

The timezone stuff does not need to be 100% accurate +-2hours is fine. This means that we do not have to take into account daylight savings and we can also be one or two boundaries off. This means that getting timezone information for the lat/long centroid of one level down from country (ie state) should be ok.

It would be preferable if we used an accurate API service such as Google. We do not want to do this on-the-fly because of lag delays in time critical processing and usage charges. We should store timezone on nodes for speed and transparency purposes.

For example with google's API free limits we could populate all the nodes in a couple days (2500 api calls per day) and almost never refresh them, maybe once a year.

https://developers.google.com/maps/documentation/timezone/usage-limits

It would be interesting to compare Google API results with our Perl module. 

For transparency purposes admin needs to be able to see it. But because we are not taking into account daylight savings it should not be publicly viewable as we will get a lot of feedback on wrong times that are within the acceptable margin.

Actually we probably want to adopt a generic model where the node time zone is retrieved from the closest ancestor. If we allow admin to manually set the timezone, but also allow auto set from Google API. Two fields will do this

APITimezone
Timezone

Use the Timezone if present, otherwise use APITimezone.

**Comment by brendanheywood** [comment]
If we get the inheritance right, then in almost all cases we should only set a timezone at the country or state level, and never bother at the crag level. So this should be even simpler and more like a few hundred data points. I don't think we need any api calls and I don't think we really need to maintain it that much either as it will only ever change by small amounts and we can safely be off by a few hours. We should be able to grab just about everything we need from this single table:

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by scd** [comment]
This was done a while ago.
