### ISSUE TITLE
reduce the number of location items before triggering summary mode

### ISSUE THREAD

**Issue by scd** [theCrag/website#2089]
If more than 3 locates then streams should trigger summary mode for an event.

Although the following individual event will never trigger summary mode, the following event should be in summary mode when in a full stream:

https://www.thecrag.com/event/753770715

**Comment by brendanheywood** [comment]
Thoughts: ?

![image](https://cloud.githubusercontent.com/assets/187449/10158980/af7e8b8e-66d8-11e5-94fe-10883e572470.png)

**Comment by scd** [comment]
+1 for desktop. Mobiles?

**Comment by brendanheywood** [comment]
This would just be inline block wrapping, and only partially solve it. I think in combination with a 'more' / 'less' hiding thing that would be fine. Maybe only trigger the cut down summary if there is a heap of them, maybe 10+

**Comment by scd** [comment]
I have implemented the inline block stategy in simons dev. I think there is another issue which covers the more/less buttons.
