### ISSUE TITLE
Add "view all ascents" to crag listings

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2090]
I very much like the new "view all ascents of this route" button in the stream. Would it be possible to include it also in the crag listings button pulldown? Currently this function can only be reached via a stream, or by selcecting the route and then viewing ascents with beta (in fact, this is the interesting function).

**Comment by scd** [comment]
Ok we can do this

**Comment by brendanheywood** [comment]
Yup, I'm in it right now, or have you beat me to it?

**Comment by brendanheywood** [comment]
![image](https://cloud.githubusercontent.com/assets/187449/10163151/2155ce3c-66f4-11e5-874d-0c8f405b900c.png)

done
