### ISSUE TITLE
self service advertiser account/settings-advertiser page

### ISSUE THREAD

**Issue by scd** [theCrag/website#2094]
I think we need a self service advertiser section for gyms and advertisers.

This will eliminate bank end work on my side of things. 

Workflow something like 
- [ ] gym owner/advertiser signs up to theCrag as a normal user, then subscribes to monthly subscription.
- [ ] Somewhere in a settings page they click a button to enable themselves as an advertiser/gym account. This will trigger the creation of the gym and/or advertiser organisation and associate the account with that organisation.
- [ ] A /settings-advertiser page will become available to that account which will allow the advertiser to update their own details. Note that if they are not a premium account then they will not be able to update these details.

Advertiser details include:
- [ ] Business name
- [ ] Business directory info
- [ ] Administration contact info
- [ ] Logo avatar style
- [ ] Web advertising image
- [ ] PDF advertising image
- [ ] Gym node if gym
- [ ] Advertising node

**Comment by rouletout** [comment]
This is off the table for now, current process is well established and works fine, closing
