### ISSUE TITLE
'BR' should be another black listed route name for autolinking

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2098]
http://www.thecrag.com/climbing/australia/blue-mountains/the-zigzag/route/144909048

ie should only auto link if quoted:

http://www.thecrag.com/climbing/australia/blue-mountains/the-zigzag/area/579088821

![image](https://cloud.githubusercontent.com/assets/187449/10260072/bffebfdc-69b3-11e5-8379-f26302c2d5b9.png)

**Comment by scd** [comment]
hotfixed
