### ISSUE TITLE
add table for who somebody climbs with in their profile

### ISSUE THREAD

**Issue by scd** [theCrag/website#2101]
In the spirit of the avatar train in events, I now want to know who each person climbs with as an aggregate summary when I visit their profile page.

The ascent count should link to all the ascents that that person has climbed with.

I think we should include plain text who with people as well to encourage this to be updated when somebody creates an account on theCrag. You should be able to get to this list via a facet search.

**Comment by brendanheywood** [comment]
This would overlap quite a lot with who they are following, perhaps just extent that with another section for those that they have climbed with, but don't follow so we're not duplicating.

**Comment by scd** [comment]
There are some other factors that I think are worthwhile taking into account, which may not be convenient to add as an extended list of people they are following. 

 - [ ] ascent 'with' fields that do not use mentions. In other words you might climb with somebody who does not have an account so you just use their name. Or they may have an account and you have not linked them yet.
 - [ ] see the number of ascents you have done with that person and link to the facet
 - [ ] see the people you boulder with versus the people who you free climb with (ie use the profile filter)
 - [ ] just show the top 10.

This is leading to bulk update of with field.

Also Simon's ascent facet of ascents that I have climbed with Campbell should match Campbell's ascent facet of ascents that he has climbed with Simon. Having tools to compare is the first step. Eventually we could recommend.

**Comment by brendanheywood** [comment]
Yeah I'm just hesitant to add more to the profiles which I already think are quite bloated. eg right now we have recent ticks on the right, and the stream on the bottom, which for someone who only ticks and doesn't edit these two things are identical. 'Recent ascents' should be removed completely at some point. 

If we can properly integrate both the 'following' and 'involved' concepts together in some new way I think that would be better than simple adding a new extra section.

**Comment by scd** [comment]
What about fitting it into the climbers facet?

**Comment by brendanheywood** [comment]
Extra climber facet filters has zero downside (unless they are super slow) so no objections there

**Comment by brendanheywood** [comment]
Done
