### ISSUE TITLE
Weird discuss event where I can't see the discussion

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2105]
https://www.thecrag.com/event/758994201

![image](https://cloud.githubusercontent.com/assets/187449/10296546/3891b284-6c15-11e5-8c29-1158f5074ad8.png)

I can see that it is a duscsion, and that you are involved, but can't see the discussion. it should be all or nothing (if private)

**Comment by scd** [comment]
already logged in #2104 

I know what it is- starting a discussion directly on a photo.

**Comment by Mdemaillard** [comment]
Closing as #2104 is closed.
