### ISSUE TITLE
Stream duplicates of topos?

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2107]
These are all edits on the same topo by the same person on the same day but appear as multiple stream events:
![image](https://cloud.githubusercontent.com/assets/187449/10299378/2be49e0a-6c35-11e5-844b-1a8895dce080.png)

http://www.thecrag.com/event/757255767
http://www.thecrag.com/event/757259742
http://www.thecrag.com/event/757257525
http://www.thecrag.com/event/757257108
http://www.thecrag.com/event/757255737

I'm wondering whether this is because its an area topo and the areas in the topo are crags so each edit is aggregated at the lower crag level instead of the region level. If this is the case then perhaps any topo edits should be calculated using the topos parent node and not the node that was edited? In many cases these with both cascade up to the same crag anyway, it's only when we have a 'region' level topo that this would differ. Do we have clear business rules for aggregating events which are higher than a TLC? Does each event just not look 'up' any further and just stick with whatever node it is on, whether an area / region?

**Comment by brendanheywood** [comment]
Hmm, I think this area just doesn't have any crags at all so could be considered a data issue, but the above I think would still be an issue?

**Comment by scd** [comment]
Yes your explanation I think is correct. If the data is set up correctly I think having a topo across multiple top level crags will be fairly rare.

**Comment by Mdemaillard** [comment]
That was an edge case.
Mutiple topo edits seems aggregated now:

![image](https://user-images.githubusercontent.com/60388146/76520761-35cb8f80-646c-11ea-8534-5fe4840e534a.png)

Candidate for closure
