### ISSUE TITLE
Stream event title links to route not area and is broken

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2108]
eg 'Radical departures' should actually be 'Bell Super Crag'
![image](https://cloud.githubusercontent.com/assets/187449/10321372/03851f68-6cc4-11e5-91b2-ba80d3273910.png)

it links to this which is broken:
http://www.thecrag.com/climbing/australia/blue-mountains/shady-side-upper/area/422657622

it should be:
http://www.thecrag.com/climbing/australia/blue-mountains/bell-supercrag

Note the summary in the event page is different:
http://www.thecrag.com/event/758397693

The discussion one is broken:
http://www.thecrag.com/event/758935395

**Comment by scd** [comment]
I bet the discussion is associated directly with the 'Radical departures' route. Probably some piece of logic I had not considered when building a virtual discussion event. Note to self, to first check logic associated with logging a discussion directly with an ascent.  If this is the issue see also related issue #2104 which is also a broken use case with direct discussions on photos.

**Comment by brendanheywood** [comment]
If I tick 5 routes, and then someone comments on the event, and then 2 other people comment on 2 individual ticks, do we end up with 3 discussion events? There seems to be a class of issues around the event vs event discussion(s), ie in FB land they are one and the same. One of the things we need to thrash out is how comments should work on an event which is shown in two contexts, which means two subsets of the event are shown.

**Comment by scd** [comment]
They are all associated with one discussion event (at the activity level), however the route message is directly linked either to the ascent, photo or event (at the message level).

Yes there could be an issue with comments in different contexts. I think the big problem here is that event date is updated. Let's wait until we have a couple of real world examples before we solve this one.

**Comment by scd** [comment]
fixed on simon's dev.

**Comment by scd** [comment]
fixed on simon's dev.
