### ISSUE TITLE
streams on smart watch app

### ISSUE THREAD

**Issue by scd** [theCrag/website#2111]
A friend has just shown me his new kickstarter pebble smart watch. I must confess I was surprised at it's simplicity and how well it has been put together (water proof and visible in sun glare).

https://www.pebble.com/ 

I recon putting our streams onto an app would be pretty cool and fit in really nicely with the paradigm.

They have development SDK, C and javascript. I think they already have RSS, but our RSS is public feed stuff only. 

I think it should be fairly straight foward to build an app which presents our stream content. Need to work out user authentication.

**Comment by brendanheywood** [comment]
Meh. It could possibly be cool, but I reckon it's like 669th down the line in terms of priorities. Why do pebble before Apple Watch? Why do a watch app before a mobile app? And we can easily make a private rss through a revocable random token in the feed url.
