### ISSUE TITLE
Do we want to make our location data available to Android Locus Map

### ISSUE THREAD

**Issue by scd** [theCrag/website#2112]
An idea from a user.

http://www.locusmap.eu/

**Comment by brendanheywood** [comment]
It has gpx import, they can use this now

**Comment by DorienCragen** [comment]
Hi, was thinking not only about put cords on map, but do some sort of api, that connents two application to see topos in locus map, guide to destination in forest, mark routes that you have been done also from locus map, it allready have integration with geocathing service on similar level

**Comment by scd** [comment]
What you described is the app we are building (re-building).

**Comment by DorienCragen** [comment]
app for android? if that so i cant wait for it :D, locus have advantage of offline map and awesome navigation tool

**Comment by scd** [comment]
iOS and andriod. We had an andriod app out for a couple of years, but it ended up being too difficult to support and was causing some problems so we had to pull it at the beginning of this year. The app is high on our priority list, however it will take time while we try and sort out our development resources.

**Comment by rouletout** [comment]
Nothing we will pursue in the mid term, closing
