### ISSUE TITLE
Archived and actual gym route with the same name

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2113]
When I try to add a route named "Alter Schwede" to this gym line http://www.thecrag.com/climbing/germany/oberbayern/area/612818169 , I get the error "Climb name already in use as child network node". In fact, this is the name of an archived route from about a year ago, now there is a new one with the same name (I know, in theory I have to blame the routesetters)...

**Comment by scd** [comment]
fixed on simons' dev
