### ISSUE TITLE
Stream broken in prod with image embed issue

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2115]
![image](https://cloud.githubusercontent.com/assets/187449/10561980/c1863366-758f-11e5-9b57-8daf6ff48158.png)

http://www.thecrag.com/climber/brendanheywood/stream?embed=off

Apache Module Load Portal Error: Error: Error generating image URL: no volume provided at /opt/CIDS/perllib/CIDS/Application/WebHelpers.pm line 592. Stack: [/usr/local/share/perl/5.14.2/CGI/Carp.pm:379] [/usr/local/share/perl/5.14.2/CGI/Carp.pm:468] [/opt/CIDS/perllib/CIDS/Application/WebHelpers.pm:592] [/opt/CIDS/cgi-bin/templates/html/thecrag/minor/phototopo:79] [/opt/CIDS/cgi-bin/templates/html/thecrag/stream/event-update:159] [/opt/CIDS/cgi-bin/templates/html/thecrag/stream/stream:109] [:104]

**Comment by scd** [comment]
this was actually me accidently removing apache write permissions to the temp directory yesterday fixing something else. I did not realise I did this, and it took a while to hunt down. What it meant was that all uploads were broken, causing corrupt data. Hot fixed now.
