### ISSUE TITLE
Miss spelling of principal grade

### ISSUE THREAD

**Issue by scd** [theCrag/website#2119]
From Kieran L.

When reporting a grade update, TheCrag refers to the "principle grade". This should be "principal grade".

Principle is a noun for a rule or tenet and cannot be used as an adjective.

Principal can be both a noun and an adjective. As an adjective it refers to the main or primary instance of something - as in this case.

**Comment by Mdemaillard** [comment]
Stream / Activity
![image](https://user-images.githubusercontent.com/60388146/77196904-e7159980-6aec-11ea-904c-cffed6cae4c1.png)
Route page
![image](https://user-images.githubusercontent.com/60388146/77197174-63a87800-6aed-11ea-8844-297720b91bc4.png)

i can't find this wording anymore. candidate for closure, or need an URL.

**Comment by rouletout** [comment]
yes, closing
