### ISSUE TITLE
Error when deleting image

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2121]
I deleted an image, which apparently succeeded. I got an result page whoch I could only leave via a "Cancel" button, resulting in the following error message:
Apache Module Load Portal Error: Error: Error generating image URL: no volume provided at /opt/CIDS/perllib/CIDS/Application/WebHelpers.pm line 592. Stack: [/usr/local/share/perl/5.14.2/CGI/Carp.pm:379] [/usr/local/share/perl/5.14.2/CGI/Carp.pm:468] [/opt/CIDS/perllib/CIDS/Application/WebHelpers.pm:592] [/opt/CIDS/cgi-bin/templates/html/thecrag/minor/imageUrl:40] [/opt/CIDS/cgi-bin/templates/html/thecrag/minor/photoLink:44] [:81] 

I have to admint that I probably screwed up before: I uploaded a photo. In the photo naming dialoge I noticed I picked the wrong one. So I went back using the browser back button (shame on me) an uploaded a file of the same name again, which already threw some error message ("back to start of process").
Thus, I suggest to include a "discard" button in the photo naming dialogue.

**Comment by scd** [comment]
Is there any persistent issue with the photo not being deleted or in a bad
state

**Comment by MelwinQ** [comment]
I couldn't reproduce it, so I guess adding the "discard" button would solve the problem

**Comment by birgander2** [comment]
I had the exactly the same problem yesterday. The photo seems to disappear, but then I ran into a bad state with all photos away and back after a while (except the deleted one).

**Comment by scd** [comment]
About two weeks ago I made some changes in this area, but it has not been released. I was fixing some things with the way we are changing how images are being treated. Let's wait until after the next release and if the problems are still there then I will look into it further.

**Comment by Mdemaillard** [comment]
tried pretty hard on some pictures in test area on prod - cancelling, "back" browser function and forth,... couldn't generate a back state.
Closing
