### ISSUE TITLE
FR_alt grades of ascents "disappear"

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2124]
When ticking routes with a FR_alt grade, everything seems correct first, but the recorded ascent has no grade at the end. [Example here](http://www.thecrag.com/climbing/spain/mallorca/route/381040602): See ascents of 1st November.

It can also not be entered again by edit ascent, as FR_alt is missing in the list.

**Comment by birgander2** [comment]
It is stange as I just saw that somebody else logged the same route and I see everything correctly for his ascent, but not for the one of us. I'm sure I haven't unset the ascent grade.

http://www.thecrag.com/climbing/spain/mallorca/cala-magraner/route/14164915

P.S: You put your comments into the wrong issue. And take your time!

**Comment by brendanheywood** [comment]
@birgander2 is this still happening? I didn't quite follow the comments above and not sure if they are still current

**Comment by birgander2** [comment]
I don't think so. At least I haven't encountered it recently and a quick test did not show any problem.

**Comment by brendanheywood** [comment]
ok thanks well if it crops up again please make a new issue
