### ISSUE TITLE
Crag topo only displays first word

### ISSUE THREAD

**Issue by Ce-e** [theCrag/website#2127]
One for you Brendan - seems like a crag topo will only display the first word of labels.
https://www.thecrag.com/climbing/australia/mount-wellington/organ-pipes

ie "The Columns" is labelled as "The"
Not sure if this is site wide.

On a side note, also doesn't seem to be a way to delete these labels from the topo once they are put on.

**Comment by brendanheywood** [comment]
Yup should be simple to fix. The label can be edited to add in the proper name, or to remove the whole shape just unlink it from the able under the topo in the editing page.

I've just done a cleanup of that particular topo:

![image](https://cloud.githubusercontent.com/assets/187449/11329568/eb529580-91f1-11e5-86e0-ecce4e4aa38a.png)

**Comment by brendanheywood** [comment]
Fixed, was a tiny escaping bug - thanks Chris! how goes the summer of sendage?

**Comment by Ce-e** [comment]
Thanks Brendan, figured it was small but worth reporting. Summer is going
well! Not sure if I'll be ready for the totem pole this year, but am
gradually working up the grades!

How are den and Nora?
