### ISSUE TITLE
Changing default sort order of ascents facet to ascent date and then logged date if missing

### ISSUE THREAD

**Issue by scd** [theCrag/website#2129]
A user has suggested that we consider changing the default sort order of a facet to ascent date

http://www.thecrag.com/climbing/europe/ascents/?sortby=when-climbed,desc

**Comment by nicHoch** [comment]
+1
Am 26.11.2015 21:49 schrieb "Simon Dale" <notifications@github.com>:

**Comment by birgander2** [comment]
You mean oldest first? In this case: -1

**Comment by brendanheywood** [comment]
The current setting is create order which in almost all cases is the same order so should be fine (and is also newest first @birgander2 )

If that particular url is the only example where this isn't working then look at the date, it's set with a future date of 2016. So I don't think anything needs to happen here, but ultimately we should kill the ability to set ascents in the future, probably at the same time we implement route wish lists #1318 and kill the target ascents

**Comment by ajfclark** [comment]
+1

Sorting by date logged seems a bit weird.

**Comment by brendanheywood** [comment]
Prior to the streams concept it made more sense to be a log of updates. I think it would be fine to swap this to ascent date instead of log date as long as ascents without a date continue to inherit log date as their assumed ascent date

**Comment by brendanheywood** [comment]
This was done a release or two ago, probably a duplicate issue somewhere
