### ISSUE TITLE
We need email notification when application server is broken

### ISSUE THREAD

**Issue by scd** [theCrag/website#2132]
If the app server daemon goes down it effects uploading images and pdf creation as well as some other stuff. 

Maybe we should have a cron job watcher which does something like

```
./cids-client version
```

which tells us if we can connect to the daemon

**Comment by brendanheywood** [comment]
I'd look into a local instance of nagios / icinga as it does more of the hard work and then just point it to look at log files or whatever we need it to

**Comment by scd** [comment]
Not such an issue anymore as some critical stuff has been re-arranged.
