### ISSUE TITLE
Xmas wishes

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2133]
Dear theCrag team, it was a pleasure to use your site the last year, it is getting better and better! In the following I have assembled some wishes the the magic Santa Claus developers -not bugs, just some ideas for further improvment:
- [ ] Better ways to do various "statistics" on the profile page. Some examples: select year and get the tree and notable ascents for only that year. Check your outdoor sport performance (excluding indoor) and similar. This should not require tweaking your profile filter defaults. Set perferred system for sport and boulder independently. Many things are somehow there, but lots of improvements are possible here. I have the feeling that many of them don't require much effort, just some redesign of how things are presented and can be configured.
- [ ] An idea for the theCrag labs: You already have these buissiness cards (btw. the colour lines are missing when you click on "print"). Another convenient option would be to print stickers or half page printouts based on a certain region / crag. This should include the link (and maybe a QR code) and a short text "Supercrag on theCrag" & "Collaborative climbing" or similar. This could be used to make some advertisement, in gyms, campings, pin boards in areas where theCrag is not so well known as in Australia.
- [x] Slash grades for UIAA. They are not good but very common and used in almost every topo I have. The "8+ to 9-" version is not the same and causes problems when ticking a routes - you have to decide for one or the other.
- [ ] Nicer display of grades out of context. Here (Germany) a route with french grades are either printed as "FR: 8-" or "{FR} 8-", while a very commong standard used by many topos (even in contries with french grades) is to write "F8-". Same for Fontainebleau grades: "Fb7A+". At least the ":" should be removed when having system explicitly set to "FR 8-".
- [ ] Include "bob point" as an aspirational ascents, ideally with the Bob (Dobbs) symbol. I already wrote you a description in another post. It is only something funny, but it's about climbing and a quite common expression. In fact, I even learned it from some Australians!
- And of course: keep on the good work!

**Comment by scd** [comment]
Nice list. Some quick points for discussion:
  * We recognise that there is still work to do on the profile page. We want to completely disassemble it and rebuild as disctinct components which can exist in their own right, be attached to other facets, not just profile page and be embedded in external pages. Before I do that it might be worthwhile looking at what improvements could be made without putting a lot of work into it.
 * Yes, for stickers. Nicky has done a generic sticker already. Maybe we can publish that. Also another sticker idea is mini profile stickers to label your gear.
 * I now agree that slash grades should be implemented as you suggest.
 * Usually "{FR} 8-" grade presentation means that the wrong context is being used or there is some sort of deficiency in the system I should know about.  Maybe we can open a separate issue for these and knock them off one at a time.
 * I did not know about the 'F8-' standard. There might be a bit of work in this.
 * We are going to remove aspiration ascents into wish lists. There is a plan here.

:)

**Comment by brendanheywood** [comment]
hi @birgander2 - most of these are either done or already logged elsewhere. If you feel I've missed something can you please make 1 new issue per real issue so it's easier to track. thanks as always :)
