### ISSUE TITLE
Topo tool: additional point type

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#2134]
At the moment, the only point types for protection in the topo tool are "bolt / ring / hanger", "carrot bolt" and "fixed piton".

I would wish for an additional point type indicating an optimal placement for a sling. More specifically, I am targeting http://www.thecrag.com/climbing/germany/frankenjura where most routes are bolted sport climbs, but it is very common that there are fixed slings in place if there is a solid rock tunnel, completely replacing the bolt.

As it is now, merely looking at a topo might suggest huge distances between two bolts, when in reality there is a sling in place between them which you cannot see clearly on the picture. And even when the sling is not present or deteriorated so much that you don't trust it, a symbol in the topo helps us sports climbers decide what gear to take.

To my knowledge, symbols for rock tunnel slings ("Sanduhren") appear in all the available printed climbing guides of the area and I guess that Frankenjura is not the only region which could benefit from this. The symbol usually looks like webbing tied off with a knot.

**Comment by brendanheywood** [comment]
hi @quaestor can you please provide a couple pics from various books so I can see what the icon would look like. Once I have a good icon sorted adding this is pretty trivial.

**Comment by quaestor** [comment]
Hey @brendanheywood, sure! Here's three examples:

One from the public route database at frankenjura.com:
![sling_fj](https://cloud.githubusercontent.com/assets/54371/11928594/fcd5decc-a7d4-11e5-8f3a-ee4459cbab21.png)
One from the books by the publisher "Panico":
![sling_panico](https://cloud.githubusercontent.com/assets/54371/11928595/00db192e-a7d5-11e5-87ef-12292e020f57.png)
And one from the books by the publisher "Gebro":
![sling_roeker](https://cloud.githubusercontent.com/assets/54371/11928598/044678ce-a7d5-11e5-8450-f7f855bf8ec8.png)

**Comment by brendanheywood** [comment]
Ok I've done this in our development system, you can see an example topo here:

http://dev.thecrag.com/climbing/germany/frankenjura/burglesauer-wand/area/448189908

![image](https://cloud.githubusercontent.com/assets/187449/11930141/03dc289c-a835-11e5-9aad-dbf9b11c9db7.png)

Please have a play in that test system, but note that everything there will be deleted as some point so don't do any real data entry.

This will get bundled into the next release, roughly every month or so but not sure what @scd's plans are over the break re releases.

**Comment by quaestor** [comment]
@brendanheywood Looks great! Two minor points:
* I would scale down the symbol a tad since it looks a bit large in comparison to the others.
* The description of the point type is now "Thread / Sanduhren", but "Sanduhren" is plural, so it should be "Thread / Sanduhr"; my bad ;-)

**Comment by brendanheywood** [comment]
done and done and also fixed the rounding on the end of the lines.

![image](https://cloud.githubusercontent.com/assets/187449/11931030/12af41c6-a83d-11e5-9e26-ed8bbdcbcb69.png)

**Comment by nicHoch** [comment]
Hi Brendan

that was a very fast resolved issue. Maybe you are on the run right now 
- could you consider to add also 2 more point types:

  * Friend (cam)
  * Nuts

I do not think that it is very common in pure trad regions to draw 
details topos with all possible placements. But in more mixed and 
sportclimbing regions it might be very helpful to know where the one 
crucial additional cam is expected.  An absolute nice to have 
enhancement  would it be to add a label to points - for example: C3.

Nicky

**Comment by brendanheywood** [comment]
Yes it was fast, but that's kinda the luck of the draw sometimes :) 

Adding a new point type is really trivial,  2-3 lines of code. Adding an arbitrary text label is definitely on my todo list but not as easy, mostly covered in #1614. I'm a little hesitant to add cams / nuts as point types as there is a lot of arbitrary judgement with trad placements - my rule of thumb is if it is something commonly done in published guidebooks then I'll try to add that capability, so if you can show me some photos of real life examples I'll consider it. Perhaps both of these would be better done as the arbitrary text labels instead of new point types anyway?

**Comment by nicHoch** [comment]
I do not have any topo example  with a specific friend/nut symbol only some
with text labels as "C3". So the free label will solve that issue.

Nicky
Am 21.12.2015 23:27 schrieb "Brendan Heywood" <notifications@github.com>:
