### ISSUE TITLE
Ctrl+click when editing topos deselects the node being edited

### ISSUE THREAD

**Issue by oliverstory** [theCrag/website#2136]
When editing a topo it is possible to hold down Ctrl while clicking on a node. This disables snapping (very handy, thank you). A side effect that seems to be a bug is that the node being edited loses its 'selected' status (outline changes from blue to white - but still moves around with the mouse as expected), and instead some random (?) node on the route line becomes selected. This means that next time I click on the topo to create a new node, the node is inserted after the randomly-selected node rather than extending the end of the line.

**Comment by brendanheywood** [comment]
Yeah I've come across this too but found it hard to nail down exactly what triggers it. I just tried again with your instructions and couldn't make it break. Can you reproduce it on any topo? If so what browser you in? If not and it is only certain topos or certain routes on topos can you give me those?

**Comment by oliverstory** [comment]
OK I've narrowed it down. The bug doesn't occur if you haven't right-clicked on any nodes during that topo editing session. The node that steals the focus when you press Ctrl is whichever one you last right-clicked on (e.g. to set it to a 'belay' or number label). You don't seem to need to actually set anything, just right clicking is enough. 

It seems to persist across route lines as well - so if I right-click on node #2 on route A, then deselect that route, select route B (the last node gets the focus), press Ctrl and node #2 on route B takes the focus. 

Also persists between topos if you're editing two at the same time and switching between them.

It also happens if I press Shift or Alt (causes unexpected behaviour when for example Alt+Tab to another window).

I'm using Chrome on Ubuntu (haven't tried other browsers).

**Comment by brendanheywood** [comment]
Alrighty then, fixed! Thanks heaps for the awesome testing, I would not have got to the bottom of this without it :)
