### ISSUE TITLE
Stream does not shows events that did happen

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2137]
Probably already known: it seems, the stream can show edit activities that actually did not happen.
[See here for an example](http://www.thecrag.com/event/815871810) and follow the discussion. Obviously Max Stein just only added a tag to the area, but did not edit the routes. And for curiosity: what is shown here? Some old edits?

On a side note: Are multiple grading systems wanted or not (e.g. "6c, AU: 21"), or should one stay only with the local one? The first one might help tourists, while the second one is more "clean".

**Comment by brendanheywood** [comment]
Yeah seems legit that he didn't change the other stuff so this is a a bug in the feeds.

Re grades, I don't think we have, or should have, a global preference, some areas are dual grade, others make you learn their grade system. So as long as each crag or region is internally consistent I don't mind and would leave it to the locals

**Comment by birgander2** [comment]
And: streams do not show events that happened. [Example here](
https://www.thecrag.com/climbing/germany/oberbayern/area/400652451). Last event of mine was on Dec 28th, and at that time only topo 3 and 4 have been there. Today there are 6 (nice!), but no stream event about the updates.

**Comment by Mdemaillard** [comment]
renamed as original problem better captured in #3451.

**Comment by georg-d** [comment]
https://github.com/theCrag/website/issues/2000

**Comment by scd** [comment]
dup
