### ISSUE TITLE
retrobolting causing style inconsitencies for historical trad ascents

### ISSUE THREAD

**Issue by scd** [theCrag/website#2139]
From user...

"So ... for retrobolted trad routes defined as "sport" (ugh) so that filtering to sport will find them, is there any way to indicate that an ascent was done in the original style, or mixed if you clipped a few bolts? And have that show up in stats?

Can we perhaps have a "greenpoint" ascent style added? I have a number of NZ routes in mind to have a go at

**Comment by scd** [comment]
... also from John,

"I was thinking that perhaps the route style needs to allow multiple selections - so that if a route is marked as trad and sport a search for trad, mixed or sport will each find the route - then the user selects which style it was done in when logging an ascent. Perhaps there could be a default style setting for the lazy

**Comment by Macciza** [comment]
I would certainly like a 'Greenpoint' option 

And it would be great to have a 'Mixed' option for trad/bolted routes

Cheers

**Comment by Mdemaillard** [comment]
- [x] implement Tick types as green point & green point onsight
Green point ascent count toward Trad CPR and not sport
- [x] mark a route defined as trad but with bolt >0 as Mixed trad
"mixed trad" routes are excluded from search with "sport" style, included in "trad" style, and exclusively returned in "trad" style with additional misc flag "bolted"

The common ascent types do not distinguish between sport or trad style, so i guess CPR is assigned according to route style, at the moment of the ascent recording ? How are handled ascents from an originally trad route, modified later as sport route after retrobolting ? I assumed not changed retro-actively.  
This is slightly edge case, but changing route style might be a candidate for pop-up "are you sure, this change would impacts x previous ascents"

**Comment by rouletout** [comment]
CPR considers ascent style - so green point of a sport route is a trad and a pink point of a trad route is a sport ascent. Closing as the missing green point is available.
