### ISSUE TITLE
Gear type bar in header links are broken after re-filter

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2143]
ie go here:

http://www.thecrag.com/climbing/australia/blue-mountains

click on Trad and you get:

http://www.thecrag.com/routes/at/11741347/with-gear-style/trad/

instead of:

http://www.thecrag.com/climbing/australia/blue-mountains/routes/with-gear-style/trad/

**Comment by scd** [comment]
this seems fixed
