### ISSUE TITLE
deleting a photo removes the original but leaves a cached version somewhere

### ISSUE THREAD

**Issue by scd** [theCrag/website#2144]
original is removed in both static and prod, but thumbor still serves

**Comment by scd** [comment]
note that restarting thumbor the image is still cached

**Comment by scd** [comment]
it seems as though cache is stored in /tmp/thumbor/storage but not so sure how it works

**Comment by scd** [comment]
the cache expires after 2592000 seconds (30 days)

This image should have expired 30 days after this issue was created:

http://static.thecrag.com/img/100x/7c/fd/7cfda3d92cc8846713b9ea9c154f0f533f810411

Check it

**Comment by brendanheywood** [comment]
If we delete an image it should propagate to thumbor. We should also be able to safely purge the thumbor cache at any time

**Comment by scd** [comment]
It was not clear to me what the image was in the cache.

**Comment by scd** [comment]
Closing as I don't plan to do anything more here.
