### ISSUE TITLE
Gym tournament - teams & tick on behalf of

### ISSUE THREAD

**Issue by scd** [theCrag/website#2147]
There are two critical features that are required for the next scheduled gym tournament.
 - [ ] Gym administration must be able to tick on behalf of somebody
 - [x] Competitor must be able to register against a team.

Gym admin is happy to collect competitors theCrag accounts before the tournament and if they do not have one then create one for them.

The tournament organiser sees it as too much of an ask to get people to log into thecrag and log their ascents during the tournament. They want somebody at a dedicated desk to be able to do it for them.

They also want a live leaderboard so they want to minimise the delay in logging ticks.

Here are my thoughts:
 - [ ] Use the normal ticking process with an extra field 'on behalf of' somebody else. The field will be enabled in a gym, where the user has coordinator permissions in the gym and the competitor is registered to an open tournament.
 - [x] Create a Participation table (fields user, tournament, and optional team). Actually I am thinking of using the word initiative rather than tournament so we can use this concept more generally.
 - [x] Add JSON variable to the tournament to indicate that it is for registered competitors only. This will open a registration list and UI for updating the registration list for admin.
 - [x] Add the participates in tournament facet to ascent facets. 
 - [x] Add a JSON variable to the tournament to indicate that teams are enabled. This will open a teams field in the registration list of the tournament and a UI to update.
 - [x] Create a teams scoring algorithm which adds individual scores of the same team. At this stage each individual will have the team score against them in the leaderboard.

**Comment by brendanheywood** [comment]
This might be easier to implement if we made a new UI just for it, the more the add to the existing ticking process the more edge cases we need to keep track of. And doing it as custom will be a much better outcome and can be tailored to this use case

**Comment by brendanheywood** [comment]
Probably get the tick api working with the extra fields and then I could work on something a bit more dynamic like a grid spreadsheet ticking page just for comps

**Comment by scd** [comment]
I am more conerned with what I can do in the time frame.

**Comment by scd** [comment]
Why don't I try and get the thing working as I described which includes the update to the API, then if you have time you could try redoing a UI. That way, we will have the functionality for the tournament, but if you come through then we will have a great new ticking UI for gyms, but you can free yourself from the time pressure and aim for the next tournament.

**Comment by brendanheywood** [comment]
Sure, but work on the api first

**Comment by scd** [comment]
The very last thing to do will be the ticking UI.

On Sun, Mar 13, 2016 at 9:01 PM, Brendan Heywood <notifications@github.com>
wrote:

> Sure, but work on the api first
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theCrag/website/issues/2147#issuecomment-195926320>.
>



-- 
http://thecrag.com/

**Comment by brendanheywood** [comment]
A random thought: how does this affect a users editing rights? Would gym added ticks be uneditable by the climber? I'd say yes, or at least for the duration of the comp, but probably yes permanently to make everything easier.

**Comment by scd** [comment]
I think the main reason why rocksports wants to have gym added ticks is that they don't think it is reasonable for all competitors to self report using a device during the competition. My understanding is that the tournament is still a self reporting tournament, just one mechanism to do it is talking to a human at a table.

For this scenario we want ticks to be editable.

If we do serious gym competitions then I agree, but for social competitions I think we want to leave it as it is.

**Comment by scd** [comment]
It was good to get further feedback from Thomas. He definitely wants gym admin only logging ascents, which puts a stronger focus on providing a different interface.

If we are going to do admin only then we should have a tournament field on the ascents which can only be set by admin logging ascents.

I have built a new UI for registering people, which is already in table form. I think it might be ok to have a tick widget next to each person which lets you navigate to the route on the page and when you select it the route is automatically ticked.

As long as the tick has no other variable properties I am confident of being able to do this in javascript pretty quick.

We would have to enable deleting in case of a mistake.

I am not to concerned about users editing the ascent as they will not be able to increase their score.

**Comment by scd** [comment]
I have got a tournament ticking UI going - pretty cool. I have to do a couple more tidy up things then I will rebuild dev. @brendanheywood are you using dev today?

**Comment by brendanheywood** [comment]
Nope go for it
