### ISSUE TITLE
Add UI to rotate images after upload

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2148]
Now that we can safely rotate images at any time, we need to add UI to fix rotated images eg

https://www.thecrag.com/climbing/japan/area/836068947

and also figure out why this one got borked and if possible do a batch migration to fix current broken ones

**Comment by scd** [comment]
I have manually fixed this. Let's keep an eye on how many times it comes up.

It is not my intention to keep fixing these manually but doing it once or twice manually will be ok as time is not on my side for a proper fix. Hints for tracking down the problem for next time (in this example I changed Rotate from 180 to 90). Get the topo id from topo page, do a join to get the image id, then do the update:
```
mysql  -e "SELECT T.ID AS TID,I.ID AS IID,I.Rotate FROM Topo AS T,OriginalImage AS I WHERE T.ID = 838357599 AND T.OriginalImage = I.ID;" cids
mysql -e "UPDATE OriginalImage SET Rotate=90 WHERE ID=838357734 LIMIT 1;" cids
```

The create date for this topo was 3rd March. I am wondering if there was an issue with having both image formats installed and maybe only one rotation triggered. If this is the case it will have effected all images between the release A (where we converted) and release B (where new images were added).
