### ISSUE TITLE
Hidden fields when entering new cliff

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2149]
When I enter a new cliff (probably other node types, too), the fields "Approach Time From Parking" and "route count estimate" are not displayed. To enter/change them, I have to click "update area details" after finishing the creating of the cliff.
I'd prefer to be able to enter these straight away. Even tag assignment right away from the same form would be nice. currently, I find assigning tags somewhat hidden; it would probably boost the use of them a bit.

**Comment by brendanheywood** [comment]
+1 - the tags was always intended be moved over, that was just an interim place until the wrinkles got ironed out.

**Comment by Mdemaillard** [comment]
has been implemented
![image](https://user-images.githubusercontent.com/60388146/77198450-a703e600-6aef-11ea-883f-532e91d90ad9.png)
