### ISSUE TITLE
UKClimbing Logbook import

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2162]
Support better matching of tick types:

Lead dog -> Dog
Lead rpt -> Lead
Lead dnf -> Attempt
TR dog -> Top rope with rest
Lead β -> Flash
Lead RP -> Red point
2nd -> Second
Lead O/S -> Onsight
Sent -> Tick
TR O/S -> Top rope onsight
TR RP -> Top rope clean
TR β -> Top rope flash
2nd RP ->Second clean
TR rpt -> Top rope
2nd β -> Second clean

**Comment by nicHoch** [comment]
@scd Have you that one on your radar?
A user from Germany would like to import ~500routes from his UK account.
There is no good matching between the ascent types he proposed the one above!

The idea would be if you chose a source during the import (i guess so fare this is just an information for us no actions are tricked to that) that than this matching is used.

Nicky

**Comment by scd** [comment]
That went off my radar, thanks for the reminder. Was that David? I cannot find the email. I would like to ask for his spreadsheet so I can test as I make the change
