### ISSUE TITLE
add api entpoint for ascent config

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2164]
api/config/ascent/ticktypes

api/config/ascents/relativeDifficulty 

api/config/ascents/quality

**Comment by scd** [comment]
I think, for now we have abandoned relative Difficulty. 

I will try and get the others done this weekend.

**Comment by nicHoch** [comment]
of course that has do be discussed elsewhere but i really hope that we 
could bring relative Difficulty back.
Maybe only on the app side for acceptance testing

Nicky

**Comment by scd** [comment]
I will add the relative difficulty config end point.

**Comment by scd** [comment]
I have implemented these end points.

@brendanheywood please pull from repo so nicky access on dev.

@nicHoch can you please close this issue after you see them working on dev. Note that they are all lowercase with the implementation.

**Comment by brendanheywood** [comment]
done

**Comment by nicHoch** [comment]
endpoints working well.
I would like to propose a unified format for all of these 3 endpoint especially with internationalization in mind:
```
{
    "value": "7509568",
    "label": "Don't Bother",
    "name": "dont_bother",
},
```
ascent/quality: does not have a name
ascent/ticktypes: names and labels are inverted
ascent/relativedifficulty: does not have a name

the name should by immutable and used as key in translation files. For convenance we use the name not  the value because it is readable for the translators.

**Comment by scd** [comment]
To align with the database design the meaning of label and name fields are
the other way around.

**Comment by nicHoch** [comment]
yes i know i also struggled with that in the wp-plugin. is it by mistake? For me a label is something that is shown to the public.  or not?

**Comment by nicHoch** [comment]
the grouping of tick types also need label/name

**Comment by scd** [comment]
No it is not by mistake, I just interpreted it exactly the opposite way.
Name is public, label is for code. It was over 10 years ago when I came up
with that convention.  Industry standards may well have gone the other way.

**Comment by nicHoch** [comment]
anyway what counts is consistency internally. So i can cope with the inversion.

**Comment by scd** [comment]
I have altered the end points as you suggested. 

You will soon realise there are many idiosyncrasies with what I have done in the core code base. In hindsight I think I was isolated on the project by myself for too long. Anyway we just have to work with them in the short term and work out a long term solution slowly where necessary.

@nicHoch please review and close when you are ready

**Comment by nicHoch** [comment]
We also need an endpoint for the tag settings:

`api/config/tags`

should include: 
- key(name)
- groupings
- icon best with an url

**Comment by scd** [comment]
I have implemented something here but the end point is

```
/api/config/structured-tags
```

Note that in order to avoid confusion I am distinguish between structured tags and hash tags.

This is implemented only on simon's dev at the moment and will be available after the next release.

It looks like this:

```
{

    "icon": "cids/images/tag-icons_no-fires.png",
    "themeName": "Comfort",
    "appliesTo": {
        "Areas": 1
    },
    "typeName": "Amenities",
    "typeLabel": "Amenities",
    "tagName": "No fires",
    "themeLabel": "Comfort",
    "tagLabel": "No fires"

},

...

{

    "themeName": "Access and approach",
    "appliesTo": {
        "Routes": 1,
        "Areas": 1
    },
    "typeName": "Walk in time",
    "typeLabel": "Walk in time",
    "tagName": "20-30 min",
    "inherits": 1,
    "themeLabel": "Access and approach",
    "tagLabel": "20-30 min"

},

**Comment by scd** [comment]
Actually hold on a sec, the images are on static and the url looks like this:

https://static.thecrag.com/cids/images/tag-icons_drinking-water-1.1.0.png

so I have to do more work to get you the images correctly.

**Comment by scd** [comment]
I had to throw the asset wrapper around the url image. Now you should get something like

```
{

    "icon": "/dev-cids/static/cids/images/tag-icons_dog-friendly-1.1.0.png",
    "themeName": "Comfort",
    "appliesTo": {
        "Areas": 1
    },
    "typeName": "Family",
    "typeLabel": "Family",
    "tagName": "Dog friendly",
    "themeLabel": "Comfort",
    "tagLabel": "Dog friendly"

},

```

**Comment by brendanheywood** [comment]
While I think of it, we should check for any images which contain English and remove it (or localise the images?)

**Comment by nicHoch** [comment]
@scd 
tagID is missing in the data set.

**Comment by scd** [comment]
doh, now added :)

**Comment by nicHoch** [comment]
still no id on dev.

**Comment by scd** [comment]
sorry just on my dev. Hopefully will release in prod tomorrow.

**Comment by nicHoch** [comment]
working fine
