### ISSUE TITLE
malformed topo json

### ISSUE THREAD

**Issue by scd** [theCrag/website#2166]
http://www.thecrag.com/climbing/australia/mt-yarrowyck/area/27594204
http://www.thecrag.com/climbing/australia/nowra/new-nowra-braidwood-road/area/112211136

**Comment by scd** [comment]
That was weird. I just had to edit and save, without even changing anything, and the problem went away.

@brendanheywood can you confirm the malformed topo no longer appears then close the issue.

**Comment by brendanheywood** [comment]
Ok so possible this was fixed ages but something was cached or something, I dunno but happy to close for now
