### ISSUE TITLE
Misplaced error message for Route count estimate

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2168]
I entered "15?" into the field Route count estimate to indicate my uncertainty, after submitting the form the field goit hightlighted with the remark "Invalid override price".
I guess it should rather say "please enter integer number".

**Comment by Mdemaillard** [comment]
corrected
![image](https://user-images.githubusercontent.com/60388146/77197766-68b9f700-6aee-11ea-83e2-c4662e9158b7.png)
