### ISSUE TITLE
CIDS result page after photo upload

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2169]
From https://www.thecrag.com/climbing/spain/olvena/area/597542037/photos I navigated to the sibling node "Peña del Coixo" using the list on the left side and used the button "Upload another photo" at the top. The upload dialogue was as usual, but resulted in a page with the following output:
CIDS

The Climbing Information Distribution System (CIDS) distributes climbing information electronically to registered stakeholders.

You have permissions to access the sub-processes outlined below.
...

The uploaded photo does not appear at this node. I suppose this is not an intended way of user interaction, please check.

**Comment by scd** [comment]
Can you send me the photo so I can follow the process too - scd@thecrag.com

**Comment by MelwinQ** [comment]
I have uploaded the photo a few minutes later using the "standard way". It  
is available for the node  
https://www.thecrag.com/climbing/spain/olvena/area/597542157 now.


On Sun, 10 Apr 2016 23:43:21 +0200, Simon Dale <notifications@github.com>  
wrote:

>
> Can you send me the photo so I can follow the process too -  
> scd@thecrag.com
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub



-- 
Erstellt mit Operas revolutionärem E-Mail-Modul: http://www.opera.com/mail/

**Comment by rouletout** [comment]
Maybe a one time event? Can not be reproduced, closing
