### ISSUE TITLE
stars tasklist

### ISSUE THREAD

**Issue by scd** [theCrag/website#2171]
- [x] 1 route 1 person 1 vote - baseline & delta mode
 - [x] remove threshold limits
 - [x] align *** = classic, ** = very good, * = good
 - [x] consensus rating half way between brackets

**Comment by scd** [comment]
I think will has made some good arguments in #560 for the following mapping
Mega Classic ★★★ (3)
Classic ★★★ (3)
Very Good ★★ (2)
Good ★ (1)

I was reading in New Scientist a couple of nights ago that showing negative ratings can have adverse effects such as users hunting people who give them negative ratings. Very few guidebooks show negative stars. I don't think we need to emphasis negative ratings even further. The ratings are there in the quality score.

Some guidebooks also have 5 star systems. I have no problems with Classic and Mega Classic both being three star. It also is closer to our current trigger for three star. I would not want to see a change in star ratings create a lot less three star climbs.

Will has put a lot of thought into his proposed changes. I think we should just go with the mappings he suggests then see what falls out.

**Comment by brendanheywood** [comment]
Hey I just thumbs up'ed you comment, never done that before and it's a new feature in github. Did you get an email or anything?

**Comment by scd** [comment]
nope, did not get anything. But I see the thumbs up

**Comment by nicHoch** [comment]
to give the user the impression that each vote counts (and that is how it shout be) we should provide a real value for the star score. IMO 0 - 3 is fine but with real intermediate steps. It should also be visible to the user (not in listing but on detail page) on how many and what particular votes/ascents the star score is based.

**Comment by scd** [comment]
I have done the work for this in my dev. Testing is a little bit more involved and requires a stats rebuild. Once done on my server I will sync dev with my server and we can have a look at what it looks like.

**Comment by willmonks** [comment]
Good on ya guys, thanks! 

nicHoch, I think the quality score out of 100 and the ratings histogram, which are already provided against each route, give you the info you're asking for.
