### ISSUE TITLE
Easier link to 'all ascents'

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2172]
Intuitively I always want to click on the 'relative popularity' symbol in the route listing to open the list of ascents of that route. Would that be complicated to implement? 

Also, maybe a matter of taste, 'relative popularity': is that really so important? Why not rearrange the popup a bit to show, for example "12 ascents" (in big letters) and below "relative popularity 30%" (in small letters). Or remove the lower line entirely, anyway the information is already contained in the symbol.

**Comment by brendanheywood** [comment]
Done! Example on the dev server:

http://dev.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/area/27070683

![image](https://cloud.githubusercontent.com/assets/187449/14458564/71a09fe8-00f5-11e6-956b-8804fc844c73.png)

**Comment by nicHoch** [comment]
Maybe to less precision? 0 and 1 ascents (from maximal 3) are both mapped to 0% 
reopen?

**Comment by brendanheywood** [comment]
I don't follow, do you have some urls to dev with examples?

**Comment by nicHoch** [comment]
the same as above:

http://dev.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/area/27070683

compare route#  4 and 9

**Comment by brendanheywood** [comment]
Ah, yeah I don't calculate that stat in the view template, that's back somewhere in the stats engine. It's possible that's actually what it's supposed to be doing but not sure, @scd ?
