### ISSUE TITLE
Gear style band links on area and route page are broken

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2174]
Route ones are completely broken
Area one work, but then don't stick after you submit the facet form

**Comment by brendanheywood** [comment]
I've mostly fixed this, but there is one tiny template data issue @scd can you look at this?

http://dev.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/route/24516303/routes/with-gear-style/boulder/?sortby=at,desc

This is a facet page for a route, but the data given to the template says it's an area instead so the urls it's generating are broken:

http://dev.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/route/24516303/routes/with-gear-style/boulder/json

![image](https://cloud.githubusercontent.com/assets/187449/14493856/24fe46e6-01cb-11e6-860c-e5a21de92ac4.png)

**Comment by scd** [comment]
Interesting. This was a common failure case in the template data because we assumed that referenceArea was an area. Fixed now
