### ISSUE TITLE
Who: Auto complete non-accounts the same as real accounts when ticking

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2177]
Pretty annoying to keep retyping the same names over for friends who don't have accounts (and who probably never will)

**Comment by brendanheywood** [comment]
This probably ties in somehow to #1518

**Comment by scd** [comment]
Half resolved in new tick flow. If you log mulitple routes in an area then the with names are preserved.

**Comment by rouletout** [comment]
Closing
