### ISSUE TITLE
It's easy to loose track of which topo in the various topo process

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2178]
I have a habit of working in multiple tabs to try and speed up editing, ie I'll upload different batches of topos in different tabs, and then as needed move them or delete old ones, or add routes etc.

In all of these processes it's really easy to not know which topo you are actually dealing with, I think we just need to add a thumbnail to the process pages so you always know what you are dealing with (ie the other processes always have the route name or area name)

**Comment by rouletout** [comment]
The tabs show the area and the breadcrumbs are visible, closing
