### ISSUE TITLE
Admin created accounts got gyms and competitions

### ISSUE THREAD

**Issue by scd** [theCrag/website#2180]
Gym competitions (and potentially other services like outdoor courses) may wish to create accounts on behalf of somebody else. In particular this process should cater for the following:
- [x] Juniors who do not have an email
- [x] People have not agreed to the terms and conditions, so should not be able to use their accounts until they have
- [ ] Claiming their account
- [x] Merging accounts

While the UI forces email, there is no reason why accounts must have email addresses.

Claiming their account will be easy if their email is associated with the account. If there is no email then we have to come up with a process. 

If a kid account is duped over multiple competitions then we have to have a way of de-duping

**Comment by scd** [comment]
See also #1518

**Comment by brendanheywood** [comment]
@scd apart from the merging which is logged elsewhere is this one pretty well sorted?

**Comment by scd** [comment]
Claiming accounts.

**Comment by scd** [comment]
THe core of this is done. If this get used then we can create a new issue for claiming an account. Closing
