### ISSUE TITLE
Via ferrata lost colour

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2185]
Seems that the grade of via ferratas is not displayed in colour anymore. Is that desired?
http://www.thecrag.com/climbing/austria/route/856959591

**Comment by scd** [comment]
I don't think it is intentional, but it does seem to be consistent across all alpine grading systems, which makes me think we made an intentional change that I have forgotten about or made a change with some side effects we did not intend.

We will have to investigate.

**Comment by scd** [comment]
@birgander2 this is now fixed
