### ISSUE TITLE
Should be able to delete a topo you just made

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2186]
This seems to be a reoccuring theme, someone makes a topo and then can't delete it
- [ ] not sure if there is supposed to be existing logic to cover this, do we have the same issues with routes? If so we just need to apply it to topos too
- [ ] if not then maybe add an exemption or something so a topo which have been created by that person and not edited by someone else can be deleted by the creator OR if the person has editing rights to the crag
- [ ] regardless of above, we should also show a delete link in the drop down menu, even if greyed out so peopoe know it's there, but if they don't have perms then it tells them why

**Comment by rouletout** [comment]
Topo Admin allows you to remove the topo, closing
