### ISSUE TITLE
Email links to discussions for ticks should go to event page not discussion page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2188]
ie I got this email link:

![image](https://cloud.githubusercontent.com/assets/187449/14803105/01512c12-0b9a-11e6-9164-aecf3fc74e06.png)

which went to here:
https://www.thecrag.com/discussion/864342273/nice-one-skippy

when I think it would be more useful to go to here:
https://www.thecrag.com/event/861795087

**Comment by scd** [comment]
I have done this. Will come through next release.
