### ISSUE TITLE
team gym comps workflow improvements

### ISSUE THREAD

**Issue by scd** [theCrag/website#2189]
- [ ] Make it easy for the comp organiser to create accounts on the fly without a user signing T&C or providing email or password. Just a name
- [ ] Team view for logging ascents rather than participants view. Consider selecting the person from that team as part of the index UI selection.
- [ ] Clearer feedback that an ascent has been logged. Below the fold scrolling issues.
- [ ] Competition route name selection that has meaning for the climber if they want to claim their ascents. For example the competition route name may be "14 meters", but this is pretty meaningless in log book. Maybe have a log book name of 'Gym Comp, 14 meters' for the logbook.

**Comment by brendanheywood** [comment]
most of this is done or managed elsewhere, closing
