### ISSUE TITLE
The field "AKA name" is not available when creating a node but only when you edit it

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2195]

**Comment by birgander2** [comment]
+1

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76417513-a78cd600-63a5-11ea-9424-246548b260e0.png)

![image](https://user-images.githubusercontent.com/60388146/76417557-bbd0d300-63a5-11ea-868b-aa5c6d4b4651.png)

Implemented. Closing.
