### ISSUE TITLE
add the word 'rock' in more meta descriptions

### ISSUE THREAD

**Issue by scd** [theCrag/website#2196]
google says it is the 20th most important content keyword in the site. It should be in the top 4.

**Comment by scd** [comment]
It seems to be in there. It is not in the url's but I don't think we want to put it in the urls. There is some google magic going on here which I don't understand.

**Comment by brendanheywood** [comment]
I'm a little sceptical of any magic fix like this.

**Comment by scd** [comment]
There was not an easy fix, so I am closing this
