### ISSUE TITLE
user control of which tick types (and therefore colours) in the performance charts on profile page

### ISSUE THREAD

**Issue by scd** [theCrag/website#2197]
Todo list:
- [ ] break up 'other' so other common tick types are visible
- [ ] possibly first figure out which are the top 5 tick types for that person and then only show those on the graph legend

Current state:
![image](https://cloud.githubusercontent.com/assets/187449/15101114/e00e4892-15ca-11e6-8abe-e3e569f137dc.png)

**Comment by brendanheywood** [comment]
Hhmm, this seems pretty low value to me. The colors are those colors for good reason and are consistent across the whole site

**Comment by thorstencho** [comment]
I agree with that point.
For me the issue is rather to control the tick types -i.e. colours- that are shown in the charts.
e.g.: I don´t do pink points but would like to see how many heroic solos I have done ;-)

**Comment by brendanheywood** [comment]
Ah yes that makes more sense. So just to double check you mean this chart:

![image](https://cloud.githubusercontent.com/assets/187449/15101114/e00e4892-15ca-11e6-8abe-e3e569f137dc.png)

But I get the feeling it's probably still not great making this a user setting, it would be better to just make the defaults better so everyone sees an improvement. Perhaps a starting point is that more different tick types are added to the chart each with their own subtle color difference, but with similar tick types having similarity colors.

**Comment by thorstencho** [comment]
Yes, that one and 
![pfcbtt](https://cloud.githubusercontent.com/assets/19255275/15161882/3c2c70d2-1700-11e6-8c6a-7e486a8068cb.png). 
I like all your ideas to reduce the ratio of "other", so a user choice is probably not necessary.

**Comment by birgander2** [comment]
Generally, the profile charts and lists are one of the most interesting features on thecrag, and therefore quite important, but several interesting features are missing or quite hard to use: 
- config buttons exclude each other; one cannot select sport & indoor or boulder & outdoor together, select a certain period overrides all, etc. Sometimes one just want to play around without changing the default settings your the profile. Or when checking other person's profiles.
- performance chart / notable ascents for certain years
- performance chart / notable ascents by tick type
- performance chart / notable ascents by region / crag
- click in performance chart for '2015' and get a list of all the routes contained
- there is only one fixed (user-defined) grade system. But one per type is needed (sport, boulder, ice, ...).
These are just some suggestions. The data is there, it would be great to get some improvements here!

**Comment by brendanheywood** [comment]
We are doing a review of all the tick types soonish, it makes sense to tweak these graphs at the same time to show them all

**Comment by scd** [comment]
no longer configurable for profile page

**Comment by brendanheywood** [comment]
note that there is more work happening soon to redo the top too charts so the colors match and there is less 'gray' ticks
