### ISSUE TITLE
Via ferrata get displayed as unknown in crag list overview

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2202]
Hope it's clear what I mean. The via ferrata type seems to end up as unknown in the style summary for a crag / area.

Example 1:
http://www.thecrag.com/climbing/austria/area/866738772
http://www.thecrag.com/climbing/austria/area/551633583

Example 2:
http://www.thecrag.com/climbing/germany/oberbayern/area/403966290
http://www.thecrag.com/climbing/germany/oberbayern/area/400556163

**Comment by scd** [comment]
Yes there was something missing in the backend stats. Hopefully this will be fixed for next release.

**Comment by scd** [comment]
Code fixed in simons dev. We be available next release.
