### ISSUE TITLE
Usability Issue Switching between Map and Index

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2210]
When entering a new crag once you hit the "Location" button the system takes you to the "Map" menu (same if you hit "Edit Location" on an existing crag). If you wish to enter new routes after that there is no easy way to find the "Add Routes" function. The easiest way I found is to go to your dashboard and select the crag from your "recent" list which is quite a pain. Add Routes and Ascents should be top level functions and available almost anywhere...

**Comment by brendanheywood** [comment]
From the map pages, just click on the 'Index' tab to go back to where you were.

**Comment by brendanheywood** [comment]
I've added the same action menu from the normal index view to the location edit page:

![image](https://cloud.githubusercontent.com/assets/187449/21917159/d806fa0c-d999-11e6-8062-865ef0097ba7.png)
