### ISSUE TITLE
Dashboard / Your Profile Menues

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2214]
I would like to propose a change of menue names / content for the Dashboard and Your Profile menues:

In IT terms I expect from a Dashboard more what is shown under Your Profile (pyramid, list of ascents and other interactive graphics) and not a list of Activities. However, the current "Your Profile" seems to be a mix of real profile information (such as text about yourself) as well as Dashboard information. My proposal is to create 3 menues out of it, The Profile Info (strictly related to the user and rarely changing), the Dashboard (showing a configuarable graphic and list of ascents of the user) and an Activities menu.

**Comment by scd** [comment]
Yes we need a whole new review of the profile page and what goes on it.

**Comment by brendanheywood** [comment]
Closing this as most of the dashboard direction and changes are underway
