### ISSUE TITLE
reduce disk usage by moving sessions to redis or some other store

### ISSUE THREAD

**Issue by scd** [theCrag/website#2220]
The fundamental reason is that we are still storing new images on both prod and static. We don't have to store on prod at all, I only want to do this for my own paranoid reasons and if there are problems with the thecrag daemon then images don't make it to static.
- [ ] make the upload process more robust
- [ ] do not store images on prod at all (currently 48G and growing)

I have not fully removed the old image store, just in case
- [x] old photos removed
- [ ] old topos still not removed (29G available when we remove)

There is a growing session cache hash file in the 'files/queue' which is about 6G. Removing this will invalidate sessions. I don't think we want to do this just yet
- [ ] reset session cache file

There are 19G of custom PDF files. We can remove anything older than 1 month because it is against our T&C to use PDFs older than a month.
- [ ] write daily script to remove old custom PDFs (19G of space)

**Comment by brendanheywood** [comment]
> I only want to do this for my own paranoid reasons and if there are problems with the thecrag daemon then images don't make it to static.

Do you mean as a backup for disaster recovery, or do you mean just in case the transient upload process doesn't work? The backup I see as independent and should already be solved. If it is only the transient risk then can't we delete everything older than say 1 month?

> There is a growing session cache hash file in the 'files/queue' which is about 6G. 

That seems very unreasonably large by several orders of magnitude, is this all sessions ever? are we just storing a lot of stuff in the session? Most apps I've worked on have one file per session (default php behaviour), or stick them into db / memcache / redis, and there is a cron job to clean up old sessions which haven't been closed via normal logout.

This in turn makes me ask a bunch more questions, I assume there are good answers but I want to double check: how does session locking work? is there session write contention with this single file across all sessions? or is this in memory and only intermittently flushed to disk? Either way this sounds like something we will need to revisit at some point so we can scale to multiple front ends.

> write daily script to remove old custom PDFs (19G of space)

Yup and we also need to tidy up the GUI for historical downloads of custom PDF's or simply also remove items which are > 1 month here too

**Comment by scd** [comment]
> That seems very unreasonably large by several orders of magnitude, is this all sessions ever? are we just storing a lot of stuff in the session? Most apps I've worked on have one file per session (default php behaviour), or stick them into db / memcache / redis, and there is a cron job to clean up old sessions which haven't been closed via normal logout

All sessions all time. Won't work across multiple front ends. One reason I put it in this list was because it is clear it needs to be addressed. Drop in replacement for memcache might be ok.

**Comment by brendanheywood** [comment]
We've been using memcache for sessions at work extensively, but we are working to move away from it to db / redis. The big downside with memcache is that it's by design a cache and not a persistent store, so there is no guarantee that it will hang on to data. If a session is lost it's not the end of the world but it's not great UX, also moodle's sessions are quite strict and < 24 hours where as we have fairly long lived sessions so this becomes more important. Also memcache is crap when you do an upgrade or something and bounce the server and kick everyone out, you need to flush to persistent disk eventually. Hence the move to redis which does all this, but even just using the normal DB would be a step up for us and probably sufficient without trying to introduce another layer in the stack.

**Comment by scd** [comment]
There will be some work in moving sessions and we will need to discuss thoroughly. Going to multiple front ends will have other more significant issues. 

> Do you mean as a backup for disaster recovery, or do you mean just in case the transient upload process doesn't work? The backup I see as independent and should already be solved. If it is only the transient risk then can't we delete everything older than say 1 month?

Also forgot to respond to this. Nothing to do with backup. Creating a local store of images in production was part of the migration procedure and as a transient for ongoing upload process. The first is done, but we are still using it as a transient. This can obviously be rectified but I need to remove it from the process before removing the production image store.

We have backup on my LAN in two places and on the Internet. We do daily a daily sync to local LAN and another LAN server which I sync every couple of months. Our official backup is on an rsync service by an organisation called StrongSpace. 

We should have a backup audit process every now and again. It is easy to assume everything is working, but there are chances I have missed something or something breaks. I have got monitoring in place for many aspects of the process, but it is still no guarantee that all is good.

**Comment by scd** [comment]
Disk space under control now. Closing
