### ISSUE TITLE
Topo Discard button not working

### ISSUE THREAD

**Issue by scd** [theCrag/website#2222]

**Comment by brendanheywood** [comment]
Yeah it doesn, it's just badly named and isn't what people expect. It's a way for people to discard unwanted draft changes, when people expect it to delete the topo. I'd be happy to remove it

**Comment by Mdemaillard** [comment]
Still the case. If function kept, the pop-up "Leave site ? chang eyou made may not be saved" could be escaped or rephrased.

**Comment by rouletout** [comment]
I have no idea where a topo discard button is? Closing
