### ISSUE TITLE
translate UI enhancements

### ISSUE THREAD

**Issue by scd** [theCrag/website#2224]
- [x] better permissions handling
- [x] auto create missing language directories
- [x] verify presence of placemarkers (eg if we as the dev's add a new english  string like "There are {count} things" and then someone translates it to "There are some things" then it could throw a validation error because it doesn't contain the {count} token)
- [x] perl is very sensitive to malformed information. If the input text is not valid utf8 then it is not stored. This needs further research. 
- [x] system does no crash if a translation file has a bad format

**Comment by nicHoch** [comment]
If we go with multiple translators for each language we need some collaboration helpers
Add meta data fields to each key each lang and add filters to the UI:
 - [ ] new translated (some kind of ready for review)
 - [ ] mark for discussion
 - [ ] comments
 - [ ] who has done the translation

**Comment by scd** [comment]
Hmmm, that was sort of what I was getting at with using a DB design. 

I log who made the update and what it was changed to. But this in a log not the UI. If we take Phillip up on his offer I will not have made any of the above enhancements.

**Comment by UFU608** [comment]
I think we need to keep it small and have one "lead translator" per language in order to stay consistent with terms. The lead could check the logs, no?

**Comment by nicHoch** [comment]
later on we go with languages we do not know personal and also do not 
have a "friend" in hand for being the main translator. It is most likely 
that many languages will be translated be a group of volunteers. 
Therefor i guess we need good support tools.

What about only storing the meta data in a db schema: using the lang and 
key as ID.


Am 25.07.2016 um 10:32 schrieb UFU608:

**Comment by rouletout** [comment]
I think this is all in place, closing
