### ISSUE TITLE
climber/id/avatar/size

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2227]
provide a endpoint for a climber that will serve the avatar image regardless of the avatar source type. 
The pure avatar image without any html.

The size parameter is a enum of:
- normal (default) (50x50)
- small  (25x25)
- large  (75x75)
- xlarge  (100x100)

real sizes are suggestions!

**Comment by scd** [comment]
Remind me what is the deficiency of the /avatar/9068185 end point? 

Is it because it does a redirect?

**Comment by brendanheywood** [comment]
Can also suggest we dont use keywords and just always use pixel sizes as arguments, ala thumbor

**Comment by nicHoch** [comment]
i did not see that endpoint. This one is fine please just add some sizing arguments. Direct size is more flexible and also fine for me.

**Comment by nicHoch** [comment]
i think i can live without the sizing arguments. Or is it possible that you redirect the sizing to facebook gravatar ....
If not we can close that one.

**Comment by scd** [comment]
Use the url parameter 'size'  eg /avatar/1234?size=100

Avatars are square so you only need one dimension. Gravatar, Google and internal avatars accept the size parameter so this is passed on. Facebook does not so it makes no difference for Facebook avatars. However I think Facebook avatar is by default a little larger?

You also don't know if it is Facebook or some other source so just pass the size as you would like.

Please close once you are happy

**Comment by brendanheywood** [comment]
The important takeaway with this endpoint is that you may request an image of a certain size but you ma not get it, so you need to correctly handle those cases, in particle images smaller than you wished for. Thumbor could be set to upscale, but the FB etc ones don't.

**Comment by scd** [comment]
@nicHoch can we close this one now?
