### ISSUE TITLE
Reparenting Select Children

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2232]
When re-parenting children under e.g. a crag it would be useful to not only see the list of Child Nodes and the selection box but also the type of Child Node (e.g. Sector, Route, etc.).

Use case: An existing crag is re-organized by introducing sectors and the existing routes are re-parented to the new sectors. You can not see the difference between the new sector names (in the example below the last 4 entries) and the route names when selecting the routes.

<img width="718" alt="screen shot 2016-06-15 at 17 51 19" src="https://cloud.githubusercontent.com/assets/19162952/16088784/f7a2ff5e-3328-11e6-9705-0534b308318b.png">

**Comment by Mdemaillard** [comment]
see also #3558, using the new list view here would be great as well

**Comment by Mdemaillard** [comment]
Merging from duplicate: From Brendan
I would go one step further and add the description, or the first line of the description of each area / routes and possible other details like grade or height. Some areas have good route details but poor names

**Comment by rouletout** [comment]
This is actually done - @Mdemaillard if you agree you can close

**Comment by Mdemaillard** [comment]
there is a good progress. It does not use the same view as topo though, and still without description. I am fine with closing though. @brendanheywood final vote ?

**Comment by scd** [comment]
I am ok to close this.
