### ISSUE TITLE
api idempotent data

### ISSUE THREAD

**Issue by scd** [theCrag/website#2235]
We need to be able to protect the system from rogue apps submitting the same data over and over again.
We also need to ensure there are no dup entries on personal data because of connectivity issues.

Options
- [ ] write watcher functions over each api write endpoint to ensure that the data has not already been submitted. Too much work as each end point has it's own watcher code.
- [ ]  write app level idempotent api key which means that a transaction can only be accepted once. If the app wanted to re-submit then it would have to create a new idempotent key. Does not protect the system from rogue app
- [ ]  md5 the api data. If the key has been seen then return the previously recorded result. Does not allow the same data to be submitted twice.

I am favouring the later as it can be implemented system wide. There are some problems with it though. For example what happens if somebody favorites and area, unfavorites then favorites again.

**Comment by brendanheywood** [comment]
Favorites I don't see as an issue, lets say that you can fav a crag offline in the app. The data for a fav is the crag id and a timestamp of when you fav'ed it. If you unfav it later before it has synced with the api then it removes the record and never syncs. If it has synced then the data includes a timestamp of when you fav'ed it so it is unique for subsequent unfav's and refav's. This idea of retrospective data timestamps could apply for anything but has implications everywhere and may not be appropriate. I think it makes sense for fav's and ticks, but perhaps not for everything. And is ticks a full timestamp or just a date?

Also I think all of this should only apply for some period, ie only detect duplicate data within a minute or hours etc, so I think the pure hash method isn't ideal, unless we include a rounded timestamp as part of the hash data.

**Comment by scd** [comment]
Timestamps are implemented server side. There are no timestamps passed with the favorite API. The timestamp is the create date of the record. Are you suggesting we add timestamps as part of this solution?

Favoriting of course is not a problem as it is impossible to get dup favorites. I am just pointing out a counter example to doing a system wide solution.

Ticks have two dates - the log date and the ascent date. The log date is the record create date and the ascent date is the user defined date. The log date is not passed to the API, just the optional ascent date.

**Comment by brendanheywood** [comment]
Conceptually if I am offline and I fav a crag, and then sync the app a week later back at home, I could reasonably expect the fav to have a date of when I actually did it and not the api sync date. So in this case yes I think we should have a timestamp for fav's but it's a low priority.

It's not really a counter example because it actually highlights that when we are talking about multiple states (ie app + api) and syncing across them at a later date, then you really do need to track either a version number or timestamp (like subversion) or a unique distributed id like a hash of the content (like git, which uses date as part of the data to form the hash)

So I do see this generally as a solution for this class of sync problems. Ascents already have a log date which would be set by the app at tick time not sync time. And that is the date which should be used to detect duplicates. Although I am not sure if it is a full timestamp or just a date. Either way it would still work. Even if the app allowed you to do historical tick which didn't have any log date, a date = null is still valid data and we can still use that to detect duplicates.

**Comment by scd** [comment]
> Conceptually if I am offline and I fav a crag, and then sync the app a week later back at home, I could reasonably expect the fav to have a date of when I actually did it and not the api sync date. So in this case yes I think we should have a timestamp for fav's but it's a low priority.

I generally agree with this but there is possibly a higher level concept. The system automatically creates the record create date. This is totally controlled by the system, and no third party app should be able to control and backdate this. I am very reluctant to make exceptions to this. So maybe we keep this concept as the record create date and have another timestamp we add for app create date. 

Being offline for a week brings up the stream date issue. What date should we be using for this. Perhaps we should be using this app timestamp. With ascents we use the log date and use a historical flag if this is significantly different from the create date. Whatever logic we decide needs to be consistent for stream events.

> It's not really a counter example because it actually highlights that when we are talking about multiple states (ie app + api) and syncing across them at a later date, then you really do need to track either a version number or timestamp (like subversion) or a unique distributed id like a hash of the content (like git, which uses date as part of the data to form the hash)

Then we should create a hash of the API content as this can be implemented as an overlay to the API. We could do it one end-point at a time and make the app timestamp mandatory for those end points.

This was my preferred implementation and with a mandatory app timestamp solves the issues I had with the method.

>  So I do see this generally as a solution for this class of sync problems. Ascents already have a log date which would be set by the app at tick time not sync time. And that is the date which should be used to detect duplicates. Although I am not sure if it is a full timestamp or just a date. Either way it would still work. Even if the app allowed you to do historical tick which didn't have any log date, a date = null is still valid data and we can still use that to detect duplicates.

Ascent date is a date not a time stamp throughout the system. However I think it is a datetime in MySQL, so there should be no fundamental reason why we cannot move to actual time. It would make sense with an app.

**Comment by brendanheywood** [comment]
> Being offline for a week brings up the stream date issue. What date should we be using for this. Perhaps we should be using this app timestamp. With ascents we use the log date and use a historical flag if this is significantly different from the create date. Whatever logic we decide needs to be consistent for stream events.

Yes we've already hashed all this out for ascents and streams and I still agree with those past decisions. Record date is internal and set by api, log date, or fav date, or photo taken date, or whatever is data dependant on the activity type and set ahead of time. We should be able to use the same thresholds for all types in the stream logic for when the two dates are sufficiently separated.

**Comment by scd** [comment]
closing
