### ISSUE TITLE
Translations of site policies

### ISSUE THREAD

**Issue by scd** [theCrag/website#2236]
In particular this includes T&C. 

Generally speaking I have structured site policies in a versioned document of clauses. Currently this includes:

  * Site Usage (ie T&C)
  * Copyright
  * Privacy
  * Offensive Content

There is a backend process to update these which will also update the version of the document. These documents will not change without careful consideration.

I have written a script that generates keys for the english version of each of the documents. Keys look something like `policy.usage-policy.5.001.header`, where the 5 refers to the version of the document, the 001 refers to the clause number (ie the keys will be in the same order as the natural flow of the document) and the 'header' refers to the presentation of the clause (ie header/normal/list). The 'header' is strictly not required, but I think it will add value to the translators.

I create two files for each document:

  * en/policy.usage-policy.5.json
  * en/policy.usage-policy.5.text

The json document is the standard translation key/value pairs. The text file is a straight text document in it's intended clause order. We can do a diff on the one version to the next to get the overall changes to the policy versions. This will be useful for translators. I have not implemented this diff at this stage.

There is one json document per document version. There are several advantages for this when it comes to managing via git. Once a version document is created it should not change. The history will be explicit in the repository. We can easily do a diff between versions, maybe even using repository tools.

I have also been thinking about the process of creating a new version of a document. Because the version number will change in the key, all the translations will be invalidated. However it should not be too difficult to write a script which upgrades the translations for key text that have not changed between versions.

What to do about translations of old versions. Do we remove them to save space. If we keep them we don't want a translator to be translating for old versions. I think we just remove them because we never need to pull out old versions and if we do they will be in the repository (eg for legal reasons).

Tasks to complete:
  - [x] add clause to refer to the english version as being the legal version
  - [ ] identify other articles which should be implemented as policy documents (eg behaviour policy)
  - [ ] document version diff for translators
  - [x] script to upgrade translation keys for clauses that have not changed between versions
  - [x] work out a way to manage translation keys for old versions (ie translators should not be able to translate old versions of policy documents).

**Comment by nicHoch** [comment]
The first preamble of the T&c should be a sentence thats points out that the only valid T&C are the one in english (show a link) and that the T&C shown below  (other language) is only a help to understand this but not legally valid.

Am 20. Juni 2016 03:47:16 MESZ, schrieb Simon Dale <notifications@github.com>:
>In particular this includes T&C. 
>
>Generally speaking I have structured site policies in a versioned
>document of clauses. Currently this includes:
>
>  * Site Usage (ie T&C)
>  * Copyright
>  * Privacy
>  * Offensive Content
>
>There is a backend process to update these which will also update the
>version of the document. These documents will not change without
>careful consideration.
>
>I have written a script that generates keys for the english version of
>each of the documents. Keys look something like
>`policy.usage-policy.5.001.header`, where the 5 refers to the version
>of the document, the 001 refers to the clause number (ie the keys will
>be in the same order as the natural flow of the document) and the
>'header' refers to the presentation of the clause (ie
>header/normal/list). The 'header' is strictly not required, but I think
>it will add value to the translators.
>
>I create two files for each document:
>
>  * en/policy.usage-policy.5.json
>  * en/policy.usage-policy.5.text
>
>The json document is the standard translation key/value pairs. The text
>file is a straight text document in it's intended clause order. We can
>do a diff on the one version to the next to get the overall changes to
>the policy versions. This will be useful for translators. I have not
>implemented this diff at this stage.
>
>There is one json document per document version. There are several
>advantages for this when it comes to managing via git. Once a version
>document is created it should not change. The history will be explicit
>in the repository. We can easily do a diff between versions, maybe even
>using repository tools.
>
>I have also been thinking about the process of creating a new version
>of a document. Because the version number will change in the key, all
>the translations will be invalidated. However it should not be too
>difficult to write a script which upgrades the translations for key
>text that have not changed between versions.
>
>What to do about translations of old versions. Do we remove them to
>save space. If we keep them we don't want a translator to be
>translating for old versions. I think we just remove them because we
>never need to pull out old versions and if we do they will be in the
>repository (eg for legal reasons).
>
>Tasks to complete:
>- [ ] identify other articles which should be implemented as policy
>documents (eg behaviour policy)
>  - [ ] document version diff for translators
>- [ ] script to upgrade translation keys for clauses that have not
>changed between versions
>- [ ] work out a way to manage translation keys for old versions (ie
>translators should not be able to translate old versions of policy
>documents). 
>
> 
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2236

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by scd** [comment]
> The first preamble of the T&c should be a sentence thats points out that the only valid T&C are the one in english (show a link) and that the T&C shown below (other language) is only a help to understand this but not legally valid.

Yes I was thinking of something similar. But how to implement. The easiest way is to possibly implement as a clause in the T&C ???

**Comment by scd** [comment]
I am closing as this is substantially done. Remaining tasks are broken into separate issues.
