### ISSUE TITLE
email template internationalisation

### ISSUE THREAD

**Issue by scd** [theCrag/website#2237]
- [x] get welcome template keys set up
 - [x] a way to test email templates very simply
 - [x] non template email footer
 - [x] all email templates to be turned into language keys
 - [ ] welcome email has smarts to pick a crag for particular countries
 - [x] how is language selected for emails?
 - [x] policy for missing translations or wrongly encoded en keys?
 - [x] review processes that trigger emails for initialising the translation module

Here are a list of the templates to be translated
 - [x] BulkImportLogbookProcessFinished 
 - [x] NotifyNewDiscussionComment				 
 - [x] Email-Change-Notification
 - [x] Password-Change-Notification	
 - [ ] RequestBusinessDirectoryListing
 - [x] FollowedBy
 - [x] Password-Reset
 - [x] RequestEditorNotification	
 - [x] Login-Change-Notification
 - [x] PDFCragGuide-WebRequest
 - [x] Signup
 - [x] Supporter-Monthly-Start
 - [x] PromoteCragEditor
 - [x] Supporter-OnceOff-Charge
 - [x] Supporter-Monthly-Change
 - [x] Supporter-Monthly-Charge
 - [x] Supporter-Monthly-Cancel

**Comment by scd** [comment]
I have written a script that tests email templates. If the script is 'email-templates/Signup' then write a test json file 'email-templates/Signup.test' which contains json data to be passed to the template and call the script like such

```
./test-email email-templates/Signup.test
# or for de language
./test-email -l de email-templates/Signup.test
```
It will output the text of the email rather than sending it.

**Comment by brendanheywood** [comment]
>  non template email footer

Why does this need to not be a template? Why can't it stay as a minor template and just call getString as needed which is what I'd expect?

It's subtle but I think refactoring at the template level has more value than refactoring at the string level, eg we could decide to later add stuff to the email footer (eg an image link) which isn't strictly language related so we'd then have to either add that to every language (which would be wrong and duplcated), or we'd then have to swap back to a template

> welcome email has smarts to pick a crag for particular countries

We could start by just hard coding this for each language? eg en already hard codes waterworks. 

> how is language selected for emails?

By the time the email is sent we should already have an account, which should already have it's language set which most probably came from the browser accept language. In theory there should be no custom logic at all in the email process it should just call getString in an account context and it's handled the same as elsewhere.

> policy for missing translations or wrongly encoded en keys?

If we find a missing key at runtime I'd like this to be pretty noisy, like spam the error log and if possible also turn up in the daily email so we can jump on it right away.

**Comment by scd** [comment]
> Why does this need to not be a template? Why can't it stay as a minor template and just call getString as needed which is what I'd expect?

I was refering to the html boilerplate being added around the email. There are some links to privacy policy, etc which need to be called using getText. 

> It's subtle but I think refactoring at the template level has more value than refactoring at the string level, eg we could decide to later add stuff to the email footer (eg an image link) which isn't strictly language related so we'd then have to either add that to every language (which would be wrong and duplcated), or we'd then have to swap back to a template

I think I am confused.

> We could start by just hard coding this for each language? eg en already hard codes waterworks. 

I would still class an if statement as smarts. I agree we should just hard code it as you suggest. We should really be picking something from the users country.

> By the time the email is sent we should already have an account, which should already have it's language set which most probably came from the browser accept language. In theory there should be no custom logic at all in the email process it should just call getString in an account context and it's handled the same as elsewhere.

Yes, but we need to work through the flow. For example if it is a system triggered email (eg somebody being granted editor permissions for a crag), then we must make sure that the script picks up the users language from their account and sets it. The script may run through dozens of users so it needs to be done for each user.

> If we find a missing key at runtime I'd like this to be pretty noisy, like spam the error log and if possible also turn up in the daily email so we can jump on it right away

We have talked about a few different things here. In templates you mentioned adding a big red box for empty content.

I have not implemented anything yet because I want to get a stronger feel for what is needed. Getting warnings into the apache error log is a good idea.
