### ISSUE TITLE
Improvements to Translate framework

### ISSUE THREAD

**Issue by scd** [theCrag/website#2238]
- [x] strip leading and tailing whitespace
 - [x] refesh UI keys when pressing the next key button if you are editing only emtpy keys
 - [x] log missing keys to apache log
 - [x] add preparse json file to join multi lines to legal json (lines ending with backslash \) 
 - [x] display \n as html `<br>` in texts
 - [x] set getText to return en if key missing for everything but templates
 - [x] implement a simple plural function
 - [x] toSentence function - borrowed idea from Rails. toSentence('One','Two','Three') returns 'One, Two and Three', where the 'and' comes from getText.

**Comment by scd** [comment]
Given the way we are implementing translation keys I am now in agreement with @brendanheywood about implementing some simple functions. I am going to start with plurals. 

Looking at the sentence "You have 2 unread discussions". I am now thinking of implementing this something like "You have {count} unread {p object.discussion, count}" and have the following keys in the system 'object.discussion' => discussion and 'object.discussion.plural' => discussions. 

I think we have accepted that {variable} is useful in the translations. My thoughts are to expand the syntax within the curl brackets to allow for functions.

**Comment by brendanheywood** [comment]
> Given the way we are implementing translation keys I am now in agreement with @brendanheywood about implementing some simple functions. I am going to start with plurals.

Do you mean the ability to call other strings within a string (ie usually called partials) OR do you mean functions which are defined outside the string system. If the former then we are effectively inventing our own template language which I'd prefer to avoid and just use a solid one already in existence. If the latter then we are sorta doing the same thing but worse we need to implement these various functions in multiple languages so e can use them in perl + js + java.

If this is only ever going to be a very small limited number of well defined functions and the overhead of multiple implantations isn't a burden then ok.

We also need to be careful what the function are for and what they do. For instance the count function you mentioned above either needs to be language aware, or if we implemented it instead as a template then you could potentially have different templates for each language to sort the differences. The example you gave makes assumptions that don't always apply in all other langues, ie that there is a singular form and a plural form.

**Comment by scd** [comment]
The webserver and the app will have to implement the same translate functions, but js will call the webserver for the key translation so we don't need to worry about js.

I think we have aready agreed that the translation system will do substitutions like {count} or {username}. Both the app and the webserver should be conforming to this. Yes I want to add a small number of additional conventions in the curl brackets. This is something I actually thought this is what you were suggesting.

The implementation of this was a one liner in the webserver:
```
    $text =~ s/\{\s*p\s+([a-z0-9-\.]+)\s*,\s*([a-zA-Z0-9]+)\s*\}/getText($1,'lang',$lang,'count',$subhash->{$2},'seenkeys',$seenkeys)/ge;
```

I was hoping to avoid this but we are getting scenarios in the email templates where the sentence generation is depending on two different parameters, so we get sentences like:

```
2 unread comments in [Arapiles: let's talk](https://www.thecrag.com/some-url) by Campbell Gome and Brendan Heywood
```

Where comments can be plural or singular and the by clause may or may not be there.
