### ISSUE TITLE
robots.txt issue with czech republic

### ISSUE THREAD

**Issue by scd** [theCrag/website#2246]
Have a look at the google search results for 'thecrag czech republic'.

https://www.google.com.au/search?client=ubuntu&channel=fs&q=thecrag+czech&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=BUd0V-r5CaXu8weBhLTgDg#channel=fs&q=thecrag+czech+republic

Google claims that 'A description for this result is not available because of this site's robots.txt'.

It also seems that indexing stops here.

Does anybody know what is going on?

**Comment by brendanheywood** [comment]
![image](https://cloud.githubusercontent.com/assets/187449/16472821/e32cbe38-3eaa-11e6-94df-43f3f2f77e3c.png)

**Comment by scd** [comment]
ok that means we have to rethink the robots.txt file

**Comment by brendanheywood** [comment]
This is actually a fairly wide issue with any urls that contains any of those suffixes, ie 

/*epub

should be

/climbing/*/epub

I'm not sure how expressive the robots stuff it, it's not a regex

**Comment by brendanheywood** [comment]
![image](https://cloud.githubusercontent.com/assets/187449/16472909/010b29ac-3eac-11e6-84ef-7730400f74aa.png)

**Comment by brendanheywood** [comment]
btw the tool is here:

https://www.google.com/webmasters/tools/robots-testing-tool?hl=en&siteUrl=http://www.thecrag.com/

**Comment by brendanheywood** [comment]
We can also use $ at the end see 

http://searchengineland.com/a-deeper-look-at-robotstxt-17573

I can't do much more right now

**Comment by scd** [comment]
You have done heaps. Based on what you have done I have made a quick update to the robots.txt file. It probably needs a more thorough review

**Comment by brendanheywood** [comment]
Also in the same tool you can resubmit urls to be crawled sooner, I've just done this for czech and it's children

https://www.google.com/webmasters/tools/googlebot-fetch?hl=en&siteUrl=http://www.thecrag.com/
