### ISSUE TITLE
Deprecate pdf to dropbox syncing (was Dropbox api migration)

### ISSUE THREAD

**Issue by scd** [theCrag/website#2247]
Tasks:

* [ ] remove all references to dropbox in lang files
* [ ] remove references to dropbox in articles
* [ ] remove dropbox checkbox on pdf process page

was:
Dropbox API will be turned off in June 2017. We need to migrate to their version 2

**Comment by brendanheywood** [comment]
Did this happen?

**Comment by scd** [comment]
Nope. I just tested and it is broken.

**Comment by brendanheywood** [comment]
Ok I think we should just deprecate this, nobody has complained in a year of it being broken so it's obvious very few people use it. I'll rename this to a deprecation task

**Comment by scd** [comment]
Yup, it is way to much work for us to keep up with other systems API change schedule. We should really think hard about introducing new features which rely on third party systems in the future.

**Comment by brendanheywood** [comment]
Yup agree, but lets get rid of this properly

**Comment by brendanheywood** [comment]
Just downloaded a pdf and noticed this was still here

**Comment by killakalle** [comment]
Just downloaded a couple of PDFs and wanted to try the Dropbox sync. Noticed it does actually not exist.

**Comment by rouletout** [comment]
Yes this is gone :-) - the last links to it will disappear with the next release
