### ISSUE TITLE
Possible error in profile graph statisics

### ISSUE THREAD

**Issue by scd** [theCrag/website#2249]
https://www.thecrag.com/climber/DJGUYFI

I've setup my first profile ascents filter to only show trad and sport routes lead ascents. On my page it shows 2 19s, when I click it only shows 1 19?

One of the grade 18 sport routes has a grade 19 contribution:

https://www.thecrag.com/climbing/australia/onkaparinga/route/130410126

**Comment by brendanheywood** [comment]
fixed
