### ISSUE TITLE
Editing process not perfectly round trip (or maybe stream issue)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2250]
I just posted the story of the tote on ABC tonight, and cleaned up the totem pole url stub before I linked to it. This was the stream feed:

![image](https://cloud.githubusercontent.com/assets/187449/16729307/ec874c98-47ae-11e6-9a19-6c5b7b8d11c2.png)

I did batch edit the crag, but the only thing I touched was the url stub. So what's going on here, is there not a perfect round trip between what is given as the default values in the process form so it's detecting some subtle change? Or is this a display bug in the stream event?

**Comment by scd** [comment]
I think this is a once off change to the grade format  in the back end. I
should have done a global migrate to all grades when we last changed the
way the grades work. Future bulk edits to the area should be ok. If you do
a bulk edit to the area again tomorrow and it has the same behaviour then
it is of more concern

**Comment by brendanheywood** [comment]
Just confirmed that

**Comment by scd** [comment]
Yes this is a bit irritating and I am kicking myself for missing it. However we usually miss one or two things in any major upgrade.
