### ISSUE TITLE
framework for translations in javascript

### ISSUE THREAD

**Issue by scd** [theCrag/website#2251]
There are instances where texts displayed in the UI come from javascript. I have made a simple implementation as follows.

 - [ ] updated the footer template to include translation keys in the template. All the translations are loaded via a inline javascript array. This avoids a whole heap of asynchronous issues if we were to do it via the API. 
 - [ ] I have implemented the getText logic in the common.js file.
 - [ ] Each javascript file has a default load for their en key translations. This basically acts as a specification for the translations required for the js file and also means that the js file will work in english even if there are no translations loaded by the footer template. Eventually I think I want to split this so that for each xxx.js file there is a xxx.js-en file. Our pipleline will then compile the defaults, setup the template dependancies in the footer template and build the translation key file. This will happen when we refactor the asset pipeline.

**Comment by brendanheywood** [comment]
How does a template, like a tiny one 3 or 4 nexted template calls deep, decalre to the system that it requires a string to be available in js land? got a file / line with an example?

**Comment by scd** [comment]
If the template requires a particular js.template then this is currently managed through the js variable in the footer template. I have assumed that if you require a js template then you require all the keys for that template.

here is the code in the in the footer template:

```
%         if ( $script =~ /^cids\/common.js/ )   {
%           push(@{$translate_keys},(
%             "js.common.show-more",
%             "js.common.hide",
%             "process.button.log-ascent",
%             "process.button.log-ascent.one",
%             "process.button.log-ascent.many",
%           ));
%         } elsif ( $script =~ /^cids\/area-listview.js/ )   {
%           push(@{$translate_keys},(
%             "process.button.log-ascent",
%             "process.button.log-ascent.one",
%             "process.button.log-ascent.many",
%           ));
%         }
```

**Comment by brendanheywood** [comment]
It would be much better if each template could just tell some variable what keys it needs, and then the footer reads them and does what needs. Each top level template should not have to manage the transitive dependencies for all of it's templates and templates sub templates etc

eg /minor/foo/bar calls a function: requiresJSlang('foo.bar.ajax.ok', 'foo.bar.ajax.bad')

This internalls adds it to some global hash, footer reads them out and does its thing

**Comment by brendanheywood** [comment]
eg moodle does this:

```
// Include a single string:
$PAGE->requires->string_for_js('example', 'block_fruit');
 
// Include several strings from the same string component:
$PAGE->requires->strings_for_js(array(
        'example',
        'foo',
        'bar',
        'baz',
    ), 'block_fruit');
```

$PAGE is global and call be used from anywhere, when the footer renders strings appear same as what you've done

**Comment by scd** [comment]
That seems reasonable and in line with my first thoughts. What I implemented means I don't have to think about what is required in an individual template, but rather what javascript files we need.

When we revamp the asset pipeline I imaging we will have something like this:
 - climber.mason
 - climber.css
 - climber.js-keys
 - climber.js
 - climber.json-sample
 - climber.test
 - climber.style-guide
 
If we implement this then climber.js-keys will be equivalent to what you suggested. I am only doing a couple of keys in the javascript files at the moment.

**Comment by brendanheywood** [comment]
I didn't quite understand all that. But js files should be loaded exactly the same way, a template at any level of nesting should just say $PAGE->requires->js('foo.js') and the footer collects them all and renders whatever it needs to and handles all the dependancy ordering and de-duplication etc. The parent root template like /major/climber shouldn't know anything about what it's children need.

**Comment by scd** [comment]
no not the /major/climber, I was refering to the individual minor templates (minor/climber.card). Any minor template may have some javascript associated with it. At the moment it is all in bigger files, but I want to split it into smaller files the use the asset pipeline to build the files we are service. Sort of like we are doing with css (one-to-one relationship). I am pretty sure we have talked about this and have agreement. See #1587 & #1979

**Comment by brendanheywood** [comment]
Ah yes, splitting into micro js and then combining them back when serving and minifying etc I'm all for

**Comment by scd** [comment]
I am happy with what is implemented here with the next step being micro js
