### ISSUE TITLE
col-header.climbs tag to general

### ISSUE THREAD

**Issue by scd** [theCrag/website#2254]
there an easy way to find out where the term is used (e.g. col-header.climbs)? I try to look in the life system where

**Comment by brendanheywood** [comment]
How about something simple, like a string prefix mapping to a url, so if you have:

template.climber.foo.bar.title = ...
template.climber.foo.bar.header = ...
template.climber.foo.bar.footer = ...

then you could have one url mapping like:

template.foo.bar => /climber/brendan

It would be a pointer into a real life page that we've chose to have lots of good data. When editing any string who matches any prefix then just add the url to the editing lang page, there could end up being multiple example urls for a give string.

**Comment by scd** [comment]
I am mostly using prefixes like template.some-template.bla-bla-bla

We have got a lot of tables where we re-use headers. So I had some thoughts about minimising the translation work. Rather than having

 template.some-template.col-header.height = 'Height'
 template.another-template.col-header.height = 'Height'
 template.and-yet-another-template.col-header.height = 'Height'

My thinking was we could just use

col-header.height = 'Height'

IMO generally speaking table headers across different tables should have the same translation.

What I want to understand is if my assumption is just wrong or reasonable? 

In this example the `col-header.climbs` is ambigious. Is it a verb or noun? I think that is because we are using the wrong key. If we used the key `col-header.routes` would that still be ambigious?

**Comment by scd** [comment]
This particular issue is solved if I replace the `col-header.climbs` key with `object.route.many`. We should be doing this where possible anyway.

As far as the general discussion I am not convince that there is any issue with the way I am currently implementing report column headers. I am closing and will reopen if other issues come up
