### ISSUE TITLE
API: index/detail should have a "childIDs" parameter

### ISSUE THREAD

**Issue by adamdebono** [theCrag/website#2256]
I'd like to get a list of `childIDs` in the index/detail response. Currently this can be achieved by (computationally expensively) looping through all of the response data and mapping it manually. This is currently possible when retrieving an area/route using `api/node/id/{nodeId}?show=children`.

Also, it would be great to be able to differentiate this into `areaIDs` and `routeIDs`.

**Comment by scd** [comment]
Looping through an array once is not that computationally expensive. Surely you have to go through all the response data anyway?

**Comment by adamdebono** [comment]
I do go through all the response data but this adds an extra loop since I have to go through each node to map the child nodes, then I can assign and save them. It's not super expensive but this will be a task which is generally run in the background (on ios) so I want to minimise the chance of the system booting me out for taking too long/using too much power.

Also, when using the `since` parameter to get incremental updates, this becomes more complicated because I would need to check any cached data I already have.

**Comment by scd** [comment]
@nicHoch are you having a similar issue with your app dev?

**Comment by scd** [comment]
closing because apps should be using the index/detail endpoint
