### ISSUE TITLE
Formatting Area Page / Translations

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2258]
Translated keys mess up the formatting of the main area page (see attached). Needs fix asap!
<img width="817" alt="screen shot 2016-07-18 at 09 16 12" src="https://cloud.githubusercontent.com/assets/19162952/16908009/5a56471a-4cc8-11e6-8110-7fb3cd5dc9f3.png">

**Comment by scd** [comment]
I think we should be solving this in css. @brendanheywood what do you think?

**Comment by brendanheywood** [comment]
Yes, maybe. I'd like to avoid having css dependent on each language, it would make testing and introduce a lot of edge case bugs.

This class of issue is going to come up a lot, either words being too long, or for some language I can imagine them being way too short (eg asian character languages) and so there being heaps of whitespace. This needs a lot of thought. My first rule would where ever possible to try and fix it in the lang packs by finding a balanced set of translations. That's not always going to be possible though. Next would be some semi cheating fixes like allowing hyphenation in css across the board, but that could be even worse. Then I'd probably look into just more relaxed css that accommodates more languages but means English could be worse off.

**Comment by UFU608** [comment]
Changed some translations, still minor tweaking is required - please adapt

**Comment by scd** [comment]
Experimental feature of having an .abbr key for some translations (eg `col-header.height.abbr`).

I code the template such that if a text is longer then trigger characters it uses the abbr version.

**Comment by UFU608** [comment]
Tried it but haven't seen it working. Should it work here?
<img width="817" alt="screen shot 2016-08-16 at 19 25 31" src="https://cloud.githubusercontent.com/assets/19162952/17708930/639c782c-63e7-11e6-9144-b5a2676b8437.png">
I added abbreviations for: col.header.height,abbr and col-header.difficulty-band.abbr

**Comment by scd** [comment]
@UFU608 is this still an issue?

**Comment by UFU608** [comment]
Yes it is

**Comment by scd** [comment]
Did you try the .abbr keys? 

This gives you the ability to specify a shorter name for column headings. This is standard practice for column headings in spreadsheets so I think we should experiment with it here. Note it does not have to be the full word, just an understandable abbreviation.

**Comment by UFU608** [comment]
The last one I found was dbconfig.category.description-type.access-issues and I added an abbreviation now. I closed it until we find a new one.
