### ISSUE TITLE
Recent ascents list in profile page not handling partial dates correctly.

### ISSUE THREAD

**Issue by scd** [theCrag/website#2271]
This last one is quite strange! If you check this profile (https://www.thecrag.com/climber/yves_froyen) you’ll see that the Recent ascents are dated 1st Jan 1970. The issue is that if you check them (as an example the first one: https://www.thecrag.com/ascent/566087703) it is suppose to be 2002. The bug might be caused by registering the ascent with only the year (in the ascent details the year is registered as 2002-00-00).

**Comment by nclementel** [comment]
I thought about this a little bit more and I think that the 00-00 for month and day is considered a wrong input and results in a conversion of the date to Unix timestamp returning a zero result. Therefore it goes back to Unix epoch, indeed 1st Jan 1970.

**Comment by scd** [comment]
It will only be wrong in the display template. The database is ok with it

**Comment by scd** [comment]
Fixed in simon's dev

@brendanheywood I have written a translate helper for this so we have one place to deal with date translations. I have partially implemented date translations. Note that the Date::Format only supports limited languages, so I am doing some post format manipulation.

Anyway call the dateFormat function looks like this in the template:

```
<% formatDate $ascentDate, format => "%a %o %b %Y", format_partial_month => "%b %Y" %>
```

**Comment by brendanheywood** [comment]
cool, one trick that moodle uses is the date format itself can be a lang key, so you could say something vaguely like:

<% formatDate $ascentDate, format => "dates.full", format_partial_month => "dates.month" %>

This may or may not have limited value here with us.

**Comment by scd** [comment]
There is a wider question on how we want to standarise dates in the system. I think we should standardise date formats so we never use "%a %o %b %Y" but rather something like "date-with-words".  What do you think?

This has several advantages:
  * standardise output
  * tinker in one spot
  * the label also defines how to handle partial dates
  * an explicit parameter which told me if we even have to do any translations and the nature of the translations.

Our system default format should be "yyyy-mm-dd". So if we don't specify any format there are no translations necessary.

We want to translate months in the system anyway so we already have keys like `system.month.jan.short`. I am just reusing them for the translations.

The one thing I have not implemented is the translations for st in 1st. I want to understand the nature of this a little bit more. My preference would be to make a general solution so that if we use 1st in a leader board it is the same as 1st day of the week. I am not sure if this is valid yet.

**Comment by scd** [comment]
So I have now implemented it as follows:

```
<% formatDate $ascentDate, format => 'with-words' %>
```

The `with-words` format uses full format = "%a %o %b %Y", month format = "%b %Y", year format = "%Y" and triggers the short month name translations and day of week translations

If you specify
```
<% formatDate $ascentDate  %>
```
The `default` format will be used which does not require translations.

I think this is really good and will solve several issues.

**Comment by scd** [comment]
FYI Date::Format only has limited I18N support (I think about 5 languages and it does not align with keys). I don't want to rewrite this so we are doing post format text replacements for translations.
