### ISSUE TITLE
Import logbook should accept files with just a line feel rather than a new line

### ISSUE THREAD

**Issue by scd** [theCrag/website#2279]
- [x] \n
- [x] \r\n
- [ ] \r

I think we need to gobble the whole file into a single variable, rather than a line at a time then split. This needs restructing as the function use the file handle. We also need to think about big files which could be a problem using this method.

**Comment by scd** [comment]
For failure case use Simon's pc ~/Downloads/climbs3.csv file or look for email from Brendon Jones

**Comment by rouletout** [comment]
@nicHoch is this still a thing?

**Comment by nicHoch** [comment]
will not be supported in near future
