### ISSUE TITLE
altomijares directly refering to images in the now defunct image volume

### ISSUE THREAD

**Issue by scd** [theCrag/website#2283]
```
[Tue Jul 26 10:10:39 2016] [error] [client 88.16.171.220] File does not exist: /opt/op/CIDS/files/image/photo/00004, referer: http://altomijares.org/wpcrag-node/?wpcrag_tab=photo&thecrag_node_id=190488567&lang=es
```

@nicHoch we should work out a plan for this.

**Comment by scd** [comment]
for debugging try topo/00003/fixedheightmedium/834954936.jpg

**Comment by scd** [comment]
@nicHoch I have updated apache config and hot fixed this to map incoming topo and photo requests to the new urls. Please confirm that this is working on your end.

Note that the dimension and volume information will stop coming through in the API as it is no longer calculated for new images. This means you will eventually have to touch the altomijares code.

Please close if you are happy.

**Comment by nicHoch** [comment]
thanks for the ... kick 
this is on my to do list.
i will take care today

**Comment by nicHoch** [comment]
@scd 
the api/photo/ids endpoint does not provide the new photo format data: hashID ...

**Comment by scd** [comment]
try again now.

There is a fairly deep rabbit warren of changes resulting from changing image management.

**Comment by nicHoch** [comment]
it is working well. Is there a documentation how to control the dimensions of the thumbur endpoint?
I am poking around in the dark ...

**Comment by scd** [comment]
Look on the thumbor website. Their doco is pretty minimal though.

My implementation is in the WebHelpers.pm file. 

Here is the snippet which may help you:

```
  $h = int($h+0.5) if $h;
  $w = int($w+0.5) if $w;
  die "Error generating image URL: no width or height" unless $w or $h;
  $url .= "${w}x${h}/";
  $url .= "filters:rotate($options{rotate})/" if $options{rotate} and $options{rotate} =~ /^(90|180|270)$/;
  #$url .= "$labelA/$labelB/$options{hashID}";
  $url .= $stubPath;
```

Rotation only works for 90/180/270. If both w and h are supplied then thumbor will crop otherwise it will scale to the dimension you specify
