### ISSUE TITLE
What to do with the mentions template

### ISSUE THREAD

**Issue by scd** [theCrag/website#2286]
I forgot we had a mentions template

http://www.thecrag.com/mentions

where you can see who has mentioned you. 

We should do more with this one

**Comment by brendanheywood** [comment]
Is that url supposed to do something?

Apache Module Load Portal Error: Error: Error generating image URL: no hashID at /opt/CIDS/perllib/CIDS/Application/WebHelpers.pm line 561. Stack: [/usr/local/share/perl/5.14.2/CGI/Carp.pm:379] [/usr/local/share/perl/5.14.2/CGI/Carp.pm:468] [/opt/CIDS/perllib/CIDS/Application/WebHelpers.pm:561] [/opt/CIDS/cgi-bin/templates/html/thecrag/minor/linkPhoto:82] [:198]

**Comment by scd** [comment]
hmm still the odd bug with the new photos. While I have not fixed the bug, I have stopped it crashing.

BTW, the mentions url is the same as your personal mentions url:

http://www.thecrag.com/climber/brendanheywood/mentions

My mentions url did not crash.

**Comment by brendanheywood** [comment]
both works now

**Comment by Mdemaillard** [comment]
I think that this link should appear in the menu under "your activity"
![image](https://user-images.githubusercontent.com/60388146/78563377-277a5480-781b-11ea-874e-da32fa7412aa.png)

**Comment by scd** [comment]
The word `activity`is used internally for site activity. I think we should just say ''Your mentions".  I like the placement of the link.

**Comment by scd** [comment]
Actually I just added and hotfixed this.

**Comment by rouletout** [comment]
@scd please add the new keys in a card - thx

**Comment by scd** [comment]
@rouletout the new key is 

template.header.menu.mentions
