### ISSUE TITLE
topo image dimension migration required - using wrong aspect ratio

### ISSUE THREAD

**Issue by scd** [theCrag/website#2290]
There is at least one problem with the Topo images using the wrong aspect ratio. When we save images we are not adjusting the width and height to take into account the aspect ratio or rotation. This is very complex and effects about 1500 topos. The problem was totally hidden the when the image volumes were being used.

I cannot do anything before next week so I have made a hack in the phototopo code to swap width and heigh it there is old volume dimensions and their aspect rations are different. 

 - [ ] establish that the native image size does not return the width and height based on exif and document in code for future logic analysis
 - [ ] on upload swap width and height for certain aspect ratios.
 - [ ] swap width and height on rotate
 - [ ] review upload code if image already exists in the system for upload
 - [ ] script that reads all original images (+photos) and works out whether the width / height should be swapped.  Review this with aspect ration for old volume system
 - [ ] There are some rotated images - work out why.
 - [ ] Update rotate back fix process to also swap width and height
 - [ ] remove phototopo hack

**Comment by scd** [comment]
Actually thinking about it more I think we should be storing width/height without taking into account exif and working out aspect ration on the fly based on exif and rot. Use the following logic orientation on the fly if:
 - [ ] swap width and height if exiforientation is 6,8,5,7
 - [ ] swap if rotate is 90, 270

So exif of 6 and rotate of 90 is two swaps which means no change.

**Comment by scd** [comment]
The calls go through `Image::getImageRecord` when getting images associated with topo/photo/...  and `queryOriginalImageRecord` when getting images in isolation and `selectOriginalImageDetail` to map a photo/topo/... id to an image record. 

There are also some bulk functions where image information may be returned: `selectSelectParamTopos` and `selectBulkPhotos`

Need an aspect rotator function which takes the image record and swaps the aspect ratio under certian conditions.

**Comment by scd** [comment]
see also #2233 #2223 #2221

**Comment by scd** [comment]
Reference topo:

http://www.thecrag.com/topo/936621639

Here is the thumbor original.

http://static.thecrag.com/img/ee/1e/ee1e1609c9e95fffd0e145778d07d32afe741335

**Comment by scd** [comment]
I have made the changes so that the width/height are dynamically swapped before template data depending on exif and template data. I have made the hot fix and am in the process of rebuilding the cache.

So the system now works as follows:
 - [ ] the db stores the absolute width and height without consideration of exif.
 - [ ] all the system access functions now call an aspectRotator function which swaps the width and height depending on the settings of the exif and rotation fields.
 - [ ] the template uses the width and height without consideration of exif or rotation
 - [ ] thumbor uses exif and the rotation supplied by the url. It also uses the crop/scale modifiers supplied in the url. It does not use any database settings.

This seems to work fine on my dev. I hope I don't have a logic flaw, because this has taken a while to work out.

**Comment by scd** [comment]
Nup, this sucks. There is something still wrong. Two reference topos with different results

http://www.thecrag.com/topo/936621639
http://static.thecrag.com/img/ee/1e/ee1e1609c9e95fffd0e145778d07d32afe741335 - 1936x2592 
Exif Orientation: 6
In our DB: 2592x1936
Image with exif removed: 2592x1936

https://www.thecrag.com/topo/276959622
http://static.thecrag.com/img/8c/7d/8c7dc9b58ea9c9320cd8003115c0349129a9b4ea - 1344x1792
Exif Orientation: 6
In our DB: 1344x1792
Image with exif removed: 1344x1792

Why does thumbor rotate the first example by default?

**Comment by brendanheywood** [comment]
Maybe this recent bug? https://github.com/thumbor/thumbor/issues/550

**Comment by scd** [comment]
Reinstalling does not fix on my dev. In debugging I have found one issue on our end. 

Without exif thumbor treats the WxH spec as the pre rotation dimensions rather than the view port dimensions. For example compare

http://static.thecrag.com/img/x320/ee/1e/ee1e1609c9e95fffd0e145778d07d32afe741335  - 239x320
http://static.thecrag.com/img/x320/filters:rotate(270)/ee/1e/ee1e1609c9e95fffd0e145778d07d32afe741335   - 320x239

However we need the viewport width and height, which means we needs an extra variable to tell us that we have flipped the aspect.

Now that I have the non-exif use case out of the way I can now look at the exif issue.

**Comment by scd** [comment]
I have now established that thumbor does not like the exif for some images, so although we read the exif ok thumbor rejects the orientation because there are exif read errors.

This file (with exif orientation of 6)

http://static.thecrag.com/img/320x/8c/7d/8c7dc9b58ea9c9320cd8003115c0349129a9b4ea

causes the following error (at least in dev). This is with the latest version of thumbor.

```
2016-08-02 02:57:31 thumbor:ERROR Ignored error handling exif for reorientation
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/engines/__init__.py", line 229, in _get_exif_segment
    segment = ExifSegment(None, None, self.exif, 'ro')
  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 856, in __init__
    DefaultSegment.__init__(self, marker, fd, data, mode)
  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 150, in __init__
    self.parse_data(data)
  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 902, in parse_data
    ifd = IfdThumbnail(self.e, offset, self, self.mode, tiff_data)
  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 466, in __init__
    self.ifd_handler(data)
  File "/usr/local/lib/python2.7/dist-packages/pexif.py", line 826, in ifd_handler
    raise JpegFile.InvalidFile("Thumbnail doesn't have an offset "
InvalidFile: Thumbnail doesn't have an offset and/or size
```

Effectively this means that for some files the exif orientation will not be honoured. Massive pain because I have no way of telling. The effect is an aspect ration skewing. Options
 - [ ] Turn off exif for thumbor and update data and code to correspond
 - [ ] When we come across these files remove the exif and re-upload.

**Comment by scd** [comment]
Oh, and I found yet another logic issue.
 - [ ] Viewport dimensions may be swapped twice (once for exif and once for rotate).
 - [ ] thumbor dimensions are only ever swapped once because the exif dimension is honored (except for bug).

For viewport I swap the width and height dynamically based on exif and rotate. I also supply a template flag aspectFlipped which is set based on the aspect being rotated from the view port dimensions to the thumbor input dimensions.

With the thumbor discrepency, complex logic issues, and templates using the old volume dimensions this has been a real shit of an issue to get to here. It was really very difficult to work out what the truth was because my testing was based on a thumbor discrepency.

BTW, i still don't know why there are some rotation issues which may be different again.

It's late now, 3am. Here is a check list of hot fix stuff to complete tomorrow:
 - [ ] find all templates that use the image data and add the aspectFlipped flag to generate the url
 - [ ] test system, topo facet, topo stream, add topo, rotate topo,
 - [ ] hot fix
 - [ ] refresh entity cache (flag needs updating in the topo data in the cache)
 - [ ] continue reviewing topos and fix rotated topos.
 - [ ] make announcements about topos added in the last week.

**Comment by brendanheywood** [comment]
Without knowing exactly what the current internals are, my thoughts from the outside are that perhaps the most simple / robust way of dealing with this would be:

* thumbor always ignores exif, and rotates according to what is in the db
* when a new image is uploaded we attempt to read the exif and if we can then set that as the default and allow people to rotate as normal
* do whatever we need to migrate old data to match above
* we never ever serve the original file as the browser could have different exif parsing to thumbor and rotate differently, only ever something that has been processed by thumbor and has exif stripped out (assume we already do this)

This way there is no complex logic in the templates, if the exif isn't readable then it's caught and fixed right at the start. Thoughts?

**Comment by scd** [comment]
My original preference was for thumbor to ignore exif and us to manage it. This what was done with the old system. However it is a significant piece of work as every image with an exif will have to have the rotation updated in the database and cordinated code.

It would have to be a release in it's own right. It is not going to happen for a while. I have spend four days on this rabbit hole already and I need to stop. Logged here #2303

This would fix the thumbor deficiency which is the main motivation. The rotate variable will still be required. There would still be template compexity.

We would still have to swap the view port display dimensions for rotated images, but not for thumbor inputs.

Thumbor never serves the exif, so browser interpretation will never be a problem. We have no direct access to the images, only via thumbor.

**Comment by scd** [comment]
closing
