### ISSUE TITLE
Markdown parsing results in weird image html embed

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2292]
Not clear what the user actually put into their message but the output is a bit garbled:

http://www.thecrag.com/discussion/948517728/clocks--clocks-anchor-failed-needs-replacing

**Comment by scd** [comment]
I think this is bad markdown order. Looking at the generated html
```
<a class="photo thumbnail" href="/photo/948505491" title="Clocks (22) - Anchor of <a class="internal" data-nid="13103911" href="/climbing/australia/north-shore/route/13103911">Clocks</a> (22).JPG">
```
That looks like an embedded photo then the title turned into a link to the route

**Comment by scd** [comment]
Having looked at the code it is a little more significant.

I cannot just change the order because there are cross dependencies. 

Our card embedding comes before internal links mark down.

 - https://www.thecrag.com/photo/948505491 maps to the photo card.
 - the photo card creates a title="Clocks (22) - Anchor of Clocks (22).JPG"
 - the capital internal link method maps the second Clocks to the route name. Note that the first one is not mapped because the capital internal links match requires a space not a double quote.

I am not sure what to do about this. Maybe we can change the order, which is here:

```
  $text = sanitiseText($text,%options);
  $text = markupInternalCardLinks($text);
  $text = markupOEmbed($text) unless $options{noOEmbed};
  $text = markupExternalLinks($text);

  if ( defined $routeLinkNames or defined $areaLinkNames )   {
    $text = markupInternalLinks($text,$defaultLinkStem,[((defined $routeLinkNames)?([$routeLinkStem,$routeLinkNames]):()),((defined $areaLinkNames)?([$areaLinkStem,$areaLinkNames]):())]);
    $text = markupCapitaliseLinks($text,$defaultLinkStem,[((defined $routeLinkNames)?([$routeLinkStem,$routeLinkNames]):()),((defined $areaLinkNames)?([$areaLinkStem,$areaLinkNames]):())]);
    $text = markupAcronymLinks($text,$defaultLinkStem,[((defined $routeLinkNames)?([$routeLinkStem,$routeLinkNames]):()),((defined $areaLinkNames)?([$areaLinkStem,$areaLinkNames]):())]);
  }
  $text = markupMentions($text,%options,type=>'html');
  $text = markupHTMLHashTags($text);
  $text = markupHTMLEmoji($text);
  $text = convertDTDD($text);
  $text = markupKeywords($text,$keywords) if $keywords;
```

I just think it will have cross effects.

**Comment by brendanheywood** [comment]
Wikis and markdown don't have formal grammar's so the common workaround for this is to reversibly hash or obfuscate bits you don't want to be processed twice and then undo them at the end.

So something like

```
https://www.thecrag.com/photo/948505491

Something about Hope
```

then markupInternalCardLinks is currently something like

```
<a href="https://www.thecrag.com/photo/948505491">Hope</a>

Something about Hope
```

but then it's also munges it into something like

```
TOKEN_STARTbase64hashofaboveTOKEN_END

Something about Hope
```

then apply all the other transformations

```
TOKEN_STARTbase64hashofaboveTOKEN_END

Something about <a href="/hope">Hope</a>
```

 and then reverse them at the end

```
<a href="https://www.thecrag.com/photo/948505491">Hope</a>

Something about <a href="/hope">Hope</a>
```

**Comment by scd** [comment]
I should have thought about this as I have used this technique for something else once :)

**Comment by rouletout** [comment]
This looks good, closing
