### ISSUE TITLE
style error in streams

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2293]
<img width="613" alt="2016-07-28 09_31_28-dashboard for nicky _ thecrag" src="https://cloud.githubusercontent.com/assets/2226714/17204521/4f237d46-54a6-11e6-8afb-4fe484581eff.png">

If a stream entry ends with an image the next entry needs some newline or clear.

**Comment by scd** [comment]
I know what that is. I made maps take up less screen space by using float left. However the float left interfers with the avatar float.

**Comment by brendanheywood** [comment]
Don't float them, make each image div online block, and make sure it's container is a block. No clearing which means less other knock on hassles

**Comment by scd** [comment]
good advice, worked easily and perfectly
