### ISSUE TITLE
URGENT: Translation system messed up

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2294]
It seems that the translation system is not working properly. Only German is available as language! All other languages are not there to work on. Please fix asap as 3 people try to work on it at the same time and can't!

![screen shot 2016-07-28 at 15 50 38](https://cloud.githubusercontent.com/assets/19162952/17216682/ef10a852-54e1-11e6-9b6e-ac75cc4d9435.png)

**Comment by scd** [comment]
there was a merge conflict issue on dev which needed manual intervention. This left spurious lines in the language file and caused the system to fail.

Fixed now

Sorry that was probably me not properly reading diagnostics when I committed the work. This would explain why the system was not working at all, but not why only German was working.

My guess is that this is strange UI behaviour if the system stops working after loading the UI.

I am going to close this now, but feel free to re-open if this occurs again.
