### ISSUE TITLE
Translating '4th' in dates needs implementing

### ISSUE THREAD

**Issue by scd** [theCrag/website#2299]

**Comment by scd** [comment]
added a day-of-month key in simons dev

```
 "system.day-of-month.1st": "1st",
  "system.day-of-month.2nd": "2nd",
```

**Comment by brendanheywood** [comment]
It's not simple.

This isn't just the 1st day of the month and has nothing to do with months or days it applies to all numbers. We have the 1st, the 2nd, the 3rd, 4th and then the 11th, 12th, 13th, 14th then the 21st, 22nd, 23rd, 24th etc. English is crazy and other languages are crazy in other ways. Don't try and implement this at all with lang keys, right just call a lib that does it and can have a locale that we set.

I'm not sure what perl libs we should be using for this, but google something like "perl i18n ordinal suffix" and have a browse

**Comment by scd** [comment]
Here is a perl module:

https://github.com/labster/p6-Lingua-Number

I am happy to leave it as I have done it for dates for the time being for a couple of reasons.
  * I am not experienced enough to know that all languages even use ordinals for dates. While it is common in english to use 1st in a date, this might not be done in other languages
  * I have been pretty unhappy with every perl module I have used for translations. The support seems to be limited and random and ends up being a time sink before I abandon.
  * Once we get ordinals implemented then we can just drop in replace if appropriate.

**Comment by brendanheywood** [comment]
If you leave it as-is in the mean time, do you also handle 3rd, and do you also correctly handle 11,12,13?

**Comment by scd** [comment]
yup. 31 keys. I know stupid brute force.

**Comment by brendanheywood** [comment]
oh, why not just 4 keys?

**Comment by scd** [comment]
other languages may have different rules.

**Comment by scd** [comment]
I am closing this as because I have created a different issue for a more general implementation - see issue #2321
