### ISSUE TITLE
should we show karma in the climber card for accounts that have choosen to be excluded from karma leaderboard

### ISSUE THREAD

**Issue by scd** [theCrag/website#2301]
@nicHoch this is one for you

You are not listed in the Karma leaderboard but your Karma is shown in your climbers card for ascents:

https://www.thecrag.com/climbing/world/contributors

**Comment by rouletout** [comment]
@nicHoch thoughts as Data Officer on this one?

**Comment by nicHoch** [comment]
suggest to close the issue until users will complain
