### ISSUE TITLE
Translations: Title page shows "OR" between login buttons

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2309]
Seems the key is not implemented there as it is in the translation list
<img width="552" alt="screen shot 2016-08-04 at 11 07 11" src="https://cloud.githubusercontent.com/assets/19162952/17396411/9e1c8144-5a33-11e6-94e6-4ecb0be83406.png">

**Comment by Mdemaillard** [comment]
also, one is infinitiv, one imperativ. Should probably be "Hinein Schnuppern"

**Comment by rouletout** [comment]
This page actually doesn't exist anymore like this but the "or" is still not translated. Onyl it is here now:

<img width="490" alt="Screenshot 2020-04-06 at 08 45 24" src="https://user-images.githubusercontent.com/19162952/78571134-17468300-77e3-11ea-8281-8bae2947f9e9.png">

but correctly translated here:

<img width="762" alt="Screenshot 2020-04-06 at 08 45 47" src="https://user-images.githubusercontent.com/19162952/78571227-3218f780-77e3-11ea-8f66-01457395155b.png">

**Comment by rouletout** [comment]
moved to missing key list, closing here
