### ISSUE TITLE
Translations: Country not translated

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2310]
The keys for countries are translated but not shown on dev

<img width="499" alt="screen shot 2016-08-04 at 11 36 21" src="https://cloud.githubusercontent.com/assets/19162952/17397323/c80d4b1a-5a37-11e6-9ab7-3f092fda0003.png">

**Comment by nclementel** [comment]
In dev (but not in prod) the translation worked only for the climber profile in the general climbers page

![screen shot 2016-08-14 at 16 01 11](https://cloud.githubusercontent.com/assets/19304867/17649556/af211f92-6238-11e6-807b-ce953af28ae2.png)

**Comment by scd** [comment]
fixed
