### ISSUE TITLE
Warn about banned routes better

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2311]
See https://www.thecrag.com/discussion/948517728/clocks-anchor-failed-needs-replacing#m954357639

1) should the access field inherit to route pages?
2) should we something more major based on inheriting the banned tag, eg showing this in the route title

**Comment by scd** [comment]
banned tag should inherit. access field has too many words to inherit to every route. We accidentally did this for a while and decided it was not a feature we wanted.

**Comment by brendanheywood** [comment]
I am thinking of a hybrid, ie if the banned (or illegal) tag is present then also show the field so you can see why it's closed

**Comment by scd** [comment]
I have fixed most of this on my dev. It requires some data config updates in the database to make inheritable to route level, which I have done in prod.

Things still to consider:
 - [ ] do we want an icon for closed and illegal.
 - [ ] we could make it clearer in the PDF. 
 - [ ] we could make it clearer on the route and area page. In header somewhere?

**Comment by brendanheywood** [comment]
Mockup with both an extra big style tag in the route name + an extra Access summary detailing which node the tag is applied to

![image](https://cloud.githubusercontent.com/assets/187449/17506488/a1b8b2e2-5e4c-11e6-8659-9352a46cf3ce.png)

I'm less worried about PDF as you get the whole crag in context, there main issue here is that you are viewing a single route in isolation.

**Comment by brendanheywood** [comment]
Also we need to pay careful attention to how this looks in responsive mobile mode, much of this gets tucked away so the header tag I think is pretty important.

**Comment by Drazhar** [comment]
This is also the case for closed crags.

Right now the only thing you can do is add the "illegal" or "closed" tag and write in the "Access issues", that the crag shouldn't be climbed anymore.

Something like closing the crag, that nobody can tick anything anymore and a big disclaimer is shown would be great.

**Comment by brendanheywood** [comment]
Ha didn't even remember this one existed this is more or less done now.

I've mostly I've been focused on the 'Closed' tag. Is there any point to the 'Illegal' one? There is some inconsistency at the moment, I think the second tag is very low value and probably negative value as it detracts from the closed one and creates ambiguity.

There are 293 Closed areas:
https://www.thecrag.com/areas/with-structured-tag/198053209/?sortby=at,desc

And 93 Illegal ones:
https://www.thecrag.com/areas/with-structured-tag/198053203/?sortby=at,desc

I think we merge all those across and then remove the tag, @scd ?

**Comment by scd** [comment]
+1

**Comment by lordyavin** [comment]
We have a language problem here. If we (Germans) are not allowed to climb a rock for nature conservation reasons, then we speak of "locked/off-limits/prohibited", not "closed". We say "closed" when a business is closed. But this is mostly about legal prohibitions. 

So what do you understand by the term "closed"? In Germany (Europe?) it is mostly illegal to climb on a closed rock.

**Comment by brendanheywood** [comment]
Probably the closest in the list you gave would be 'prohibited', but it means any or all of those. Being closed doesn't not always mean illegal. It may just mean closed to the public. It may mean temporarily closed like after a bush fire, in the same sense as a shop may be closed.

If it is mostly illegal to climb on a closed rock, that just reinforces my thoughts to merge them as they mean basically the same thing. It sounds like we just need to rename it in german to something more general, maybe verboten?

**Comment by rouletout** [comment]
@lordyavin I think this is just a question of translation - the correct German word from ym point of view is "gesperrt" - no matter if illegal or simply for another reason...

**Comment by lordyavin** [comment]
I agree that "gesperrt" is the correct term.

**Comment by brendanheywood** [comment]
We'll I'm proposing to remove the illegal tag completely. Is there any point to it at all?

**Comment by rouletout** [comment]
fine with me

**Comment by scd** [comment]
fine with me

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by brendanheywood** [comment]
This is totally done now with the closed tags and warnings

**Comment by lordyavin** [comment]
I'll think I have to reopen the issue because closed route don't get the closed sign in the index list: See this [boulder block](https://www.thecrag.com/climbing/germany/saechsisches-huegelland/area/2447482149). The problem [AO Kampagne](https://www.thecrag.com/climbing/germany/saechsisches-huegelland/route/3696831570).

**Comment by scd** [comment]
I have fixed this for next release. Please close again once you have checked after next release.

How common is closing routes as opposed to closing areas. There may be other things not working with closed routes?

**Comment by lordyavin** [comment]
In my home crag there are routes that are individually closed too. So it is a use case but a rare one I think.

**Comment by georg-d** [comment]
@scd 
In my home region (tri-nations-region France/Germany/Switzerland), we've yearly closings due to bird nesting; usually sectors/cliffs/crags, sometimes only few routes (usually adjancent), and I can't recall I ever heard a whole area (e.g. [Südschwarzwald](https://www.thecrag.com/climbing/germany/schwarzwald/area/2924497773)) or region (e.g. [Grand-Est](https://www.thecrag.com/climbing/france/alsace-lorraine)) being closed. Other closing reasons are rare and usually affect a sector/cliff/crag and sometimes single routes (e.g. after rockfall) and I can't recall any closing of whole areas or regions.

**Comment by georg-d** [comment]
> I agree that "gesperrt" is the correct term. But what about "illegal"/"verboten".

For my language feeling, the current translation "verboten" seems better than "illegal" because I associate "illegal" more with crime while "verboten" more with access restrictions like street sign "Durchfahrt verboten". Moreover, I feel "gesperrt" is to be sufficient general to include "verboten/illegal", hence no translation update required when @brendanheywood joins both tags together.

**Comment by scd** [comment]
I was more referring to a generic area versus route. By area I meant sector or cliff. I just have not reviewed any code for individual closed routes.

**Comment by rouletout** [comment]
This is done, closing.
