### ISSUE TITLE
Translation: column header keys missing?

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2314]
These 2 tables should have the same column headers but the "non-logged-in" version is not translated.
<img width="767" alt="screen shot 2016-08-10 at 09 17 07" src="https://cloud.githubusercontent.com/assets/19162952/17548778/b1f092b4-5eed-11e6-9f58-0c5287a01d47.png">
<img width="678" alt="screen shot 2016-08-10 at 09 17 19" src="https://cloud.githubusercontent.com/assets/19162952/17548783/b99d9e26-5eed-11e6-9d87-b40e3fadc590.png">

**Comment by scd** [comment]
fixed on simons dev
