### ISSUE TITLE
Error when editing ascents

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2315]
I had marked 3 routes to get the ascents edited when this occured:

<img width="1384" alt="screen shot 2016-08-10 at 13 09 17" src="https://cloud.githubusercontent.com/assets/19162952/17553089/151c0182-5f04-11e6-8531-86ef6715ed7a.png">

**Comment by scd** [comment]
Does it work if you use the plus character '+' instead of space between the ids

**Comment by UFU608** [comment]
I can not reproduce it anymore

**Comment by scd** [comment]
closing, but reopen if you can reproduce.

**Comment by UFU608** [comment]
Did it again ;-)
http://www.thecrag.com/ascents/at/17713597%2017713651/by/843088251

![Uploading Screen Shot 2016-08-18 at 15.57.43.png…]()

**Comment by scd** [comment]
What is your workflow to get here.

Note the difference between the following URLs. The following works:

http://www.thecrag.com/ascents/at/17713597+17713651/by/843088251

and this one is broken:

http://www.thecrag.com/ascents/at/17713597%2017713651/by/843088251

What I want to know is what your workflow was for the system to create the url with spaces.

**Comment by UFU608** [comment]
So I go to the Index and select 2 routes using the checkboxes. Then I use the menue at the right and choose Your Ascent History resulting in a list view of the 2 (see screenshot). There then I click on Edit Ascent (next to the route) which opens the edit ascent form. I do a change and when I hit Save the error appears (even though it seems it is saving the change).
<img width="1062" alt="screen shot 2016-08-19 at 10 00 30" src="https://cloud.githubusercontent.com/assets/19162952/17803028/0069a1b2-65f4-11e6-81cf-17b25cc5c454.png">

**Comment by scd** [comment]
Ah, ok. The error is in the original selection. you should only be able to edit one ascent at a time. Our form currently does not support multiple ascent editing.

**Comment by scd** [comment]
I have hot fixed this so both urls work.
