### ISSUE TITLE
Translation keys "don't add up to German sentence"

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2316]
upload (past) and multiple photos are separet keys but can't be combined like that to form a correct German sentence. It should be: "USER hat mehrere Fotos von AREA hochgeladen"

<img width="765" alt="screen shot 2016-08-10 at 18 17 44" src="https://cloud.githubusercontent.com/assets/19162952/17561548/e382d4c0-5f26-11e6-8cf0-8cf09a8c07dc.png">

**Comment by UFU608** [comment]
Same issue with this one:
<img width="691" alt="screen shot 2016-08-10 at 18 21 35" src="https://cloud.githubusercontent.com/assets/19162952/17561649/609471bc-5f27-11e6-950d-92c319c8afd0.png">

**Comment by scd** [comment]
There are four keys which control the sentence structure for the streams. I think if you play with these you should be able to adjust the result to what you want.

 "template.stream.summary": "{who} {action} {what}.",
  "template.stream.summary.at-crag.mentions": "{who} {action} {what} at {crag} and mentioned {mentions}.",
  "template.stream.summary.at-crag": "{who} {action} {what} at {crag}.",
  "template.stream.summary.mentions": "{who} {action} {what} and mentioned {mentions}.",


For example would it fix things by changing `template.stream.summary` to `{who} {what} {action}`

**Comment by UFU608** [comment]
Unfortunately not - the problem is that for some verbs the action is split and the what is put between the 2 parts of the verb. E.g. added (past) ist "hat <what> hinzugefügt" or "fügte <what>  hinzu". Same for uploaded. Any ideas?

**Comment by scd** [comment]
@nicHoch any ideas given you speak both german and have a technical understanding.

It sounds like the sentence structure should be something like: `{user} {action.modifier} {what} {action}`

**Comment by scd** [comment]
@UFU608 I have an experimental solution for this. Please add `action.modifier` to the german translations to the following keys:

```
  "template.stream.summary": "{who} {action.modifier} {what} {action}.",
  "template.stream.summary.at-crag.mentions": "???.",
  "template.stream.summary.at-crag": "???.",
  "template.stream.summary.mentions": "???.",
```

Note that I have had a go at the first one, but you will have to do all of them. 

Then go to each action key modifier (eg `system.db-interaction.upload.past.modifier`) an input a modifier value. 

To find all the modifiers do a search `modifier$` in the translate UI.

If it does not work then please let me know if it is conceptual thing or just a bug.

**Comment by UFU608** [comment]
I tried to do it but get this error when I enter a translation for the modifier:
<img width="1342" alt="screen shot 2016-08-15 at 16 07 38" src="https://cloud.githubusercontent.com/assets/19162952/17667078/9b067284-6303-11e6-9755-85c07b536d9c.png">

**Comment by scd** [comment]
try again.

**Comment by UFU608** [comment]
Error is gone, we have one more issue and one simplification:

1) it would be sufficient to have only one modifier that is independent of the verb (e.g. system.db-interaction.delete.past.modifier is the same as system.db-interaction.discuss.past.modifier, etc.)

2) we need to distinguish between singular and plural as this changes the modifier (e.g "Simon edited a route" or "Simon and Brendan edited a route") - so we need "only" 2 modifiers

Can this be done?

**Comment by scd** [comment]
> it would be sufficient to have only one modifier that is independent of the verb (e.g. system.db-interaction.delete.past.modifier is the same as system.db-interaction.discuss.past.modifier, etc.)

That can be done in the translation text itself. For example:

```
 "template.stream.summary": "{who} someverylonggermanwordforsomethingquiteminor {what} {action}.",
```

> 2) we need to distinguish between singular and plural as this changes the modifier (e.g "Simon edited a route" or "Simon and Brendan edited a route") - so we need "only" 2 modifiers

Yes this is possible. Implement as singular (above) for now and then I can address the second part of the issue separately. It would be good to put several examples in this issue so I can see what the system is producing and what it should produce.

**Comment by UFU608** [comment]
Just to be sure on (1) - I'll put the action modifier in hardcoded, correct? No issues with (2) then?

**Comment by UFU608** [comment]
OK I hardcoded the singular (hat) and tested a bit, looks good also with the keys template.stream.tick-event....
Let me know when you need help with the plural (haben) ;-)

**Comment by scd** [comment]
@UFU608  can we close this?

**Comment by UFU608** [comment]
Do we have the plural now?

**Comment by scd** [comment]
Please give me two examples, one of the singular and the other of the plural

**Comment by UFU608** [comment]
Simon, let's close that for the time being. I'm actually not sure that we have a situation in the streams where we need the plural as all actions are done by a single person. The current construct seems to work ok even though it is not perfect German. I'll open again if I find a case where we need it.
