### ISSUE TITLE
Similar to FA and FFA, be able to 'Set' / scrub / bolt / maintain a route as a tick type, or stream event type

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2319]
Whatever we do here would have the same treatment as FA and FFA, so linking between the tick as a subjective journel of the process, and the route FA / FFA / Set data which is the resulting end state.

![image](https://cloud.githubusercontent.com/assets/187449/17652928/4b9a9f62-62cd-11e6-9a36-88daca219b66.png)

**Comment by rouletout** [comment]
Introduced route maintenance a while back, also notable ascents as more general way to record history, closing
