### ISSUE TITLE
helper function or library for translation of ordinals (eg 4th)

### ISSUE THREAD

**Issue by scd** [theCrag/website#2321]
Once implemented also use in dates (see issue #2299)

**Comment by brendanheywood** [comment]
My gut tells me that this shouldn't even be perl, there should be very solid posix / c libs from decades ago  that sort this properly and perl should just expose it (in theory!).

This seems to be pretty close for dates (but no korean):

```
brendan@zebrafish 04:45:24 /var/www/moodle.local $ perl -MDate::Format -e 'use Date::Language; my $l = Date::Language->new('English'); print $l->time2str("%a %o %B\n", time());'
Tue 16th August
brendan@zebrafish 04:45:27 /var/www/moodle.local $ perl -MDate::Format -e 'use Date::Language; my $l = Date::Language->new('German'); print $l->time2str("%a %o %B\n", time());'
Die 16. August
brendan@zebrafish 04:45:34 /var/www/moodle.local $ perl -MDate::Format -e 'use Date::Language; my $l = Date::Language->new('French'); print $l->time2str("%a %o %B\n", time());'
mar 16th ao�t
brendan@zebrafish 04:45:41 /var/www/moodle.local $ perl -MDate::Format -e 'use Date::Language; my $l = Date::Language->new('Italian'); print $l->time2str("%a %o %B\n", time());'
Mar 16th Agosto
```

Need to make sure we don't also miss:
* [ ] integer ordinals
* [ ] very large and small number (ie commas, periods, decimals), maybe percentages are different too?
* [ ] currencies

**Comment by scd** [comment]
> This seems to be pretty close for dates (but no korean):

Yes my understanding was that we could use the module itself. We use Date::Format::time2str which does translations, but the devil is in the details. It only supports 8 languages. So we are on our own.

Actually we don't need to translate all possible date combinations, just the ones we use. It ends up being pretty simple. Have a look at `formatDate` in `CIDS::Application::Translate` module.

I guess this is why having Korean as one of our first languages has it's advantages.

**Comment by scd** [comment]
We have bespoke date functions for translations now
