### ISSUE TITLE
make home page content customised by country of IP address

### ISSUE THREAD

**Issue by scd** [theCrag/website#2322]
Use the getDefaultCountryFromIP function in the CIDS::Application::Interface module

**Comment by scd** [comment]
@brendanheywood the home page template data now has country based on IP address. `data->{country}` 

It has got a lot of the data in that variable as would the visiting the area template.

Also default sponsors are provided. Note that sponsors have to be explicitly configured to show on the home page.

**Comment by brendanheywood** [comment]
This is working from a nav context point of view and everything is in place for further additions later
