### ISSUE TITLE
add alternate name to import area process

### ISSUE THREAD

**Issue by scd** [theCrag/website#2325]

**Comment by scd** [comment]
added column for alternateRouteName for creating routes only.

**Comment by nicHoch** [comment]
hi @scd 
i would need a alternate name also on areaLevel soon.
any why that you could hack something in?

**Comment by scd** [comment]
This seems to already be there. Call the column alternateNameAreaLevel1 or languageNameAreaLevel1 where the number corresponds to the depth of the area relative to the import area.

Please test before doing live, because I cannot remember it being used. I just tested the alternateNameAreaLevelX locally but not yet the language variant.

**Comment by scd** [comment]
@nicHoch please close this issue when you are happy.

**Comment by nicHoch** [comment]
worked very vell
