### ISSUE TITLE
Site policies error

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2329]
For the following links in [https://www.thecrag.com/article/Policies](url):

Special Projects
Adding Climbs Reminder Policy
Publisher Participation Policy
Publisher Copyright Protection Policy

> Error

> Cannot continue process: Error building terms report: Internal error, empty report - have you set up translations

> State:

> Error Code: 2

> CodeReference: CIDS::Process::ConfigureSystem::TermsVersion, /opt/CIDS/perllib/CIDS/Process/ConfigureSystem/TermsVersion.pm, 51

**Comment by scd** [comment]
Those policies are not really relevant anymore. I am removing the links to them, because we don't want to translate them and if we do they need a total rework.
