### ISSUE TITLE
visiting an climber page which does not exist should give 404 page

### ISSUE THREAD

**Issue by scd** [theCrag/website#2331]
There are a couple classes of urls whih should server 404's but serve something else weird instead: 
Eg 

* [x] http://www.thecrag.com/climber/idontexists -> should be 404 or climber specific 404 help / search page
* [x] http://www.thecrag.com/article/wrong -> should be 404, and / or redirect to root article index page

**Comment by scd** [comment]
The article handler was not returning correctly when there was a missing article. This is fixed.

I have also mapped the pageType so it now shows `climber not found` or `article not found`, etc

**Comment by brendanheywood** [comment]
:+1:
