### ISSUE TITLE
Translators help article

### ISSUE THREAD

**Issue by scd** [theCrag/website#2334]
Need a translators help article. Possibly one, maybe several.
- [ ] becoming a translator
- [ ] help with support emails
- [ ] technical how to
- [ ] keys policy
- [ ] suggested workflows for starting a new language

Note that the text for the text and images for this may need to be prepared. Images must be installed on the server by simon, while the text can be prepared by anybody.

**Comment by rouletout** [comment]
We have a solid process by now and "offline" help article, closing
