### ISSUE TITLE
Fuzzy search cgi error

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2337]
http://www.thecrag.com/nodes/fuzzy-search/mt%20warning?S=mt+warning&ST=w

![image](https://cloud.githubusercontent.com/assets/187449/17845706/35d9f7c6-6887-11e6-9fca-de8cc81ec6a5.png)

**Comment by scd** [comment]
the space in the fuzzy search is killing it for some reason

**Comment by brendanheywood** [comment]
Is this related to the other hot fix you just did for the facets?

**Comment by scd** [comment]
Yes, just fixing now. Actually there was an underly issue already if you searched for something like 'some+climb'.

**Comment by scd** [comment]
fixed

**Comment by brendanheywood** [comment]
Except mount warning doesn't even come up :(

http://www.thecrag.com/climbing/australia/mt-warning-wollumbin-shield

**Comment by scd** [comment]
Yes but different issue. The fuzzy search misses quite a few edge cases. The full search for the area comes up.
