### ISSUE TITLE
Missing stream keys

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2339]
- created {count} routes/areas
- updated {count} routes/areas
- with
- full details
- "actions"

![screen shot 2016-08-21 at 16 43 38](https://cloud.githubusercontent.com/assets/19304867/17863163/da9528a6-6898-11e6-89a7-c855f29220da.png)
- "comments"

![screen shot 2016-08-22 at 18 48 46](https://cloud.githubusercontent.com/assets/19304867/17863218/2649621c-6899-11e6-988e-829c4434d78c.png)
- "title" in profile page

![screen shot 2016-08-22 at 18 52 20](https://cloud.githubusercontent.com/assets/19304867/17863365/abd9d8bc-6899-11e6-8b5a-b89dc2c00aee.png)
- "feed updates" in profile page

![screen shot 2016-08-22 at 18 55 06](https://cloud.githubusercontent.com/assets/19304867/17863460/fa478404-6899-11e6-83f8-6b8713dab1aa.png)

**Comment by brendanheywood** [comment]
Duplicate and now fixed
