### ISSUE TITLE
Temporary snap marker at "Locate ..."

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2343]
Hey,

just saw a small confusing "bug". When you place a temporary snap marker while locate a boulder/area/... the GPS coordinates of the mouse are shown in Lat/long, which typically is the standard. But if you place a Temporary snap marker (eg. coordinates from a picture taken), you have to put in long/lat.

This was a bit confusing to me ;)

![longlatconfusion](https://cloud.githubusercontent.com/assets/3040689/17888113/bda525fc-6929-11e6-8c14-e3a37c02b018.png)

**Comment by Drazhar** [comment]
Also in the route description its long/lat instead to lat/long. Would be great to have the same format everywhere.

![longlat_latlong](https://cloud.githubusercontent.com/assets/3040689/17888853/57a6c4d2-692d-11e6-962f-1df74b6c4efa.PNG)

**Comment by scd** [comment]
fixed in simon's dev

**Comment by scd** [comment]
also fixed a bug with updating lat long
