### ISSUE TITLE
world node missing in world index Api endpoint

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2344]
https://www.thecrag.com/api/index/detail/world

the root node "world" is not in the result set anymore (that was working some weeks ago).
The App needs the world node ...

**Comment by scd** [comment]
hotfixed!

please test

This happened when we added an area filter to the index. Unfortunately the world node is not an area type but a root node type. I forgot to include the root node type in the filter.

**Comment by scd** [comment]
Please close when you are happy.

Also this is a good test for app diagnostics. How hard was this to detect if you did not encounter it on your own device. 

What was the failure mode of the app. Did it download again?

**Comment by scd** [comment]
@nicHoch can we close this one now?
