### ISSUE TITLE
png topos with transparent background causes the loading symbol to show (Thumbor should strip alpha channel)

### ISSUE THREAD

**Issue by scd** [theCrag/website#2346]
The image uploads fine, but when the topo displays the loading symbol is persistently displayed over the topo:

https://www.thecrag.com/climbing/austria/area/719069031/topo#t965843799

In case this is tidied up the image is:

https://static.thecrag.com/img/fa/fe/fafe61a6cce7cd5694b84c3e10a3b2797b368b59

**Comment by scd** [comment]
Discussion here:

https://www.thecrag.com/discussion/965893668/nicky-ist-bei-dir-bei-dem-loch-topo-auch-die-ganze-zeit-das-ladesymbol#m966448860

**Comment by brendanheywood** [comment]
Need to add a thumbor filter to discard the alpha channel, or perhaps better to instead add a white layer under anything transparent as the base transparent layer may not be white. Final pic should never have an alpha channel

**Comment by Mdemaillard** [comment]
Near duplicate from #3277, except for Avatar instead of Topo

**Comment by scd** [comment]
Loading symbol not showing anymore. Closing
