### ISSUE TITLE
Change the Language in the Profile settings

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2347]
Hey everyone,

because of the current english-german mix of theCrag I changed the language in my profile setting to English.
If I want to change it back to "..." to see what's happening with the translation, an error occur if I want to save the changes. Just want to make an screenshot of it, but now it just loads forever and the error doesn't occur anymore...

**Comment by Drazhar** [comment]
![screenshot-2016-08-29-08 59](https://cloud.githubusercontent.com/assets/3040689/18043282/25c83240-6dc7-11e6-9445-3f0db2628877.jpg)

**Comment by scd** [comment]
Thanks. Just looking at this file right now out of coincidence. Fixed on simons dev
