### ISSUE TITLE
Add small badges to avatars to show editor / coordinator / supporter / admin roles (esp in forums)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2350]
General context:

* [x] supported. currently pink border but could be something nicer
* [ ] ~~private accounts???~~  (nah)

In the context of a node
* [x] Need to take into account either square or round avatar (and probably consolidate to one?)
* [ ] do we need to be able to have multiple badges?
* [x] have a badge priority, ie admin should take precedence over editor
* [ ] staff / setter in a gym (https://fontawesome.com/v3.2.1/icon/wrench)

Specifically in the context of a forum:
* [ ] who the author was, ie who start the discussion

* [x] Single avatar template with variantions
* [ ] Stacked list of avatars (horizontal - in stream, vertical?? in photos?)

**Comment by lordyavin** [comment]
Is there already a role model? Which role do I have?

**Comment by scd** [comment]
https://www.thecrag.com/settings/contributions

Where it says 'you have editor permissions' means you have an editor role for the area

**Comment by brendanheywood** [comment]
mostly done so closing
