### ISSUE TITLE
Translations: Capitalisation does not work

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2356]
There are isolated instances where the subject is displayed with non-capitalized first letters. One is template.area.no-permissions {areaType}.
Another one is template.area.please-contribute {areaType}. See screenshot.
<img width="899" alt="screen shot 2016-09-02 at 06 14 14" src="https://cloud.githubusercontent.com/assets/19162952/18190078/bca7acd2-70fa-11e6-8ab0-fb15bdb6c882.png">

**Comment by brendanheywood** [comment]
Is this still an issue? I can't see whats wrong above

**Comment by rouletout** [comment]
yes, still the same, see attached for this area: https://www.thecrag.com/climbing/united-states/new-river-gorge/area/1998919053

<img width="844" alt="screen shot 2018-09-26 at 10 04 56" src="https://user-images.githubusercontent.com/19162952/46085315-bc56b900-c173-11e8-8e98-077ab6a11c98.png">

The areaType is not capitalized.

**Comment by brendanheywood** [comment]
Ah thanks

https://www.thecrag.com/climbing/united-states/new-river-gorge/area/1998919053?lang=de

hot fixed

**Comment by brendanheywood** [comment]
If there are others please do that red circle style screenshot again, that saved me a heaps of time
