### ISSUE TITLE
Translations: dynamic menus not translated

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2357]
As an example only parts of this menu are translated and no keys are available:

<img width="854" alt="screen shot 2016-09-02 at 10 54 58" src="https://cloud.githubusercontent.com/assets/19162952/18191286/33ec0ce4-7104-11e6-9846-648eca00ecf9.png">

**Comment by lordyavin** [comment]
Found a bug after translation of "action" menu for gyms:
![grafik](https://user-images.githubusercontent.com/1528540/33267697-c6af2e74-d37a-11e7-85fc-05e8e567d851.png)

**Comment by Mdemaillard** [comment]
implemented
![image](https://user-images.githubusercontent.com/60388146/77201256-d8cb7b80-6af4-11ea-8af2-240ae9288e6f.png)

**Comment by Mdemaillard** [comment]
ok confirmed both implemented
![image](https://user-images.githubusercontent.com/60388146/77201379-0e706480-6af5-11ea-8745-db354ca959c9.png)
