### ISSUE TITLE
Translations: date translation not 100% correct

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2359]
See screenshot, 2nd should be 2. or at least not show the "nd".
<img width="393" alt="screen shot 2016-09-02 at 16 08 17" src="https://cloud.githubusercontent.com/assets/19162952/18195663/b24bf608-7127-11e6-9885-3c544df33f25.png">

**Comment by scd** [comment]
There is a translation key for this

system.day-of-month.2nd

Note that this is a temporary hack while we are waiting for our proper ordinals fix. 

Please note that it is just the 'th' component, so in German it would be set to '.'????

**Comment by UFU608** [comment]
Found it. Yes, any date would just end with a dot "." , e.g. 2. Sep 2016 - for once German is easier ;-)
Can you bulk upload / translate that?

**Comment by scd** [comment]
I have done a bulk update for all these keys and pushed to dev and prod.
