### ISSUE TITLE
new urgent 404 routing bugs

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2364]
See https://www.google.com/webmasters/tools/crawl-errors?hl=en-GB&siteUrl=http://www.thecrag.com/

![image](https://cloud.githubusercontent.com/assets/187449/18224779/1bc848dc-7224-11e6-9950-2c66e0167c5d.png)

We are only seeing these issues now because we've properly exposed them via the new 404 error page. So far google has only found 67 but I suspect this is only just from what it has crawled so far and that after a full scrape the number will be heaps bigger. In GA click Behaviour > Site content > All pages, then change the primary dimension from url to page title and search for 404 and you'll get a similar list

There seems to be 3 classes of errors:

1) crap links which would just never work:

http://www.thecrag.com/CRAGS/WesternAustralia-275158.html

These are possibly legacy from way way back, or external links pointing in, but just always got the old 200 page with no content so have never been remove from google but would have had crap pagerank.

2) links which look like they should work, or perhaps did at one point, eg

http://www.thecrag.com/climbing/australia/tooheys-forest (fixed, it's proper url is http://www.thecrag.com/climbing/australia/queensland/toohey-forest)

Not a big issue but we could fix these by adding more url stubs to those nodes. It depends on how many we end up finding. I've fixed a couple of these on the spot

3) Route / area mistyped urls, these ones are actually concerning and we should hot fix this:

http://www.thecrag.com/climbing/germany/schwaebische-alb/route/249413973
should be
http://www.thecrag.com/climbing/germany/schwaebische-alb/area/249413973

http://www.thecrag.com/climbing/australia/nowra/new-nowra-braidwood-road/route/119522991
should be
http://www.thecrag.com/climbing/australia/nowra/new-nowra-braidwood-road/area/119522991

http://www.thecrag.com/climbing/south-africa/silvermine/area/16419445
should be a route url:
http://www.thecrag.com/climbing/south-africa/silvermine/route/16419445

4) There are some whole classes of urls which should work which are a 503 so something has exploded, eg /publication/7544620

So actions in rough priority order:
- [x] hotfix? so we should just accept these even if the node type is wrong. We have a node id which is enough to uniquely identify the node so we should be more forgiving about the node type. Almost all of these urls are coming direct from google so they must have previously worked at some point for them to be remembered.
- [x] hotfix? http://www.thecrag.com/publication/7544620 seems all publication urls have an internal error
- [x] trace these back to find which templates or helper functions are rendering these broken links and fix them, where possible. When they work again the canonical link should kick in next scrape and google shouldn't come there again in theory
- [x] Regression: http://www.thecrag.com/article/ which should render the article index and was last release.
- [ ] There are some other urls which may not have ever worked but we should probably make them do something useful, eg http://www.thecrag.com/climbing/ 404's but should just go to the world page

**Comment by scd** [comment]
> so we should just accept these even if the node type is wrong. We have a node id which is enough to uniquely identify the node so we should be more forgiving about the node type. Almost all of these urls are coming direct from google so they must have previously worked at some point for them to be remembered.

If they were already in google then the source is probably an earlier mistake. Some templates had got the area type wrong in the past.

Shouldn't we be permanently redirecting these ones?

> hotfix? http://www.thecrag.com/publication/7544620 seems all publication urls have an internal error

hotfixed. Regression bug with the image cutover.

> trace these back to find which templates or helper functions are rendering these broken links and fix them, where possible. When they work again the canonical link should kick in next scrape and google shouldn't come there again in theory

Which failure case are you refering to.

**Comment by brendanheywood** [comment]
I'm not fussed wether just serve the page or serve a redirect. Either way Google will see the canonical and go to the right on in future. 

Re failure cases I'll rerun the report later today and see what else we need to do

**Comment by brendanheywood** [comment]
Just re-working through the two lists of 404 errors (which has been growing since last night), the publications one is now good and I'm marked them as resolved for google. But the majority of all of these busted links are still the area / route mixups. Almost all of these are coming from google, so we need to fix them so google rescrapes them and then remembers the correct url instead.

* [ ] Also there seems to be a similar issue with the directory links:

http://www.thecrag.com/climbing/czech-republic/usti-nad-labem-brny/vrcholova-vez/directory

Should we completely deprecate these or what?

* [ ] there is also quite a few urls which look like: http://www.thecrag.com/web?DN=7&P=11743795. Almost all of these seem to be the really old url format for either a route, area or climber or whatever. Almost all of them work if I change the url to, ie that one above should redirect permanently to http://www.thecrag.com/climbing/australia/gibraltar-peak-and-corin-road-crags

**Comment by rouletout** [comment]
+1

**Comment by scd** [comment]
There is another failure mode here with the new article translations. There are a couple of articles which have now been retired or migrated to new urls (eg /article/donate was migrated to /article/supporter). The link_to does not check for these migrations, but perhaps it should. More importantly there are references to /en/article/donate in the system (eg footer) which are not being mapped by the Rewrite.pm function (perhaps it should).

I have made some changes so that /en/article/donate redirects to /en/article/supporter and I have started fixing links in the system so that the donate url does not appear anywhere (eg footer). In the process of doing this I am converting to link_to

 - [ ] Do we want link_to to have redirect capability for migrated article urls? It will not fix any historical problems just perhaps future problems, so we could deal with this in the future. I think no for now.
 - [ ] Do we want Redirect.pm to be smart enough to also work out language redirects based on their language equivalent. Hmm to minds about this as it will only happen if we stuff up the urls in the first place.

**Comment by scd** [comment]
In dev I have updated the template data build function for route and area page to redirect if the area or route has been specified incorrectly in the url. NOT HOTFIXED.

**Comment by scd** [comment]
@brendanheywood shall we just make /climbing redirect to /climbing/world

**Comment by scd** [comment]
@brendanheywood shall we server a blank noindex page for all the /CRAGS urls?

**Comment by scd** [comment]
Notes to self. There is a mapToNewURLFormat function in MyApache2/Webportal.pm module which we could make use of for the DN=7&P= ... issue. Move the function to a shared module and refer to it in the Rewrite.pm. There is a section in this module which is commented out, so we could remove the comments and call the url mapping function then redirect.
