### ISSUE TITLE
Repeated text

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2368]
In your profile page, selecting a template (in my case Artificial) where you have no ascents:

![screen shot 2016-09-06 at 12 41 40](https://cloud.githubusercontent.com/assets/19304867/18270850/53c63e6c-742f-11e6-929b-2767da7459b1.png)

If this is the intended behaviour, only the second sentence is actually translated:

![screen shot 2016-09-06 at 12 38 00](https://cloud.githubusercontent.com/assets/19304867/18270744/dcea67a0-742e-11e6-87eb-4f97fab2adc2.png)

**Comment by rouletout** [comment]
Closed
