### ISSUE TITLE
Messed up maps/location position

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2369]
Hey,

since today the map/location at a crag wrong positioned. It is behind the area/route list. 

As an example:
![unbenannt-1](https://cloud.githubusercontent.com/assets/3040689/18299825/4f81a0ae-74c4-11e6-8f68-cf13f47cd4b2.jpg)

**Comment by brendanheywood** [comment]
Dunno why this happened, but @scd can you please hotfix this css change:

current:

```
.overview {
    width: 120px;
    float: right;
    background: #fff;
    margin: 0 0 16px 16px;
}
```

fixed:

```
.overview {
    width: 120px;
    float: right;
    background: #fff;
    margin: 0 0 16px 12px;
}
```

**Comment by scd** [comment]
Just to be clear, this is the `overview` class specified in portal.css. Also, if you have not made this change in portal.css, I can. I just want to know if this is something you have changed but not pushed?

**Comment by brendanheywood** [comment]
Yes, and no I haven't even checked this in that was live fixing in chrome dev tools

**Comment by scd** [comment]
I have made the hotfix, but it was never broken for me so I cannot confirm if it is working not???

**Comment by brendanheywood** [comment]
It was broken for me, pretty badly too on every single page on the site. I can confirm it's fixed now in chrome

**Comment by nicHoch** [comment]
also fixed for me in Firefox.


Nicky


Am 08.09.2016 um 02:16 schrieb Brendan Heywood:
