### ISSUE TITLE
Minor formatting problem in stream

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2370]
Text box in stream too big
![screen shot 2016-09-07 at 15 22 35](https://cloud.githubusercontent.com/assets/19304867/18313415/fbab1b7c-750e-11e6-90a1-ccc6e39bbe2f.png)

**Comment by Mdemaillard** [comment]
seems fixed on chrome, both desktop and mobile. + edge desktop.
Was that on mobile or another browser ?

**Comment by rouletout** [comment]
I think we can close that
