### ISSUE TITLE
Translation: wrong alphabetic order

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2371]
Noticed if filtering climbers "From country" (but will and might apply to other areas).

The alphabetic order follows the english version of the word not the translated one. Each language must have its own ordering.

![screen shot 2016-09-07 at 15 39 42](https://cloud.githubusercontent.com/assets/19304867/18313978/68957154-7511-11e6-9351-5d7633cd483f.png)

**Comment by scd** [comment]
fixed in simons dev
