### ISSUE TITLE
Route hight filter

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2373]
I think the fourth one should be "20 to 45m"

![screen shot 2016-09-07 at 15 53 45](https://cloud.githubusercontent.com/assets/19304867/18314436/5b028976-7513-11e6-918d-95648d8c8d7f.png)

**Comment by brendanheywood** [comment]
@scd just looked at this thinking it's an easy lang pack issue, but I think this is db config somewhere?

**Comment by scd** [comment]
fixed in simon's dev. Also provided a translation key system.filter-between
