### ISSUE TITLE
Photo-topo display issue

### ISSUE THREAD

**Issue by kurtdoherty** [theCrag/website#2375]
Hi gents, just noticed an issue with photo-topos no longer showing. Looks like the phototopo-min-1.1.9.js isn't getting retrieved. Screens attached.

<img width="968" alt="screen shot 2016-09-08 at 5 22 27 pm" src="https://cloud.githubusercontent.com/assets/8381850/18340546/07bba500-75e9-11e6-8fdf-35d788505c01.png">

![screen shot 2016-09-08 at 5 22 47 pm](https://cloud.githubusercontent.com/assets/8381850/18340559/154cf8fe-75e9-11e6-8adb-103580bd68d5.png)

**Comment by scd** [comment]
whoops regression issue from this mornings hotfix. Thanks for pointing this out :)

Fixed

**Comment by kurtdoherty** [comment]
👍🏼
