### ISSUE TITLE
PDF topo does not show (some) photo topos

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2379]
When I try to generate a topo of [this Magic Wood boulder](http://www.thecrag.com/climbing/switzerland/alpen/graubunden/magic-wood-averstal/area/724113804) via "instant pdf", its photo topo is not contained in the generated pdf. The same happens when generating a pdf topo of its parents. However, other photo topos appear correctly!?

**Comment by brendanheywood** [comment]
The instant PDFs and made roughly once a month ahead of time, that topo looks a couple days old. Try generating a custom pdf and it should be present.

**Comment by birgander2** [comment]
Right, so this was a misunderstanding. Maybe better call it "pre-generated" or so instead of "instant". This made me think that it is calculated on the fly.

Anyway, you can clode this issue.

**Comment by scd** [comment]
Yes that is a good point about the way it is worded. I must confess that the wording was chosen because it was quick and the on-the-fly stuff is a bit slower.

We will consider rewording when we look at this area of the site again.

**Comment by brendanheywood** [comment]
I've just reworked this so instead of 2 download buttons, you instead just get one which drops down to reveal all the stuff which was previously hidden in a tool tip:

![image](https://cloud.githubusercontent.com/assets/187449/18615545/a32aaa4e-7dec-11e6-95fd-754159c63e4b.png)
