### ISSUE TITLE
Translation: question keys

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2383]
I can't find the key for that title "karma leaderboard in of climbers"

<img width="887" alt="screen shot 2016-09-16 at 17 37 46" src="https://cloud.githubusercontent.com/assets/19162952/18580092/73eaed8e-7c34-11e6-9990-83ae08868b8a.png">

**Comment by UFU608** [comment]
By the way I also struggle with the English here or is this a mix?

**Comment by scd** [comment]
This was not really completed properly in english.

I have done some tinkering here to bring this in line with the other facets. @UFU608 do a search on 'facet' keys for new keys to complete. Please close when happy

**Comment by UFU608** [comment]
done
