### ISSUE TITLE
Translations: Button not translated

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2384]
The "More Climbs" key is translated but does not show on the button
<img width="1152" alt="screen shot 2016-09-16 at 19 00 18" src="https://cloud.githubusercontent.com/assets/19162952/18582430/fbb162ba-7c3f-11e6-889c-a575c1096c88.png">

**Comment by scd** [comment]
fixed on dev. @UFU608 please close when key is translated

**Comment by UFU608** [comment]
I cannot find the key

**Comment by scd** [comment]
process.button.more-climbs

**Comment by UFU608** [comment]
done
