### ISSUE TITLE
Translations: pages without translation keys (excluding the Help guides)

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2385]
- [ ] Change password
- [ ] Change email
- [ ] Reorder favorites
- [ ] Karma
- [ ] Edit your photo
- [x] Following
- [x] Followers
- [x] Home Policies (https://www.thecrag.com/article/Policies)
- [x] Donate page (https://www.thecrag.com/donate)
- [x] Reorder areas/routes
- [ ] Route details page
- [ ] Ascent details

**Comment by Mdemaillard** [comment]
We need to review each of these pages IF and WHICH ELEMENTS are missing, for it to be tackled by dev. Screenshots below taken with URL hacked -> ?lang=xx

- Change password: 0% done (CIDS process page)
![image](https://user-images.githubusercontent.com/60388146/78549989-977ce080-7803-11ea-8a0d-bdf257585772.png)
- Change email : 0% done (CIDS process page)
![image](https://user-images.githubusercontent.com/60388146/78550068-bda28080-7803-11ea-9b9c-79c5a2466b87.png)
- Reorder fav: 0% done (CIDS process page)
![image](https://user-images.githubusercontent.com/60388146/78550304-225ddb00-7804-11ea-80bb-0d6b477b42c9.png)
- Karma : 0% done         https://www.thecrag.com/climber/mdemaillard/karma/?lang=xx
![image](https://user-images.githubusercontent.com/60388146/78550668-b9c32e00-7804-11ea-813c-702e92777dc3.png)

- Photo 50% done
https://www.thecrag.com/photo/3166468449/?lang=xx
![image](https://user-images.githubusercontent.com/60388146/78550768-f1ca7100-7804-11ea-975b-319a876494a5.png)

- Review Photo 0% done (CIDS page)
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3APushReturnURL=%2F3166468449&C%3AState=16159&D%3APhotoID=3166468449&C%3AHideNavigation=1/?lang=xx
![image](https://user-images.githubusercontent.com/60388146/78550874-263e2d00-7805-11ea-8c4e-1aefdac66318.png)

- Following 99% done, 1 key remaining for Profile button
https://www.thecrag.com/climber/mdemaillard/following/?lang=xx
![image](https://user-images.githubusercontent.com/60388146/78551056-61406080-7805-11ea-9399-8e1a6249b875.png)

- Follower  99% done, 1 key remaining for Profile button
https://www.thecrag.com/climber/mdemaillard/followers/?lang=xx

- Home policies: 100% done please tick box in 1st post
- Donate page : 100% done please tick box in 1st post

- Reorder areas/routes: 0% done (CIDS page)
![image](https://user-images.githubusercontent.com/60388146/78551399-f0e60f00-7805-11ea-8e49-b6cd13c6a643.png)

- Route Detail page: 80% done
![image](https://user-images.githubusercontent.com/60388146/78551601-44f0f380-7806-11ea-9ee9-c4e3e4ab1dc4.png)


- Ascent Detail page 0% done
![image](https://user-images.githubusercontent.com/60388146/78551728-78338280-7806-11ea-9b9c-b84bffb707b6.png)

**Comment by rouletout** [comment]
I close this as this is all managed in the translation boards and individual issue raised where keys are missing or nor transalted.
