### ISSUE TITLE
Translations: key missing for connections

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2388]
The sub-header "Notes on connections" seems to have no key
![screen shot 2016-09-18 at 22 46 06](https://cloud.githubusercontent.com/assets/19162952/18616186/e240ec16-7df1-11e6-8ae0-651900e382e7.png)

**Comment by scd** [comment]
Added a key

template.account-settings.connections.notes-on-connections

@UFU608 please close when confirmed working

**Comment by UFU608** [comment]
works
