### ISSUE TITLE
Translations: key missing for Create Circuit

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2389]
In this menu the key for create circuit seems to be missing
<img width="671" alt="screen shot 2016-09-18 at 22 52 03" src="https://cloud.githubusercontent.com/assets/19162952/18616228/ae43ae0c-7df2-11e6-8747-5fd3d0ecd588.png">

**Comment by scd** [comment]
added key 

template.action-area.create-circuit

We plan to change the name of this to something like 'List'.  Note that a circuit is a list of routes.

**Comment by scd** [comment]
@UFU608 please close after you have confirmed that it works.

**Comment by UFU608** [comment]
works
