### ISSUE TITLE
Trip

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2390]
I tried to create a trip according to the help document but couldn't find the menu...
![screen shot 2016-09-18 at 22 58 30](https://cloud.githubusercontent.com/assets/19162952/18616261/7eb40104-7df3-11e6-94c6-9a26f5478500.png)

**Comment by scd** [comment]
We are not really supporting trips anymore. We will probably come back to it, but needs significant work to make it useful. One thing I really liked about trips was a function that combined recommendations from various team members in a single table.

**Comment by rouletout** [comment]
Closing
