### ISSUE TITLE
Translations: weird grammer / capitalization for "Hide"

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2392]
The "hide" function (e.g. Hide History) creates its own text. The field description should be capitalized and the verb and subject switched

<img width="267" alt="screen shot 2016-09-18 at 22 30 44" src="https://cloud.githubusercontent.com/assets/19162952/18616540/b2a1c474-7df8-11e6-9c9d-b4b630a54fcb.png">

**Comment by scd** [comment]
This is fixed on dev. New key

js.common.hide.label

**Comment by scd** [comment]
@UFU608 please close after confirmed working

**Comment by UFU608** [comment]
works
