### ISSUE TITLE
Translations: Spelling corrections/suggestions for German translation

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2394]
A node without information displays
Gebiet Information hinzufügen
I should be either
"Gebietsinformation hinzufügen"
or more general
"Informationen hinzufügen"

**Comment by MelwinQ** [comment]
when editing a route, the "submit"-button is labelled
"'Speichern und schliessen"
I find "Schließen" obsolete, but if it needs to be contained, it is spelled with "ß" (unless you are Swiss)

**Comment by MelwinQ** [comment]
Gesteinsarten:
metamorphos -> metamorph
Platte -> Schiefer (?)
Brecia -> Breccie


"Zustand" contains "abgespeckt" twice, please check
"überfüllt": I think it is "cramped" originally, which I would interpret as (too) close to other routes with unlogical course. I suggest "reingequetscht", "gesucht" or "definiert"

**Comment by MelwinQ** [comment]
When viewing in bulk edit mode, inherited tags are displayed as
vererben Granit
It should rather be 
geerbt: Granit

**Comment by UFU608** [comment]
Most of that was updated on DEV - some of it has limitations based on the way the terms are build up (e.g. Seite 2....), exceptions are:

Trad has still to be homogenized across the system.
vererben / geerbt requires a "past" key for inherited (new issue)
Platte - Schiefer (not found)

**Comment by MelwinQ** [comment]
Platte - Schiefer
refers to tag "Gesteinsart -> Metamorphes Gestein", last entry

**Comment by UFU608** [comment]
Corrected on dev and closed

**Comment by MelwinQ** [comment]
https://www.thecrag.com/settings/profile:
"Profil URL" -> "Profil-URL"
Dorpdown "Bewertungssystem (Kontext):" not yet translated 

https://www.thecrag.com/article/cragkarma (partially translated already)
"Kontotaktivität" -> "Kontoaktivität" (btw. -1 for getting Karma for this)
"Email Bestätigung" -> "Email-Bestätigung"

Navigation-Sidebar:
"PDF Kletterführer" -> "PDF-Kletterführer"
"Gebiets Diskussionen" -> "Gebietsdiskussionen"
"Facebook Verbindung" -> "Facebook-Verbindung"
"RSS Feeds" -> "RSS-Feeds" 
"Benutzer Berechtigungen" ->"Benutzerberechtigungen" 
"Photo*" -> "Foto*"
"Topo Tips" -> "Topo-Tipps"
"theCrag Fördern" -> "theCrag fördern"
"App Anwednungsfall" -> "App Anwendungsfall"

**Comment by rouletout** [comment]
Thanks! All fixed and updated, will be online with next release
