### ISSUE TITLE
Translations: view at the level of a single route still completely in English

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2395]
https://www.thecrag.com/climbing/switzerland/alpen/zentralschweiz/uri/route/983243931
even though the parent node is correctly displayed in German.

**Comment by scd** [comment]
Yup, this is one of the templates that have yet to be completed.

**Comment by MelwinQ** [comment]
bulk-edit view is already in German, but the sub-heading ("There are 21 nodes (areas,routes or annotations) to review. Updates DO NOT take effect...") comes in English.

**Comment by UFU608** [comment]
Fixed on dev
