### ISSUE TITLE
Translations: new key required for "inherited"

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2396]
For German translations we also need a past tense of "inherit / inherited"

**Comment by Mdemaillard** [comment]
in bulk edit - tag
inherit - done
![image](https://user-images.githubusercontent.com/60388146/77203022-24cbef80-6af8-11ea-8880-
98f23056324d.png)

where is an example of inherited ? can't find an occurrence

**Comment by rouletout** [comment]
when you open teh Bulk Edit Form you see the example above. It is still the same. Also, on hovering over an inhertied Tag you see it but it seems to be a different key as in German it says "übernommen von" and not "vererbt" - maybe we can use this key instead...

**Comment by rouletout** [comment]
done, closing
