### ISSUE TITLE
Maps showing wrong language, ignore both browser settings and account settings

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2399]
I created a new test account on dev "testulftest" with Country = South Korea and Language = German. In the map the menue is displayed in Korean, the rest is in german.

<img width="1260" alt="screen shot 2016-09-27 at 17 12 11" src="https://cloud.githubusercontent.com/assets/19162952/18865913/94eaa25c-84d8-11e6-87fa-2be70fc89932.png">

**Comment by scd** [comment]
Interesting. Note to self - look at javascript

**Comment by brendanheywood** [comment]
This is what we want:

https://developers.google.com/maps/documentation/javascript/localization

https://developers.google.com/maps/documentation/javascript/examples/map-language

```<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap&language=ja&region=JP"
    async defer>```

Tasks:
* [ ] I would guess that google will do a better job than us of handling the language if given the chance, so I would not pass in a language for anon users and let it decide.
* [ ] When the language preference is known from an account then send it.
* [ ] I'm in two minds about the 'region' api option, it seems to be used for both local law applications (in which case we should hard code it to AU) but it also seems to be used for geocoding hints - in which case we should map from the users current location (which we don't really actually know in the db). So I think we should add region=AU for now

**Comment by rouletout** [comment]
Solved and closed
