### ISSUE TITLE
Template issues stream reparented key error

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2400]
_template.stream.detail.removed-reparented-child_ 

not working properly, output as follow:

> Removed reparented child 'Michl' to '{to}'.

(check also _template.stream.detail.removed-merged-child_ since it has the same syntax)

**Comment by nclementel** [comment]
_template.stream.detail.changed-name_

In the english version is: 

> Changed name from '{from}' name '{to}'.

I think it should be: _Changed name from '{from}' **to** '{to}'._

**Comment by Mdemaillard** [comment]
Reparent case: seems stream update to:
![image](https://user-images.githubusercontent.com/60388146/77203713-c6077580-6af9-11ea-85dd-2ded3bb68344.png)

Renaming: still open

**Comment by rouletout** [comment]
All done, closing
