### ISSUE TITLE
Historical ascents to go with historical accounts

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2401]
If and when we implement the pseudo historical accounts (#1518) so we can link first ascents to people, it would be cool if the community could also log historical ascents, especially for important ascents which are not fa's but noteworthy in other ways. Imaging being able to generate a list like this any crag region or country:

http://www.verticallifemag.com.au/2016/09/first-at-the-grade/

**Comment by lordyavin** [comment]
Please implement this feature. I think it's good to honour the legends of mountaineering and climbing. Additionally the community should be able to edit informations about the person. A good point to start would be the Eiger Nordwand. There is so much history!

**Comment by scd** [comment]
Yes we will. There are some significant dependencies though, and there is quite a lot of work. If you add text names to FA's then this will eventually be converted to a pseudo account. So doing this project should not be a blocker to adding information.

**Comment by brendanheywood** [comment]
This one has been eating away at me for ages too, especially since the frog trip. I'm really keen to work on a facet graph view which shows a history timeline of a crag (see #2025) and it will partially leverage this data. I was thinking about whether I could approach it in a very manual way in the beginning, ie I signup and create a new account for each historical person and then clearly state in that persons profile that it's not a real person. And we can collect a list of these accounts and then flip the bit on them later once we implement the historical pseudo account flag. @scd do you see many downsides to this? It's not really functionally any different to if that person has signed up 20 years ago and then moved on and is no longer active.

@lordyavin yes there is the comments next to the FA / FFA in the route details, this is currently not shown anywhere useful but I think it should be so add a few bits for a couple routes and then paste the url's of those routes here so we have some test cases.

**Comment by scd** [comment]
For managed gym comps we solved some of the account issues, where I create surrogate accounts just based on a persons name. If the surrogateFlag is set in the API then most of the mandatory account creation fields are not required and the system creates a login based on the persons name.

What we need is a nice javascript interface to this which sits on the route page. This would be very little work, but what is far more work is propagating this to other FA's on other routes. We only want to create a surrogate account once then link all relevant FA's to it. We also need to make sure we are not creating duplicate surrogate accounts.

**Comment by brendanheywood** [comment]
I think when we get to #1518 we'll do the analysis and implement it properly, but @scd for right now would you be opposed to people making historical accounts as real accounts now as a workaround and we can convert them over later? I'm kinda a fan of zero code workaround solutions as they help figure out what we actually want for when we get to it for real, but only if it's not going to cause issues later.

**Comment by scd** [comment]
I see no problems with creating historical accounts

**Comment by brendanheywood** [comment]
fyi I've made a whole bunch of pseudo accounts and started fleshing out the history fa fields of ebor:

https://www.thecrag.com/climbing/australia/ebor-gorge

for when we get around to #2025

**Comment by lordyavin** [comment]
**Hans Dülfer**:
* https://www.thecrag.com/climbing/italy/dolomites/cortina-dampezzo-area/route/1043063364
* https://www.thecrag.com/climbing/italy/dolomites/cortina-dampezzo-area/route/1043064459

**Alexander Huber** (is alive)
* https://www.thecrag.com/climbing/italy/dolomites/cortina-dampezzo-area/route/1273248282
* https://www.thecrag.com/climbing/italy/dolomites/cortina-dampezzo-area/route/1273248417

Also checkout the updates on [Eiger Nordwand](https://www.thecrag.com/climbing/switzerland/alpen/berner-oberland/area/513463548)

**Comment by lordyavin** [comment]
Hey @brendanheywood I checked your updates on ebor-gorge. Good work ;). In the future we need to refine the profile page of these pseudo accounts. E.g. the "Member since" information should be removed. Accounts of deceased persons should display † behind the name. And of course the historic ascents should be listed.

**Comment by brendanheywood** [comment]
thanks @lordyavin - we are planning on showing a persons development / first ascent contributions on the profile page regardless of whether they are real or pseudo. I couldn't actually find an issue so I've created this #2843. 

Also I have collected some thoughts on how these community accounts would differ from normal accounts here #1518. I've added you couple of ideas to the list, if you think of more can you please add them to that issue.

In terms of creating the accounts, these are just normal real accounts. I signed up as anyone else would using my gmail with subaddressing (https://en.wikipedia.org/wiki/Email_address#Subaddressing). I don't mind you doing the same, but the main purpose of this is to figure out what the feature gap is so we can implement it properly. If you create any accounts the please ensure you add a notice similar to what I did and also add the url to the new profiles into #1518 so that when we are done we can go back and swap them over.

**Comment by lordyavin** [comment]
Unfortunately my email provider doesn't support sub-addressing. Therefore I'm not going to add new pseudo accounts :(

**Comment by Mdemaillard** [comment]
This (interesting) discussion went mostly sideways to #1518, but these are the topic i see which are not otherwise covered by it:

- Will we want a way to highlight a FA as "Historical", or will some Statistic process scrub the ascents to define them  ? (ex, oldest FA at grade X for sex Y)

- Implementation of either a new page or rather extension of existing Facet search to display these results according to whichever criteria selected

**Comment by rouletout** [comment]
This is happening and being done constantly, closing
