### ISSUE TITLE
Show location of routes (not just areas) in maps

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2403]
I don't understand the idea behind geolocation of individual routes. One can enter coordinates, but they are not shown in the map, or am I doing something wrong? I would expect a snap marker or something like that to appear in the sector's map. At least some geolocated routes could be very helpful for orientation in complicated sectors.

Also, one can enter coordinates only by hand, not by clicking in the map. In practice that normally means that you need Google Earth in a 2nd window.

**Comment by brendanheywood** [comment]
Yes sorry this is just unfinished, the area level locations was way higher value than route level and it got left off. we are near the point of starting over with a rewrite of the maps to support a bunch of new features, it's on the list

**Comment by birgander2** [comment]
Cool, thanks! Please don't forget to add a switch for OSM maps, not only Google (just like in edit mode)!

**Comment by brendanheywood** [comment]
Routes are now shown in maps v2
