### ISSUE TITLE
Translation too fast: Gym route colours

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2406]
In the edit/add route dialog: the route colours explanations are already translated (to German), but they cannot be entered (yet) in German.

**Comment by scd** [comment]
This is an interesting issue, as it is a reverse translations issue. The color is used in the CSS code, so I think we need to look at another way of selecting the color.

**Comment by brendanheywood** [comment]
Either we want people to choose any valid css3 color, or even color gradient or any other valid css backgrond, or we want a limited palette. If we go with the former then we wouldn't translate this. If we want the latter then we can provide a mapping. I don't have a problem with these being raw in a one-time-setup of a gym, but it is a bit of a hassle for route setters to use directly.

I think we should leave this for the moment, but come back to this when we implement the last few parts of #1499 - in particular we'd enable a gym to configure the exact colors that it has (or color mixes) and in that setup provide the mapping from local names to the css colors. Then the route setters would work just with the local names in a dropdown.

**Comment by birgander2** [comment]
Additional comment on the gym route colours: I was always missing the very basic colour "orange"

**Comment by scd** [comment]
yes this was because we took the initial color set from css2 standard colors. It was not until after we did that we released it was missing something basic.

**Comment by lordyavin** [comment]
stumpled acros this today

**Comment by lordyavin** [comment]
Please fix this ASAP. I don't want to argue about such a "little" bug if I demonstrate it to the Kletterwerk.

**Comment by scd** [comment]
I just want to confirm what the gap is here for this issue. My understanding is that you can select a colored tag, it is just that the label is not translated. Is this correct?

![screenshot from 2017-11-28 10-15-57](https://user-images.githubusercontent.com/373058/33294583-6d2832f0-d425-11e7-876c-f4f59e001aef.png)

**Comment by scd** [comment]
I am thinking that this should be part of the gym setup. The gym color palette will only ever be in one language as it is for route setters, so we don't actually need translating. 

What about adding a json variable to the gym node such with the selectable color labels. This would allow more complex textures such as marble and we could give orange a proper name.

**Comment by brendanheywood** [comment]
I've prefer to just remove the words and have a preset palette. btw orange is a css3 keyword

**Comment by scd** [comment]
I just removed the color name. We now get this:

![screenshot from 2017-11-28 14-38-17](https://user-images.githubusercontent.com/373058/33301504-2a1059dc-d44a-11e7-9bf8-71b8f5fedc48.png)

@brendanheywood if this is what you mean then please close.

Hotfixed BTW

**Comment by brendanheywood** [comment]
yes - but the real problem here is the 'add single route' and 'add multi routes' processes are completely different. In those pages you have to type the color instead of choose from a palette. All 4 processes add / edit vs single / multiple should be exactly the same bulk edit ui.

**Comment by scd** [comment]
I forgot about that. Will keep this open until done

**Comment by brendanheywood** [comment]
The stated issue here is fixed since we rolled out a fixed color palette. The add route form is not great as the layout is different so the color picker is on huge column. That will be fixed in https://github.com/theCrag/website/issues/635
