### ISSUE TITLE
Wrong grade display in stream

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2408]
https://www.thecrag.com/climbing/spain/mallorca

Today's two ascents of Georg Kretzschmar are shown as "4+ 4c", but the route grade string is "4+" only. However, in https://www.thecrag.com/climbing/spain/mallorca/ascents/  is is correctly displayed.

**Comment by scd** [comment]
That is probably some wierd artifact due to the way we are handling updating event info and grades. 

Did you know you can link to an event by itself via the dropdown menu on the right.

https://www.thecrag.com/event/996556695

It makes it easier to find later when I get time to debug this issue :)

**Comment by brendanheywood** [comment]
This looks to be resolved
