### ISSUE TITLE
Responsive crumb trails

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2410]
Mockup of responsive crumb trail on small devices:

Collapsed default:
- [ ] all crumb nodes title hiddne with just arrow showing
- [ ] current node hidden (duplicated in main header)
- [ ] if you click parent then navigates to there
- [ ] if you click on any of the arrows then it expands to show the full crumb trail

![image](https://cloud.githubusercontent.com/assets/187449/19421434/c6e65b6a-944c-11e6-8fc7-f9637b27cf9d.png)

Expanded crumb trail:
- [ ] world node title added
- [ ] all nodes staggered in
- [ ] current node shown
- [ ] After expanding all the arrows work the same as now
- [ ] top right will be a 'hide' button (not mocked up)

![image](https://cloud.githubusercontent.com/assets/187449/19421417/4b8be304-944c-11e6-8701-ef0738046e11.png)

**Comment by brendanheywood** [comment]
This idea is possible redundant if we instead go with: https://github.com/theCrag/website/issues/1476

**Comment by Mdemaillard** [comment]
I believe this was implemented looking slightly differently
![image](https://user-images.githubusercontent.com/60388146/76620948-ffa71200-6536-11ea-86f1-66159f6e11cc.png)
Closing

**Comment by rouletout** [comment]
yes
