### ISSUE TITLE
Translations: variable missing

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2411]
It seems the updates already made it over to PROD but the variables are not there. PROD shows "AreaName" instead of the name...

<img width="311" alt="screen shot 2016-10-17 at 13 58 28" src="https://cloud.githubusercontent.com/assets/19162952/19427072/5e10cbd6-947c-11e6-8588-b70fcab0b02a.png">

**Comment by scd** [comment]
This should be fixed on dev now.

**Comment by UFU608** [comment]
Yes this one is fixed but the same issue occurs in other places, see issue #2367 for a list of variables where this occurs
