### ISSUE TITLE
Tags: deleting tags does not work

### ISSUE THREAD

**Issue by UFU608** [theCrag/website#2414]
I tried to remove the tag "Dolomite" from the region "Industrieviertel" (https://www.thecrag.com/climbing/austria/wien-vienna-area/area/385120671) but the tag is still here. Here the sequence of events:

1) click on Edit region
2) click on the small x next to the tag - the tag disappears
3) click on save and finish
4) on re-load the tag is still here

<img width="890" alt="screen shot 2016-10-18 at 15 26 02" src="https://cloud.githubusercontent.com/assets/19162952/19466706/c802da0e-9547-11e6-8ec6-c53210753a75.png">

<img width="1056" alt="screen shot 2016-10-18 at 15 25 34" src="https://cloud.githubusercontent.com/assets/19162952/19466697/bf8dd054-9547-11e6-9eb9-a190b4bd54fc.png">
<img width="1017" alt="screen shot 2016-10-18 at 15 25 46" src="https://cloud.githubusercontent.com/assets/19162952/19466699/c02e897c-9547-11e6-8c51-ef78dc2f3823.png">

**Comment by scd** [comment]
yup looks like a bug

**Comment by scd** [comment]
Now fixed on prod. 

The problem occurred when deleting the last tag. I needed an extra variable to manage tags being settable. If the system saw no tags then it assumed that there were no tag inputs for this form.
