### ISSUE TITLE
ga tracking of pdf downloads

### ISSUE THREAD

**Issue by scd** [theCrag/website#2418]
Behavior -> Site Content -> All pages 

search of .pdf urls

Get results like:

 /climbing/australia/blue-mountains/bells-line-of-road-pierces-pass/area/422159931/download-422159931.pdf

and

/https://static.thecrag.com/pdf/422159931.pdf

So this looks like an error in logging which creates dups

**Comment by brendanheywood** [comment]
I've removed the duplicated code. Note that I just implemented this twice in different places for some reason, I've removed the lower information version.

@UFU608 for your purposes all you need to know is that the pdf's stats are double, but it depends on how you measure this in ga, you can easily filter to get just the right number.

NOTE: I haven't hot fixed this, it's not critical.
