### ISSUE TITLE
Error while uploading topo images

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2422]
Hey,

I tried to upload some photos for topos, but it seems like not working anymore. I get the following error:
 
> Software error:
> 
> ERROR: Unable to connect to localhost:31218: Connection refused
> 
> For help, please send mail to the webmaster (scd@thecrag.com), giving this error message and the time and date of the error.

Also if I tried to re-upload the image, it isn't displayed at the topos and just a placeholder is shown, like here: https://www.thecrag.com/climbing/switzerland/alpen/sarganserland/area/996024171

Best regards,
Philip

**Comment by Drazhar** [comment]
It looks like I uploaded 3 topos from which 2 are disabled and 1 isn't working:
https://www.thecrag.com/event/1006247343

**Comment by scd** [comment]
try again now.

one of our application servers got stuck. This happens every couple of months and I have not yet been able to track it down.

anyway restart the application server
