### ISSUE TITLE
facebook error with tags

### ISSUE THREAD

**Issue by scd** [theCrag/website#2423]
publishFacebookStory: unsuccessful get response: 400 Bad Request: {"error":{"message":"An unknown error occurred","type":"OAuthException","code":1,"error_subcode":1611257,"is_transient":false,"error_user_title":"Indicates that a URL property has whitespace characters, which is not allowed.","error_user_msg":"URL 'http:\/\/www.thecrag.com\/opengraph\/tag\/rock type\/sandstone' for property 'thecragcom:tag' of the object at 'http:\/\/www.thecrag.com\/climbing\/australia\/blue-mountains\/main-area\/route\/161876193' is invalid because it contains whitespace characters.","fbtrace_id":"GGCBmUrl8ll"}}

**Comment by brendanheywood** [comment]
redundant
