### ISSUE TITLE
Production bug: Locating areas is broken ajax js error

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2424]
@scd ajax bug in production (eg was trying to locate that new crag in turkey)

https://www.thecrag.com/climbing/turkey/area/1006547541/locate

![image](https://cloud.githubusercontent.com/assets/187449/19834468/b9f7d88a-9eb4-11e6-90b1-addc45e0567c.png)

**Comment by brendanheywood** [comment]
@scd I think this is a more widespread problem with the entire API

**Comment by scd** [comment]
please check. I stuffed up when I fixed the app server this morning. There is actually a systemic issue with a log file being created with the wrong permissions.

**Comment by brendanheywood** [comment]
:+1:
