### ISSUE TITLE
I cannot untick any Index stream of Account stream items in settings

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2434]
In the stream settings page: 
https://www.thecrag.com/settings/streams

I cannot untick any of the last 6 boxes:

![image](https://cloud.githubusercontent.com/assets/187449/20042755/72b368f2-a4d3-11e6-96c8-8dad566407f5.png)

They appear to untick and save but them reload and they are back.

**Comment by scd** [comment]
Actually you can unselect one, you just cannot unselect all.

There is a bit of code in WebPrimaryContent.pm which resets to all selected if none selected. I am not sure what the basis of this logic is. If I comment 

```
unless ( $oneisset )  {
      $config->{accountSettings} = {ticks=>1,updates=>1,discussions=>1};
    }
```

Theoretically this should turn off streams in your dashboard, however there are some seldom used types (eg upload a photo) which are still coming through.

Shall I uncomment the code and see what happens?

**Comment by brendanheywood** [comment]
Are you making an assumption for old accounts that may not have this setting set explicitly yet to reset them to the defaults?

**Comment by scd** [comment]
I have updated so at least you can save with everything turned off. However the streams itself don't behave very well with everything turned off.

**Comment by scd** [comment]
> Are you making an assumption for old accounts that may not have this setting set explicitly yet to reset them to the defaults?

I think I was assuming that there was no point browsing the index with no streams set and had a fail safe. Yes accounts which have not set this explicity will default to everything on.

I don't know what it means to browse the index without streams. Would you do it to make it faster?

I don't understand the use case.

**Comment by brendanheywood** [comment]
I've removed the must fix tag, I think the only thing we should do here is add some language just to make it clearer what it means

**Comment by scd** [comment]
I have updated the language as part of my translations tasks. This page is now translated.

![update-stream-language](https://cloud.githubusercontent.com/assets/373058/20086984/a0345688-a5c8-11e6-80f8-ce2c864b7695.png)
