### ISSUE TITLE
archive route menu item missing in non paying gyms

### ISSUE THREAD

**Issue by scd** [theCrag/website#2436]
Eg

https://www.thecrag.com/727939488

vs

https://www.thecrag.com/climbing/australia/melbourne/gravity-worx/area/968244759

Actually we have to confirm that this is the reason not some other bug.

**Comment by Drazhar** [comment]
Hey, this is an old issue, but I just tested, that the archive button appears if I create a sub-area with the type "feature". At the gym level I still can't archive, but at the feature it's possible. I think this isn't intended to be like that ;)

**Comment by scd** [comment]
Please try it on dev.thecrag.com as I have recently done some work on this and it is just not released

**Comment by Drazhar** [comment]
It seems like the same at the dev. At the gym level, archiving isn't possible:
https://dev.thecrag.com/climbing/germany/schwarzwald/area/727939488

but at feature level it works fine:
https://dev.thecrag.com/climbing/germany/schwarzwald/area/560149402

**Comment by scd** [comment]
Ah, I just had another look and I had meant to fix this but there was a complexity so I left it. Sorry my memory is shot. What I was looking at is making outdoor Artificial walls behave in a similar way to gyms.

**Comment by Drazhar** [comment]
haha ok, no problem. 

Now that I know, that it works at feature level, it should be easy to restructure a gym that the routes are only at feature level.

**Comment by scd** [comment]
We rushed the gym formating in a while ago to test the concept and we have to do some refactoring to make it work better in the templates.

**Comment by Mdemaillard** [comment]
works in test area, both in Gym and gym child's node
![image](https://user-images.githubusercontent.com/60388146/77206203-146b4300-6aff-11ea-99ee-ae92ffb554b0.png)
