### ISSUE TITLE
Emails being sent in wrong language

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2444]
See recent support email sent in korean instead of english

**Comment by brendanheywood** [comment]
From simon:

> As the request came through the web callback, it was whatever language was last set from a web call. I have also neglected to reset the language in the callback.

**Comment by scd** [comment]
@brendanheywood I think stripe is broken on the new dev. I have made a fix for this and currently unable to test it because my new dev stripe seems to be barfing before it gets to the updated code. Can you pull and install on your dev so I can check there.

**Comment by brendanheywood** [comment]
done

**Comment by scd** [comment]
Ok I think this is ok as it works on dev.
 - [ ] work out why stripe is broken on new dev
 - [ ] test the actual callback

**Comment by scd** [comment]
I have hotfixed this. I am not sure about the easiest way to test the monthly callback pipeline. The direct pay pipeline uses the same bit of code and that is tested. So unless there is a really strange bug it should be ok. As soon as we get our first monthly payment email then we know it is ok.

**Comment by scd** [comment]
We can close once we see the first monthly email.
