### ISSUE TITLE
Generating topo bug / crash

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2445]
I tried to upload 2 topos. Uploading both at a time gave me some server error, after trying with single files it worked but now I have 4 topos deactivated (the first two tries I suppose) and 2 others which do not display (even not after waiting 1h):

https://www.thecrag.com/climbing/spain/mallorca/sestret/area/226692612

**Comment by brendanheywood** [comment]
I had something similar last night, uploaded a topo from my iphone and it barfed. @scd I had a quick look and thumbor was working fine, I didn't get the exact error but said something about not being able to connect to a particular port number presumably on static

**Comment by brendanheywood** [comment]
Just reproduced this on my desktop:

Software error:

ERROR: Unable to connect to localhost:31218: Connection refused

For help, please send mail to the webmaster (scd@thecrag.com), giving this error message and the time and date of the error.

**Comment by brendanheywood** [comment]
The uplaod works now, the thumbnail after the upload didn't thought

**Comment by brendanheywood** [comment]
static is resynced, all good agin

**Comment by birgander2** [comment]
Thanks. However, the sector still shows 6 topos while it has only 2.

**Comment by brendanheywood** [comment]
Can you please dump a screen shot here? I only see two:

![image](https://cloud.githubusercontent.com/assets/187449/20244723/e86c1c80-a9e0-11e6-9512-62113eee6754.png)

**Comment by birgander2** [comment]
In the sector listing it shows 6:
https://www.thecrag.com/climbing/spain/mallorca/sestret

**Comment by brendanheywood** [comment]
Ah righto, that's unrelated to the bug with the uploads failing. I'm not too concerned by that, the stats process can lag a bit after an edit. If it's still wrong in a day or so please ping me again
