### ISSUE TITLE
Stripe failing on new dev server

### ISSUE THREAD

**Issue by scd** [theCrag/website#2447]
Creating a customer works successfully but the Stripe third party library thinks it fails. Something has changed in the way it operates when we upgraded operating systems.

**Comment by scd** [comment]
Wow this is weird. I have written a minimal stand alone WFT_test function in Stripe.pm. It passes when called via a command line script, but fails when via apache.

Hmm,  I am wondering if this could be a temporary file permissions thingy

**Comment by scd** [comment]
not permissions. Just ran the script as www-data and it was fine.

**Comment by scd** [comment]
This is gone from a debugging issue to a major planned piece of work. We need to replace the stripe module with another. I am not sure if this will be drop in.

**Comment by brendanheywood** [comment]
Pretty sure this was all done
