### ISSUE TITLE
Typos in images used in grade help article / translation

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2453]
On this page https://www.thecrag.com/article/Grades#s2

Is this image:

https://www.thecrag.com/static/cids/images/difficultybanddemo-1.1.1.gif

with some typos. We need to translate this so proposing to remove either the entire image and replace with a call to the grade bar template so it perfectly matches and all text around it will be translated lang strings

**Comment by Mdemaillard** [comment]
This image is not in that page anymore. Closing
