### ISSUE TITLE
not able to set grade 

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2458]
it is not possible to set the grade of this 3 routes:
all should be V0
https://www.thecrag.com/climbing/australia/eastern-suburbs/route/1001703651
https://www.thecrag.com/climbing/australia/eastern-suburbs/route/1001707077
https://www.thecrag.com/climbing/australia/eastern-suburbs/route/1001708016

**Comment by scd** [comment]
updated, but route cause is that all these routes had a registered grade of '--' which does is treated as an empty grade for display purposes, but not for update purposes. I had to delete the principle grade using Action -> Route Grade -> Update principle grade. From there I could then add my own contribution which would update the route.

To complete this issue:

 - [ ] Enhance the save personal grade to update registered grade if the registered grade is a '--' grade.

**Comment by scd** [comment]
Fixed in dev
