### ISSUE TITLE
Photoographers name doesn't show up on photo page (tour related bug)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2459]
eg on this page:

https://www.thecrag.com/photo/1018597092

photographer is:

https://www.thecrag.com/climber/spostle21

**Comment by scd** [comment]
can you screen shot the edit page so I can see that the photographer is assigned.

**Comment by brendanheywood** [comment]
![image](https://cloud.githubusercontent.com/assets/187449/20458811/7cc95308-af03-11e6-943e-f830de024d14.png)

**Comment by brendanheywood** [comment]
See also

https://www.thecrag.com/photo/1026902733

**Comment by brendanheywood** [comment]
I've fixed this and hit fixed it. The photographer data was there, but there was an issue with the photo tour data. I've just worked around it for now so will leave this open until the tour data is fixed as well.

**Comment by rouletout** [comment]
Solved, closing
