### ISSUE TITLE
List view nested sticky topos and headers

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2461]
* [ ] sticky topos
  * [x] detect lowest linked route on page
* [ ] sticky annotation headers
* [ ] sticky area headers with area topos
* [ ] sticky route headers (do we ever need them?)
* [ ] decide on policy of 'always sticky' vs 'only sticky if stretch > viewport'
* [ ] works on wide screens when the main header is sticky too
* [ ] works in some reasonable way on landscape mobile, not sure what is best here

**Comment by scd** [comment]
Since this was logged we have reworked the templates. Closing
