### ISSUE TITLE
Remove Google map maker reference from help article

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2464]

**Comment by scd** [comment]
@brendanheywood do you mean the Geolocation article. Do you want to do this? I can do it if it is just a mindless removal, but if it requires updates then it is best for you to do it.

**Comment by brendanheywood** [comment]
the mapmaker situation is worse than I thought, I thought it was going to come back once they sorted the spam issues but now they are discontinuing it completely (including many many hours of my edits in the past)

New wording: https://dev.thecrag.com/article/Geolocation

How do I add tracks to a map?
Right now you can't sorry! We previously encouraged editors to add information to Google Maps using MapMaker but Google has since watered down and abandonded this project. Many other climbers have requested we also use OpenStreetMap or other sources. We have on our roadmap to re-think our maps tools which will enable both easier inclusion of third party maps and also the ability to draw some key features such as car parks and walking tracks inside theCrag.

Please add your votes and comments to our todo list here:
Github issues related to maps
