### ISSUE TITLE
Crowd source flagging of a forum post as spam

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2465]
I can't believe we didn't actually have this on the list already. What I'm thinking is something simple to alert us to issues quicker, and to mitigate the effect of spam until we can action it properly. So something like:

* [x] anyone with a certain amount of karma can flag a post as spam, only needs to be quite low
* [ ] if a post is flagged spam, it immediately gets notifications turned off, so we don't email people, or have it show up in the dashboard for lots of people. The discussion would still be visible, but would have a label at the top saying it's been marked as spam by X, and will be reviewed shortly.
* [x] I think we should probably get a support email immediately, then one of us can take a look, and either use the spam nuke button to delete it, or to remove the flag if we deem it not that spammy. Notifications should resume if we remove the flag

**Comment by DaneEvans** [comment]
I was torn as to what would get the faster response, tagging you, or posting it here. I went with the easier option...
But I agree, it needs to be available.

**Comment by brendanheywood** [comment]
Thanks @DaneEvans :)

Some more thinking out loud:
* [ ] similar to support emails we probably need to find and delegate this to people in each language, but maybe spam is just spam and easy to pick regardless

**Comment by brendanheywood** [comment]
+1 support issue

**Comment by brendanheywood** [comment]
Food for thought 
https://meta.stackexchange.com/questions/313754/updated-comment-flagging-supporting-the-new-code-of-conduct

**Comment by scd** [comment]
done
