### ISSUE TITLE
No facet filter for date ranges

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2467]

**Comment by birgander2** [comment]
Yes, please!

**Comment by brendanheywood** [comment]
fyi in the mean time the urls and logic is all there, it's just the GUI which is missing, eg:

https://www.thecrag.com/ascents/by/brendanheywood/logged-after/2014-01-01/logged-before/2015

https://www.thecrag.com/climbing/australia/routes/before/1965

**Comment by quaestor** [comment]
+1. I used the manual URL modification hack quite often already.

**Comment by brendanheywood** [comment]
So the filter for climber dates it in prod. There is also the filtering on log date which works in the urls but I'm not sure if it worth the clutter in the UI to add two date filters which is also confusing

**Comment by brendanheywood** [comment]
eg https://www.thecrag.com/ascents/between/2014+2015/by/brendanheywood/?sortby=when,desc
