### ISSUE TITLE
Field tag shown in  menu

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2468]
Saw this in the action menu:

![image](https://cloud.githubusercontent.com/assets/22091505/20518225/7b763700-b0f2-11e6-947b-d3b536692f51.png)

**Comment by Mdemaillard** [comment]
The menu changed significantly since 2016...
![image](https://user-images.githubusercontent.com/60388146/76424749-51be2b00-63b1-11ea-9661-ad6ef0815920.png)

Closing
