### ISSUE TITLE
Tuff should be Tuff in German translation

### ISSUE THREAD

**Issue by scd** [theCrag/website#2471]
Feedback from a user:

 > I did not check all the others but realized at least one wrong transformation: The English Tuff becomes the German Tuffstein, which anyhow has a slighly different and more technical meaning. After all it's >wrong< [;)] In German the correct meaning is just Tuff, too

Came from this discussion:

https://www.thecrag.com/discussion/934782630/welcome-harald-how-can-i-help-you#m1020305685

**Comment by rouletout** [comment]
this is done
