### ISSUE TITLE
login endpoint should return translations keys not plain english

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2472]
`api/login/`

is returning "not a valid username ...." a translation key would be better

**Comment by brendanheywood** [comment]
Are we translating anything in the API? Most apis don't translate much as the strings are generally to be read and consumed by a developer. How would the API even know what Lang? If the call is using oauth then the server side Lang state could be different to the client side state. If not using oauth then would the app send an accepts header? I'd prefer to avoid all this and the API only returns code and all translation is done in the app

**Comment by nicHoch** [comment]
that is exactly what i am asking for. right now it returns error messages: full sentences in English. But i need some code number or code key string and that would go into the translation.

**Comment by nicHoch** [comment]
@scd 
this is becoming urgent
at least at sandpit

**Comment by scd** [comment]
@nicHoch it is a difficult 10 days for me. This weekend I am traveling to Sydney for a couple of days to see family then back to Melboure then back to Sydney for a funeral.  I am going to try and do the release on Monday or Tuesday but everything is up in the air for a little bit.

If you want to fit in with my processes please assign the issue to the next release milestone. I don't look at issues beyond that, which is probably why I have missed this. Also I often don't have time to look at much more than the must be fixed issues, so if you really want something done for the next release then it should have this tag.

**Comment by nicHoch** [comment]
That's fine. It is not supper urgent is was more meant as a reminder

Am 20. April 2017 14:28:47 MESZ schrieb Simon Dale <notifications@github.com>:
>@nicHoch it is a difficult 10 days for me. This weekend I am traveling
>to Sydney for a couple of days to see family then back to Melboure then
>back to Sydney for a funeral.  I am going to try and do the release on
>Monday or Tuesday but everything is up in the air for a little bit.
>
>If you want to fit in with my processes please assign the issue to the
>next release milestone. I don't look at issues beyond that, which is
>probably why I have missed this. Also I often don't have time to look
>at much more than the must be fixed issues, so if you really want
>something done for the next release then it should have this tag.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2472#issuecomment-295717761

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by scd** [comment]
done on simon dev
