### ISSUE TITLE
Extra flags for sensitive or closed areas (streams, photos, ticks, etc)

### ISSUE THREAD

**Issue by scd** [theCrag/website#2476]
If an area is closed we should consider what to have in the streams. If a climber has added information to an area which then becomes closed then the climber may no longer want to be associated with the area due to sensitivities

Consider:
  * turning off streams for closed areas
  * turning off climbers with max karma for closed areas
  * if not turn off streams allow a climber to turn themselves off for that area

**Comment by brendanheywood** [comment]
I don't think we should do anything based on karma, nor would I do something which is per user. I'd simply want a flag which is to show the stream or not. If you are a coordinator I would still show the stream, but show a message above it stating that only other coordinators can see it.

To me the question is whether the flag is a new independent flag, or whether it piggy backs of the closed tag, or perhaps something else existing like the 'locked' flag. I'm leaning towards a completely new flag as it's the simplest and most transparent for everyone.

**Comment by scd** [comment]
New flag it is then. I am happy with this solutions

**Comment by scd** [comment]
I have added a few new flags to resolves some of Neil's issues:

![screenshot from 2016-12-29 13-33-55](https://cloud.githubusercontent.com/assets/373058/21535607/91b72b28-cdcb-11e6-9372-d504b3990da7.png)

**Comment by scd** [comment]
updates flag
 - [x] update in database
 - [x] available in template data
 - [ ] disable in in streams

ticks flag
 - [x] update in database
 - [x] available in template data
 - [ ] disable in in streams

photos flag
 - [x] update in database
 - [x] available in template data
 - [ ] disable facet
 - [ ] no photos to main area

locations flag
 - [x] update in database
 - [x] available in template data
 - [x] turn off main area page map
 - [x] turn off locate area
 - [ ] no data to map
 - [ ] no data to mobile app

access flag
 - [x] update in database
 - [x] available in template data
 - [ ] turn off in main area page
 - [ ] no data to mobile app

pdf flag
 - [x] update in database
 - [x] available in template data
 - [ ] turn off in main area page

**Comment by brendanheywood** [comment]
If a crag is sensitive, but not closed, there are valid use cases for certain people with permissions to see these things. So how much extra work would it be to make info with the flag visibly to coordinators and editors but no one else? This seems much more useful and flexible going into the future and effectively also gives us #753 too.

**Comment by scd** [comment]
I have been thinking something similar. At the moment the field is saved as a mysql tiny int, but I guess we could change that to a normal int and store status. 

We could have hide status for:

- Completely hide
- Coordinators only
- Coordinators or qualifying karma

The way which we would typically implement something like this is define the statii in a category and use the category ids. 

Alternatively we could store a level as an integer and leave the interpretation of the level as business rules in the code.

0 (or undefined): available everywhere
1: must be logged in
2: must have minimum karma for us to say you are most likely a climber
3: must have editor permissions
4: must have coordinator permissions
5: must have admin permissions
9: completely hidden

It is much easier to do this now then after release, but will require some rework.

 hide

**Comment by brendanheywood** [comment]
I think we do this right, the urgent issue right now has been mitigated so there is no time pressure to release

**Comment by scd** [comment]
This is not urgent for the permissions stuff but is pretty compelling to help Neil mitigate issues with the authorities. It has also come up several other times in the last year. In particular there was an issue recently with somebody making their account private to hide an accidental update. For the life of me I cannot find the issue/email/ or site message where this was discussed.

I want to get something out for next release. It is probably only a little bit of work left to compelte this as a flag. I would be ok with this being implemented in order to trial something while we get an understanding of the real requirements. Otherwise I want us to put our heads together to get a longer term solution.

Decision time:
A. Just go out with a flag and change later when we understand better
B. Implement something that has more flexibility

I am comfortable with either of these decisions, but we need to do one of them

**Comment by brendanheywood** [comment]
I think this all comes down to the migration of the flag if we break it into two steps. If it's creating more work to migrate it later than to do it more flexibly now then lets do it the better way. We've been talking about lots of different issues which touch on this for years, Neil's case is one of many and there will be lots more. Even if we need to remove stuff now to help Neil we can workaround that by just editing the content, it's not critical to use this new feature.

**Comment by scd** [comment]
We cannot easily remove locations now. I would have worked on that, but I think this is a better solution because it does not remove the information.

Are you happy with the levels idea. I will update to that if you are happy with that.

**Comment by brendanheywood** [comment]
Yeah those levels were great

**Comment by scd** [comment]
Great, I am happy to make those changes now and see how it goes. Whatever we do will still be testing the idea and subject to change.

**Comment by scd** [comment]
I have updated the flags to levels:

![screenshot from 2017-01-01 14-24-20](https://cloud.githubusercontent.com/assets/373058/21580099/1b92854a-d02e-11e6-8624-e633388b7284.png)

The template data for an area now has a hide parameter:

```
"hide": {
    "access": {
        "node": {
            "id": "11740915"
        },
        "level": "100"
    },
    "updates": {
        "node": {
            "id": "11740915"
        },
        "level": "100"
    },
    "photos": {
        "node": {
            "id": "11740915"
        },
        "level": "100"
    },
    "locations": {
        "node": {
            "id": "11740915"
        },
        "level": "100"
    },
    "ticks": {
        "node": {
            "id": "11740915"
        },
        "level": "100"
    },
    "pdf": {
        "node": {
            "id": "11740915"
        },
        "level": "100"
    }
},
```

This can be inherited from ancestor crags, hence the node to tell us which ancestor area the hide directive came from. If we do end up using the node then I will expand this.

A user has a view level assessment based on their karma and area permit.

```
viewLevel: 32,
```

And the template has the following pattern:

```
if ( !canView('locations',$data->{hide},$account) )  {
}
```

**Comment by brendanheywood** [comment]
I think the same as the inherited tags and fields we'd want to show from day one where they are set in the GUI, so please expand that in the template data. 

Also does it make any sense to have more permissive levels at a lower node? If not then should to editing GUI only allow more restrictive levels as an override?

**Comment by scd** [comment]
I have populated the node.

I am not sure if it makes sense to have a more permissive node at a lower level. But I am not certain of all the use cases.

If we do implement this via the gui then we need to work both ways. Not only restrict lower level nodes but also change lower level nodes if the higher level changes. I am happy to hold off on this functionality.

Alternatively we could just do it at read time via the templates and only use the lower level permissions if it is less permissive.

Maybe just leave this for a bit, because the main use case will to hide info at a crag. Also it is only us System Administrators who can do it for now.

**Comment by scd** [comment]
I have finished this on my dev so closing now
