### ISSUE TITLE
Contact / feedback form to augment the support email address

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2481]
Most of our emails are from existing members, it would be better to have a form they can fill out which stream lines a few things. This could work inside the platform similar to a private message, or it could just send an email on their behalf. I prefer the latter and this would also work well for anon users who either haven't signed up yet or who aren't logged in (eg could be having login issues)

* [ ] has a quick topic choose with some common choices such as:
  * [ ] I have a feature request
  * [ ] I found a bug
  * [ ] I'd like to add a new crag
  * [ ] General feedback
  * [ ] I need more permissions
* [ ] Name - auto filled out if logged in, but they can edit it (eg change a nick name to a real name)
* [ ] email - auto filled out if logged in, but again they can edit it
* [ ] Subject
* [ ] body, markdown with preview like other places

The subject and body would have a chunk of boiler plate content filled in depending on the topic and they can insert / edit the bits they need

This would send an email to support, include a bit of extra data for logged in people, and have a reply-to address of their email to continue the conversation. We would still provide the email for anyone who wants to use it that way and for people who need to attach files etc

**Comment by Mdemaillard** [comment]
Some of the intent of this is covered with the contact-me update that links to a lot of ressources and add mail as last resort.

Still, the form would help for:
-anon users who either haven't signed up yet or who aren't logged in (eg could be having login issues)

**Comment by scd** [comment]
I am not in favour of a contact form. I think we should just close this
issue.

**Comment by Mdemaillard** [comment]
I agree, 
- anon should create an account, (else why contact ?)
- unlogged should log
- login issue will be minimal at most and might require attention that the email will generate.
