### ISSUE TITLE
Unlocated areas warning says "We don't know where this sector is located. Do you?  Locate {areaName}"

### ISSUE THREAD

**Issue by pmonks** [theCrag/website#2482]
Here's an example:
![image](https://cloud.githubusercontent.com/assets/54865/21118809/6e2cadfe-c074-11e6-923b-76e7c7088625.png)

**Comment by Mdemaillard** [comment]
That one was corrected. 
![image](https://user-images.githubusercontent.com/60388146/76425409-3f90bc80-63b2-11ea-99d6-9fb1063b7270.png)

Buuuuut a typo introduced in the additional green message:
If ...this crag the**N** please...

**Comment by scd** [comment]
I have fixed theN typo. Will be available next time I push translations.

**Comment by Mdemaillard** [comment]
confirmed done.
