### ISSUE TITLE
Translation bug in stream for 

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2483]
![image](https://cloud.githubusercontent.com/assets/187449/21121354/08fa8990-c120-11e6-8491-b8182fabece2.png)

https://www.thecrag.com/event/1026951015

Tasks:
* [ ] add line breaks to text
* [ ] fix the {to} placeholder in the text

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76433440-03168e00-63bd-11ea-9e39-d9eb1bdbe891.png)

Implemented some time ago. Closing
