### ISSUE TITLE
Translations: Variable missing

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2485]
Seems this one fell in between the cracks.... key is shown instead of crag name
<img width="649" alt="screen shot 2016-12-14 at 14 51 25" src="https://cloud.githubusercontent.com/assets/19162952/21171432/73872abc-c20f-11e6-96de-55bd6b6f196b.png">

**Comment by Mdemaillard** [comment]
Seems "fixed" 
![image](https://user-images.githubusercontent.com/60388146/78505378-6c4ab080-7773-11ea-930c-773f4bb326a3.png)
