### ISSUE TITLE
plupload - retry upload if failed

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2490]
Need to handler errors an enable a retry of the same file

![image](https://cloud.githubusercontent.com/assets/187449/21448167/9ff90f22-c933-11e6-8013-19ef68505311.png)

**Comment by brendanheywood** [comment]
We should also update plupload to the latest version again

**Comment by scd** [comment]
Plupload will eventually be replaced. I think we can live this issue until then.
