### ISSUE TITLE
relative time delta is too vague in forums

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2493]
There is something screwy with the logic in the time delta relative time, it's always 'today' instead of '10 mins ago' or 2 hours ago'

![image](https://cloud.githubusercontent.com/assets/187449/21490337/7d57b15a-cc47-11e6-80c4-fae1758ad1b4.png)

**Comment by scd** [comment]
regression issue in message template. The relative_time function call was missing a flag being set.

hotfixed
