### ISSUE TITLE
Translations: searching key

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2494]
Realized that this is pretty messed up in German - can you please let me know the set of keys covering the text here? Couldn't find it....

By the way, the date (weekday) is not translated at all, the date has the English abbreviation (th).

<img width="711" alt="screen shot 2016-12-12 at 12 50 00" src="https://cloud.githubusercontent.com/assets/19162952/21532271/83370b2c-cd03-11e6-8d58-8f3bca63cb88.png">

**Comment by scd** [comment]
They start with template.account-settings.contributions

Here are some keys:

```
template.account-settings.contributions.financial.since
template.account-settings.contributions.content
template.account-settings.contributions.content.karma
system.action.donate
```

I think we text search
