### ISSUE TITLE
Weird disabled account but still visible

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2498]
I just clicked the 'spam nuke button' twice with two different forum spam accounts, one in krabi and one in canberra. This account is disabled but still visible:

https://www.thecrag.com/climber/kyduyen

**Comment by scd** [comment]
Note to self. I think we may be disabling the account record not the membership record. I think we need to disable both. Needs a bit more investigation

Look for removeSpamAndAccountFlag in API/Message.pm

**Comment by scd** [comment]
I think this was fixed.
