### ISSUE TITLE
Request permissions process

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2499]
We've removed the request permissions process, but ultimately we need something like it but with a better workflow rather than just approving it. Some ideas to throw around:

* anyone can request more permissions at a certain node
* anyone with a coordinator role can see a list of requests somewhere (with a message: 'Only coordinators can see this list')
* anyone with a coordinator role at that node can approve it
* perhaps the request would be a stream event when approved, eg 'Simon gave Bill the coordinator role for Arapiles'. I think this matters more for general crowd sourcing of approvals, but we will probably still do most of them

**Comment by scd** [comment]
I have made an update to the request permission process. This should be sufficient for this release. The new process is that anybody can request permission in which case we send them an email which looks like this:

```


Hi Test,

We have noted your (testpub) request for editor permissions for Para Wirra. We will assess this as soon as we can and get back to you. If we have not responded in a couple of days please feel free to follow up.

Response to: scd+test@thecrag.com

First joined: 2011-02-24

Number ascents: 0

Karma: 1

Your reason follows:

I want to help

Happy cragging!

Brendan, Campbell, Nicky, Simon and Ulf
```

This is currently cc to me, but after the release I will create a generic support account connected to support@thecrag.com

The idea is we will get an email with some key account information and to help us make the decision to give them access. We just need to reply to all when it is done.

**Comment by brendanheywood** [comment]
Can you also put in the url of the area so we can jump directly to it?

Also is that a raw text email like above or does it go through the normal email templates?

**Comment by scd** [comment]
Actually both the account name and area name are linked, it just did not come through in the cut and paste.

Through our normal templates. I thought about this for a while and decided that we want to email the user immediately when they request, which means the email must be translated and come through our normal email templates.

**Comment by brendanheywood** [comment]
Perfect :)

**Comment by brendanheywood** [comment]
I think this has been lost in trello so dumping here. We get lots of manual emails asking for permissions instead of via the 'Request permissions' button. I suspect the root cause is that button just isn't present in many cases.

I have my alter ego test private account, it only has 10 karma:

https://www.thecrag.com/climber/evilbrendanheywood

I would expect this account to have almost no ability to edit at all, eg if I pick a random cliff I can see I have no permissions:

https://www.thecrag.com/climbing/australia/victoria/melbourne/area/1463064855/account-permit/evilbrendan

And yet all the way down that same hierarchy:

https://www.thecrag.com/climbing/australia/victoria/melbourne/route/1076185152 <- can edit route
https://www.thecrag.com/climbing/australia/victoria/melbourne/area/1463064855 <- can edit sector
https://www.thecrag.com/climbing/australia/victoria/melbourne/area/1228953615 <- can edit area
https://www.thecrag.com/climbing/australia/victoria/melbourne/area/1023222720 <- can edit crag
https://www.thecrag.com/climbing/australia/victoria/melbourne/area/1023101124 <- can edit region
https://www.thecrag.com/climbing/australia/victoria/melbourne  <- cannot edit, no request button
https://www.thecrag.com/climbing/australia/victoria <- no button
https://www.thecrag.com/climbing/australia <- no button

I assume this is because that route and area is low kudos?

Lets pick on at araps, I found the lowest popularity route in the most popular crag:

https://www.thecrag.com/climbing/australia/arapiles/the-pharos/route/12923251 <- no edit button, no request button
https://www.thecrag.com/climbing/australia/arapiles/the-pharos/area/11971945  <- request button
https://www.thecrag.com/climbing/australia/arapiles/the-pharos                          <- request button
https://www.thecrag.com/climbing/australia/arapiles/the-pharos-and-surrounds  <- request button
https://www.thecrag.com/climbing/australia/victoria/north-west                            <- no request button

So it's really hit and miss where this button is show. I think the key here is consistency:

* [ ] If you can't edit **always** show the request button, but it just may go to different places.
* [ ] If the node in question is a route then the button request should be for the parent node
* [ ] If the node is something large like a region or country, then still add the button but maybe just make it a link to the permissions article, or add a button dropdown with a comment saying ask for a lower crag instead.

**Comment by brendanheywood** [comment]
Ah sorry simon I think this is done but not released in https://github.com/theCrag/website/issues/2941 ?
