### ISSUE TITLE
Decide and change performance ranking param names

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2508]

**Comment by scd** [comment]
General terminology
 * Climber Performance Rating
 * Climber Performance Rank

Style specific
  * Trad Rating / trad-rating
  * Sport Rating / sport-rating
  * Boulder Rating / boulder-rating
  * All Time Trad Rating / all-time-trad-rating
  * All Time Sport Rating / all-time-sport-rating
  * All Time Boulder Rating / all-time-boulder-rating

**Comment by brendanheywood** [comment]
I've also updated the sub menu to reflect this and link directly to each page:

![image](https://cloud.githubusercontent.com/assets/187449/21960347/fde704a8-db3b-11e6-8c19-d10d0d866cdb.png)
