### ISSUE TITLE
icon capitalisation issues in Crag Guru, route name all lowercase

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2509]
I've seen this a few times, but not really checked that it was a real thing.

https://www.thecrag.com/climbing/australia/pierces-creek-bouldering/area/11833099

The name of some routes in the Crag Guru appears in all lower case, despite the route name being correct. 

- It seems to be most likely to occur on the first route on the list (lowest grade)
     - it can occur on the second route at least
     - it doesn't occur all the time
     - it seems to be related to being in a 'crag'
     - if you go up to the parent area it works 
![image](https://cloud.githubusercontent.com/assets/22091505/21704572/6f231196-d40e-11e6-88c3-d47f0f025489.png)

- the routes in question were never named in lowercase
![image](https://cloud.githubusercontent.com/assets/22091505/21704572/6f231196-d40e-11e6-88c3-d47f0f025489.png)
![image](https://cloud.githubusercontent.com/assets/22091505/21704578/78fbcb54-d40e-11e6-9769-9699573690f8.png)

**Comment by lordyavin** [comment]
Got that too.

**Comment by brendanheywood** [comment]
> it seems to be related to being in a 'crag'

ah! I've only just re-read this carefully and that observation around the node type = crag was key!

I managed to trace this back to a bug in the markdown processor which was accidentally mutating the node object details while doing string comparisons

Finally squashed :)
