### ISSUE TITLE
NumberTopos field from Index Detail API returning wrong value

### ISSUE THREAD

**Issue by stuartin** [theCrag/website#2513]
When performing an index api call for the top level crag, a child area is reporting the wrong value for the NumberTopos field.

Example API call (TLC = Chiang Mai)
https://sandpit.thecrag.com/api/index/detail/11875969?key=abc&abbr=0&withdata=NodeID,Name,NumberTopos,Topo

You can look for nodeId: 13950577 (The Gatekeeper)
It reports NumberTopos: null, but it does list Topos.

When performing a direct area API call on that nodeId:
https://sandpit.thecrag.com/api/area/id/13950577?key=abc

It does report the correct NumberTopos.

I would like the Index Detail API call to report the correct NumberTopos for all child areas.

**Comment by scd** [comment]
This is probably the known cache issue. I do not propose to do any further work investigating this particular issue for now so closing.
