### ISSUE TITLE
Route facet, for all the 'data' filters also add the reverse, ie show route *with* descriptions

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2515]

**Comment by scd** [comment]
hot fixed:

https://www.thecrag.com/climbing/united-states/adirondacks/routes/has/description/

**Comment by brendanheywood** [comment]
I think we should rename 'Missing data' to something like 'Has fields' or 'Content' and then in the list has 'Has description' and 'Missing description' etc

**Comment by scd** [comment]
sounds good
