### ISSUE TITLE
Add filter to facets for wether someone is a support, or is not a supporter

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2519]
eg something like:

Climbers facet:

* [x] https://www.thecrag.com/climbing/world/climbers/using-stat/karma/is/supporter

* [x] https://www.thecrag.com/climbing/world/climbers/using-stat/karma/is/not-supporter

Ascents facet:

* [x] https://ww.thecrag.com/climbing/australia/ascents/climber-is/supporter

* [x] https://www.thecrag.com/climbing/australia/ascents/climber-is/not-supporter

**Comment by scd** [comment]
I have done the backend of this so the urls work.

**Comment by brendanheywood** [comment]
Added the facet ui:

![image](https://cloud.githubusercontent.com/assets/187449/21954751/0186031c-daaf-11e6-9a05-87f09d8f1961.png)

**Comment by brendanheywood** [comment]
btw I added 3 lang strings for this @theCrag/translators
