### ISSUE TITLE
Grade context / system chooser / selector similar to language selector which converts all grades

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2527]
In a similar vein to the idea of choosing your preferred language for a crag (#2429), it also makes perfect sense to choose your preferred grade system for a crag. In most cases it would be set to 'auto' which shows the principal grade, but you could choose to set it to whatever system you want.

![image](https://cloud.githubusercontent.com/assets/187449/21959773/41b2112a-db26-11e6-83e6-3f735562c7ac.png)

This goes hand in hand with the grade context shown in the crags (and accounts pages #2526), and the chooser would be integrated directly in this display.

This also has a strong relationship to #2525 (floating the principal grade)

**Comment by brendanheywood** [comment]
+1 from @rouletout

**Comment by rouletout** [comment]
Global lists like https://www.thecrag.com/climbing/world/routes/?sortby=grade,desc require a universal grade conversion to make sense and being useful. Preferably it is in a grade context the user can select.

**Comment by brendanheywood** [comment]
There is a few simpler things we can do here in the interim which would be complimentary too:

1) For the route and ascent facets based off a node then we can use the default context for that node and show the prefix for grades outside it, eg "FR 9a" so it is at least explicit. This may even be preferred by many as it shows the original grade and no conversion is perfect.
https://www.thecrag.com/climbing/europe/routes/

The world node defaults to the US context

2) In the giant grade group headers, we could show the top 3 most common grade systems side by side, or perhaps just the grades systems actually in use in that particular facet. This has the advantage of now only retaining the original grade, but also helps educate people about the conversions:

![image](https://user-images.githubusercontent.com/187449/46154744-27f66e80-c2b9-11e8-90d3-ba7eb52250d5.png)

**Comment by rouletout** [comment]
+1 from support (mailto:misledluke@gmx.at)

**Comment by brendanheywood** [comment]
A semi +1 from support email. Here the confusion was around contexts as a concept vs grade systems.

In an ideal world we would never need to expose the concept of a grade context to a typical casual user. ie instead of saying talking in terms of context and in this case say "Grades: FR" we could detect the actual grade systems being used in this particular cliff or crag and instead say "Grades: FR" when it was actually a sport crag and "Grades: Font" when bouldering. If it was a bit of both then we could show "Grades: FR, Font, others" or "Grades: Font, FR, others" depending on relative usage.

This also ties into the swapped a little, because everyone naturally thinks in terms of systems and not contexts which are unique to us. So I think it would be better if instead of linking to the article page for a context, it instead opened a little popup which showed each dominate gear style and which system it defaults to in the current context. Then when we offer the ability to switch grade systems we are actually showing in this popup what systems to convert to, and not simply just the context.

**Comment by Mdemaillard** [comment]
Candidate for closure after release 81 ?

**Comment by scd** [comment]
I am going to close this because we have done the work for the conversion and this was not a targetted task. We may reopen later.
