### ISSUE TITLE
How to prioritise rating systems when multiple rating systems on a particular route

### ISSUE THREAD

**Issue by scd** [theCrag/website#2534]
A route may have multiple rating systems. Mostly they are things like 21 M1 where there is an aid grade associated with the main grade. There are all sorts of combinations, so we should be clearly identifying which ones do not apply for rating purposes.

Also the particular use case we cannot get around is UK grades. Routes often come as a combination of UK Adj. and UK Tech. grades. We should be rating on just one of these.

Do we want to rate on just UK Tech? Or do we want to rate on UK Tech and if not present UK Adj?

All of the above is solved by adding a rating priority field to the RatingSystem table.

If the priority is not set then the rating system is not used for rating, and if it is set then the rating system with the lowest priority order is used. 

I need to know the answer to the UK grades purely for setting the configuration in the new field.

**Comment by brendanheywood** [comment]
UK tech is the appropriate thing to compare to AU, USD, FR etc If it is not present then we can't compare it, that's on par with comparing a V grade to a jump grade, it just doesn't make sense.

For each system their is a 'type', most are 'Free', but there is also 'Aid', 'Boulder' - it's almost like we need a second type system something like 'Technical', 'Boldness', 'Quality', and in theory any two systems of the same type should be able to be translated into another system of the same type. Most normal systems would be 'technical' including the UK teck, while the UK Adj would be 'boldness'. The boulder V-grade is also 'technical' and so we would be able to directly translate into USD, FR etc Do you think such an attribute is worth exploring - or does it already exist?

**Comment by scd** [comment]
There is no parameter as yet which says whether it is a technical difficulty level. The parameter I am suggesting would tell us which rating systems match the criteria for ranking. 

The rating system is designed to be very generic, so jumps and stars are also included. This means there are many different types of rating system.  We could create a new parameter for all of the different types.

However while it is good to know that a rating system is technical for ranking, I don't think we need to explicitly categorise 'boldness' though. Note that the AltGrade in an ascent is for this secondary system.

In the interest of pragmatism I am just going to add a Technical Priority Order field purely for ranking. Leave the rest for another day.

Based on your explanation we should remove the UKAdj from the grade systems table. Originally I had the feeling that it was also used with some sort of alignment to difficulty. I think that was just an error on my part.

I have had further thoughts about translating V-grade to YDS  and I think there is some value in this from a Climber Performance Rating point of view. I think we should be normalising so that comparing a climbers Boulder and Sport performance rating makes some sort of sense. On average a climbers trad rating should be lower than a climbers sport rating which in turn should be lower than a climbers boulder rating, as each of the various styles has more emphasis on the technical difficulty of the moves. So as long as the overall stats make sense then I am happy with the conversions.

**Comment by scd** [comment]
I have done this on my system.

**Comment by scd** [comment]
Actually I have just done further investigation on UK Adj grade and there are a couple of errors in the way we are dealing with this. I will create a separate issue.
