### ISSUE TITLE
Add account option to explicitly set the profile page grade context

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2540]
By default all profiles will automatically figure out which grade context to show, to people viewing your profile:

* [x] The default will be whatever is implemented in #2526
* [x] But a person should be able to select the context explicitly
* [x] Or set it back to automatic
* [ ] and the current auto choice will be shown in the drop down

![image](https://cloud.githubusercontent.com/assets/187449/22065973/cc2a54ce-ddde-11e6-8561-0b6907587e59.png)

**Comment by brendanheywood** [comment]
I've split this up better, this task is now just the config option which can come later, and the algorithm to chose a grade context for an account is in #2526

**Comment by scd** [comment]
I gather from #2526 the purpose of context is to restrict which profile grading system can go together. So you could not display the french grading system on a profile with a UK context. Is there any other purpose.

Note that we might need to take this one step further, to allow the user to pick the actual grading systems as well.  For example if you are in US context there are multiple bouldering systems and there may be a group of climbers who what to keep using their 'B-Scale' bouldering.

**Comment by brendanheywood** [comment]
> I gather from #2526 the purpose of context is to restrict which profile grading system can go together. So you could not display the french grading system on a profile with a UK context. Is there any other purpose.

Sorta but not quite - I don't want to restrict what grade systems are shown at all, I just want to make it explicit what system a particular displayed grade is in. If most or all grades on the page are in the same context then the only thing you need to know is in the top right hand corner. If there are any exceptions outside that context they will still show but be clearly marked eg 'FR:6a' so you don't get ambiguous grades all mashed together on the same page.

> Note that we might need to take this one step further, to allow the user to pick the actual grading systems as well. For example if you are in US context there are multiple bouldering systems and there may be a group of climbers who what to keep using their 'B-Scale' bouldering.

I don't think it's required. The main point here is just to reduce the ambiguity around showing many grades from different systems on the same page without showing what system / context they are in. The B-scale isn't a good example because the b-scale grades don't overlap with any other grade system. The major issue which happens heaps is the overlap between the french grades and other similar grade systems. In theory I thought most contexts couldn't contain systems which overlapped (or if they did they were super rare).

eg right now I could have a 'Hardest grade' of 6b which matches 5 systems (if you weren't aware of and remembered the case differences between climbing and bouldering french grades)

**Comment by scd** [comment]
+1, I understand the display ambiguity issue.

**Comment by brendanheywood** [comment]
As is, this issue has been essentially done for some time. So I will close it, the future direction here we are probably leaning towards splitting this up into per gear style settings but we want to let the new profile pyramids and notable ascents settle in before we make that call.
