### ISSUE TITLE
RatingSystem: filter only the ascents that apply to the node/style/time

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2542]
https://dev.thecrag.com/climbing/switzerland/jura/climbers/using-stat/sport-rating/

the ranking score for a certain node (not world level) is calculated only based on ascents in/under this node and the style and time.

In the result list you see only the total ascents (world). For reliability it is important to know the number of ascents in the actual node level and also get a link for all this ascents. Also the ranking route style (sport/boulder ...) and time period (all time ...) have to be by considered in the filter.

**Comment by scd** [comment]
> For reliability it is important to know the number of ascents in the actual node level and also get a link for all this ascents

Do you mean total ascents at the node or total ascents for a particular climber at the node?

 > and also get a link for all this ascents. Also the ranking route style (sport/boulder ...) and time period (all time ...) have to be by considered in the filter.

This is mostly done. The filter facet is completely done, so we just need the UI to create the link from the climber card entry. The two sample links are in #2504

**Comment by brendanheywood** [comment]
done in #2504
