### ISSUE TITLE
Bug with stream event missing data

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2548]
Just saw a weird stream event from @willmonks with no data:

https://www.thecrag.com/event/1051516920

![image](https://cloud.githubusercontent.com/assets/187449/22280183/45670b36-e323-11e6-9ca4-f4e8e66950b6.png)

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76497729-3fd99800-6444-11ea-8a3c-f96dd86f8d30.png)

Event has now content in the event card, also on his full stream event. Will not be able to check on the global stream if it is present or not because of the date.
Closing
