### ISSUE TITLE
Internal admin facet for admin photo category

### ISSUE THREAD

**Issue by scd** [theCrag/website#2559]

**Comment by brendanheywood** [comment]
Why internal? I think this should just be a new public facet filter by quality or sort by quality. This paves the way for community consensus voting #1666 #1062 

Ultimately our vote should just be one of many opinions. (note flagging a photo would be tangential to voting)

**Comment by scd** [comment]
The main reason for internal is that I don't want to expose our internal ratings to the general public in case it causes some complaints. Once we have the ability for others to rate then I don't care. 

Lack of transparency is fine while it is all internal, but as soon as we make it partially transparent then we open ourselves up for complaints where we are not in a position to fix.

Anyway it's marginal and if you want to expose it then I can live with that.

**Comment by brendanheywood** [comment]
Sure ok, I'm easy either way. I just hate wasting time on this whole thing given we are going to throw it away. I'd just prefer to invest in it's replacement or step stones towards it

**Comment by scd** [comment]
It was already there:

https://www.thecrag.com/climbing/world/photos/photo-quality/agrade
