### ISSUE TITLE
Example of how to hide locations in a senstive area

### ISSUE THREAD

**Issue by scd** [theCrag/website#2561]
In the You Yangs, there is private property area, called Stockyards Car Park Area, which is potentially sensitive to location information.

I have turned off location access so you have to be logged in to see it:

https://www.thecrag.com/climbing/australia/the-you-yangs/area/11942395

Is this a reasonable thing to do, or should we increase the viewing requirements or turn off completely?

Note we should consider the text we display.

**Comment by rouletout** [comment]
This is somethingw e do on a "regular" basis - closing
