### ISSUE TITLE
Decide how to handle api calls eg maps for hidden secret / protected crags

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2562]
eg if we lock a location down, it's not visible on the index page but is still visible on the maps page. Obviously we should remove it here too, but this has bigger implications with caching and that api endpoint. So need to make a clear decision how we handle the perms for web api calls like this so it's consistent for all ajax calls. Ideally this should be the same mechanism for the mobile app, in theory at least a coordinator should be able to login to the app and see all this hidden stuff (eventually not a priority at all)

ie, if someone is not logged in, then any ajax call they make like this should still work but not return anything for the secret areas. If however they then login and go back to the same page we don't want them to see cached data. 

![image](https://cloud.githubusercontent.com/assets/187449/22394498/2472f524-e577-11e6-915d-2ab35cccb957.png)

**Comment by scd** [comment]
I thought I solved this. It was one of my tasks for this issue. There were three places I needed to take it out of the API. 

I cannot see Stockyards on the map. Please have a look again and tell me if I am wrong.

**Comment by brendanheywood** [comment]
Ah yes I got a bit mixed up. However do we still need to solve the general case, ie if the crag was only secret instead of closed?

**Comment by scd** [comment]
At the moment the API performs the same logic as the website (canView) but on the API auth user. If it is via the web the this comes from the session. If it is via a mobile app then this will come via the oauth.

So this is really cool and I am secretly excited by this. We can now hide features for people who are not logged in or have not demostrated themselves as real climbers via karma. For example we could hide locations for the whole of Sydney Metropolitan area to people who do not have karma. We trust people with karma so it may solve a few problems.

When we do a secret crag, I imagine we will extend the canView to do a join on the members of the secret crag. I am not sure if we will have to change things around for performance reasons, but I think it should be fairly manageable. 

It maybe worthwhile starting a doco on all the areas which are effected by viewing restrictions:
  * index
  * pdf
  * crag guide
  * locations api
  * mobile api
  * facets (facets still include routes from turned off areas)
  * stats (stats still come through from turned off areas)
  * streams (world level should not get stream updates from turned off areas - I think this is partially fixed).

**Comment by brendanheywood** [comment]
Ok so this is all done, was just a caching issue
