### ISSUE TITLE
add star ratings next to quality settings when logging and ascent

### ISSUE THREAD

**Issue by jedparkes** [theCrag/website#2563]
trying to get my head around the new stars system
i can edit a route and add my personal stars but when i'm logging an ascent it doesn't give me an option there to put my star rating?

**Comment by scd** [comment]
When logging ascents it comes from quality rating

**Comment by jedparkes** [comment]
ah ok but that's kinda confusing, you have a star system of 4 stars (0,1,2,3) then you have a rating system of 7 stars (Mega Classic, Classic,Very Good,Good,Average,Don't Bother,Crap)
Maybe it would help if the rating system had stars next to those words?
Mega Classic 3
Classic 2.5
Very Good 2
Good 1.5
Average 1
Don't Bother 0.5
Crap 0

**Comment by scd** [comment]
It is actually this

Mega Classic ***
Classic ***
Very Good **
Good *
Average
Don't Bother
Crap

I have updated the title of this issue

**Comment by jedparkes** [comment]
not sure if this is a seperate issue then but if you look at the ascents for Berts Butter Menthol
https://www.thecrag.com/climbing/australia/mount-wellington/organ-pipes/route/406430895/ascents
i logged an with a rating of average but the stars on the left don't reflect my rating

**Comment by scd** [comment]
There are a lot of ascents including quality ratings of Classic and Very Good. The stars are associated with the overall assessment of the route.

Do you just want to see your rating on the route, or do you want to see what the community thinks the route is?

**Comment by jedparkes** [comment]
i would think it would work that if i look at the route i would see the community stars next to the route but on the ascents underneath (and in my logbook) i would see the user's star rating rather than a blanked 2 stars when i have specified 1, its good to know what ppl think of a route at a glance
How does it work if a route is 2 stars and loads of people log ascents but don't specify a Quality does the calculation for the community stars include that ascent or only people how have specified a quality?

**Comment by scd** [comment]
sounds reasobable

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by brendanheywood** [comment]
As a start I've just added this to the ascent logging form:

![image](https://cloud.githubusercontent.com/assets/187449/22617995/d15a7560-eb25-11e6-8f73-f50173ee997b.png)

**Comment by brendanheywood** [comment]
I've also added the equivalent stars next to the word ratings

![image](https://cloud.githubusercontent.com/assets/187449/22618314/6bf862e2-eb2d-11e6-8cc1-eacfa2482272.png)

Was there anything else I missed or should I close this now?

@scd this is only in the templates, is there a more robust way so if we update the mapping in future it all just works?

**Comment by scd** [comment]
I don't know what you mean by a more robust way. Is it in a quality template? Do you want to do it via quality css card?

Happy for you to close this.

**Comment by brendanheywood** [comment]
I mean in the past this mapping between the quality ratings eg 'Very good' and stars was different, and we've only recently change it. Can you provide this mapping somehow so if and when it changes again we don't need to update this hard coded stuff. If we are super committed to the current mapping then lets close this issue

**Comment by brendanheywood** [comment]
well if it changes again later we can redo it properly then

**Comment by jedparkes** [comment]
what about the issue with the stars on the left don't reflect my rating
all the stars on the left are still showing as 2 stars?

**Comment by brendanheywood** [comment]
Isn't showing the ascents stars next to the rating enough? The star next to the route is still the consensus

![image](https://cloud.githubusercontent.com/assets/187449/22630254/bafff580-ec4a-11e6-8285-4befbd350e33.png)

This isn't on prod yet, release in a week or so.

**Comment by jedparkes** [comment]
the grade on the left isn't linked to the consensus grade so i think it would make more sense for the stars to be the same.
having the stars on the left showing the consensus stars then another column showing users rating stars looks confusing i think.
Maybe just remove the stars on the left?

**Comment by scd** [comment]
I disagree, I think it is really good to see the difference between what the climber thinks and consensus grade.

**Comment by brendanheywood** [comment]
> the grade on the left isn't linked to the consensus grade

huh? Yes it is- if it's not then there is probably a stats bug, can you provide an example? ** Berts Butter Menthol has a consensus of 2 stars everywhere else consistently?

**Comment by jedparkes** [comment]
I agree seeing the consensus grade and stars in the default guide book view but i'm talking about in the ascents view (logbook view also)
I looks confusing in the log book if i log a route as 1 star but shows 2 stars on the left.
Same as the grade issue that was just fixed showing consensus grade in log book rather than the logged grade.

**Comment by scd** [comment]
I don't get confused with this and find it a feature, but rather than argue with one person I am happy to see how it goes and gather some feedback. If the community agrees with you then we will get the feedback and change it.

The important step has been done and that is to make it more transparent what it means for each quality rating.

**Comment by jedparkes** [comment]
not trying to to argue :) just tring to help.
i can see how the feature to see the consensus stars could be helpful
consistency i what i'm thinking about.
ATM is the ascents and log book page are showing the users grade but are showing both the consensus stars and users stars.
Either show both the consensus and users grade and stars or on users grade and stars in ascents and log book page.

**Comment by brendanheywood** [comment]
Yeah I had that same thought too re the grades being ascent grades. I'm also thinking of swapping around the columns so that all of the ascent related stuff is on the left and all the fixed route stuff is on the right right.

**Comment by scd** [comment]
sorry @jedparkes I did not mean to use the word argue as it probably sounded. 

@brendanheywood if the ascent label is different from the route name then we show the route name in brackets. This may change when we finish the translation work. If you change the display to separate the route and ascent details then we should consider this as well.

**Comment by brendanheywood** [comment]
Ok so did a few prototypes, first swapping around the columns but I found this a bit pointless as almost everything except gear type and crag are ascent focused. I also prototyped just changing the stars over the ascents star, unless they are missing in which case it defaults to the consensus stars. In this scenario the second set of stars in the quality column is redundant so I've removed them. I also tried removing that column completely but this still has value as there are do many double ups in the mapping.

I have to say that I prefer this way now. My vote would be to change it both here and in the stream event template too. I get this is a reasonably big conceptual change so I haven't committed this yet and I'd like to get a bunch of different eyeballs on this so I'm just gonna mention a bunch of random people for input @nicHoch @lordyavin @rouletout @DaneEvans @willmonks @tomkjaerolsen 

So for some quick context for everyone, the question is in the logbook view, should the stars next to the route be the routes consensus stars (current state), or the stars that particular person gave for that ascent (mockup below)?

![image](https://cloud.githubusercontent.com/assets/187449/22637823/73da4040-ec98-11e6-82f5-badca12014d3.png)

**Comment by willmonks** [comment]
My vote is the other way.  IMO if the logbook shows user Quality rating
(e.g. "Very Good") then the route stars should be consensus stars.
Otherwise it's redundant to show stars at all - the user rating would just
be duplicated in a different format by "user stars", and the logbook is
less information rich.

Also, showing consensus stars is consistent with the old logging method of
ticking things off in a paper guidebook. The book gives "consensus" stars
when you buy it, then you might add or deduct some when you are writing a
log of an ascent, and then your logbook shows both your opinion and the
consensus.

Just my 2c though, not a big deal either way.

**Comment by brendanheywood** [comment]
Ok so there is not clear consensus one way or another so I'm going to stick with what we have, but I have added the stars to the quality column. I've also moved the quality column over next to the climber column so hopefully it's a little more obvious that quality is an opinion of that climber and not the overall quality.

![image](https://cloud.githubusercontent.com/assets/187449/23098124/5eb704c6-f69a-11e6-9670-1363966dadd6.png)
