### ISSUE TITLE
should be able to exclude particular ascents and people from ranking

### ISSUE THREAD

**Issue by scd** [theCrag/website#2564]
Admin should be able to exclude particular ascents and accounts from CPR
 - [x] exclude account
 - [x] exclude ascents
 - [ ] update ascent grade

**Comment by scd** [comment]
Eg.


https://www.thecrag.com/climbing/world/ascents/with-route-gear-style/sport/by/moxifloxi/?sortby=rating,desc


Moxi has onsighted an 8b+

She has done the first pitch of Mammuthone which is only a 6c+ but has not changed the ascent grade.

https://www.thecrag.com/climbing/italy/sardinia/cala-gonone/route/720130848

**Comment by brendanheywood** [comment]
So really we need to just fix #1698 and do a migration to fix up all the old grades in this category. Fixing them manually will still be required for the first two use cases but we shouldn't be constantly monitoring this and fixing up other peoples grades.

On that topic, we should also look into #2327 - I'll comment there too

**Comment by scd** [comment]
Admin can now exclude a particular ascent from CPR calculations and a particular account from Rankings. All other aspects of this issue are covered elsewhere so closing
