### ISSUE TITLE
Dropbox Custom PDF linking - 503 Error

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2569]
Just pressed the link to save PDF's into dropbox 'set this up by clicking here' and ended up with a 503 Error page. 

It says it was logged, but let me know if you need any further details not included in the log.

**Comment by scd** [comment]
Please let me know the details. In particular which crag

**Comment by DaneEvans** [comment]
https://www.thecrag.com/climbing/australia/nowra/new-nowra-braidwood-road/area/13248097

DownloadPDF > Custom > dropbox link pointing to https://www.thecrag.com/climber/10101301/settings-connections

Bounces to a page like this 
![image](https://cloud.githubusercontent.com/assets/22091505/22536225/3420ec66-e954-11e6-95fa-6d57277b6bc9.png)

**Comment by scd** [comment]
Ahh, the link to dropbox config is wrong. I have hotfixed.

Could you do me a favor and go through the process again and confirm it works for you.

**Comment by DaneEvans** [comment]
Thanks, seems to be working now. 

Is it possible to allow the directory to be user selectable?

**Comment by scd** [comment]
Last time I looked at Dropbox spec we could not do this. That was a while ago so maybe something has changed.

This is probably low on the priority list
