### ISSUE TITLE
Hidden location visible from sibling area

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2570]
![image](https://cloud.githubusercontent.com/assets/22091505/22536338/37ab7120-e955-11e6-90da-3a4b8fdfdb74.png)

ACT / Tidbinbilla / Scout crag 
- https://www.thecrag.com/climbing/australia/new-south-wales-and-act/australian-capital-territory/area/1019938086
- Tagged as Illegal
- Notice saying crag is unlocated (It isn't, and given that it's been disabled, this prompt should be too) 

If you go to a sibling area (Pierce's Creek) the location of Scout Crag is visible greyed out in the map, this should be disabled as well, or we could just delete all of the location information
![image](https://cloud.githubusercontent.com/assets/22091505/22536367/6b9dd112-e955-11e6-94cb-56d24c96a6a6.png)

**Comment by scd** [comment]
Thanks this is a good find. It is important that once we decide to hide location it is done properly.

**Comment by scd** [comment]
OK I have hotfixed this. @DaneEvans could you please confirm

**Comment by DaneEvans** [comment]
Looks to be solved, of course I'm looking for absence, so no guarantees. I'll keep an eye out as I keep browsing. 


- [ ] The 'Please locate this area' banner is still present and should be handled a bit more gracefully eventually

**Comment by scd** [comment]
Done on simons dev. Will be on prod after next release.
