### ISSUE TITLE
Audit and fix of outrider registered grades for ranking / rating  purposes

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2572]
So just noticed this one:

https://www.thecrag.com/climbing/australia/climbers/using-stat/trad-rating/

Elliot is # 1 but it's not their ascent which is wrong, it's the registered grade:

https://www.thecrag.com/climbing/australia/ascents/with-route-gear-style/trad/by/elliotvercoe/?sortby=rating,desc

https://www.thecrag.com/climbing/australia/swan-river/route/13376407

So if we fix the registered grade, then their ascent won't change but the min() will kick in and the stat should fix itself. I've left it in a broken state on purpose, I think we need to do a big audit and look for any registered grades which have other grade citations which are wildly different. In this case by a whopping 12 grades!

It may also be prudent to automatically fix the ascent grade too when the ascent grade and the current registered grade are the same.

**Comment by Mdemaillard** [comment]
From ascent: 
![image](https://user-images.githubusercontent.com/60388146/76498093-e02fbc80-6444-11ea-8e44-db58c7cbe18f.png)
![image](https://user-images.githubusercontent.com/60388146/76498163-048b9900-6445-11ea-838c-7baee95fa122.png)


From route page
![image](https://user-images.githubusercontent.com/60388146/76498122-ee7dd880-6444-11ea-801e-4f2c66f79e0e.png)

So it IS the ascent which was wrong.

For CPR purposes though, the value is in line with a 20
![image](https://user-images.githubusercontent.com/60388146/76498240-2ab13900-6445-11ea-95ec-960017dc6794.png)

So i guess the stats are fixed, simply his glorious personal ascent not. Good for him (maybe it was a typo)
Candidate for closure ?
