### ISSUE TITLE
Combine the 'misc flags' and 'Missing data' facet filters

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2577]
![image](https://cloud.githubusercontent.com/assets/187449/22618694/85018444-eb37-11e6-8db0-da2bbe27b8f8.png) ![image](https://cloud.githubusercontent.com/assets/187449/22618697/8b9e9e5e-eb37-11e6-9d02-a46282b6b5f4.png)

This would be better served as just 'Misc flags' and things like 'Bolts' becomes 'Missing bolts' - as well as 'Has bolts' - see also #2515

**Comment by scd** [comment]
this is done

**Comment by scd** [comment]
Note it may come up with other facets, so I have got a process combines the old facet into a new one, whilst maintaining backward capability with old urls.
