### ISSUE TITLE
Swap all filter facets around climbers to use select2

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2578]
@scd I'd like to swap the all of the facet which involve people over to use select2. What the best way forward on this one?

eg for a facet like this:

https://dev.thecrag.com/climbing/australia/arapiles/ascents/has/rating+ascent-date/with-route-gear-style/trad/by/adam_demmert/?sortby=rating,desc 

In some cases like this one, the name must match an account exactly, and we also been to keep the url working for backward compat. If I swap over to the new widget it makes urls like:

https://dev.thecrag.com/climbing/australia/arapiles/ascents/has/rating+ascent-date/with-route-gear-style/trad/by/@adam_demmert/?sortby=rating,desc 

Should be simply make this work in the backend? Or make the widget spit out the @ or not depending on context.

**Comment by scd** [comment]
Do you need any advice with how we implemented the select2 in the javascript. Do you want me to do anything here?

I do not like the `@` in the url from an asthetic point of view, however I think we should still handle it in the bankend if it ever came up. So I think we should do both the front end and back end solutions.

**Comment by brendanheywood** [comment]
I think the idea of using @ in the url has happened long ago, we are using it in other facets, eg the route FA facet filter: /routes/by/wills/  VS  /routes/by/@vwills/

But I think I'm going to change tack, and instead of changing the type of this facet from 'account' to 'mention' I'm going to re-implement the 'account'.

**Comment by brendanheywood** [comment]
all sorted
