### ISSUE TITLE
Make route archiving available for all sub areas in a gym and artificial walls.

### ISSUE THREAD

**Issue by scd** [theCrag/website#2579]
At the moment it has to be a feature in a gym.

**Comment by brendanheywood** [comment]
I think this is already strictly happening? There just was no gym node. Do we actually want to be able to have an artificial node without an ancestor gym node?

**Comment by scd** [comment]
Yes we absolutely want an artificial node that is not an ancestor of a gym node. This was the reason why we created this area type and it is precisely for the Wilson Bouldering Wall use case. I had only got halfway through implementing the template data and behaviour.

From a technical route management point of view, everything is the same for an artificial wall - ie archiving and route colors. 

The one thing that I am not sure of is that gyms require that there are feature sub areas for the gym style template to be implemented. In the Wilson Bouldering Wall case this means we will have an artificial area (ie Wilson park) with one feature in it. If we don't force this then there is probably a fair bit of template rework.

**Comment by brendanheywood** [comment]
The logic should be fairly simple: are we in a gym either this node or any ancestor, and does this node have routes as children? If so use the gym template. I don't see why it needs to be any more complex. Teh use of 'feature' was a quick hack to get it working. It should work the same regardless of the node subtype, eg a boulder, feature, area, cliff would all make sense to me in a gym

**Comment by scd** [comment]
The beauty of having two heads on the problem. Thanks :)

**Comment by scd** [comment]
Just tried this and we lose the map, and area descriptions.

**Comment by brendanheywood** [comment]
Maps is easy as I think we simply show it or not show based on wether it has been located when inside a gym.

Node fields is a little more invovled. Reading between the line this feels like the rules for when fields should inherit are probably different for gyms than outside. Eg access would be a street address, but we don't want that At the rope level. I think we can defer figuring all that out and for now simply say that if you are inside a gym then only fields added explicitly at this node show, and not inherited ones.

**Comment by scd** [comment]
I think we are talking cross purposes. To correctly show gym routes in a gym we trigger the gymFeature template. Normally this is triggered fine because all gyms have feature sub areas, not routes directly off the node level. In the case of the artificial wall there is not sub areas. Triggering the gymFeature for routes directly on the artificial wall means we lose the maps and area descriptions because they are not catered for in the gymFeature. This goes back to my original point of needing template rework to properly cater for this use case.

> access would be a street address, but we don't want that At the rope level

If this is the case then our current set up is correct and all we need to do is make sure that the artificial area has a feature sub area. At the moment Wilson Bouldering wall does not have a sub area. For now I think we should just make the rule that gyms and artificial walls should have routes listed in a feature sub area.

**Comment by brendanheywood** [comment]
No we are on the same page, I was just talking about fixing the template to conditionally add the map and fields to the gym feature template. Up to you to go defer or not

**Comment by scd** [comment]
If we cannot decide the business rules then let's defer.

I think we want to force Wilson Bouldering Walll to have a child feature. If you agree then we are done, except for a bit of post release followup. Are you happy with this business rule.

I totally agree with the sentiment that we don't want street address and maps at the route level, which is the basis for making the business rule above.

**Comment by brendanheywood** [comment]
It's small fry, we more important things to spend time on

**Comment by scd** [comment]
I think what we have done is fine for now. I am going to make this a release followup issue to update the data at the particular artificial area.

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76500355-14a57780-6449-11ea-9baa-e6810dd414be.png)

The have done an interesting work-around, listing the dates as separate boulder nodes.
I cannot test since it is LOCKED: Only setters can edit

Otherwise tested: Routes placed in the following structures are archivable:
Area-gym-gym-route 
Area-gym-feature-route 
Area-gym-boulder field-Boulder-route 
Area-Artificial Area-Route

Closing the issue.
