### ISSUE TITLE
Add UI for archiving routes from any gym node which contains routes

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2581]
ie not just 'features' or 'boulders' inside a gym

**Comment by scd** [comment]
see also #2579

**Comment by Mdemaillard** [comment]
Can someone confirm or do we need to test each node type in sandpit ?

**Comment by scd** [comment]
I think archiving us still only in gyms

**Comment by Mdemaillard** [comment]
I have tested this subset to close a separate issue, they do archive.

> Otherwise tested: Routes placed in the following structures are archivable:
> Area-gym-gym-route
> Area-gym-feature-route
> Area-gym-boulder field-Boulder-route
> Area-Artificial Area-Route
