### ISSUE TITLE
It's impossible to search for a string including a space

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2584]
eg if I type 'Vanessa Wills' as a single auto complete tag:

![image](https://cloud.githubusercontent.com/assets/187449/22625511/1b8b21d0-ebed-11e6-9f74-8a86627bee6d.png)

it makes a url stub as I'd expect like: /by/vanessa%20wills/

But this is silently turned into this after submission:

![image](https://cloud.githubusercontent.com/assets/187449/22625513/405bc622-ebed-11e6-8706-dc3e44d7ccd0.png)

And if I resubmit that then I get this stub: /by/vanessa+wills/

Now I don't really care about the url's and I'm happy to go with whatever is easiest here encoding wise, but to me those two searches are distinct, the first should find exact matches including the space, and the second should be a Boolean or, union of both sets

**Comment by Mdemaillard** [comment]
+1 from forum, funnily enough exactly 2 years after the issue opening date
https://www.thecrag.com/discussion/3070065012/syntax-in-search-field

**Comment by lordyavin** [comment]
+1 but I'm not sure if there isn't a duplicate existing.

**Comment by georg-d** [comment]
Like the post cited by [Mdemaillard](https://github.com/Mdemaillard), if I wanted the exact phrase including space, I would expect I need to surround it by quote (") character.

**Comment by lordyavin** [comment]
Strange that this bug fix is still open. Should be a quick fix I think. @scd could you give some insights why this is still open (besides to few man power)? No offense, just interested.

**Comment by scd** [comment]
Simply man power. I find it difficult to find the time to even engage in how hard or important secondary issues are. I am relying on Ulf doing filtering to bring them to my attention if they are really bothering people. I am fine with the super high priority, it is just secondary bugs which are difficult to get done. My guess is that this is about an hours work, but I don't have an hour now and by the time I have an hour there are dozens of priorities. It just gets lost.

If Ulf puts 4 of these issues as a priority to fix then our strategic work goes back a week so it is a juggling act. Eventually we will have enough funds to employ some devs and these bugs will get cleared much quicker.

**Comment by scd** [comment]
I have just fixed this in dev. Should be available next release.

The most difficult part of this fix is that it may break something else which assumes that a space should split into separate items. I could not work out what or why the the space was triggering an item split. Let's see what happens.
