### ISSUE TITLE
Cannot edit registered grade if it wasn't set when a route was created "no registered grade"

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2588]
Make a new route, leave it's grade blank, then go back and try to edit it and you are stuck:

![image](https://cloud.githubusercontent.com/assets/187449/22646382/3cea7050-ecc0-11e6-8c3b-6fd0b66d5fa0.png)

This needs to be the normal round trip editing with the usual text field

**Comment by brendanheywood** [comment]
Run into this a few more times. It happens all the time when I create a boulder project with no grade yet, and then I come back later to add more detail like say a height and it explodes with a bsis error, but it does actually save the extra data I wanted, and it also seems to fix the underlying problem as after that I can edit as much as I want and don't get the error again.

**Comment by brendanheywood** [comment]
+1 from support query https://www.thecrag.com/discussion/1992113646

**Comment by brendanheywood** [comment]
+1 from suppoer https://www.thecrag.com/discussion/1703740170

**Comment by scd** [comment]
working now in dev
