### ISSUE TITLE
static topos for embedding in pdfs are busted

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2589]
eg

https://www.thecrag.com/topo/1031707467/png?targetWidth=368.638850048216;targetHeight=276.4125

Fatal error: @brendanheywood [503] Apache Module Load Portal Error: Error: Not a HASH reference at GeneratePortal.pm line 337.

**Comment by scd** [comment]
Regression issue. Hotfixed

**Comment by brendanheywood** [comment]
Do we need to force rebuild all the pdf's? I've done a few spot tests and I'm pretty sure they are all broken

**Comment by scd** [comment]
Doh. I have now triggered everything before today to rebuild.

**Comment by scd** [comment]
Can we close this issue now?
