### ISSUE TITLE
compare quantization between grade factors

### ISSUE THREAD

**Issue by scd** [theCrag/website#2592]
/climbing/australia/arapiles/climbers/using-stat/all-time-trad-rating/?pageSize=200

Grade Factor 7

![ranking-page-size-200-cmp-grade-factor-7](https://cloud.githubusercontent.com/assets/373058/22811447/fa5d3f9e-ef92-11e6-85aa-0d4638f5ecd9.png)

Grade Faactor 5

![ranking-page-size-200-cmp-grade-factor-5](https://cloud.githubusercontent.com/assets/373058/22811386/a2fc6a54-ef92-11e6-866a-1066a6e6a4b6.png)

**Comment by scd** [comment]
I think there is less quantisation for a lower grade factor. As a thought experiment I would expect that if our grade factor is statistically too high. As soon as our grade factor goes beyond what normally happens it becomes less likely that gaps will be filled by lower grade routes.

Statistically I think we had more support for a grade factor of 5 rather than 7. For various secondary reasons I don't want to go below 4.

Comparing the two graphs above implies to me that we should consider lowering it.

Anyway I think this is a worthy comparison to get to understand quantisation a bit better. It only took two days of processing to get the two different graphs :)

**Comment by brendanheywood** [comment]
Yeah 7 was the original guess so totally fine with changing that.

**Comment by scd** [comment]
Going with 5
