### ISSUE TITLE
Be able to clearly break down an ascents score in facet sorted by rating

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2593]
There has been a few times that I've gone to a ranking, clicked on the ascents for a person, and then seen something weird. It always makes sense when I did into it, but I think we could explain it a bit more. Often it's not the score itself which is pretty well meaningless at the ascent level, it's also's "why is that 22 worth more than that 25?"

What I'm thinking is a hover with something like: "+ 298 points for grade, -50 points for pink point, -10 for decay"

**Comment by scd** [comment]
I have added this to the ascent page. 

![cpr-ascent-cpr-calcs](https://cloud.githubusercontent.com/assets/373058/23114103/12d7e5a0-f791-11e6-9519-7f5e96a0a230.png)

**Comment by brendanheywood** [comment]
I imagine this as a hover over the score (not yet added as a column) in the ascents facet. Can we do that two. This is all about comparing two ascents side by side and wondering why they are not ranked as you expect

**Comment by scd** [comment]
Yup, i think the maths is pretty simple and we store the components that the maths is based on.

tick shift points = stored tick shift on ascent * 10
decay shift points = decay daily rate * (current day index - ascent day index) * 10

**Comment by brendanheywood** [comment]
swet, can you add some template data, soemthing like

```
  "gradeScore": 242,  <-- existing
  "cpr": {
    "raw": 3328,
    "shifted": 3658,
    "decayed": 3638
   }
```

Also I noticed in your ascent page example there is a rounding error. Should these numbers be integers? The decayed one in particular I would expect could easily have a few decimals if we wanted.

**Comment by scd** [comment]
Ok it should look something like this:

```
cpr": {
    "decayed": {
        "systems": [
            {
                "grade": "23",
                "system": "AU"
            }
        ],
        "grade": "23",
        "band": 3,
        "internalGrade": 274.3,
        "rating": 2743
    },
    "base": {
        "systems": [
            {
                "grade": "21",
                "system": "AU"
            }
        ],
        "grade": "21",
        "band": 3,
        "internalGrade": 243.3,
        "rating": 2433
    },
    "shifted": {
        "systems": [
            {
                "grade": "23",
                "system": "AU"
            }
        ],
        "grade": "23",
        "band": 3,
        "internalGrade": 276.3,
        "rating": 2763
    }
},
```

Which is more consistent with what we have been doing elsewhere.

**Comment by brendanheywood** [comment]
From https://github.com/theCrag/website/issues/2582#issuecomment-282452055

So the main takeaway here is that the breakdown could benefit from one extra component which is whether it is even counted or not. This could be tricky so some thoughts:

If I onsighted a route last week, and then came back today and repeated a red point then in my list of ascents ranked by score I would expect to see the tick from last week at the top, and the red point lower underneath it. I would not expect to have the second tick disappear completely or to have a score of zero and be at the bottom of the table.

However if that second tick doesn't count at all, can we, and should we, show this in the breakdown? I'm not completely sure but it seems like we'd need to do a query asking for all the other ticks for this route, and then decay them all, and then say is this particular tick the highest of them all? Dunno about complexity or performance here. Maybe a message like

Your onsight 8 days ago overrides this score

**Comment by scd** [comment]
This is a system performance issue.

I am happy to do this on the ascent page as it is complexity we want to go through anyway, but in the facets I think it is marginal cost benefit.  What we need to do is make sure it is easy to get to the ascent page.

On the ascent page, I plan to show all other ascents you have done on that page.

**Comment by brendanheywood** [comment]
Thinking out loud here, don't we keep a statistic at the node level for every ascent that we roll up?

So don't we keep for node X, both the calculated cpr and the calculation date. This extra component above would be just a single join, or a an extra lookup afterwards. Then combine the stats cpr + decay and compare it to the same numbers for this particular ascent. If they match then it counts, if not then this ascent doesn't count.

Or do we only store this stat at the area node level and above and not for every route?

**Comment by scd** [comment]
Yup, I like your out loud thoughts. 

FYI, the stats have a direct component and a rolled up component. The direct component comes from activity directly associated with that node (in this case route). The rolled up component comes from direct components plus sum of children rolled up nodes. I am pretty sure it is a parallel implementation for account node stats.

**Comment by scd** [comment]
@brendanheywood I have implemented your idea as a `relegated` template parameter.  If the `cpr` variable above has this relegated parameter set then the ascent CPR is not used in the overall account CPR and ranking. Note that this will be firing a lot on dev because the stats have not been recalculated. I have tested it on a couple of routes where I have recalculated the stats and it seems to work.

**Comment by brendanheywood** [comment]
@scd can I pass this one back to you to finish. I'm finding it hard to test on dev without all the stats rebuilt so everything is relegated

![image](https://cloud.githubusercontent.com/assets/187449/23404785/ebdd34c0-fe0a-11e6-85c8-ba5696bda77d.png)

* [x] Add styles for ignored ratings
* [ ] implement tooltip logic (parallel to ascents page)
* [ ] convert all to lang packs

Note I'd prefer not to mention grades with the +20 and -30 bits, just keep it as numbers

**Comment by scd** [comment]
I am happy to leave the lang translation for the ascent page until we redesign it. It has always been a side show for us, but it is looking like it will be quiet an important page in the future. I would like to put some further thoughts on what should be on this page, and get the designer to do a mock up.

For example, if an ascent is a break through ascent (ie first ascent of the grade) we should have a section showing this.

I guess what I am saying is that I am not going to do any more on this issue for this release.

Also it would be cool to see which friends have also done this ascent.

**Comment by brendanheywood** [comment]
Is the tooltip even implemented though? The lang stuff can wait

**Comment by scd** [comment]
Please outline your thoughts with the tooltip in more detail. I am a little reluctant to do more tooltip work as it is anti mobile.

**Comment by brendanheywood** [comment]
This whole page is rather rubbish on mobile at the moment. The tooltip was more or less exactly what you added to the ascent detail page just in a tooltip on this page so it's trivial to compare ticks side by side

**Comment by scd** [comment]
I have updated the tool tip using translation keys.

**Comment by brendanheywood** [comment]
I find the tooltip to be pretty baffling, all the words seems to be attached to the wrong numbers:

![image](https://cloud.githubusercontent.com/assets/187449/24327921/838becc2-1228-11e7-8413-54345137d070.png)

I know the internals and this still took me a while to figure out what all this means. For starters this should be *explaining* the CPR not referring to it. Perhaps this instead:

CPR breakdown
+2933 Base score for grade
+300 for onsight
-19 for time decay

... ok I figured out what is going on, the lang pack items contained " - " which is what we use as the new line delimiter for tooltips so all of these were split very weirdly and so the words were on the wrong lines.

This is how it looks now:

![image](https://cloud.githubusercontent.com/assets/187449/24328058/57b54528-122b-11e7-9316-712873b12a51.png)

**Comment by scd** [comment]
That's better :)
