### ISSUE TITLE
API: add country code to shortcuts endpoint 

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2594]
if a country is a favorite the API (`/api/climber/id/.../shortcuts`) entry contains a isCountry flag. Please also add the country iso2 code.  

**now**

```
{
    "name": "Germany",
    "totalRoutes": "60765",
    "isCountry": 1,
     ... 
}
```

**new**

```
{
    "name": "Germany",
    "totalRoutes": "60765",
    "isCountry": 1,
    "countryCode" : "DE",  
    ... 
}
```

**Comment by scd** [comment]
This is fixed on my dev and sandpit:

https://sandpit.thecrag.com/api/climber/id/9068185/shortcuts
