### ISSUE TITLE
Portrait ratio images in photo detail page are too tall and go off screen

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2595]
Tasks:
* [x] set max width in px
* [x] set max height in px
* [x] ~make both work with responsive srcset~ (moved to #2872)
* [x] make max height also use calc() using viewport maxH
* [x] test it works with webcovers with correct sizing regardless of window size

Hey,

I just wondered at what size photos will be down scaled when uploaded to TheCrag. All vertical images uploaded have a too high resolution, that you have to scroll trough them, at least at a standard full HD screen. 
For example [this photo](https://www.thecrag.com/photo/1119889062) is scaled to 960x1345px, so that I have to scroll trough it. If I upload the image at 571x800px, the image looks a lot worst, due a high compression which is more visible at smaller images.

Wouldn't it make more sense to scale the images to a maximal height of 800-960px and a width of max 1024 px? I think no one likes such large images, that they have to scroll trough them. Typically you want to get a view of the complete image. If you reduce the maximum dimensions, you could also decrease the compression while containing the same disk space usage. And if you take Instagram as an example, it's a lot easier and more fun to view images, even if they are only max 600x600px.

In my opinion, photos are quite important at the climbing community and TheCrag would benefit if this would be improved ;)

Best regards,
Philip

**Comment by brendanheywood** [comment]
Yup totally agree, I'll add a max height to the photo. You should always upload the highest quality photo you have regardless as we resize it on the fly to wherever it needs to fit.

**Comment by brendanheywood** [comment]
Example of bug that I need to re-fix before next release:

https://dev.thecrag.com/photo/1363223955

**Comment by brendanheywood** [comment]
Ok I am really happy with this, the image detail page if now fully responsive by both width, height. It will always try and make the photo just big enough that it fill the screen but you should never have the scroll to see any of the photo.

I'll ship this and then sort the srcset later in #2872
