### ISSUE TITLE
Webhelper for grade ranges

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2596]
@scd is there a webhelper which can give more nuanced grade ranges, and by that I mean:

22-23 would be "22-23"

V3-V5 would be "V3-5"

5.12a - 5.12b would be "5.12a-b"

This has the most bang for buck for YDS and Fr / FB. If such a thing doesn't exist I'll take care of it.

**Comment by scd** [comment]
No but we need one. The parser works in reverse so we can read the convenient format.

**Comment by brendanheywood** [comment]
Ok no worries

**Comment by brendanheywood** [comment]
Note to myself: I actually want a second meta helper which given a grade system can return back a smaller more coarse set of grade intervals. For instance I want to be able to say, give me a set of grades intervals from 5.6 to 5.12 with no more than 10 steps and it will return something like below, which takes into account where each 'denomination' boundary is

```
5.6-.7
5.8-.9
5.10a-b
5.10c-d
5.11a-b
5.11c-d
5.12a-b
```

**Comment by scd** [comment]
One thing we have been toying with is the meaning of a grade range when they are adjacent grades. Does 5.12a - 5.12b mean 5.12a/b or 5.12a-b. The former indicates a grade half way between 5.12a and 5.12b and the later is a classic grade range. I think most of our use of grade range is the former, but we have interpreted the other way around.

Obviously for aggregation purposes in CPR only the range interpretation applies.

**Comment by scd** [comment]
In the CPR time series the grade ranges will not be evenly spaced as the spacing depends on conversions, which may vary from grade to grade in a series.

**Comment by brendanheywood** [comment]
Yup that is expected. This will be more or less the same as the grade slider but vertical. Note also I'd be happy to try adding 2 or more grades here (but probably only 2), the primary grade that this profile is in, and then the next most useful grade depending on some context.

Don't stress too much about this one, I can probably work around it in the first cut if we need to

**Comment by brendanheywood** [comment]
Just cross posting here, I solved this by just skipping grades when they overlap, so not required anymore for this particular chart but I think is still desirable in many other places

**Comment by brendanheywood** [comment]
Pretty sure this is done now
