### ISSUE TITLE
API: structured-tags labels are wrong

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2599]
in the endpoint `api/config/structured-tags` all labels are names or the other way around:

```
{
    "themeName": "Route character",
    "id": 198052699,
    "tagLabel": "Sedimentary",
    "typeLabel": "Rock type",
    "inherits": 1,
    "typeName": "Rock type",
    "categoryLabel": "Sedimentary",
    "tagName": "Sedimentary",
    "themeLabel": "Route character",
    "categoryName": "Sedimentary",
    "appliesTo": {
        "Areas": 1,
        "Routes": 1
    }
} 
```
all labels should be like: "rock-type" and match to the labels substring in the translation files

**Comment by scd** [comment]
This is a total balls up on my db table design, given the way we have chosen to do Translations. It is no longer simple just to change the labels as my code has assumed they do not change. If we changed them then it would be considerable work and the system would break in strange places for a while. I am not so sure we want to go down this path.

I am wondering if we can do another style of fix. My understanding is that we want the translation partial stub.

How do you feel if I add a field typeStub: 'rock-type' instead?

Also my initial definition of a Label and a Name seems to be at odds to how the industry has evolved. I have assumed that the Label is the piece of info which never changes but the Name can change. This is a massive piece of work to change and I don't want to half change it. We have to live with it for now.

**Comment by scd** [comment]
So this is what it will look like 

```
{

    "tagStub": "sedimentary",
    "tagName": "Sedimentary",
    "tagLabel": "Sedimentary",
    "typeName": "Rock type",
    "typeLabel": "Rock type",
    "themeLabel": "Route character",
    "categoryStub": "sedimentary",
    "id": 198052699,
    "themeName": "Route character",
    "categoryName": "Sedimentary",
    "appliesTo": {
        "Routes": 1,
        "Areas": 1
    },
    "themeStup": "route-character",
    "typeStub": "rock-type",
    "categoryLabel": "Sedimentary",
    "inherits": 1
},
```

**Comment by brendanheywood** [comment]
The db internals and what comes out in the api don't need to have any relationship to each other. Can I suggest you start using the attribute 'key' in the api and explicitly make it mean a non changing and non translated strong. It would be nice, but not critical, if the key was always lowercase and didn't contain any spaces or punctuation.

**Comment by scd** [comment]
I am ok with the nomeclature 'key' instead of 'stub'. So it looks like:

```
{
    "appliesTo": {
        "Routes": 1,
        "Areas": 1
    },
    "typeKey": "rock-type",
    "categoryKey": "sedimentary",
    "categoryLabel": "Sedimentary",
    "themeName": "Route character",
    "themeLabel": "Route character",
    "tagName": "Sedimentary",
    "tagKey": "sedimentary",
    "typeName": "Rock type",
    "typeLabel": "Rock type",
    "categoryName": "Sedimentary",
    "tagLabel": "Sedimentary",
    "themeKey": "route-character",
    "inherits": 1,
    "id": 198052699
},
```

I think we should just adopt the following rules for a key:
  [ ] - never changes
  [ ] - can be used in translations and url stubs
  [ ] - lowercase ascii
  [ ] - no spaces, '-' in place of spaces
  [ ] - no punctuation

@nicHoch are you happy with this. If yes I will slowly add this to all api end points. Using the keyword key means that I do not have to change existing parameters so pre-existing things will continue to work.

**Comment by nicHoch** [comment]
Key and the rules are fine for me. 
Could you please bring back to my mind what the current meaning of label and name is?

**Comment by scd** [comment]
label was meant to be similar to key, but had only one restriction - it should not change. This meant it has non ascii, punctuation, spaces and mixed uppercase. Name is something that can change.

Now that we are doing translations the way we are, the only thing the app needs to look at is the 'key'. The other fields are there for backward compatibility.

**Comment by nicHoch** [comment]
Fine - Thanks 

Am 14. Februar 2017 02:15:06 MEZ schrieb Simon Dale <notifications@github.com>:
>label was meant to be similar to key, but had only one restriction - it
>should not change. This meant it has non ascii, punctuation, spaces and
>mixed uppercase. Name is something that can change.
>
>Now that we are doing translations the way we are, the only thing the
>app needs to look at is the 'key'. The other fields are there for
>backward compatibility.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2599#issuecomment-279576660

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by scd** [comment]
@nicHoch can we close this now?

**Comment by nicHoch** [comment]
yes
