### ISSUE TITLE
Bulk import of Frey

### ISSUE THREAD

**Issue by jedparkes** [theCrag/website#2600]
could you point me in the right direction for something
i'm about to go to frey in Argentina
there isn't much on thecrag for that area.
i want to bulk import everything on these pages
http://www.pataclimb.com/climbingareas/frey/torres/tonto.html
then relink the ascents that have been logged to the right climbs (thy're aren't many)
https://www.thecrag.com/climbing/argentina/frey/ascents/?sortby=when,desc

**Comment by scd** [comment]
@jedparkes have you been in contact with the website publishers?

**Comment by jedparkes** [comment]
I'm assuming you mean about copyrite ?
You can't copyrite a route name and grade can you ?

**Comment by scd** [comment]
Our understanding is that you cannot. However copyright laws are different around the world. Both eithically and legally dubious copying somebody else's full database. 

We will put them on the list of publishers to contact - @rouletout

**Comment by jedparkes** [comment]
OK i'll just log the routes that i climb in the thecrag DB manually then... *sigh* god damn copyrite....

**Comment by scd** [comment]
Don't panic, mostly when we contact publishers they are interested in participating, because theCrag is a really good way for them to manage routes for their community. Ulf is out of range at the moment so it will be a while before he contacts them.

**Comment by jedparkes** [comment]
OK I leave in 2 days for the trip and won't be back till 1st April so i'll wait till i get back before looking into logging me ascents

**Comment by Mdemaillard** [comment]
seems more a forum topic than an issue, except if you want to manage some todo of publisher contact via github. Candidate for closure ?
