### ISSUE TITLE
Profile page stats settings general cleanup

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2601]
Noticed on the Profile Filter settings page, but is likely elsewhere as well
This is due to the resizing of the page, but as you can see the checkbox, and the words of different elements can be split and occur on separate lines, these should be treated as one entity if possible

* [ ] Ice climbing" is split between words
* [ ] Aid solo" is split between the checkbox and Aid, which is even more confusing

While we're at it, could we add double spacing to make it easier to distinguish that it's the checkbox before that belongs to the text?

![screenshot 2017-02-15 08 53 33](https://cloud.githubusercontent.com/assets/22091505/22951510/8b95e75e-f35d-11e6-8ef7-bfbbe512cf3c.png)

**Comment by brendanheywood** [comment]
This will open a small can of worms but thats ok we needed to do it anyway:

We are currently redoing all the stats and graphs for the profile page. I suspect that some of those settings may become meaningless. Pretty well every option under the grade system I think we should remove. We should also combine this page with the other profile settings page so it's all consistent. I also think some of these settings should be changeable directly in the profile page but we can sort that bit later.

So I'm going to rename this issue to be a bit more broad and tackle all of these together

**Comment by scd** [comment]
Here is my proposed changes to each of the settings for the profile filter;

1. Profile URL: Move to general profile page

2. Show ascents of style: Remove once we have retired the old performance graph. 99% of our users are covered by sport, trad and boulder. The new graphs will cover the three styles automatically and the other components have enough in them for us not to worry.

3. Show ascents in setting (outdoor/gym). Move to general profile page. The community has very clearly spoken that it is important to distinguish. There will be a regression issue until we work out what to do with the performance graph for gym climbers. Gym routes do not have a cpr - #2607

4. Convert to grade system. Remove - we are doing this via contexts on profile page. Already discussed and agreed.

5. Show ascents of tick type. Remove. We are creating much better default behaviours. I think this makes no sense anymore

6. Plot period. Remove as we have good defaults and setting this at the account level could really screw with how the graphs are presented if they forget to change it.

7. Performance outliers. Remove as this is replaced by CPR logic.

8. Allow repeats. Remove as this is taken into account by CPR logic.

**Comment by scd** [comment]
This is done.

Also uniqueAscentCount and uniqueDistanceClimbed is a permanent stat in a tooltip.
