### ISSUE TITLE
Tune WebP and jpeg quality settings

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2606]
We've had a bunch of people complain about low quality topos / photos. Essentially the default level of compression in thumbor is probably a bit too low for most peoples liking. this should be easy to fix

https://www.thecrag.com/1049626104/topo

eg this photo:

https://static.thecrag.com/img/x640/d7/b3/d7b36cc5722a30a92fea697eb46dd94b0481c935

![image](https://cloud.githubusercontent.com/assets/187449/23110862/87327c26-f778-11e6-9433-04d7e6e5350f.png)

has grainy artifacts around the flowers on the top of the cliff. There is a gotcha however in that it depends on what browser you are in. thumbor serves a webp to chrome, which is a fixed quality set in the server somewhere. The jpeg on the other hand also has a default quality level set at the server side, but this can also be overridden in the url like this, try these in firefox:

https://static.thecrag.com/img/x640/filters:quality(100)/d7/b3/d7b36cc5722a30a92fea697eb46dd94b0481c935

https://static.thecrag.com/img/x640/filters:quality(1)/d7/b3/d7b36cc5722a30a92fea697eb46dd94b0481c935

For jpeg at least I think a quality level of around 90 seems like the best balance between file size and quality:

https://static.thecrag.com/img/x640/filters:quality(90)/d7/b3/d7b36cc5722a30a92fea697eb46dd94b0481c935

* [ ] tune and set webp quality level to ??
* [x] set default jpeg quality level to 90

**Comment by scd** [comment]
I have added the quality filter to the thumbor url. Note that the combined filter format is `filters:rotate(270):quality(90)/` which has been tested.

**Comment by brendanheywood** [comment]
Can we fix it in config instead on in the URL? The URL method doesn't seem to work for webp either way

**Comment by scd** [comment]
So here is our in internal thumbor settings for webp

```
## Quality index used for generated WebP images. If not set (None) the same level
## of JPEG quality will be used.
## Defaults to: None
#WEBP_QUALITY = None

## Specifies whether WebP format should be used automatically if the request
## accepts it (via Accept header)
## Defaults to: False
AUTO_WEBP = True
```

Not sure what to fix yet?

**Comment by scd** [comment]
Also this...

```
Usage: format(image-format)
Description

This filter specifies the output format of the image. The output must be one of: "webp", "jpeg", "gif" or "png".

...

http://thumbor-server/filters:format(webp)/some/image.jpg

```

**Comment by Drazhar** [comment]
Hey, nice to see that this topic gets some work :)

Just as a small hint. I'm not familiar with WebP, but in Photoshop, a quality setting at 70 is mostly suggested for the best compromise between size and quality. Typically I use 75 if the size matters and I really don't see a difference to quality 100. But I'm not sure if the algorithm in Photoshop for the compression is the same or at least comparable to the one used here.

In general I'm happier with a higher quality setting :)

But one question for topo images. If you use the zoom button, the image doesn't get recreated from the highest resolution image, it just will zoom the displayed image? If this is correct, could this be changed?

Best regards
Philip

**Comment by scd** [comment]
I think I need to change this line in the server:

```
## Quality index used for generated JPEG images
## Defaults to: 80
#QUALITY = 80

```

**Comment by brendanheywood** [comment]
@scd as an experiment can you try and get a very low quality webp image in chrome. For instance in firefox this url looks like:

https://static.thecrag.com/img/x640/filters:quality(1)/d7/b3/d7b36cc5722a30a92fea697eb46dd94b0481c935

![image](https://cloud.githubusercontent.com/assets/187449/23114931/f514ff44-f795-11e6-91de-c28cd4bd8386.png)

In chrome it looks normal so the quality filter is clearly not taking affect there.

@Drazhar yeah I don't know how the quality setting in PS correlates to thumbor, 90 is what I came up from my testing. There is a chance that this whole issue is only the quality of webp images and the setting of 80 is fine for jpeg's

Also there is actually a second high res zoom photo but it may not be working that well due to this issue, but there are things to tune there as well

**Comment by scd** [comment]
I have made jpeg default to quality of 90, but this does not effect the webp quality. I tried setting webp quality to 1 but it stops serving images all together. Need to do more testing, in particular try and find out why webp quality of 1 does not work.

**Comment by scd** [comment]
My eyes are not good enough to tell the difference between jpeg 80 and 90. @brendanheywood can you please have a look at your first example and tell me if it is as you would expect for firefox, and just in case you can tell on chrome. Theoretically webp should inherit jpeg setting.

**Comment by brendanheywood** [comment]
80 vs 90 is discernible if you are looking for it, but ultimately I don't think is that important, nor is it related at all to what @rouletout was seeing. I think we should change it back to 80

> Theoretically webp should inherit jpeg setting.

Yes but it's obviously not. This is either a bug in thumbor, or possibly a bug in which pil. I've logged this https://github.com/thumbor/thumbor/issues/861

**Comment by scd** [comment]
Do you want to change it back to 80 because it only half works?

I just want to confirm that after all this fine tuning we want to leave it at the default level.

**Comment by brendanheywood** [comment]
> Do you want to change it back to 80 because it only half works?

It's not causing the issue we are debugging at all. The ability to tune webp would be nice, but even it is not the root cause, it looks like there is something going on before the file even gets to thumbor.

**Comment by brendanheywood** [comment]
I'm closing this, the image quality is a complete red herring, this is all about the image dimensions, ie this issue https://github.com/theCrag/website/issues/1911
