### ISSUE TITLE
Sort climbers facet by joined date, and filter between joined date

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2610]
Eg I'd like to see sorting by 'joined' ie the date they became a member and also filtering by this date - this would help heaps with finding edge cases to testing the rankings and graph for very recently joined people.

Again like #2609 is tiny but will help heaps for testing so flagged as must do for release

eg filtering:

* [x] https://www.thecrag.com/climbing/world/climbers/joined-between/2010+2015

sorting:

* [ ] https://www.thecrag.com/climbing/world/climbers/?sortby=joined,desc

**Comment by scd** [comment]
I have just done the filter which was 10 minutes work. I have also implemented joined-before and joined-after.

I think there is an issue for people who joined before 2004, which I have not investigated yet.

The sort by in the climbers facet is a structural issue, which I will comment on #2609. Effectively this means it is a lot of work.

I have also implemented this in the ascents facet, in particular in case the sortby joined helps identify test accounts as a surrogate to not getting this sort by in the climbers facet.

In repo.

**Comment by brendanheywood** [comment]
Going to reopen this until the UI is done as well

**Comment by scd** [comment]
I took the must be must be resolved tag as we can release without the ui component done.

**Comment by brendanheywood** [comment]
done

![image](https://cloud.githubusercontent.com/assets/187449/23403577/cbf39c86-fe04-11e6-8426-12df206123e2.png)
