### ISSUE TITLE
Regression bug with markdown data for profile intro

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2611]
the html code is getting shown:

![image](https://cloud.githubusercontent.com/assets/187449/23328978/51421ed8-fb82-11e6-9c2c-2798ff57e5c8.png)

It's bad in the template data:

Prod:

![image](https://cloud.githubusercontent.com/assets/187449/23328973/3ee91f84-fb82-11e6-9bea-8f0cbd067b19.png)

dev:
![image](https://cloud.githubusercontent.com/assets/187449/23328976/477335cc-fb82-11e6-8eb9-06d959c48a20.png)

**Comment by scd** [comment]
Fixed. In some other work I had found a logic gap with html escaping for mentions within a text. Somehow I got it a little wrong. The issue I was trying to resolve was to make sure a persons name is html escaped, just in case. I had also accidently html escaped the main text as well.
