### ISSUE TITLE
Make the account climber profile page responsive

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2612]
https://docs.google.com/document/d/1H16lSHemjK5KF9yw_h9ku6iOLe5XYW5AhvvsovrADpY/edit

https://trello.com/c/VUnWrnEZ/75-decide-on-broad-directions-for-profile-page

**Comment by scd** [comment]
I have made the profile page responsive but like the other responsive pages there is probably a bit of tuning to do.

 - [ ] Can we dump the recent activity right hand column. Even though it is mostly in the streams, I think that we would get complaints if we dump this. If we did dump it then the fine tuning for responsive design will be a lot easier.

 - [ ] We need to pass different widths to the graphs. For the life of me, I cannot think of how to do this unless in javascript land, or returning multiple svg graphs for selection using css. If we are going down the javascript path then I think we should not use iframes, but rather the direct svg embed. Thoughts?

**Comment by brendanheywood** [comment]
Yeah I was saving this for after the redesign because the layout I had in mind will be quite different. There is a lot of moving parts across the whole page and I wanted to do it all in one hit. This included moving some of the charts into the right column and drastically shrinking all the redundant crap in the middle so the stream was on the 2nd page scroll down instead of the 5th or 6th.

The charts I want to make responsive embeds, ie the aspect ratio of the embed stays the same and the charts scales up and down in the exact same way as an image. The information density / internal pixel width of the svg will have to be fixed, so we'll tune it for the desktop size. Smaller screens generally have higher pixel densities so this is ok.

So dunno, up to you if you want to continue or park this one for the next release. I'd prefer to focus only on the critical stuff and this isn't critical.

**Comment by scd** [comment]
I don't think I want complete this now, but may re address if other
critical issues effect this.

**Comment by brendanheywood** [comment]
Ok, so reverted / rolled back?

**Comment by scd** [comment]
Not yet. Will do before release. Just needs two lines commented out when calling the header template

**Comment by scd** [comment]
I am intentionally not reverting in so I can see what the profile page looks like after resolving some other issues.

**Comment by brendanheywood** [comment]
Cross linking, this is all a subset of #1686

**Comment by brendanheywood** [comment]
Done!
