### ISSUE TITLE
Experiment and resolve issues with cpr curves at crags / regions without account filter

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2616]
This stuff is all low priority and just logged for later, but might be worth a quick look as some of these edge cases might also apply to the more normal graphs.

I can't believe we've left it this long to experiment, but a crag level chart works fairly well, except:

* [x] there is a bug with the grade system choosing YDS instead of AU 

https://dev.thecrag.com/climbing/australia/gara-gorge/ascents/aggregate/graph-trad-cpr/with-route-gear-style/trad/

![image](https://cloud.githubusercontent.com/assets/187449/23338645/8fd928c0-fc64-11e6-9995-1b2a5df89118.png)

I still have have no idea how idea whether this makes much sense but it is cool. The cpr lines look good in this particular chart, but you can already see in places the cpr curve being way above the candles due to volume effects. I think in a higher volume crag the cpr curves would be floating so high above they would be completely meaningless.

* [x] if no account is selected then figure out if we can tune cpr different to make sense, or whether we just remove it completely, or replace it with a different algorithm that makes sense here.

I thought I'd try some bigger data sets just to see how performance is and whether we need to protect against these in some way. This one took a minute or so and has some really weird date thing going on

* [ ] mitigate performances issues somehow, maybe just do a quick stat lookup of the number of ascents without any filters applied, and if it's more than say 10k ascents then show a 'too much data' warning
* [x] fix weird date range issues. The left side of this scale is in the year 1021!

https://dev.thecrag.com/climbing/australia/new-south-wales-and-act/ascents/aggregate/graph-trad-cpr/with-route-gear-style/trad/

![image](https://cloud.githubusercontent.com/assets/187449/23338652/bf43168e-fc64-11e6-89ed-e68fcb54b705.png)

82 seconds in dev:

![image](https://cloud.githubusercontent.com/assets/187449/23338742/21234160-fc67-11e6-9d96-349bf9a75605.png)

Clearly something whack with the timescale too but probably not worth chasing once the overall scale bug has been fixed

**Comment by scd** [comment]
>  I think in a higher volume crag the cpr curves would be floating so high above they would be completely meaningless

Don't forget repeat ascents do not add to the cpr. When producing the curve data I don't check the account, so it is any repeat ascent. I suspect this is a bug rather than a feature, because there are strange artifacts with onsights.

I you are doing a cpr for a crag then you are looking at changes over time, in particular are people climbing harder there. In this case the cpr is not meaningless as we are looking at relative change over time.


> Clearly something whack with the timescale too but probably not worth chasing once the overall scale bug has been fixed

It is possible that there are strange artifacts for dates before 1970. Any date before outside the epoch range is certainly incompatible with the algorithm.

**Comment by scd** [comment]
And now for something completely cool :)

NSW
/climbing/australia/new-south-wales-and-act/ascents/aggregate/graph-trad-cpr/with-route-gear-style/trad/

![cpr-nsw](https://cloud.githubusercontent.com/assets/373058/23345818/e14268ce-fce7-11e6-9984-956673d74df5.png)

QLD
/climbing/australia/queensland/ascents/aggregate/graph-trad-cpr/with-route-gear-style/trad/

![cpr-qld](https://cloud.githubusercontent.com/assets/373058/23345829/f8f7badc-fce7-11e6-994e-b4bf4b5c1022.png)


VIC
/climbing/australia/victoria/ascents/aggregate/graph-trad-cpr/with-route-gear-style/trad/

![cpr-vic](https://cloud.githubusercontent.com/assets/373058/23345831/08692622-fce8-11e6-8a5c-760ed67ee0ae.png)

CPR being over candles just is not a problem. For it to be one grade above candles there would have to be about 10 ascents of the hardest grade at the area in the same time period.

**Comment by scd** [comment]
Australia 25 seconds on my laptop

https://dev.thecrag.com/climbing/australia/ascents/aggregate/graph-trad-cpr/with-route-gear-style/trad/

![cpr-aus](https://cloud.githubusercontent.com/assets/373058/23345983/093e896e-fcea-11e6-9733-d5eba5ca4e38.png)



World 40 seconds on my laptop

https://dev.thecrag.com/climbing/world/ascents/aggregate/graph-trad-cpr/with-route-gear-style/trad/

![cpr-world](https://cloud.githubusercontent.com/assets/373058/23345987/0f908d44-fcea-11e6-8b2b-22d1e393e1e0.png)

Besides some clear bad data this is also a great audit of the grade shifts, which seem really good to me :)

**Comment by scd** [comment]
> mitigate performances issues somehow, maybe just do a quick stat lookup of the number of ascents without any filters applied, and if it's more than say 10k ascents then show a 'too much data' warning

Let's just make this premium feature. If it starts to screw us up then we can do the query on a different server. For example sandpit is near real time, which would be fine for any cpr timelines

**Comment by scd** [comment]
Closing this because the only remaining task is how to add to a facet and whether or not to make it premium. Both of these are covered in issue #2614
