### ISSUE TITLE
CPR timeline graph emedding types

### ISSUE THREAD

**Issue by scd** [theCrag/website#2617]
I am in the process of updating CPR timeline to align with our standard embedding. So

https://dev.thecrag.com/ascents/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/vwills/

Will return the graph in a normal theCrag page, ie with headers, etc.

https://dev.thecrag.com/ascents/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/vwills/?embed=chunk

will return html chunk without html and body elements. This can be used for embeding html directly using javascript. This is what is done in the streams.

https://dev.thecrag.com/ascents/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/vwills/?embed=html

will return html with html and body elements. Suitable for iframes.

https://dev.thecrag.com/ascents/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/vwills/?embed=svg

Will return `image/svg+xml` mime type.

**Comment by scd** [comment]
I get an xml error when serving svg.

![cpr-mime-svg-error](https://cloud.githubusercontent.com/assets/373058/23349790/dec7130c-fd09-11e6-9393-01f25d5194e0.png)

@brendanheywood do you want me to look into this or is something you want to fix?

**Comment by brendanheywood** [comment]
should just be a namespace missing somewhere, please followup, it should be an easy fix like

 ```<xlink:a ...```

**Comment by brendanheywood** [comment]
also the template will need to know it is being served as svg vs html so it can render or not render some css at the top to remove the default html padding

**Comment by scd** [comment]
FYI I have added the embed code in the ascents-timeline template so it should be clear where to add things when we need to.

**Comment by scd** [comment]
xlink was an easy fix. Missing from the svg params
```
xmlns:xlink="http://www.w3.org/1999/xlink"
``

**Comment by scd** [comment]
My intention for the `aggregate` template was to be a little bit more generic, so I have made a couple of minor changes. We get multiple graphs for free:

https://dev.thecrag.com/ascents/aggregate/graph-sport-cpr+graph-trad-cpr/by/vwills/

I know we are still discussing this, but it is there for free if we decide to use it. If we do decide to use it there are some issues we need to work through with headings and whitespace. Also the base facet will include a wide range of tick types, which may not be what we want.
