### ISSUE TITLE
503 error in topos facet

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2618]
Doing a search for "Topos" using as filters "with:" and both "Route links" and "Multiple routes" gives a 503 error.

**Comment by brendanheywood** [comment]
Reproduced:

https://www.thecrag.com/climbing/world/topos/has/route-links+mult-routes/?sortby=at,asc

**Comment by scd** [comment]
Fixed so no longer crashes. Although I don't know why one would choose these two filters together because one is a superset of the other.
