### ISSUE TITLE
Convert the grade slider on the ranking page into an aggregate graph

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2620]
![image](https://cloud.githubusercontent.com/assets/187449/23405150/10e21d6a-fe0d-11e6-9db8-0abdb5f851f2.png)

This is seems like the natural way we would have done it if we'd sorted the aggregate stuff first. Note I would not embed this in the ascents page, that's wasteful it already has all the data it needs. This would just be a some template wrangling to make a url like this work and call the same minor template with the same data:

https://dev.thecrag.com/climbers/aggregate/graph-grade-ranking/using-stat/sport-rating/

The main driver here is embedding a live one into the CPR help article #2503. This isn't critical as we can just take a screen shot. Alternatively we can just push that data into the CPR template and render it inline. Happy either way

**Comment by Mdemaillard** [comment]
Looks implemented as embedding 3 lives. Awesome !
![image](https://user-images.githubusercontent.com/60388146/76700490-d0bca780-66c0-11ea-9fc3-fc3abe9cde5e.png)
