### ISSUE TITLE
Bug with lower grades overlapping volume in cpr graph

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2621]
@scd in one of your examples there is a bug:

https://dev.thecrag.com/climbing/world/ascents/aggregate/graph-trad-cpr/with-route-gear-style/trad/

![cpr-world](https://cloud.githubusercontent.com/assets/373058/23345987/0f908d44-fcea-11e6-8b2b-22d1e393e1e0.png)

The YDS grade range start at 5, but the internal grade range goes below that. There are a couple ways we can solve this but probably the best is to send through in the template data an explicit range of internal grades and I will use that for scaling instead of the internal low grade of the lowest grade (and the high of the top grade)

Note that also have this issue in the grade slider. Do you think we should have an ugly which gap, or should we just fill it with green at the low end and purple at the high end where the grades run out?

**Comment by scd** [comment]
> The YDS grade range start at 5, but the internal grade range goes below that

I think this is a conversions issue. 5.0 does not start at the bottom.

> Note that also have this issue in the grade slider. Do you think we should have an ugly which gap, or should we just fill it with green at the low end and purple at the high end where the grades run out?

Eventually.

**Comment by brendanheywood** [comment]
Just so we are clear, I don't see this as a bug with the grade systems. If YDS starts at internal grade 80 or whatever I don't care.

What I care is that the graph looks good despite this.

The fix is for the template data to include 2 extra params stating the explicit upper and lower limit of the grade data in the graph, rather than me assuming that the lower limit is the lowest grade in the y axis and the upper limit is the upper grade in y axis.

Then I can scale the whole graph and the yaxis correctly. If the grade system doesn't go all the way to the bottom I can optionally fake this by just filling in the bottom part with an empty green box with no grade it in.

**Comment by scd** [comment]
is this ok

```
flashCpr": {

    "ascentCount": 1,
    "rating": 1535,
    "grade": "V0",
    "band": 2,
    "power": 35795101.3391875,
    "decayOffset": 12873,
    "systems": [
        {
            "system": "BLDV",
            "grade": "V0",
            "low": 134,
            "high": 167
        }
    ],
    "directCount": 1,
    "startDecayOffset": "12799",
    "internalGrade": 153.5,
    "maxAscentGrade": 167,
    "minAscentGrade": "134"

},
"period": "quarter",
```

**Comment by brendanheywood** [comment]
I'm confused about what you've added here, what has this got to do with flashCpr? I was expecting a min and max internal grade right back at the root of the graph json data

**Comment by scd** [comment]
Whoops I put it on the wrong variable. I will update over the weekend

**Comment by brendanheywood** [comment]
So to flesh this out, lets lower grade in the V series was VB+ (and not VB-), then in the data the lowest grade would have a low grade of 68, but the graph itself might have a low grade of say 50 instead. I'd want this new min . max to be directly under 'graph-boulder-cpr'

![image](https://cloud.githubusercontent.com/assets/187449/23776174/ae4c657c-0580-11e7-89e3-25f06ed1d9d8.png)

**Comment by brendanheywood** [comment]
I've just found a minimal test case for this, ie someone who has ticked a < 4 AU grade, but whose graph is shown in YDS grades which don't go that low:

https://dev.thecrag.com/ascents/aggregate/graph-trad-cpr/with-route-gear-style/trad/by/arvinnought/?embed=html

![image](https://cloud.githubusercontent.com/assets/187449/23776316/b57901ec-0581-11e7-8bde-2be33e7b0104.png)

So in this case I would expect the graph minimum grade to be roughly the lower grade of AU:3 and then minus the 'breathing room' delta, and then cropped to 0 if it has gone under. Same logic for top end of the scale. In this particular case the end result will be an internal grade of zero and the resulting graph should look like:

![image](https://cloud.githubusercontent.com/assets/187449/23776463/9e483bfe-0582-11e7-86eb-31b714f2c61b.png)

**Comment by scd** [comment]
Try again :)

```
"aggregate": {
    "graph-sport-cpr": {
       highInternalGrade": 213,
       lowInternalGrade": "121",
```

**Comment by brendanheywood** [comment]
ok so this is now using those numbers, but those numbers aren't quite right and force the grade yaxis to overlap the bottom:

![image](https://cloud.githubusercontent.com/assets/187449/23946042/ef7e2a44-09cc-11e7-9668-7e22d7364bd3.png)
https://dev.thecrag.com/ascents/aggregate/graph-boulder-cpr/with-route-gear-style/boulder/by/aikibujin/json

The lowInternalGrade for the graph must always be lower or equal to the lowInternalGrade of the lowest grade in the yaxis2:

![image](https://cloud.githubusercontent.com/assets/187449/23946075/16772394-09cd-11e7-8275-045fbb9795e5.png)

**Comment by brendanheywood** [comment]
@scd no chance to look at this one?

**Comment by scd** [comment]
Whoops, I forgot this was back in my ball park. I have fixed on repo

**Comment by brendanheywood** [comment]
perfect
