### ISSUE TITLE
Error displaying emojis

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2624]
Hey,

This error is there quite a while and not only on my devices, it's also on the iPad of my wife. 

Some emojis like the scream and sweat sometimes aren't displayed, instead the URL of the svg is shown. I will append a screenshot from my phone to show the error.

Best regards
Philip

**Comment by Drazhar** [comment]
![screenshot_20170301-072052](https://cloud.githubusercontent.com/assets/3040689/23448274/3c7f01de-fe50-11e6-9a91-28c0b6d55bb7.png)

**Comment by brendanheywood** [comment]
Reproduced here:

https://www.thecrag.com/event/1128979989

**Comment by brendanheywood** [comment]
@scd is this probably related to the recent escaping change you made that also cropped up on dev?

**Comment by Drazhar** [comment]
Not sure how recent this change was, but if I'm correct, we had this error also a year ago, but it feels like this happens more frequently now.

**Comment by scd** [comment]
not related at all to the other bug. smile works but sweat does not. Here is the html with sweat

```
<img class="emoji" title=":<em class="strenuous">sweat</em>:" src="//twemoji.maxcdn.com/svg/1f613.svg" />
```

We are double dipping our markup.

**Comment by scd** [comment]
The quick fix is to not markup `:sweat` with our keywords. Still markup `sweat`.

**Comment by scd** [comment]
fixed in simons dev
