### ISSUE TITLE
Data: Serbia FA vs. RS information

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2626]
From the xls import the Route Setter was imported to FA - here the message from the web-site owner:

Ulf, i finally found time to check serbia on your website. Everything looks ok for now except that we made a mistake in importing data. Those who are in FA in your database are route setters in our. We dont have FA database yet.

**Comment by scd** [comment]
There are about 500 routes which need updating:

https://www.thecrag.com/climbing/serbia/routes

**Comment by brendanheywood** [comment]
Worst case if we have to fix this manually it would be better if we could swap FA / FFA easily which is here:

https://github.com/theCrag/website/issues/443

**Comment by Mdemaillard** [comment]
There are 468 routes with history, it seems that has not been corrected.
I can tackle that, especially now that the FS to Set is a drop down away in bulk edit.
Any contact person from there to confirm it needs to be done ?

**Comment by Mdemaillard** [comment]
Done. I could see a few crags had been updated with set and FA, left untouched. All others switched.
