### ISSUE TITLE
In gyms show heirarchy for updates at well as for ticks

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2627]
eg a while back I did this:

![image](https://cloud.githubusercontent.com/assets/187449/23495519/48b6e0d4-ff6d-11e6-8b41-19ddd66f9440.png)

Just need to replicate that in the update stream events:

![image](https://cloud.githubusercontent.com/assets/187449/23495535/576e11c4-ff6d-11e6-8428-f313fbdd0650.png)

**Comment by scd** [comment]
This looks to be done. Eg look at stream in a particular gym:

https://www.thecrag.com/en/climbing/austria/lechtaler-alpen/imst
