### ISSUE TITLE
Bug with x time scale, waay too many slices

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2631]
https://dev.thecrag.com/ascents/aggregate/graph-boulder-cpr/with-route-gear-style/boulder/by/aikibujin/?embed=html

![image](https://cloud.githubusercontent.com/assets/187449/23537604/48cfccf2-0021-11e7-958a-d7d7c002a546.png)

**Comment by scd** [comment]
I know what that is. The system is making a decision about how many time slices based on the first and last ascent date. It should be making a decision based on first ascent date and now.

OR

In this particular graph, maybe we do not want to show all the way out to now. In otherwords if somebody stopped being active years ago, then there is no need to have a tailing off graph. 

Let's say we are still around in 20 years time and Lee has stopped climbing for 15 years. We would not want to show the graph decaying for 15 years.

**Comment by brendanheywood** [comment]
I think both have value and we should do both. Ultimately the immediate bug is that the time scale is not related to the period being graph which we should fix now.

Later we can add a new feature to choose a better time period to plot, perhaps showing a bit of buffer afterwards showing a little bit of decay. Maybe a 2 year buffer. I'm happy to leave this and see how it looks in prod with lots of data and make a call when we get to it. Split into #2633

**Comment by scd** [comment]
fixed in repo
