### ISSUE TITLE
bouldering mostly using plain tick but we are not showing this in it's own timeline

### ISSUE THREAD

**Issue by scd** [theCrag/website#2637]
Plain bouldering tick does not have it's own cpr curve so bouldering looks a bit funny where this is the main type of tick.

https://dev.thecrag.com/climber/tommykrauss

![cpr-bouldering](https://cloud.githubusercontent.com/assets/373058/23644120/adb22486-0359-11e7-9461-29d6b4c3e36a.png)

**Comment by brendanheywood** [comment]
I think this will become a lot clearer once we introduce the new tick types for bouldering. In the mean time pink point is meaningless and should be removed, and red point could be renamed to 'sendcpr' and it could safely include ticks.

**Comment by scd** [comment]
This is fixed in accordance with @brendanheywood recommendation
