### ISSUE TITLE
Log multiple ascents at routes overview page of an area

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#2643]
Hey,

I couldn't find an issue regarding this topic. Hopefully there isn't already one. Also this hasn't a high priority.

There are some areas, especially spots for bouldering or indoor climbing, which contains a lot of sub areas for each boulder or each feature of a gym. In this cases, logging ascents after a climbing day is sometimes kinda time consuming, because you can't simply select multiple routes across the areas and log all at once. 

So there could be two solutions which come to my mind:
1. The really cool one: Save the selection which was made at one area, so the user is able to browse trough multiple areas and when finished log all selected ascents. But I think this could be kinda hard to archive and brings some other issues, like accidental selections which will be "saved".

2. Allow selecting multiple routes at the routes overview of an area like for example at [Magic Wood](https://www.thecrag.com/climbing/switzerland/alpen/graubunden/magic-wood-averstal/area/461042262/routes).  The downside would be, that the user misses a lot of information this way. For example many boulder problems don't have very meaningful names and can only be distinguished by there location or with the help of a topo. But if you know what you are doing, it would be far more comfortable this way.

What should also be mentioned is the option to tick all routes a friend has ticked in a stream event. Most of the times when I'm out with Moxi, we are doing the same stuff, so only one would have to tick all the routes at the different areas and the other one could simply tick the same. Right now this is only possible for the individual routes.

Hopefully it is clear what I mean by this :)

Best regards,
Philip

**Comment by scd** [comment]
Probably the second way is doable and just needs a UI tweak. It is likely that we will re-address the multiple ascent logging in the future with some design changes.

How important is it to be able to log multiple ascents in one go?

What about inline ticking? (tick on the same page, or with a popup)

**Comment by brendanheywood** [comment]
The second way is something we are already planning, so I'm gonna close this as a duplicate, see

https://github.com/theCrag/website/issues/2352
