### ISSUE TITLE
reparent node action - page "title"

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2649]
When reparenting a route this is the text at the top left corner:

_ReparentNodePromptSpecifyNewNode_

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76504724-f04d9900-6450-11ea-8cda-a93ffbc6c404.png)

**Comment by scd** [comment]
@Mdemaillard this should be done, can you please check and close
