### ISSUE TITLE
Translation: Ranking Page 

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2652]
Title is not translated fully / correctly, "die Welt" should probably be a different variable as it is "Welt" only. "Deine sport rating" is also not translated (next to Deine Platzierung)

<img width="436" alt="screen shot 2017-03-15 at 16 12 17" src="https://cloud.githubusercontent.com/assets/19162952/23974753/32bc5246-099a-11e7-9afe-53c66fa3b71a.png">

<img width="630" alt="screen shot 2017-03-15 at 15 43 53" src="https://cloud.githubusercontent.com/assets/19162952/23974720/fc82002c-0999-11e7-8164-f2555534519c.png">

**Comment by scd** [comment]
@rouletout the sport rating is in the `system.statistic.climber-leaderboard.sport-rating` key. Actually do a search for `system.statistic.climber-leaderboard` as there will be a number of keys you need to translate.

I have added a new key for the 'in die Welt' component - `template.facet.title-component.in.the-world`. This is on snapshot.

This brings me to a feature we need for translators. It is very difficult for translators to know what keys they need to translate for a particular page. I am thinking each template needs some sort of report on the keys which are used. To that end I have implemented a new parameter 'langreport' for templates:

https://dev.thecrag.com/climbing/world/climbers/using-stat/sport-rating/?lang=de&langreport=1

This tells the system to add a translators report to the end of the file output, which looks something like this:

```
e,system.month.jul.short (1,0) => "Jul"
de,system.month.nov.short (1,0) => "Nov"
de,system.month.oct.short (1,0) => "Okt"
de,system.month.sep.short (3,0) => "Sep"
de,system.note (1,0) => "Notiz"
de,system.statistic.climber-leaderboard.all-time-boulder-rating (1,1) => missing
de,system.statistic.climber-leaderboard.all-time-sport-rating (1,1) => missing
de,system.statistic.climber-leaderboard.all-time-trad-rating (1,1) => missing
de,system.statistic.climber-leaderboard.ascents (1,0) => "Begehungen"
de,system.statistic.climber-leaderboard.boulder-rating (2,2) => missing
de,system.statistic.climber-leaderboard.distinctascents (1,0) => "Begehungen (ohne Wh.)"
de,system.statistic.climber-leaderboard.heightclimbed (1,0) => "Klettermeter"
de,system.statistic.climber-leaderboard.karma (1,0) => "Karma"
```

A quick page search for the word `missing` shows you what is still to be translated for this page.

This report does not work for the whole system, just templates at the moment.

Note that this functionality is just on my dev. Let's keep this issue open until you  see the report in action. Can I leave this up to you to document and inform the translators?

**Comment by rouletout** [comment]
Hi Simon,

translated the keys, couldn’t find “the-world” though…

Ulf


> On 20 Mar 2017, at 17:13, Simon Dale <notifications@github.com> wrote:
> 
> template.facet.title-component.in.the-world


——————————————————
Ulf Fuchslueger
Head Business Development @ theCrag
ulf@thecrag.com <mailto:ulf@thecrag.com>
www.thecrag.com <http://www.thecrag.com/>

https://www.thecrag.com/climber/rouletout <https://www.thecrag.com/climber/rouletout>

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Linkedin <https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>
——————————————————

**Comment by Mdemaillard** [comment]
@scd Candidate for closure ?

**Comment by rouletout** [comment]
yes
