### ISSUE TITLE
email verification of accounts

### ISSUE THREAD

**Issue by scd** [theCrag/website#2656]
I am rethinking the value of email verification. 

I have just worked on another project where it has become crystal clear the importance of email sender reputation, which goes far deeper then setting up the technical verifications properly.

Firstly email verification ensures that users get the email out of their spam box and the fact that users click on a link in an email can be used to improve our send reputation. 

I have just seen first hand the effect of changing email providers on another system where emails just went into the spam box.  There is a magic art to warming an IP address when changing providers, and I think it was the cause of emails getting into peoples spam box for our CRM stuff. 

With the other project, when somebody takes an email out of their spam folder, then subsequent emails go into their inbox with google. We are trying to assess if enough people do this, does it google then reassess the new IP address as a good address.

The upshot of all this is that regular and relevant emails is very important for our sender reputation. Opening emails and clicking on links helps our reputation. Email verification seems to me to be critical in this overall process.

**Comment by brendanheywood** [comment]
> I am rethinking the value of email verification.

This scared me as it wasn't clear if you meant it was pointless or it if was becoming more important. 

Yes absolutely email verification is critical, and there is a lot of moving parts here not just with the verification but also things like the forum subscription model and the headers etc

**Comment by scd** [comment]
Yes I mean it is critical. I use to think it was relatively unimportant, which is probably why we do not have this process implemented.

I am raising this as specific issue because it has a very long lead time. Our sender reputation takes months to establish. Whereas some of the other equally important stuff, will filter through immediately when we fix it.

For this reason I want to get the email verification component started asap.

**Comment by scd** [comment]
Here is the task list:
  - [ ] Add datafields to account for email verification token and email verified date
  - [ ] Add ui and api process for triggering verification email to be sent
  - [ ] Add Activity Item for karma for verifying email
  - [ ] Add verify template page assigned to end point /verify-email/token 
  - [ ] If logged in with matching account then the template page automatically verifies you
  - [ ] If not logged in then it asks if it is you (ie protect against bots following links in emails)
  - [ ] Our standard notification process on dashboard to catch people who created account a while ago
  - [ ] Add email verification to create account process

**Comment by scd** [comment]
Because of cross domain stuff I could not test the not logged in verification process. Test this after released.

**Comment by brendanheywood** [comment]
We can do this much a little more transparently by simply adding a token to all links we markup in emails. Every page on the site should check for the token which can be safely long lived. This means we get constant feedback and can keep updating the email verification date. It also means we can simplify the user experience so in most cases they get the verification for free in their 'welcome' email which contains links to their profile etc. This also gives us good metrics inside the platform without using sparkmail

Also we need the inverse as well, if we verified the email last week, but then it started bouncing this week, then we need to know when it started bouncing. Currently we can only know that at the sparkmail level but we need this in the platform so we can warn people and get them to update their email. So a valid email is one which has a verified date and that date is after the latest bounce date. sparkpost should have a bounce webhook for getting this feedback.

**Comment by scd** [comment]
@brendanheywood tokens on email links will bring us up to par with sparkpost tracking capability. My paying client also wants this so I have to decide which to do first.

I also plan to implement a last opened email on an account record and an open count on the email record itself. Quite a few business get valuable information by looking at how many times an email is open.

These are all to be done as background prep for our user email campaigns.

**Comment by brendanheywood** [comment]
Various thoughts:
* [ ] most email clients will proxy and cache the images in shown emails so while you may get a realistic first open you probably can't trust the subsequent views to fire properly, so I see open count as less important (though in concept highly desirable).
* [ ] most of these types of things will embed a different code of some type into every link in the email so you can see which links get used or not (like utm_* stuff for ga)
* [ ] depending on the internals many systems churn through massive amounts of data, so to help manage this the state is encoded into the link rather than as a stored token. ie each user gets a single random key which is reused for everything, which is then used as the key to reversibly encrypt a bunch of things like email template, link, campaign etc into the query param. When it comes out the other side the server decrypts it and processes it without needing to have stored anything (which also scales way better). This may be overkill for us but worth considering.
* [ ] are we happy to ignore all this in the text version of the email? the links with long tokens can get pretty unwieldly when viewed in as text

**Comment by scd** [comment]
> encoded into the link rather than as a stored token

This is much more preferable for me. Accounts already have a token when they are created. We will implement this way.

**Comment by scd** [comment]
closing
