### ISSUE TITLE
Adding new activity items

### ISSUE THREAD

**Issue by scd** [theCrag/website#2657]
I could not find this anywhere. New activitiy items:
  - [x] Verify Email - 50 karma points (once only)
  - [x] Update Profile Description - 20 karma points (once only)
  - [x] Follow Account - 1 karma point (once per account following)
  - [x] Followed By Account - 5 karma points (once per account followed by)
  - [x] Login (10 points, once per month)
  - [x] Add avatar (10 points)

Then the following task items
 - [x] Add the config items
 - [x] Implement each activity and test exclusions
 - [x] Update karma article, seperating account based karma
 - [x] Translate karma article
 - [ ] Analyses whether we want this in the streams or not (definitely not publicly, but maybe a helpful admin function).

Role granted stream events (and revoked?)
- [ ] You granted a role in a node
- [ ] You were granted a role in a node

**Comment by nclementel** [comment]
Hi Simon,

I have a weird problem in the last few days.

A couple of times when saving ~20/30 new routes the site returned the following error, but in the end the routes were correctly added to theCrag.

If it might help you checking the log, I encountered it once yesterday at 11:18 am Brussel time.

Moved
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, scd@thecrag.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.

Apache/2.2 Server at www.thecrag.com Port 443

Cheers,

Nicola Clementel

**Comment by brendanheywood** [comment]
@nclementel if you have issues like that please either email us or make a new issue, that's unrelated to this issue.

@scd can we also make sure most of these end up as new stream items too please? They should only appear in the profile streams as they don't relate to a node. The following events should be their own stream item and appear in both streams, but all the verify and update should be like a node update so multiple updates get merged. A verify and the login would be ignored I think, but they could just be merged into a generic 'profile updated' event.

Also avatars are important, we should have karma for either uploading an image or a bit more karma for linking to facebook and getting the avatar from there. Added to the list at the top

**Comment by scd** [comment]
Notes to self about Login activity.

The module CIDS::Application::Session (which is actually in the BSIS directory) is the place to update this code. We should be looking at when a new session is created because people may stay logged in from month to month, but the system will create a new session if they are logged in.

There are two places we need to look at, both in the file above. Creating a login request (which if successful creates a session) and renewing a session.

**Comment by scd** [comment]
I have just completed the account based activity so I am closing this issue. All other tasks are part of other issues.
