### ISSUE TITLE
Configurablte view window in facet

### ISSUE THREAD

**Issue by scd** [theCrag/website#2660]
@brendanheywood to do the UI components
 - [x] link from profile page to facet aggregate graph
 - [x] date selection
 - [ ] url stub view-before, view-after, view-between

Simon to do backend
 - [x] use view dates to select default period
 - [x] use view dates to drop time slices outside this range OR to provide a flag saying that the time slice should not appear in the graph
 - [ ] update timeline explained article

**Comment by scd** [comment]
@brendanheywood are you ok with the above suggestions

**Comment by brendanheywood** [comment]
Yup just won't get to this til Sunday

**Comment by scd** [comment]
No problems. I have implemented my first bit, so 

https://dev.thecrag.com/ascents/view-between/2015+2016/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/leecujes/

Will use the view-between range to select the default period. The view-before and view-after should also work. At the moment it just adjusts the chart to show the full range of ticks at a finer period. When it comes filtering out time slices outside the view range, would you prefer to have the backend pass a flag in the axis and timeseries, or use the query parameter.

FYI if there is a logic issue I have made the changes to the inputs to the `selectDefaultTimeSeries` function in the Portal/WebPrimaryContent.pm module.

**Comment by nicHoch** [comment]
For analytical  time drill down i think it is important to disable decay via option.

Is that doable? 

Am 25. März 2017 02:38:20 MEZ schrieb Simon Dale <notifications@github.com>:
>No problems. I have implemented my first bit, so 
>
>https://dev.thecrag.com/ascents/view-between/2015+2016/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/leecujes/
>
>Will use the view-between range to select the default period. The
>view-before and view-after should also work. At the moment it just
>adjusts the chart to show the full range of ticks at a finer period.
>When it comes filtering out time slices outside the view range, would
>you prefer to have the backend pass a flag in the axis and timeseries,
>or use the query parameter.
>
>FYI if there is a logic issue I have made the changes to the inputs to
>the `selectDefaultTimeSeries` function in the
>Portal/WebPrimaryContent.pm module.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2660#issuecomment-289179158

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by brendanheywood** [comment]
@scd that example you gave for Lee looks pretty screwy with way too many slices for this period:

![image](https://cloud.githubusercontent.com/assets/187449/24328105/6962b94e-122c-11e7-90de-6967a418cb93.png)

* [ ] The time slices should use whatever time period is being used for viewing not the time period used for calculating the data. Is this what you meant by the logic issue?

* [ ] likewise I think there is a similar issue with the grade range, ideally we should show a suitable grade range for the grades being used in this period not all time which I suspect is what is happening here. ie I think lee's lowest grade in this time period is 8 so with the 'breathing room' the lower grade limit should be around 5 or so and not 1 in the example above. Same for the top end of the scale if we were viewing early in lee's timeline it should max at ~29ish instead of 37

* [ ] can we avoid all triple filter sets like 'view-before', 'view-after', 'view-between' and just stick purely with view-between which should be able to handle all 3 cases. It adds a bunch of complexity with little value. The gui filters will never link to the before / after ones and it should accept values like /between/2016+/ and /between/+2014/. The other filters already work this way and the GUI for them only ever links to 'between', but this new view-between filter does not like the others and should. ie this doesn't work and should:

https://dev.thecrag.com/ascents/view-between/2010+/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/leecujes/


I've implemented the majority of my side now, it's just hard for me the test end to end and fix any bugs until those issues above are fixed. I am only showing the graph in the ascents facet if there is 1 person, 1 valid gear type, and sorted by rating. Note this graph also appears if you link to a persons ascent facet from the climbers ranking facet

> For analytical  time drill down i think it is important to disable decay via option.

Do you mean remove the decay from the stats or remove the display of the decay after the last known real cpr? Neither really make sense to me, if you are zooming in on the graph you want the graph to be consistent at all zoom levels

**Comment by scd** [comment]
> The time slices should use whatever time period is being used for viewing not the time period used for calculating the data. Is this what you meant by the logic issue?

I thought you were going to exclude the time slices on the graph. I have to calculate them all, but I guess it makes sense for me to just remove the ones we don't want. 

I will have a look at this again in a couple of hours.

**Comment by scd** [comment]
PLEASE PUSH EVERYTHING YOU HAVE DONE.

> The time slices should use whatever time period is being used for viewing not the time period used for calculating the data. Is this what you meant by the logic issue?

Fixed now

> can we avoid all triple filter sets like 'view-before', 'view-after', 'view-between' and just stick purely with view-between which should be able to handle all 3 cases. It adds a bunch of complexity with little value. The gui filters will never link to the before / after ones and it should accept values like /between/2016+/ and /between/+2014/. The other filters already work this way and the GUI for them only ever links to 'between', but this new view-between filter does not like the others and should. ie this doesn't work and should:

The filters are all there, but you don't have to use them in the UI. The url behavior of the view-between/+2014 works. Are you saying that the UI does not generate the url or the url is returning the wrong thing.

I cannot see what you have done because you have not pushed.

> I've implemented the majority of my side now, it's just hard for me the test end to end and fix any bugs until those issues above are fixed. I am only showing the graph in the ascents facet if there is 1 person, 1 valid gear type, and sorted by rating. Note this graph also appears if you link to a persons ascent facet from the climbers ranking facet

 - [ ] I still have to update the article

**Comment by nicHoch** [comment]
Removing Decay:
 the decay is very fine to condense everything town over time to the your current "a proximite state". 
But we need also the possibility to compare two time binns (month) directly to each other. Asume you climbed a 28 route  5 month ago. Now you climbed lets say 2 routes 24 and the next month they very same 2 times 24. 
I asume that in the current state the very last month has a lower CPR than the month before. You climed the same but there is more decay from that peak 5 month ago. 
So when zooming in via fasetted search there should be the positivity to disable the decay by explicit option to provide raw data for comparison and analytics. 

Hope thats helps.
Nicky

Am 26. März 2017 06:43:07 MESZ schrieb Brendan Heywood <notifications@github.com>:
>@scd that example you gave for Lee looks pretty screwy with way too
>many slices for this period:
>
>![image](https://cloud.githubusercontent.com/assets/187449/24328105/6962b94e-122c-11e7-90de-6967a418cb93.png)
>
>* [ ] The time slices should use whatever time period is being used for
>viewing not the time period used for calculating the data. Is this what
>you meant by the logic issue?
>
>* [ ] likewise I think there is a similar issue with the grade range,
>ideally we should show a suitable grade range for the grades being used
>in this period not all time which I suspect is what is happening here.
>ie I think lee's lowest grade in this time period is 8 so with the
>'breathing room' the lower grade limit should be around 5 or so and not
>1 in the example above. Same for the top end of the scale if we were
>viewing early in lee's timeline it should max at ~29ish instead of 37
>
>* [ ] can we avoid all triple filter sets like 'view-before',
>'view-after', 'view-between' and just stick purely with view-between
>which should be able to handle all 3 cases. It adds a bunch of
>complexity with little value. The gui filters will never link to the
>before / after ones and it should accept values like /between/2016+/
>and /between/+2014/. The other filters already work this way and the
>GUI for them only ever links to 'between', but this new view-between
>filter does not like the others and should. ie this doesn't work and
>should:
>
>https://dev.thecrag.com/ascents/view-between/2010+/aggregate/graph-sport-cpr/with-route-gear-style/sport/by/leecujes/
>
>
>I've implemented the majority of my side now, it's just hard for me the
>test end to end and fix any bugs until those issues above are fixed. I
>am only showing the graph in the ascents facet if there is 1 person, 1
>valid gear type, and sorted by rating. Note this graph also appears if
>you link to a persons ascent facet from the climbers ranking facet
>
>> For analytical  time drill down i think it is important to disable
>decay via option.
>
>Do you mean remove the decay from the stats or remove the display of
>the decay after the last known real cpr? Neither really make sense to
>me, if you are zooming in on the graph you want the graph to be
>consistent at all zoom levels
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2660#issuecomment-289258126

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by scd** [comment]
@nicHoch I think you are introducing a whole new concept altogether. I just want to clarify some things first.

The candles do not have any decay in them, so you can visually compare them.

The CPR lines take into account all historical ascents (in the facet), so a grade 28 climbed 5 months ago swamps a grade 24 in the current month. Any ascents that are not near the CPR line will have negligible effect on the CPR. So regardless of decay CPR lines are not a good way to compare months if they are not at your peak performance levels.

If we were to remove decay then the CPR lines would be step function, going up every ascent (maybe only a tiny amount). Effectively what this means is that for any timeslice, the CPR level is the same as if all historical ascents were done in that time slice. In your example the CPR would be based on the 28, 5 months ago and when you climb the 2x 24 it would be the same as climbing a 28 and 2x24 in the same month, and when you climb the next 2x 24 the CPR would be the same as a 28 and 4x 24. Because of the 4 grade difference this would effectively look like a horizontal line starting at the 28, 5 months ago.

The concept I think you are getting at is comparing two periods as if they were in isolation. For example, am I climbing better in this years Easter Araps trip then last years? If you set your ascent facet filter to climbed-between dates this is possible. You just need two web pages to do this side by side.

**Comment by nicHoch** [comment]
Yes  what i have in mind are these  isolated CPR values over some defined timebin length (month, week ...).

I think the chart itself wight work out of the box but we neef a additional aggregate function.

I will open an issue github or trello? 

Am 26. März 2017 23:49:14 MESZ schrieb Simon Dale <notifications@github.com>:
>@nicHoch I think you are introducing a whole new concept altogether. I
>just want to clarify some things first.
>
>The candles do not have any decay in them, so you can visually compare
>them.
>
>The CPR lines take into account all historical ascents (in the facet),
>so a grade 28 climbed 5 months ago swamps a grade 24 in the current
>month. Any ascents that are not near the CPR line will have negligible
>effect on the CPR. So regardless of decay CPR lines are not a good way
>to compare months if they are not at your peak performance levels.
>
>If we were to remove decay then the CPR lines would be step function,
>going up every ascent (maybe only a tiny amount). Effectively what this
>means is that for any timeslice, the CPR level is the same as if all
>historical ascents were done in that time slice. In your example the
>CPR would be based on the 28, 5 months ago and when you climb the 2x 24
>it would be the same as climbing a 28 and 2x24 in the same month, and
>when you climb the next 2x 24 the CPR would be the same as a 28 and 4x
>24. Because of the 4 grade difference this would effectively look like
>a horizontal line starting at the 28, 5 months ago.
>
>The concept I think you are getting at is comparing two periods as if
>they were in isolation. For example, am I climbing better in this years
>Easter Araps trip then last years? If you set your ascent facet filter
>to climbed-between dates this is possible. You just need two web pages
>to do this side by side.
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2660#issuecomment-289319140

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by scd** [comment]
git hub. Thinking out aloud, I think we could get this with a double embed.
