### ISSUE TITLE
CPR values are not consistent

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2667]
2,582 points here (for sport):
https://www.thecrag.com/climber/anderlnought

3,107 points / place 1224 here:
https://www.thecrag.com/climbing/world/climbers/using-stat/sport-rating/

**Comment by scd** [comment]
Give it another day. We are still processing stats.

**Comment by birgander2** [comment]
Better now, only 1 point difference

**Comment by brendanheywood** [comment]
@scd reopening this, I'd still like to get to the bottom of that discrepancy, ie is this a rounding error on either side? Assuming the stats background stuff is fully up to date this should be perfectly in sync

**Comment by Mdemaillard** [comment]
1 pt difference as well on mine. could be a rounding at the display stage as well ?

**Comment by scd** [comment]
Closing this as it is most likely a minor rounding issue.
