### ISSUE TITLE
cpr timeline missing last three months (2017 ascents) in graph

### ISSUE THREAD

**Issue by scd** [theCrag/website#2668]
@brendanheywood I think this is in the graph. Can you have a look in your spare time :)

**Comment by brendanheywood** [comment]
eg 

https://www.thecrag.com/climber/anderlnought

They have ticked stuff in 2017:

![image](https://cloud.githubusercontent.com/assets/187449/24504681/e803325a-15a2-11e7-9f5a-1827ba9c60f0.png)

but doesn't show up in the graph:

![image](https://cloud.githubusercontent.com/assets/187449/24504694/f750dce4-15a2-11e7-9f44-3e24e6b30070.png)

**Comment by scd** [comment]
I think the problem is in the chart logic. The cpr data is in the template data:

https://www.thecrag.com/ascents/aggregate/graph-boulder-cpr/with-route-gear-style/boulder/by/anderlnought/json

xaxis1, xaxis2 and timeseries all seem ok to me

```
{

    "facetSuffix": "/between/2017-1+2017-3",
    "startIndex": 17167,
    "endEpoch": 1491004799,
    "label": "17 Q1",
    "endIndex": 17256,
    "startEpoch": 1483228800
}
```

@brendanheywood can you please either correct me if I am wrong, confirm that the problem is in the graph and fix or get me to look at the graph code.

**Comment by brendanheywood** [comment]
ah yup, fixed and also hot fixed
