### ISSUE TITLE
Profile page shows toprope ascents eg in notable ascents

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2670]
Hey, I just realised that among my notable ascents on my profile page are two toprope ascents. I don't consider those as very notable. Would it be possible to reintroduce a possibility to exclude certain ascent styles?

**Comment by scd** [comment]
Which ascents are top ropes?

https://www.thecrag.com/climber/anderlnought

**Comment by birgander2** [comment]
Oh, sorry:
* [La puerta](https://www.thecrag.com/climbing/spain/mallorca/route/381042291)
* [Direkter Argonautenweg](https://www.thecrag.com/climbing/germany/sachsische-schweiz/bielatal/route/230766177)

**Comment by scd** [comment]
I think we should exclude top ropes for everybody in this section.

It should probably be related to CPR, so maybe include on ascents with a zero or positive tick shift.

Is there any reason why you would want the Via ferrata there?

**Comment by birgander2** [comment]
Yes, toprope should't be included. The only reason I could think of are beginners / kids, who do only do toprope and still want to see their progress.

Via ferrata can be excluded in my opinion. This is not rock climbing ;-)

**Comment by Drazhar** [comment]
Hey, I have a slightly different opinion Anderl. For me, a toprope without rest is also an indicator for performance. For example if I toprope a 7b without a rest, it is harder than red pointing a 7a in most cases. And there certainly are days where I prefer a toprope :)

**Comment by scd** [comment]
I think @birgander2 is only concerned with what is in the notable ascents table.

Top ropes still get a CPR, although we have not been very scientific about the shift for the top rope tick shift.

Unless I misunderstand something both requirements can be satisfied.

**Comment by brendanheywood** [comment]
A quick thoughts: in the notable ascents table, my intention is to reduce this table a lot and order the entries by 'most notable' ie onsights at top, then flash, red point etc. With the CPR we now have a very clear ordering for these things. It will only ever show the top N most notable things, but if all you have ever done is top rope then it will show that for you.

**Comment by birgander2** [comment]
> I think @birgander2 is only concerned with what is in the notable ascents table

Yes. And I mostly agree with all of the above. To have a notable toprope category/entry, that's fine, I just don't like that they poulate my "by area" listings just because they have been a tad harder in grade.

@brendanheywood to reduce the page length, please also make this **huge** "you have 478 ascents without height information" disappear and place the "hardest" "onsights" "acents" "distance" in a single line not two. One really has to scroll far to discover the cool CPR graphs.

**Comment by brendanheywood** [comment]
@birgander2 yes I really dislike this whole page at the moment, it has slowly been bloated over time and contains a lot of junk. We have a plan to fairly radically reshape and focus this page. The CPR timelines are the first step. I'm in two minds about whether we slowly chip away and convert it whether we just yank it and do it all in one go. Some people will be unhappy either way. One of my main goals is to be able on a desktop to see the stream after at most 2 pages of scrolling, on some profiles this is 6 pages!

Also can you stick a screenshot here of exactly what you mean by two lines? That sounds like a separate smaller bug with the wrapping.

**Comment by birgander2** [comment]
Sure. "distance climbed" is in a 2nd line, independent of browser window size and zoom factor. And the huge missing height information box is obvious. 
![out](https://cloud.githubusercontent.com/assets/6367190/24503032/a0f48d3e-1550-11e7-98ca-114ccbc34b81.jpg)

**Comment by brendanheywood** [comment]
Yup that's a bug, what browser? I don't see that.

Also note that only you see that blue box, but it should probably be smaller and dismissable

**Comment by birgander2** [comment]
Chrome 56 on Windows 7, same on Firefox 52. 

Yeah, I know that only I see it. But once in a while is enough and honestly, I won't fix those 478 heights. I don't know them. Maybe an idea: put is a popup on the distance climbed box?

**Comment by brendanheywood** [comment]
Yeah it's also doesn't make as much sense to ask people to fill heights out for boulders, they are almost all 2m - 4m and it's not like people care, where as climbing a few 100m climbs adds up quickly. I've toyed with the idea of having a default height say 2m for boulders and 10m for climbs if the route is missing them just to make the total height slightly more realistic.

**Comment by brendanheywood** [comment]
+1 from @jedparkes via https://github.com/theCrag/website/issues/3239

**Comment by brendanheywood** [comment]
The whole notable ascents table has been completely reworked so this should be solved. Note that certain people will still get top rope ascents as notable, but only if they happen to be beginner climbers and that is all they have done.

**Comment by brendanheywood** [comment]
btw this is your page to demo before the release: https://brendan.thecrag.com/climber/anderlnought
