### ISSUE TITLE
top rope gear styles are not included in CPR

### ISSUE THREAD

**Issue by scd** [theCrag/website#2674]
For example:

https://www.thecrag.com/ascent/857679963

**Comment by brendanheywood** [comment]
This is a little vague. Should they be? I would say yes, a top rope ascent of a top rope climb should be treated more or less like a top rope of a normal sport climb with a the same shift etc. A 'lead' or 'tick' of a top rope climb however should be invalid and so have the same shift as a top rope.

**Comment by scd** [comment]
this should be done in the latest round of CPR work on simon's dev
