### ISSUE TITLE
How to enter trad routes with no possibility of pro or top rope, gear style 'solo'? 'no pro'?

### ISSUE THREAD

**Issue by scd** [theCrag/website#2675]
For example

https://www.thecrag.com/climbing/australia/evans-crown-tarana/route/12086923

I think the best solution is to add a 'no pro' tag.

Another suggestion was to add a new gear type of solo, but i think it is too much of an edge case.

**Comment by brendanheywood** [comment]
Yeah I think this is too edge case to worry about

**Comment by Mdemaillard** [comment]
The one example of that i saw, climb was labelled trad with top rope access, and description mentioned top rope only due to no pro available.

**Comment by rouletout** [comment]
Agree, I close - it states no pro. If a top rope can't be installed and no pro be put it is a high ball and should be a boulder.
