### ISSUE TITLE
In logbook crag is showing region rather than crag

### ISSUE THREAD

**Issue by jedparkes** [theCrag/website#2682]
I'm sure i had this issue in the past and you fixed it but i can't remember how to do it.
In my logbook for Crag Frey in town of Bariloche in country of Argentina
https://www.thecrag.com/ascents/by/10765333/?sortby=when-climbed,desc
It is showing the crag as Bariloche rather than Frey ?

**Comment by scd** [comment]
The reason for this is that Bariloche is recorded as a crag. Is this not correct?

**Comment by jedparkes** [comment]
Bariloche is a town, it should be region.
How can i change a crag to a region?

**Comment by jedparkes** [comment]
Hobart and surrounds has the same issue.
That is an area, how can i change that to a region ?
https://www.thecrag.com/climbing/australia/tasmania/hobart

**Comment by scd** [comment]
Done. It now looks like the ascents say they come from 'unknown'. We have noticed this before as a cache transitionary issue when you change area types. It will fix itself

**Comment by jedparkes** [comment]
OK thanks, so i can't fix this myself?
Just create another issue if i see it again?

**Comment by scd** [comment]
If you have permissions you can fix it yourself. Just send us email asking
for permissions and reference what you plan to change.
