### ISSUE TITLE
Business rules for handling the final CPR shift

### ISSUE THREAD

**Issue by scd** [theCrag/website#2683]
The code is really lose on how it handles the final tick shift back to a grade and it may even be inconsistent.

Should the presented CPR in charts include the final shift back?

OR

Is this just a conversion of the CPR back to the grade?

Currently it is poorly implemented as the later but at the internal grade level. If we do the later it should be part of the conversion back to an Internal grade.

If we do the former then it needs to be adjusted in many places including CPR chart and CPR breakdown and rating.

**Comment by brendanheywood** [comment]
Yes the cpr should include the final shift consistently everywhere. Just to double check we are talking about the 'Solidifying a new grade' shift?

The conversion of the cpr to a grade system is a separate unrelated step and is purely to make it more consumable but is optional depending on the context. Whether we convert to a local grade shouldn't matter.

**Comment by scd** [comment]
I think I can close this now
