### ISSUE TITLE
Weird anon mention in stream event

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2685]
The even has 2 people editing an area and one is anon which seems inconsistent to me:

https://www.thecrag.com/event/1176556647

![image](https://cloud.githubusercontent.com/assets/187449/24614420/7ca123d0-18ce-11e7-8804-520a21755cb7.png)

**Comment by Mdemaillard** [comment]
Anon is not there anymore, but the text still suggests there was another editor
![image](https://user-images.githubusercontent.com/60388146/76509821-4aeaf300-6459-11ea-8e98-5e10eb3a3e60.png)

**Comment by rouletout** [comment]
The second is a deleted account (now?) - hard to reproduce, closing for now
