### ISSUE TITLE
Context menus in mobile view can we wider than the screen

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2690]
**What you expected:**

Menu items should wrap, and the context menu should never be wider than the viewport and so is off screen

**What actually happened:**

![image](https://cloud.githubusercontent.com/assets/187449/24760678/bfa65690-1b2c-11e7-85ed-0012ef859a18.png)

**Comment by lordyavin** [comment]
Applies to desktop too:

![grafik](https://user-images.githubusercontent.com/1528540/36537934-f5a08fac-17d1-11e8-8a2f-8936ecd28fd7.png)

**Comment by brendanheywood** [comment]
This is finally fixed, tested in the down load menu, the action menu and the stream details menus
