### ISSUE TITLE
People are missing ascent numbers per year

### ISSUE THREAD

**Issue by scd** [theCrag/website#2691]
There seems to be a common theme in some of the feedback about the new CPR timeline. A few people miss the old chart. As best I can ascertain the common theme is around calendar year ascent numbers.

I think people want a clear chart for calendar year ascent numbers. 

The new CPR deemphasizes the ascent numbers and is not controllable to be calendar year.

**Comment by scd** [comment]
Feedback from one user:

 > I preferred the old chart that showed all my disciplines combined with total assents per year.

**Comment by brendanheywood** [comment]
Now that we have made the candles wider having a number on every single bar is fine

Before:
![image](https://cloud.githubusercontent.com/assets/187449/24825663/4d394f64-1c66-11e7-9aea-bcdcf5071cf0.png)

After:
![image](https://cloud.githubusercontent.com/assets/187449/24825665/7324fb6a-1c66-11e7-9507-76bfb877942a.png)

**Comment by scd** [comment]
That partly solves it, but I think people were interested in total ascents of all gear styles combined. The just wanted to know the volume of climbing as opposed to the performance of their climbing. I think this is fairly easily solved as a simple bar graph as some later point.

**Comment by brendanheywood** [comment]
If we do anything I'd prefer to keep it as one graph and make the botton section slightly taller and split the single gray volume bar into a stacked bar for each type. But I'm happy to roll a few incremental tweaks each release and not do any more major jarring changes.

**Comment by Drazhar** [comment]
+1 from me and +1 from Moxi.

It should be possible again to see the grade bar charts only for one discipline and also the hardest grade climbed at the top shouldn't consider bouldering and sport climbing. The grade conversion from bouldering to sport climbing makes no sense. My 7B boulder ascents count the same as 8a routes, which is totally not comparable.
