### ISSUE TITLE
Fix typos and add a few missing rock type structured tags

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2692]
as discussed yesterday here the required changes in English - once they are in I’ll (@ulf) do the translations….

In Sedimentary add: Breccia (sedimentary)
Change Greenschist to Greenschist and Prasinite
In Metamorphic add: Migmatite
Anorthosit should be  Anorthosite
Granodiorit should be Granodiorite
Brecia should be Breccia

Igneous should have 2 sub-groups:
- Plutonic with 
-- Peridotite
-- Gabbro
-- Anorthosit
-- Diorite
-- Syenite
-- Granodiorit
-- Granite
-- Tonalite

- Volcanic with
-- Andesite
-- Trachyte
-- Phonolite
-- Rhyolite
-- Basalt
-- Dolerite
-- Tephrite
-- Ignimbrite
-- Tuff
-- Agglomerate
-- Brecia

Spawned from #1930

**Comment by scd** [comment]
Here is what I will do

The following translation updates should be done first:
 - [ ] Rename: dbconfig.tags.category.igneous.label to dbconfig.tags.category.igneous-plutonic.label
 - [ ] Add: dbconfig.tags.category.igneous-volcanic.label
 - [ ] Rename: dbconfig.tags.tag.brecia.label to dbconfig.tags.tag.volcanic-breccia.label
 - [ ] Add: dbconfig.tags.category.sedimentary-breccia.label
 - [ ] Rename: dbconfig.tags.tag.greenschist.label to dbconfig.tags.tag.greenschist-and-prasinite.label
 - [ ] Add: dbconfig.tags.category.migmatite.label
 - [ ] Rename: dbconfig.tags.tag.anorthosit.label to dbconfig.tags.tag.anorthosite.label
 - [ ] Rename: dbconfig.tags.tag.granodiorit.label to dbconfig.tags.tag.granodiorite.label

Modify the following category level info:
 - [ ] Rename Igneous category to Igneous Plutonic
 - [ ] Add category Igneous Volcanic

Modify the following tag level info
 - [ ] Add Sedimentary Breccia to Sedimentary
 - [ ] Rename Greenschist to Greenschist and Prasinite
 - [ ] Add Migmatite to Metamorphic
 - [ ] Rename Anorthosit to Anorthosite
 - [ ] Rename Granodiorit to Granodiorite
 - [ ] Move Basalt to Igneous Volcanic
 - [ ] Move Dolerite to Igneous Volcanic
 - [ ] Move Ignimbrite to Igneous Volcanic
 - [ ] Move Tuff to Igneous Volcanic
 - [ ] Move Trachyte to Igneous Volcanic
 - [ ] Move Tephrite to Igneous Volcanic
 - [ ] Move Phonolite to Igneous Volcanic
 - [ ] Move Andesite to Igneous Volcanic
 - [ ] Move Agglomerate to Igneous Volcanic
 - [ ] Move Brecia to Igneous Volcanic AND rename to Volcanic Breccia
 - [ ] Move Rhyolite to Igneous Volcanic

For audit purposes this means the following igneous tag entries are unchanged:
 - Igneous
 - Granite
 - Anorthosit
 - Peridotite
 - Gabbro
 - Diorite
 - Tonalite
 - Syenite
 - Granodiorit

**Comment by scd** [comment]
@rouletout this is now done, so it is now over to you for the translations.

**Comment by rouletout** [comment]
Translations done - still some things unclear, see separate email

**Comment by scd** [comment]
I have updated these translations on prod.

Have you sent the email yet, I have not seen anything?
