### ISSUE TITLE
Regression cannot choose existing photo for use as topo anymore

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2693]
**What you expected:**
In the create topo process also see a list of images to select and turn into a topo

Split off from #346 (@lordyavin )

**What actually happened:**
You can only upload

**Comment by brendanheywood** [comment]
@scd is there much involved with this one, is it simply making it only check the db and not the filesystem as well?

**Comment by scd** [comment]
I think we can do it with just the db.

**Comment by rouletout** [comment]
+1 can we fix that, I have to load all images twice for that

**Comment by lordyavin** [comment]
+1

**Comment by rouletout** [comment]
I put that up again - it is a real pain, especially if you work in a low bandwith environment as you have to upload everything twice

**Comment by brendanheywood** [comment]
Yeah I miss this too and want it with almost all topos I make. I would still much prefer the stronger solution of simply forcing all topos to also be photos, both new and retrospectively.

**Comment by brendanheywood** [comment]
Killed https://github.com/theCrag/website/issues/346 in preference to this issue

**Comment by brendanheywood** [comment]
+1 via 
https://github.com/theCrag/website/issues/3310

**Comment by rouletout** [comment]
+1 - would have liked to hand over an image to another user so that he can draw a topo, currently impossible

**Comment by brendanheywood** [comment]
+1 from PM

**Comment by rouletout** [comment]
+1 tried again had to upload images twice (node https://www.thecrag.com/climbing/mexico/area/2172529938)

**Comment by rouletout** [comment]
+1 from support email (user conorfm)

**Comment by scd** [comment]
FYI this is fixed in dev. Closing

![Screenshot from 2019-04-22 15-24-45](https://user-images.githubusercontent.com/373058/56484413-d2163c00-6512-11e9-90e2-11fdb84d45bf.png)
