### ISSUE TITLE
Serious spam account wasn't deleted after forum was removed

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2696]
**What happened?**

Spam account:

https://www.thecrag.com/climber/willshere
created this discussion which I just 'serius spammed':

https://www.thecrag.com/discussion/1210331562/blue-mountains--cheap-kitchens-nottingham#m1210331562

but the account didn't get deleted. I have left if there for the time being

**What you expected:**
* [ ] account page to no longer be visible

**Comment by brendanheywood** [comment]
Just a heads up that I've deleted a couple new spam acounts, one today and one last week and this bug is still present. eg this account still exists and should not:

https://www.thecrag.com/climber/hannymark

**Comment by scd** [comment]
I have looked at the code and I think this was fixed a while ago. The code looks like it should work. Closing
