### ISSUE TITLE
Idea's for improving the csv logbook import process

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2699]
I've just been playing with the csv import process and I think there is some low hanging fruit that would make this much more usable. The main issue I have had so far is the cognitive load trying to match up the columns. The process introduces the arbitrary meaningless labels like Col A, Col B, Col C but then you have to scroll up and down to see which columns these are actually talking about. It would be good to have the column selection directly linked with each column and not in a second set of fields.

Feedback on 'Upload CSV logbook' step
* [x] "Third Party Source" had some junk in it

Feedback on the mapping page:
This is what my import screen looks like when trying to re-import my own log book, I've zoomed right out:
![image](https://cloud.githubusercontent.com/assets/187449/24908559/cc259c02-1f03-11e7-95de-dd69bf0641e1.png)

* [x] it's very common for csv files to have lots of columns, the table layout should look and feel roughly like excel like this:
![image](https://cloud.githubusercontent.com/assets/187449/24908736/8a5646ea-1f04-11e7-9cbd-16fbed05dd09.png)

* [x] to make it really easy to map between the columns and the values we should either
  * [x] invert the selection so instead of selection which column to pull from, we have a dropdown above each column and select what value it represents, eg the dropdown has 'Country, Crag, Sector, Cliff ...'
  * [ ] we leave it as is, but we extend the label of each to be "Col A: Ascent label", "Col B: Ascent ID", "Col C: Ascent link" this assumes that the first row is the labels which is a pretty safe assumption, and even if it's not then you'll instead get real data which is just as useful for mapping. I'm guessing this one is easier to implement.
* [x] the 'Confirm configuration' drives me nuts, this serves no purpose at all here. If you want to confirm something then you need to be presented with a summary of what you've just done to validate it.

Feedback on Import dashboard:
* [ ] when I got to this page I had absolutely no idea what to do next and the buttons made no sense to me. We need to rename some of these and add some help text to guide people through it.

Bulk assessment
* [x] not sure if things are working right on dev, I got the "Server currently process import files" message but I don't think it's processing, and clicking other buttons I got cids errors

Other issues with the export:
* [ ] I think this is already known but the columns are screwed in the logbook export, the column don't match the data.
* [ ] Also the urls used in the export don't have the proper url stubs

**Comment by nicHoch** [comment]
add more date formats 

- [ ] (d)d.(m)m.yyyy

**Comment by Mdemaillard** [comment]
@nicHoch you improved multiple things recently, so have a good grasp on current status:
can you please check if some of the aboves are ticked ?

**Comment by nicHoch** [comment]
@Mdemaillard all done 

can you please copy the issues for the export:

_Other issues with the export:
- [ ]  I think this is already known but the columns are screwed in the logbook export, the column don't match the data.
- [ ]  Also the urls used in the export don't have the proper url stubs_
 
to a better issue and close this afterwards

**Comment by nicHoch** [comment]
available with next release
