### ISSUE TITLE
Forums attached to events don't affect last read status

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2701]
**What happened?**
If I visit this:
https://www.thecrag.com/event/1132697433

then I have read all the comments attached to it, and the read status should be reset. But it doesn't like if I had gone to here:
https://www.thecrag.com/discussion/1211046945/hi-brendan-just-realized-this-message-suppose-you-have-not-been-here-i-am-also-not-aware-of-any-c

Really these two pages be merged. See also https://github.com/theCrag/website/issues/2488

**Comment by scd** [comment]
The read status is fixed.
