### ISSUE TITLE
The users CPR graph in the ascents facet doesn't honor node navigation

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2702]
**What happened?**
ie here:
https://www.thecrag.com/climbing/australia/arapiles/ascents/with-route-gear-style/trad/by/johnpitcairn/?sortby=rating,desc

**What you expected:**

* [x] The graph shows John's full timeline, not his timeline just for araps.
* [x] on the flip side if you drill into that graph it should also retain the node position too

**Comment by scd** [comment]
done
