### ISSUE TITLE
Structured Tags: Final corrections to rock types

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2705]
**What happened?**
Feedback received on latest changes to rock types, 4 minor corrections required in English and German

**What you expected:**
- Change "Sedimenatry Breccia" to "Breccia (sedimentary)" - also for consistency
- Insert "Igneous" as title above "Igneous Plutonic" as this is a group heading also for the 2 sub-groups
- Rename "Igneous" (rock type tag) to "Igneous Plutonic"
- Add "Igneous Volcanic" as tag under the heading for consistency, so all headings are available as tags

Please report when done so I can do the translations

**Comment by scd** [comment]
All changed except for one. It is not possible to insert a Igneous title above 'Igneous Plutonic' without a major redesign. There is only one level of title and the titles must have a tag.

**Comment by rouletout** [comment]
Translated it on sandpit - you can push it over

**Comment by scd** [comment]
done
