### ISSUE TITLE
Convert PDF topos lines and labels from raster back to svg lines on photos

### ISSUE THREAD

**Issue by dragonfirexx** [theCrag/website#2706]
I've just tried downloading the instant pdf for Skaha and noticed that for larger wide shot images, the numbering on the topos are very blurry to the point of incomprehensible. I try zooming in on the pdf and it just gets blurrier. The vertical shots are usually fuzzy but better to see. 
(This happens the same when I try to custom download pdf in single column as well)

Skaha PDF: https://static.thecrag.com/pdf/11758591.pdf

Side by side: 
![image](https://cloud.githubusercontent.com/assets/27459110/25028652/cbe50968-206a-11e7-8b45-4831c65dc8cf.png)

**What you expected:**
I was expecting to be able to see the numbers so i can figure out which route is which.

**Comment by brendanheywood** [comment]
Root cause is we shouldn't be serving a raster for the topo, it should be an svg which references the base raster. The lines should be bezier curves not pixels.

Give this comment: https://github.com/theCrag/website/issues/1881#issuecomment-322112748, ie that we are already using svg within the existing pdf pipeline this seems quite promising that this will be viable.

**Comment by scd** [comment]
It use to work this way but had to abandon it for some reason. We extracted svg from the rendered topo page using phantom. I cannot remember the exact difficulty, but there was some problem. Just be warned that there there might be some debugging required to get this working again.

**Comment by brendanheywood** [comment]
This one is most fixed now as the res of the topos has been bumped up, but I'll keep it open and use this as a placeholder for converting the lines and labels back to svg

**Comment by brendanheywood** [comment]
+1 via https://github.com/theCrag/website/issues/3326

For example in this area https://www.thecrag.com/climbing/mexico/el-salto/area/1667175816 the image of the topo has unreadable labels (see screenshot).


Ideally also provide screenshots:

![img_3808](https://user-images.githubusercontent.com/19162952/50377485-cefe5400-05e3-11e9-8a21-27128cb0cf4f.PNG)


Readable numbers on topo

**Comment by scd** [comment]
I think I made some fixes to this a while ago.
