### ISSUE TITLE
should undef translation inputs translate to empty string or leave the translate variable intact

### ISSUE THREAD

**Issue by scd** [theCrag/website#2708]
It is possible that a translate variable is undefined. In which case should we

A. Leave the translate variable untouched with no substitutions (this is what currently happens)

or

B. Substitute as an empty string.

I am in two minds about this. I have done it as the the former because I viewed an undefined translation variable as an error condition that I wanted to hunt down. Of course this means a little extra work in a percentage of variables where undef contextually means empty string, but there is a simple pattern which gives more control ($var||0, or $var||'').

I am not convinced we should change the current behavior.

**Comment by brendanheywood** [comment]
Honestly this should be a compile time error and never get this far. The choice of A or B isn't that important, the real question is how do we get notified when it happens at runtime? We need a loud noisy mechanism for reporting these so they get fixed asap. ie these get pushed into the error log and then an aggregate of the errors is bundled into the daily reports

**Comment by scd** [comment]
Closing as we have compile time errors.
