### ISSUE TITLE
Bad formatting of description text

### ISSUE THREAD

**Issue by johtso** [theCrag/website#2712]
`text-align: justify` on the description text is causing the text to be displayed in a very confusing, difficult to read way.

![image](https://cloud.githubusercontent.com/assets/830800/25206779/dac1ea68-2561-11e7-86fb-59c303711b32.png)

**Comment by brendanheywood** [comment]
Can you please provide an example url for this?

**Comment by brendanheywood** [comment]
note to self: https://www.thecrag.com/climbing/france/fontainebleau/area/445348695

**Comment by brendanheywood** [comment]
fixed

![image](https://cloud.githubusercontent.com/assets/187449/25260994/ffd9c438-2692-11e7-93b5-0efe93938406.png)
