### ISSUE TITLE
create climber endpoint should return translations keys not plain english

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2714]
api/climber/create

is returning plain error messages in english and the validate endpoint as well 
should return translation keys 

see #2472

**Comment by scd** [comment]
@nicHoch this is done but there are some business rules which also apply to the login endpoint.

Calling the API you can also set the language by either the lang=en url parameter or the Accept-Language header. In particular this is useful for the website javascript, and may or may not be useful for your app.

If the language is set the then error returned is translated. If the language is not set then the language key is returned.

While this is the business rule, it will take a while to implement fully. The api has hundreds of error messages that need translating. This is going to take a long time to work through. My strategy is just to fix them as you encounter them in the app.

This means your app should be able to gracefully handle a non-key being returned.

@nicHoch please close this issue after the release.

**Comment by Mdemaillard** [comment]
@nicHoch candidate for closure ?
