### ISSUE TITLE
weird customize event for circuits (wishlists)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2715]
**What happened?**

https://www.thecrag.com/event/1219905657

(please also provide urls and screen shots)
![image](https://cloud.githubusercontent.com/assets/187449/25230773/9a0f5e30-2618-11e7-8af6-d00910e35c50.png)

**What you expected:**
This event makes no sense. It probably does but just needs to be fleshed out properly

**Comment by scd** [comment]
This is an event for creating a circuit. You can see the details in the json:

https://www.thecrag.com/event/1219905657/json

I think we just never got around to fleshing this out. 

From memory we wanted to keep the list of event types down and the customize was for stuff that did not quite fit.

Note that adding a new event type is a bit shitty, so I want to avoid this if possible.

A wishlist may not have to have anything in it. I think it may or may not be associated with a node.

A stream event must be associated with a node. 

Are we happy with a customize event at all?

What do we want the event type to be for creating a wishlist? Adding/removing a route to a wish list? Publishing a wishlist to an area? In someways it is also similar to a topo, so I would be happy with moving it to the update type.

We need to have this discussion in context of other activity items soon to be associated with a stream event. For example assigning permissions and updating account profile details.

**Comment by brendanheywood** [comment]
> Note that adding a new event type is a bit shitty, so I want to avoid this if possible.

Hmm, there is a large list of these in the pipeworks as you mentioned. Some of these can go under the general 'update' category but some won't.

In this particular case I think there should be a 'created / updated circuit' event, but it may not always have a node. In some cases like a circuit it may make sense to teat it like another type of update, but this isn't right for wishlists ro other lists. So I think it needs to be it's own type.

I guess if it doesn't have a node then in some cases its really is just the world node. I don't think a generic 'customize' event makes sense here at least, can you remember the rationale for this at the time?

> A stream event must be associated with a node.

This seems not great, eg updating your profile, following someone, these don't have nodes attached and are not equivalent to being added to the world node. 

All that said I'm happy to delay this particular issue until we get to the wishlists, except for any structural issues to support the other new event types

**Comment by scd** [comment]
Closing as we are revamping circuits to wishlist soon.
