### ISSUE TITLE
@mention autocomplete not working anymore in stream comments

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2719]
**What happened?**
In any stream event comments no longer allow @ mention auto complete, eg

https://www.thecrag.com/event/732443394
![image](https://cloud.githubusercontent.com/assets/187449/25265720/ba0a5110-26b1-11e7-8b76-c957d1f2b449.png)

**What you expected:**
If I view the discussion directly and comment then it does work:
https://www.thecrag.com/discussion/1222344579/did-you-finish-this-alan#m1222344579
![image](https://cloud.githubusercontent.com/assets/187449/25265758/e39fa1ec-26b1-11e7-8ea8-2fbf521c4c11.png)

Perhaps this has never worked but it feels like a regression to me.

**Comment by scd** [comment]
never worked. 

I have already fixed this in dev when I allowed comments to be edited. Have you tested in dev.

Please close if works in dev

**Comment by brendanheywood** [comment]
Ha! this is great, testing in area, route, dashboard
