### ISSUE TITLE
CPR number label not visible in timeline graph

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2720]
**What happened?**
The 'breathing room' above and below the graph only takes into account the ticks but not the cpr. If cpr is mostly based of the most pure tick type then it will be above the breathing room and the number label will be outside the bounds of the graph

https://dev.thecrag.com/climbing/australia/arapiles/ascents/with-route-gear-style/trad/by/johnpitcairn/between/2016+2016?sortby=rating,desc

(please also provide urls and screen shots)
![image](https://cloud.githubusercontent.com/assets/187449/25313952/ee2a9938-287c-11e7-81b1-75b45c4f6a99.png)

**What you expected:**
The logic which determines the breathing room should take all ascent grades as well as derived cpr grades into account when determining the upp and lower grade bounds for the graph

**Comment by rouletout** [comment]
I think this is solved, closing
