### ISSUE TITLE
new investigatory yy language

### ISSUE THREAD

**Issue by scd** [theCrag/website#2721]
@ulf I have added a new 'yy' language which is similar to the 'xx' language but returns the key. This will be available after the next release. After you have seen it in action please close this issue.

So

https://www.thecrag.com/climbing/australia/arapiles?lang=yy

will look like:

![screenshot from 2017-04-24 09-38-28](https://cloud.githubusercontent.com/assets/373058/25318423/da8c29f0-28d1-11e7-974b-ebabe6f5cccc.png)

**Comment by rouletout** [comment]
Works, and included in the translation manual
