### ISSUE TITLE
"Notable ascents: by area" not updating

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2722]
**What happened?**
[Yangshuo](https://www.thecrag.com/climbing/china-mainland/yangshuo) should have overtaken [The stones](https://www.thecrag.com/climbing/australia/pierces-creek-bouldering/area/816338718) more than a week ago, based on the ascent no. criteria.

Additional points
- https://www.thecrag.com/climber/deeno
- Doesn't seem like it's just a delayed update thing, I've left it a week, guessing it was just a periodic update, but that seems unlikey at this point. 
- Both areas are actually classified as area's
- I've got a second area within Pierces on that list, so there might be some block in merging. 

![image](https://cloud.githubusercontent.com/assets/22091505/25318798/f2c26f8c-28d8-11e7-9837-6979f7a572ee.png)

Yanshuo ascents (lead excluding dog) :
![image](https://cloud.githubusercontent.com/assets/22091505/25318945/178abb2e-28db-11e7-8312-c8f90c3bb95b.png)

**What you expected:**
I would expect to have been able to rid myself of one bouldering area after this trip, and at least condense Pierces Ck down to a single mention.

**Comment by scd** [comment]
I just want to confirm that there are two issues you see in the ascents by area part of the notable ascents.
  * Both Tumblers and The Stones should be combined to Pierce's Creek (or some higher level)
  * You have more ascents in Yangshuo than the Stones, so Yangshuo should be on the list.

**Comment by DaneEvans** [comment]
Yeah, I'm not sure that the former is an issue though, it made some sense to have them separate when they both had substantial numbers relative to other things on the list.
So it seems likely to be a result of the latter

**Comment by scd** [comment]
It will be a while before we get around to this one. There is some planed work on this table, which is when we will look into this.

**Comment by brendanheywood** [comment]
@DaneEvans this should be done so closing, please correct me if I'm wrong
