### ISSUE TITLE
detect encoding when importing ascents

### ISSUE THREAD

**Issue by scd** [theCrag/website#2724]
The import ascents process should be able to detect encoding when importing. 

This has been split from #2713 

@nicHoch to send the broken example file to simon for further investigation.

**Comment by rouletout** [comment]
@nicHoch it does that now, no? Please close if this is the case.

**Comment by nicHoch** [comment]
there is no auto detecting encoding while import but we mention on several places on the website that we only support UTF-8 well. Any auto detecting will be not 100% correct and so the matching will suffer. I think we should close that.
