### ISSUE TITLE
Verify your email - followup

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2725]
**What happened?**

Pressed the "Verify your email" in the user menu.
Mail was sent and delivered but the activation link in the mail is not a link just plain text. 

(please also provide urls and screen shots)

**What you expected:**

A real link not just plain text. 

After successful verification i expect that the menu entry will disappear until i change my e mail address again.

**Comment by scd** [comment]
I have hot fixed the email but the test email has not come through yet so I am unable verify if it works.

@nicHoch can you please try again yourself.

Also did you cut and paste the activation link and that did not turn it off in the menu. Is this also broken?

**Comment by nicHoch** [comment]
i copy and pasted the link and the activation is working. i cant resent the verification mail because it is already activated. The activation did not turn off the entry in the menue.

**Comment by scd** [comment]
both issues fixed. Maybe test with one of your alternate accounts.

And doh, the issue with not receiving email was because I used the dev system rather than the live system.

**Comment by nicHoch** [comment]
Tested with other account. And is working as expected.
