### ISSUE TITLE
Favorites are not shown correctly

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2727]
**What happened?**
On profile page, click the number after "Favorites". Instead of the favorite crags, n times the avatar image is shown.

**What you expected:**
A listing of the favorite crags of this person.

**Comment by brendanheywood** [comment]
Weirdly this page works fine on dev:

![image](https://cloud.githubusercontent.com/assets/187449/25433915/8a68b8d2-2acd-11e7-9648-b0846a8e3dfb.png)

It could certainly do with some love, in particular after we get the webcover stuff going but I'll treat that as a new issue.

**Comment by brendanheywood** [comment]
Ah this is the same bug as https://github.com/theCrag/website/issues/2733 which I just fixed on dev already. @scd this is just a css bug, do you think this warrants a hot fix?

**Comment by scd** [comment]
Don't worry about hot fix. Hopefully we will be starting a tighter release cycle again soon.
