### ISSUE TITLE
Exclude toprope from notable ascents

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2728]
**What happened?**
Has been mentioned before, now as a seperate issue: Toprope ascents are shown as part of the notable ascents by area / by style

**What you expected:**
Was configurable before, is not anymore. Maybe fine, but the default is not optimal. Spontanous idea: use highest CPR for selection maybe?

**Comment by brendanheywood** [comment]
Yes this is planned, the intention is the use the 'cleanest' top N ascent groups, so if all you've ever done is topropes then thats what you'll see but as you start leading and onsight then top ropes will drop off.

**Comment by birgander2** [comment]
Sounds like an excellent plan!

**Comment by lordyavin** [comment]
What about via ferrata ascents? I recently logged some via ferrate and now my hardest ascent is a via ferrata grade E. I don't want to see this in my notable ascents too.

**Comment by scd** [comment]
Yup agree with this.

**Comment by lordyavin** [comment]
any updates on this issue?

**Comment by scd** [comment]
We have not been working on the profile for a while. Not in the immediate future either.

**Comment by lordyavin** [comment]
I propose to close this as won't do to reduce the backlog.
