### ISSUE TITLE
profile page message about height info not wrapping

### ISSUE THREAD

**Issue by scd** [theCrag/website#2730]
![image](https://cloud.githubusercontent.com/assets/187449/25412843/2a9f19d2-2a69-11e7-86e8-6fa120ae8a3b.png)

https://www.dropbox.com/s/21b8vp771aurwya/Screenshot%202017-04-25%2018.57.58.png?dl=0

**Comment by brendanheywood** [comment]
I have hot fixed this

![image](https://cloud.githubusercontent.com/assets/187449/25431706/066385a6-2ac5-11e7-838e-6a52b65e6c36.png)

**Comment by quaestor** [comment]
The "View pending" link on the left-hand side in the Karma box still doesn't wrap, though.

**Comment by brendanheywood** [comment]
hotfixed as well

![image](https://cloud.githubusercontent.com/assets/187449/25437486/e3ef5756-2ad9-11e7-9608-450143340be2.png)
