### ISSUE TITLE
Make permissions request and grant emails thread together

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2734]
**What happened?**
At the moment we have 2 emails which have two different titles like:

[theCrag] Request Permissions - {user} - {crag}
[theCrag] You have been granted {role} permissions for {crag}

Sometimes we get multiple requests for different crags from the same person, and sometimes we grant them higher up. So there is a bunch of disconnected emails. Ideally we want these all to be grouped together so we can see the context for 1 account all together.

**What you expected:**
It would be nice if we could keep it all together. We can make this easier in the email for both us and the people involved if it is all threaded together as one coherent and ongoing conversation, which is exactly what it is. What I'm thinking is just some simple renaming of the email title to:

[theCrag] Permission request for Brendan Heywood (@brendanheywood)

and then the followup granted email to simply:

Re: [theCrag] Permission request for Brendan Heywood (@brendanheywood)

Pros:
* This way if we get 3 emails from the same person they well all get threaded.
* the reply also gets threaded so it's super clear if anyone has responded
* the reply still gets threaded even if we give permissions for a higher level
* we also see a long history of all the crags we have granted in one thread for more context

Cons:
* it's possible that because we will get all crag requests together we may miss an email

Tasks:
* [x] set the two email titles (this is what gmail uses for threading)
* [ ] in the grant email set the email From header name (but *not* the email) to the person who granted the role. ie the header should look like:

```
From: Simon Dale - @scd <support@thecrag.com>
```

* [ ] in the grant email set the To: headers to correctly include the recipients name. ie for Lee it would be

```
From: lee cossey - @leej <redacted@email.com>
```

* [x] the granted email text should make a reference to the person who granted the role, eg "Simon Dale (@scd) has granted you Editor permissions for Australia on theCrag."
* [ ] set consistent References: headers for both sets of emails so they get threaded in most other clients. I'd suggest a header like:

```
References: permissions+12345678@thecrag.com
```

The number is the account user id. Note this is just a message id not an email, it just looks like one.

**Comment by scd** [comment]
+1 for the subject changes and adding administrator name to grant. I will get onto this.

An enhancement would be required to get the from email working as you suggest, so that is not low hanging fruit.

The to headers is a general issue and should just be dealt with as such. Maybe we should just separate it.

The references is probably not as important as the subject as we are all using Google, and not so low hanging.

**Comment by scd** [comment]
I have done the low hanging fruit here. I have done a round trip test which groups emails on gmail.

My suggestion is that we close this issue and split the remaining tasks into another issue (something like email header enhancements) as they all have wider importance.

**Comment by brendanheywood** [comment]
Cool, can you split off what's left so we know whats what?

**Comment by scd** [comment]
split off in #2746
