### ISSUE TITLE
Wrong text in forum button

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2738]
**What happened?**
In any forum discussion the text of the third button at the top is "template.forum.button-to-dashboard" instead of "template.forum.button-to-forum" (only the text is wrong, the link is correct)

https://www.thecrag.com/discussion/1227012459/blue-mountains--rope-found-at-mt-piddington-carpark-24th-april

![screen shot 2017-04-28 at 13 23 42](https://cloud.githubusercontent.com/assets/19304867/25526927/3ba88660-2c16-11e7-83a7-98a622e74cfb.png)

**What you expected:**

The same as at the bottom 

![screen shot 2017-04-28 at 13 27 54](https://cloud.githubusercontent.com/assets/19304867/25526969/8e174526-2c16-11e7-842a-12beba8df4f2.png)

**Comment by brendanheywood** [comment]
thanks!

![image](https://cloud.githubusercontent.com/assets/187449/25579482/9ac96c8e-2ebb-11e7-84fa-a4c4278b8081.png)
