### ISSUE TITLE
Pop-up info box not showing

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2739]
**What happened?**

Pop-up info box doesn't show if area is in steam. Same goes for creation or update of area, routes, or topos (try placing your cursor on any link like the one in the following screenshot).

![screen shot 2017-04-28 at 13 46 36](https://cloud.githubusercontent.com/assets/19304867/25527553/81bdffb0-2c19-11e7-88bd-11a85c855f7f.png)

**What you expected:**

![screen shot 2017-04-28 at 13 46 58](https://cloud.githubusercontent.com/assets/19304867/25527648/ffce675a-2c19-11e7-832a-19a3f1b5c0e6.png)

**Comment by birgander2** [comment]
Yes, this annoys me, too. This bug is present since about 1 or 2 years, before it was working.

**Comment by brendanheywood** [comment]
Ok thanks I have added this in a bunch of places. If there other places you find where you want this that need it (not all do), then please make new issues.

![image](https://cloud.githubusercontent.com/assets/187449/25579303/0349ac4e-2eba-11e7-8d6b-9d40160b1034.png)
