### ISSUE TITLE
translation not implemented in 'Help' menu pop-up box

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2748]
**What happened?**

The guide 'topics' in the pop-up menu from the 'Help' button are not translated.

![screen shot 2017-05-03 at 16 48 45](https://cloud.githubusercontent.com/assets/19304867/25666463/e9e8d816-3020-11e7-982f-c70c6c698e01.png)

**What you expected:**

Same translation as in the left column on the 'Help' page

**Comment by scd** [comment]
fixed on simon dev
