### ISSUE TITLE
Township Creek Merge

### ISSUE THREAD

**Issue by jedparkes** [theCrag/website#2751]
This https://www.thecrag.com/climbing/australia/tasmania/area/638030577
Needs merging into this https://www.thecrag.com/climbing/australia/tasmania/area/1043910396

**Comment by brendanheywood** [comment]
thanks done. There will need to be some cleanup, possibly re ordering them etc. @jedparkes you already had coordinator role for tassie (actually for all of aus) so you can do this youself in future too

**Comment by jedparkes** [comment]
great, thanks for that
