### ISSUE TITLE
Cannot see the default grade context in Slovakia

### ISSUE THREAD

**Issue by scd** [theCrag/website#2754]
**What happened?**

Cannot see the default grade context here:
https://www.thecrag.com/climbing/slovakia

![image](https://cloud.githubusercontent.com/assets/187449/25779752/ec53a12e-3360-11e7-8fad-a4e4a70a05c1.png)

**What you expected:**

Should be able to see it like this:
![image](https://cloud.githubusercontent.com/assets/187449/25779756/f5c9035c-3360-11e7-83fe-760271a93083.png)

**Comment by brendanheywood** [comment]
Missing the data->locate template data.

Weirdly the data is there, eg on the grade page Slovakia:

https://www.thecrag.com/en/article/grades#context-UIAA

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76700128-01024700-66bd-11ea-8aa5-6a401c560614.png)

Closing
