### ISSUE TITLE
Update trips article to indicate it is not longer functional

### ISSUE THREAD

**Issue by scd** [theCrag/website#2759]
**What happened?**

Users getting confused with an article that says trips exists and it does not.

https://www.thecrag.com/article/Trips

**Comment by Heineken** [comment]
Yeah, I am one of those confused users. I was looking for a way to link to a climbing trip (is there one?), stumbled upon this help article and kept looking for the mentioned "trips" tab for a while...

**Comment by Mdemaillard** [comment]
that URL default to another help page. No trips mentioned in help anymore.
the lists and circuits page DOES mention it is currently broken.
https://www.thecrag.com/en/article/circuits
closing.

![image](https://user-images.githubusercontent.com/60388146/78450243-991c9c00-767d-11ea-99ba-8ff69d78070e.png)
