### ISSUE TITLE
Dashboard misleadingly presents ascents, hides ascent date

### ISSUE THREAD

**Issue by dnnr** [theCrag/website#2760]
This is mainly usability criticism, with a suggestion for enhancement:

When ascents shows up in the dashboard, the message looks something like this:

![image](https://cloud.githubusercontent.com/assets/2630359/25936762/548aff88-3629-11e7-811f-e427321b3c8c.png)

The wording suggests that this ascent happened the day before, even though this is not the case.
Experienced users might guess from the styling, that "about a day ago" refers to the time of the site activity (as in: the logging of the ascent) rather than the ascent itself.

However, even with that in mind, the actual ascent date is pretty far away in terms of UI workflow: the only way seems to be to open the context menu for one of the ascents and selecting _View this ascent_. And then you still don't know whether all those ascents happened on the same day. 

I'd suggest this:
- Rephrase the message to, for example, "logged one onsight and 5 ascents at [...] • about a day ago", which would at least be factually correct
- Provide the ascent date in a non-invasive hover text; maybe within the ascent icon hover text

**Comment by scd** [comment]
We do what you suggest when the ascent date is more than a couple of days away from the log date.

@brendanheywood can you suggest ways of making it clearer what the actual ascent date was.

**Comment by dnnr** [comment]
Nice, I didn't know that! In my example, the ascent and log date were 3 days apart. Subjectively, this should be have been enough of a difference to warrant an indication of the difference. I'd even set that threshold to just 1 day.

**Comment by scd** [comment]
The overall workflow we were designing for was going away for the weekend and logging the ascents on Monday morning. 1 day does not work in this workflow.

Eventually when we have an app and the majority of users will be logging real time. When this is the case then a tighter limit will be more reasonable.

**Comment by dnnr** [comment]
Ah, I see. Personally, me and my peers almost always log ascents on the same day, so I don't even run into that issue too often. On the other hand, this makes it extra confusing to me, seeing something like in the screenshot above, while being certain that Simon did not in fact go out climbing yesterday.

Maybe the best of both worlds is to find a presentation that works well for "both" cases, so that you don't even have to think about if the threshold might be too low or high.

**Comment by brendanheywood** [comment]
Slight cross over with #1121 and #2913

**Comment by Mdemaillard** [comment]
Behaviour confirmed : ticked retrospectively vs ticked on the same day.
![image](https://user-images.githubusercontent.com/60388146/78450345-3b3c8400-767e-11ea-8f6d-2a84af960b33.png)

![image](https://user-images.githubusercontent.com/60388146/78450359-47c0dc80-767e-11ea-9059-ba79040abba6.png)

closing
