### ISSUE TITLE
Markdown description with explicit link to route does not link correctly.

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2762]
**What happened?**
See "history" section of the description of [Fontainebleau](https://www.thecrag.com/climbing/france/fontainebleau), route "La Marie Rose", entered as: 'La Marie Rose'[14019247]. The correct route is linked only on the "La", a wrong one on "Marie" and nothing on Rose.

**What you expected:**
The whole text as a single link to the correct route.

**Comment by brendanheywood** [comment]
Not directly related, but seems like if we did https://github.com/theCrag/website/issues/2765 then this could be done a lot more exact and tidier via that method. These particular examples also include the FA and year.

**Comment by quaestor** [comment]
"La Marie Rose" shows a wrong link for me on all the words, but shows up as a single link.

**Comment by quaestor** [comment]
Moreover, could it be that this 'thecrag flavoured markdown' doesn't work at all in private discussions?

**Comment by scd** [comment]
Screenshot? What is the url it is linking to?

**Comment by quaestor** [comment]
That's the rendered version from a private conversation:
<img width="305" alt="screenshot 2018-03-17 22 30 10" src="https://user-images.githubusercontent.com/54371/37560119-fb5caf20-2a32-11e8-9cd3-aa18203b32e7.png">
It is rendered just as I typed it.

**Comment by birgander2** [comment]
At least the "Marie Rose" bug I managed to fix, by simply entering the route name again.

**Comment by Mdemaillard** [comment]
closing as duplicate of #3272
