### ISSUE TITLE
Requesting permissions for a route has wrong urls in email

### ISSUE THREAD

**Issue by scd** [theCrag/website#2769]
https://www.thecrag.com/climbing/australia/victoria/melbourne/area/1076185152/account-permit/xxxx

1076185152 is a route.

Permissions process should work with areas only

**Comment by brendanheywood** [comment]
If you are at a route page it should still have the same request button but for its parent

**Comment by scd** [comment]
- [ ] Add button to route page
 - [ ] Process to request permission for parent area

**Comment by scd** [comment]
this is done
