### ISSUE TITLE
CPR logic of new Ascent Gear Style field

### ISSUE THREAD

**Issue by scd** [theCrag/website#2770]
We need to do CPR type off ascent gear style setting, not route gear style setting.

The rules involve looking at both the gear style of the route and the tick type

Gear Style: Sport
  * Greenpoint => Trad
  * Greenpoint Onsight => Trad
  * Solo => Trad

Gear Style: Trad
  * Pink point => Sport
  * Top roping ascents => Sport

Gear Style: Boulder
  * Top roping ascents => Sport

Gear Style: Top rope
  * Top roping ascents => Sport
  * Solo => Trad

Gear Style: DWS
  * all => Sport

Gear Style: Aid
  * no mapping

Gear Style: Via ferrata
  * no mapping

Gear Style: Ice
  * no mapping

Gear Style: Alpine
  * no mapping

Gear Style: Traverse
  * no mapping

Gear Style: Unknown
  * no mapping

If somebody failed a greenpoint and logged a failed attempt, this will go on their failed ascents for sport. This is not quite right, but a real edge case.

**Comment by scd** [comment]
See also #2687 #2674

**Comment by scd** [comment]
Checklist
 - [ ] update tick types
 - [ ] add new cpr scores for new tick types
 - [ ] implement ascent cpr gear style assessment
 - [ ] migrate existing ascents
 - [ ] system variable flag for system cuting over to ascent cpr gear style
 - [ ] create ascent
 - [ ] update ascent
 - [ ] delete ascent
 - [ ] route node statistic can have multiple cpr scores for a particular account. Assess logic
 - [ ] update route gear style -> impacts all ascents
 - [ ] statistic delta modes (which ones?)
 - [ ] statistic baseline modes
 - [ ] sql snippets
 - [ ] cpr curve - new facet?

**Comment by brendanheywood** [comment]
Just thinking out loud, we currently have facet urls like this:

/ascents/aggregate/graph-boulder-cpr/with-route-gear-style/boulder/in-setting/natural/by/brendanheywood/

In furure will be ignoring the routes gear style and using the ascents gear style instead, that would suggest we have a new url instead something like:

/ascents/aggregate/graph-boulder-cpr/with-ascent-gear-style/boulder/in-setting/natural/by/brendanheywood/

But this still kinda bugs me a little and seems redundant. To me 'boulder cpr' implicitly means things are filtered to only the things which contribute to the boulder cpr score, so it could just be:

/ascents/aggregate/graph-boulder-cpr/in-setting/natural/by/brendanheywood/

This might seem a little academic, especially as it's inside an iframe url, but this affects a bunch of urls that are visible and more importanlt impacts the filterin UI as it means adding an extra filter. To me there should not need to be an ascent filter for ascent gear style pre-selected to 'Boulder', and when it comes to the cross gear style things like green point and pink point I think this will become really confusing.

**Comment by scd** [comment]
The 'aggregate/graph-boulder-cpr/' is meant to be a processing display function that operates on the returned facet search. It already filters itself to use just the boulder CPR ascents, but we could make it implicitely do the boulder facet aswell.

The issue is, what will the raw facet be that captures all the boulder cpr ascents (ie without an aggregate function).  I cannot see how we can get away without having an extra filter for ascents.

**Comment by brendanheywood** [comment]
We already have that and are using it in the drill down urls:

/ascents/has/rating/with-route-gear-style/sport/in-setting/natural/by/brendanheywood/?sortby=rating,desc

But the problem is that it's generic as is just /has/rating/ when it really needs to be /has/sport-cpr/

/ascents/has/sport-cpr/in-setting/natural/by/brendanheywood/?sortby=rating,desc

this makes more sense to me than

/ascents/has/rating/with-ascent-gear-style/sport/in-setting/natural/by/brendanheywood/?sortby=rating,desc

**Comment by scd** [comment]
Yes, the 'has/sport-cpr/' makes sense to me. This change is the last step in the process so I had not really thought about it, but expected to do something like this.

**Comment by scd** [comment]
Updating a routes gear style is a bit more troublesome because every ascent associated with the route must be assessed and the ascent cpr gear style potentially updated. To make this scalable this has got to happen in the backend, rather then live when the user presses the button. Tasks:
 - [ ] add a route field (GearStyleChanged) indicating that gear style has been updated
 - [ ] when a route gear style change has been changed update the GearStyleChanged field and trigger a dequeue event (dequeue_gear_style_changes) on the application server
 - [ ] application server dequeue_gear_style_changes function which forks and initiates a dequeue script to run
 - [ ] dequeue-gear-style-changes script which iterates through each route with a GearStyleChanged flag set with the following functions: a) updates the flag and b) foreach ascent assess if cpr ascent gear style needs to be changed and c) trigger statistics if the cpr ascent gear style is changed for any ascents.
 - [ ] add a processing point for gear style changes

**Comment by scd** [comment]
NOTE TO SELF. Currently up to testing ./dequeue-gear-style-changes.

**Comment by scd** [comment]
I have implemented some simple logic to select which CPR graphs to show in profile page. It is based on the profile page settings for showing ascents in natural or artificial ascents. The rules are:
  * Show maximum of 3 CPR curves
  * If Natural ascents is selected then just show Outdoor CPR curves
  * If Artificial ascents is selected then just show Gym CPR curves
  * Order by number of ascents

**Comment by nicHoch** [comment]
Greenpoint => Trad

is that working?

i have done some greenpoints recently

https://www.thecrag.com/climbing/switzerland/goscheneralptal/area/1400407503/ascents/with-tick-type/greenpointonsight+greenpoint/by/nickyhochmuth/?sortby=when,desc 

 but they do not appear in my cpr trad chart:

https://www.thecrag.com/climbing/switzerland/goscheneralptal/area/1400407503/ascents/has/trad-cpr/by/nickyhochmuth/?sortby=when,desc

**Comment by scd** [comment]
Something is wrong because the system says the ascent is ineligible for cpr:

https://www.thecrag.com/ascent/1401394608
