### ISSUE TITLE
Mobile Web: Help Menu not displayed

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2772]
**What happened?**
![img_1377](https://cloud.githubusercontent.com/assets/19162952/26525206/2db224d6-430d-11e7-8854-1e40408298f1.PNG)

The help menu appears to be empty on mobile devices (screenshot for iPhone)

**What you expected:**
Same behaviour as web-site

**Comment by brendanheywood** [comment]
The hover event isn't firing on mobile, I think the simplest fix here is rendering that menu server side like all the others instead of an Ajax call. This also fixes some other edge case bugs with the load timing of this menu. The help structure should be cached and have no performance impact

**Comment by scd** [comment]
fixed on simon dev
