### ISSUE TITLE
unescaped text in event stream

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2774]
**What happened?**
Some formatting in the stream events are not escaped and interferes the following code. 

https://www.thecrag.com/event/1286025402

<img width="543" alt="2017-05-31 10_04_13-dashboard fur nicky _ thecrag" src="https://cloud.githubusercontent.com/assets/2226714/26621865/95131576-45e8-11e7-95d4-bf31dcbe37e9.png">

**What you expected:**

**Comment by Drazhar** [comment]
I'm not sure if this is my mistake. I wanted some parts of the text bold and the only way I know how to do this is by using <b>...</b>.

**Comment by Drazhar** [comment]
Can't use this here... < b > and < / b >

**Comment by scd** [comment]
Git uses markdown which means you can emphasis with `**stars**` which will look like this **stars**. I think this should be the same in theCrag. Please give it a go.

**Comment by rouletout** [comment]
Please refer to https://www.thecrag.com/de/artikel/formattingtext#fett-und-kursiv - closing
