### ISSUE TITLE
Profile page showing contradicting ascents total

### ISSUE THREAD

**Issue by AndrewRR** [theCrag/website#2776]
The ascent totals displayed on the profile page (header and main page) do not agree.  Following screen shot shown with mouse over main page ascents (displaying 72 unique ascents).
![ascents3](https://cloud.githubusercontent.com/assets/29109217/26659830/32ef8364-46b7-11e7-8e38-929c8f5e316b.PNG)

The profile header total agrees with the total found in logbook:
![ascents2](https://cloud.githubusercontent.com/assets/29109217/26659606/40506ad4-46b5-11e7-8e5a-12901ae75d9d.PNG)

**Comment by scd** [comment]
Is this a difference between distinct ascents versus all ascents? 

By distinct ascents, I mean if you climb a route twice then it is only counted once.

**Comment by brendanheywood** [comment]
No, in that example there is 72 vs 78 vs 83, this is a bug

**Comment by brendanheywood** [comment]
This is more aligned and where it isn't now has clear labels as to why, done
