### ISSUE TITLE
Profile page circuit total still counts deleted circuits

### ISSUE THREAD

**Issue by AndrewRR** [theCrag/website#2777]
Profile page circuit total still counts deleted circuits:
![ascentscircuits](https://cloud.githubusercontent.com/assets/29109217/26659870/805ad0b8-46b7-11e7-8369-9f388f9d6736.png)

Six circuits had been created but were all deleted.  The correct circuit count should be 0, as shown when clicking the total count (of 6):
![ascentscircuits2](https://cloud.githubusercontent.com/assets/29109217/26659930/f8f51f2e-46b7-11e7-955b-7b0930c7a7dd.png)

**Comment by scd** [comment]
We will be giving circuits an overhaul. Will look into this issue then.

**Comment by rouletout** [comment]
Circuits are gone from the profile page, closing
