### ISSUE TITLE
Update ascent grade to align with pitches when pitches provided

### ISSUE THREAD

**Issue by scd** [theCrag/website#2782]
I could not find this anywhere even though I am now working on it.

If you provide pitches for your ascent then this should determine the overall ascent grade. The main driver for this is that there are a number of ascents with inaccurate grades for CPR calculations.

I am ok with managing this when logging the ascent in the backend rather than a front end function. This means it is consistent no matter where the ascent is being logged from.

 - [x] create ascent
 - [x] update ascent
 - [ ] data migration

**Comment by brendanheywood** [comment]
This one: https://github.com/theCrag/website/issues/1698

**Comment by scd** [comment]
The only thing I am doing in this piece of work is not mentioned on that issue. 

I am only updating ascent grade to reflect the grade of pitches logged. There is a heap of stuff required for pitches but I am only doing the stuff which is directly required for CPR to satisfy ulf.

**Comment by scd** [comment]
done on simon dev
