### ISSUE TITLE
Meta sediment rock type tag is missing

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2784]
**What happened?**

Pretty well everything in new england that isn't granite is meta sediment but there isn't a clear tag for this. All the gorges, and down on the coast all the headlands are metasediment of one type or another. The rock types don't always have exact names and if they did they wouldn't really be known or that useful to climbers - but broadly they are all meta-sediments and climb fairly similarly so a single name is useful for them all. All the geologist climbing friends I know just say 'meta-sediment'. It can be chossy but in places where it's been hammered by water in the gorges or headlands it can be quite good.

Depending on which classification we adopt this could be a new generic tag under Metamorphic, or it could be a new group and all the metamorphic sedimentary rocks get moved into it which would include marble, quartize and others. Probably the former is less work and clearer:

https://en.wikipedia.org/wiki/Metasediment

See also:
https://www.thecrag.com/discussion/1294981449/lowtai-cave--what-type-of-rock-is-this

**Comment by brendanheywood** [comment]
See also https://github.com/theCrag/website/issues/2771

@flugrost it would be good to get your input here too please?

**Comment by flugrost** [comment]
Good morning. Naturally not all existing rock types are listed. I
restricted the list on that, what I defined to be climbrocks. (see
http://www.dav-karlsbad.de/klettergesteine-klettern-fuer-geologisch-interessierte/all-types-of-rock-and-some-geology-for-climbers).
Therefore it is essential, too, that the rocktype actually is climbed or at
least is of any other important relevance. Monzonite at first was not
included, as it is a special plutonite, mostly combined with granite and
syenite and not really the main part of a rock occurence, but a special
part of a pluton only. In systematics there also is a syenite-monzonite
group. Thus I thought it's not really climbed  respectively there are no
known sportclimbing routes and even in case of a possible single occurence
it might be tagged as granite or syenite. However, as of some forgotten
reasons, I found Joshua tree
https://www.thecrag.com/climbing/united-states/joshua-tree (and Alabama
hills and stone mountains) in the US and read some geological papers from
USGS.

Thus the occurences in the US (which I did not know before) really are
significant and there definitely are sportclimbing routes. Thus this
requirement for climbrock is fullfilled. I do not know Joshua tree, but it
seems to be a really huge rock and the main rock type indeed is monzonite,
what also is in existing written papers of National park and USGS. Thus, I
did not want to tag it "wrong" as syenite or granite but decided indeed to
add monzonite as a new climbrock in my list. Thats already done:
http://www.dav-karlsbad.de/wp-content/uploads/2017/05/climbrock-englisch.pdf

I already also asked Ulfi by chance to add it within the thecrag-rock tags
and as long as this tag is not existant, I just tagged Joshua tree as
plutonic only. Some more explanation here:
https://www.thecrag.com/climbing/test-area/area/1278538767

After all it was a request of myself to add monzonite within the plutonic
rock tags. Did anybody else ask for it in the meantime?


Best regards
Harald


Am Montag, 12. Juni 2017 schrieb Brendan Heywood :

**Comment by flugrost** [comment]
Sorry, don't know why 2771 is listed under 2784.
>
>
With respect to 2784 I do not think anything is missing and do not agree to
an additional tag. It's not really senseful, does not fit in used
systematics and would create some additional problems.

However, I listed arguments in a private discussion in thecrag and invited
you. Generally the arguments are free for any interested person, but I do
not want to discuss this in public.

Best regards
flugrost
