### ISSUE TITLE
Gym cpr flags missing from facet filters

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2786]
**What happened?**

https://dev.thecrag.com/ascents/has/gym-sport-cpr/by/jaka20/?sortby=rating,desc

* [ ] 'has' flags are missing:

![image](https://user-images.githubusercontent.com/187449/27010660-b98aae02-4eec-11e7-8d07-8a61a47d101d.png)

**What you expected:**

Flags in the url and the filter should be aligned

**Comment by scd** [comment]
fixed on simon's dev. Will make the release
