### ISSUE TITLE
webcover not shown in activity

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2788]
**What happened?**

set a webcover

**What you expected:**
see a entry in the activity stream like:

Nicky set a webcover for alto mijares

**Comment by brendanheywood** [comment]
+1 this was already on the task list in https://github.com/theCrag/website/issues/974#issuecomment-276641942

**Comment by scd** [comment]
Yup, I missed this in implementation. Whoops.

**Comment by brendanheywood** [comment]
@scd not critical for now, but I'd like to break photos out into their own stream group. They aren't really 'updates' (See https://github.com/theCrag/website/issues/2791). But webcovers definitely are an 'update', and I'd also like the stream event for the webcover to be bigger and different to the photos event. Just something to keep in mind when you get to this.

**Comment by scd** [comment]
This is done in simons dev. Note I have assigned 10 karma points.

![tc-webcover-stream-event](https://user-images.githubusercontent.com/373058/27323190-0308a6b2-55e4-11e7-80a5-b342792d4780.png)
