### ISSUE TITLE
change free solo back to lead solo

### ISSUE THREAD

**Issue by scd** [theCrag/website#2792]
Lead solo is more widely understood

**Comment by brendanheywood** [comment]
These mean different things and are distinct, we shouldn't be changing the semantics of any tick type? What was it, is it, and what should it be? And do we need to add a second one or is that already covered?

**Comment by scd** [comment]
It came from this document.

https://docs.google.com/spreadsheets/d/1HhDomfKxrARGdxMSAyJGQ0nywYLSWF5OShdsyMGLaLE/edit#gid=0

I think we discussed the change in a very cursory sense.
