### ISSUE TITLE
CPR Boulder Choosing V-scale in UIAA context even though climber has not climbed a V-scale boulder

### ISSUE THREAD

**Issue by scd** [theCrag/website#2795]
**What happened?**

The boulder CPR is presented in V-scale for the following account

https://www.thecrag.com/climber/anderlnought

The account is set to UIAA context, but no boulders have been done in V-scale

https://www.thecrag.com/ascents/has/boulder-cpr/by/anderlnought/?sortby=rating,desc

(please also provide urls and screen shots)

**What you expected:**

Preseneted if FR bouldering grade

**Comment by birgander2** [comment]
> For some reason the system thinks the main bouldering system for UIAA is the V-scale. My guess is that this is not correct.

No, that's wrong. However, there is probably an ambiguity: In UIAA (Germany) there are boulders graded FR (mostly) and boulders graded UIAA (sometimes). Anyway, I'm fine with both selections. But probably better is to let the user choose seperately for routes and boulders!?

**Comment by Mdemaillard** [comment]
Closed a few releases ago, as you can choose your preferred grade for sport, trad and bouldering
