### ISSUE TITLE
Allow location for banned / illegal crags, but make the status much more prominent

### ISSUE THREAD

**Issue by pmonks** [theCrag/website#2798]
Crags that are banned / illegal should be able to have their locations listed, since other information supported by TheCrag is insufficient to unambiguously identify them (and hence keep climbers away).

In parallel, the access status of banned / illegal should also be vastly more prominent than it is currently, so that anyone visiting the page for such a crag can have absolutely no doubt about its status.

While I'm not one to propose specific approaches, I would encourage consideration of a watermark-esque overlay covering the entire page, and saying (in very large font) something like **CLIMBING HERE IS BANNED / ILLEGAL**.

**Comment by scd** [comment]
I have done this on simon dev
