### ISSUE TITLE
Default tick types don't align with new gear style specific tick types

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2802]
**What happened?**

If I'm bouldering, the default tick type should be 'send', not tick:

![image](https://user-images.githubusercontent.com/187449/27182602-2407f070-521f-11e7-9ff4-5a2ca752714c.png)

I'm I climbing on trad it should be 'lead' not tick, etc etc

**What you expected:**

More or less the most common type of ascent should be the default

**Comment by scd** [comment]
this is hotfixed
