### ISSUE TITLE
When we do a new release the message should contain a summary of the release

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2803]
**What happened?**

The notice in the dashboard is a key piece of communication to our users so we need to make sure it's as useful as practical. It should clearly communicate whatever we need it to without them needing to do anything else so we get the message out as far and wide as possible. If there is other things we want them to do then there should be clear calls to action.

eg for each release notification it should contain a very basic 2 line summary for each release. This means that people know what to expect without needing to dig into the forum, and it also gives them a clear memory trigger to go back to the forum if they see something amiss (this step is extremely difficult at the moment).

The challenge is that we also want it to be translated but we cannot always get this done in time in all languages, and as we add more languages this will become harder. We do not want a lowest common denominator approach here: if you can read English then you should get a decent summary in English, but if you can read say french but there is no french translation then you should get either a generic "there has been a release" message, or the English message, or possible both. Either way we will link of to a forum which is probably going to be in English only anyway.

There is also some relation to this issue, the release forums are essentially invisible once you have dismissed the box and there is as far I can tell zero ways to navigate to it:
https://github.com/theCrag/website/issues/2732

They need to be easily discover-able again if you have dismissed the box but later find an issue and want to comment on the forum.

**What you expected:**

* [x] So what I'd like is for the release message to be translated into english, but if there is not an appropriate translation then it falls back to a generic message. Perhaps the easiest zero code way is to just cut and paste the generic strings into each language, and then if the translators have time they can refine it. But that is a bit of laborious effort, we should do this in code for free.

* [ ] Better simpler titles. We should keep the title itself short and succinct. eg this title is awkward:

![image](https://user-images.githubusercontent.com/187449/27206905-daa1bfce-527d-11e7-93ec-97315f61073f.png)

And it doesn't look good in the streams either. I think they should probably all have a similar title structure like:

"Release 55: Crag webcovers, new tick types (eg Greenpoint), CPR tweaks and more..."

* [ ] as a followup to this point, I cannot edit your post as a forum admin to try and fix that issue. But I just tested this on dev and editing my own first message does correct the title too, so I think we should go and fix that right now and set the format for the following release posts. I think it's worth even going back and tweaking all of them, there is only 4 so far.

* [x] Do we continue to maintain the release pages? The last few have not been generated correctly or at all eg: https://www.thecrag.com/release/54-post-cpr-mini-release

  It would make sense to me to cross link this page into the forum post for each new release for the full details. Or we can stop maintaining these pages and link directly to github? ie to this ugly link:

  https://github.com/theCrag/website/issues?utf8=%E2%9C%93&q=milestone%3A%22Release%2055%20-%20Greenpoint%2C%20CPR%20update%20and%20webcover%22%20sort%3Acomments-desc%20

* [ ] Also if the message says something like "hey profiles now get new feature X" then we should make an effort to add a personal link directly to that feature so they can check it out. Either a link to an example crag, or to their own profile with a hash anchor down to the particular bit we are talking about or whatever.

**Comment by rouletout** [comment]
+1 - good points, if it is that critical we can get them translated by the translation service...

**Comment by scd** [comment]
FYI I have hot fixed a link to the Release forum in the forums primary menu.

This makes me think that we should start to think about adding other forums to this menu, such as Gear forum.

**Comment by scd** [comment]
I have added the framework for custom component of the release message. The custom component comes from translations db, but if the local language is not found then it does not fallback to english, but rather returns empty string.

![tc-release-notice](https://user-images.githubusercontent.com/373058/27570011-516f445a-5b3e-11e7-8155-e657dd84fe0a.png)

**Comment by scd** [comment]
We should keep the releases pages up to date. They were broken because we did not have a due date for the release. The api interface relied on a due date so I have converted this to closed_at. Our workflow does not force us to have a due date for milestones, but I always close the day I release. 

The missing release pages should be back in after next release.

**Comment by scd** [comment]
I don't think it is that important to fix up the historical release forums and the rest of the tasks are recommendations for future releases so I think I can close this issue now.
