### ISSUE TITLE
search results should exclude nodes in the test tree

### ISSUE THREAD

**Issue by scd** [theCrag/website#2805]
https://www.thecrag.com/search?S=custer+state+park

**Comment by rouletout** [comment]
Search still lists "to be deleted" areas (see screenshot, search for Custer) as example

<img width="975" alt="screen shot 2017-10-22 at 17 11 18" src="https://user-images.githubusercontent.com/19162952/31867026-b7e9ec1a-b74d-11e7-9ea0-811b24af41ce.png">

**Comment by brendanheywood** [comment]
Done in last release
