### ISSUE TITLE
Welcome message still includes reference to app

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2810]
**What happened?**

https://www.thecrag.com/discussion/1221933111

![image](https://user-images.githubusercontent.com/187449/27536920-97cbd704-5ab4-11e7-935e-2a07c7debe4f.png)

**Comment by scd** [comment]
This is purely in the translations file. I have removed the line referencing the app for English, German and Itallian versions.

@rouletout could you please organise the correction to the Korean version

**Comment by brendanheywood** [comment]
fixed at some point
