### ISSUE TITLE
'with' autocomplete easily autoselected the top item by accident (ie yourself in ticking form)

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2811]
**What happened?**

I'm seeing a lot of ticks come though from people who have said they are 'with' themselves. This seemed odd but I've accidentally done it myself, if you click into the field and then move on it's very easy to select yourself.

* [ ] if you click into the field, and then tab out or click on the empty field again, then the top selection (ie you) get selected. This seems like a bug either in the widget or maybe in how we are using it

**What you expected:**

* [ ] click in, the top item should not be selected yet until you hover / click / arrow key etc it
* [ ] Click in, then out, and nothing should change.

**Comment by rouletout** [comment]
Solved in new ticking interface, closing
