### ISSUE TITLE
account profile page webcovers for current supporters

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2816]
**What happened?**

Splitting this off from https://github.com/theCrag/website/issues/974

**What you expected:**

If you are are a supporter then:
* [ ] on your profile page have a prompt to encourage people to add a web cover
* [ ] similar ui to crag web covers, go to photo, select webcover dropdown and choose 'my profile' then select a focus
* [ ] add a stream event

**Comment by brendanheywood** [comment]
Do we want to always have some metadata overlay, like the photographer / copyright? eg like on jakob's page?

https://www.thecrag.com/climber/jakobschubert

To me this is clutter which you can get on the photo detail page, I don't think we need it shown everywhere

**Comment by nicHoch** [comment]
+++1 ;-)

**Comment by lordyavin** [comment]
wanted +1

**Comment by brendanheywood** [comment]
@lordyavin as you are already sponsor, so send me the url of a photo uploaded to thecrag and I'll hard code yours in the mean time just like https://www.thecrag.com/climber/jakobschubert

**Comment by lordyavin** [comment]
No hurry. I've to check if there is any photo that is appropriate.

  Brendan Heywood <notifications@github.com> hat am 8. März 2018 um 12:26 geschrieben:
 
 
 @lordyavin as you are already sponsor, so send me the url of a photo uploaded to thecrag and I'll hard code yours in the mean time just like https://www.thecrag.com/climber/jakobschubert

**Comment by rouletout** [comment]
This will be part of the new profile page for all users, not supporters only, closing
