### ISSUE TITLE
Inbox numbers mismatch, unread messages when there are none showing

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2817]
**What happened?**

![image](https://user-images.githubusercontent.com/187449/27758004-278a2502-5e4e-11e7-9b52-a90591f8b8d5.png)

**Comment by nicHoch** [comment]
+1 had this to since a while but was to lazy to report

**Comment by scd** [comment]
I think this is now working

**Comment by lordyavin** [comment]
What does now mean? Is this released already?

**Comment by scd** [comment]
That section of code was recaptured a while ago
