### ISSUE TITLE
Forum message has "no content"

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2819]
**What happened?**
This phot: https://www.thecrag.com/photo/1344712617 had no description and teh forum message created on it had no content, only a click on the empty space opened the photo and wa the only way to know what was meant and going on.

Forum message: https://www.thecrag.com/discussion/1350577770/welcher-boulder-ist-das-denn-bitte-genauer-zuordnen#m1351168134

(please also provide urls and screen shots)

**What you expected:**
Some text, e.g. generic text liek, comment on this photo was made...

**Comment by rouletout** [comment]
Same thing again: https://www.thecrag.com/discussion/1426750302/chido#m
I have no clue what this is referring to and can't find it out. Even the click in empty space doesn't lead anywhere...

**Comment by brendanheywood** [comment]
Again:

![image](https://user-images.githubusercontent.com/187449/52998381-47b04e00-3477-11e9-876b-f4c5f2c9bf1f.png)

**Comment by brendanheywood** [comment]
I've pretty sure someone has made a forum post, and then changed their mind. They cannot delete the post so they edit the comment and reduce it to nothing and save.

We can now delete a whole post, so maybe this is redundant:

https://github.com/theCrag/website/issues/3035

If we see this again then we should detect if:
a) a comment was changes to nothing
b) and it is the first and only comment

then treat it exactly as a thread delete

**Comment by scd** [comment]
This was fixed coinicidently when fixing the public/private issue. Ready for release.

![screenshot from 2019-02-19 21-32-19](https://user-images.githubusercontent.com/373058/53008694-0bd4b300-348e-11e9-8ab2-5b7c4cc07785.png)
