### ISSUE TITLE
Simple button to prepare a photo for instagram

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2826]
**What happened?**

Photos shared to instragram should have a watermark of the new logo but don't

@rouletout both the cropping and the watermark we attempt to do automatically - but if you usually end up doing tight cropping or any rotation etc then we probably can't do this automatically. So I'll leave this up to you to decide if this is worth doing it or not. Worst case is you can crop and apply the logo manually for each post (and if so close this issue).

**Comment by rouletout** [comment]
Close for now - not worth the effort
