### ISSUE TITLE
Onsight solo Tick type

### ISSUE THREAD

**Issue by jedparkes** [theCrag/website#2835]
I know its a rare one but could you add Onsight solo to the Tick types ?

**Comment by brendanheywood** [comment]
I think you are the third to ask now :)

**Comment by lordyavin** [comment]
Wow, who is insane enough ;-) to onsight routes solo? We are talking about free solo, right?

**Comment by birgander2** [comment]
Quite common, only needs to be easy enough ;-) I think I never made a "redpoint" solo...

**Comment by brendanheywood** [comment]
+1 from @jaka4eva

**Comment by DaneEvans** [comment]
+1

Half my solos are onsight. No way I can be bothered doing all the sub 10s in an area if I have to rope up ...

**Comment by brendanheywood** [comment]
@scd the icon for this is ready to go, is this possible to sneak into this release as part of #1881 ?

![image](https://user-images.githubusercontent.com/187449/29262273-10f2150c-8117-11e7-9e6a-c2d0317951ba.png)

https://brendan.thecrag.com/tick/soloonsight?v=1

**Comment by brendanheywood** [comment]
yet another duplicate https://github.com/theCrag/website/issues/1320

**Comment by scd** [comment]
this is done on simons dev
