### ISSUE TITLE
Stream event of a target tick uses past tense

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2836]
**What happened?**
Ticked a route as target in the future but the stream event says I logged an ascent from the past.

![target_tick_event](https://user-images.githubusercontent.com/1528540/28071278-bf632c58-664f-11e7-83ee-825d0e3bae0e.png)

**What you expected:**
The stream says: "Kai added the route XY to his target list." Or something similar.

**Comment by Mdemaillard** [comment]
+1 These should become deprecated with the list function... but it is worth a quick correction until that features comes out

**Comment by Mdemaillard** [comment]
interestingly this event get it right for 4 of 6 ticks ? even if all 6 seems to be of type "mark".

https://www.thecrag.com/event/3177298326

![image](https://user-images.githubusercontent.com/60388146/78443577-f4985b00-7678-11ea-9604-f82c2aa4f8a3.png)

diggin into each ascent, 2 have no ascent date -> wrong wording
ex https://www.thecrag.com/ascent/3177301629
4 have ascent date = log date -> correct wording
ex https://www.thecrag.com/ascent/3177301656
