### ISSUE TITLE
Thumbor scaling algorithm for cropping produces smaller photos

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2837]
**What happened?**
I think we've only talked about this in emails and we decided it wasn't a big enough issue. However it is definitely a real issue in some cases and the new crag card has exposed them. eg:

https://dev.thecrag.com/climbing/australia/tasmania/hobart/favorites/by/brendanheywood

produces this card which has a very blurry image:

![image](https://user-images.githubusercontent.com/187449/28121708-4a62cdee-675f-11e7-901a-fb120ced84b0.png)

The problem is that this is the image url that was generated:
![image](https://user-images.githubusercontent.com/187449/28121739-62ee4334-675f-11e7-9361-7d9df02208e3.png)
https://static.thecrag.com/img/299x0:985x343/fit-in/300x150/37/90/3790fbcc06beda2a943df021ffa9d72126bb2014

Not only does is get blurred because of the scaling but the aspect ration is all distorted too.

**What you expected:**
This isn't a thumbor bug, it's our algorithm to make the thumbor url. I hand crafted this url and it's exactly 300x150 and sharp as a tack:
![image](https://user-images.githubusercontent.com/187449/28121935-11fee662-6760-11e7-9ad4-f6e30978d660.png)
https://static.thecrag.com/img/58x0:743x343/fit-in/300x150/37/90/3790fbcc06beda2a943df021ffa9d72126bb2014

I'm still ok if the image is off by a couple pixels here and there but something is clearly up. One thing I noticed is that the original image is only 800px wide, but the url we produced attempts to crop it from 299 to 985 px which is out of the bounds of the image.

**Comment by scd** [comment]
I had a similar bug just after the release. It ended up being a rotation
issue, which was easily corrected, when I found where it was. I will have a
look.

**Comment by scd** [comment]
Yes there was an edge error in the algorithm. Fixed and pushed.
