### ISSUE TITLE
Add Route facet filter for fa history which has unlinked text

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2840]
**What happened?**

I want to search a crag and find all routes which have text FA / FFA data and replace it with links. This is an incremental process and so I want to keep running it and working on the ever shrinking remainder of routes.

This is an enabler for the historical accouns (#1518) and a precursor to the batch history editing tool (#558)

**Comment by rouletout** [comment]
This is done using a script and available to admins
