### ISSUE TITLE
Convert popularity icon to svg

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2841]
**What happened?**

So it's crisp on mobile / retina. Not blurry like this:

![image](https://user-images.githubusercontent.com/187449/28201940-806ee5aa-68b6-11e7-9d14-38a70f3d63ec.png)

**What you expected:**

**Comment by brendanheywood** [comment]
Actually turns out this is a 1 liner in css

![image](https://user-images.githubusercontent.com/187449/28202073-1ae70cca-68b7-11e7-9a26-684020168ad6.png)

**Comment by scd** [comment]
+1

I wanted to look at your one liner so I pulled but did not find a svg mason template there as I would have expected. I did find the less file though

```
application/frontend/src/minor/popularity.less
```
