### ISSUE TITLE
Create a media pack article linking to our drop box media pack

### ISSUE THREAD

**Issue by scd** [theCrag/website#2842]
Dropbox public link to media pack:

https://www.dropbox.com/sh/1yvuclem8ogug2k/AAB_qxWqqkJEHPQRpfCAN8T7a?dl=0

**Comment by lordyavin** [comment]
Are you guys sure to make this public? Not everyone on the internet is a nice guy ;) The link must list rules how to use the images and state the copyright license explicitly.

**Comment by brendanheywood** [comment]
The link will have our guidelines we are working on that. This is business as usual, most companies make this public. If someone wants to be malicious they can rip our logo of in a variety of ways already and they would ignore any rules we published anyway. eg

https://en.facebookbrand.com/assets

**Comment by brendanheywood** [comment]
done ages ago
