### ISSUE TITLE
On profile page level of fa / ffa / set of the first ascent / development a person has done

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2843]
**What happened?**
This is the complementary feature to #2571 (which adds the list of developers to the area list view), this would add to a profile page the list of routes they developed, did the FA/FFA on or also maintained.

**What you expected:**
There is a soft dependency on getting the historical accounts (#1518)

We probably just want something similar to the 'notable ascents' table but derived from first ascent data. We'd only show a couple of routes but then we would deep link off to a page with more detail, possible the same page we build for (#2025)

**Comment by brendanheywood** [comment]
Just read this article about stackoverflows profile which has a 'reach' stats, ie the number of people you have reached via you good questions / answers. I like this concept translated into climbing and think its more useful than just 'I put up X routes', instead 'I put up Y quality routes which have made Z peoples day better'

https://blog.codinghorror.com/what-does-stack-overflow-want-to-be-when-it-grows-up/

**Comment by Mdemaillard** [comment]
One of the top searches is 'tom o'halloran climber' (who just got knocked out, but is probably Australia's best climber at the moment)

But his profile is essentially empty, but he has been with us for 10 years:

https://www.thecrag.com/climber/banga

I think there is opportunities to make the profile pages better for climbers like this who don't tick, but we do know something about them.

For instance we know that Tom'O has done 15 FA's:

https://www.thecrag.com/climbing/australia/routes/by/@banga/?sortby=grade,desc

**Comment by Mdemaillard** [comment]
as a first step, a "first ascents" link has now been added on the left menu of every profile, opening a search of routes with "user" in FFA/FA/Set history
Ex here from a community profile:
https://www.thecrag.com/climbing/world/routes/by/@dwoods/?sortby=grade,desc

**Comment by rouletout** [comment]
Link is on profile page, closing

**Comment by brendanheywood** [comment]
I think this could be improved slightly. The problem is when you look at a persons profile you don't have any indication of how many fa's they have done, you need to click on that new link to see.

The simplest change would just be to add that into the link like this:
![image](https://user-images.githubusercontent.com/187449/103470596-43218400-4dc8-11eb-8bc7-82450a4a4f23.png)

But I really think that this info is important enough to be given more detail on their profile directly. ie it could be a new side block very similar to the icons saying 'these are the list of the most popular or important routes that this person has done the FA of'. Many of these people are on thecrag but don't use theCrag for ticking and never will, so their profile is pretty empty.

For prolific developers like Neil or Lee I'd love to see a summary of the most popular routes which they have put up, and that would also work really well with the historical profiles.
