### ISSUE TITLE
Add automatic table of contents in articles and refactor with list view

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2847]
**What happened?**
Finishing off a refactor task from ages ago

**What you expected:**

* [x] have a standard table of contents template
* [x] have every linked header link back to itself with a nice hash hover marker
* [x] have all help articles use the table of contents template automatically so they are all consistent (also avoids issues with hashes changing and the links don't get changed at the same time)
* [ ] help articles should have sticky header OR offset in px should not apply when not sticky header
* [ ] fix up margin in articles
* [x] make sure the markdown heading create the same markup
* [x] convert Grade back to normal h2 / h3 and then auto link them

**Comment by scd** [comment]
@brendanheywood whenever possible I am trying to write the whole article in markdown now using the translation system.

Please make sure this works fine with the gym solution article (as an example):

https://www.thecrag.com/article/gymsolution

**Comment by brendanheywood** [comment]
This is even better. I have a heading template which will be used in multiple contexts to setup the anchors in the right way. The articles don't need to call it directly, we could post process the html produced from the markdown to add the extra heading markup or possibly this could be inside the markup processor itself.

Given that we disable headers in almost all places we use markdown, I think it's probably safe to just modify the markdown processes to spit out the full header html we want in the few cases were we do want headers. The only interesting bit is that we don't have clean ids / hash anchors so we will have the generate them. We could either do something automatic and based off the header text:

```
<h2>Some header</h2>
```
into
```
<div class="offset"><a id="some-header">
<h2><a href="#some-header">Some header</a></h2>
```

But this won't work if there are multiple headings with the same text which is easy in h3 / h4 nested headings. Or we can do some auto numbering system as long as we have a way to set the starting counter. Or perhaps there can just be a record of anchors so it won't duplicate them.

The main thing driving this for me is being able to easily deep link to any heading and have it reasonably permanent. The Grade article method uses lang keys and works well because it works in all languages. The hash derived from the text is very brittle for heading changes. And the number based system is brittle for document restructuring.

Do you have a preference or a better idea?

**Comment by brendanheywood** [comment]
Some long drawn out discussions around auto generating id's here:

https://talk.commonmark.org/t/feature-request-automatically-generated-ids-for-headers/115/16

https://en.wikipedia.org/wiki/Help:Section#Section_linking

The more I read I think I'm leaning towards auto gen based on the heading text. If the heading changes then it's possibly a sign the content has changed significantly and a deep link isn't perfectly valid any more anyway. You still get the main doc and will see the new table of contents.

**Comment by scd** [comment]
Spanner in the works. Translations.

The headers will be different for different languages. 

If it is just TOC then I don't think it matters. If we want to deep link from outside the page we really need clear and immutable ids.

I am leaning toward something like {#some-id}.

**Comment by brendanheywood** [comment]
I don't think translations is a show stopper as this won't matter once we properly sort the article urls. I'm still assuming this is the desirable long term end goal so we get all the different versions translated in google. Technically this isn't the only way, but if we keep a single url the we need to do some google hoop jumping to get this to be indexed.

Lets say we have the 'GymSolution' article. This label should be translated so in some other language it could 'FooFar'. Each will have it's own url and will have it's own unique set of internal ids:

```
https://www.thecrag.com/en/article/gymsolution#some-link-in-english
https://www.thecrag.com/xx/article/foobar#some-link-in-foo-bar
```
This url doesn't make as much sense as it mashes two languages together (and yes we need to translate the word 'article' too)
```
https://www.thecrag.com/kr/article/article-name-in-korean#some-link-in-english
```

As long as both sets of links are reasonably stable then this is fine. If someone is providing support in german they will probably post the german speaker the german support page.

**Comment by brendanheywood** [comment]
Ok this is pretty well done, example:

![image](https://user-images.githubusercontent.com/187449/28832498-f94f7b02-771f-11e7-96f6-56de3991eed8.png)

There was a very large amount of inconsistencies at multiple layers which I've ironed out now. This boils down to:

* All articles should just use a h2,h3,h4, regardless of html, markdown
* No content should ever use h1, this is only for the page title, if you use it then it messes up the document hierarchy
* If you are writing content in markdown then don't use # (h1) start with ## h2
* content doesn't need id's, these are generated automatically
* every heading gets magically links so it's easy to link to it, and back to the top
* a table of contents is generated only if there is > 3 headings in the article
* I've most numbers from headings

I've gone through every article and adjusted the headings to what they should be regardless of html or markdown or lang pack. They are all consistent now except for grades which I'll fix shortly.

https://dev.thecrag.com/article/Grades

I will also do a bit more work on the toc style. We need to consider pages like this too with massive tocs:

https://dev.thecrag.com/article/API

I don't think massive tocs is the problem, I think massive pages is the problem.

**Comment by brendanheywood** [comment]
Ok final polish and article fixups. There is still a lot of general weirdness with the article styles and the trialCSS stuff that is sometimes injected, but out of scope. We need to resolve that.

https://dev.thecrag.com/article/GymSolution

![image](https://user-images.githubusercontent.com/187449/28877564-1cba3bf2-77e0-11e7-9d63-677e6fdcdb8e.png)
