### ISSUE TITLE
No error message displayed when login or password is wrong

### ISSUE THREAD

**Issue by scd** [theCrag/website#2849]
**What happened?**

If somebody logs in with the wrong login or password then no error message is shown. This can be particularily frustrating if people think they have the right username/password.

**What you expected:**

We should show an error message.

**Comment by scd** [comment]
Fixed on simons dev

![tc-login-error](https://user-images.githubusercontent.com/373058/28303820-59c60922-6bd8-11e7-9de5-12f0fb5d1b53.png)

**Comment by brendanheywood** [comment]
Given that usernames are publicly used in the urls there is no security reason to make this message generic. It would be better if there was 2 messages for wrong username and wrong password

**Comment by scd** [comment]
If we are going to do this the messages should be "Username not in system" or "Username or password wrong".

We can not know for sure wither the username or password is wrong. For example there could be two registered accounts 'simon' and 'simondale'. If I use my simon password on simondale then what is wrong, the password or username?

There are other failure conditions as well, such as facebook login. I have a different message for this.

For now I am happy to leave it as it is.

**Comment by brendanheywood** [comment]
> If we are going to do this the messages should be "Username not in system" or "Username or password wrong".

+1
