### ISSUE TITLE
Date taken: 2034 instead of 1934

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2855]
**What happened?**
Submitted a historic picture under public domain taken 1934. Filled the "Date taken" field correctly but the photo record displays 2034 and the stream event says that picture will be taken in the future

https://www.thecrag.com/1373396253

**What you expected:**
Correct usage and display of the date.

**Comment by scd** [comment]
This one made me laugh :)

**Comment by lordyavin** [comment]
You are welcome :)

**Comment by lordyavin** [comment]
Some new examples, both taken 1927:
* https://www.thecrag.com/photo/2709602541
* https://www.thecrag.com/photo/2709602547

**Comment by lordyavin** [comment]
Why is this not fixed already? Isn't it a low hanging fruit?

**Comment by scd** [comment]
This is fixed now on prod. Note that this is a bug with a third party library which is used all over the place. We have a work around but each instance must be found individually so this is really painful. 

@lordyavin can I ask you to keep documenting this when you come across it. Please put `possible formatDate century bug: ...` in the title if you find another with similar characteristics. It will make triage quicker.

**Comment by scd** [comment]
Note that the links you provided were great and it made hunting this down fairly easy.
