### ISSUE TITLE
Wrong date in ascents

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2857]
**What happened?**
 If you order the world ascents by date the first three are 1000 years old, and then for most of the first page they are in the future!

https://www.thecrag.com/climbing/world/ascents/?sortby=when-climbed,desc

![screen shot 2017-07-23 at 21 18 55](https://user-images.githubusercontent.com/19304867/28502194-572a02ae-6fed-11e7-852e-0e7068753350.png)

**What you expected:**

**Comment by scd** [comment]
I don't know if we will ever fix dates like this in ascents as it is personal data. The future dates are a bit of an issue though, which seems like a bug

**Comment by brendanheywood** [comment]
The plot thickens:

https://www.thecrag.com/ascent/1022223603

* [ ] The ascent date is actually 2916-11-27 (2916 is only a single mis typed number from 2016 and the log date was the next day) - but is being shown and sorted as 1016, so need to fix the sorting / display to show the real data
* [ ] We should not accept future dates, which is already logged way way way back in issue #31

**Comment by rouletout** [comment]
The 1000 year old's are gone - the future date is a separate issue #31 - so closing this
