### ISSUE TITLE
No original image for photo anywhere

### ISSUE THREAD

**Issue by scd** [theCrag/website#2858]
**What happened?**

The following photo image is missing from the server

https://www.thecrag.com/photo/1011715407

The image is not in prod, static, backup or lan backup.

The image should be stored under the name

d2c4f6c02e38f78f8c851b2410c95c0dd22cedba

In the d2/c4 directory.

The directory exists but does not have any images in it.

There is a second photo record which refers to the same image

https://www.thecrag.com/photo/1011715272

Which could be a hint with what is going on

**Comment by nicHoch** [comment]
maybe another example the profile image of: https://www.thecrag.com/climber/toko

https://www.thecrag.com/photo/1283133315

**Comment by nicHoch** [comment]
another?:
https://www.thecrag.com/photo/1279181973

**Comment by scd** [comment]
There was a code deficiiency when an image was uploaded twice then removed from one of the uploads where the system removed the image even though there was still another photo referring to it. This has been fixed. 

I am going to keep this open for a while and if no other examples are found close later.

**Comment by Mdemaillard** [comment]
@scd , happy about the monitoring period ?

**Comment by scd** [comment]
Happy, closing
