### ISSUE TITLE
Change grade context / system in profile settings should be reflected in profile graphs and big stats

### ISSUE THREAD

**Issue by nclementel** [theCrag/website#2860]
**What happened?**
Changing the grade context in the profile settings has some issues:

If you "let the system decide" you get (in the CPR graphs) the most climbed context for sport/boulder/trad (in my case SA/FB/SA).

If you want to change it (in my case to FR/FB/FR):
- setting FR then boulder is defaulted to V scale
- if instead you force FB then sport/trad are in YDS

There is also an increase in range problem for the trad graph when changing context (this happened going form "let the system decide" to FR)

![screen shot 2017-07-24 at 11 10 07](https://user-images.githubusercontent.com/19304867/28516220-ba6241d8-7060-11e7-8bda-f4b89080dd43.png)

![screen shot 2017-07-24 at 09 39 21](https://user-images.githubusercontent.com/19304867/28516051-1d408fcc-7060-11e7-9261-c893fa129550.png)

* [ ] Also the grade pyramid is not affect by this at all, and should be converted to the best grade system for the context

**Comment by brendanheywood** [comment]
+1 from support email

**Comment by brendanheywood** [comment]
Duplicate here: https://github.com/theCrag/website/issues/3168 from @Telefonzelle

**What happened?**
When i choose a grade system at thecrag.com there is no change on my profile side. On my profile https://www.thecrag.com/climber/telefon I can see different grade systems. Besides UIAA, FB and Fr there is also a grade system with V0, V0+, V2 and so on. However,  I havn´t made a boulder in this grade system in the past.

**What you expected:**
Normally, I can choose for example FB, UIAA or FR grade system. Afterwards my collected routes should shown over timeline in the choosen grade. Furthermore I would like to know, why my "Boulder" Ascents (for example Tafelsteinkante 6A) are listed in "notable ascents" as Lead Ascents. I expect that Lead Ascents only contain Ascents of Sport and Traditional routes.

Thank you in advance,
Holger

**Comment by brendanheywood** [comment]
Another duplicate comment in https://github.com/theCrag/website/issues/2665#issuecomment-289427827

**Comment by brendanheywood** [comment]
And another https://github.com/theCrag/website/issues/2505#issuecomment-273476477

**Comment by brendanheywood** [comment]
This is partially done now, the profile setting is now correctly reflected in the new gear style based grade pyramids. Other parts of the profile ie cpr charts  will follow suit to be consistent.

**Comment by brendanheywood** [comment]
+1 from support, but to split this into finer grained per-style settings

**Comment by scd** [comment]
+1 from support

**Comment by Mdemaillard** [comment]
Update post Release 81 - Universal Grade Conversion update
- [x] grade pyrammids should follow profile setting (natural & artificial, all gear styles)
- [x] CPR charts should  follow profile setting (natural & artificial, all gear styles)
- [ ] Notable ascents should follow profile setting

**Comment by rouletout** [comment]
This is covered by Universal Grade Conversion, closing
