### ISSUE TITLE
Typo in tick list description for via ferrata

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2862]
**What happened?**

![image](https://user-images.githubusercontent.com/187449/28574718-18ff7ee0-7192-11e7-9755-05e632f96f46.png)

This isn't lang pack? assume in db somewhere and need translating?

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/77255990-14408400-6c74-11ea-9710-9ed19f4814f3.png)
Corrected in english, and translated in others (checked de, it, es)
