### ISSUE TITLE
Safari + iPhone, topos drawn upside down 

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2863]
** What happened ***

on iOS on mobile, using safari, creating a topo bottom up results in topo lines being inverted (top down). 

I've seen it before, but assumed that I must have screwed it up. This time I know I got it right, and placed the points of the routes from start to finish

You also can't access the menu to allow you to invert them later, I gave up and did it once I got back to a PC

(please also provide urls and screen shots)

**What you expected:**

The same process as occurs on desktop, you place the start point, then intermediate, then finish.

**Comment by brendanheywood** [comment]
thanks - Yeah I have seen this but never figured out what was causing it, I added the reverse option as a workaround.

**Comment by brendanheywood** [comment]
I saw this again and tweaked it, see also

https://www.thecrag.com/event/1417537293

**Comment by brendanheywood** [comment]
Another example

https://www.thecrag.com/event/1436083185

**Comment by brendanheywood** [comment]
Ahhh finally fixed this bug which has fixed a bunch of subtle bugs related to touch support :)
