### ISSUE TITLE
Add details of supporter benefits to help article

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2864]
**What happened?**

https://www.thecrag.com/article/donate

This page doesn't list the benefits. As we roll out new supporter only features we need to keep this page updated

* [ ] Bigger pdf's I have reduced the route count limit to 1000 and the number of topos to 50, vs 500
* [ ] instant karma

**Comment by Mdemaillard** [comment]
Can problably 

- [ ] link the Perk page on donate,
- [ ] update Perk as above

https://www.thecrag.com/en/article/perks

**Comment by rouletout** [comment]
The supporter benefit article is pending in our "article to do" - I close it here
