### ISSUE TITLE
Route has 6 stars!

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2866]
**What happened?**
This route has a 6 stars:
https://www.thecrag.com/climbing/australia/coles-bay/route/13646275
![image](https://user-images.githubusercontent.com/187449/28776768-77326e16-763b-11e7-995b-e51f5f801cfa.png)

**What you expected:**
Max of 3

**Comment by jedparkes** [comment]
just logged in to raise this issue but you bet me to it.

**Comment by rouletout** [comment]
has 3 now - closing
