### ISSUE TITLE
embedding video does not work in route descriptions

### ISSUE THREAD

**Issue by scd** [theCrag/website#2868]
**What happened?**

https://www.thecrag.com/climbing/germany/schwaebische-alb/donautal/route/249519696

**What you expected:**

I youtube link should emed the video. A little more thought maybe required here because this field goes to PDF, etc. 

See also #1678

**Comment by brendanheywood** [comment]
Video's shouldn't work in route descriptions precisely because of all the places they mess things up.

**Comment by brendanheywood** [comment]
I think we should close this as won't fix, it's more appropriate that a video link is put into either an ascent comment, or a forum about the route / crag, or at a stretch possibly in the history or desc field of the crag.

**Comment by brendanheywood** [comment]
fyi @lordyavin

**Comment by lordyavin** [comment]
I'm fine with not fixing this, but it should be mentioned in the help that embedding videos doesn't work for rout descriptions.

Maybe we need a list of external links per node. A categorization (Video, Articel, Topo, ...) of a link would make it easier to decide how to present it to the user in the context of different use cases (Web, PDF,...). Referencing a link (citation) may be useful for description.

**Comment by scd** [comment]
@lordyavin that is what the #1678 issue is about.

I am happy for this to close.
