### ISSUE TITLE
Alternative payment solutions for donation

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2869]
**What happened?**
Wanted to donate once again. But I don't own a credit card any more. 

**What you expected:**
Alternative payment solutions to donate. My preferred option would be PayPal or [SEPA](https://en.wikipedia.org/wiki/Single_Euro_Payments_Area) Direct Debit Scheme.

**Comment by lordyavin** [comment]
Should be possible in (almost) no time. Your payment provider supports the following stuff.

https://stripe.com/de/payments says:
> Payment methods
>
> Go beyond credit cards and support global payment methods, which you can activate from your  Dashboard.
> 
> * Bancontact
> * Giropay
> * iDEAL
> * SEPA Direct Debit
> * SOFORT
> * Alipay
> * WeChat Pay

**Comment by scd** [comment]
If we can do it through stripe then this is better. I will see if we can get something going outside our standard interface.

**Comment by scd** [comment]
https://stripe.com/docs/sources/sepa-debit

**Comment by lordyavin** [comment]
Still waiting to get this solved. Do you want my money? :wink:

**Comment by matozoid** [comment]
I would donate if I don't have to jump through all the credit card hoops. Paypal and SEPA are nice. Or set up a Patreon or so.

**Comment by scd** [comment]
We need your money, but we are focusing our severely limited Dev resources
on some really critical support and features.

I realise we will lose some potential money, but if money is the sole
prioritisation then I consult on something else which has nothing to do
with thecrag, which I have to do anyway to pay the family bills.

Fyi I looked into adding other payment methods but it is not a trivial
project. We will discuss patreon as an alternate, but I suspect integration
to thecrag accounts will be too much work.

Kai, last time you did a transfer to my pay pal account. Do you want to do
an out of band transfer again.

Note that as we get bigger the business case for adding payment methods
will start to stack up.

**Comment by Mdemaillard** [comment]
Paypal is setup, as well as bank details to make EFTs. Details on the Donate page. Closing
