### ISSUE TITLE
Make linkPhoto use src  make both work with responsive srcset

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2872]
**What happened?**
Splitting this task off from #2595

linkPhoto should be automatically using srcset. General thinking is regardless of whatever size you ask for, it will generate some fixed sizes that are smaller. If you request the same image at two slightly different sizes, the srcsets should nicely match up.

So lets say we have an original image 3000x2000:

If I ask for a 1500x1000 image then I should get:

1500x1000
1200x800
600x400
300x200

and if I ask for 1400x700 then I should get this which perfectly overlaps:
1200x800
600x400
300x200

The reason we want to the overlap is if I ask for different things on different pages, and I'm on a small screen so it's going to grab a smaller version, then I want it to preferentially use the existing cached smaller version.

So I think my logic is:
1) pick the largest of the 2 dimensions, make it 300px, and second one will be smaller. This forms the smallest set. 
2) double both dimensions and add it to the set. If we are bigger than the requested dimensions then stop
3) rinse and repeat

**Comment by scd** [comment]
This is mostly done, however it will not work in markdown because the srcset urls are converted to links downstream in the markdown. I need to refactor markdown logic so it does not do this.

**Comment by brendanheywood** [comment]
Should I leave this with you then?

**Comment by scd** [comment]
Yup.

**Comment by scd** [comment]
Closing as mostly done.
