### ISSUE TITLE
Rebuilding node URLs

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#2873]
Are the URLs for nodes rebuilt at some point? The URLs for nodes are generated when the node is created, but if there is a (spelling) mistake in the name and someone fixes it, the node URL stays the same. Example:

https://www.thecrag.com/climbing/germany/frankenjura/engelhardtsberg

The name in the URL is spelt with "dt". However, the correct spelling is just with "d". There are dozens of cases like this in Frankenjura alone.

**Comment by brendanheywood** [comment]
At the moment the url's are completely manual, and not tied directly to the title shown on the page. We have plans to completely automate this which is logged here:

https://github.com/theCrag/website/issues/1306

The UI to change these is currently admin only, and it easy to break it so the old url no longer works so it's not really in a state to roll out widely (ie why we want to automated it).

**Comment by brendanheywood** [comment]
Close as dup of #1306
