### ISSUE TITLE
generating topo pngs on brendan's new server is failing intermittently

### ISSUE THREAD

**Issue by scd** [theCrag/website#2876]
**What happened?**

https://brendan.thecrag.com/topo/119361966/png

works if apache has just been restarted but fails after you have browsed the site a bit

**Comment by Mdemaillard** [comment]
While the topo itself displays fine on all 3 server, the /png serves 2 different results:

Prod: Gives a PNG including the picture and the topo-graph
https://www.thecrag.com/topo/119361966/png

Sandpit or Brendan: Gives a PNG of the topo-grpah with grey background     (the topo displays fine)
![image](https://user-images.githubusercontent.com/60388146/77913026-e242a980-7293-11ea-9e3b-718ad3b3465b.png)

Is that issue / server still relevant ?

**Comment by scd** [comment]
I will be closing down the old dev server - brendan.thecrag.com as it's OS is old. Being replaced by nicky.thecrag.com

https://nicky.thecrag.com/topo/119361966/png

works fine.

I am closing this issue,
