### ISSUE TITLE
iphone mobile view, help menu doesn't appear on tap

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2877]
**What happened?**

![img_4987](https://user-images.githubusercontent.com/187449/29030677-45132fbc-7bcf-11e7-89f5-1a490ae77feb.PNG)

**What you expected:**

**Comment by scd** [comment]
What is the url just in case it is missing template data. There have been a couple of edge cases with missing template data

**Comment by brendanheywood** [comment]
Ah this is something I introduced and is only on dev. Unrelated to @rouletout issue

**Comment by brendanheywood** [comment]
Fixed regression
