### ISSUE TITLE
Offtopic Messages in Release Forum

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2878]
**What happened?**

Everybody can start a new thread in the Release Forum.

https://www.thecrag.com/forum/release

**What you expected:**

Relocate the current "false" one and make the "Create new" available for admins only.

**Comment by brendanheywood** [comment]
There is quite a backlog of important forum things we need to do, and if we did the main ones at the top of that list then this issue would probably no longer be an issue.

The two we need to sort is adding the UI to move a thread:
https://github.com/theCrag/website/issues/2441

And fixing the subscription model (including karma minimums for posting to big regions)
https://github.com/theCrag/website/issues/1365

**Comment by scd** [comment]
I think this is covered by other issues. I am closing

**Comment by lordyavin** [comment]
@scd are the other issues already referenced?

**Comment by scd** [comment]
In Brendan's post above
