### ISSUE TITLE
alternate order of the default webCover link

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2880]
**What happened?**

the main menu: phots > webCovers leads to the webCover facet result list.

the default order here is index,asc

if you see webcovers as the creme de la creme of phots. by visiting the webView page again and again for just a bit climbing picture porn the index order make no sense from my point of view.

**What you expected:**

the default order should be: `sortby=when,desc` : so the new ones first

**Comment by scd** [comment]
I have thought the same thing

**Comment by scd** [comment]
fixed in simon dev
