### ISSUE TITLE
CPR includes ascents from 'To Be Deleted' 

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2888]
**What happened?**
CPR includes outrageous ascent in the 'To Be Deleted' area
https://www.thecrag.com/climbing/world/ascents/has/trad-cpr+ascent-date/by/pumpensmear/?sortby=rating,desc

![image](https://user-images.githubusercontent.com/22091505/29486552-1ac4f072-852c-11e7-983c-d63799b03c6d.png)

(please also provide urls and screen shots)

**What you expected:**
these to no be included in the calculation of CPR values

**Comment by scd** [comment]
I have excluded this ascent from CPR.
