### ISSUE TITLE
Trad CPR not seeming to come from ascents

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2889]
**What happened?**

number 2 Worldwide (Elliot) has CPR = 4143 (5.14b)

https://www.thecrag.com/climbing/world/climbers/using-stat/trad-rating/

![image](https://user-images.githubusercontent.com/22091505/29486602-835674ac-852d-11e7-9498-a888a0bc9f74.png)

when you click on ascents, you see an OS 23 as the highest ranked, and the plot shows a CPR of 3028 (5.12a) 

https://www.thecrag.com/ascents/with-route-gear-style/trad/by/elliotvercoe/?sortby=rating,desc

![image](https://user-images.githubusercontent.com/22091505/29486616-b4079702-852d-11e7-9b43-0a9862261e3a.png)

(please also provide urls and screen shots)

**What you expected:**
These to have some bearing on each other,

**Comment by scd** [comment]
I recon something has gone wrong with this ascent:

https://www.thecrag.com/ascent/963411300

Where he has logged a grade 20 route as a grade 32.

If I tighten the area for the climber ranking to the parent area of the route above, you can see it is broken there too.

https://www.thecrag.com/climbing/australia/swan-river/area/12143071/climbers/using-stat/trad-rating/

The business rules is to use the minimum of ascent grade and route grade.

**Comment by Mdemaillard** [comment]
duplicate #2572
closing
