### ISSUE TITLE
only allow auto merge nodes with same node type  

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2896]
**What happened?**

I merged a sector (old z) with routes with an other sector (new z). Old Z has a route with the name "Ziegenrücken" and the name of "new z" is "Ziegenrücken" as well (a sector named for a route is not uncommon). All other routes where reparented fine but the Route "Ziegenrücken" was merged with the parent node "new z". In the end the route "Ziegenrücken" was lost.

it all happens here:

https://www.thecrag.com/climbing/switzerland/schartenfluh/area/1408550913

and the route of this ascent get lost:

https://www.thecrag.com/ascent/865439181

a similar merging instate of reparenting will happen if a annotation with the route name already exists.     

The summary of the merge process told "correctly": Ziegenrücken will be **merged** with Ziegenrücken

**What you expected:**

* the algorithm should not propose to merge a route with its parent.
* it only should propose merging of nodes with same type: 
  * route <-> route
  * area <-> area
  * annotation <-> annotation

**Comment by scd** [comment]
This is a pretty serious bug so I have also fixed it when looking at the other merge issue. Will be available from next release
