### ISSUE TITLE
New tick type for mixed routes done on pure sport

### ISSUE THREAD

**Issue by jaka4eva** [theCrag/website#2897]
I think it would be good to have a tick type where the climber leads a mixed route, but instead of using trad gear for added pro does it on pure sport?

**Comment by brendanheywood** [comment]
I'm not sure this has a great deal of value. If you lead a trad route on gear you can always just place half as much gear, or if it was a sport route you could just clip half the draws. In terms of ethics or purity I don't think many people would care, more people would be much more interested in the opposite (ie green point). If possible can you point us at some examples in the wild (like climbing dictionaries?) and if it's got an established name?

**Comment by brendanheywood** [comment]
On the flip side, if you only have sport gear then this type of ascent should probably count to your sport cpr instead of your trad cpr.

**Comment by scd** [comment]
I think it is of value for CPR purposes.

Let's sit on this for a while.

**Comment by birgander2** [comment]
'mixed' is anyway not a good term for this gear style, as it commonly refers to mixed rock / ice climbing, including its own grade system: https://en.wikipedia.org/wiki/Mixed_climbing

**Comment by rouletout** [comment]
The ascent gear style solves this in the new ticking interface, closing
