### ISSUE TITLE
Missing icon for green point ascents

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2898]
**What happened?**
Logged a green point ascent and missed a icon that is has a green point instead of the red one of the red point icon.

**What you expected:**
I similar icon to the one of red point ascents. 
![greenpoint](https://user-images.githubusercontent.com/1528540/29664932-0d030fc4-88d2-11e7-9eeb-540e8d9ab07c.png)

**Comment by scd** [comment]
This will be there next release. Monday

**Comment by lordyavin** [comment]
then assigned to that milestone ;)
