### ISSUE TITLE
Ascents facet 'climbed by' filter drops first character (assumes @ )

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2903]
**What happened?**
I tried searching, not logged in, and typed my tag 'deeno' and hit search
Result was an error message saying 'eeno' not found

![screenshot 2017-08-28 16 52 39](https://user-images.githubusercontent.com/22091505/29762482-05adabec-8c12-11e7-96ba-9225ca0054d4.png)

My guess is that it tries to strip the **@** and does so by removing whatever is the first character without checking. 

Worked fine when I did it properly as '@deeno' 
![screenshot 2017-08-28 16 52 57](https://user-images.githubusercontent.com/22091505/29762481-05ad4bde-8c12-11e7-8448-6a789fbc9a86.png)

**What you expected:**
The search to be able to handle people only writing the name and skipping the @ prefix.

**Comment by brendanheywood** [comment]
This might be a regression I caused recently when I converted some of these from text fields to select2 fields.

**Comment by brendanheywood** [comment]
This was fixed a while back
