### ISSUE TITLE
Make forum comment deeplink more obvious

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2905]
**What happened?**
I've seen this over the last few days, I think it's a recent change

Any forum message has had the second hyperlink replaced with '#' - I think it used to contain the Area/node it was associated with. 

Seems to now link to that message train, but the text could still be more useful.

![image](https://user-images.githubusercontent.com/22091505/29857298-5d1dccb0-8d9b-11e7-9e5b-8bc4258bc014.png)

**What you expected:**
A link to something useful, and text saying where it would lead

**Comment by brendanheywood** [comment]
The hash is new, there was nothing there before. This enables you to deep link to any forum message. It probably should be the '2 days ago' which is actually linked, or a 'chain' / 'link' icon - would that be more obvious?

**Comment by DaneEvans** [comment]
Weird, I could have sworn there was something else in that location in the past. 

So it's a permanent link? 
In that case a chain/link is probably the cleanest way of doing it IMO

**Comment by brendanheywood** [comment]
Cool, swapped to link icon and added a tooltip

![image](https://user-images.githubusercontent.com/187449/29861118-84c2cda0-8dab-11e7-9274-84e012676e4a.png)
