### ISSUE TITLE
API: api/index/detail/world gradeBand

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2907]
**What happened?**

adding the `gradeBand `with parameter to the API endpoint

`api/index/detail/world `

courses an error:

https://sandpit.thecrag.com/api/index/detail/982501716?key=xyz&withdata=NodeID,ParentID,NodeType,AreaType,TLC,GradeBand,Name,Webcover,Ghosts,Grade,RegisteredGrades,LastUpdated&abbr=0&stub=1&to=leaf&since=1502283318

**Comment by scd** [comment]
The GradeBand parameter is not defined as a valid with parameter. There is BandProfile and an AscentBandProfile.

Are you after the area statistic or the grade band for the route?

**Comment by nicHoch** [comment]
I would like to know the grade band of a route grade.

Am 2. September 2017 01:41:00 MESZ schrieb Simon Dale <notifications@github.com>:
>The GradeBand parameter is not defined as a valid with parameter. There
>is BandProfile and an AscentBandProfile.
>
>Are you after the area statistic or the grade band for the route?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/2907#issuecomment-326705156

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by scd** [comment]
hotfixed on sandpit. @nicHoch please use the tag 'Band'

**Comment by nicHoch** [comment]
test: ok
