### ISSUE TITLE
Add an emojis help article

### ISSUE THREAD

**Issue by scd** [theCrag/website#2910]
**What happened?**

Users want to know what emoji's they can use.

**What you expected:**

An emoji's help article

**Comment by scd** [comment]
https://www.thecrag.com/discussion/1427395989/emojis#m1427949393

**Comment by Mdemaillard** [comment]
there is some in here:
https://www.thecrag.com/en/article/formattingtext

**Comment by Mdemaillard** [comment]
https://www.webfx.com/tools/emoji-cheat-sheet/
link from brendan - originally used but not updated since

**Comment by rouletout** [comment]
This ca be closed, the link is the set of Emojis we use

**Comment by Mdemaillard** [comment]
hum, we will want to put the webx link in the help article then ? or is the help article listing the full list of what is implemented on thecrag ?

**Comment by rouletout** [comment]
Yes, the link in the article is the correct list
