### ISSUE TITLE
wrong page count in bulk edit

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2911]
When bulk editing, the top line said
Seite 3 von 111. Du hast von 111 Einträgen 30 geprüft und 27 aktualisiert [...]
It should be
Seite 3 von *8* (page 3 of 8)

Found here:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3AReturnURL=%2fclimbing%2fgermany%2fkatzensteingebiet&C%3ACallingURL=5212560&C%3APID=5212553&C%3AState=18535&D%3AN=13992445&D%3ARoleAlias=Climbing%20Information%20Distribution%20Role&D%3ACoordinator=1&D%3ATotalNodes=111&D%3APage=2&D%3APageSize=15&D%3ARefDepth=4&D%3AFieldGroup=area_all&D%3AFieldGroup=route_all&D%3AFieldGroup=annotation_all&D%3ANextPage=3&D%3AUpdatedNodes=27&D%3ANodeExpansion=descendants&D%3ADefaultContext=7516402&D%3AFieldSelection=1&D%3AReviewedNodes=30&P%3A0%3AInformationNetworkID=7539484&C%3AHideNavigation=1

**Comment by Mdemaillard** [comment]
listed URL does display correctly page number.
Verified working on current release

closing the issue.
