### ISSUE TITLE
Private / public ascent comments: Secrets, beta and safety (stream event)

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2912]
As mentioned in #500, I'd optionally like to tag comments of an ascent as:

1) private (vs public)
2) spoiler (contains beta)  (vs pure opinion "beautiful route")
3) safety relevant (e.g. "loose third bolt") (See #1865)

The first should be done only by the author of a comment, the latter two also by others.
This would allow filtering them to specific needs (refines "view ascents with beta")

**Comment by brendanheywood** [comment]
1) +1 for there to be a private vs public setting at an ascent level.

2) Spoilers not so sure about, I think it's a fair bet that if you are reading ascent comments you should expect to see beta.

3) Re safety stuff, I don't want this here as it will get lost. We have talked about a whole special system for this for flagging issues, dodgy bolts, and also for adding maintenance logs for when hardware has been installed or replaced. We would want to work with a couple cliff care groups or peak bodies to get this data model right. These guys record crazy amounts of stuff like the individual bolts, and make periodical assessments, and when they rebolt they record the temperature and brand of glue, and batch numbers etc. We want to get it all right

**Comment by brendanheywood** [comment]
+1 from support email

**Comment by brendanheywood** [comment]
Just fleshing this out a little more, I think the simplest and most useful data model we could introduce here is being able to specify if an ascent is private or public, or only visible to yourself. This is slightly different to @MelwinQ's original request but close enough.

This would behave exactly the same as setting the account to be private or public. You could think of the account setting as simply the default value for the ascent value, ie a private account could have some public ticks, and a public account could have some private ticks.

Facebook has the option of doing this at the post level, and you can set this in your accounts settings which is the default for new posts:
![image](https://user-images.githubusercontent.com/187449/55872318-08c58b80-5bd0-11e9-9372-539eb8ee06a3.png) ![image](https://user-images.githubusercontent.com/187449/55872398-39a5c080-5bd0-11e9-8782-16bffb0e5c92.png)

I think this makes the most UX sense at the event level for a batch of ascents, but under the hood really needs to be at the ascent level (or both?). The bit I'm less sure about is how we would handle changing the account setting, probably the option: either just making this for future tick events, or for changing all past ticking events.

**Comment by brendanheywood** [comment]
+1 via discussion

**Comment by quaestor** [comment]
I'd love to see the second point (spoilers) implemented in the markdown, actually. This should be much easier conceptually.

**Comment by rouletout** [comment]
See also https://github.com/theCrag/website/issues/1106

**Comment by rouletout** [comment]
+1 from supporter email

**Comment by scd** [comment]
Private comments available in new tick flow
