### ISSUE TITLE
Time Zones, Ticking Default Date wrong

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2913]
**What happened?**

Default date when ticking behaves stranegly or is wrong:
<img width="1140" alt="screen shot 2017-09-09 at 8 24 21 pm" src="https://user-images.githubusercontent.com/19162952/30306534-9762dbf4-972d-11e7-811e-541d88f77c7e.png">

My profile had Asia/Seoul as timezone, my computer has Pacific Time - when I log ascents in the evening (Pacific Time), the correct date is set as today’s default date.
Then I change my profile setting to America/Los Angeles and log an ascent. When the screen opens, it first shows tomorrow’s date, but after a second or so it changes to the correct one of today.

On a friend's computer with a profile timezone of Los Angeles and computer time on Pacific  the default date stays on tomorrow (see screenshot).

(please also provide urls and screen shots)

**What you expected:**

Computer time zone should be used to determine current date as default date.

**Comment by rouletout** [comment]
Being in the US and ticking in the evening always results in the next day chosen as default date for ticks. Can we fix that? This might also become an issue in contests.

**Comment by scd** [comment]
Ulf, you have set your local time to Los_Angeles. The system might not be using this for default tick dates.

![screenshot from 2018-05-16 10-38-01](https://user-images.githubusercontent.com/373058/40090519-96ebb300-58f5-11e8-9786-7b0f1ead9b25.png)

**Comment by rouletout** [comment]
That's the point - I set the timezone to where I am but it does not pick the correct date!

**Comment by rouletout** [comment]
What for is this time zone setting anyways? Shouldn't it just use the computer time and date?

**Comment by scd** [comment]
Whoops I deleted my comment as it was summarized at the top. I wanted to delete it before you read it.

I am not sure how hard this will be to fix and will not be able to assess until next week.

**Comment by scd** [comment]
I think the gap is just setting the default date when initially creating the ascent. But I agree there is potential to make things worse here. This is why I don't want to assess this until I have some free time next week.

Ascent date does not have any timezone information. 

Ulf, can I confirm that the ascent date is saves as it is set. In other words if you correct the default date then it will be stored as you saved it. If this is not the case then there is possibly a major issue.

So the current effect on the tournaments would be if somebody in the US saves an ascent on the last day of the month without correcting the default date then it will be assigned to the next month and therefore miss the tournament. If they don't correct the ascent before we finalise the tournament then they will miss out on some points.

**Comment by rouletout** [comment]
That's correct - it saves as set but in the future if I don't change it manually. I alos think we shouldn't overcomplicate or think of edge cases. If I fly half way round the world and tick I'm ok to check that the date is right but if I tick on the day I climbed or life at the cliff I don't want to (and I don't) check the date for correctness - I assume it is today in wahtever timezone.

**Comment by brendanheywood** [comment]
Duplicate in https://github.com/theCrag/website/issues/1121 (will keep both open)

**Comment by rouletout** [comment]
+1 - this is still wrong when ticking in the US in the evening

**Comment by rouletout** [comment]
+1 the date is wrong every evening when I tick routes here in Mexico (Central Time)

**Comment by rouletout** [comment]
+1 this is really a nuissance if you live in the Americas and you tick when you come home from climbing, the date is ALWAYS wrong. The system actually seems to know which date it is but somehow makes it the next day (see screenshot, the 18th of April is marked but it chooses to putthe 19th for my ascents)

<img width="540" alt="Screenshot 2020-04-18 at 18 05 28" src="https://user-images.githubusercontent.com/19162952/79674443-87b8b100-81a0-11ea-9827-4f3aba93cdc4.png">

**Comment by scd** [comment]
I thought our technical implementation was based on the timezone of the crag you ticked in. This cannot always be worked out. For the virtual crag this is obviously just rubbish.

**Comment by rouletout** [comment]
@scd this has nothing to do with virtual or not, it is the same if i tick a local crag here, it is ALWAYS wrong.

**Comment by scd** [comment]
Then there is probably a bug. Can you please redo the example with something other than virtual because that will definitely be wrong.

**Comment by rouletout** [comment]
Here you go:

<img width="1103" alt="Screenshot 2020-04-18 at 18 44 35" src="https://user-images.githubusercontent.com/19162952/79676586-c2bce380-81a4-11ea-99f8-13cf92df9c21.png">

this time it is from my local crag: https://www.thecrag.com/climbing/belize/area/3149753298

For the record, it is 18-Apr-2020, 18:46 local time

**Comment by lordyavin** [comment]
IMHO all user interfaces need to display date and time based on the user's local time. Internally thecrag should store utc + time shift (time zone) as users travel the time zone may be determined based on the crags location. If there is no location info use the user's country. Insufficient/imprecise for Australia, the United states and other big countries.

**Comment by brendanheywood** [comment]
The analysis I did in https://github.com/theCrag/website/issues/2913#issuecomment-391330628 is still valid, but this was never been implemented which is why this issue is still open.

**Comment by lordyavin** [comment]
I agree with the analysis of @brendanheywood.

**Comment by rouletout** [comment]
+1 from support

**Comment by lordyavin** [comment]
+1 because correct timezone handling is a must for an international site.

**Comment by scd** [comment]
I think this should be ok in the new tick flow
