### ISSUE TITLE
Stream Events may not cover all "new routes"

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2914]
**What happened?**

this event was created by an batch import for around 750 routes but only 350 where mentioned.

https://www.thecrag.com/event/1434899787

**What you expected:**

all in

**Comment by scd** [comment]
For example this route thinks it should have been in the stream:

https://www.thecrag.com/climbing/united-states/massacre-rocks-state-park/route/1435039935

Hint: When debugging look for a LIMIT in the SQL, which would explain this behavior

**Comment by scd** [comment]
This is the group_concat_max_len mysql variable hitting it's maximum size. 

Fixed by 
```
SET GLOBAL group_concat_max_len=1048576;
```

And restarting apache.

Weirdly it does not seem to be fixed when setting in cnf file.

**Comment by nicHoch** [comment]
https://www.thecrag.com/event/1525546377
working well now!
