### ISSUE TITLE
Dup alternate name cannot be deleted

### ISSUE THREAD

**Issue by scd** [theCrag/website#2924]
**What happened?**

Editing the following route to try and remove a duplicate alternate name causes an error

https://www.thecrag.com/climbing/united-states/bighorn-mountains/route/960754581

![screenshot from 2017-10-07 09-18-17](https://user-images.githubusercontent.com/373058/31300682-b4672f08-ab40-11e7-8fe7-20182acf7d4c.png)
![screenshot from 2017-10-07 09-22-45](https://user-images.githubusercontent.com/373058/31300740-1d30cc56-ab41-11e7-8b4a-7949fdf62850.png)

**What you expected:**

We should not have alternate name duped in the system. If we do then we should be able to delete it

**Comment by Mdemaillard** [comment]
I was able to delete the dup alternate name.
Closing.
