### ISSUE TITLE
Routes with FR_ALT grades do not show up correctly in stream

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2925]
**What happened?**
Routes with FR_ALT grades do not show up correctly in stream. See below:

![example](https://user-images.githubusercontent.com/6367190/31316438-9aa70014-ac2d-11e7-814b-28924c273337.jpg)

I think I opened this issue already once (years ago), but I couldn't find it anymore.

https://www.thecrag.com/event/1464119406

**What you expected:**
The coloured boxes with the grade.

**Comment by brendanheywood** [comment]
Still an issue, missing template data

![image](https://user-images.githubusercontent.com/187449/47467395-e7e7c480-d841-11e8-9648-0c21f037a24e.png)

**Comment by Mdemaillard** [comment]
FR_ALT is not listed here
https://www.thecrag.com/en/article/gradesonthecrag
The routes in question seems in FR, and do display properly
![image](https://user-images.githubusercontent.com/60388146/78295731-e2110b00-752c-11ea-87b9-466b23571954.png) 
![image](https://user-images.githubusercontent.com/60388146/78295767-ef2dfa00-752c-11ea-9a50-3c5ff6507f00.png)
![image](https://user-images.githubusercontent.com/60388146/78295808-ff45d980-752c-11ea-8326-fcd429f8bf52.png)


Is FR_ALT still a thing ?

**Comment by scd** [comment]
Yes it is a thing. Go to the grade converter and type in 7 with French context. Some grading systems have alternate ways of describing grades which overlap with the standard way. Where this happens we describe an Alt system. Other examples are 5.12 vs 5.12a.

**Comment by Mdemaillard** [comment]
OK got it. Thanks for the pointer.
Still, just tested it in sandpit, the display is correct for a route with override FR context
![image](https://user-images.githubusercontent.com/60388146/78347493-dceda380-75a0-11ea-8f74-489b9ebda4c5.png)
Closing.
