### ISSUE TITLE
Deleting or disabling a photo should remove webcovers

### ISSUE THREAD

**Issue by scd** [theCrag/website#2926]
**What happened?**

The following web cover

https://www.thecrag.com/climbing/greece/kalymnos/arginonda

Links to a deleted photo

https://www.thecrag.com/photo/1465265784

(please also provide urls and screen shots)

**What you expected:**

**Comment by scd** [comment]
I have fixed the bad data, but not the bug

**Comment by brendanheywood** [comment]
Or should we turn this around and say, if a photo is used elsewhere then it cannot be deleted? Or perhaps it can be unlinked from the original uploader but just becomes an orphaned image but still active?

**Comment by scd** [comment]
Cannot be deleted is probably the path of least resistance.

**Comment by quaestor** [comment]
@scd This happened here as well: https://www.thecrag.com/climbing/germany/frankenjura/wurgau

**Comment by scd** [comment]
I have fixed the data for this one and in simon's dev disabled photo deletion button if the photo is used in a webcover
