### ISSUE TITLE
Tick icons no longer appearing in PDF exports

### ISSUE THREAD

**Issue by georgebadelphi** [theCrag/website#2929]
Exported a PDF.
None of the icons (mark, sent, dab, etc) are appearing for the routes.
Guessing the PDF export code wasn't updated with all of the new icons?

**Comment by brendanheywood** [comment]
thanks @georgebadelphi, yep always forget something :)

**Comment by lordyavin** [comment]
+100 ;-)

**Comment by brendanheywood** [comment]
This is fixed for next release
