### ISSUE TITLE
oembed resize bug on hover

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2930]
**What happened?**

1) Go here:

http://www.canberraclimbing.org.au/~canberra/climbing-guides/booroomba-rocks/

2) Scroll to the very bottom
3) hover over the 'naked chef'
4) it's triggered heaps of events which resize the iframe 1 pixel large each time. Not only does it keep stretching out the iframe but it's also consuming a lot of cpu grinding reworking the dom for no reason

**What you expected:**
Would be good to sort the root cause, but worst case just let it resize the first time and then disable the re-resizing

**Comment by Mdemaillard** [comment]
here is the updated link. https://canberraclimbing.org.au/climbing-guides/booroomba-rocks/
I don't see anything wrong with the over frame.
![image](https://user-images.githubusercontent.com/60388146/77910844-1caa4780-7290-11ea-9525-ba88ed03ed25.png)

Assumed closed.
