### ISSUE TITLE
oembed cleanup

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2932]
**What happened?**
ust saw a bunch of tiny issues:
* [x] old logo
* [x] white text on white so invisible
* [x] no GA stats

**What you expected:**

**Comment by brendanheywood** [comment]
Done, and GA is hotfixed

![image](https://user-images.githubusercontent.com/187449/31849577-2d18029c-b690-11e7-9046-6cc6a691585f.png)

**Comment by rouletout** [comment]
The Wordpress embed does not exists at the link given: https://www.thecrag.com/static/wp/wp-thecrag-oembed.zip
