### ISSUE TITLE
Cannot fix gym's route colour

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2933]
**What happened?**

I added a new gym route, but accidently with a wrong colour (yellow in my case). But in the "edit route" dialog, no field is available to manually enter the colour, only a selection of pre-defined colours. However, I need another one (fuchsia in my case). 

**What you expected:**

The same name / hexcode colour field as in "add route" to be present.

**Comment by scd** [comment]
Which gym? Please provide URL so we can look into this.

**Comment by brendanheywood** [comment]
Rather than allow random hex code I think it would be better to:

* [ ] combine the add and edit process so they are the same form (or refactor these somehow)
* [ ] add more color swatches

**Comment by birgander2** [comment]
Sorry: [URL here](https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?select=0;R=%2Fclimbing%2Fgermany%2Foberbayern%2Farea%2F612829032;C%3APushReturnURL=%2Fclimbing%2Fgermany%2Foberbayern%2Farea%2F612829032;C%3AState=18538;D%3AFieldSelection=0;D%3AFieldGroup=area_all;D%3AFieldGroup=route_all;D%3AFieldGroup=annotation_all;C%3AHideNavigation=1;D%3AN=1480527675&P%3A0%3AInformationNetworkID=7539484). Should be fuchsia, not purple.

Yes, add and edit dialog should look similar. At least to have the possibility for hex code is good imho, it gives a skilled user more flexibility.

**Comment by birgander2** [comment]
Probably fixed with the new release!

However, one slightly off-topic question: I cannot open new issues here anymore, the field "Submit new issue" is grayed out. On top there is now a box "Before you open an issue please review the contributing guidelines for this repository", with a link to the file "website/contributing"!?? I'm confused.

**Comment by brendanheywood** [comment]
@birgander2 re github issues nothing has changed can you send a screen of what you see including the whole browser window?

**Comment by birgander2** [comment]
@brendanheywood Sorry, my error. After some googling, this is a new feature of github, the button stays disabled until the issue title is filled out.

I'm closing this, seems to be consistent now.
