### ISSUE TITLE
Add oembed auto discover discovery

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2934]
**What happened?**
Paste a url in a supporting service like slack, 

Tasks
* [ ] have a global function or list somewhere where we can track in code all the places which do support embeds, and if so what types of embed (ie summary or full or ?)
* [ ] make the header auto spit this out

**What you expected:**
* [ ] get a full oembed in slack without any admin side config

**Comment by scd** [comment]
Closing for now as I do not plan to work on this.
