### ISSUE TITLE
Typo: "ciruit"

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#2937]
**What happened?**

On index pages, the 'action' menu says 'create ciruit'

**What you expected:**

'circuit'

**Comment by lordyavin** [comment]
Tried to fix this issue via the tanslation system but I can't change the en setting. See template.action-area.create-circuit.

**Comment by scd** [comment]
cannot update english at the moment. It is on our list. I thought it would
be easy, but english is handled in a different way which makes it more
difficult to save via the translations system

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by brendanheywood** [comment]
I've fixed this for next release
