### ISSUE TITLE
Crash with a photo facet to a private account

### ISSUE THREAD

**Issue by scd** [theCrag/website#2939]
**What happened?**

Crash (503 Error) with photo facet to a private account

https://www.thecrag.com/photos/uploaded-by/michael_f

**What you expected:**

* [ ] never a 503, worst case a page saying 'not found' which could be a 404 but styled
* [ ] if you are that user, or a friend then it should work

**Comment by brendanheywood** [comment]
This is now not a 503, but it returns the world photos. It probably makes more sense to say 'nope can't see that because it's private' instead of misleadingly showing other people photos.

**Comment by lordyavin** [comment]
Just got that error for 
* https://www.thecrag.com/photos/uploaded-by/captainhook
* https://www.thecrag.com/photos/uploaded-by/quaestor

Looks like a generic issue.

**Comment by scd** [comment]
Hot fixed.

**Comment by scd** [comment]
Hot fixed the generic error.

**Comment by rouletout** [comment]
So closing
