### ISSUE TITLE
Pitch who to inherit and interact with ascent 'who' (and also batch tick 'who')

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2940]
**What happened?**

Split off from https://github.com/theCrag/website/issues/1313

* [ ] When ticking with pitches there is no relation with the 'lead by' and 'mentioned'. If you mention someone in the 'lead by' then they should auto be added to the 'with' box at the route level.

![image](https://user-images.githubusercontent.com/187449/32220875-6d98a2dc-be87-11e7-8ec1-624a135f8a6e.png)

* [x] I was thinking maybe making the 'lead by' dropdown show a new section just on this page "with" which just merges in those who are already either in 'with' field so it's faster to add the same person again

**Comment by scd** [comment]
I should just update with field in the ascent log. This should then come through automatically.

**Comment by brendanheywood** [comment]
Yes the first checkbox needs to happen server side either way, but this in the second box is more focused on making the UI much quicker to use so you can just do it all with 1 click instead of typing anything. It's fine polish and not urgent.

**Comment by brendanheywood** [comment]
@scd I've now done this. It's a generic solition which links any two select2 instances, you link them via:

data-inheritwith="D:Who-13344307"

Now if you add something to the pitches select2, then it's also pushed into the 'with' select, and if you open up the pitch selector search it will show a new "with" group:

![image](https://user-images.githubusercontent.com/187449/32356238-d31ac5ca-c087-11e7-9d2e-5443a1881ba7.png)

**Comment by brendanheywood** [comment]
btw I'm happy to leave it as is so the top level with's are only populated via js, but it can't hurt for you to also add the service side double check. An edge case is that you can add people in the pitches and then manually remove them from the top with.
