### ISSUE TITLE
Include 'send' (boulder tick) as a colour on ascent by tick type

### ISSUE THREAD

**Issue by jaka4eva** [theCrag/website#2942]
**What happened?**
Boulder ticks are counted as 'other' in ascents by tick type

https://www.thecrag.com/climber/brendanheywood

![image](https://user-images.githubusercontent.com/187449/32327591-284b06b6-c02b-11e7-84c7-7ea86b67c261.png)

**What you expected:**
That boulder ticks (sends) would be in a colour within the legend (as in a pinkpoint is a pink band) instead of being labelled 'other' and coloured accordingly

**Comment by brendanheywood** [comment]
fyi the grade pyramids will be re-done and use the same color scheme as the CPR timelines, eg Send will be red

**Comment by brendanheywood** [comment]
redundant / done
