### ISSUE TITLE
Grade cannot be updated

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2945]
**What happened?**

This [Route](https://www.thecrag.com/climbing/italy/finale-ligure/grotta-dell-edera/route/1291594659) shows a grade "6a to 6b", but should be "6b". When trying to edit it, only 6b is shown. Updating the grade doesn't work.

Note: This might be a result of merging the parent crag (existing twice at different nodes). However, no problem with other routes with diverging grades...

**What you expected:**

That the grade can be updated.

**Comment by lordyavin** [comment]
The community registered grade is 6b (by [Vanessa](https://www.thecrag.com/climber/vwills)). [Daniel](https://www.thecrag.com/climber/daniels) added his opinion that it is a 6a. So the system says the grade is between 6a and 6b. If you want to see just the 6b, then we have to delete the contribution of Daniel.

**Comment by lordyavin** [comment]
Good question

**Comment by scd** [comment]
There is a bug somewhere with two assigned grades. I have removed and re-added.

Note that the assigned/registered grades of a route can be independent of user and publisher contributions.
