### ISSUE TITLE
Mobile, Help menu not useable

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2946]
**What happened?**

On mobile (screenshot from iOS) the help menu stays in the right corner and is hard to read, also, the lower hierarchies of the menu are not visible
![img_2160](https://user-images.githubusercontent.com/19162952/32502708-7ae9a3d8-c3a9-11e7-961e-dd8c31499bcd.PNG)

(please also provide urls and screen shots)

**What you expected:**

Same behaviour as for desktop - access to help on mobile

**Comment by brendanheywood** [comment]
redundant now / wont fix in new design
