### ISSUE TITLE
Software error: DBD::mysql::st execute failed

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2950]
Updated the FFA and saved. Got the following error:

https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?select=0;R=%2Fclimbing%2Fgermany%2Ffrankenjura%2Fschuttersmuhler-wand%2Froute%2F17823727;C%3APushReturnURL=%2Fclimbing%2Fgermany%2Ffrankenjura%2Fschuttersmuhler-wand%2Froute%2F17823727;C%3AState=18538;D%3AFieldSelection=0;D%3AFieldGroup=area_all;D%3AFieldGroup=route_all;D%3AFieldGroup=annotation_all;C%3AHideNavigation=1;D%3AN=17823727&P%3A0%3AInformationNetworkID=7539484

>Software error:
>
>DBD::mysql::st execute failed: Deadlock found when trying to get lock; try restarting transaction at /opt/CIDS/perllib/BSIS/Db.pm line 1228.
>
>For help, please send mail to the webmaster (scd@thecrag.com), giving this error message and the time and date of the error.

**Comment by scd** [comment]
Which route? Is there still a problem with the route or updating? 

This is a general failure case which will be very involved to fix so unless it is still unresolved I probably cannot do anything.

**Comment by lordyavin** [comment]
Sorry, don't remember which route it was. I sent the request a second time and it worked. Is this some sort of race condition that happened? I think the DB layer should never run into such a situation. I suppose that this is hard to repeat but I thought you should know.

BTW: Is it good to display such a messages to users? Wouldn't it be better to have a special error page that hides the (implementation) details from the public and provides a button that sends a report?

**Comment by scd** [comment]
Most of the failures now go to a dedicated failure page. We have not yet captured all the edge cases.

**Comment by lordyavin** [comment]
Houston we have a problem.

**Comment by rouletout** [comment]
Closing based on comments
