### ISSUE TITLE
How to manage topos when a gym changes a subset of routes on the topo

### ISSUE THREAD

**Issue by scd** [theCrag/website#2953]
**What happened?**

Some gyms have a policy of of changing particular colors on a wall when route setting. For example a bouldering gym may change yellow climbs one week and green climbs the next. 

The bouldering wall is changed every week, but each change 90% of the routes remain the same.

Every change will require the topo be updated. However we really don't want to have to redraw the unchanged routes every week. We will need a new photo because the holds have changed.

My current thoughts are that this should be a fairly controlled environment so if you take the photo from the same place each time it should be fairly similar in dimensions. If we then added a UI feature to swap a photo in a topo we would get the new topo without having to redraw and routes. If the dimensions were significantly off then you may have the lines a little.

Does anybody have better ideas?

**Comment by scd** [comment]
I am going to close this because we don't really want processes with topos changing all the time. In otherwords we should not really be doing topos for gyms.

**Comment by brendanheywood** [comment]
> In otherwords we should not really be doing topos for gyms.

Just clarifying for posterity, we do want room and feature topos, just probably not route or boulder problem topos

**Comment by scd** [comment]
Yes the test is rapidly changing topos are to combersome to manage
