### ISSUE TITLE
Notable ascents rework on profile page

### ISSUE THREAD

**Issue by scd** [theCrag/website#2954]
We have got logs of separate issues around notable ascents. This is the master issue.

A lot has changed on the system since the this table was put together. It would be good to know what is now important. When I look at the table it does three things.
 - [ ] Tells me my hardest ascent for a particular tick type (may be rolled up).
 - [ ] Tells me how many ascents and a general breakdown of difficulty for a particular tick type
 - [ ] Tells me where I have been climbing the most.

What has changed:
 - [ ] We are focusing on three gear styles
 - [ ] We now know the relative difficulty of various tick types via CPR so we can assess what is notable
 - [ ] Rollup tick types are becoming less relevant given that CPR is assigned based on specific tick types
 - [ ] We have assessed effective gear styles (eg pink point trad is effectively a sport)

## Solution options

Make the table based on our 5 CPR types (Trad, Sport, Boulder, Gym Sport, Gym Boulder) and show one of them, allowing selection of the others.

Each type should be handled as an aggregate functions and embedded as it is for the CPR curve.

Use CPR ascent rating and show the top rated ascents.

I think we should keep area in the graph for each of the CPR types. This will tell somebody where I boulder, where I go to the gym the most, etc. Maybe have it as a config flag to show areas, and show the two most notable ascents from the area. Because it will be an aggregate we could do Simon's notable trad ascents in Arapiles as it's own notable ascents table.

One thing that is missing is how many ascents I have done. But that is in the ascents by tick type.

## Existing issues

 #1685 
 #2670 
 #2722 
 #2902 
 #2952

**Comment by brendanheywood** [comment]
done
