### ISSUE TITLE
Improve the workflow for pitch logging, in particular if you just want to tick the first pitch

### ISSUE THREAD

**Issue by scd** [theCrag/website#2955]
This has been branched off from issue #1698 

 - [ ] Make the UI more obvious how to use multipitch feature
 - [ ] Make it simpler to tick just pitch one
 - [ ] Make sure logging ascents is still mobile responsive

**Comment by dnnr** [comment]
Small suggestion for this: if *log pitch info* is enabled, shouldn't the grade dropdown at the top be disabled and automatically set based on the hardest pitch?
Maybe I got that entirely wrong, but I was confused by the seemingly redundant input fields. Other than that, the UI is already pretty okay in my opinion.

**Comment by scd** [comment]
I started implementing this a while ago but there are complexities.

The underlying issue is that overall grade is dependant on tick type. If you seconded the hardest pitch then but onsighted an easier pitch then we should probably log the onsight of the easier grade as the overall grade and tick type.

We can work out what is the `best` pitch (combo of grade and tick type) for the overall tick by using CPR, which is a fairly scientific way of establishing the best pitch.

There is a fair bit of work and I am not sure the community is ready for us to force this kind of change. So I am now watching to see how people are logging multipitches.

It seems as thought the major process is to create a generic tick then log the explicit tick types for each pitch. This is definitely not what I want as we make assessments on the overall tick type. In otherwords this provides evidence that we should at least default to `best` pitch tick type and grade for the overall ascent.

**Comment by lordyavin** [comment]
+1

**Comment by scd** [comment]
This is fixed in the new tick flow
