### ISSUE TITLE
Linking photos as admin

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#2957]
Having admin permissions to a crag, I would expect I'd also be able to correct the linking of photos. Apparently, this is not the case. This would make sense, though.
Instead, when clicking a photo, I get a drowdown for selecting its priority for WebCover.  If this is intended, it would benefit from some expanation.

**Comment by scd** [comment]
Two separate concepts. 

Currently you can only relink your own photos. This is a functional gap, which we will cover once we have a node selector widget. 

We covers are the images that are shown in the crag header.

**Comment by brendanheywood** [comment]
thanks @MelwinQ - I will close this as a duplicate of https://github.com/theCrag/website/issues/1124

If you have more comments or feedback please add it over there
