### ISSUE TITLE
oembed failing for youtube

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2958]
**What happened?**

oembeds in articles on brendan are failing:

https://brendan.thecrag.com/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DfkrZa1M9Kk4&format=json&callback=foo

could not decode third party json for matched url 'https://www.youtube.com/watch?v=fkrZa1M9Kk4': JSON text must be an object or array (but found number, string, true, false or null, use allow_nonref to allow this) at /usr/local/share/perl/5.20.2/JSON.pm line 187.

**What you expected:**

On this page, see a video at the end:
https://brendan.thecrag.com/article/connect

**Comment by scd** [comment]
Fixed. Please pull

This is an irritating regression issue with the third party json library when upgrading operating systems. It would have been fine on prod.
