### ISSUE TITLE
sandpit.thecrag.com/translate not working anymore

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2959]
**What happened?**
Tried several times to add some German translation to gym keys. While storing the translation for the key *article.grades.header.grade-contexts.sub-header.grades-in-a-gym.content2* I got an error message that I can not reproduce at the moment. I think it said something about an API error and I should contact @scd.
I tried to translate some other key with just one line, but the text was never stored and the JavaScript loading indication never stopped or disappeared. 
So far I tried with Firefox and Chrome and different PCs and locations.

**What you expected:**
A working interface to translate.

**Comment by DaneEvans** [comment]
I think sandpit might be more thoroughly broken. 

I'm getting failures on all API calls that I try to make to sandpit, and they were working yesterday, so I don't think it's my end

**Comment by scd** [comment]
@lordyavin is it working now?

**Comment by lordyavin** [comment]
Yes it works again. What was the problem?

**Comment by scd** [comment]
There is a lot of change going on. Sandpit is way less stable then prod for a couple of reasons.

In this case it was because we introduced a new process to remove old translation keys, which erroneously changed the permissions of the translation file.
