### ISSUE TITLE
PDF for arapiles (and likely others) are broken

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2962]
**What happened?**

https://www.thecrag.com/climbing/australia/arapiles

1) the link says the pdf is 2 years ago!?:
![image](https://user-images.githubusercontent.com/187449/33191351-9be38322-d10c-11e7-9ec5-cb19ba6f8ec6.png)

2) the pdf itself doesn't even load
![image](https://user-images.githubusercontent.com/187449/33191363-b18a3536-d10c-11e7-815b-134fafa7b7cf.png)

https://static.thecrag.com/pdf/11740915.pdf

**What you expected:**

* [ ] every time we generate a pdf, we should do a check on it first to confirm it is not corrupt

**Comment by brendanheywood** [comment]
That pdf is actually a html 404 not found document.

**Comment by brendanheywood** [comment]
This looks like a pretty robust health check:

https://superuser.com/questions/580887/check-if-pdf-files-are-corrupted-using-command-line-on-linux

```
$ pdftotext 11740915.pdf 
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error (2): Illegal character <21> in hex string
Syntax Error (4): Illegal character <6f> in hex string
Syntax Error (6): Illegal character <74> in hex string
Syntax Error (7): Illegal character <79> in hex string
Syntax Error (8): Illegal character <70> in hex string
Syntax Error (11): Illegal character <68> in hex string
Syntax Error (12): Illegal character <74> in hex string
Syntax Error (13): Illegal character <6d> in hex string
Syntax Error (14): Illegal character <6c> in hex string
Syntax Error (18): Illegal character <68> in hex string
Syntax Error (19): Illegal character <74> in hex string
Syntax Error (20): Illegal character <6d> in hex string
Syntax Error (21): Illegal character <6c> in hex string
Syntax Error (24): Illegal character <68> in hex string
Syntax Error (31): Illegal character <74> in hex string
Syntax Error (32): Illegal character <69> in hex string
Syntax Error (33): Illegal character <74> in hex string
Syntax Error (34): Illegal character <6c> in hex string
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
```

**Comment by scd** [comment]
I think when the PDFs get to a certain size the system cannot cope and produces errornous results. 

@brendanheywood what do you think about the quick fix to no allow PDFs for bigger nodes. EG a simple rule that if there are > 1000 children then no PDF. We may need a second test on number of topos, because I think it is topos rather than nodes causing the issue.

**Comment by brendanheywood** [comment]
+1 for both tests. I think keep the download button, but in the dropdown just say 'hey too big try a cliff instead'.

**Comment by scd** [comment]
Actually there were already a route count limit in the code, just a bit too big.

I have reduced the route count limit to 1000 and the number of topos to 50.

**Comment by scd** [comment]
Also there are some further limits in the code if you are not logged in or a supporter. 

200 routes if you are not logged in and 500 if you are not a supporter.
