### ISSUE TITLE
TLC in API index/detail not correct

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2964]
**What happened?**
The TLC node ID returned by the endpoint is the very same ID of the current node and not of the parent TLC 
https://www.thecrag.com/api/index/detail/789776166?withdata=NodeID%2CParentID%2CSiblingSequence%2CNodeType%2CName%2CAreaType%2CTLC%2CCountryNodeID&abbr=0&to=child&stubs=1&key=ABC

**What you expected:**
In that case i would expect TLC = 190488567 because the requested node is a child of that TLC crag.

**Comment by scd** [comment]
This has been fixed on sandpit.

@nicHoch please test and close the issue when you are happy.

**Comment by nicHoch** [comment]
nice
