### ISSUE TITLE
Hide donation button for paying gyms

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2966]
**What happened?**
The dashboard of the Klettwerk is showing the donation button.

![grafik](https://user-images.githubusercontent.com/1528540/33320302-12be2bf4-d442-11e7-8b89-af5997926ce4.png)

**What you expected:**
I think you shouldn't present a donation button to paying gyms.

**Comment by brendanheywood** [comment]
@lordyavin can you please provide a screenshot?

**Comment by lordyavin** [comment]
BTW I know that this gym is yet not paying.

**Comment by scd** [comment]
Are you referring to an account which is managing the gym.  We would
normally get them to pay via that account n which case it would look like a
supporter account.

**Comment by lordyavin** [comment]
Okay then I assume the button is displayed because this account is yet not paying. I understand. I cose this for now.
