### ISSUE TITLE
Add Molasse tag

### ISSUE THREAD

**Issue by gui84** [theCrag/website#2969]
Add Molasse tag 
(sedimentary rock) in Route character.

**Comment by rouletout** [comment]
I reached out to our geologist for this one - the article https://www.thecrag.com/en/article/rocktypes lists this under Arkose - but wait for the expert to decide...

**Comment by rouletout** [comment]
OK, I have an answer :-):

Molasse is NOT a rock type but defines a way of formation of rock in an early stage. These can be very different "loose rocks" that ultimately for eitehr sandstones or conglomerates (and some other rare forms that are not climbable). All of them are already available on theCrag.

I therefore close the issue and ask @gui84 to find out what the "real" rock type is or provide a link to the area that claims to be Moalsse.

Thanks!!
