### ISSUE TITLE
alternate names are not sensitive to stress marks - critical for import 

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2974]
**What happened?**
An alternate name will be rejected if it only differs in stress marks.

try to add "testèr" to a route with name "tester"  here: https://sandpit.thecrag.com/climbing/spain/tenerife/route/1415797226

currently i try to import many routes from Czech Republic and we have many names in two Languages: German and Czech and somehow often they differ only in stress marks.

The problem is i can not auto detect this cases in excel and alike and therefore the import process is very time consuming because the system tells me during the import that the name is the same. 

**what i expect** 

wether the system allows alternate names only differ in stress marks 
or the import process will automatically reject the alternate name if only differ in stress marks and create the route only with the original name. 

This also apply to area names!

**Comment by nicHoch** [comment]
i found a excel macro to deal with that a bit better. I am not sure if that can deal with any case or just some usual ones because it is doing some static replaces only. Depending on how hard it is to implement on the script side. We could postpone that. it is up to you @scd

**Comment by scd** [comment]
@nicHoch do we want a route with a name testèr and an alternate name tester? I think not, but am open to your opinion.

If the answer is no, then we should definitely go down the macro path.

Regardless I think the system should allow this type of difference so I will look into it, but if you can fix via a macro then I no longer have to do this as a priority.

**Comment by nicHoch** [comment]
I think it is very important that we have the ability to distinguish that kind of different spelling.
Let's take the English"pirate" as example 
In German "pirat" in Czech "pirát". In this area (close to the German/Czech border) we have many route names in both languages available. Right now we have to decide for one of the two names. Every teacher will tell you in the corresponding country that you have written the pirate wrong if you tell them it is almost the same just with/out the little dot. It would be the very same mistake to write in English just "pirat" - there is also just one letter wrong (missing).

Now the macro will work to get the routes imported but with the cost that we loose one correct written name.

**Comment by scd** [comment]
Let me look into how hard this will be to fix

**Comment by scd** [comment]
I am pretty sure this is a mysql issue that the database does not allow accent duplication. My initial investigation implied that the database was throwing the error not my validation check. Here is a forum example:

https://stackoverflow.com/questions/11702432/mysql-utf8-latin-fails-on-duplicate-key-entry

If this is the case this is a far deeper structural issue. 

I think we should leave this until we have properly resolved the translation issue for route and area names, in which case the problem will just disappear because the test will be uniqueness on language.

**Comment by nicHoch** [comment]
ok

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/79851934-46094f80-83c6-11ea-8f08-f71405fbd399.png)

seems sorted on beta

**Comment by Mdemaillard** [comment]
actually already working on prod server. closing.
