### ISSUE TITLE
Photo ranking

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#2976]
We've got a lot of high and bad quality pics on theCrag. I would love to "like" or rate high quality pics. This would make it easy for the random pictures algorithm to show quality pics only. A page with the best pics on theCrag would be great to discover new areas and photographers.

**Comment by brendanheywood** [comment]
thanks @lordyavin - but I will close this as a duplicate of:

crowd source image / photo quality assessment https://github.com/theCrag/website/issues/474 

And also partially related to:

Allow us to comment on photos and 'Like' them  https://github.com/theCrag/website/issues/1293

**Comment by brendanheywood** [comment]
Please go and comment on those, we use the number of comments on issues as a rough guide to help prioritize the roadmap, thanks again :)

**Comment by lordyavin** [comment]
Damn it, searched for similar issues but didn't find them. Don't know why. Thanks for the hint.
