### ISSUE TITLE
Software error when trying to add route (to gym)

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#2977]
**What happened?**

Today, I repeatedly get the following error when trying to add a route to a gym. Probably only something temporary, but I thought you should know:

```
Software error:

DBD::mysql::st execute failed: Deadlock found when trying to get lock; try restarting transaction at /opt/CIDS/perllib/BSIS/Db.pm line 1228.
For help, please send mail to the webmaster (scd@thecrag.com), giving this error message and the time and date of the error.
```

(please also provide urls and screen shots)

**What you expected:**
No error, route added.

**Comment by birgander2** [comment]
Seems to work again!

**Comment by lordyavin** [comment]
Duplicate of #2950

**Comment by lordyavin** [comment]
Closing because of duplication.
