### ISSUE TITLE
gearProfile for api/index/detail

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2980]
please add gearProfile to the withData for the

`api/index/detail `

endpoint if the node is a area.
That should return the relative/absolute? numbers of routes per gear style.

**Comment by nicHoch** [comment]
@scd if that will takes a bit longer please propose the expected format of that data as soon as possible so i could mock something for the meantime.

**Comment by nicHoch** [comment]
@scd any news

**Comment by scd** [comment]
I have done a bit of work on this now. Use the withdata 'Styles'. It should return a hash which looks something like:

```
         {
            "Aid" : "3017",
            "Alpine" : "2876",
            "DWS" : "947",
            "Ice" : "1794",
            "Unknown" : 94741,
            "TopRope" : "3455",
            "Boulder" : "49513",
            "ViaFerrata" : "246",
            "Sport" : "177486",
            "Traverse" : "70",
            "Trad" : "77904"
         }
```

Note that this has not been implemented very well in the backend and there are a number of outstanding issues we need to slowly work through.

  * These stats do not differentiate between indoor and outdoor
  * The Traverse type is something we are going to probably dump
  * The label is inconsistent in the templates for a couple of labels - sometimes 'Top Rope' and sometimes 'TopRope'. I think we should commit to the later for this interface and fix elsewhere.
  * The stats fields are hard coded in a stat record rather then generically assigned to a gear style.
  * We also have a grade profile statistic hard coded for some of the styles. It is really cool to get this kind of granularity, but I would really want to refactor properly before pushing this through to the app.

If the above hash does what you want then we should lock this in and refactor around this format?

It is on sandpit if you want to test it.

@nicHoch please close this issue if you are happy.

**Comment by nicHoch** [comment]
@brendanheywood is that proposed format reusable for you style donut implementation from the web?

**Comment by brendanheywood** [comment]
Yeah that's fine. There has been a lot of mess due to the key names being sometimes treated as keys and sometimes and values, it would be nice in the api normalized all this and they were all lowercase with no spaces and considered a key.

Also the value is always going to be an integer so it could just be a number instead of a string, but both of these are pretty minor.

**Comment by nicHoch** [comment]
@scd  yes all lovercase keys and integer numbers would be nice

**Comment by nicHoch** [comment]
right now some values are string ("Traverse" : "70") some integers (  "Unknown" : 94741) it should be consistent!

**Comment by scd** [comment]
I have made the keys lower case and the values all integers.

**Comment by nicHoch** [comment]
looks all god
