### ISSUE TITLE
Added and then removed webcovers make a busted stream event

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2981]
**What happened?**
https://www.thecrag.com/event/1584504672

![image](https://user-images.githubusercontent.com/187449/33989472-c7f26888-e11b-11e7-84ff-8c13fb1cb17c.png)

I saw 2 pics that would have been good, but when I added them the resolution was too low and they looked bad so removed them.

**What you expected:**
* [ ] In this case either probably no event at all, or maybe a 'deleted' event

**Comment by brendanheywood** [comment]
Another example from @rouletout:

https://www.thecrag.com/event/1602472965

![image](https://user-images.githubusercontent.com/187449/34337911-8147a836-e9b7-11e7-8ce7-a951d540302a.png)

**Comment by brendanheywood** [comment]
https://www.thecrag.com/event/1900190871

**Comment by rouletout** [comment]
Seems fixed, closing
