### ISSUE TITLE
Faulty link to PDF guide

### ISSUE THREAD

**Issue by Heineken** [theCrag/website#2987]
Hey there.

I just tried to download a PDF guide of the[ fjordland area](https://www.thecrag.com/climbing/new-zealand/milford):

1. Clicking on pre-created gives me a [pdf](https://www.thecrag.com/processmap/requestpdfguide/11746027?R=/climbing/new-zealand/milford), which is actually an HTML file containing an 404 error message.

2. Click on "[Personalised](https://www.thecrag.com/processmap/requestpdfguide/11746027?R=/climbing/new-zealand/milford)" gives me "No Guides Above TLC". 
I guess that means "top level crag", right?

Are 450 routes too much for a pdf?

How am I supposed to extract a guide for a larger area? (That would be quite useful here as NZ seem to be a little short on guide books.)

**Comment by scd** [comment]
Yes TLC means top level crag. This is a business rule, so the static link should not even be there.

There are a couple of other use cases where people may want small region based guides so we will look into this. We are juggling a lot of priorities, so in the meantime just generate the lower level guides.

**Comment by Heineken** [comment]
OK, thanks.
If the behaviour remains like this, at least the error message could be made clearer. Something like:
"Fiordland is a region. PDF generation is only possible for nodes up to level 'crag'."
Good luck with the juggling!

**Comment by Mdemaillard** [comment]
Implemented. Buttons greyed out, and if you squint a bit it tells why.
![image](https://user-images.githubusercontent.com/60388146/76629546-19505580-6547-11ea-97c7-93a82859bfa7.png)

**Comment by Heineken** [comment]
Neat!
