### ISSUE TITLE
Roped solo icon should be more distinctive as the icon is being miss intepretted

### ISSUE THREAD

**Issue by scd** [theCrag/website#2988]
From user...

Just a little niggly thing but worth mentioning. When i mark a tick as 'roped solo' it puts a graphic that says 'solo' next to the tick. Most people who see that immediately think free solo with no ropes. Being a responsible father who no longer solos it looks really bad. Ive actually had a few friends contact me and ask about it with some degree of concern (they think im free soloing 23s!). Is there some way of changing this symbol? Its really a top rope ascent with no belayer and a device rather than a "solo". Your thoughts?

![screenshot_20171220-170923](https://user-images.githubusercontent.com/373058/34228525-1a810254-e625-11e7-9a89-e2462e94a129.png)

**Comment by brendanheywood** [comment]
Lead roped solo:
![image](https://user-images.githubusercontent.com/187449/34241928-d0820f20-e66c-11e7-8bfe-78c2e75d0e60.png)

Top role solo
![image](https://user-images.githubusercontent.com/187449/34241936-db7a8470-e66c-11e7-9c00-65f3246745c6.png)
