### ISSUE TITLE
numberAreas for api/index/detail 

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2989]
please add numberAreas to the withData for the

api/index/detail

endpoint if the node is a area.
That should return the number of all areas in the sub tree

**Comment by brendanheywood** [comment]
Is this for display in the child area template? I wasn’t sure how to interpret that as either number of direct children vs total descendants but I assumed the first is more useful. The latter has little value at region or even crag level. So I think this might not be needed?

**Comment by scd** [comment]
@nicHoch what is the outcome of this. Do you need the extra variable(s)?

Number of descendant areas is a statistic so it is easy to provide.

Number of direct child areas is not a statistic so requires an additional query which will have a slight performance hit. This is a considerably more work so I don't want to do it unless it is really required.

**Comment by scd** [comment]
@nicHoch could you have a look at this again. I want to know what needs to be done, number children or number descendents?

**Comment by brendanheywood** [comment]
Number of children, or more correctly actually the number of direct children who are areas. If there is a mix of routes and areas we don't care about the routes as they are already in the donut chart

**Comment by scd** [comment]
As we have a NumberRoutes parameter already, which means ancestors I have decided to make the new parameter NumberChildAreas

@nicHoch this is hotfixed on sandpit. You will need to use the `NumberChildAreas` parameter.

Please close once tested.

**Comment by scd** [comment]
Closing
