### ISSUE TITLE
Adding routes to a gym missing color selector

### ISSUE THREAD

**Issue by scd** [theCrag/website#2993]
The workflow for adding routes to a gym is missing some stuff:

 - [x] No button to add routes from an area with routes already in it
 - [x] Color selector not available when adding routes (just text field)
 - [x] Color field not even on screen when adding multiple routes

**Comment by brendanheywood** [comment]
Related to deprecating single edit mode https://github.com/theCrag/website/issues/635

**Comment by rouletout** [comment]
It is also a language issue, when you enter e.g. blue in the text field it is recognized but if you enter "blau" (German) it is not

**Comment by scd** [comment]
It will not be a text field when fixed.

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
scd@thecrag.com
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>
