### ISSUE TITLE
Aid tick showing up on trad bargraph

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#2997]
**What happened?**
An aid tick of a trad route is showing up on the bar graph as a successful trad tick
the ascent is this one of infidelity: 
https://www.thecrag.com/ascent/1590281325

![image](https://user-images.githubusercontent.com/22091505/34548812-47a98f60-f158-11e7-8653-793f45a48fbb.png)

**What you expected:**

An aid tick should be treated as a failed ascent of a trad route

**Comment by brendanheywood** [comment]
Redundant and should be all good in the new pyramids
