### ISSUE TITLE
Route action menu is badly formatted when not logged in

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3003]
**What happened?**

<img width="885" alt="screen shot 2017-12-17 at 09 07 16" src="https://user-images.githubusercontent.com/19162952/34080848-fa703c1e-e309-11e7-90d0-a9ab62971f65.png">

**What you expected:**

* [ ] probably no menu at all

**Comment by rouletout** [comment]
Shows now log ascent and leads you to the login page, closing
