### ISSUE TITLE
All history fa ffa and route set dates don't display correctly with partial dates

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3004]
**What happened?**

https://www.thecrag.com/c/kletterwerk/route/1680076440

If a month and year is chosen, but no day of the month, the month is ignored in the FA history display.

**What you expected:**

* [x] if the month is specified then the month should show. Even if the route is old and we show just the year, then the hover tooltip should still show as much of the date as has been entered.

**Comment by lordyavin** [comment]
This bug applies to gym wall cards too.

![grafik](https://user-images.githubusercontent.com/1528540/36535592-87e25a10-17ca-11e8-8599-1dd3012f7211.png)

I set the month and year for a [route](https://www.thecrag.com/c/kletterwerk/route/1680076440) without a name.

**Comment by brendanheywood** [comment]
Fixed. Tested with year, year + mon, year+mon+day, and in both rock and gyms, and there is also logic for smaller date formats for either very new (1st Jan) or very old routes (2018). The route detail page always shows the full date, in other places it's in the tooltip
