### ISSUE TITLE
Alternate names does not allow for "similar" international characters

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3005]
**What happened?**
E.g. adding the alternate name "Sarıkaya" to https://www.thecrag.com/climbing/turkey/area/1635818400 results in error 

Cannot continue process: Error:[ { "dbError" : "record already exists" } ]

State: 18577

Error Code: 4

CodeReference: CIDS::Process::SupplyInformation::BulkEdit, /opt/CIDS/perllib/CIDS/Process/SupplyInformation/BulkEdit.pm, 931 

**What you expected:**

Possibility to add local language names

* [ ] item 1
* [ ] item 2

**Comment by scd** [comment]
Note to self. For the current release I have removed the database index uniqueness dependency. This means the rest of this issue could be hotfixed after the release

**Comment by rouletout** [comment]
yes
