### ISSUE TITLE
Image dimensions and the actual image don't match

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3009]
**What happened?**

https://www.thecrag.com/event/1621318230

![image](https://user-images.githubusercontent.com/187449/34963631-aaa34fea-fa9d-11e7-8774-ffb2f964a837.png)

The html template and the thumbor url generated don't have the same data so almost certainly a code issue and not a rotation issue. Or possibly a cache issue?

**What you expected:**

* [ ] image dimensions and thumbor dimensions should match

**Comment by scd** [comment]
hotfixed
