### ISSUE TITLE
og:image in area picking a photo from the area but not rotating

### ISSUE THREAD

**Issue by scd** [theCrag/website#3010]
**What happened?**

https://www.thecrag.com/climbing/czech-republic/area/648186114

Has og:image set to

```
<meta property="og:image" content="https://image.thecrag.com/268x200/69/37/6937630a39e4f953a98856004d77b572724b9e54" />
```

Which is picked from area images:

https://www.thecrag.com/photo/653926293

But rotation info is not correct in the template so the image looks like

https://image.thecrag.com/268x200/69/37/6937630a39e4f953a98856004d77b572724b9e54

But should look something like

https://image.thecrag.com/1285x960/filters:rotate(90)/69/37/6937630a39e4f953a98856004d77b572724b9e54

**What you expected:**

Before this is fixed we need to resolve what we should be showing here. Do we even want to show a random image if there is no web cover. Should it be location?

**Comment by brendanheywood** [comment]
Lets decouple the issues and fix this as is. Yes the business logic needs to change for the og image but in some cases it will probably still fall back to a random photo if there is nothing else so we may as well have that bit working correctly first.

**Comment by scd** [comment]
This is hot fixed. You may have to reset the facebook cache to see in facebook.

**Comment by scd** [comment]
og stands for open graph which I think was a standard developed by facebook. It means you can have meta tags in your page which describe your page to third parties. og:image is used by Facebook to get an image to display with an url post. It is actually pretty cool.
