### ISSUE TITLE
When drag and drop uploading new photo into a forum it should inherit the node

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3012]
**What happened?**

If I am in a forum for X, and I drag in a photo then it should auto attached to the same node.

This should apply to any markdown which has any context so:

* beta fields have a nodeid
* forums

**What you expected:**

* [ ] photos to not be orphaned

**Comment by scd** [comment]
I have just checked the code and node id is there. 

I have confirmed it works for forums.

@brendanheywood did you see a case where this was broken or was it just a matter of testing. My understanding was that we have not see a broken case yet.

**Comment by brendanheywood** [comment]
No it's just that I want to avoid a user interface that made it easy to do the wrong thing. I want to encourage people to upload photos which are linked to nodes and have nice titles and where possible are linked to people. This new upload process is absolutely easier for some use cases but I think could result is much worse data long term. I can't remember where it was but I remember talking about making it easier to edit this metadata inline after you've dragged it in to help avoid this potential loss of metadata as well.

I just had another thought: if you are browsing the photos and you see a random photo, lets say a picture of some shitty anchor but with no context, it would be good to see that the photo was linked to a forum in a similar way to the webcover link so that you can at least figure out what the photo is about.
