### ISSUE TITLE
Foto upload broken

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3013]
**What happened?**

Photographer and Climber can not be selected, box resizes on click only.

<img width="945" alt="screen shot 2018-01-18 at 06 20 36" src="https://user-images.githubusercontent.com/19162952/35100212-91c97510-fc20-11e7-9064-16dc24842ec2.png">

(please also provide urls and screen shots)

**What you expected:**

Dropdown lists for photographer and climber

**Comment by nmonteith** [comment]
+1 I can't seem to select climber or photographer from a list of usernames (I can manually type it though)

**Comment by lordyavin** [comment]
Entered photographer not stored: https://www.thecrag.com/photo/1640779977

**Comment by scd** [comment]
- [ ] css missing in form
 - [ ] wrong image url (old image) when updating an image
 - [ ] climber missing from template
 - [ ] updating date may have a UTF issue as displayed the day before in templates.

**Comment by scd** [comment]
@lordyavin can you please try again. Specifically I want to know if it is now storing photographer when you upload.

**Comment by lordyavin** [comment]
Fix Acknowledged.
