### ISSUE TITLE
Add route history facet to ticks / ascents facet so you can search for fa / ffa / setter

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3015]
See also: https://trello.com/c/xeFUy74e

**What happened?**

We can currently filter routes by who set them, but we cannot filter a set of ascent of routes filtered by a fa or setting. ie 'show me all the ascents of routes I have created'

**What you expected:**

* [ ] These should all work:

Routes set by: (half works, only shows text names)
https://www.thecrag.com/climbing/australia/routes/by/monteith/

Routes set by @ mention: (doesn't work)
https://www.thecrag.com/climbing/australia/routes/by/@monteith/

Routes set by account id: (does work but UI is broken not round trip)
https://www.thecrag.com/climbing/australia/routes/by/9231481/

Routes climber by (works)
https://www.thecrag.com/climbing/australia/ascents/by/nmonteith/?sortby=when,desc

Routes climber by anyone but set by (doesn't exist yet)
https://www.thecrag.com/climbing/australia/ascents/route-by/nmonteith/?sortby=when,desc

* [ ] corresponding gui to go with the new url filters

**Comment by scd** [comment]
I have just done the backend to this. It is pretty server intensive so we need to discuss how to make this available. Maybe this is for paid supporters.

https://www.thecrag.com/climbing/australia/ascents/route-by/@nmonteith/?sortby=when,desc

**Comment by scd** [comment]
Closing as enough of this is done.
