### ISSUE TITLE
Missing photo data file behind a photo record

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3016]
**What happened?**

This photo is busted:

https://www.thecrag.com/photo/1502179560

![image](https://user-images.githubusercontent.com/187449/35132438-709f5c1a-fd1f-11e7-94d1-60b8029e9274.png)

**What you expected:**

* [ ] photo file exists, or the photo record is disabled in some way

**Comment by brendanheywood** [comment]
Another one

https://www.thecrag.com/photo/662014722

**Comment by brendanheywood** [comment]
And this one:

https://www.thecrag.com/photo/1426663740

**Comment by brendanheywood** [comment]
Which is also a webcover:

https://www.thecrag.com/climbing/brazil/minas-gerais/area/500912274

**Comment by brendanheywood** [comment]
Six different photos here are affected:

https://www.thecrag.com/climbing/brazil/photos/

**Comment by scd** [comment]
Hmmm, these photos do not exist on any of our servers so it is not possible to fix this.

I have done a bit of investigating here and cannot work out why. There is only one way I can think of that can remove images and that is if the user removes them (not just disable) using our standard photo admin ui.  However it does not look like this has been done. There is one edge case that I fixed, which may not have come through to the release, where if images were duplicated in the system removing it from one photo record removed it for all photo records. Again this does not seem to be the case unless I have made a mistake in my analysis.

Given that they are no longer in the system we should write a script to correct the records so that the system knows that they no longer exist.

**Comment by scd** [comment]
BTW, I have removed the webcover.

**Comment by scd** [comment]
I have updated the status of all records we no longer have data for to deleted, so now we have a clean baseline if the problem keeps occuring. There were about 150 all up:

UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 866380242;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1426663722;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 873740757;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1419297507;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1376609271;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 965682000;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 965682120;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 973258449;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1488454827;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1518576036;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1224050004;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1438164777;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 846072219;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 929981697;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 927247500;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 927248133;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 991511736;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1276818162;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1360273362;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 640980801;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1434237891;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 972453753;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 972454077;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1376609265;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1441154973;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1439407122;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 923591595;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 923734752;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 923853855;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1127444553;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1127445924;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1507383765;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 846072327;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1599355329;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1438150197;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1593750288;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1426663740;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 957799020;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1004786886;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1373498043;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1237116867;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1241782104;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1279910100;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1434237768;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1539020769;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1539024654;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 986893092;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 986893086;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1502179560;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1438510863;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1424245530;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 640980795;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1426663752;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1463030409;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1283133315;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1127445189;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 921737316;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1441827594;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1129574640;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1593750282;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1234955595;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 861223926;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1410704517;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1434237885;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 949906422;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1429891062;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1593750276;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1425378633;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1425379584;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1621009404;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 850892598;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 852450054;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 852450330;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1376609259;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1429891056;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1118236644;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1118238936;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1000417596;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1014507279;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1423918830;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1004353551;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1593750270;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1342487163;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 841857501;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1379138868;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 640795545;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1426663770;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 986893098;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 861223950;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 640980789;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 861223938;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 917967360;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1197314475;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1618704369;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1333343253;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 928533060;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 921634434;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 986507358;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 996919095;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1376609253;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 845859537;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 588526275;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 588528027;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1391640183;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1050655950;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1470506046;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1226695761;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 861223932;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1533336006;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1011715407;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1279910106;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 905696619;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1593750264;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 846439971;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 875943672;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1426663758;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1445075685;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1599357465;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 845859531;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1227130338;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 973513830;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 973570041;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 991511742;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1227130344;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1373370021;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1426663746;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1371104883;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 861223944;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1010794833;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1005112845;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1518575748;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1279181973;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 1425871893;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 929980650;
UPDATE Photo SET RecordStatus=0, UploadStatus=7273909 WHERE ID = 926304993;
