### ISSUE TITLE
Refactor the topo ordering from templates to backend

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3027]
**What happened?**

The app needs to know the order of topos interleaved within the chlid areas, routes and annotations. This logic is currently only in the web templates and we could duplicate this logic in the app but I think it's much better to move this logic back so the template data and api are consistent.

This is a partial stepping stone toward potentially making the topo order explicit:

https://github.com/theCrag/website/issues/1190

It is also a chance to properly document the business logic around this and make it clearer. I've marked this as must do as it will be blocking the app.

**What you expected:**

Topo data is currently a separate data item distinct from children, this will split it into two parts:

1) Topos you are 'in' which I will call ancestor topos. The topo is parented to a node which is not the current node. Eg a crag topo with each cliff added, and you are at a cliff node. I think we could simply keep these types of topo in the existing data item as is. The only thing to clarify might be defining an explicit order for these topos which I think should just be world index order.

2) Topos that are parented to the current node, ie typical topos. These will be interleaved into the existing children data item and look like other nodes types but just have a type of 'topo'

The main principal behind the business rules are simply that we want topos to appear as close as possible to the routes and areas they contain.

The existing algorithm is:
1) go through each topo and look at all the links to routes or areas, and filter these to just the nodes which are children of the current node and ignore the rest.
2) we are concerned with all nodes which have been linked to topos, and not the subset of these nodes which actually have line data drawn. Let's call this 'disabling' those node links. This already gives us a small amount of control to fine tune the way topos are presented, ie if a topo is positioned a little bit funny then we can link another route to refine the order but not draw that route in. It is only because of this that we haven't needed to worry about #1190 yet.
3) for each topo find the linked node which is positioned earliest in the children list and not disabled, and now sort the topos according to this order
4) if two topos have the same order based on the first non-disabled link, then compare by position of the last linked node. ie if topo A points to 1,2,3,4 and topo B points to 1,2,3,4,5,6 then A will be ordered first. 5) pick the first topo off that list and insert if into the children list just before it's first linked node. In the step above, if two or more topos were perfectly tied, then instead them all, and order them by node id.
6) now still focusing on that topo, grab it's list of linked node, and then iterate over the rest of the remaining topos and 'disable' any other references to those same nodes as no longer counting. This is so if we have topos that overlap by several routes, then we move the topos further down so they are closer to the new routes which haven't already been shown in a topo.
7) now because of the disabling of various links, we need to go back to step 3) and re-find the top most non-disabled node reference and then re-sort the list of topos again as it can change, then pop off the top one and keep repeating until there are no more topos.
8) if a topo is not linked to any nodes then position it last in the children list, and then sort by node id.
9) The type of nodes being linked to from a topo, ie route, or area (or annotation in future) makes no difference to the topo ordering.

Examples:

Topos:
A: 1,2,3,4
B: 7,8,9

Result:
A,1,2,3,4,5,6,B,7,8,9

Topos:
A: 1,2,3,4
B: 4,5,6,7

Result:
A,1,2,3,4,B,5,6,7

Topos:
A: 1,2,3,4
B: 1,2,6,7,8
C: 1,2,3,5,7,8,9

Result:
A,1,2,3,4,C,5,B,6,7,8,9

Tasks:
* [ ] implement new pseudo topo node type in the children data item in all atoms
* [ ] change the nodeListView template to rip out the current topo order code and just use the children ordering
* [ ] double check other node list templates, eg the html guide view and the pdf export view
* [ ] ensure list view still shows the ancestors topos
* [ ] make the api spit out the exact same stuff (should be free?)

**Comment by brendanheywood** [comment]
@nicHoch can you review this too please

**Comment by scd** [comment]
@brendanheywood are you suggesting that every topo becomes a node in it's own right?

**Comment by nicHoch** [comment]
sounds right to me. at the moment in the app there is no topo order logic at all. if the comes with the api data model - the better.

**Comment by scd** [comment]
The scope of this work is

  - [ ] implement algorithm in API index list. When topos are requested the algorithm is invoked and topos inserted into the list as fake nodes. Will the fake nodes have a nodeID (something like their topo ID) or just a null nodeID. I think the latter.
  - [ ] the app handles 'topo' node types and null node ids
  - [ ] generating template data should use the same algorithm and should share the business logic as a single piece of code
  - [ ] templates should be refactored to use the new template data
  - [ ] Note to check that adding a fake node type does not break topo route numbering. There is currently a major business logic deficiency where the route numbers on the PDF topos depend on two pieces of logic aligning. Bonus points for make this a single piece of logic.
  - [ ] Topo facets already have some sort of ordering implemented in sql land. No need to change this.

**Comment by brendanheywood** [comment]
Yes just use fake node id = topo id, I'm already using this and I don't want it to change.

**Comment by scd** [comment]
I have done the critical part of this a while ago so closing.
