### ISSUE TITLE
Added a routes facet flag filter for 'not a project'

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3028]
**What happened?**
The hardest sports route in the world list

https://www.thecrag.com/climbing/world/routes/with-gear-style/sport/?sortby=grade,desc

But this included projects which don't have a confirmed grade and should be excluded. We don't have a filter for this, only filtering to projects:

https://www.thecrag.com/climbing/world/routes/with-gear-style/sport/assert/is-project/?sortby=grade,desc

**What you expected:**

* [ ] an 'Is not a project' filter under 'Misc flags'

https://www.thecrag.com/climbing/world/routes/with-gear-style/sport/assert/isnt-project/?sortby=grade,desc
* [ ] added to facet GUI

**Comment by brendanheywood** [comment]
@rouletout do you want this one done quickly and hot fixed before you send publish the url?

**Comment by scd** [comment]
It is done:

https://www.thecrag.com/climbing/world/routes/with-gear-style/sport/assert/is-not-project/?sortby=grade,desc
