### ISSUE TITLE
The "not-an-issue" (aka keep design functional vs pretty but less usable)

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#3033]
This one does not require doing anything; instead, refraining from an action:

I really like the classic, tidied-up layout of thecrag. Call me last millenium, but I despise responsive design with oversized fonts, bulky buttons, tons of scrolling and huge slideshows and pictures covering the entire screen, which a PITA to use with a real computer.
Not sure about your plans, but seeing something like "webcover image" makes me feel uneasy.
Please, keep a "classic layout" (at least optionally), that won't inflict a tendonitis in my scroll-wheel finger.

**Comment by brendanheywood** [comment]
@MelwinQ I assume you've had a look at the mockups, can you please link specific feedback back to specific parts of the mockups? Ideally with a screenshot with some scribble on it (please don't share any mockup links here, they are transient urls and not intended for public viewing). I totally agree that desktop should be optimized for desktop and not merely a big version of mobile and this is the plan. Responsive itself is not the problem, we are already responsive. Nor are webcovers, we already have these too, or are you opposed to what we have already done? Whatever happens there will not be two layouts or options. If anything if we get things right there will be less scrolling now that currently.

**Comment by MelwinQ** [comment]
I am not sure what "mockups" are in this context, please enlighten me.
I'll try to be more specific, though:
Looking at https://www.thecrag.com/climbing/germany/frankenjura, I find a quarter of my screen covered by (admittedly beautiful) picture, hiding all essential information completely, unless I scroll down. I'd prefer to do without this.
As for "responsive design", of course there's nothing wrong with a pulldown menu. What really irritates me are navigation elements that completely change the layout of the page or make me scroll erratically to and fro. Not (yet) the case at thecrag, as far as I can see.
No ofense, I am completely aware that taste do differ. Just wanted to trigger some user feedback, BEFORE major changes are implemented.

**Comment by lordyavin** [comment]
+1 for user options to select theme/layout

Don't get me wrong. A fresh layout/design would help do gain new users and if it improves the usability I'm with you. But don't forget the users like @MelwinQ who contributed a lot and are used to the actual design. If the design changes are to big and don't improve the usability it may drive them away from theCrag.

**Comment by birgander2** [comment]
+1 from me (another last millenium guy).

I really like the webcovers, and I really dislike that I have to scroll before reaching relevant content. However, not sure how to solve that. A "pro" theme would be one solution, or maybe a clever overall layout using background images? I think it's worth investing some time on this topic. Btw, the new stating page is really good. And 27crags, for example, has a horrible interface imho. A good example how not to do it.

**Comment by scd** [comment]
> Btw, the new stating page is really good

Was that a typo? What is stating (or am I going crazy)?

**Comment by lordyavin** [comment]
I think he meant "starting" aka home aka landing page

**Comment by scd** [comment]
ahh makes sense. Yes a lot of analysis and work has gone into that. It will eventually flow through. We collect feedback from users where there are new difficulties and try and work through these issues.

**Comment by lordyavin** [comment]
BTW: I like the webcovers too.

**Comment by rouletout** [comment]
Useful discussion and taking into account in the re-design of pages, closing
