### ISSUE TITLE
Ability to delete a new forum completely

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3035]
**What happened?**

If a user has just started a new forum, and nobody else has since replied, they should be able to delete their own forum completely. ie 'I lost some gear' - 'ok found it, don't bug everyone about it'. Or 'opps I didn't mean to make that post in this node'

**What you expected:**

* [ ] be able to delete a new forum that nobody else has replied to yet
* [ ] softer option: be able to convert the forum from public to private. Private forums should still be remain attached to a node but just be visible only to those in the forum already.

**Comment by scd** [comment]
Admin or a user can delete their own discussion.

The core of this issue is done so I am closing.
