### ISSUE TITLE
Simple gym route view should work regardless of node type

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3037]
**What happened?**

Business logic of when gym template should kick in:
* if we are inside a gym
* and we are at a node which contains routes

https://www.thecrag.com/climbing/austria/area/1604702022

https://trello.com/c/BHHugakn

**Comment by brendanheywood** [comment]
done and hotfixed

**Comment by nicHoch** [comment]
now the user is forced to create at least one sub sector to put the routes behind. otherwise no information about the gym are shown at all due to the simple template.  

https://www.thecrag.com/climbing/switzerland/mittelland/zurich/area/776368122

**Comment by brendanheywood** [comment]
hhmm, I was kinda expecting there to be some fallout of changing that logic. I think medium term we should be moving some of the hard coded decisions around what we want to show into gym config. I think in the short term we just work around it. Is a gym with only 6 routes worth worrying about?

I just had a look at their website, it looks to me like there should actually be a ton more routes here and should have a second layer of walls / features anyway?

**Comment by scd** [comment]
I think most gyms will require walls. However they may start their data entry via routes, which may lead to a shitty experience.

Also there are some use cases where there are single artificial features in public spaces. For example Wilson Bouldering Wall in Melbourne is a single bouldering feature in a public park.

https://www.thecrag.com/climbing/australia/inner-melbourne/area/982344321

This is going to become more prevalent.

**Comment by nicHoch** [comment]
It is not a gym with only 6 routes this is a very common pattern that the community only create generic routes. For training log many do no really care about name, route setter, ...
they just want to log that they have done a hard,easy, ... boulder in this gym at a curtain date.

**Comment by brendanheywood** [comment]
I'm curious who in the community besides us has added gyms like this, and doubly curious how many have ever had ticks? I can't easily filter to this with the existing facets but I had a quick scan and couldn't find any ticks of generic gym routes.

**Comment by nicHoch** [comment]
here other: https://www.thecrag.com/climbing/austria/area/990747330

**Comment by brendanheywood** [comment]
fyi:

https://www.thecrag.com/climbing/austria/area/983138523/activity
https://www.thecrag.com/climbing/austria/area/990747330/activity

**Comment by scd** [comment]
If it is the same route they are doing over and over again for training then this is fine. However if it is actually different routes then ticking a generic grade is not great for their logbook as it will look like they are repeating the same route. CPR will be tragically effected. At the moment I cannot see us supporting the pattern of doing a second ascent of a route and indicating that it is not a repeat.

Our first efforts for gyms in Australia were to create generic grades, but that was pretty unsuccessful.

I think most gyms should have sub areas. However there will be single artificial features in the community which do not have sub areas and if we want home woodies in the index they will not have sub areas.

**Comment by nicHoch** [comment]
another example without generic routes but way to small to force subareas:

https://www.thecrag.com/climbing/germany/oberpfaelzer-wald/area/420174048

**Comment by brendanheywood** [comment]
@rouletout / @nicHoch can you please confirm the business logic you want to see. I would propose:

1) if we are inside a gym, but NOT at the gym node
2) AND we are at a node which contains routes

Then use the 'simple' gym template.

If not then use the normal template (descriptions, maps, topos, stats)

**Comment by rouletout** [comment]
sounds good to me

**Comment by nicHoch** [comment]
sound also good for me.

BUT we need a way to archive routes on the top level to!

**Comment by brendanheywood** [comment]
This has been completely redone, the 'gym feature' alternate template is no longer used at all and most of the differences have now been merged into the single main area template
