### ISSUE TITLE
People posting comment to forum creates duplicates

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3039]
**What happened?**

I'm not sure the root cause here, but I've seen this repeatedly:

![image](https://user-images.githubusercontent.com/187449/35725102-39c0bd8e-0854-11e8-926f-405efe74d71e.png)

**What you expected:**

* [ ] we should both avoid it happening in the first place (maybe mouse double click issue?)
* [ ] but ideally also detect it and not create the duplicate

**Comment by brendanheywood** [comment]
Just reproduced this on dev box, almost certainly a double click issue. Easy to capture the first click and disable the button so the second click does nothing.

**Comment by lordyavin** [comment]
I see this every day. Got used to it but would appreciate if it is going to be fixed. A easy approach would be to just have one "inbox" notification. Would be sufficient for me. I don't distinct between forum and private messages.

**Comment by lordyavin** [comment]
Did you change something at the inbox. Mine was flooded with almost 29 notifications.

**Comment by brendanheywood** [comment]
![image](https://user-images.githubusercontent.com/187449/36401886-a5926b10-162e-11e8-8ca8-b23c635ac6a5.png)

**Comment by lordyavin** [comment]
Same for me

**Comment by brendanheywood** [comment]
![image](https://user-images.githubusercontent.com/187449/37314822-5c9d1b30-26aa-11e8-8f15-a314a74e0d2a.png)

**Comment by brendanheywood** [comment]
meh this seems to be happening more often than not, I'll aim to get this done when I do the touch the forum pages in this release

![image](https://user-images.githubusercontent.com/187449/37380817-6f8c62fc-278e-11e8-9388-2e9ce5af4a4e.png)

**Comment by brendanheywood** [comment]
The first click now disables the button preventing a second accidental click
