### ISSUE TITLE
Bulk editing history fields error

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3045]
**What happened?**
Tried to update the history information of a [node](https://www.thecrag.com/climbing/germany/sauerland/area/860021082):
![bulk_edit_form](https://user-images.githubusercontent.com/1528540/35860390-29d30dd0-0b44-11e8-83da-8478b8a6f541.png)

Got that error but I don't understand which data is missing.
![bulk_edit_error](https://user-images.githubusercontent.com/1528540/35860394-2e766ae4-0b44-11e8-8afd-2e386afc7b3c.png)
[URL](https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3AReturnURL=%2fclimbing%2fgermany%2fsauerland%2farea%2f860021082&C%3ACallingURL=5739561&C%3APID=5739552&C%3AState=18535&D%3ARoleAlias=Climbing%20Information%20Distribution%20Role&D%3AReviewedNodes=6&P%3A0%3AInformationNetworkID=7539484&C%3AHideNavigation=1)

**What you expected:**
* [ ] Form validation should highlight the erroneous field.
* [ ] Form validation should jump back to input form or
* [ ] Form validation is done on client and avoids server communication until validation okay.

**Comment by brendanheywood** [comment]
@lordyavin can you put more steps how to reproduce that screenshot before the error? That wide column layout is pretty bad :/

**Comment by lordyavin** [comment]
1. I started the bulk editing process
2. Filtered the form field to only show the history fields
3. Entered the history information
4. Tried to save.

**Comment by Mdemaillard** [comment]
similar to #2241

**Comment by rouletout** [comment]
Yes, same as #2241 - closing here
