### ISSUE TITLE
Display max heights for nodes below region

### ISSUE THREAD

**Issue by scd** [theCrag/website#3047]
**What happened?**

A gym can have very high walls, which can be a feature they wish to promote, but because some walls are not so high the average height of the area may be well below the height they wish to promote.

This also applies to outdoor areas. Heights have little meaning at region level.

**What you expected:**

 - [x] removed heights from node list displays in a gym
 - [ ] add max height statistic
 - [ ] remove heights from node list displays in a region
 - [ ] use max height statistic for everything below regions. 
 - [ ] including gyms

**Comment by brendanheywood** [comment]
I agree with this, but I think the same logic equally applies to outside too. I'd lean towards a max height.

This is also one of those stats that has very limited value once it has been rolled up to say the grandparent level regardless of what we use. I think we could easily just drop it at the region level.

**Comment by scd** [comment]
Yup.

**Comment by scd** [comment]
As we don't have a max height stat I have just taken the height out of node lists in gyms as a short term fixed and renamed this issue to represent the longer term fix.

**Comment by scd** [comment]
I do not see a strong need for this ATM, so closing. We may reopen later though when there is a stronger business requirement.
