### ISSUE TITLE
Each one ascent us being logged as eight in logbook

### ISSUE THREAD

**Issue by AndrewRR** [theCrag/website#3052]
Each appears that each ascent tick is being logged eight times in the log book.  The timelines also show lots of extra ascents.  I should only have 230 ascents total, but the website is showing >1000.

![image](https://user-images.githubusercontent.com/29109217/36070193-1e3230f0-0f4a-11e8-89d4-55dd1fdce0a3.png)

![image](https://user-images.githubusercontent.com/29109217/36070207-6b6bc110-0f4a-11e8-8bb7-cf9795e48ec1.png)

**Comment by scd** [comment]
This is the first time I have seen this. It is going to be easier to investigate if you also include a url (website link) to the problem page.

**Comment by scd** [comment]
I think it is a display issue not a logging issue.

**Comment by scd** [comment]
It looks like it was a hot fix I made this morning cause the site to go from 1 million ascents to 8 million. It is fixed now so there are not duplicate displays of the same ascents anymore
