### ISSUE TITLE
Map view doesn't render located children

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3055]
**What happened?**
I recently updated and located a bunch of nodes in the [Harz area](https://www.thecrag.com/climbing/germany/harz-mountains). Today I recognized that the map view doesn't list all located children. (Firefox ESR 52.6.0)

* [No child rendered](https://www.thecrag.com/climbing/germany/harz-mountains/area/265253628)
* [No child rendered](https://www.thecrag.com/climbing/germany/harz-mountains/area/265440381)

**What you expected:**
* [ ] Correct rendering of all located children
* [ ] BBox rendering of unlocated children with located grandchildren.

**Comment by nicHoch** [comment]
same for me in many areas also in chrome. 

- https://www.thecrag.com/climbing/spain/alto-mijares

**Comment by lordyavin** [comment]
Should this be a priority hotfix?

**Comment by scd** [comment]
@brendanheywood has something changed as far as you know. This is actually right the way through the site, in regions, etc.

I have done a bit of triage. The child data is still there in the html page:

```
var children = {
'265191945': {id: '265191945',i:'1', type:'Crag',name:'N&ouml;rdliches Harzvorland',geometry:[[11.0076327,51.8860707],[11.1065096,51.8860707],[11.1652178,51.8336989],[11.1504549,51.7946455],[11.0570711,51.8050489],[10.9918398,51.8186334],[10.9722704,51.8597864],[11.0076327,51.8860707]],cen: ["11.07004145637","51.84265157472"]},
'265253628': {id: '265253628',i:'2', type:'Crag',name:'Oberharz',geometry:[[10.4529947,51.9542851],[10.2593607,51.9644401],[10.2071756,51.9356616],[10.2071756,51.9356616],[10.1266665,51.8118416],[10.2768257,51.6860303],[10.4529947,51.6685243],[10.6526369,51.6208023],[10.7116884,51.7379154],[10.76868,51.8118416],[10.7116884,51.8619385],[10.4529947,51.9542851]],cen: ["10.44618439068","51.80294040286"]},
'265428636': {id: '265428636',i:'3', type:'Crag',name:'Unterharz',geometry:[[10.6945652,51.5803201],[10.6945652,51.6106052],[10.8592195,51.8260303],[11.0734529,51.7376723],[10.8592195,51.5262737],[10.6945652,51.5803201]],cen: ["10.87043395640","51.67380005550"]},
'265473219': {id: '265473219',i:'4', type:'Crag',name:'S&uuml;dharz',geometry:[[10.2768257,51.6860303],[10.4466433,51.6685243],[10.6526369,51.6208023],[10.677058,51.5498984],[10.5434447,51.5748782],[10.3628726,51.6109108],[10.2768257,51.6860303]],cen: ["10.49152249015","51.62109034696"]},
'1606405737': {id: '1606405737',i:'6', type:'Gym',name:'Kletteratelier Sangerhausen',geometry:[[11.29288,51.45373],[11.29328,51.45373],[11.29328,51.45413],[11.29288,51.45413],[11.29288,51.45373]],cen: ["11.29308000000","51.45393000000"]},
'1606408251': {id: '1606408251',i:'7', type:'Gym',name:'Kletterfelsen PeterStein20',geometry:[[10.78985,51.50325],[10.79025,51.50325],[10.79025,51.50365],[10.78985,51.50365],[10.78985,51.50325]],cen: ["10.79005000000","51.50345000000"]},
'1606411320': {id: '1606411320',i:'8', type:'Gym',name:'Kletterfels Wippra Ski- und Freizeitsportverein Wippra',geometry:[[11.27394,51.57197],[11.27434,51.57197],[11.27434,51.57237],[11.27394,51.57237],[11.27394,51.57197]],cen: ["11.27414000000","51.57217000000"]},
'1606412736': {id: '1606412736',i:'9', type:'Gym',name:'Outdoorfriend - Kletteranlage in der Apenke',geometry:[[10.24199,51.72662],[10.24239,51.72662],[10.24239,51.72702],[10.24199,51.72702],[10.24199,51.72662]],cen: ["10.24219000000","51.72682000000"]},
}
```

In `minor/mapTopo` line 245 the following line seems to fail.

```
if (!map.getBounds().intersects(bounds)){ return; }
```

with most of the children. There is some commented out code just after this line.

**Comment by brendanheywood** [comment]
That line simply says if the marker isn't within the map viewport then don't both adding it to the map, something has changed on the google side. I suspect there is a race condition where the map viewport is changing just after load. @scd if you comment out that line it will work, can you please hot fix that.

The line after it is just an unrelated visual debugging rectangle.

**Comment by scd** [comment]
I figured it was a change in google side of things. I have hot fixed. I presume things rendered off screen is a waste of cpu but will not hurt the UX.

**Comment by brendanheywood** [comment]
Yeah we add markers for the parent, current, siblings, and children and they all add up. But working is better than slightly slower. I'm just glad this wasn't a deeper bug giving the timing of the imminent rewrite.

**Comment by lordyavin** [comment]
@scd I don't agree that this doesn't hurt the user experience. JS is nowadays massively used on every website and slow JS does effect the user experience. Ordinary user isn't aware that website do calculations on their computer and if this computations are slow, the user does think it has to do with the internet connection. As far as the computer is in idle mode or the JS engine is quite smart, this won't hurt but if not the user will have to wait until theCrag is rendered completely. And this will repeat for every page. 

As a hot fix I agree with the solution but either you should reopen this issue until it is fixed without performance decrease or open a new issue to address this.

**Comment by brendanheywood** [comment]
@lordyavin if you think there is a performance issue then please make a new issue with an example url. I'm doubtful if there is a performance issue it is related specifically to this fix, the cpu and memory and pretty are well identical when I profiled it both ways but there might be particular nodes which are hit worse
