### ISSUE TITLE
Areas are not shown in Conutry overview anymore

### ISSUE THREAD

**Issue by AndreasAachen** [theCrag/website#3057]
**If I check the crags in Belgium I cannot see where the areas are located, even though it says they are linked**

https://www.thecrag.com/climbing/belgium

![belgium](https://user-images.githubusercontent.com/36492188/36233610-fbeb0aa0-123a-11e8-9376-3102a97951a7.png)

**Comment by scd** [comment]
This is a dup of #3055

**Comment by lordyavin** [comment]
Duplicate of #3055
