### ISSUE TITLE
Transparency around gym karma points

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3058]
**What happened?**

Gym edits don't currently acrue karma, this is by design but make this more transparent:

**What you expected:**

* [ ] mention this in the karma article
* [ ] show the points or lack thereof in the users karma table
* [ ] decide on business rules of community gyms vs paid gyms

**Comment by lordyavin** [comment]
I would quite like (prefer) the idea to earn karma if I put time into organizing/updating community managed gyms.

**Comment by scd** [comment]
I am closing this because gym updates now earn karma and have done for a while
