### ISSUE TITLE
Create a competition facet page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3060]
**What happened?**

Just cookie cutter new facet page which lists all competitions.

**What you expected:**

* [ ] show all competitions, at this stage the list could be just a table or maybe we can make a competition card similar to the crag crads. But not all comps have webcovers.

MVP Filter:
* [ ] by comp state: develop, pending, live, complete, archived

nice to have filters:
* [ ] start date / end date
* [ ] comps an account has participated in

The underlying sql logic should get re-used in a couple places too:
* [ ] under one of the top menus, probably ascents, we should list current comps

**Comment by rouletout** [comment]
These pages work now, closing
