### ISSUE TITLE
Crag cards not loading a static map fallback image

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3064]
**What happened?**

https://www.thecrag.com/favorites/by/weieran/?sortby=when,desc

![image](https://user-images.githubusercontent.com/187449/36464504-5b4dc620-1724-11e8-87ad-9d290d793d99.png)

**What you expected:**

* [ ] the first bug is probably because the node doesn't have a location. In this case it should be inheriting a location from it's nearest located ancestor
* [ ] second bug is unrelated google charts api rate limiting. I'm not sure if this is per browser or per host. This might be affecting everyone

**Comment by scd** [comment]
I think this is ok now. 

<img width="704" alt="Screen Shot 2019-07-01 at 10 30 50 am" src="https://user-images.githubusercontent.com/373058/60404341-5956ee80-9beb-11e9-932e-241bebba3ac2.png">
