### ISSUE TITLE
gym-report-xls 503 Error

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3065]
**What happened?**
Logged in as admin of [Klettwerk](https://www.thecrag.com/climbing/kletterwerk) and clicked [Aktion->Hallenbericht](https://www.thecrag.com/climbing/kletterwerk/gym-report-xls) and got 503 error page.

**What you expected:**
* [ ] A working report.

**Comment by nicHoch** [comment]
Might be an permission issue. I can confirm the 503 if logged in with the gym admin  but it is working with my normal admin account.

Am 21. Februar 2018 08:15:26 MEZ schrieb Kai <notifications@github.com>:
>**What happened?**
>Logged in as admin of
>[Klettwerk](https://www.thecrag.com/climbing/kletterwerk) and clicked
>[Aktion->Hallenbericht](https://www.thecrag.com/climbing/kletterwerk/gym-report-xls)
>and got 503 error page.
>
>**What you expected:**
>* [ ] A working report.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/3065

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by scd** [comment]
Ha, I laughed when I worked out what this was. It is the interaction between Microsoft arbitrary short restrictions on worksheet name lengths and german language translation of names to be super long.

In otherwords german translations crashed auto generation of Microsoft excel spreadsheets.

Kai, could you please retest and close the issue

**Comment by lordyavin** [comment]
Solved for me.
