### ISSUE TITLE
Gym routes with mixed colors

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3066]
**What happened?**
Often gyms use holds with more than one colour but currently it isn't possible to select or define mixed colours for routes.

![415cbioxhbl](https://user-images.githubusercontent.com/1528540/36535970-a54281c4-17cb-11e8-99a8-d488f83b64cb.jpg)
![41vyzhbfdwl](https://user-images.githubusercontent.com/1528540/36535998-bccd5b7a-17cb-11e8-9639-035c28869724.jpg)

**What you expected:**
* [ ] A predefined set of mixed colours or the possibility to to select more than one colour per route.
* [ ] Mixed colours shall be rendered on wall cards and index listings.

**Comment by brendanheywood** [comment]
If a gym is set up with a custom palette then we can have 'blue + white' as a set color. This is existing functionality for paid gyms. But this won't work if there is a really large variety of mixed colors as then the palette will be massive. The other benefit of this is the palette is named, so you could name the 'blue + white' as 'Swhirly blue clouds', and those names can be shown in the wall cards. I think this makes more sense for when the list of mixed colors is fairly small and would make the data entry faster. The custom palettes can be just about anything, a gradient, pattern or even a photo texture. So it could be a close up photo of the blue / white swirl on a hold.

If we don't have a custom palette configured, then we could allow multiple colors, but I'd probably limit it to 2 colors. However if we do have a custom palette I would still allow selection of 2 colors, and you would be able to select 'blue + white' and 'black + green'. ie perhaps you have a route which is made from both sets of holds in your photo above.

So how many different combinations of colors are there? If there is only say 20 pure colors and say 5 mixed colors then I think this is better done as a custom palette.

**Comment by lordyavin** [comment]
The above pictures are just arbitrary samples. Even though I translated some of the gym help articles, I wasn't aware that such a function exists for paid gyms. How is the custom palette configured?

I agree that a limit of two colours will probably be sufficient in most cases. I've never seen holds with more than two colours. I think it isn't a good idea to bloat the colour selector with mixed colours but I'm not sure how to teach editors that it is possible to select two colours. Hover tips?

**Comment by brendanheywood** [comment]
That new feature only went out in the last release, so it's only weeks old. It has not really been battle tested with a wide range of gyms so I'd prefer to get you using it first to see how far we can get with it before we consider writing more code. The custom palette at this stage is setup by us, in the long term we will make a better UI and allow the gyms to set this up.

I think the best approach here is if you could do a quick walk around the gym and just take a bunch of photos of every type of hold color scheme you can find (one pic close up of each hold might be easiest), stick them into a online share and send the link to the support email. When I can see that full list it will make it easy to determine whether the custom palette is going to work for you, and if it is I'll set it up for you (even if it's a community gym). And if it isn't then we at least have a good test case to inform the best solution for the next steps. I think if there is 30 or less colors the palette approach will work best.

**Comment by lordyavin** [comment]
I'll do next time in the gym. Maybe @nicHoch could reach out to the guys of the gym to request that images?

**Comment by nicHoch** [comment]
@rouletout is against asking the "customer" for photos of holds.

**Comment by lordyavin** [comment]
Is working for the Kletterwerk
