### ISSUE TITLE
Descent notes is not available for crag node type

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3068]
**What happened?**

https://www.thecrag.com/climbing/uganda/area/1671521307

Descent notes in route because it's not available as a crag field. This makes sense for small crags.

**What you expected:**

* [ ] field is available for crags

**Comment by Mdemaillard** [comment]
I don't have an issue with the proposal, but also don't really see the need here.

Let's look at a big crag, with a few sectors/features and a few routes each.
If a sector/feature has common descent (which might have been the reason to create it in the first place), descent info goes there.
If some routes do not share a common descent, the info does go into the route itself, or some annotation. Same can apply for above.

**Comment by scd** [comment]
I am closing because this did not get enough supporting evidence in the last two years,
