### ISSUE TITLE
Route is missing parent area in navigation

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3069]
**What happened?**

https://www.thecrag.com/climbing/uganda/route/1671607575

In the left hand nav the parent area is missing:

![image](https://user-images.githubusercontent.com/187449/36542629-7188aa06-1835-11e8-95da-5130b2837cc1.png)

**What you expected:**

* [ ] missing parent visible

**Comment by Mdemaillard** [comment]
possible link #2655

**Comment by lordyavin** [comment]
Please always provide screenshots to document the current state.
