### ISSUE TITLE
gym-wall-cards does not print all routes

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3076]
**What happened?**

This "sector" has 3 routes

https://www.thecrag.com/climbing/kletterwerk/area/544244850/

trying to print the cards via:

https://www.thecrag.com/climbing/kletterwerk/area/544244850/gym-wall-cards

only shows a card for the first 2 routes

might be due the fact that the second card is not filled with 2 routes .. 

**What you expected:**

* [ ] all routes on cards

**Comment by rouletout** [comment]
Not an issue anymore, closing
