### ISSUE TITLE
Could not log an aided alpine climb

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3077]
**What happened?**
I added the alpine route [Titanic](https://www.thecrag.com/climbing/argentina/route/1687420590) and logged it for the historic account of [Dean Potter](https://www.thecrag.com/climber/deanpotter). I wasn't able to log it as an aided climb.

![grafik](https://user-images.githubusercontent.com/1528540/36775153-1fcf7a16-1c61-11e8-9557-1db44ade13ad.png)

Since the route is in glacier region ice and snow may be an issue. Therefore I chose alpine as route style.

**What you expected:**
* [ ] Alpine routes can be aided.

**Comment by rouletout** [comment]
Available from next release on, closing
