### ISSUE TITLE
PDF Topos: Web covers not shwon

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3081]
**What happened?**

PDF topos do not show web-covers

**What you expected:**

Expect to see web-covers for areas and sub-areas

**Comment by brendanheywood** [comment]
Can you draw how you think this would actually work in a book layout? Would you use the 3 : 1 ratio webcovers? I think we could easily change the ratio to fit a bit better (eg the crag cards are 1 : 2) but I'm not sure well most webcovers would work if we forced them all to fit in say portrait A4 full bleed.

**Comment by brendanheywood** [comment]
closing this as dup of https://github.com/theCrag/website/issues/172
