### ISSUE TITLE
PDF Topos: tick icons not rendered

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3082]
**What happened?**

sometimes, the tick icons are not displayed on the personalised PDF, the space is taken in front of the route name but it is empty

(please also provide urls and screen shots)

**What you expected:**
Tick icons to be shown on personalized PDFs

**Comment by lordyavin** [comment]
+1! is bugging me today. Thought about printing a personalized PDF but without the tick icon it is useless.

**Comment by brendanheywood** [comment]
fixed

![image](https://user-images.githubusercontent.com/187449/40279689-2a49828e-5c8a-11e8-8cb6-dc8378b049d9.png)

**Comment by brendanheywood** [comment]
also dup of https://github.com/theCrag/website/issues/2929
