### ISSUE TITLE
PDF Topos: Ascent pie charts useful?

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3087]
**What happened?**

What are the criteria to show the pie chart of ascent styles per route? This just takes up space and has close to zero value. If you are not familiar with theCrag it is even incomprehensible. The chart for the star rating should have a legend like “Rating” (if we include it).

**What you expected:**

I would simply remove it - just takes up space

**Comment by scd** [comment]
Criteria is that this is done for the iconic climbs in an area.

**Comment by rouletout** [comment]
Wow, ok - nobody would ever guess that ;-) - I still think it is just a waste of space ;-)

**Comment by scd** [comment]
Not arguing. This was done a long time ago.

**Comment by brendanheywood** [comment]
+1 to ditch completely

**Comment by brendanheywood** [comment]
Removed
