### ISSUE TITLE
Gym: wall cards add "thecrag.com" to logo

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3093]
**What happened?**

our brand is not aware for each climber

![gym_logojpg](https://user-images.githubusercontent.com/2226714/36897239-0df040f8-1e16-11e8-8f00-e5125a4ba1ad.jpg)

**What you expected:**

the logo on the wall cards should mention "thecrag.com"

Kletterwerk: suggested it as well

only so the gym visitor can know that there is a platform at all

**Comment by brendanheywood** [comment]
There is a trello card for this already so removing this one
