### ISSUE TITLE
Gym: wall cards date format and translations

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3094]
Translate the wall cards: basically only "set by" to the language of the user that is printing the card.
also imply a proper date format from the user locale

![gym_date](https://user-images.githubusercontent.com/2226714/36897429-ca4a1c10-1e16-11e8-9cb7-f20738649c70.jpg)

**What you expected:**

* [ ] for german: DD.MM.YYYY

**Comment by lordyavin** [comment]
+1

**Comment by brendanheywood** [comment]
I'm going to split this into two issues:

1) the perl time2str which is formatting "23rd Mat 2014" isn't using the account locate and should (See #3096)

2) allowing gyms to set a custom date format

I think 1) is more important as this is everywhere across not only the FA / FFA for all outside routes but also in date strings anywhere in all the templates so I'd like to fix it first

**Comment by rouletout** [comment]
@nicHoch this is done, no?

**Comment by nicHoch** [comment]
![image](https://user-images.githubusercontent.com/2226714/107274843-40622080-6a51-11eb-8ee6-5748987bf955.png)
Dates are sensitive for the user language or page language.
