### ISSUE TITLE
Gym: wall cards optional visibility "set by" 

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3095]
https://www.thecrag.com/climbing/kletterwerk/area/544244850

![gym_setby](https://user-images.githubusercontent.com/2226714/36897621-a07139e0-1e17-11e8-9337-77d6b1fb35cb.jpg)

Kletterwerk would like to hide "set by" 

encapsulate that term with a extra css class where the visibility can be configured

**Comment by brendanheywood** [comment]
The history fa html now has everything marked up for individual styling:

![image](https://user-images.githubusercontent.com/187449/36941309-2248f27e-1fac-11e8-8bd2-168f7713605f.png)
