### ISSUE TITLE
Help Articles: TOC does not float

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3098]
https://www.thecrag.com/de/artikel/sensitivecrags

Translated another [article](https://sandpit.thecrag.com/de/artikel/sensitivecrags) and recognized that the TOC is not floating (Firefox ESR 52.6.0).

![grafik](https://user-images.githubusercontent.com/1528540/36967198-61293068-205f-11e8-8b25-07c650bccb29.png)

TOC shoudl float as in other articles.

**Comment by brendanheywood** [comment]
Ah, yeah that top heading clears it :/

This will be redone for the next release

**Comment by brendanheywood** [comment]
fixed
