### ISSUE TITLE
Gym: action menue gym entries missing in sup areas

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3099]
**What happened?**

In the action menu the gym specific action items "print lables" and "gym report" are missing for all nodes below the main gym node (sub areas). 
<img width="655" alt="2018-03-05 13_53_34-neue halle sport climbing _ thecrag" src="https://user-images.githubusercontent.com/2226714/36976123-c38420c0-207c-11e8-8dae-c0ebb52bc230.png">

**What you expected:**

* [ ] the same gym entries as in the TLC gym node in order to be able to export and print partial data.

**Comment by brendanheywood** [comment]
Fixed
