### ISSUE TITLE
We shouldn't allow future ascents, or photo taken date, to be logged

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#31]
http://www.thecrag.com/ascent/99378918

**Comment by brendanheywood** [comment]
I think we should do this as a low hanging fruit until we can sort the wishlists. We'd still allow future dates for mark / hit / target but nothing else.

**Comment by brendanheywood** [comment]
+1 from support but with photo taken field

**Comment by brendanheywood** [comment]
+1 via https://github.com/theCrag/website/issues/3274 (closed)

**Comment by brendanheywood** [comment]
+1 from support

**Comment by rouletout** [comment]
Will not be done, closing

**Comment by rouletout** [comment]
Will not be done, closing

**Comment by rouletout** [comment]
see also https://github.com/theCrag/website/issues/4138
