### ISSUE TITLE
Gym sector with routes does not show webcover

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3109]
I setup a webcover for a [sector](https://www.thecrag.com/climbing/kletterwerk/area/529723707) of a [gym](https://www.thecrag.com/climbing/kletterwerk) but the webcover is not displayed.

Webcovers should be displayed in all sub areas of gyms.

**Comment by scd** [comment]
Gyms are a moving beast, so I am not sure I want to commit to any business rules with web covers in gym sub areas - particularly subareas holding routes. 

Which photo?

Sub areas in gyms are sort of meant to be for easy ticking to they have their own template. We covers in sub areas of gyms may work against us. I would like to see the photo so I can understand this in more detail.

**Comment by brendanheywood** [comment]
https://www.thecrag.com/climbing/kletterwerk/area/529723707/webcovers/

**Comment by scd** [comment]
Ok it could be useful to show where the routes are. Having the visual cue would help a lot in my local gym

**Comment by brendanheywood** [comment]
No that is what the area topos are for, they are functional navigation. webcovers are designed to be eye candy

**Comment by lordyavin** [comment]
I agree that web covers for features (ropes) is not good. But the mentioned case is a sector (actually a room) where the individual problems are not labeled. Instead there is a color scheme for grade bands. Thats why there is now addtional feature child that may list routes. Since the node is a room I would like to have a webcover displayed.

**Comment by Mdemaillard** [comment]
Feature in a Gym in Test area does display webcover.
https://www.thecrag.com/climbing/test-area/area/3151102440

closing
