### ISSUE TITLE
Re-order tick types for bouldering so attempt & working are more accessible 

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3111]
**What happened?**

Broadly the tick types and groups of tick types should be ordered by how often they are used. 

![image](https://user-images.githubusercontent.com/187449/37259637-f6d0f33a-25dc-11e8-9ee9-a8241cd001ee.png)

**What you expected:**

* [ ] move the attempts tick types up as the second group under the boulder specific ones

**Comment by scd** [comment]
Triage notes:

This will be in Tick.pm. Order is defined in the config, but attempts is always ordered below the core ascents, so there is a minor refactor required.

**Comment by Mdemaillard** [comment]
see #3158 for broader discussion. should possibly close this one ?
