### ISSUE TITLE
Slashgrades not correctly parsed

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3113]
**What happened?**
It's very cool that slashgrades are now correctly parsed! Generally, it seems to work fine, but in one case, something went wrong. See here:

https://www.thecrag.com/climbing/germany/oberbayern/route/1706606121

"9-/9" is entered as the grade, "9-/" is displayed

**What you expected:**

9-/9 displayed.

**Comment by scd** [comment]
Ha, that looks like an edge case display algorithm error. Nice find :)

**Comment by scd** [comment]
This is fixed in simons dev:

         "systemText" : "UIAA",
         "input" : "9-/9",
         "grade" : "9-/9",
