### ISSUE TITLE
competition board: grading chart default in AU

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3116]
**What happened?**
the ascent grade chart for that competition is in AU and not FR.
All ascents are in FR and also the default grading system for the connected node is FR:

https://www.thecrag.com/climbing/spain/valencia-cuenca-area

https://www.thecrag.com/competition/2018-horzelbuben-ostern

<img width="587" alt="2018-03-14 10_37_38-horzelbuben osterwettkampf 2018 _ thecrag" src="https://user-images.githubusercontent.com/2226714/37394539-491d0dac-2774-11e8-8821-041ed64312b7.png">

**What you expected:**

a way to config the grading of the chart 
or correct auto detected grading

**Comment by scd** [comment]
In the top level of the competition config json use 

 "gradeSystem": "FR",

@nicHoch this config item has not been tested yet so can you please try it and let me know how it goes.

**Comment by nicHoch** [comment]
works well
