### ISSUE TITLE
competition board: hangman table not readable text

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3117]
**What happened?**
After redesign of the competition board
https://www.thecrag.com/competition/1236877083

the hangman letters are not visible if you logged in.
It is white font on white background.

<img width="562" alt="2018-03-14 10_31_42-dach 2017 meetup _ thecrag" src="https://user-images.githubusercontent.com/2226714/37394815-fc0b4172-2774-11e8-8cac-0a2dd64bc28f.png">

In the screenshot a marked some letters - to see the effect

**What you expected:**

* [ ] readable letters

**Comment by scd** [comment]
@nicHoch does this need to be fixed for your easter comp?

**Comment by nicHoch** [comment]
no

**Comment by brendanheywood** [comment]
fixed

![image](https://user-images.githubusercontent.com/187449/37457870-54bcdbf0-2897-11e8-9f4b-81d7cc5fe32c.png)
