### ISSUE TITLE
area cards: default grading system for boulder areas 

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3118]
**What happened?**
The area card grade chart provides the V-boulder grade system even for French areas like Fontainbleau

<img width="246" alt="2018-03-14 21_09_56-areas in fontainebleau _ thecrag" src="https://user-images.githubusercontent.com/2226714/37428358-4a49b36c-27cc-11e8-8759-e6de45f7f2cb.png">

**What you expected:**

* [ ] correct auto detection of the grade system FB/FR in this case.

**Comment by Mdemaillard** [comment]
Working now for Fontainebleau:
https://www.thecrag.com/search?S=fontainebleau
![image](https://user-images.githubusercontent.com/60388146/77903266-dbf80180-7282-11ea-83de-78de930e4933.png)

I checked randomly a few areas in different countries and grades system, seems working overall. Please reopen if some specific issue is found ?
