### ISSUE TITLE
TR solo ticks counted as solo on Notable ascents. 

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#3121]
TR solo ticks are counted as solo for the purposes of the notable ascents table.

I know you're looking at dropping/redoing the section, but while it still exists this is a little misleading. 

(please also provide urls and screen shots)
![image](https://user-images.githubusercontent.com/22091505/37498368-12ec6116-2912-11e8-94af-625736dbfe39.png)

**What you expected:**

* I would count solo as ropeless for the purposes of notable ascents. 
* TR solo ascents would be rolled into TR (and ignored if you have any lead ascents) 

Otherwise use the orange Top tick in the summary to make it more obvious that they aren't a free solo ascent

**Comment by lordyavin** [comment]
+1

**Comment by brendanheywood** [comment]
@DaneEvans this should be fixed so closing, bump this if you think otherwise
