### ISSUE TITLE
Edit comp button is visible

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#3122]
@scd 
The edit comp button for the easter comp is visible to me as a logged in user. 
I can also click on it ... I'm not going to see whether I can make changes...  

![image](https://user-images.githubusercontent.com/22091505/37503899-2a32cb86-292f-11e8-8dbc-a27ecd0d4562.png)

![image](https://user-images.githubusercontent.com/22091505/37503889-2355ec80-292f-11e8-9c5e-75b9b7b991d6.png)

(please also provide urls and screen shots)

**What you expected:**

These to not be visible to general users

**Comment by brendanheywood** [comment]
@scd  I've just hot patched this with a dodgy hack

**Comment by DaneEvans** [comment]
Seems to have worked

**Comment by DaneEvans** [comment]
It's back again... most recent release?

**Comment by scd** [comment]
@DaneEvans thanks for the headsup. Can you please test again

**Comment by DaneEvans** [comment]
and hidden again

**Comment by brendanheywood** [comment]
@scd can we close this as properly done now?
