### ISSUE TITLE
merging routes results in inconsistent grades / names which cannot be edited

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3123]
**What happened?**

When merging two routes with entries having different grades, the resulting grade is a mix of both and cannot be fixed. I assume this behaviour is wanted (preserving the Route Grade Citations), but very confusing. Shouldn't be the community registered grade the one shown in the crag listing?

[See here, route #6](https://www.thecrag.com/climbing/france/fontainebleau/area/447336708)

Additionally, also the name of the "feature" in the above link has a kind of undefined state. I cannot remove its alternative name. Error: { "alternateNamesError" : "name 'Sea blue circuit (nº 5)' does not exist, so cannot be deleted." }. This feature is the result of a merge. There was any children present twice before the merge, I merged all of the seperately before (with the result described above).

**What you expected:**

A more consistent behaviour of the merging process.

P.S. If you can, please remove the alternative name of this circuit.

**Comment by scd** [comment]
I think the merge does not save the registered grade properly. In the atom we have a record:

```

grade: "3B - 4B",
input: "3B",
isPrinciple: "true",
systems: {
FB: [
"3B",
"4B"
]
}
```

I think Input should be updated to '3B - 4B'. 

Given that there is a problem, bulk edit should also handle this bad data better.

**Comment by scd** [comment]
Bulk edit uses the 'input' grade to compare if it needs to update the grading system. As the input Grade is 3B the system does not see that the grade needs fixing. If you change the grade from 3B to say 4B then it will fix itself. 

You can then update again to get back to 3B. 

I know this is fairly boring but once I fix the merge issue this will no longer happen. There will be a handful of these cases that need sorting out.

I don't want to spend time changing the bulk edit.

**Comment by scd** [comment]
Note to self, look for RouteGradeContributionFreeTextDisplay in Application/MergeNode.pm and add the Input field as well.

**Comment by scd** [comment]
I have just fixed the merge side of this bug, which means it will be fixed for future merges.

The data issue is unfixed, but as there is a simple workaround to fix the data by editing the route twice in bulk edit I do not propose to do any further work on this issue. Note that this decision is based on a huge backlog of priority work.
