### ISSUE TITLE
CPR Article empty space

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3125]
**What happened?**
Below the heading are a few centimeters of empty space. See screenshot:

<img width="814" alt="screen shot 2018-03-18 at 17 53 51" src="https://user-images.githubusercontent.com/19162952/37573482-a1c11f34-2ad5-11e8-9a8c-81834549be93.png">

**What you expected:**
Nicer formatting of the article

**Comment by brendanheywood** [comment]
Closing as a duplicate of this: https://github.com/theCrag/website/issues/3098
