### ISSUE TITLE
Route Quality graphic doesn't update

### ISSUE THREAD

**Issue by tomkjaerolsen** [theCrag/website#3127]
The route quality graphic doesn't always update when people add tickets. I think this happens after a route has been moved between areas.

Example: https://www.thecrag.com/climbing/australia/queensland/pages-pinnacle/route/936931656

Route quality graphic shows this, which has some good and some classic. 
![image](https://user-images.githubusercontent.com/7426019/37744068-fb1f8e04-2db8-11e8-92aa-ed880d522759.png)

However the last two ticks were "very good"
![image](https://user-images.githubusercontent.com/7426019/37744088-10b68f60-2db9-11e8-86c9-0ef1a2756ca1.png)

I've seen this on a number of climbs.

- Tom

**Comment by brendanheywood** [comment]
Re-checked, still an issue. Something is quite srewy here, some of the ratings have negative counts, and the overall count is -6!

![image](https://user-images.githubusercontent.com/187449/47466110-80c71180-d83b-11e8-975d-335559560da3.png)

**Comment by brendanheywood** [comment]
```
qualityProfile: [
0,
0,
0,
6,
-13,
1
],
```

**Comment by rouletout** [comment]
This looks correct now - eg there are 5 "classic" shown and 5 users have marked it as such...
