### ISSUE TITLE
Allow comments on each pitch when logging an ascent

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3129]
**What happened?**
We now accept grades, tick type, and who for each pitch but in hind site we are missing the most obvious thing which is comments per pitch. Check out this ascent:

https://www.thecrag.com/ascent/1729819737

![image](https://user-images.githubusercontent.com/187449/37946669-5112cd7c-31d2-11e8-985f-463d65c07d0d.png)

**What you expected:**

* [ ] Each pitch has comments for it after the grade and tick type

**Comment by lordyavin** [comment]
+1

**Comment by scd** [comment]
This will be available in the new tick flow after the next release.
