### ISSUE TITLE
Clarify and refine AF all free tick type

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3131]
**What happened?**

https://www.thecrag.com/discussion/1730194191/please-review-above-tickage-p#m1733253441

https://www.thecrag.com/article/TickTypes#allfreewithrest

**What you expected:**

There is also clearly a lot of people want to use a tick type like this because they don't understand dog. Or perhaps they prefer this as it better describes what they did with less negative connotations.

Some ideas on the table:

* [ ] update the description of the tick type
* [ ] update the name.
* [ ] The all free icon could be the red hollow circle
* [ ] see how hard it is to introduce tick types filtered to certain locations

**Comment by rouletout** [comment]
Done in new help with next release - closing
