### ISSUE TITLE
Swap primary action in listview from edit to tick

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3134]
**What happened?**

Ticking should be the primary action, for every edit there will be 10's or 100's of ticks

![image](https://user-images.githubusercontent.com/187449/38226355-84698336-373c-11e8-8a67-1c99ac670b4d.png)

**What you expected:**

* [x] tick as primary action
* [x] edit as secondary action
* [x] not broken menu when you cannot edit
* [ ] make lick process return to listview with hash anchor back to where you were

**Comment by brendanheywood** [comment]
We need to redo the list view table in bem and mobile first before we tackle this

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76840792-6cc0ed00-6840-11ea-824f-3aaee0040479.png)

Tickboxes 1 and 2 done.
Tick 3 looks fine to me, in areas where i don't have edit rights, the edit is greyed out.

Box 4 open, it return to list view but top of the page.

**Comment by lordyavin** [comment]
@Mdemaillard just check the checkboxes if the items are done

**Comment by Mdemaillard** [comment]
I cannot edit other user's posts ? or is there a way that i don't know yet ?

**Comment by lordyavin** [comment]
To check the boxes you don't need to edit the post. Just check them. If it doesn't work you are missing the privileges I think.

**Comment by Mdemaillard** [comment]
Pretty please can i get the privilidges ? On a bonus note, maybe you'll get less spam that way

**Comment by lordyavin** [comment]
@theCrag/thecrew I'm not sure if I'm allowed to change the privileges of Marc. Please consider upgrading his role.

**Comment by Mdemaillard** [comment]
see #1542 for remaining point
