### ISSUE TITLE
Regression with star styles, in both text versions and svg versions

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3135]
**What happened?**

no stars:

https://www.thecrag.com/climbing/australia/arapiles/organ-pipes/route/12879769

blue stars:

https://www.thecrag.com/ascents/with-route-stars/2/?sortby=when,desc

white stars

https://www.thecrag.com/climbing/world/photos

**What you expected:**

* [x] svg isn't loading (wrong domain)
* [x] text stars when svg stars should be showm (not photo titles)

**Comment by lordyavin** [comment]
Bugged me too

> 404: The requested URL /svg/star was not found on this server.

**Comment by brendanheywood** [comment]
Fixed and hit fixed
