### ISSUE TITLE
In forum thread page, show list of participants in order of when they joined the thread 

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3139]
**What happened?**

The order at the moment is seemingly random, would be good to make it the same order as when they joined. Not sure what to do about people who were invited but ave never posted, or who have since left.

**What you expected:**

* [x] make order explicit, when they first posted
* [ ] show people who have left somehow
* [x] if people have joined but not posted maybe show them last if we don't have a joined timestamp
* [x] show how many posts each person has added to the thread

**Comment by DaneEvans** [comment]
+1 
Was just about to post that one Brendan... same example thread too

**Comment by brendanheywood** [comment]
As a quick work around I've double the page size from 50 to 100. I can't really see any compelling technical or ux reason for a limit of 50, and I just ran the stats and only 11 threads have ever gone past 50 and none past 100.

**Comment by brendanheywood** [comment]
hot fixed
