### ISSUE TITLE
Some grade use comma which erroneously get used as pitch grades

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3141]
**What happened?**

For example in this area https://www.thecrag.com/climbing/united-states/potash-road/area/16955899  many routes are recorded with a comma in the grade from the Dessert Rock guidebook, for exampl 'I, 5.8' in the following route:

https://www.thecrag.com/climbing/united-states/potash-road/route/19405105

and are thus displayed as multi pitch routes (numbers in circles) even though they are recorded as single pitch routes.

**What you expected:**

Display as single pitch routes with one grade

**Comment by brendanheywood** [comment]
I don't think we should attempt to have it both ways and accept every format we see in the wild. I see this as just a data quality issue that needs to be cleaned up.

**Comment by rouletout** [comment]
Fine with me - I just need to know what to do

**Comment by brendanheywood** [comment]
Just edit and remove all the "I" bits from the grades. What are they even supposed to mean? Are they an alternate grade or an aid grade or something?

**Comment by rouletout** [comment]
I have no idea! The problem is, I can't see them when I edit the route, i have to open each route and edit the specific grade contribution - there are hundreds... Is there an easier way?

**Comment by scd** [comment]
You need to edit the Desert Rock grade entry (Action -> Route grade -> Update grade contribution) and remove the comma.

![screenshot from 2018-04-09 11-38-19](https://user-images.githubusercontent.com/373058/38475308-a0988c20-3bea-11e8-8b41-6d5178e619fd.png)

**Comment by scd** [comment]
No easier way right now.

**Comment by rouletout** [comment]
ok so leave it open - this is for some other time....

**Comment by scd** [comment]
Yes probably best. There are some mutlipitches and some strange formats, for example

https://www.thecrag.com/climbing/united-states/potash-road/route/16955275

So even writing a script will not help

**Comment by lordyavin** [comment]
Hey @brendanheywood and @rouletout found that info on [Wikipedia](https://en.wikipedia.org/wiki/Grade_(climbing)#Yosemite_Decimal_System):

>The YDS system involves an optional Roman numeral grade that indicates the length and seriousness of the route. The Grade is more relevant to mountaineering and big wall climbing, and usually not stated when talking about short rock climbs. The grades range from grade I to VI spanning a one-hour climb to a multi-day climb respectively.[6]
>
>I–II: 1 or 2 pitches near the car, but may need to be avoided during avalanche season.
>
>III: Requires most of a day perhaps including the approach, which may require winter travel skills (possible avalanche terrain, placing descent anchors). The East Buttress route on Mt. Whitney is a grade III,[7] yet it requires 1,000 feet of technical climbing and a total gain of over 6,000 vertical feet from trail head to summit. Only a minority of climbers, the most fit and seasoned, could do this route car to car in a day. Other grade III climbs, such as Cathedral Peak in Tuolumne, are typically done in one day.
>
>IV: A multipitch route at higher altitude or remote location, which may involve multi-hour approaches in serious alpine terrain. A predawn start is usually indicated, and unforeseen delays can lead to unplanned bivouacs high on the route.
>
>V: A multi-day climbing adventure for all but the elite few. The route, Dark Star, on Temple Crag is grade >V[8] and involves a seven-mile approach and over 2,200 feet, 30 pitches[9] of technical climbing.

>VI: A multi-day climbing adventure for all. Peter Croft saves this grade for the mythical Palisade >Traverse, a massive route which includes six 14,000-foot summits and miles of technical climbing.[9] He >states, "This is the only route in this book that I haven't completed in a single push, although I've done all the crux sections at various times."
>
>VII: Under discussion.

**Comment by brendanheywood** [comment]
Ah yes, we've come across a range of various mountaineering grade systems before and haven't brought any of them into the system yet:

https://en.wikipedia.org/wiki/Grade_(climbing)#Mountaineering

**Comment by scd** [comment]
Correction, we have a lot of them in the system just not fully configured and not in our articles.

**Comment by brendanheywood** [comment]
We should show everything in the article, https://github.com/theCrag/website/issues/3143

**Comment by brendanheywood** [comment]
https://www.thecrag.com/climbing/canada/bon-echo/route/102647988

![image](https://user-images.githubusercontent.com/187449/61169882-a51f7580-a5a5-11e9-8d73-31c3ade0b5f7.png)

**Comment by rouletout** [comment]
Data were cleaned a while back, closing
