### ISSUE TITLE
URL endpoint: https://www.thecrag.com/climbing/germany/falkenwaender

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3142]
**What happened?**
The crag [Falkenwand](https://www.thecrag.com/climbing/germany/falkenwaender) has the URL endpoint *falkenwaender*.

**What you expected:**
*falkenwand* or *falkenwaende* but no trailing *r*

BTW: Why are URL endpoints not automated?

**Comment by brendanheywood** [comment]
It's on the list: https://github.com/theCrag/website/issues/1306

That url already exists for a different node, which also highlights some of the inherent difficulty in getting the automation of this right:

https://www.thecrag.com/climbing/germany/falkenwand

This now works, and the old url will continue to work:

https://www.thecrag.com/climbing/germany/falkenwaende
