### ISSUE TITLE
'who' selector in ascents facet selected broken usernames with @ in them

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3149]
**What happened?**

Go to the ascents facet and search and add various people. Some are added without a @ and they work, and other are added with a @ which do not work, eg:

![image](https://user-images.githubusercontent.com/187449/38840085-321aa4c6-4221-11e8-8cb4-304f07df570c.png)

https://www.thecrag.com/climbing/world/ascents/by/alanezzy+kadazz+@deeno/?sortby=when,desc

I cannot figure out why certain accounts are failing like this but they are consistent:

```
No account '@caesar'
No account '@flatpeach'
No account '@deeno'
No account '@simpledimples'
```

Root cause is only the first @ is working, all second third etc are broken

**What you expected:**

* [ ] all @ working

**Comment by brendanheywood** [comment]
fixed

**Comment by scd** [comment]
What did you do to fix this. There may be a consistency issue:

The by field for ascents only accepts login so we never required the `@`. The @ has been introduced to who fields that can take free text search and a login search.

**Comment by brendanheywood** [comment]
I think this bug has always been there, the js was doing a replace instead of a replace all to remove the @ and the way it worked meant that the first 2 @ accounts worked but none after that.

I have not changed the semantics of the 'account' class of facet filters which only accepts accounts and does not have a @ (eg /ascents/by/brendanheywood) vs the 'mention' class of filters which can accept either free text or a @ mention (eg /routes/by/brendan and /routes/by/@brendanheywood route FA filters)

https://www.thecrag.com/ascents/by/brendanheywood/  (account)

https://www.thecrag.com/routes/by/brendan/ (mention)
https://www.thecrag.com/routes/by/@brendanheywood/ (mention)

**Comment by scd** [comment]
+1
