### ISSUE TITLE
Fuzzy/Text search for Ascents and Routes

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3152]
**What happened?**
The facet search should contain a free-text field for route names.

**What you expected:**

For example, I would like to find all routes (or just my ascents) with a name containing "Gedenkweg" under the node "Frankenjura Nord". This is already possible using the "Nodes"-type facet search, but you cannot filter these results any further.

**Comment by brendanheywood** [comment]
I'm going to close this as a duplicate and it's covered by 2 other issues:

https://github.com/theCrag/website/issues/799 Align / merge site text search with faceted search

https://github.com/theCrag/website/issues/2881 Home page and top header universal simple search box

These have been schedules already tentatively for 2 months away (famous last words)
