### ISSUE TITLE
Quality rating of routes doesn't match stars, finish merging these concepts

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#3153]
**What happened?**

The stars and the quality rating of a route does sometimes not match. For example could a route have a rating of 100% but only two stars.

**What you expected:**

100% should have 3 stars :)

**Comment by Drazhar** [comment]
![screenshot_20180421-100936](https://user-images.githubusercontent.com/3040689/39082028-7edf0ac6-454c-11e8-85f6-fec901723b4f.png)

**Comment by brendanheywood** [comment]
Can you please post the exact url for that page?

**Comment by Drazhar** [comment]
https://www.thecrag.com/climbing/germany/frankenjura/routes/with-gear-style/sport/?sortby=quality,desc

**Comment by brendanheywood** [comment]
Thanks - even weirder is when you sort it by stars then it's not even in star order either:

https://www.thecrag.com/climbing/germany/frankenjura/routes/with-gear-style/sport/?sortby=stars,desc

![image](https://user-images.githubusercontent.com/187449/39104173-73e9f8d6-46f2-11e8-838a-1dad34231b56.png)

**Comment by Mdemaillard** [comment]
Quality seems not to be accessible anymore. Merge with stars done ?
![image](https://user-images.githubusercontent.com/60388146/76688338-8261c700-6634-11ea-8f98-a80b367afcf1.png)


Sorting by star is still not clean
https://www.thecrag.com/climbing/south-africa/kwa-zulu-natal/routes/?sortby=stars,desc&page=3
![image](https://user-images.githubusercontent.com/60388146/76688371-be952780-6634-11ea-9a83-d37c52d8b853.png)

**Comment by Drazhar** [comment]
Just to push this up again.

Lately I see many cases where the stars don't match the user quality ratings. I try to find some examples:

- [https://www.thecrag.com/en/climbing/france/les-traverses/route/2662888632](One ascent with "Mega Classic" but only 2 stars)

**Comment by rouletout** [comment]
Thanks for that - please keep collecting :-)

**Comment by scd** [comment]
I found two bugs here.

1. We were including contributions which no star rating as a zero rating.
2. Disabled publications were included in the stats but not shown in the route page.
