### ISSUE TITLE
be able to select mulitiple routes and then deep link to the reparent process

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3154]
**What happened?**

We should be able to select and then move routes or areas in the same way as we can batch tick and edit:

https://brendan.thecrag.com/processmap/logascent_multi/13332313+13332361?parent=12094657

https://brendan.thecrag.com/processmap/bulkedit/13332313+13332361?select=0

**What you expected:**

* [ ] Select and deeplink to reparent process and skip a few steps, eg

https://brendan.thecrag.com/processmap/reparentnode/13332313+13332361?parent=12094657

**Comment by brendanheywood** [comment]
Hmm just tried this manually and that link above doesn't actually work, it only picks up the first node in the list. @scd what is the correct url for moving multiple nodes?

**Comment by brendanheywood** [comment]
+1 from discussion, this needs to be more discover-able / usable

**Comment by brendanheywood** [comment]
+1 support

**Comment by DaneEvans** [comment]
I swear I used to be able to do this. 

Maybe I used to create a new one, then make the existing a daughter to that

+1 anyway

**Comment by brendanheywood** [comment]
If you do a reparent from an area, the first step in the process is whether you want to reparent this area, or the children of this area, and if the latter then you get to select them all. This issue is about skipping all those steps and selecting the children right at the start before you even start any process.

Where exactly do you get stuck with the reparent of routes? I just tried it and seems fine to me

**Comment by DaneEvans** [comment]
it's redirecting to rearrange ... odd now it seems to be working. 

An artifact of having a mixed route/sub areas crag perhaps?

**Comment by brendanheywood** [comment]
It's hard to tell without knowing exactly what page you are looking at. We do hide and show things that are more / less relevant

**Comment by DaneEvans** [comment]
it was https://www.thecrag.com/climbing/australia/orroral-ridge/echidna-rocks

0) it had routes and annotations
1) I added sub areas, 
2) I tried to move the routes into one of the sub areas, I couldn't and had to enter the route page and move them individually from there. 
3) I copied, then deleted the annotations

I may have also changed one or more area types in this process. Honestly, I think user error is probably the answer

**Comment by brendanheywood** [comment]
Another +1 from support email

**Comment by brendanheywood** [comment]
+1 from @jalonavens via https://github.com/theCrag/website/issues/3443

**Comment by nicHoch** [comment]
+1

**Comment by scd** [comment]
This is done

**Comment by lordyavin** [comment]
Don't forget to check the checkbox of todos in initial comment :wink:
