### ISSUE TITLE
Annotations missing from list of nodes for the purpose of resequencing

### ISSUE THREAD

**Issue by scd** [theCrag/website#3157]
**What happened?**

If an area has annotations then these are not shown on the map for the list of routes. This means it can be difficult to resequnce a route to just above an annotation.

**What you expected:**

Expect to be able resequnce annotations from map and also reseqence routes to just above annotations

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76688423-31060780-6635-11ea-86c0-d66a57e0242d.png)

This has been done. Closing.
