### ISSUE TITLE
Grades: Strange grade display

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3161]
**What happened?**

Look at this route, the entry looks ok but the grade is displayed as ```8c+/9aa```

https://www.thecrag.com/climbing/italy/central-and-southern-italy/rome-area/route/1774698552
<img width="" alt="screen shot 2018-04-26 at 14 31 09" src="https://user-images.githubusercontent.com/19162952/39367870-3a628bea-49f5-11e8-8e6d-8ea30bf813e6.png">

**What you expected:**

* [ ] Grade displayed as ```8c+/9a```

**Comment by scd** [comment]
Fixed in Simon's dev. Also added it as a test case for unit testing.
