### ISSUE TITLE
When logging multi pitch routes, allow removal of first pitch and addition of more routes

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3163]
**What happened?**

![image](https://user-images.githubusercontent.com/187449/39416169-3b6288ec-4c8e-11e8-8c7e-6660d3abe4ee.png)

**What you expected:**

* [ ] allow removal of first pitch
* [ ] all additions after last pitch

**Comment by scd** [comment]
This is not an issue in the new tick flow
