### ISSUE TITLE
Route Grade Distribution Graph has weird width

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3164]
**What happened?**

The width of the bars on the grade distribution graph is not the same, for example:
https://www.thecrag.com/de/competition/2018-la-sportiva-90-years

See green bars on chart
<img width="320" alt="screen shot 2018-05-01 at 16 58 01" src="https://user-images.githubusercontent.com/19162952/39525217-9953f2e2-4dd8-11e8-8e3d-173d98786b4b.png">

**What you expected:**

Same width of all bars

**Comment by brendanheywood** [comment]
To be clear, all the bars should not actually be the same width. Some grades are wider than others, eg 5.8 is roughly the 3x the width of 5.11a

The only slight bug I will address here is that some of the green bars on inconsistent with each other despite being the same thinner width than the yellow and orange bars.

**Comment by Mdemaillard** [comment]
Is that bar width = width of grade documented anywhere ? I understand but it is not intuitiv and i was not aware. Had i noticed, i would also have thought bug rather than feature.

**Comment by rouletout** [comment]
This should actually be explained here: https://www.thecrag.com/en/article/gradesonthecrag#article.gradesonthecrag.header.grade-bands

Let me add that to the article updates for the next update. I close this here.
