### ISSUE TITLE
Printing any web page should be a little bit more streamlined, eg remove nav, footer, set fixed width

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3165]
**What happened?**

Any page on the site when printed should have a few tweaks to make it work better on paper.

**What you expected:**

* [x] do we provide a way for people to do a 'as seen in the browser' print? or just let them do a screenshot and print that? Or do we have an explicit 'print this page' which applies this print css? (opted for brutal, print styles you can't opt out of)
* [ ] remove left nav
* [x] remove footer
* [ ] remove tabs and most nav, but probably keep crumb trail for context (invert colors?)
* [ ] fix width to standard paper size
* [ ] maybe swap some colors around
* [x] hide stream
* [ ] remove actions sub regions and selected other buttons

https://www.smashingmagazine.com/2018/05/print-stylesheets-in-2018/

**Comment by lordyavin** [comment]
+1

**Comment by brendanheywood** [comment]
Done enough for release
