### ISSUE TITLE
Outline of help page hides content

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3167]
**What happened?**

The grade comparison table for sport and trad routes is too wide and the outline of the article overlaps the 3 right most columns.

https://www.thecrag.com/de/artikel/grades#trad-und-sportbewertungsskalen

![image](https://user-images.githubusercontent.com/187449/40101739-b2f86760-592b-11e8-94aa-98eb8f1b8823.png)

**What you expected:**

* [ ] Table has the same width as the text or
* [ ] Outline can be collapsed

**Comment by brendanheywood** [comment]
This is already fixed but not yet released. I've tagged it as 'almost done' and will keep it open until it's on prod

**Comment by brendanheywood** [comment]
Oops mixed this one up with https://github.com/theCrag/website/issues/3098

But I did prototype a solution to this a while back by making the table headers 45 degrees which is a partial solution eg:

![image](https://user-images.githubusercontent.com/187449/39759963-632bd0f6-5317-11e8-8028-53162d32269f.png)

**Comment by Mdemaillard** [comment]
Under small width, there is still overlap but the table is readable. One can always scroll to get to the navigation menu again. 
No problem on mobile at all. Solved for me.

![image](https://user-images.githubusercontent.com/60388146/76688740-26993d00-6638-11ea-9fdb-d0eab5614741.png)
