### ISSUE TITLE
Regression ascent facet Apply Filters is not working in UI

### ISSUE THREAD

**Issue by scd** [theCrag/website#3175]
**What happened?**

The Apply Filters button on the acents facet is not triggering.

It is working for other facets (tested photos and webcovers).

**Comment by brendanheywood** [comment]
Works for me?

https://www.thecrag.com/climbing/australia/ebor-gorge/ascents/?sortby=when-climbed,desc

What url is it failing on?

**Comment by scd** [comment]
https://www.thecrag.com/ascents/by/scd/

**Comment by brendanheywood** [comment]
I've fixed this in dev in facet.js needs a hotfix

**Comment by scd** [comment]
hotfixed
