### ISSUE TITLE
CPR drill down broken

### ISSUE THREAD

**Issue by scd** [theCrag/website#3177]
**What happened?**

Clicking on a CPR graph column does not show the ascents for the drill down.

This looks like the wrong thing is being passed to the url - see the hash in the url in the screen shot

![screenshot from 2018-05-19 09-43-40](https://user-images.githubusercontent.com/373058/40262294-9d073a2e-5b49-11e8-8d56-73b2d82baa82.png)

**Comment by scd** [comment]
I think there are two problems here.

From the url.

https://www.thecrag.com/ascents/has/gym-boulder-cpr/by/scd/?sortby=rating,desc

Clicking on one of the columns leads to this url

https://www.thecrag.com/climbing/world/ascents/aggregate/graph-gym-boulder-cpr/has/gym-boulder-cpr/by/scd/HASH(0x7faab46029b8)/between/2018-5-10+2018-5-16?sortby=rating,desc

So the HASH is one issue. The other is that we are swapping from ascents facet to ascents aggregate.

It should be something like:

https://www.thecrag.com/ascents/has/gym-boulder-cpr/by/scd//between/2018-5-10+2018-5-16?sortby=rating,desc

@brendanheywood can you have a quick look as I will not be able to look into this for a while. I think that the HASH is a long term bug, but swapping to the aggregate is something that has changed recently.

**Comment by brendanheywood** [comment]
I'm on it

**Comment by brendanheywood** [comment]
This was a recent regression as part of the link_to migration, it's fixed and hotfixed

**Comment by brendanheywood** [comment]
btw there was only 1 problem, the baseurl just changed from a string to object and it turned into a relative link from the current page
