### ISSUE TITLE
"View edit history" not working as expected

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3179]
**What happened?**

While on the detail page of a route, there is an option to "view edit history". However, most types of "edit" are not shown there, among them route creation and renaming.

**What you expected:**

Show as many edits as the data model currently allows. I suspect that at least the creation date plus user should be available.

**Comment by scd** [comment]
The streams are meant to show this level of edit history. Route
descriptions are also versioned so you can see the route description
history.

We are not going to change functionally here, but we should make it clearer
on what the link does.

**Comment by quaestor** [comment]
The streams are fine for recent changes, but it gets complicated to find out who created or changed a route if it's buried in the stream due to a lot of activity.

**Comment by scd** [comment]
Can you please provide a url of a route where this is complicated?

**Comment by quaestor** [comment]
Ok you're right, it was just incompetence on my side, I searched the streams of the crags instead of the route's streams. However, streams don't go back to before 2010, so route creation date and user are still something you cannot find in the stream for lots of routes, but it's debatable if that info is of any use; my use case was just that I wanted to find out if a route was added before a certain point in time, which can be read off the stream.

**Comment by brendanheywood** [comment]
No worries - I think there is also an edge where a private account did edits and they won't be shown in the stream. Things are a little inconsistent here as that will show up in the old edit history. Either way I'll close this one
