### ISSUE TITLE
Confused node picker hierarchy when moving and merging

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#318]
Seems to me the node hierarchy is mislabelled when moving or merging a node: the drowdown list of Sibling Nodes in fact holds nodes one level above the current node; the children-list contains what I would rather call sibling. Please correct me if I misunderstood the concept.

**Comment by brendanheywood** [comment]
See also https://github.com/theCrag/website/issues/1476

**Comment by brendanheywood** [comment]
closing as dup of https://github.com/theCrag/website/issues/1476
