### ISSUE TITLE
Inconsistencies with ascent counts for accounts

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3182]
**What happened?**

Sibling issue is https://github.com/theCrag/website/issues/1219 which is for areas. This one should be much simpler as the ticks per user is never a mix of private or whatever, so the numbers should be simpler to at least describe.

https://www.thecrag.com/climber/davidcook

* [x] Ascents in stats top left corner: 1561
  https://www.thecrag.com/ascents/by/davidcook/?sortby=when,desc&page=16

* [ ] Ascents in grey big stat: 1002. Facet below isn't perfect, it shows 1001 (clean ticks)
  https://www.thecrag.com/ascents/with-tick-type/on+tick+clean+send+lead+onsight+flash+groundupredpoint+redpoint+pinkpoint+greenpointonsight+greenpoint+allfreewithrest+leadsolo+second+secondclean+toprope+topropeonsight+topropeflash+topropeclean+ropedsolo+on+aid+aidsolo+on+onsightsolo+solo+on+firstascent+firstfreeascent/by/davidcook/?sortby=when,desc&page=10

* [ ] Unique ascents in big stats hover: 645 (unique and clean? or just unique)

* [x] ascents in black hover on account on another page 815, eg a follower
  https://www.thecrag.com/climber/amougenot
  This one I don't get at all, I think it is a real bug and the number should be 1561

* [x] ascents in a climber card, eg the followers facet (1561, raw count)
  https://www.thecrag.com/climber/amougenot/following

I think this issue is half semantics and some actual bugs. We don't have consistent language to clearly say 'all logged routes' vs 'things I got to the top off'  vs 'things I have done to some level or personal satisfaction'. I also think we should consider the purpose and context of each number more clearly when presenting it, so for instance the grey summary big stat on the profile is more or less just a quick indication of climbing volume. In this context I think just the unfiltered number is fine, if they are working stuff heaps then that counts. Ghost or target probably shouldn't, but I think for simplicity we just include them and this will get sorted better when we implement the route wishlists.

**What you expected:**

* [ ] Each presented number should always link to a facet so it's exactly clear what it represents
* [ ] We can do this for all of them except for distance climbed, we need to have a way of showing the cumulative distance for any facet (probably similar handling to the count, eg under a certain size it is exact, over that is estimate)
* [x] fix the account black hover bug

**Comment by brendanheywood** [comment]
So the black hover is using routesTicked vs ascentCount. On top of any sense of being more correct or expected, routesTicked is only used in a tiny handful of places in the whole codebase so mostly for consistency I will swap that to ascentCount. hotfixed:

![image](https://user-images.githubusercontent.com/187449/40422505-e98a4954-5ed2-11e8-98a5-27259e3d4fc7.png)

**Comment by scd** [comment]
Hmmm, routesTicked versus ascentCount. Nice pickup

**Comment by brendanheywood** [comment]
@scd do you know what I did wrong re the 1001 vs 1002 numbers? What filters are wrong in the facet?

**Comment by brendanheywood** [comment]
fixed
