### ISSUE TITLE
Error in PDF generation for regions

### ISSUE THREAD

**Issue by scd** [theCrag/website#3184]
**What happened?**

The following region has an error in pdf production:

https://www.thecrag.com/climbing/united-states/colorado-shelf-road/area/14385865

Screen shot of the xhtml shows some issues

![screenshot from 2018-05-25 08-53-39](https://user-images.githubusercontent.com/373058/40517625-9ac2332c-5ff9-11e8-86e0-61ce19459d30.png)

 - [ ] Business rule for no generation of PDF at regions not implemented in a user friendly fashion. 
 - [ ] The PDF generated is not legal xhtml - extra div which hides the failure reason from the user
 - [x] There is a data error. The Bank was assiged a region under the top level crag of Shelf Road. This has now been changed to an area.

Changing from region to area fixed this problem. However the technical error and poor business rule implementation is still there

**Comment by brendanheywood** [comment]
Probably the same as this issue https://github.com/theCrag/website/issues/2987

**Comment by brendanheywood** [comment]
tested and works now
