### ISSUE TITLE
Re-parenting looses the order of annotations and routes

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3186]
**What happened?**

Re-parented a junk of routes separated by annotations from one sector to another (using reparent children of selected node). All annotations ended up at the bottom of the list in the new sector, actually loosing the previously correct structure for good.

https://www.thecrag.com/climbing/united-states/colorado-shelf-road/area/16741519

<img width="954" alt="screen shot 2018-05-25 at 12 57 49" src="https://user-images.githubusercontent.com/19162952/40561762-91141a80-601b-11e8-8c76-732369f51f73.png">

**What you expected:**

Annotations stay where they were.

**Comment by brendanheywood** [comment]
closing as dup of https://github.com/theCrag/website/issues/1351
