### ISSUE TITLE
Make the who with @mention selector more context dependant

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3189]
**What happened?**

ie if I am ticking a route, the who field should prioritize friends over 'area developers' (and not include myself https://github.com/theCrag/website/issues/2103)

But if I am adding FA info, then it should prioritize 'area developers' over friends.

**What you expected:**
* [ ] optionally specify the modes as a data attr on the search field
* [ ] change the api to honor the order of the modes sent in
* [ ] change the auto complete library so we can define a custom mode
* [ ] add the extra modes for 'partners' and 'recent'
* [ ] The order of the various select2 groups is tuned to each context  as above

There is a bunch of easy new groupings that I think would make things much nicer like:

* [ ] partners - the list of top partners we just created for the profile page
* [ ] recent - recently ticked with, but perhaps not in the top most ticked with list above
* [ ] nearby - others who have ticked in the same crag very recently, perhaps a week or less. A good way to easily connect with people you meet at the crag

Specific ordering for contexts:

* [ ] tick, with = recent, partners,nearby,following,karma (exclude you!)
* [ ] Comps could be like: participants,partners,following,karma
* [ ] Editing the FA = me,recent,partners,developers,karma,following

**Comment by lordyavin** [comment]
+1

**Comment by brendanheywood** [comment]
+1 for competition participant context search for with field

**Comment by scd** [comment]
This is probably not to difficult once we have documented all the contexts and the priorities. It already partially works this way.

**Comment by brendanheywood** [comment]
The key thing here is to have the api honour the order of the contexts passed in for searching. Then it is purely up to the calling client code to define what groups and in what order it wants. The api should be relatively dumb and not attempt to guess what is best.

Eg ticking should be something like 

partners,following,karma

Comps could be like

participants,partners,following,karma

Editing the fa field should be something like:

me,developers,partners,following,karma

There is a bunch of easy new groupings that I think would make things much nicer like:

partners - the list of top partners we just created for the profile page

recent - recently ticked with, but perhaps not in the top most ticked with list above

nearby - others who have ticked in the same crag very recently, perhaps a week or less. A good way to easily connect with people you meet at the crag

**Comment by rouletout** [comment]
Not all implemented but many aspects covered in the new ticking interface - closing this and open more specific issues for the ones we want to do.
