### ISSUE TITLE
TLC not being selected for a normal crag in the 'who' selector for fa / ffa in bulk edit

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3190]
**What happened?**

This doesn't appear to be an edge case, it's just a normal crag inside a region, with cliffs inside. But when I edit any of the cliffs it is not finding the crag as the TLC as so defaulting to australia. This manifsest as the 'area developers' being a massive list vs the < 5 people who have actually developed here:

https://www.thecrag.com/climbing/australia/bakers-creek/area/1821986184

![image](https://user-images.githubusercontent.com/187449/40634381-3890f678-62e4-11e8-8dc1-f034c58bb171.png)

The TLC is correctly being selected properly for the stream events.

**What you expected:**

* [x] It should find the crag at the TLC when bulk editing the fa field

**Comment by brendanheywood** [comment]
Related issue with probably the same root cause:

https://www.thecrag.com/ascents/by/brendanheywood/

![image](https://user-images.githubusercontent.com/187449/40658532-1987bf6c-633b-11e8-87b6-8c9a845a564f.png)

I'm fairly sure this is a recent regression

It's also in other crags

https://www.thecrag.com/climbing/world/ascents/by/rockboy76/

In fact I think this is affecting every ascent in australia but not other crags:

https://www.thecrag.com/climbing/australia/ascents/?sortby=when,desc

```
{
"name": "Australia",
"isCountry": 1,
"numberRoutes": "67480",
"depth": "1",
"countryCode": "AU",
"urlStub": "australia",
"isTLC": 1,
"subType": "Crag",
"subAreaCount": 9,
"id": "11737699",
"countryID": "7478254"
},
```

But all the streams are ok

https://www.thecrag.com/event/1823902173

But the super weird thing is that in both places the isTLC flag is incorrectly set on the australia node, so there is two issues:

1) the isTLC flag is wrong
2) the stream logic is using 'cragID' which is not using the same logic as the isTLC

**Comment by scd** [comment]
Australia is set to crag. Bad. Cannot do anything now

**Comment by scd** [comment]
I have ran a cache rehash of all nodes in Australia which fixes one problem.

./rehash-entity-cache -nN 11737699
