### ISSUE TITLE
Align route popularity with area popularity visually

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3196]
**What happened?**

The area popularity has a log curve applied which feels much more natural and gives a more balanced feel to the popularity of siblings areas. It would be better for the routes to follow suite. eg this new area only has a handful of ascents, the max being 4 for a route, but every route has at least one ascent but these don't even register on the graph at all:

https://www.thecrag.com/climbing/australia/kaputar/mt-lindesay/area/1741160889

![image](https://user-images.githubusercontent.com/187449/41232041-9b029ccc-6d74-11e8-9922-8cefa2dae534.png)

**What you expected:**

* [ ] more natural popularity 'power bars'

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76748656-d0391500-6783-11ea-89bc-2dad47a767f7.png)

Seems done, the visual scale takes in account even low ascent counts
