### ISSUE TITLE
Flesh out publications template data with details for each guide

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#320]
eg I've added the guidebook image:

http://dev.thecrag.com/area/12016363/publications

But I'm linking into the dark, I don't know if there is actually an image. It should have the complete data structure the same as the publications template data.

view-source:http://dev.thecrag.com/publication/7545139/json

Also some minor tweaks:
- publication data in both templates where possible should be a partial date format so we can sort by date or at least by year (eg show more recent guides first)

**Comment by rouletout** [comment]
Done with release 101 - closing
