### ISSUE TITLE
URLs to routes in "Activities" facet wrong

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3204]
**What happened?**

Example url(s) to reproduce the problem: https://www.thecrag.com/climbing/germany/frankenjura/activity

The URLs generated for route names in the activity facet lead to a 404, since the URL contains the string "/area/" instead of "/route/".

**Comment by brendanheywood** [comment]
See also: https://github.com/theCrag/website/issues/2364

**Comment by Mdemaillard** [comment]
tested the URLs are working now.
