### ISSUE TITLE
Filter grade pyramid to only show unique ascents

### ISSUE THREAD

**Issue by Dturf** [theCrag/website#3205]
Is it possible to have the option to filter the grade pyramid on the profile page to only reflect unique ascents at each grade?

Such an option used to exist for a while and no longer does. If having it as an option is not possible can we revert to it being that way for everyone?

**Comment by langley921** [comment]
This would be awesome if possible...

**Comment by brendanheywood** [comment]
Yes this is in line with the direction we want to take the profile page in

**Comment by brendanheywood** [comment]
The new pyramids will only show unique routes, so this is more or less done (except there won't be an option)
