### ISSUE TITLE
"Bolts" to support multi-pitch?

### ISSUE THREAD

**Issue by bing-li** [theCrag/website#3206]
**What happened?**
- Only one "Bolts" drop down box, can't input bolts for different pitches

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/china-mainland/route/1877841966 

Ideally also provide screenshots:

**What you expected:**
- "Bolts" is a edit box that can take an array, such as `9,6,8` for 3 pitches, similar to "Height" and "grade"
- and the bolts can be shown next to the grade and height 
- the overall bolts of the mutli-pitch route is the max of each pitch

![image](https://user-images.githubusercontent.com/8226377/42449633-fe5a509e-83b3-11e8-9dee-550b7c6aa3c7.png)

**Comment by brendanheywood** [comment]
Thanks @bing-li - I will close this as a duplicate and add you vote there instead

https://github.com/theCrag/website/issues/640
