### ISSUE TITLE
Broken layout in bulk add form

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3215]
**What happened?**

This is site wide, but an example:

https://www.thecrag.com/processmap/createclimbnode/302006535?D:InsertBefore=17480629&R=/climbing/united-states/rumney/area/302006535

Its worse if you add more blank routes, looks like a missing closing div somewhere:

![image](https://user-images.githubusercontent.com/187449/43068412-abfea534-8ead-11e8-9bd3-5b3bc5aeb93a.png)

**What you expected:**

**Comment by scd** [comment]
Fixed. This was a regression issue I made a couple of days ago fixing the gyms color layout. Out of the 4 use cases I forgot to test the outdoor bulk add.
