### ISSUE TITLE
Allow easier creation of annotations at the area level

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3217]
**What happened?**

Annotations make valid sense between areas where a grouping area is overkill, but a couple of sibling areas share an approach, or area topo, etc.

Some useful cross over with annotations in topos: https://github.com/theCrag/website/issues/1693

**What you expected:**

* [ ] add annotation above, in area hover action menu
* [ ] add annotation in area action menu

**Comment by rouletout** [comment]
Add annotations is available for areas - however it introduces the route menu bar as well, but this is covered elsewhere, closing
