### ISSUE TITLE
clicking on thumbnail maps on region pages zooms out to world level

### ISSUE THREAD

**Issue by cgome** [theCrag/website#322]
It seems like any time you click on a thumbnail map in list view for a region you are taken either the top level world map or a map that is more zoomed out than you'd expect. 

(In comparison, clicking on a cluster of crags in the map zooms in you a good level that is basically as zoomed in as possible to include all the crags in the cluster. Clicking on a thumbnail map of a Crag in List View also seems to take you to about the right level on the map).

Zooms out to whole world
- Australia
- North America
- USA
- Alaska

Zooms in a bit but not as much as you'd expect
- Victoria (zooms in to about what you'd expect for Australia)
- Melbourne (zooms in to about what you'd expect for Victoria)

**Comment by brendanheywood** [comment]
redundant
