### ISSUE TITLE
All the various facets (route, area, climber, node etc) could have a consistent free text search

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3221]
**What happened?**

On the new search page we link from there off to the advanced / facet search page, but this doesn't retain the search keywords. In most cases it makes sense to retain these, but only some facets support a concept of a free text search.

**What you expected:**

* [ ] climber / photo / route / area / node facet, search route name
* [ ] cross link from simple search into the facet search

**Comment by brendanheywood** [comment]
From support email: A more specific use case here would be searching route descriptions for specific things. I think searching inside the route markdown should be a different filter to a generic search on the route names, eg

Find a route named bard: (undocumented but working, multi keyword might not be right)

https://www.thecrag.com/climbing/australia/arapiles/routes/search/bard

Find all offwidth routes: (not implemented yet, would be expensive at region level)

https://www.thecrag.com/climbing/australia/arapiles/routes/has-text/offwidth

**Comment by brendanheywood** [comment]
+1 from Gabe

**Comment by brendanheywood** [comment]
+1 via https://github.com/theCrag/website/issues/3250

**Comment by lordyavin** [comment]
+100

**Comment by quaestor** [comment]
This is so important. +1 as well.

**Comment by scd** [comment]
This is done in simons dev
