### ISSUE TITLE
Add french adjectival alpine grades and other alpine grade systems

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3224]
**What happened?**

I thought this was already logged but can't find it:

From Ryan:

>  french adjectival grade, namely that it won't accept + or - additions.

https://firstlightguiding.com/international-grade-comparison/

http://www.alpinist.com/p/climbing_notes/grades

https://en.wikipedia.org/wiki/Grade_(climbing)#Mountaineering

https://www.thecrag.com/article/Grades#other-grade-systems

https://en.wikipedia.org/wiki/Ice_climbing#Grades

We are missing essentially all grade systems for alpine:

* french
* russian
* new zealand
* UIAA (different to UIAA rock grades)
* Alaskan
* Romainian

**What you expected:**

* [ ] Import systems we can
* [ ] Split the grades article sections so that alpine it a new grade section, separate from aid and via ferrata
* [ ] Fix up the tick type mappings so that we can aid alpine routes see https://github.com/theCrag/website/issues/3077
* [ ] Make sure the grades render properly https://www.thecrag.com/ascents/with-route-gear-style/ice+alpine/?sortby=when,desc
* [ ] consider a different grade color spectrum for ice and alpine climbs

**Comment by scd** [comment]
We have currently got the following Alpine grading systems on theCrag

 * International French Adjectival System (IFAS) - eg `AD`
 * National Climbing Classification System (NCCS) Alpine Grade - eg `III`

From the articles above I can work out the following to be implemented:

 * Alaska Grade (1 to 6)
 * Russian Grade (1A to 6B)
 * Scottish Winter Grades (I to IX)

**Comment by rouletout** [comment]
Fixed with release 88
