### ISSUE TITLE
Stream edit events from private accounts should exist and be visible

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3225]
**What happened?**

Edits from private accounts are completely hidden. I think this is conceptually wrong, privacy applies to what you do in private, but edits are public and not having a clear audit trail is bad. 

Part of this is about splitting up the idea of 'a private account' into finer grained permissions (See https://github.com/theCrag/website/issues/1106 and https://github.com/theCrag/website/issues/500). ie if you are looking at a profile, then that person could chose to hide the whole list of what they have done (at least to randoms). 

**What you expected:**

* [ ] At minimum the activity facet, and the streams should create normal events, but the visibility of the events should depend on who is viewing it
* [ ] Their followers should be able to see their edits (either in the crag stream or the profile stream)
* [x] Crag coordinators / admins should see full edit history

* [ ] stream events need a clear public / private status, similar to the facebook post world / friends icon

* [ ] Ideally change the T&C so  all edits are visible from the crag side in the stream

**Comment by brendanheywood** [comment]
+1 from support email

**Comment by brendanheywood** [comment]
Just reflecting on this, maybe there is some middle ground for private accounts. The problem is that you don't know what you don't know. We could half solve this by just showing that there was an edit, and what the edit was, and when, but showing the account as anonymous. This would solve 90% of the issues and at least allow people to know what the don't know and ask for it instead of just stumbling around in the dark thinking the system is broken.

I still think new edits should be public by default after some set point in time but that's a different decision.

**Comment by scd** [comment]
We enabled this a while ago. Closing
