### ISSUE TITLE
Logbook: Ascents sorted by logged dat, not ascent date as default

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3228]
**What happened?**

E.g. here https://www.thecrag.com/ascents/by/rouletout/ ascents are sorted by log date which is not intuitive and probably not of interest to anyone. 

Ideally also provide screenshots:

**What you expected:**

A default sort by Climb Date would be more useful

**Comment by Luen** [comment]
This would be great. I would like to see the logbook default to ?sortby=when-climbed,desc

**Comment by brendanheywood** [comment]
Fixed
