### ISSUE TITLE
Forum Info Box is confusing

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3232]
**What happened?**

An favourited area shows the following forum info box (see screenshot)
<img width="383" alt="screen shot 2018-08-10 at 12 18 32" src="https://user-images.githubusercontent.com/19162952/43952958-bf0928a0-9c97-11e8-87db-b0f81704343f.png">

https://brendan.thecrag.com/climbing/united-states/idaho/area/1275465462/forum/?lang=yy

Ideally also provide screenshots:

**What you expected:**

Expect the lower part without button if it is favourited and thus I'm subscribed or the upper part of the message with the button if not.

**Comment by brendanheywood** [comment]
I'll sort this shortly, but it's part of the bigger problem in https://github.com/theCrag/website/issues/1449

**Comment by brendanheywood** [comment]
@scd has done this
