### ISSUE TITLE
Route History Dates format problems in Streams

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3233]
**What happened?**

In the stream event view dates of routes histories could have a wrong format and locking odd on mobile.

https://www.thecrag.com/event/1932871974

the date of the FF is not "23 Apr 2060" it is "1960"
and also the gray box spans to much space in the mobile version.

![grafik](https://user-images.githubusercontent.com/2226714/44090269-ef017b90-9fc9-11e8-9172-e245718e4f33.png)

**What you expected:**

* working format
* better layout

**Comment by scd** [comment]
fixed in dev
