### ISSUE TITLE
Photo Upload or Display broken

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3236]
**What happened?**

i uploaded a photo and the upload process was working well. Afterwards the image is not shown.

https://www.thecrag.com/photo/1944368508

**What you expected:**

* [ ] shown photo

**Comment by nicHoch** [comment]
hmmm the photo is shown now a few minutes later.
is the thumbor process well configured. seems to take a while to process ....

**Comment by scd** [comment]
Please check again as I think it was an image serving glitch. I see the
image

**Comment by nicHoch** [comment]
@scd close it if you think it was just a temporary issue.

**Comment by Mdemaillard** [comment]
Photo upload works currently. candidate for closure
