### ISSUE TITLE
CPR graphs at the CPR help page

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#3237]
The example graphs at the CPR help page don't show anything. See the screenshot.

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/article/cpr

Ideally also provide screenshots:
![17-08-2018 12-40-35](https://user-images.githubusercontent.com/3040689/44262300-ca332900-a21a-11e8-9feb-c19f3adace81.jpg)

**What you expected:**
Show the graphs as they used to before the update :-)

**Comment by brendanheywood** [comment]
Fixed for next release
