### ISSUE TITLE
Top Rope ascents in NOTABLE ASCENTS

### ISSUE THREAD

**Issue by jedparkes** [theCrag/website#3239]
If you look at my profiles page https://www.thecrag.com/climber/jedparkes#notable
The route 'The Grand Adjudicator' is showing as my hardest trad climb.
It's not... This route i have logged as 'Tick Type' = 'Top rope clean'
I would expect this not to show up as my hardest trad climb ?

**Comment by brendanheywood** [comment]
thanks jed, I'll close this as a dup of https://github.com/theCrag/website/issues/2670
