### ISSUE TITLE
Follow button at climbers search

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#3241]
**What happened?**
I searched for "Anderl" to go to his profile page. At the list of the found climbers he was there, but the "Follow" button was green with "Follow" instead of grey and "Unfollow", because I'm already following him.

Example url(s) to reproduce the problem:
Just search for a person you are already following.

Ideally also provide screenshots:
![20-08-2018 09-00-42](https://user-images.githubusercontent.com/3040689/44325502-44e98780-a459-11e8-9f24-5af968e7300a.jpg)

![20-08-2018 09-13-00](https://user-images.githubusercontent.com/3040689/44325507-4915a500-a459-11e8-8aed-8c067036bcd4.jpg)

**What you expected:**
Accounts you are following should also show the "Unfollow" button when searched for.

**Comment by scd** [comment]
thanks for this - fixed in dev
