### ISSUE TITLE
Template variables not substituted for comments on update stream event

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3242]
**What happened?**

In the forum tab, when replying to an activity, some template variables are not substituted, in my case {action} and {actionType}:

<img width="756" alt="screenshot 2018-08-22 02 13 45" src="https://user-images.githubusercontent.com/54371/44435748-ab81b900-a5b1-11e8-8b0a-87d74161864b.png">

**Comment by brendanheywood** [comment]
What is the url for that page?

**Comment by quaestor** [comment]
https://www.thecrag.com/discussion/1954411332/stark-einmal-die-ganze-wand-d-die-7en-sahen-knackig-aus-dort

**Comment by Mdemaillard** [comment]
seems solved.
