### ISSUE TITLE
Ranking Sliders don't show Avatars

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3245]
**What happened?**

https://www.thecrag.com/de/artikel/rankings don't show avatars.

<img width="853" alt="screen shot 2018-08-22 at 16 27 14" src="https://user-images.githubusercontent.com/19162952/44491964-74022380-a628-11e8-9574-922b18396a72.png">

**What you expected:**

Show avatars as before the new release

**Comment by brendanheywood** [comment]
fixed in dev
