### ISSUE TITLE
Alternative to google for maps, openstreetmap, baidu bing etc

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3248]
**What happened?**

This issue is to replace, https://github.com/theCrag/website/issues/365 which has since gone missing. 

Most of this is pulled from the google cache (will probably expire soon):

https://webcache.googleusercontent.com/search?q=cache:5nbVYawHqwgJ:https://github.com/theCrag/website/issues/365+&cd=1&hl=en&ct=clnk&gl=au

**What you expected:**

* [ ] allow a concept of 'map services'
* [ ] each service supports different abstract tiles, eg street map, terrain map, satelite maps as well as different apis, dynamic maps, static, directions, url links
* [ ] at any node, but typically a country or region you can specify which maps to use, probably as a priority. This inherits down but can be overridden

We need to support:
* [ ] dynamic maps in fullscreen mode
* [ ] static maps in streams, cards etc
* [ ] deep links to directions in apps
* [ ] static maps used in pdfs 

The original card details:

You probably have heard that Google starts to charge for the use of the map API (http://googlegeodevelopers.blogspot.com/2011/10/introduction-of-usage-limits-to-maps.html). I don't know if this is an issue for you or if thecrag can remain below the limits that still are free. If not and you are looking for an alternative, I'd like to point your attention to openstreetmap.org . Here's a short summary for your information.
pros:

free as speech, not only as in beer - no legal restrictions when including maps
map coverage of trails, paths, isohypses and other relevant landmarks in the backcountry is usually way better than in GM
different map layouts can be chosen (even customized, if necessary)
users can improve unmapped areas, if they want to
cons:
no easy switching between satellite imagery and maps (yet)
API probably not (yet) as advanced as Google's
need to be able to support static maps (eg in streams)

**Comment by brendanheywood** [comment]
Many of the comments in the previous issue are redundant and don't reflect our current thinking, so I will selectively cut and paste some of the old stuff here for history...

**Comment by brendanheywood** [comment]
Yeah thanks for understanding. Leaflet does look pretty cool and I'd like to play with it just to see how far I can get with it. My big problem is I'm always running off on tangential ideas and sometimes I just need to put blinkers on and mash out code. When I implemented OpenLayers for editing leaflet didn't exist yet.

Your comment about Bing maps being better in places I get - from my experience bing often has higher res data in particular places like big cities where as google seems to have better all round coverage. There are heaps of places in australia at least where bing just has nothing. And vice versa.

Can you also send me a url of places in OSM with cliff outlines etc? I'd love to see that

Also our careful reading/understanding of the google T&C boils down to: you can use maps offline as long as you don't modify the image and you also link back to either your webapge which embeds a google map, or google maps itself for that location (which we do). This was also one of the sticking points which once we clarified made us feel better with sticking with google maps.

And yes my belief is that Google uses the OSM data as-is without editing it or re-mixing it into their other data sources. They source from a large number of copyrighted data sets all of which would preclude being mixed with each other - it's actually fairly similar to how we can host content under different multiple licenses. But I can' find any hard evidence of where this has happened so it's all hearsay.

Also thanks for discussing this - we often have these epic internal discussions over minor clauses in license terms, or T&C, and not many people appreciate how much we angst over all of this stuff. Nothing ever seems to be clear cut.

**Comment by brendanheywood** [comment]
I guess we will always find places where one source excels over the other, in imagery or in maps. That is why I like the way you implemented it in the editing mode - one can just choose which is best.Concerning cliff outlines, as always with OSM, the coverage is very diverse. A particularly impressive example is Sächsische Schweiz (~ 20k routes), where many cliffs and summits have been mapped:http://osm.org/go/0MgWt5on--Zooming will also reveal shelters, stairs, viewpoints, etc. The cyclist layer also contains contours. Compare this to google (which is not too bad with the paths):https://maps.google.de/maps?q=schmilka&hl=de&ll=50.904088,14.242229&spn=0.022679,0.024376&sll=52.428362,13.027412&sspn=0.350857,0.390015&hnear=Bad+Schandau,+Dresden,+Sachsen&t=m&z=15I sympathize with you having to care about that legal stuff - coding is strenous, but at least you get some result (mostly). With this license stuff, one may end up with less than begun with.
--

**Comment by brendanheywood** [comment]
We've had a few more requests from this, often from german's. I'm going to re-open this one but it isn't scheduled, has a lot of dependencies, and it a whole bucket of work and so don't expect it any time soon. My plan is to probably swap to leaflet just for viewing, and let the end user swap to other maps themselves but still default to google maps.

* use leaflet (or do a selection of other maps libraries, but probably leaflet)
* default to google, sat + terrain + road, + bing + OSM
* long term possibly allow a node, either crag, country, region etc to have a preferred default map provider, ie whole of Germany could default to OSM. Probably need a default for photo, and a default for streetmap

This has a lot of knock on effects like rewriting / re-selecting libraries for clustering for leaflet instead of the Gmaps api, so will effectively be a ground up rewrite of the maps to replace both list view maps and the full screen maps tab. Map editing would probably be unaffected. See also and probably bundle this with #1145, #1094, and possibly replace #862, #421 and many others will be affected too.

**Comment by brendanheywood** [comment]
@MeForThis commented on 21 Aug 2014

Openstreetmap would be a great feature.

I live in west Africa right now and google / bing is completely useless, also the satellite pictures often have a 10m = 1px solution :-(

There are other places where these are very good, unfortunately most of the time where the decision makers / developers are.

**Comment by brendanheywood** [comment]
@lordyavin commented on 8 Sep 2014 • 

Just want to highlight this issue. On my trip to the Dolomites I found the satellite images provided by bing much better. It would be great if the backend stores with which map display the location was saved and should display this as default on the index page. Look at my recent contributions. You will see that the current display of GM is crap.

**Comment by brendanheywood** [comment]
Another +1 from FB https://www.facebook.com/thecragcom/posts/10153533269322604

**Comment by brendanheywood** [comment]
Drazhar commented on 9 Sep 2015

And a +1 from me, because you aren't allowed to edit google maps in Swiss or Germany

**Comment by brendanheywood** [comment]
@Heineken commented on 21 Nov 2016
I claim the "bump". My mail was specifically about the help text on https://www.thecrag.com/article/Geolocation#addtrack encouraging users to contribute to GM without mentioning OSM.

If that has proven to be problematic and the plan is to become less dependent on GM (yay!), both facts could be expressed in that help text in order to stop sending people's ambition in the wrong direction. No coding involved :-)

**Comment by brendanheywood** [comment]
@Heineken commented on 26 Nov 2017

Names of cliffs/subareas/crags can be set in OSM, for example here:
https://www.openstreetmap.org/edit#map=19/37.17117/22.89754
I don't where they would be rendered/used, but it would be nice to exchange that data with theCrag to avoid double work. Like:

when area location is not set in theCrag, use coordinates from OSM to show crag location or at least suggest when setting location
and, the other way around
set the point (or area, if possible) in OSM when defining location in theCrag

**Comment by brendanheywood** [comment]
@gui84 commented on 30 Nov 2017 • 

I just wand to add that it's a pity that Openstreetmap layer is not displayed in maps area, but only when we edit location. We can't simply use their work for geolocalisation. Moreover, many times Openstreetmap is more accurate than Google maps for crags approach. It's an openproject compared to Google maps.

**Comment by brendanheywood** [comment]
Next year we will embark on a major ground up rebuild of the maps. The intention here is that the cliff / crag can specify what tile layer to use as the default. Yes OSM is better in some places, but in other places it is not great, google maps will continue to be the default unless overridden. Also pushing and pulling data into and out of OSM is very problematic for lots of reasons, some technical and some around licensing, but mostly because it's not really structured data and the semantics of it don't cleanly map to our data model. OSM is also a general purpose map, often climbing areas are called one thing by climbers and another by tourists.

**Comment by brendanheywood** [comment]
Another example of this, google has no data for this part of malaysia so the map is just black:

https://www.thecrag.com/climbing/malaysia/area/1640276538

**Comment by brendanheywood** [comment]
@lordyavin commented on 19 Jan
@brendanheywood just zoom out. There is some data. Is it possible that the map display detects a blank map and zoom until there is some data?

 @brendanheywood
Member
brendanheywood commented on 23 Jan
That's the point though, there is no data at a fixed zoom level and we don't know ahead of time. We can zoom in the js api, but it would appear not really in the static maps api. The static maps api isn't something I've considered for the new maps rebuild, ideally each new alternate tile server we allow would also have a static map api but I doubt this is the case :(

**Comment by brendanheywood** [comment]
@gogulfresh commented on 30 May

+1 for supporting OSM as alternative to GoogleMaps. In many areas (at least in Europe) GM has nothing but the satelite view while OSM is pretty good mapped!

**Comment by brendanheywood** [comment]
from @rouletout :

> Google Maps doesn’t work in China. For the Map-re-work we should also make sure that Chinese maps work.
The most important ones are Baidu Map https://map.baidu.com/ and VTR www.vtrhome.net

**Comment by brendanheywood** [comment]
google maps api docs for users in china is here:

https://developers.google.com/maps/documentation/javascript/localization#GoogleMapsChina

**Comment by lordyavin** [comment]
So any schedule on this quite important issue?

**Comment by scd** [comment]
No timelines yet. We have got to work out how we can even keep a free maps service with equivalent features now that Google is charging.

Brendan is away until the end of September and as he is the most knowledgeable maps person in the team, we will not make any headway on this for a while.

**Comment by Heineken** [comment]
Works fine for me, @MelwinQ !

**Comment by brendanheywood** [comment]
the original issue at https://github.com/theCrag/website/issues/365 has not been restored by github support so I'm going to close this one, please add any further comments to the original issue
