### ISSUE TITLE
It is difficult to search for and find an area / climber / route with a common name but which has low kudos / karma / ticks

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3250]
**What happened?**

search for “Dark Side” does not show:

https://www.thecrag.com/climbing/united-states/red-river-gorge/area/14529313 

This is because there is way to may other more important dark sides.

Where you are affects the ranking, but that said I find it as the top hit when searching from inside kentucky:
https://www.thecrag.com/climbing/united-states/kentucky/search?S=dark%20side

Ranked 2 when searching from the states:
https://www.thecrag.com/climbing/united-states/search?S=dark%20side

Ranked 4 from north america
https://www.thecrag.com/climbing/north-america/search?S=dark%20side

And it doesn't rank in the top 6 when searched from the world.

**What you expected:**

* [x] Show some indication that there is more results (doesn't need to be exact, just that there is more)
* [x] So what I think we really want here is a 'show more' or pagination so you can grind through more than the top 6 results
* [x] if you drill down into more crags, then I would only show crags, not accounts or routes. We should probably treat the climbers and routes the same, so:
* [x] have an optional 'scope query param and when in this mode it limit searches to just that scope
* [x] when in scope mode also increase the page size to something quite large, maybe 40
* [x] also add pagination if we still need it after that

**Comment by rouletout** [comment]
Just another one: https://www.thecrag.com/search?S=neanderthal

This did not find the famous route at all. Now that Jake has ticked it it is at the list but not before. He actually couzldn't find the route for ticking.

**Comment by brendanheywood** [comment]
Can you please provide the actual famous route? Do we even have this route in our database at all? What crag is it in?

**Comment by rouletout** [comment]
Haha yeah sorry: https://www.thecrag.com/climbing/spain/santa-linya/route/157220427

**Comment by brendanheywood** [comment]
This one is tricky. We currently have 48 routes which contain 'neanderthal':

https://www.thecrag.com/climbing/world/nodes/fuzzy-search/neanderthal/?sortby=at,desc

We currently only show the top 20 on the quick search page. So there is few different issues here:

1) There will always be some missing, regardless of the search algorithm, so we need to link to the rest of the areas / climbers / routes (and / or get the pagination for more results). This is already on the list here https://github.com/theCrag/website/issues/3221

2) Searches scoped with ancestor keywords do not currently work as expected: https://github.com/theCrag/website/issues/3333

3) We probably also want to tune the search algorithm so that 'famous' routes get a ranking boost. We currently only rank on ticks, and famous elite routes will probably never have any, or very few ticks, so will never rank. We could add stars to the ranking, but there could also be a famous elite route which is famous only because it is hard and not because it's actually that high quality. I am struggling to think of how we could add a 'famous'ness factoring into the ranking metrics. We could maybe just have a manual fudge factor but this would be a nightmare to maintain. Another option is that if the route has an FA by a famous person then we somehow mix that person 'famousness' into the brew, but this is also difficult as a) most FA's are text, and this would result in a very inconsistent ranking factor. So ruling this idea out.

The other approach is that we try to normalize things by grade, ie routes with high grades which get less ticks get a relative boost compared to lower grades which get more ticks. I think this will effectively be equivalent to making route quality a larger ranking factor.

**Comment by rouletout** [comment]
One more, "The North Wall" is not found, search: https://www.thecrag.com/climbing/thailand/krabi/area/1720720308/search?S=the+north+wall

Area not found: https://www.thecrag.com/climbing/thailand/krabi/area/1720720308

**Comment by rouletout** [comment]
One more, "Adam Ondra" is not found, search: https://www.thecrag.com/search?S=adam+ondra

Climber profile: https://www.thecrag.com/climber/adamondra

**Comment by rouletout** [comment]
one more, route name "La Castagne":

Search: https://www.thecrag.com/search?S=la+castagne
Route: https://www.thecrag.com/climbing/france/saint-leger-gorges/route/1658328561

**Comment by rouletout** [comment]
and one more, route name "la madone":

Search: https://www.thecrag.com/search?S=la+madone
Route: https://www.thecrag.com/climbing/france/provence-cote-dazur/avignon-provence-area/route/1623418515

**Comment by rouletout** [comment]
one more, can't find this climber:

Search: https://www.thecrag.com/search?S=jon+shen
Climber: https://www.thecrag.com/climber/jonathanshen

**Comment by rouletout** [comment]
one more, can't find La Rambla!

Search: https://www.thecrag.com/search?S=La+rambla
Route: https://www.thecrag.com/climbing/spain/siurana/el-pati/route/18428605

**Comment by rouletout** [comment]
one more, can't find Mar Alvarez

Search: https://www.thecrag.com/search?S=mar+alvarez
Climber: https://www.thecrag.com/climber/maral

**Comment by rouletout** [comment]
can't find the country Lebanon on Worl Level!

https://www.thecrag.com/climbing/world/search?S=lebanon

**Comment by rouletout** [comment]
OK the actual topic of this issue is done and I close it, i copied all stuff we couldn't find to the open issue #3235
