### ISSUE TITLE
Pasting long URLs in forum messages cripples input box in Chrome

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3252]
**What happened?**

In Chrome Version 68.0.3440.106 (Official Build) (64-bit), when I paste an URL into a forum message, the preview box expands heavily and shrinks the input box to the width of a single character, making further input painful:

<img width="549" alt="screenshot 2018-08-27 16 05 40" src="https://user-images.githubusercontent.com/54371/44664398-6d522280-aa13-11e8-87b7-4faa264eb21a.png">

**Comment by brendanheywood** [comment]
Fixed
