### ISSUE TITLE
Error when trying to follow private account

### ISSUE THREAD

**Issue by scd** [theCrag/website#3255]
**What happened?**

It looks like the account id is not available for the api call to follow a private account from the private accounts profile page.

![screenshot from 2018-08-30 09-55-19](https://user-images.githubusercontent.com/373058/44821824-f6976e00-ac3a-11e8-9729-3d1349259cfc.png)

**Comment by quaestor** [comment]
Still cannot follow private accounts.

**Comment by scd** [comment]
Done a while ago
