### ISSUE TITLE
Area Page for partially located crags looks weird

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3257]
**What happened?**

This crag is partially located https://www.thecrag.com/climbing/united-states/new-river-gorge/area/12594931 but it looks like none of the location info is shown also it does not inform you that location info is missing - no call to action.

<img width="948" alt="screen shot 2018-09-01 at 16 00 23" src="https://user-images.githubusercontent.com/19162952/44949491-abc75300-ae00-11e8-977f-5440dec75c5e.png">

Ideally also provide screenshots:

**What you expected:**

Showing the map with partial location and / or call to action to locate it

**Comment by Mdemaillard** [comment]
This example is now located. what do you mean partially located ? 
not located itself, but some childrens are located ?

i played with a sandpit area, 
https://www.thecrag.com/climbing/test-area/area/3151103562
the map displayed on index seems to be centered on the parent node location, but it does NOT display the located children.

**Comment by rouletout** [comment]
Yes, partially located means that some of the children are located but not the parent in that case.
