### ISSUE TITLE
Translations, key missing

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3261]
**What happened?**

https://www.thecrag.com/climbing/united-states/new-river-gorge/area/12594907/?lang=yy

the "and" between gear styles in the table is not translated.

Ideally also provide screenshots:

Use an existing key for "and" to translate it

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76842024-4ac86a00-6842-11ea-9fb5-2f616a589d7d.png)

**Comment by lordyavin** [comment]
+1

**Comment by rouletout** [comment]
done
