### ISSUE TITLE
Cannot remove alternate name alternateNamesError

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3262]
**What happened?**

The route https://www.thecrag.com/climbing/france/obersteinbach/route/327585381 is a merger of two separate routes, formerly called "Grin Galet (L1)" and "Grin Galet  (L2)" (important: two spaces before the opening parenthesis). After merging, the alternate name "Grin Galet  (L2)" cannot be removed, an error occurs:

`{ "alternateNamesError" : "name 'Grin Galet (L2)' does not exist, so cannot be deleted." }`

It seems like a whitespace error, since the error message mentions the name with only one space before the parenthesis.

**Comment by jalonavens** [comment]
Similarly two routes named `Cave Crack` were merged, the first had a single space between the 2 words and the second had two spaces between the 2 words.

Now the alternate name "Cave  Crack" (with two spaces between the 2 words) cannot be removed from the [merged route](https://www.thecrag.com/climbing/united-kingdom/tunbridge-wells/richochet/route/21505927).

The error message is similar to the OP:
> { "alternateNamesError" : "name 'Cave Crack' does not exist, so cannot be deleted." }

**Comment by brendanheywood** [comment]
From @rouletout via https://github.com/theCrag/website/issues/3427

**What happened?**

This route https://www.thecrag.com/climbing/mexico/jilotepec/megasesino-y-capilla/route/163468155 has an AKA of "el mega" that I tried to change to El Mega. This results in the following error:

<img width="1146" alt="Screenshot 2019-05-13 at 19 36 34" src="https://user-images.githubusercontent.com/19162952/57662797-c5877f80-75b6-11e9-9842-0e5eb1fc5d10.png">



Ideally also provide screenshots:


**What you expected:**

Changing name works.

**Comment by scd** [comment]
Hot fixed this and corrected the three examples in this issue.
