### ISSUE TITLE
How to edit / delete a photo?

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#3266]
**What happened?**
I could find a way to edit / delete a photo anymore. Clicking on a photo shows various metadata and the option to comment, but no editing option.

**What you expected:**
Option to edit / delete / unlink a photo.

**Comment by scd** [comment]
There has been a bit of a paradigm shift with the new design. Call to action and settings are being placed on the top right hand part of the content section of the page.

@MelwinQ at the photo page, top right of content area, can you see and Edit Photo button?

**Comment by TillF** [comment]
Alright, I see it. I guess my "menthal social media filter" removed this button for being too close to the Facebook, G+, etc. icons. Perhaps, placing the Edit button somewhat further apart from these or even below the dropdown menu would have helped, but this problem may also be exclusively on my side.

**Comment by scd** [comment]
I am closing this and taking your comments as a general comment about the difficulty of seeing the buttons in the top right. We will monitor the feedback as it may just be getting use to a change.
