### ISSUE TITLE
Ticking: Default tick type is "tick"

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3267]
**What happened?**

The default tick type is "tick" which results in people using this as tick type without selecting the right one. This is especially bad on mobile as teh "real" tick types are found when scrolling up - not very intuitive.

<img width="1230" alt="screen shot 2018-09-12 at 14 23 57" src="https://user-images.githubusercontent.com/19162952/45445249-b3f07f80-b697-11e8-881b-8c98a6f7b414.png">

**What you expected:**

A default tick type from the top selection, maybe on-sight

**Comment by Luen** [comment]
You could also just have it as "Please select a tick type" and not submit the form until one has been selected.

**Comment by rouletout** [comment]
+1 from jakob Schubert, accidentially ticks with "tick"

**Comment by rouletout** [comment]
+1 from Stasa Gejo, too many tick types to choose from (e.g. seconding on a single pitch), wrong tick type chosen

**Comment by rouletout** [comment]
Default ticks changed in new interface, closing
