### ISSUE TITLE
Static maps in area page might have a scale or shift offset

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3268]
**What happened?**

the subareas of Germany are not located properly on the static map.

![grafik](https://user-images.githubusercontent.com/2226714/45485783-1fe6ec80-b759-11e8-8d21-23cc8da32a16.png)

Example url(s) to reproduce the problem:

https://www.thecrag.com/climbing/germany

the areas:

19: Allgäu https://www.thecrag.com/climbing/germany/allgaeu
20: Hegau  https://www.thecrag.com/climbing/germany/area/520738794
21: Linzgau https://www.thecrag.com/climbing/germany/area/577048626
...

should be much more in the south.
As shown light if you navigate into this areas 

**What you expected:**

* [ ] proper location

**Comment by brendanheywood** [comment]
Note to self:

https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Mathematics

**Comment by brendanheywood** [comment]
fixed:

![image](https://user-images.githubusercontent.com/187449/46641054-27b07a00-cbbb-11e8-87a8-1389dd6b012e.png)
