### ISSUE TITLE
Edit Route (Admin) not available any more, cannot edit multiple FA FFA Set

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3275]
**What happened?**

Before the redesign the route page offered in the action menu an "edit route" that was not redirected to the bulk edit tool with just this one route but to a admin edit form. This is not available any more. 

In the admin edit form for routes it was possible to add multible route history events of the same type. for example: 

* route setting: 1990 by XY  
* route setting: 2010 by Z replaced bolts 
* route setting: 2018 by A add 5m extension  

**What you expected:**
* [x] or bring back the old admin edit form for routes (temp done)
* [x] upgrade the bulk edit tool 
* [ ] remove the workaround when bulk edit is done

Test cases:
* [ ] responsive, when we already have lots of inherited tags https://www.thecrag.com/climbing/australia/kangaroo-point/route/12210475#history

**Comment by brendanheywood** [comment]
I've just double checked everything between the two forms, and as far as I can tell the mulit-FA's is the only bit that is in the 'updateroutedetails' process which is not in the bulkedit one, and none are missing the other way around. The old process is:

https://brendan.thecrag.com/processmap/updateroutedetails/13333147

**Comment by brendanheywood** [comment]
+1 ran into this. Workaround was create a dummy route, add the details and then merge. Example route with different FA's for different pitches:

https://www.thecrag.com/climbing/australia/mt-yarrowyck/route/2399094867

**Comment by brendanheywood** [comment]
And another: https://www.thecrag.com/climbing/australia/mt-yarrowyck/route/13350613

the processmap/updateroutedetails/13350613 workaround is quicker

**Comment by lordyavin** [comment]
+1

**Comment by brendanheywood** [comment]
+1 ran into this again and had to manually construct the url

**Comment by brendanheywood** [comment]
As an interim workaround I've added a link to the old process which does allow this, but only directly from the route detail page, and from the history section:

![image](https://user-images.githubusercontent.com/187449/63686983-abf90380-c846-11e9-9ecb-76bf9da7b247.png)

**Comment by scd** [comment]
I have removed the 'Add route history' workaround button.

I think this is now done. Closing
