### ISSUE TITLE
Avatars are assumed to be non transparent, alpha channel shows placeholder image

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3277]
**What happened?**

Example url(s) to reproduce the problem:
https://www.thecrag.com/climber/isra17

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/187449/45993779-bd380e00-c0d3-11e8-972c-acdd1d38a83f.png)

**What you expected:**

* [ ] avatar should have a white background to obscure the placeholder

**Comment by brendanheywood** [comment]
This is actually a little more complex because I think the thumbor pics do remove the alpha channel (or at least we can easily do this) - but this particular image is served from gravatar and I am not sure if their api supports this.

**Comment by scd** [comment]
I am not sure if this is fixed or not now, but the avatar look ok. Closing and will re-open if the issue comes up again.
