### ISSUE TITLE
Private Discussions show variable instead of value

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3284]
**What happened?**

In a private discussion the variable is shown in curly brackets and not the value (see screenhsot).

Ideally also provide screenshots:

**What you expected:**

The value of the variable in the correct language.

<img width="791" alt="screen shot 2018-10-03 at 18 43 27" src="https://user-images.githubusercontent.com/19162952/46443670-8ea5dd00-c73c-11e8-8ca1-fd8d68741dee.png">

**Comment by brendanheywood** [comment]
dup of https://github.com/theCrag/website/issues/3264
