### ISSUE TITLE
can not add routes to circuits

### ISSUE THREAD

**Issue by oni303** [theCrag/website#3287]
After creating a circuit the "Add route to active circuit" button does not appear.
Tried to create a circuit in a "field" and "boulder" button did not appear in both case.

Browsers used:
Chrome
Firefox

Did I misunderstood https://www.thecrag.com/en/article/circuits?

I am sorry but I do not know how to provide more details on this

**Comment by scd** [comment]
Circuits was a bit of a false start for us but we have stopped work on them for now. We will start again at some point as they are planned to be part of a something we plan in the future. Thanks for reporting the issue but it will be a while before we get time to work on this one.

**Comment by brendanheywood** [comment]
See also https://github.com/theCrag/website/issues/1318

**Comment by oni303** [comment]
Ok thanks, please put a note in https://www.thecrag.com/en/article/circuits

**Comment by brendanheywood** [comment]
I have added a note:

https://www.thecrag.com/en/article/circuits
