### ISSUE TITLE
circuit count counts deleted circuits

### ISSUE THREAD

**Issue by oni303** [theCrag/website#3288]
After deleting circuits they are still counted in areas and climbers overview.

[this](https://www.thecrag.com/climbing/germany/harz-mountains/area/1960552047) says there are 4 but after clicking the [link](https://www.thecrag.com/climbing/germany/harz-mountains/area/1960552047/circuits) only 2 are displayed, as I deleted 2.

same [here](https://www.thecrag.com/climber/oni) and [following](https://www.thecrag.com/circuits/by/oni/)

**Comment by brendanheywood** [comment]
Sorry @oni303 but the article is out of date. The circuit concept is still there but has not been supported for a while and is a bit broken in several places.

We intend to rework it and you can read about the plans here:

https://github.com/theCrag/website/issues/1318

I will close these two new issues, please have a read of that issue and add comments there with your thoughts on the direction
