### ISSUE TITLE
Lower character limit for subsequent shots

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3289]
**What happened?**

While ticking a route, the character limit for shots 2 onward is just 500 characters, while shot 1 has 4096 characters. However, all shots are stored as separate ascents, which can be edited afterwards, where the full 4096 limit is in effect again.

<img width="545" alt="screenshot 2018-10-11 19 54 54" src="https://user-images.githubusercontent.com/54371/46823907-bece2b00-cd8f-11e8-975c-16b6a8c6a897.png">

**Comment by brendanheywood** [comment]
fixed

![image](https://user-images.githubusercontent.com/187449/46842235-38116080-ce18-11e8-87a4-28c8a09cd5d7.png)
