### ISSUE TITLE
Topo Tool: Hide and Edit Button oversized

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3290]
**What happened?**

E.g. in this stream event https://www.thecrag.com/climber/stephanmitter (Gjipe Topo) if I click on zoom and hover over the topo the Hide and Edit buttons take up half of the screen.

Ideally also provide screenshots:

**What you expected:**

Normal sized buttons
![topo](https://user-images.githubusercontent.com/19162952/46922894-af442180-cfdd-11e8-8530-5eb80c525c1e.jpg)

**Comment by brendanheywood** [comment]
Closing as dup of and will be fixed in https://github.com/theCrag/website/issues/1911
