### ISSUE TITLE
Inherit feature height to routes length 

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3291]
I have a lot ascents without height/length information. This is because Gyms don't set that data for their routes. It would be to much effort to maintain this information every time a new route is set up. To ease the maintenance of this information it would be helpful to set the height to a feature of the gym. All routes in/on this feature inherit that length.

**Comment by brendanheywood** [comment]
+1 this is a great idea, and I think has broad use outside not just in the gyms

**Comment by rouletout** [comment]
+1 from gym https://www.thecrag.com/climbing/austria/wien-vienna-area/area/1661867997

**Comment by lordyavin** [comment]
Alé

**Comment by lordyavin** [comment]
So the great idea is still pending to be implemented.

**Comment by Mdemaillard** [comment]
Implemented 
Tested as follow: - default height is editable at gym level, creating a new route is autopopulated, deleting the autopopulated value during creation still result in a new route with default height filled in.
To be closed ?

**Comment by scd** [comment]
I think close the issue. We don't want routes going in without height, so
if a route is different from the default then the person entering should
just use it. Create a new issue if we need the bug fixed
