### ISSUE TITLE
Restore the previous/next route links and provide them on mobile

### ISSUE THREAD

**Issue by johnpitcairn** [theCrag/website#3293]
Recent upgrades have removed the previous/next route links that were to the left and right of the page edges in desktop view. Those were a really handy navigational aid when browsing through the routes on a cliff. It would be great to have them back.

It would be REALLY great if they were available for mobiles (they were not previously). This would be extremely useful when actually at the crag.

Initially just a couple of linked arrows somewhere would be fine - either side of the route title region perhaps - but ultimately perhaps swipe-left and swipe-right?

**Comment by brendanheywood** [comment]
Thanks @johnpitcairn - this was a regression in the recent redesign work, I have added these back on desktop.

When we first added these links we did actually have them on mobile with a swipe left / right gesture and we got a lot of complaints about it being triggered unintentionally and so we removed them after a couple years. 

We still have a large set of plans for how to redo the site navigation on mobile and after that is done it should make the need for these extra buttons redundant. You will be able to open the nav 'hamburger' menu, and then move up and down and left and right through the entire index without reloading the page and then select and load the page to you want. Sorta like a directory / file picker. So a 'next' or 'prev' will be one tap to open the nav, then a second tap to go next.

**Comment by johnpitcairn** [comment]
> When we first added these links we did actually have them on mobile with a swipe left / right gesture and we got a lot of complaints about it being triggered unintentionally and so we removed them after a couple years.

What was the gesture support library? I worked on a couple of things like this a few years back, the compatibility and tunability has improved a fair bit since then. At the time I found I needed to tune the response so it required a full swipe across 3/4 of the width before triggering.

But 2-tap access to explicit previous/next links would be fine, and sure easier to implement. I think perhaps adding explicit "previous route" and "next route" items at the top of the expanded route list if it is longer than, say, 8-10 items, might be better than having to hunt in a long list of routes to find where you are now then click the next item. 

Meanwhile, would still be keen to see those moved somewhere on the page on mobile, since they're already there on desktop and you're presumably just hiding them?

**Comment by brendanheywood** [comment]
It's more complicated than that, many browsers like chrome have their own swipe left and right gestures, and many OS'es themselves add gestures. Like in iOS a hard swipe from the left edge goes to another application, in chrome (goes back in history) or other embedded webviews it can do other things like next tab, or next article. It is really hard to get sensible support everywhere even if the gesture itself is well tuned. This is particular bad on things like maps pages (my main focus at the moment is a big maps rebuild) where a swipe pans the map, and you can end up with a swipe starting a little too close to the edge doing 2 or even 3 different actions simultaneously. Doing something like this in a native mobile app makes more sense where you have tighter control over everything.
