### ISSUE TITLE
Translation: Variable Shown instead of number in forum

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3294]
**What happened?**

On my dashboard I found this entry in the stream:

<img width="868" alt="screen shot 2018-10-20 at 10 09 40" src="https://user-images.githubusercontent.com/19162952/47256580-ba210b00-d450-11e8-841d-66fc4a220fed.png">

Ideally also provide screenshots:

**What you expected:**

The number should be shown

**Comment by brendanheywood** [comment]
@rouletout to make it easier to reproduce and you please grab the url of the event itself, click on the down arrow and the list 'Comment on this event', and make sure you can reproduce the issue on that event page too. In this case the event detail page is:

https://www.thecrag.com/event/1974344280

I've just had a look into this and fixed it:

![image](https://user-images.githubusercontent.com/187449/47277105-77099800-d608-11e8-880f-20cdf7918039.png)

**Comment by brendanheywood** [comment]
@rouletout to make it easier to reproduce and you please grab the url of the event itself, click on the down arrow and the list 'Comment on this event', and make sure you can reproduce the issue on that event page too. In this case the event detail page is:

https://www.thecrag.com/event/1974344280

I've just had a look into this and fixed it:

![image](https://user-images.githubusercontent.com/187449/47277105-77099800-d608-11e8-880f-20cdf7918039.png)

**Comment by brendanheywood** [comment]
This is fixed:
![image](https://user-images.githubusercontent.com/187449/47277770-074adb80-d60f-11e8-8cec-4ad72886055a.png)

I did close this already but github had an outage and got a bit weird
