### ISSUE TITLE
Some big stats for new tick types have no label

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3296]
**What happened?**

These both have a big stats of 25, with no label:

https://www.thecrag.com/climber/dturf1

https://www.thecrag.com/climber/mittystewart13

The missing label is a language issue, but in both cases it's an 'allfreerest'. 

**What you expected:**

* [ ] everything should have a label at minimum
* [ ] we should probably filter or map the tick types which can be in the big stats (I think we are but might just need to tune this)
* [ ] the dturf1 example is a bit weird as both grades are 25. If I've ticked 25, I really don't care about anything else at the same grade at the same or lower 'purity'. ie if I have 'onsighted' 25 then it's pointless to also show that I have red pointed 25. I would only show both if I have onsighted 25 but redpointed higher at 26. Likewise if I had redpointed 24 I wouldn't show that either.

**Comment by Mdemaillard** [comment]
The all free with rests are not visible, but the same profiles shows other issues:
- a 25 when the pyrammid shows a 26 pinkpoint --> the ascent is 26 on a route 25.
There should probably be coherence in what is shown in big stat and pyrammid: either both the ascent grade, or both the route grade.

- and a 23 flashed when there is 2 23 onsight in the pyrammid, with scent grade = route grade = 23.

**Comment by rouletout** [comment]
Seems to be gone - closing until it reappears
