### ISSUE TITLE
Route count stat is not correct or updating after reset

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3301]
**What happened?**

This node says 3 routes:

https://www.thecrag.com/climbing/australia/eastern-suburbs/area/2002906746

**What you expected:**

* [ ] It should say 15

**Comment by brendanheywood** [comment]
@scd marked as must be done only to triage it's not something worse / wider from last release

**Comment by rouletout** [comment]
Says now 15 and it is 15, closing
