### ISSUE TITLE
Negative route count in seasonality chart

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3304]
**What happened?**

The seasonality chart shows a negative entry for november here:

https://www.thecrag.com/climbing/germany/oberpfaelzer-wald/area/934782816

![screenshot 2018-11-09 13 01 06](https://user-images.githubusercontent.com/54371/48261534-b49b5d00-e41f-11e8-9b25-3b35a00cce3a.png)

**Comment by quaestor** [comment]
Might be the same problem as #3545.

**Comment by rouletout** [comment]
This is gone but we don't know why. Closing - create new issue if this shows up again.
