### ISSUE TITLE
Clicking on a link doesn't open new window 7 page

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3305]
**What happened?**

Clicking e.g. here on the link https://www.thecrag.com/climbing/austria/wien-vienna-area/area/1661867997 opens the link in the same window.

Ideally also provide screenshots:

**What you expected:**

Opening of a new window.

**Comment by brendanheywood** [comment]
Which link and from what page?

**Comment by rouletout** [comment]
The link to the gym - weirdly it is just this page where it happens

**Comment by brendanheywood** [comment]
Whether it opens in a new window is an attribute of the link itself, and nothing to do with the destination url. This fixed and hot fixed
