### ISSUE TITLE
Import ascent process broken with search update

### ISSUE THREAD

**Issue by scd** [theCrag/website#3306]
**What happened?**

Importing ascents relies on the now defunct fuzzy search algorithm. It kind of still works because an old file is still hanging around, but it will not work with matching newly added routes. 

This issue was found in dev not matching any routes when there was a clear matches.

**Comment by scd** [comment]
No I did not do anything. It is possible that if a route was just created
it may not have been added to the search index

**Comment by nicHoch** [comment]
@scd 
no it is working: the route is found!
the question is if you think the fuzzy search is generally working and we can close this card

**Comment by Mdemaillard** [comment]
#3697 seems to be a recent duplicate ?

**Comment by scd** [comment]
I think we can close. Fuzzy search should still be working in general
