### ISSUE TITLE
Topos in streams are variable sized, in some cases really small

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3307]
**What happened?**

Compare the topo in this stream event:

https://www.thecrag.com/event/734068800

to this one:

https://www.thecrag.com/event/2106121590

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/187449/48412231-2ebd4000-e798-11e8-91ad-34ef02b22f4b.png)

**What you expected:**

* [ ] all topos should be large enough to be useful, like the one on the right

**Comment by nicHoch** [comment]
+1 
even worse with buttons:

![grafik](https://user-images.githubusercontent.com/2226714/48417292-b08a7a80-e752-11e8-8b26-2061f2cd2b9e.png)

https://www.thecrag.com/event/2109330699

**Comment by brendanheywood** [comment]
Another example which is way worse:

https://www.thecrag.com/event/2603949735
![image](https://user-images.githubusercontent.com/187449/60972336-64d3b380-a369-11e9-874e-15f53a165768.png)

**Comment by brendanheywood** [comment]
Another https://www.thecrag.com/event/2558631351

These should all be a fixed height, and I think the very last one is the correct intended height. It could probably be ever smarter than and if there is only 1-4 topos them make them bigger again, then if there are tons around the size of that last one, and then if there are really heaps just truncate the list and link to more as we currently do

![image](https://user-images.githubusercontent.com/187449/61097673-833bcb00-a49f-11e9-9caa-1c80dee7e42f.png)

**Comment by brendanheywood** [comment]
Also they should be grouped, we don't need to repeat 'Updated a topo for Sector 2' or 'Made a topo for sector 2' for each one. It should just be the batch of new ones, and then another batch of updated ones.

**Comment by brendanheywood** [comment]
They seem to be getting even smaller...

https://www.thecrag.com/event/2655215793

![image](https://user-images.githubusercontent.com/187449/62463846-6b214800-b7ce-11e9-9b04-48f32c35068d.png)

**Comment by georg-d** [comment]
On mouse over the thumbails, the mouse pointer turns into "zoom in icon" but clicking does nothing in most tries and in the few tries it does trigger a size increase of the image, the overlay buttons increase as well - so most of the pic is still invisible. That few tries work and most not has nothing to do with different browsers, sessions or the like but all within one session - reason is the *tiny area* where a click is recognized.

**Comment by rouletout** [comment]
I haven't seen this in a while and the zoom also works. Closing, please re-open if you think it is not solved
