### ISSUE TITLE
Own position in leaderboards gone

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3308]
There used to be a section below the leaderboard filters and above the actual table showing your own position in the board, with a link to get to the correct page. That seems to have gone. Is that intentional?

**Comment by brendanheywood** [comment]
Woops, nope thats a regression. I have just fixed that. Should be live mid next week

![image](https://user-images.githubusercontent.com/187449/48557420-d1152900-e93a-11e8-971d-ef62720d4edc.png)
