### ISSUE TITLE
Topo Image: can not select from existing image

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3310]
**What happened?**

I thought this is already logged but couldn't find it. Nevermind, "Load from an Image URL" gives an error on Get Image for Phototopo. Images have to be loaded twice as image and as topo image which is really a pain in the ...

<img width="752" alt="screen shot 2018-11-16 at 18 02 37" src="https://user-images.githubusercontent.com/19162952/48653286-d3729400-e9c9-11e8-9952-5a8f8dfc586b.png">

Ideally also provide screenshots:

If I paste an image URL that the image is loaded for drawing a topo

**Comment by brendanheywood** [comment]
Dup of 
https://github.com/theCrag/website/issues/2693
