### ISSUE TITLE
Avoid/supress linking

### ISSUE THREAD

**Issue by gogulfresh** [theCrag/website#3314]
**What happened?**
A link to a route is created where it shouldn't/I don't want. How can linking be suppressed?

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/austria/route/1529281464 
The word "spalt" in the description links to the route "spalt" 
https://www.thecrag.com/climbing/austria/route/1532385009
spalt ~= crack in german, thus in the text it is refering to a crack of this route and not the route "spalt"

Ideally also provide screenshots:

**What you expected:**

* [ ] Have a option to suppress linking for a certain word
* [ ] Have it documented here https://www.thecrag.com/en/article/updatingdescriptions

**Comment by scd** [comment]
We sort of have this black list, but it is not very well developed. 

Notes to self: I think it is the variable CapitalisedNameBlacklist in Markdown.pm. However I am wondering why we have not already blacklisted the word Crack. Once we black list a word in one language we should consider doing it in all langauges.

**Comment by gogulfresh** [comment]
Hmm, I thought more abouth smth like [nolink]Spalt[/nolink], then you would have the flexiblitly to link if you would like to link.

**Comment by brendanheywood** [comment]
I don't want average users needing to think about this, it should "just work". I'll close this and add this as another example to this issue:

https://github.com/theCrag/website/issues/2492
