### ISSUE TITLE
Remain logged-in on iOS

### ISSUE THREAD

**Issue by dmucli** [theCrag/website#3317]
On iOS you need to login every time you visit the website. Would be great to always remain logged in.

**Comment by brendanheywood** [comment]
hi @dmucli I'm logged in permanent on iOS, I don't think this is something on our side, I suspect this is some sort of safari privacy magic or feature.

This may help:

https://forums.developer.apple.com/thread/104851

I am curious whether there is anything around the periphery that we can do to make safari not do this, perhaps it is deciding for some reason (tracking cookies or ads etc) that we aren't trustworthy and only maybe after you've been using us for a while it lets the sessions stay for longer like mine are.

**Comment by dmucli** [comment]
Thanks

**Comment by dmucli** [comment]
It seems turning on auto-logging in safari is doing the trick. Thought it already was but it wasn't, but now that it is safari hasn't asked for a login anymore so assume it works. Thanks for helping.
