### ISSUE TITLE
Warn about copyright issues in photo upload

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3318]
**What you expected:**

The photo upload page doesn't discourage uploading copyrighted content at the moment. Also, I didn't find anything about that issue in the help pages / acceptable use except one brief mention on the "embedding photos" help page.

This should be more prominent, I think.

**Comment by lordyavin** [comment]
+1

**Comment by rouletout** [comment]
This was added and will be available on next release. Closing.
