### ISSUE TITLE
Enable logging of In-between grades

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3320]
**What happened?**

Wanted to log an ascent where I'm not sure with the exact (UIAA) grade and wanted to log a In-between grade. With the current drop-down this isn't possible.

![grafik](https://user-images.githubusercontent.com/1528540/49511880-a4469880-f88c-11e8-9596-6463cbcdc076.png)

**What you expected:**

* [ ] A simple input field similar to the field used when editing the route grade contribution instead of the drop-down

Additionally this would improve usability on mobile devices. It is a pain the ass to scroll the long list of grade systems.

**Comment by Mdemaillard** [comment]
addition to #1951

**Comment by lordyavin** [comment]
Duplicate of #3114

**Comment by Mdemaillard** [comment]
thanks missed that one
