### ISSUE TITLE
Area streams empty when lang is selected

### ISSUE THREAD

**Issue by scd** [theCrag/website#3322]
**What happened?**

Area streams empty when lang is selected. 

https://192.168.56.2/climbing/australia?lang=it

In the html the stream embed url that is generated is 

https://192.168.56.2/climbing/australia?lang=it/stream

![screenshot from 2018-12-12 07-24-46](https://user-images.githubusercontent.com/373058/49828138-37c51f80-fddf-11e8-87fe-5e40cd8ef7ba.png)

**Comment by Mdemaillard** [comment]
Tested working on prod and sandpit with multiple non English languages Inc. IT
