### ISSUE TITLE
Route menu partially hidden on mobile

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3323]
**What happened?**

Selecting multiple routes and then clicking "Edit" results in a partially hidden menu, see screenshot.

Ideally also provide screenshots:

**What you expected:**

Menu on top, not overlapping
![img_3775](https://user-images.githubusercontent.com/19162952/49948394-fdc84c00-feb8-11e8-9a0c-4ed90412d273.PNG)

**Comment by lordyavin** [comment]
May be correlated with #2690.

**Comment by Mdemaillard** [comment]
Sorted for me on android + chrome.
tested with different sequence of selection (the menu start on the last selected route.
Also tested on "selected routes as a block" or "selected routes leaving a gap" as per screenshot
![image](https://user-images.githubusercontent.com/60388146/76847698-23c26600-684b-11ea-8ab8-043b92e937d0.png)
