### ISSUE TITLE
/api/route/create error "not a hash"

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3328]
**What happened?**
Trying to create a route via API endpoint /api/route/create on sandpit. 

**POST /api/route/create HTTP/1.1**
Host: sandpit.thecrag.com

**Header**
```
Accept-Encoding: identity
Content-Length: 463
Accept: application/json
Content-Type: application/json
X-CData-Key: key=mykey
User-Agent: Swagger-Codegen/1.0.0/python
```

**Body**
```
{
  "data": {
    "name": "Vier F\u00e4uste f\u00fcr ein Haleluja",
    "parent": 563201517,
    "submittor": 422926173,
    "context": "UIAA",
    "gearStyle": "Sport",
    "heightText": "12",
    "pitches": "1",
    "gradeText": "6",
    "history": [
      {
        "type": "Route Setter",
        "date": "2018-10-15",
        "climbers": "Thommy",
        "diary": ""
      }
    ]
  }
}
```

**Bad Request (400) response**
**Header**
```
Date: Thu, 27 Dec 2018 15:00:44 GMT
Server: Apache/2.4
Strict-Transport-Security: max-age=15768000
Content-Length: 166
Connection: close
Content-Type: application/json; charset=utf-8
```

**Body**
`{"apiKey":"mykey","contentType":"application/json","error":"not a hash","errorLabel":"post-data-validate-error","method":"POST","remote_ip":"myip"}`

**What you expected:**

* [ ] Better error message that points to the issue.
* [ ] No error 😉

**Comment by scd** [comment]
Hmm, I have tried to replicate using curl and I get this:

```
Replicate Kai issue
{
   "data" : {
      "context" : "UIAA",
      "gearStyle" : "Sport",
      "gradeText" : "6",
      "heightText" : "12",
      "history" : [
         {
            "climbers" : "Thommy",
            "date" : "2018-10-15",
            "diary" : "",
            "type" : "Route Setter"
         }
      ],
      "name" : "Vier Fäuste für ein Haleluja",
      "parent" : 563201517,
      "pitches" : "1",
      "submittor" : 422926173
   },
   "error" : {
      "error" : "no authorisating information"
   }
}
```

This is an error from the update function not getting the auth record. This should not be happening so something is broken somewhere.

**Comment by lordyavin** [comment]
So no idea why my JSON data is not accepted? Or is it something completly different? I tried without indentation and newlines. Same result.

**Comment by lordyavin** [comment]
Any updates?

**Comment by scd** [comment]
No. Can you please outline how fixing this will help so we can prioritise.
As the app is currently closed we are not putting much work into it unless
it is breaking an overall process.

**Comment by scd** [comment]
Note to self. Next step is to set up some logging of the actual data received. Nothing obvious.

**Comment by lordyavin** [comment]
So this is completely broken? Tried to just send the mandatory data. No change in behaviour. Look like I have to drop the usage of the API.

**Comment by scd** [comment]
Our capacity to properly support the API is the main reason why we closed it. If you have high expectations for timely support on the API you should stop using it as it will cause frustration.

However if you can loosen your expectations then I am willing to continue to try and find some time to get through these issues. I have already had put time aside twice to resolve this, but it is not obvious what is going on because I cannot replicate.

I have implemented some forensic reporting on your api key. Please try again so I can see what the debug is saying. Also note that you should not be using any personally sensitive information in the api for your key while I have the forensic reporting going.

**Comment by scd** [comment]
BTW you should do this on sandpit.thecrag.com

**Comment by lordyavin** [comment]
Hey @scd thanks for your response and time you invest. I'm aware that the API is of low priority and I'm appreciate it very much that you gave me access to it. I will be patient but loosen expectations isn't the right ways to search for excellence 😉 During dev I use the sandpit only. Frustrating is that I can't even workaround the issue with partial data.

**Comment by scd** [comment]
Did you test again so I can see the logs

**Comment by scd** [comment]
hmm I am not even getting something logged. This is wierd. I will pm you a curl command

**Comment by scd** [comment]
Actually I now know why I did not get the first one. Logging was turned off during the release process.

Please try a third time.

**Comment by lordyavin** [comment]
once again

**Comment by scd** [comment]
Ha I think I know what it is. Remove the umlats and try again.

A working response looks like this:

```
/api/route/create: 2019/01/15 11:42:40 Validated POST data:$VAR1 = {
          'data' => {
                      'gradeText' => '6',
                      'context' => 'UIAA',
                      'heightText' => '12',
                      'pitches' => '1',
                      'gearStyle' => 'Sport',
                      'parent' => 563201517,
                      'name' => "Vier F\x{e4}uste f\x{fc}r ein Haleluja",
                      'submittor' => 422926173,
                      'history' => [
                                     {
                                       'climbers' => 'Thommy',
                                       'date' => '2018-10-15',
                                       'type' => 'Route Setter',
                                       'diary' => ''
                                     }
                                   ]
                    }
        };
```

Your response looks like this:

```
/api/route/create: 2019/01/15 12:01:16 POST data failed validation:{
  "data": {
    "name": "Vier F\u00e4uste f\u00fcr ein Haleluja",
    "parent": 563201517,
    "submittor": 422926173,
    "context": "UIAA",
    "gearStyle": "Sport",
    "heightText": 12,
    "pitches": 1,
    "gradeText": "6",
    "history": [
      {
        "type": "Route Setter",
        "date": "2018-10-15",
        "climbers": "Thommy"
      }
    ]
  }
}
```

Note that the umlats have translated differently. To be frank the system behaves particularly badly when character encoding is wrong.

Let's worry about the work flow first then work out which end the character encoding is wrong at. Note that you will still not get the route created because you have not authorised the person submittor through an oauth procedure. Did I send you your secret key, which you will need for this.

BTW I am on my paid job for next three days so I cannot do much more again for a while. I should be able to send you a secret key if you don't have it.

**Comment by lordyavin** [comment]
Don't have such a secret key yet.

So, which encoding do I have to configure? I assume currently I'm using unicode.

**Comment by scd** [comment]
Utf8, but let's solve one thing at a time. Will pm you the secret key.

**Comment by lordyavin** [comment]
I replaced the Umlaute but still getting the error "not a hash". I did not set the OAuth stuff yet.

**Comment by scd** [comment]
Please try again. I have made some minor adjustments, but I still expect to see it fail.

**Comment by lordyavin** [comment]
Still fails as you said. I sent two different create posts. Still without OAuth headers. I read some doc about OAuth, OpenAPI and Swagger and I need some time to understand it and getting it to work.

**Comment by scd** [comment]
Now I am getting somewhere. Here is the raw data that is being sent

```
""{\n  \"data\": {\n    \"name\": \"some route\",\n    \"beta\": [\n      {\n        \"type\": \"Description\",\n        \"description\": \"some description\"\n      }\n    ],\n    \"parent\": 82079136,\n    \"submittor\": 9068185,\n    \"context\": \"AU\",\n    \"gearStyle\": \"Trad\",\n    \"heightText\": \"24,26\",\n    \"pitches\": \"3\",\n    \"bolts\": \"4\",\n    \"gradeText\": \"12,22M1\",\n    \"history\": [\n      {\n        \"type\": \"First Ascent\",\n        \"date\": \"2011-02-09\",\n        \"climbers\": \"some climber\",\n        \"diary\": \"diary entry\"\n      },\n      {\n        \"type\": \"First Free Ascent\",\n        \"date\": \"2011-00-00\",\n        \"climbers\": \"another climber\",\n        \"diary\": \"another entry\"\n      }\n    ],\n    \"lat\": 45.45,\n    \"long\": -22.45\n  }\n}""
```

I think there may be a double escape issue or quote issue. I think the API is parsing this as a valid json because the whole string is quoted and saying it is not a hash.

**Comment by lordyavin** [comment]
To get it right, the first quote in the string you posted should not exist?

The debug output of the Swagger generated Python-API gives me this:
`send: b'"{\\"data\\": {\\"name\\": \\"TestRoute\\", \\"parent\\": 563170551, \\"submittor\\": 422926173, \\"context\\": \\"UIAA\\", \\"gearStyle\\": \\"Sport\\", \\"gradeText\\": \\"6+\\"}}"'`
The JSON string that I create with [json.dumps](https://docs.python.org/3.7/library/json.html) is displayed by the debugger as following:
`str: {"data": {"name": "TestRoute", "parent": 563170551, "submittor": 422926173, "context": "UIAA", "gearStyle": "Sport", "gradeText": "6+"}}`
If I don't use the json.dumps and pass the dictionary directly, the debug output looks equal for this sample. So it looks like this is an error in the generated Python-API I use.

**Comment by lordyavin** [comment]
I stepped through the generated Python-API sources and learned that I don't need to use json.dumps by myself. This introduces an extra quote. If I omit the manual json.dumps call, it should work because I expect the sent data to be correct. But it still fails.

**Comment by lordyavin** [comment]
Ah tried it again, and now I'm getting `"error":{"error":"no authorisating information"}}`
