### ISSUE TITLE
YDS pure number grades not "correctly" valued

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3329]
**What happened?**

From support:

Another suggestion I have is regarding the YDS grading scale. I have noticed that whenever a rout is graded with a "-", "+" , "a/b", "b/c", "c/d" the registered ascent will not be taken into account for Grade Pyramids.
I have discussed this with several climbers in many different crags around México, and the USA and have concluded that the following is true:

5.12- = 5.12a/b
5.12  = 5.12b/c
5.12+ = 5.12c/d

and i have noticed that theCrag does not consider a solid 5.12 to be harder than a 5.12a or a 5.12b

Ideally also provide screenshots:

**What you expected:**
See above

**Comment by scd** [comment]
CPR and grade conversions determines this. 

5.12+ is a different grading system to 5.12d. There are conversions to an internal grade. 

The statement that of what climbers think is not consistent. Is a 5.12c equivalent to 5.12 grade or a 5.12+? Our internal conversions deals with all this. They can be tweaked if necessary.

If you look at CPR for 5.12 it should be about the same as 5.12b/c.

The CPR for 5.12 is harder than the CPR for 5.12a

**Comment by rouletout** [comment]
I was just following up on Albertos request from a few days ago and checked the CPR values for YDS variants (5.11- / 5.11 / 5.11a) by logging some ascents and looking at the ascent details page to get the base value of he respective CPRs (the CPR Tool does not allow entering e.g. 5.11- or 5.11 alone).

I found the following base CPR values:

5.11a:  2452
5.11-:  2428
5.11:   2685
5.11+: 2848
5.11d: 2828

What I find a bit weird is, that the + and - grades are below and above the maximum / minimum grades 11a and 11d respectively. 5.11 is somewhere in the middle which makes sense.

**Comment by Mdemaillard** [comment]
duplicate of #1117
closely related to #3042
