### ISSUE TITLE
Map error

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3336]
**What happened?**
clicking somewhere on the map in Switzerland zooms/pans to an area in Africa 

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/switzerland/alpen/maps#46.883,8.433,9.0,,auto

just click on the map (not a route donut)

**Comment by brendanheywood** [comment]
This is a data issue with 

https://www.thecrag.com/climbing/world/area/837795843

I reckon move this into the test area (which is excluded)

**Comment by nicHoch** [comment]
@brendanheywood  ok i did not realize the "climbable rock" info window. Thanks!

if fixed it: https://www.thecrag.com/event/2192133846
