### ISSUE TITLE
Ascent facet group by cliff / boulder isn't working all the time

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3339]
**What happened?**

Example url(s) to reproduce the problem:
https://www.thecrag.com/ascents/by/brendanheywood

![image](https://user-images.githubusercontent.com/187449/51115249-cd7b2100-185b-11e9-94e4-1f452b815854.png)

**What you expected:**
* [ ] super leage in 'the garden of steeden' not in 'the beach'

**Comment by rouletout** [comment]
This is now correct: https://www.thecrag.com/ascents/between/+2019-01/by/brendanheywood/?sortby=when-climbed,desc

Closing
