### ISSUE TITLE
Maps: too many labels shown

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3342]
**What happened?**

For example if you open https://www.thecrag.com/climbing/new-zealand/north-island/area/2164010358 you see a dozen of labels on top of each other - one zoom out it shows just one which would be nicer.

<img width="930" alt="screen shot 2019-01-15 at 11 11 04" src="https://user-images.githubusercontent.com/19162952/51197195-748ca680-18b6-11e9-960a-ef943db3b471.png">

Ideally also provide screenshots:

**What you expected:**

A view like this:

<img width="980" alt="screen shot 2019-01-15 at 11 12 48" src="https://user-images.githubusercontent.com/19162952/51197245-938b3880-18b6-11e9-9397-e71053b153e0.png">

**Comment by nicHoch** [comment]
Its a data issue. The problem is that all sectors are set to gyms and therefor are treated as independent areas. >I would propose to change the sub node to sectors.

**Comment by brendanheywood** [comment]
No, the node type doesn't matter for a gym. This is actually a feature, kinda. At the maximum zoom level all labels are shown. I think in most cases this is correct, it doesn't work here. The best solution here is to just redraw the gym outline so it is the correct larger footprint of the building, which will mean the zoom level is back a step. I've done this:

![image](https://user-images.githubusercontent.com/187449/51223832-93af3500-1997-11e9-8dc0-fe8d034ab977.png)

**Comment by brendanheywood** [comment]
btw we should also do what @nicHoch said, the nodes should not be gyms but sectors
