### ISSUE TITLE
Map Edit Tool Tips Update required

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3344]
**What happened?**

When editing maps, the follwoing tool tips are shown (see screenshot). these should be updated to reflect the current functionality / be clearer:

<img width="448" alt="screen shot 2019-01-20 at 11 27 27" src="https://user-images.githubusercontent.com/19162952/51443330-0c223880-1cad-11e9-8b18-d9d044fe2756.png">

Ideally also provide screenshots:

**What you expected:**

Remove Text & Link: Learn how to draw tracks....

Bullet 3, the 2nd sentence is not correct, should be: You can add extra "temporary snap markers" to help you draw boundaries if you have corresponding GPS coordinates.

**Comment by rouletout** [comment]
Yep, good point - change the phrase to:

For more details please refer to **Maps and geolocations**

**Comment by rouletout** [comment]
Still the same, please resolve

**Comment by brendanheywood** [comment]
done

https://brendan.thecrag.com/climbing/australia/ebor-gorge/locate
![image](https://user-images.githubusercontent.com/187449/54878792-77db7a00-4e85-11e9-91f0-d1995ef1d438.png)

Note: nothing at all on this page is translatable yet
