### ISSUE TITLE
Don't list archived routes in "insert before" list

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3347]
**What happened?**

Added some gym routes and changed the default insertion. It bugged me that the archived routes are listed. This is irritating.

![grafik](https://user-images.githubusercontent.com/1528540/51493518-e3399a80-1db5-11e9-9e78-381f117803ac.png)

[add route](https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3APushReturnURL=%2Fclimbing%2Fgermany%2Farea%2F563201937&D%3ANetworkNodeID=563201937&C%3AState=2059&D%3ASkipCite=1&C%3AHideNavigation=1)

**What you expected:**

* [ ] Don't list archived routes in "insert before" list

**Comment by lordyavin** [comment]
Updated the issue.

**Comment by scd** [comment]
Fixed in simon's dev. Will be part of next release
