### ISSUE TITLE
Make it easier to add / edit aspect tags

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3349]
**What happened?**

I've been adding a ton of aspect tags lately, and it is a little slower that it should be. I can see a couple ways to improve it.

**What you expected:**

* [ ] when editing the tags you can filter by typing, but if you press 'E' or 'N' it does practically nothing. It would better if the tag names were 'North' and 'North east' so you can filter them with 'No'
* [ ] Similar to how we added the quick edit widget for missing gear styles, it would be great to have something similar for crags with missing aspect, inline in the area list view, or at least within the location edit page so you can do batches of siblings areas together

**Comment by rouletout** [comment]
It would also be very helpful if you could add the tags when you create an area for the first time. Tag adding is only available on edit.

**Comment by Mdemaillard** [comment]
First box is implemented.
Second one is duplicated in #3445
third in comment is part of #1892
Closing here to limit input spread.
