### ISSUE TITLE
Ranking Page embeds include personal ranking which breaks the iframe layout

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3351]
**What happened?**

https://www.thecrag.com/de/artikel/rankings doesn't display the male sport ranking correctly - see screenshot

<img width="883" alt="screen shot 2019-01-25 at 10 29 12" src="https://user-images.githubusercontent.com/19162952/51758845-50864d80-208c-11e9-8a19-a6d259e53854.png">

Ideally also provide screenshots:

**What you expected:**

Correct display

**Comment by brendanheywood** [comment]
Fixed the embed to exclude the personal ranking
