### ISSUE TITLE
Tags Missing 'no dogs' and midday sun

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3353]
**What happened?**

Would like to add a tag "midday sun" for crags that have morning and afternoon shade.

Also miss the tag for "no dogs allowed"

Ideally also provide screenshots:

**What you expected:**

Tag for midday sun and tag for "no dogs"

**Comment by quaestor** [comment]
Slightly related: #2931

**Comment by rouletout** [comment]
Implemented a while ago
