### ISSUE TITLE
Pink Point should have higher CPR than Top Rope for gym sport

### ISSUE THREAD

**Issue by scd** [theCrag/website#3355]
**What happened?**

If you log top ropes and pink points for a single gym sport climb then the grade pyramid picks the most recent because the CPR is the same for bot top rope and pink point gym ascents.  

Example url(s) to reproduce the problem:

https://www.thecrag.com/climber/magali

Lot's of pink points but not so many shown in grade pyramid. Look at the following as an example of pink points and top ropes being logged on the same route

https://www.thecrag.com/climbing/switzerland/jura/basler-jura/route/2074132335

Ideally also provide screenshots:

![screenshot from 2019-02-04 22-34-09](https://user-images.githubusercontent.com/373058/52206218-a39ea280-28cd-11e9-8372-51e7423751f3.png)

**What you expected:**

Pink points should be shown as priority over top ropes for grade pyramid. 

Consider bumping pink point tick shift up a little.

**Comment by lordyavin** [comment]
+1 but for some reason I think we've got an issue for that already. Couldn't find it.

**Comment by scd** [comment]
+1 for user comment for top rope onsights which are not showing as a green tick in the grade pyramid.

https://www.thecrag.com/climber/leirn

**Comment by nicHoch** [comment]
is this the same problem here?:

![grafik](https://user-images.githubusercontent.com/2226714/53015199-b7f4aa80-344a-11e9-91ca-f069a28c8f5b.png)

https://www.thecrag.com/climbing/germany/schwarzwald/route/2256596613

gym route two different styles (toprope and redpoint) but almost same CPR

**Comment by leirn** [comment]
> +1 for user comment for top rope onsights which are not showing as a green tick in the grade pyramid.
> 
> https://www.thecrag.com/climber/leirn

To be more precise on this case:
My point is about displaying only. If you compare with indoor bouldering, that you can see on my page too:

On indoor bouldering:
- On sight : green
- Flash : yellow
- Sent : blue
- Others : grey

On indoor sport climbing:
- On sight lead : green
- Flash lead : yellow
- Others : grey

If you simply add a blue category on indoor sport climbing for all sent but OS lead and flash lead, like it exists for indoor bouldering, it would be a good improvement already.

**Comment by scd** [comment]
I have added a small tick shift for pink points for gym sport routes so that they are higher then standard tick. After the next release we can see what it looks like.

**Comment by scd** [comment]
Both the issues here are fixed so gym sport route pyramid is now a bit more colourful
