### ISSUE TITLE
Help Article has starnge blue boxes

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3356]
**What happened?**

https://www.thecrag.com/de/artikel/cprtimeline shows light blue boxes under each graph - see screenshot

Ideally also provide screenshots:

**What you expected:**

no boxes
<img width="694" alt="screen shot 2019-02-05 at 08 32 16" src="https://user-images.githubusercontent.com/19162952/52280065-9363e300-2920-11e9-8f99-684498b0a42e.png">

**Comment by brendanheywood** [comment]
@scd the root cause here is this article is just not using the responsive iframe template. Look at the CPR article and minor/responsive-iframe

**Comment by Mdemaillard** [comment]
not visible for me on Desktop + Chrome. Closed already ?

**Comment by Mdemaillard** [comment]
Also not appearing on android phone. closing.
