### ISSUE TITLE
Kalymnos vs Aegean Islands in notable ascents

### ISSUE THREAD

**Issue by proceedhhx** [theCrag/website#3357]
In the notable ascents by area table, ascents in Kalymnos are shown as ascents in "Aegean Islands".

https://www.thecrag.com/climber/petabarrett

What I expected:
That the table shows Kalymnos instead of Aegean Islands.

**Comment by proceedhhx** [comment]
https://www.thecrag.com/climber/honigtoertchen

![stef kaly screen](https://user-images.githubusercontent.com/47369736/52718889-c7847700-2fa4-11e9-98e5-3ec08803d03e.jpg)

**Comment by birgander2** [comment]
I think this is because "Aegean Islands" is registered as a (top level) "crag" not as an "area" or "region". So more a principal question how to organise these crags in the database than a bug.

**Comment by rouletout** [comment]
+1 - this does not behave correctly

**Comment by scd** [comment]
I think this is a dup of: 

https://github.com/theCrag/website/issues/3493

**Comment by scd** [comment]
fixed in prod
