### ISSUE TITLE
Can not enter "date of birth" earlier than 2009

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3359]
**What happened?**
Just wanted to set the date of birth for a community managed account and the year selector let me choose only back to 2009.

*Can't provide a screentshot*

**What you expected:**

* [ ] free selection of date

**Comment by brendanheywood** [comment]
Why no screenshot? works for me?

**Comment by lordyavin** [comment]
Probably some JS is blocked by the companies Firefox setup (ESR 52.8). Could be the same issue for the date of birth selector.

**Comment by lordyavin** [comment]
Or it is blocked by GitHub. They are telling me that my browser versions are not supported any more. I even can't edit my comments.

**Comment by lordyavin** [comment]
So on my mobile I could set the birth of date. I think the problam is/was on my side.
