### ISSUE TITLE
Not all photos displayed on sector page.

### ISSUE THREAD

**Issue by proceedhhx** [theCrag/website#3360]
It seems that only photos linked to a specific climb of a sector are shown in the photo section of the "side bar". Is that intentional? This way I would have thought that there are no further pictured of the area.

https://www.thecrag.com/climbing/greece/kalymnos/arginonda/area/14190097
https://www.thecrag.com/climbing/greece/kalymnos/arginonda/area/14190097/photos

![screenshot 2019-02-07 13 49 17](https://user-images.githubusercontent.com/47369736/52416555-2439ea80-2aea-11e9-9f4f-dac5f3e49630.png)
![screenshot 2019-02-07 13 49 24](https://user-images.githubusercontent.com/47369736/52416560-28660800-2aea-11e9-9d0f-7c93e25c1926.png)

What you expected:
That all or the most useful photos of an area or sector are displayed in the sidebar so that I can get an impression of the area.

**Comment by brendanheywood** [comment]
@proceedhhx neither of those screen shots worked. You can just drag or copy paste photos into github comments. See this help doc:

https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

Also try and put in some urls of the area in question and photos that you expect should be shown?

**Comment by proceedhhx** [comment]
Ok got it. Thanks.

**Comment by brendanheywood** [comment]
Huh, weird yes these should show the pics linked to a cliff or area

**Comment by lordyavin** [comment]
Works for me as usual (mobile)

**Comment by proceedhhx** [comment]
Now it works for me too. Took some time or somebody did something.

**Comment by Mdemaillard** [comment]
looks like just some time processing the uploads (from 06 feb) to display (working on 7th).
Performance ? Maybe rebuilding cache / index of the pictures in the node ?
Proposal for closure
