### ISSUE TITLE
Searching within a node generates too much results

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3365]
**What happened?**

Tried to [search](https://www.thecrag.com/climbing/united-states/clear-creek-canyon/search?S=off+the+book) for the boulder "off the book" recently sent by Alex Pucio. The search results listed al lot but not the route. If the results would have been empty this would indicate that I'm searching at the wrong place or the route doesn't exist in the index yet.

**What you expected:**

* [ ] List results within this node only. In other words just list results of descendants.
* [ ] Align with facet search or drop one of the search UIs

**Comment by brendanheywood** [comment]
The direction I want to head in here is treat the node context as a proximity search, so it will first search for things in Clear Creek Canyon, then if there is still room for more results show them from Denver, then Colorado etc. If you want a hard filter then the area facet page is the best place, the search pages should be much more softer and try harder to get a good answer to vague searches

**Comment by lordyavin** [comment]
I see your point but please think a little bit more about usability. My use case is that I enter the search term into the field that is visible on every page of the site in the header just right to the breadcrumbs.

![grafik](https://user-images.githubusercontent.com/1528540/52735110-1c38e980-2fc7-11e9-9bc5-392fe56c7b1b.png)

The breadcrumbs gave me the idea that results will be from within this area but I got routes listed which are located in Australia and that is far away from the area I searched. If the results to vague(most of the time they are) I try to change the scope by navigating view the left menu or the breadcrumbs and the search is automatically repeated a step up or down in the tree.

The idea to have to types of search functionality is somehow bad for the user experience and guidance. Why two similar functions? When to use which? Why is the presentation of results different? ... Do you get my point?

BTW: I tried to redo my search with the [facet page](https://www.thecrag.com/climbing/united-states/clear-creek-canyon/routes) but either I still don't know how use the UI or there is no free text search for route names.

**Comment by rouletout** [comment]
+1 I also find the proximity of a breadcrumb to the search confusing as it suggests something that is not true

**Comment by rouletout** [comment]
added to https://github.com/theCrag/website/issues/3235 - closing here
