### ISSUE TITLE
PDF Guides extremely hard to find!

### ISSUE THREAD

**Issue by goshenw** [theCrag/website#3368]
I get that you can download PDF's from within each sub area... but accessing them is problematic.

I sometimes create a guide on my PC, then want to go to the correct place on my phone in order to download it there.   But for some reason, they are extremely hard to find, esp on a small screen.

Eventually I read the relevant help doc, which pointed me in the right direction (Action menu) when I actually read it.   I got frustrated last time I used it a few months ago; and again this time... and I was clicking every menu button / option I could find!

However some suggestions.
- [ ] Include a direct hyperlink from the help file to the users PDF's page.  Should be super easy to do that!
- [ ] 2nd, There are 3 main menus on The Crag.  The one across the top; the one on the LHS, and the one that drops down when you click your profile pic.    Can you "please" put a link on one of those menus; rather than, or as well as, the very obscure 'Action' button.
- [ ] The most intuitive place for the link to be would be in the RH menu, where it has 'Your Profile', 'Your Logbook'; Your etc...  Just have "Your PDF Guidebooks".  Solved.   :-)

Regards,
Goshen

**Comment by brendanheywood** [comment]
Yup these are all easy low hanging fruit :)

**Comment by brendanheywood** [comment]
done!

![image](https://user-images.githubusercontent.com/187449/59551092-8e422f00-8fb7-11e9-89d9-b61463f78f6e.png)
