### ISSUE TITLE
Grades Article: wrong info on YDS slash grades

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3369]
**What happened?**

In the list of examples in the grades article (https://www.thecrag.com/de/artikel/grades) a difference is explained between 5.12a-b and 5.12a/b which doesn't exist.

Ideally also provide screenshots:

**What you expected:**

5.12a/b is the same as 5.12a-b - the text needs to be updated

<img width="716" alt="screen shot 2019-02-20 at 15 03 14" src="https://user-images.githubusercontent.com/19162952/53124332-b39ac100-3520-11e9-8ab9-d37fe36ac594.png">

**Comment by scd** [comment]
Fixed on dev. @rouletout please organise the language translations for the `article.grades.example.description.512a-slash-b` key.

![screenshot from 2019-02-22 09-41-07](https://user-images.githubusercontent.com/373058/53206806-03df6380-3686-11e9-859b-49180f9950d8.png)

**Comment by scd** [comment]
FYI updated on sandpit

**Comment by rouletout** [comment]
doen / managed
