### ISSUE TITLE
Grades Article: Google Maps Error

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3371]
**What happened?**

The map in the grades article is not displayed anymore, gives a Google Error.

https://www.thecrag.com/de/artikel/grades

<img width="784" alt="screen shot 2019-02-20 at 16 49 28" src="https://user-images.githubusercontent.com/19162952/53175933-a5958080-35b2-11e9-9669-6c9225afef68.png">

Ideally also provide screenshots:

**What you expected:**

Correct display of the map

**Comment by brendanheywood** [comment]
Fixed, and hot fixed
