### ISSUE TITLE
Grade Article: Special Rating Stars - Text broken

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3372]
**What happened?**

In the grades articel (https://www.thecrag.com/de/artikel/grades/?lang=en), section Special rating systems the sentence misses something (see screenshot).

Ideally also provide screenshots:

**What you expected:**

Correct display of sentence
<img width="744" alt="screen shot 2019-02-21 at 08 40 07" src="https://user-images.githubusercontent.com/19162952/53176867-8ef02900-35b4-11e9-8ffa-0cfc4acda7c7.png">

**Comment by scd** [comment]
Fixed in dev

![screenshot from 2019-02-22 09-34-28](https://user-images.githubusercontent.com/373058/53206448-1907c280-3685-11e9-90da-0a44c0b6df60.png)

**Comment by scd** [comment]
@rouletout can you please check different language text. Note that this was markdown interpretation. I put backquotes around the stars in the text.

**Comment by rouletout** [comment]
This is fixed in all languages, close
