### ISSUE TITLE
Grades Article: Add Example on Alternate Grade with Aid

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3373]
**What happened?**

The grades article lacks an example of an alternate grade with aid modification. E.g. a route may be UIAA 8- free but 6+ A1 at the same time. This needs to be entered as shown in the screenshot.

This scenario is fairly common in alpine multi-pitch routes. Route example: https://www.thecrag.com/climbing/austria/route/2267369631

![screenshot from 2019-02-22 08-32-42](https://user-images.githubusercontent.com/19162952/53203843-d8119e80-35ef-11e9-8298-7b38795577c2.png)

Ideally also provide screenshots:

**What you expected:**

1) An example explaining alternate grades. 

2) Displaying this input as 8- / 6+ A1

**Comment by scd** [comment]
Added in dev

![screenshot from 2019-02-22 09-29-53](https://user-images.githubusercontent.com/373058/53206209-74858080-3684-11e9-9393-e957e736488e.png)

**Comment by rouletout** [comment]
**What you expected:**

    1. An example explaining alternate grades.

    2. Displaying this input as 8- / 6+ A1


Point 2 is not done

**Comment by scd** [comment]
Point 2 is very deep rabbit hole. I am closing this issue and reopening it as https://github.com/theCrag/website/issues/3375
