### ISSUE TITLE
CPR Embeds in article use extra "blue" space

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3374]
**What happened?**

Embeds do not display correctly in this article (extra blue space below each CPR graph):

Article: https://www.thecrag.com/de/artikel/cprtimeline
![img_4028](https://user-images.githubusercontent.com/19162952/53301531-93694b80-3819-11e9-9f18-4fbe3e0510a7.PNG)

Ideally also provide screenshots:

**What you expected:**

Normal display of the CPR embed, no blue space

**Comment by Mdemaillard** [comment]
not visible neither on desktop + chrome or Phone android + chrome. closing
