### ISSUE TITLE
FFA / FA - Tick Types, CPR and impact on ranking

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3376]
**What happened?**

We enter quite some data on FFA’s of famous routes / climbers. E.g. recently data was entered on FFAs for Adam Ondra (https://www.thecrag.com/climber/adamondra). Unfortunately these FFAs result in Tick Type “climbed” and have no impact on CPR and thus the ranking. 

The question is, is a FFA a real ascent? If so it would need to be more specific (how free?). If not, i suggest it should just be a historical field and not a tick (my preference). Whatever the approach, I want to avoid that we have to enter all that twice and create double ticks as this will be quite a lot of data to clean later.

<img width="801" alt="screen shot 2019-02-25 at 16 40 38" src="https://user-images.githubusercontent.com/19162952/53373827-330f0280-391c-11e9-9649-91c56b55ef87.png">

Ideally also provide screenshots:

**What you expected:**

My preference is to remove FFA / FA as tick types and use them as "text fields" with a separate listing on the profile. Ascents have to be tikced as ascents with the correct tick type to have an impact on CPR and ranking.

**Comment by brendanheywood** [comment]
I think the simplest quick change is a FFA tick type has the same CPR as a 'Red Point'.

**Comment by scd** [comment]
First Free Ascent tick type has the same CPR as Red Point. 

Is there anything to do here before we remove First Free Ascent as a tick type?

**Comment by lordyavin** [comment]
I have some doubts about removing FAs as tick type. How should we log historical FAs if it is not clear how (style) the first ascentionists climbed.

**Comment by scd** [comment]
I imagine there is still a lot of discussion to undertake before we remove FAs from ascent type, but it just represents our current thinking for the long term direction of ascents.

I am closing because there is nothing more to do here.

**Comment by rouletout** [comment]
If we don't know how it was climbed we can simply use the generic "Tick"
