### ISSUE TITLE
"Leave"ing a discussion does not work

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3378]
**What happened?**

Checked my dashborad and got a notification about a new [discussion](https://www.thecrag.com/discussion/2277660309/world--logging-ascents-with-vague-dates). I briefly read the comment previews and decided to not participate and clicked the "leave" button. The message preview disappears but the message notification does not. after reloading the page the message preview is back again.

**What you expected:**

* [ ] If I leave a discussion I don't get any notfication about it until I join it.
* [ ] item 2

**Comment by Drazhar** [comment]
+1
Same on my side

**Comment by scd** [comment]
This was a bug and has been hot fixed. Please try again now

**Comment by lordyavin** [comment]
Fixed for me but the notification icon does not dissappear instantly. I need to reload. But I think that bug was there before the leave button existed.

**Comment by scd** [comment]
FYI I have just fixed another bug with this. If you left a discussion then later read it when there were additional comments since you last read it, the system would reset your left status. As of next release this bug will be fixed.
