### ISSUE TITLE
Import logbook: Using NOT the grade of the assigned route does not work

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3379]
**What happened?**

Tried to import several routes where the ascent grade is different than the registered one but the ascent grade wasn't used by the import script (bulk assessment). 

After I unchecked the checkbox "use the grade of the assigned route" and relaoded the page the UI didn't show the ascents grade but two empty dropdowns to "select" the ascents grade.

Ideally also provide screenshots:
![screenshot_2019-02-25-16-27-08](https://user-images.githubusercontent.com/1528540/53551073-a0977a80-3b38-11e9-9837-b573d9a2dc77.jpg)
![screenshot_2019-02-25-16-25-54](https://user-images.githubusercontent.com/1528540/53551076-a0977a80-3b38-11e9-9d75-23681bbb3a36.jpg)

**What you expected:**

* [ ] Correct application of the users ascent grade instead of the registered grade.
* [ ] Using the users ascent grade shall be the default
* [ ] Don't show empty dropdowns, instead display the users ascent grade to apply

**Comment by lordyavin** [comment]
Any progress or plans here?

**Comment by lordyavin** [comment]
+1 from [forum](https://www.thecrag.com/discussion/2313321024/hi-andreas-willkomen-bei-thecrag-alles-nur-durschnitt-im-donautal#m2316760329)

**Comment by scd** [comment]
This should be done now. There was one line of configuration missing.

However I just realised I needed to correct configuration in two places. I have tested that doing this one ascent at a time works, but have not tested the bulk mode.

Please re-open if it does not work next time you run.

**Comment by lordyavin** [comment]
confirm fix
