### ISSUE TITLE
Grades Article: Hyperlink opens in same tab

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3380]
**What happened?**

Clicking on the hyperlink YDS Protection Rating which links to wikipedia:

https://en.wikipedia.org/wiki/Grade_%28climbing%29#YDS_protection_rating

 in https://www.thecrag.com/en/article/grades#special-rating-systems opens in the same tab instead of a new one.

**What you expected:**

Opens in new tab

**Comment by brendanheywood** [comment]
fixed
