### ISSUE TITLE
Profile Page: Name not shown on private profiles

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3382]
**What happened?**

E.g. profile https://www.thecrag.com/climber/emmaayling does not show the name but should.

<img width="492" alt="screen shot 2019-03-05 at 14 17 30" src="https://user-images.githubusercontent.com/19162952/53837055-455df180-3f57-11e9-9130-9eaf5206ea23.png">

Ideally also provide screenshots:

**What you expected:**

Show the full name

**Comment by lordyavin** [comment]
Why should the name shown for private profiles? I think it is absolutely correct to hide the "full name". Are you a friend (follower vice versa) of emma and expect to see the name?

In terms of privacy I would go one step further and display the user ID only and hide the custom avatar! For this case I suspect that the user name contains the full name already but she decided to have a private profile but it is still possible to identify her.

**Comment by rouletout** [comment]
The point is that right now the name is shown in search but not when you click on the profile. I don't care how we decide but it needs to be consistent.

**Comment by scd** [comment]
If somebody makes a forum comment or a route contribution should their name
be visible.

**Comment by lordyavin** [comment]
@scd I don't think so. You should respect the decision as much as you can. So just show the user id or "private user".

**Comment by scd** [comment]
Having people post in forums without names will be a big regression in my
opinion.

If somebody really cares about their name not been seen then they do not
have to provide it.

**Comment by rouletout** [comment]
shows now, closing
