### ISSUE TITLE
User icon incorrectly displayed in map view

### ISSUE THREAD

**Issue by dmucli** [theCrag/website#3384]
**What happened?**
User icon not properly cropped when using Maps.

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/world/maps

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/29764214/53840340-f7e09380-3fed-11e9-8189-4141b0571fd3.png)

**Comment by lordyavin** [comment]
Works for me, but at the moment I don't have unread messages.

**Comment by dmucli** [comment]
Looks like it's been fixed as the icon displays correctly now.
