### ISSUE TITLE
Clickable menu titles in left sidebar

### ISSUE THREAD

**Issue by dmucli** [theCrag/website#3385]
**What happened?**
At the moment, "YOUR PROFILE", "RECENT CRAGS" and "YOUR FAVORITES" are not clickable which is a bit confusing for navigation.

There is also a lack of consistency when looking at the YOUR PROFILE menu from the dashboard and from the user profile page: sub-items are different and one page has "your" in front of menu items while the other page doesn't.

In the dashboard https://www.thecrag.com/dashboard 
![image](https://user-images.githubusercontent.com/29764214/53840770-14310000-3fef-11e9-8c08-4d87ee0e0b13.png)

VS in user profile
![Uploading image.png…]()

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/29764214/53840542-8523e800-3fee-11e9-96f5-d11efeabe91f.png)

**Comment by rouletout** [comment]
The difference (your vs not your) is that you can look at someone else's profile and click it - this is not YOUR in that case, so it is more generic. The menus are all cliockable (for me at least) - i close this, @dmucli please comment / re-open if it doesn't work for you
