### ISSUE TITLE
Gym Ticks article embed has extra blue box

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3387]
**What happened?**

The CPR embed in the article https://www.thecrag.com/de/artikel/gymticking has an extra blue box.

<img width="760" alt="screen shot 2019-03-07 at 17 13 39" src="https://user-images.githubusercontent.com/19162952/53996128-f0f47680-40fc-11e9-9303-bd18c4d7f4da.png">

**What you expected:**

No blue box

**Comment by Mdemaillard** [comment]
Probable same route cause as #3374

**Comment by Mdemaillard** [comment]
not visible neither on desktop + chrome or Phone android + chrome. closing
