### ISSUE TITLE
404 link in settings menu

### ISSUE THREAD

**Issue by Luen** [theCrag/website#3391]
**What happened?**
Clicking on "View pending karma" gives a 404 error.

Example url(s) to reproduce the problem:
1. Go to your profile page and click "Edit your profile" which takes you to https://www.thecrag.com/settings/profile
2. Click "Donate" on left side nav bar which takes you to https://www.thecrag.com/donate
3. Click "View pending karma" on left side nav bar which takes you to https://www.thecrag.com/climber//karma

Ideally also provide screenshots:
![donate](https://user-images.githubusercontent.com/1161837/54254432-6cdc3c00-459f-11e9-9bca-f0d0c54d7e4e.JPG)

**What you expected:**
Takes you do your view pending karma page (https://www.thecrag.com/climber/%USERNAME%/karma)

**Comment by lordyavin** [comment]
I confirm the bug. Mentioned link is missing the username:
https://www.thecrag.com/climber/karma
vs.
https://www.thecrag.com/climber/captainhook/karma
