### ISSUE TITLE
Ascent pitch grades not displaying both aid and technical grades

### ISSUE THREAD

**Issue by scd** [theCrag/website#3392]
**What happened?**

Logging a multi-pitch ascent which has pitches in the ascent logged with both Aid and Technical grades does not show both in the grades displayed for each pitch.

Example url(s) to reproduce the problem:

https://www.thecrag.com/ascent/2298298134

Ideally also provide screenshots:

**Comment by scd** [comment]
See also https://github.com/theCrag/website/issues/3651

**Comment by rouletout** [comment]
Fixed with release 88
