### ISSUE TITLE
dup webcovers

### ISSUE THREAD

**Issue by scd** [theCrag/website#3394]
Why are there dup webcovers for Legoland here:

https://www.thecrag.com/climbing/australia/mt-maroon/area/12199855/webcovers

![Screenshot from 2019-03-17 11-35-52](https://user-images.githubusercontent.com/373058/54483539-d8c4ea00-48a8-11e9-9bcc-1811b121bb8e.png)

**Comment by brendanheywood** [comment]
Not a code bug. It’s two different photos and two different webcovers. Just delete one of them
