### ISSUE TITLE
Link to personal ascents in stats line for non-route nodes

### ISSUE THREAD

**Issue by dnnr** [theCrag/website#3398]
**What happened?**

Related to #3395, the mobile interface currently makes it rather hard to access "Your ascents" for a non-route node. The easiest way I found is going to the Logbook (main menu entry), adding yourself to the "Been climbed by" filter and repeating the search.

The obvious reason for that is that the mobile interface does not (yet?) provide dropdowns in the main menu. However, I'd like to propose an alternative UI for this, which might be even better than restoring the dropdowns on mobile.

When viewing a single route, there is already a direct link provided next to the total ascent count (_x by you_):
<img width="324" alt="Screen Shot 2019-03-21 at 17 47 02" src="https://user-images.githubusercontent.com/2630359/54760667-93cee980-4c01-11e9-946e-16c4f42f6fda.png">

For non-route nodes, a similar element is shown, except that it does not include the personal ascent counter:
<img width="320" alt="Screen Shot 2019-03-21 at 17 49 44" src="https://user-images.githubusercontent.com/2630359/54760754-bf51d400-4c01-11e9-859a-0ea9c3b068f7.png">

I think adding the _x by you_ link here is an improvement all around: It mitigates the pain of the missing dropdowns on mobile (this is literally the only thing I'm personally missing about the dropdowns), and it makes the UI more consistent across views that are already pretty similar.

That said, I'm guessing that counting ascents for all sub-nodes is more expensive than just for a single route, and that caching count per user and node might be necessary. I'm hoping you'll consider it worth it anyway.

**Comment by quaestor** [comment]
This might actually be easy to implement, because it's already there in a way. When you visit a node and then switch to the "climbers" tab, if you happen to be in the toplist, there's a "crag ascents" link for you. So I assume all it would take is to use the same logic for the node index page?

**Comment by brendanheywood** [comment]
If it is just a link this is trivial. If it is a link including *your* ascent count for this area then slightly more work but similar to the route page

**Comment by scd** [comment]
I have hotfixed this.

**Comment by quaestor** [comment]
@scd: Thanks for taking care of this. It works for most nodes now, but some nodes don't show the "your ascents" count at all, e.g. almost all nodes below https://www.thecrag.com/en/climbing/germany/frankenjura/gossweinstein. 

It's also sometimes inconsistent, like for the following two (sibling) nodes:

* https://www.thecrag.com/en/climbing/germany/frankenjura/nankendorf/area/458698062 doesn't show the count (which should be 0 for me) at all
* https://www.thecrag.com/en/climbing/germany/frankenjura/nankendorf/area/1294658622 shows "0 by you"

Could it have to do with caching?

**Comment by dnnr** [comment]
For what it's worth, the first link by @quaestor shows the correct count for me, but the other two don't show any link for me, not even "0 by you". So it seems to be inconsistent across users as well. Feels like a caching issue indeed.

**Comment by nicHoch** [comment]
@scd the reported issues by @quaestor does not solve over time and also for me in some areas i do net get the "" link.
for example:  user (190453269)  in node: https://www.thecrag.com/en/climbing/switzerland/alpen/zentralschweiz/area/219577512
in the ancestor nodes it works but also in some sibling nodes not.

**Comment by scd** [comment]
This has been done. It sounds like there could be a bug, but I would rather deal with that as a separate issue because it is lost in the noise. Closing
