### ISSUE TITLE
Timeline view of ascents of a crag(s) and cliffs

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3399]
**What happened?**

This is very similar to the timeline of first ascents:

https://github.com/theCrag/website/issues/2025

But the key difference is that instead of a breakdown via first ascents by people, it would be a breakdown of all ascents and by sub area. ie the use case is look at a crag and see which cliffs were not only developed when, but also how popular they have been over time and which are receding or increasing. I think the absolute numbers would be taken with a grain of salt especially going back in time before thecrag was popular in that location, but at least the relative ascents between cliffs should be useful.

One further complexity is that we probably need a way to selectively drill down, eg if you started at Arapiles would seeing the top 21 groupings of cliffs be enough? I imagine you'd want to be able to expand on any area and load on demand it's children's timelines too. I don't see any reason why you wouldn't be able to drill down all the way to the routes.

**Comment by brendanheywood** [comment]
Also I think the option to weight things by height https://github.com/theCrag/website/issues/1207 would be very relevant here when comparing a crag which contains both climbing bouldering

**Comment by leo-stan** [comment]
Hey Brendan, thanks for adding that on your todo, I think being able to drill down to any level would be useful indeed, similarly to the logs at the bottom of each page, if I'm on the Glass House Mtns page I will see what people logged in the whole area, but if I chose a specific route I will only see the logs for that route. 
Now that I think about it, the 'seasonality' feature is pretty similar to what I imagined, but then being able to see ascents over a bunch of years as opposed to an average of each month and on a monthly or yearly scale.

**Comment by rouletout** [comment]
This will be available for supporters upon next release. Closing.
