### ISSUE TITLE
Gym routes cannot be reparented

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3402]
**What happened?**

No possibility to reparent a gym's route. This is necessary when the layout of a gym is reorganised on thecrag. In my case, I talk about a boulder problem (a fixed one using only the wall's structure), which is registered under the wrong node.

**What you expected:**

To have such a button in the context menu of the route (or somewhere else).

**Comment by lordyavin** [comment]
Did that a lot in the past. Is this an regression? Please provide the url to the sample node.

**Comment by birgander2** [comment]
Maybe I'm blind. The route "Rondell", currently found here:
https://www.thecrag.com/climbing/germany/oberbayern/area/1754464659

Should be here:
https://www.thecrag.com/climbing/germany/oberbayern/area/2354263890

Since it has an ascent, reparenting would be better than archiving an adding it again...

**Comment by nicHoch** [comment]
yes the option in missing in the context menu.
However as a temporary solution you can use the route the detour of reparenting the sector.
But then use the "Reparent children of selected node" option ...

**Comment by birgander2** [comment]
Ah cool, that worked. Probably this way is sufficient, shouldn't happen so often.

**Comment by scd** [comment]
I have also come across this a few times while managing a gym. It is pretty irritating so I have added this to the route menu. This will be ready next release.

![Screenshot from 2019-04-08 14-03-06](https://user-images.githubusercontent.com/373058/55697983-30b5c300-5a07-11e9-89c5-892a5b34abc4.png)
