### ISSUE TITLE
Google Plus Button still on Photo Page

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3405]
**What happened?**

E.g. here https://www.thecrag.com/photo/2361377430 you still see a Google+ button.

<img width="1097" alt="Screen Shot 2019-04-08 at 12 38 36" src="https://user-images.githubusercontent.com/19162952/55744797-62289180-59fb-11e9-89c4-4529f4342bbd.png">

Ideally also provide screenshots:

**What you expected:**

Shouldn't be there anymore ;-)

**Comment by scd** [comment]
I removed this from the share template. Please check after release today.
