### ISSUE TITLE
Translate UI: "Not Required" vs. "No need to be translated"

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3407]
**What happened?**

I translated various new keys via https://www.thecrag.com/translate and disabled the rendering of 
`article.worldranking.links.markdown` by mistake. I think at first I clicked "not required" as the english text contains nothing that needs to be translated. This inserted the text "--null--" and I tried to redo this by deleteing the text and storing it. Of course this deletes the links list for German. To revover I just copied and pasted the english text.

**What you expected:**

* [ ] Tooltips (or links) explaining the UI items
* [ ] A button that let me reset a key for a specific language.

**Comment by rouletout** [comment]
The Not Required button was renamed as this was a constant source of mistakes. We'll work with that and observe if this needs further improvement. The translation help (offline) is also updated. Closing for now.
