### ISSUE TITLE
New Account page does not save input in data fields

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3409]
**What happened?**

When creating a new community profil (using Firefox Private Mode) the entries for DOB, Gender and bio are not saved.

Ideally also provide screenshots:

**What you expected:**

Items to be saved.

**Comment by rouletout** [comment]
Just tried one without Firefox Private mode and everything was fine - I'll continue to find a pattern here...

**Comment by rouletout** [comment]
Actually it does not even save it fom the Admin page - you can't set gender and DOB!

**Comment by scd** [comment]
What I noted on dev was that I could save as admin page, but it did update and show on the profile page, but when going back to the admin page it seemed to be there. Can you confirm it is not updated on the admin page when you go back to it. 

If this is the case then this is most likely a cache issue. If not then there is probably another issue at play as well.

**Comment by rouletout** [comment]
Yes you are right - I now understand what you mean by old admin page - this one works. So no urgency but I guess this is also confusing for new users signing up.

**Comment by scd** [comment]
@rouletout I am pretty sure this was done in prep for the release and we forgot to close this issue here. Can you confirm and close.
