### ISSUE TITLE
Repeated ticking should take previous custom (ascent) grade as default

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3410]
**What happened?**

I logged/ticked a [route](https://www.thecrag.com/ascent/2384576373) the second time where I previously downgraded the ascents grade. The tick/log ascent UI does use the previous star rating as default but not the previous ascent grade.

**What you expected:**

* [ ] Select the previous custom ascent grade as default.
* [ ] If the user changes its opinion about the grade it would be nice to prompt the user if he/she wants to reflect that change to previous ascents of the route. This would assist the user to log consistent ascent grades for repeated routes.

**Comment by scd** [comment]
Upon reflection I don't think we want to do this. 

We want to encourage users to only log a grade override if absolutely necessary. 

If we are collecting climbers opinions on the grade then I do not think ascent grade override is the way to go. It would be better for the route grade to be changed by community consensus and the climber accept that route grade.

I suggest we either close this issue as not doing or monitor to see what the use cases are.

**Comment by lordyavin** [comment]
> We want to encourage users to only log a grade override if absolutely necessary.

So you question the feature to override the registered grade in principle? If this wouldn't be possible anymore, this issue would become obsolete. But as long as this feature exists and a user uses it, the default behavior of the system counter strikes the user's opinion/wish/expectation.

So, is there a plan how to combine grade contribution and ascent grade overriding in the future? This is a very old question and I'm not aware of a good answer.

**Comment by lordyavin** [comment]
BTW this issue is mainly about convience. To make thecrag attractive, logging ascents should be as easy and comfortable as possible. This also includes that one does not have to specify the personal assessment of a route again and again.

**Comment by scd** [comment]
Grade override is not meant to be a personal assessment of the route. It would definitely be turned off if that was the only use case. Using it in that way is not encouraged at all as it will stop other features working properly (eg CPR).

Please note that we plan to re-introduce the grade opinion feedback sometime. We use to have a field that let the climber say that they thought it was harder or easier than the grade. This is planned to come back.

The only reason why we are keeping grade override is because of other valid use cases, for example 

 * Only did the first pitch
 * Aid climbed a non aid route.

All of these valid use cases we definitely do not want to auto populate the field with your last ascent.

**Comment by lordyavin** [comment]
Thanks, now I understand. BTW when will the mentioned work flow released?

**Comment by scd** [comment]
Planing as soon as I can. I am stuck on another job, but may get to it
tonight

**Comment by killakalle** [comment]
@lordyavin @scd 

It's already available from the route list, isn't it?
See #3997

**Comment by lordyavin** [comment]
@killakalle my supporter status is not set, so I can't use the new feature. @scd I will test the new feature after @rouletout resets my supporter status. If the new tick flow makes this issue obsolete I will close it with a corresponding comment.

**Comment by lordyavin** [comment]
Looks like the feedback to the new tick flow gives some momentum to implement this issue.

https://www.thecrag.com/discussion/5565450684/release-95---new-tick-flow

**Comment by scd** [comment]
In the new tick flow we are remembering ascent difficulty feedback.
