### ISSUE TITLE
Display notable ascents of a route in its description

### ISSUE THREAD

**Issue by dmucli** [theCrag/website#3411]
Some routes have an historical importance and any ascent usually makes headlines. Well known examples are Action Directe, Biographie, The Nose etc.

I've noticed people attempting to log these ascents (eg. Biographie) as in the screenshot attached. It could be useful to have a feature to add this ascents in a separate specific field to keep things neat and clean.

https://www.thecrag.com/climbing/france/ceuse/route/15807193

Screenshot below of how it looks today
![image](https://user-images.githubusercontent.com/29764214/56011442-f744c680-5d2a-11e9-9739-8472075b67d3.png)

**Comment by rouletout** [comment]
+1 from rouletout

**Comment by brendanheywood** [comment]
dup https://github.com/theCrag/website/issues/3556

**Comment by rouletout** [comment]
This will be covered by the re-work of the route page

**Comment by rouletout** [comment]
We have the "Notable ascent" history entry now, closing this
