### ISSUE TITLE
Feature request: curated list of areas and/or routes

### ISSUE THREAD

**Issue by dmucli** [theCrag/website#3417]
A feature that lets (some?) users create lists of areas or routes featured at the world level, continent level or country level.

**Just a few examples**

At the world level 
World: *Most scenic crags in the world (Yosemite Valley, Wadi Rum, Getu, Verdon Gorges...)*
World: *Hardest multi-pitches routes (Dawn Wall, Silbergeier, Orbayu, Tough Enough etc.)*

At the continent level
North America: *Best sport climbing crags* (Red River Gorge, The Gunks, Red Rocks etc)*
Europe: *Climbing above the sea (Mallorca, Les Calanques, Kalymnos, Sardinia...)*
Europe: *Best bouldering areas (Fontainebleau, Magic Wood, Albarracin...)*
Asia: *Best DWS destinations (Halong Bay, Tonsai, El Nido)*

At the country level
Spain: *Best 8a sport routes* or *top 20 best sport routes under 8a*
France: *Routes at high altitudes*

The list goes on! 

This could be a cool feature to help climbers discover areas/routes in places they want to travel to. It could also be a more valuable way of presenting classic routes in a country instead of the "nearby icons" feature which is limited to one route per grade. 

Extending on the ideas of lists, there could also be lists not related to any area and that can be created by any users (privately or publicly) such as "my favourite routes of all time", "routes I want to climb before I die" etc. But this is another topic.

**Comment by lordyavin** [comment]
This is an already existing feature that isn't promoted aby more and is called circuits.

**Comment by dmucli** [comment]
Aren't circuits a specific term for bouldering (most commonly in Font)? What is suggested in the idea above is that lists would appear on region pages (maybe replacing or adding to the nearby icons feature). Also can the circuit feature be a list of crags instead of routes/boulders?

As of today, if someone wants to find routes recommendations they would likely click on "explore country" and check "nearby icons"

This is what you get for France (not very useful)
<img width="298" alt="Screen Shot 2019-04-27 at 08 16 06" src="https://user-images.githubusercontent.com/29764214/56839244-f2ece180-68c4-11e9-8030-7e6fffc7b8ce.png">

or for Spain (not much use either)
<img width="298" alt="Screen Shot 2019-04-27 at 08 16 06" src="https://user-images.githubusercontent.com/29764214/56839335-56770f00-68c5-11e9-8b2b-94742339ee1c.png">

**Comment by lordyavin** [comment]
I don't know if the initial circuit feature was introduced to implement font parcours. I never backed the idea of dropping that feature in favour of hash tags. So I'm happy that you raised this issue.

**Comment by scd** [comment]
Circuits / lists are not dropped. We just have not been able to get a clear priority to support them properly. Hash tags were an interim idea.

This feature will be back and supported properly at some point. Maybe a couple more releases.

**Comment by brendanheywood** [comment]
@dmucli I've moved your comment over to this one:

https://github.com/theCrag/website/issues/1318

I'll close this one as a duplicate
