### ISSUE TITLE
Crag comments

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#3419]
Hey,

I couldn't find a similar issue, so I create a new one. Sorry if I missed something :)

It would be cool to be able to "tick" a crag/area. By tick I mean be able to tell that I visited that crag, give a comment and a rating. This would help to visit cool crags again on the next vacation or help friends find crags.

Most people I know also write comments in their guide books, this feature would represent this behavior.

Of cause one could argue that you also mark a visit by ticking routes and rate the area by the quality of the routes, but giving a comment to a area specifically is something different IMHO.

**Comment by Drazhar** [comment]
Also by "ticking" you could mark crags you want to visit and comment for what reason

**Comment by brendanheywood** [comment]
Closing this as a duplicate, see: https://github.com/theCrag/website/issues/2228 please have a read of that and comment there
