### ISSUE TITLE
Remove ability to tick when in a closed area

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3421]
**What happened?**

We've done a bunch of tweaks to expose the 'Closed' tag in more place. To reinforce that a crag is close, we should disable ticking

**What you expected:**

* [ ] if the node you are in is closed, the tick process in the list view is disabled
* [ ] if the node you are in is closed, the tick process in the context menu is disabled
* [ ] at a route page the tick button is disabled

**Comment by DaneEvans** [comment]
What about historical ticks? 

I understand the desire here, but equally can think of scenarios where it would still be good to have some options. 

Not sure how you would go about implementing such a thing though

**Comment by lordyavin** [comment]
I see one problem with this issue. If someone joins thecrag after the crag is closed and wants to log ascent prior to the closure it will not be possible to log it.

**Comment by brendanheywood** [comment]
Yes and there is also the gray areas of crags which are closed, but were an individual has permission. eg guides in SPA's or friend of the landowner.

I did consider something basic, like disable it from the cliff page but allow it from the route page or whatever, just to add some slight barrier and force people to consider. 90% of the problem here is just making the closed tag more in your face, which we are also doing.

**Comment by lordyavin** [comment]
May be we can solve my point by introducing a date range. In Germany we have a lot of scheduled closures due to nature conservation. It would neat to just enter the official dates once and the closed tag is set and removed automatically.

So if someone wants to log an ascent from the past it has to be outside of the date range of the closure.

**Comment by brendanheywood** [comment]
No this is something we want to do fairly quickly. This is cosmetic and won't introduce any data model changes.

**Comment by nicHoch** [comment]
what about not to disable/hide the ticking option at all - but while logging an ascent (press log botton ) in a closed area to show some kind of "pop up" with an message "please respect ....for many reasons ... " with two botons "leave" and "ok i know but will log anyway".

**Comment by scd** [comment]
I am going with a fairly simple solution of displaying a warning when you log an ascent in a closed area.

![Screenshot from 2019-05-21 15-00-23](https://user-images.githubusercontent.com/373058/58069626-3d6a3100-7bd9-11e9-8e7d-b3dc459274ef.png)

The text reads:

**🚫 Climbing in this area is closed.** Logging ascents may be public, please consider implications or local sensitivities before you log these ascents. 

I am happy to use stronger or different wording, but for the next release this should just be a warning. If we still need to have an OK button which forces an extra button click before logging an ascent then this can be done later.

**Comment by brendanheywood** [comment]
Just made a small tweak to make this consistent with closed warnings elsewhere

![image](https://user-images.githubusercontent.com/187449/58320338-c5ad3800-7e5e-11e9-8ee3-cf2870777a25.png)
