### ISSUE TITLE
Date range for scheduled crag closures

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3422]
New feature to set a date range for (scheduled) crag closures. In Germany we have a lot of scheduled closures due to nature conservation. It would be neat to just enter the official dates once and the closed tag is set and removed automatically.

So if someone wants to log an ascent from the past it has to be outside of the date range of the closure.

_Originally posted by @lordyavin in https://github.com/theCrag/website/issues/3421#issuecomment-489630997_

**Comment by Mdemaillard** [comment]
duplicate
