### ISSUE TITLE
Topos in different nodes not linking correctly

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3423]
**What happened?**

As a test, I generated a feature called "Topos" in [one sector of Fontainebleau](https://www.thecrag.com/climbing/france/fontainebleau/area/14018539), in order to put some topos there (currently only 2), containing problems from several of the subareas of this sector. However, when clicking on the [actual route](https://www.thecrag.com/climbing/france/fontainebleau/route/515162487), the topo is not shown. When the topo is instead placed in the main node, the topo [shows up correcty](https://www.thecrag.com/climbing/france/fontainebleau/route/1090379124).

**What you expected:**

That the topo is shown in the route description, independently from where it is placed.

**Comment:**
I know that a node "Topos" is not the intended place for topos. But Fontainebleau is complicated. The idea behind was to avoid loading potentially hundreds of topos placed in the main node when just entering a sector. Placing them in the circuits / off-circuits nodes is not necessarily a good idea neither, it clutters the listing and most topos need to uploaded to multiple places.

**Comment by brendanheywood** [comment]
This has been touched on in the other issue #2639 for font circuits and it is already ruled this out as a solution. Topo's belong to a node eg A, and only appear when you are either at node A, or at a node which is both linked in the topo and is also a descendant of node A. If we also show the topo's for the non descendant nodes then you end up with weird topos were you really don't expect (in most normal cases). Either way I don't really like the topo belonging in a different artificial node, it's a hack. When we spent time on this it would be much better invested in a proper circuit data model which we can build on top of the 'wish list' data model (which is / was originally called circuits).

**Comment by birgander2** [comment]
Answer at [#2639](https://github.com/theCrag/website/issues/2639)
