### ISSUE TITLE
Markdown: tagging a climber and bullet points bug

### ISSUE THREAD

**Issue by dmucli** [theCrag/website#3424]
When putting a climber's tag after a bullet point, the tag does not work (eg. it remains as @adamondra instead of Adam Ondra):

https://www.thecrag.com/climbing/spain/malaga-sevilla-area/route/1088393466
![image](https://user-images.githubusercontent.com/29764214/57498811-b4254580-7320-11e9-97d0-e2a3d462c10f.png)

However it does show in the feed as expected
https://www.thecrag.com/event/2478535668
![image](https://user-images.githubusercontent.com/29764214/57498862-e59e1100-7320-11e9-8636-431a1be0f5b1.png)

**Comment by lordyavin** [comment]
+1

**Comment by scd** [comment]
I have fixed this in dev. Will be ready next release.

![Uploading Screenshot from 2019-05-21 17-58-24.png…]()
