### ISSUE TITLE
Font bouldering grades not detected properly in grade bar chart

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3426]
**What happened?**
![image](https://user-images.githubusercontent.com/187449/57593848-a7069180-7580-11e9-9f82-e37e1a09f9f6.png)

https://www.thecrag.com/climbing/france/fontainebleau/areas

All font areas which are of course bouldering, detect 'V grades' as the best system to show grades in rather than font boulder grades. 

**What you expected:**

* [ ] font grades in the grade bar chart

**Comment by brendanheywood** [comment]
This looks more widespread that just font, castle hill is not V grades either, ewbank instead:

https://www.thecrag.com/climbing/new-zealand/castle-hill-basin

![image](https://user-images.githubusercontent.com/187449/59157893-4a9e7f80-8af6-11e9-9e44-9354f44676c9.png)

**Comment by Mdemaillard** [comment]
Fontainebleau (100% bouldering) is sorted and display Font.

castle-hill (87% bouldering) is not, still displaying ewbanks. The children are at first sight randomly either V-grade or Ewbanks

interestingly, it seems the denominator for the Ewbanks chart is having in its descendant some weirdly graded routes like this one:
https://www.thecrag.com/climbing/new-zealand/castle-hill-basin/area/675720393
https://www.thecrag.com/climbing/new-zealand/castle-hill-basin/route/13736629
(a grade is displayed, but not visible while editing the route???)
![image](https://user-images.githubusercontent.com/60388146/77004647-1bac1880-6968-11ea-9229-da97d6d3f9b8.png)
![image](https://user-images.githubusercontent.com/60388146/77004675-29fa3480-6968-11ea-895e-fd20233b463f.png)

- an area with only sport routes BUT some child nodes with huge amount of bouldering will display V-scale
https://www.thecrag.com/climbing/new-zealand/castle-hill-basin/area/11871445

- each node containing only usually graded boulders or routes will display V-scale

- here and there one can find the odd 
https://www.thecrag.com/climbing/new-zealand/castle-hill-basin/route/412011624
![image](https://user-images.githubusercontent.com/60388146/77005396-67ab8d00-6969-11ea-8abc-ede09f2deba5.png)

--> it seems the unrecognized grading is the route cause

**Comment by rouletout** [comment]
This is all showing FB now, closing
