### ISSUE TITLE
Changing Alternate Route Name leads to Error

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3427]
**What happened?**

This route https://www.thecrag.com/climbing/mexico/jilotepec/megasesino-y-capilla/route/163468155 has an AKA of "el mega" that I tried to change to El Mega. This results in the following error:

<img width="1146" alt="Screenshot 2019-05-13 at 19 36 34" src="https://user-images.githubusercontent.com/19162952/57662797-c5877f80-75b6-11e9-9842-0e5eb1fc5d10.png">

Ideally also provide screenshots:

**What you expected:**

Changing name works.

**Comment by brendanheywood** [comment]
dup of https://github.com/theCrag/website/issues/3262
