### ISSUE TITLE
New "closed" icons not showing up for local SF crag

### ISSUE THREAD

**Issue by pmonks** [theCrag/website#3428]
**What happened?**
According to [this discussion](https://www.thecrag.com/discussion/2490574413/inconsistentcies#m2490928620), a nice little "closed" icon is supposed to be appear beside the name of closed crags.

However this is not occurring for the closed ["Dead Cat Rocks" sector](https://www.thecrag.com/climbing/united-states/glen-canyon/area/379269924) in [Glen Canyon in SF](https://www.thecrag.com/climbing/united-states/glen-canyon), in either the left nav:

<img width="226" alt="Screen Shot 2019-05-14 at 12 47 28 pm" src="https://user-images.githubusercontent.com/54865/57727738-18a91300-7647-11e9-8b2b-f98d7a40612f.png">

Or the sub-area list in the body of the page:

<img width="707" alt="Screen Shot 2019-05-14 at 12 47 55 pm" src="https://user-images.githubusercontent.com/54865/57727739-18a91300-7647-11e9-8140-14da4b584af5.png">

**Comment by brendanheywood** [comment]
@pmonks we are working on this and it will be in the next release in a week

**Comment by brendanheywood** [comment]
Also added this to the maps now:

![image](https://user-images.githubusercontent.com/187449/58324822-4b36e500-7e6b-11e9-86b3-e9fe492a6baa.png)

Closing this now, note the release got pushed back 2 weeks to the 3rd

**Comment by nicHoch** [comment]
this is great

**Comment by pmonks** [comment]
Wow that's great!  Nice work @brendanheywood!
