### ISSUE TITLE
Ascent facet is showing route length not ascent length

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3434]
**What happened?**

https://www.thecrag.com/climbing/australia/arapiles/area/11764783/ascents/between/2019-05-10+2019-05-10/by/adam_demmert/?sortby=when-climbed,desc

![image](https://user-images.githubusercontent.com/187449/57778683-ec38e800-7767-11e9-82cd-4ffe104adf74.png)

It is correct in the ascent detail page

https://www.thecrag.com/ascent/2492872554

**What you expected:**

* [ ] 30m instead of 120m

https://www.thecrag.com/discussion/2483609436/does-this-really-need-to-exist-as-a-separate-route#m2492877189

**Comment by scd** [comment]
This has been fixed on simon's dev. It was a simple matter of hooking up the ascent height variable properly in the ascents facet.

Available next release
