### ISSUE TITLE
A logged ascent should not be a "vote" for the grade by default

### ISSUE THREAD

**Issue by tanerkay** [theCrag/website#3436]
Correct me if I'm wrong, but I feel like every time you log a climb, the grade selected becomes attached to the ascent, and is collected to make an average grade for the "community registered grade"

I've noticed sometimes when I've been too lazy to "correct" the grade, that I've been one of the ones inadvertently voting for the new grade.

Background and biased/opinionated thinking: I think that people are too eager to call something "sandbagged". I particularly like the idea of weighting people's opinions or giving them a "grade budget" as described in other issues, as there are many more people who are all too ready to suggest a climb is under-graded. If you think a lot of climbs are "sandbagged", maybe you ought to adjust your idea of what each grade means. The problem I'm describing here also results in a feedback loop, if people tick these "upgraded" climbs, they might wrongfully think they have started consolidating at a grade, and cry foul when they can't do other climbs at a similar grade.

Examples:

- Quo Vadis at Arapiles, 19 in the guidebook, 20 on thecrag
- Hotel California at Blue Mountains, 21 originally (if I'm not mistaken), once even pushed up to 24 on thecrag, now at 22
- Judgement Day at Arapiles, 19 in the guidebook, 20 on thecrag
- Weaselburger at Blue Mountains, 23 in the guidebook (and a soft touch at that if you ask me!), 24 on thecrag

I'm also noticing a lot of climbs where the pitch description has pitch by pitch grades, and none of them match the grade that "thecrag" gives it

Examples:

- Tricycle at Blue Mountains, 23, but the crux pitch is a 22?
- Randy Rabbit Ridge, 20, but the crux pitch is a 19?
- Wind Cries Mary, 20, but the crux pitch is a 19?
- You Can't Stop the Music, 20, but the crux pitch is a 19?

Proposed solutions:

a) When you log an ascent, the default selection for the "grade" dropdown could still be the currently listed grade, but does not count as a "vote", maybe the displayed value can be blank? If, and only if, the user then explicitly selects the same grade, or a different grade, then it counts as a vote?

b) A separate field for "opinion" as suggested in issue #689

Related issues:

- https://github.com/theCrag/website/issues/2640
- https://github.com/theCrag/website/issues/689

**Comment by brendanheywood** [comment]
Yep totally agree and this is a stepping stone towards the other issues.

I think the ascent grade should just be an 'inherit' option by default, and if the route grade changes later than this also flows through to the ascent grade and recalculate the cpr for the ascent.

**Comment by brendanheywood** [comment]
Also just to correct you slightly, even though yes we do copy the current route grade into the ascent grade, the ascent grades don't inform the community grade at all. Only the other way around. At the moment you can 'vote' for a grade by adding a grade citation but it is a little awkward and isn't used much. But even then this is only shown and doesn't directly influence the community grade which is simply edited by anyone when you edit the route.

**Comment by rouletout** [comment]
Solved with the new grade feedback in the new ticking interface, closing
