### ISSUE TITLE
Interpret grades as UIAA instead of NCCS in FR context

### ISSUE THREAD

**Issue by jalonavens** [theCrag/website#3437]
If a Roman numeral UIAA grade is entered when adding or editing a route's grade in the FR context it is interpreted as a NCCS grade but it should be interpreted as a UIAA grade.

To correct this issue:
- Check whether any routes in FR context use NCCS grades. If there are then the grade is likely to be a mistake, and if so correct the grade, otherwise if actually correct, update the grade to be a forced NCCS grade by adding a "NCCS:" prefix.
- Remove NCCS grade interpretation from the FR grade context.
- Add UIIA grade interpretation to the FR context, but after the FR grade system in priority so that Roman numerals (e.g. "4") are still considered FR grades.

Background:
- Guidebooks covering mountain routes in FR context countries (particularly in the Alps of Italy & Spain) often specify UIAA grades for classic trad routes using Roman numerals. In general UIAA grades can be in Roman or Arabic numerals but in Italy & Spain UIAA grades are normally specified using Roman numerals. The usage of UIAA grades for classic trad routes in Italy is mentioned [here](https://www.guidedolomiti.com/en/rock-climbing-grades/).
- The NCCS system is a alpine commitment grade primarily used in the USA and rarely if ever used in FR contexts. NCCS grades are explained on the [alpinist](http://www.alpinist.com/p/climbing_notes/grades) and [summitpost](https://www.summitpost.org/handy-alpine-grade-facts/173430).

Examples of UIAA grades used on classic trad route in Italy and Spain:
- Italy: A 12 pitch trad route Abram on Piz Ciavazes in the Dolomites (first ascended 1953 so a classic) with a UIAA grade of VII / V+ A0. Most websites only give the UIAA grade in Roman numerals - e.g. [sassbloss](http://www.sassbaloss.com/pagine/uscite/sella28/sella28.htm), [omvertical](http://www.ormeverticali.it/relazioni/piz-ciavazes-spigolo-abram/), [ramellasergio](http://www.ormeverticali.it/relazioni/piz-ciavazes-spigolo-abram/), but one also gives IFAS, e.g. [quartograd](http://quartogrado.com/volume1_2/relazioni/PIZ%20CIAVAZES_Abram_A.htm) and it also uses Arabic numerals but this is the only example I've found to date. Most trad routes in the Dolomites have UIAA grades as far as I know - e.g. the [Marmolada](https://www.ukclimbing.com/logbook/crag.php?id=2645).
- Spain: A 9 pitch trad route called Cepeda on the east face of Naranjo de Bulnes in Picos de Europa in northern Spain (first ascended 1955 so a classic) with a UIAA grade of V+. This [blog](http://deaquinopasamos.blogspot.com/2011/10/via-cepeda-350m-v-6aa0-picu-urriellu.html) has 8 topos at the bottom and every topo uses UIAA grades (in Roman numerals), although the blog title gives the grades in Spanish IFAS (MD- = TD-), French (6a) and UIAA (V+/A0 oblig). Other routes on the Naranjo de Bulnes are listed at the bottom of this [route](http://www.todovertical.com/resena/7/cara-o-via-rabada-navarro) - some with French, some with UIAA and some with both grades again!

Screenshots:
- Screenshot showing incorrect interpretation of a Roman numeral ("IV") UIAA grade for a trad route as an NCCS grade:
![image](https://user-images.githubusercontent.com/13288347/57963689-5d94b880-796b-11e9-899e-cf1a215fe2db.png)

**Comment by rouletout** [comment]
From what I see this is resolved and Roman entries are converted to UIAA
