### ISSUE TITLE
Interpret FR grades for sport routes & FB grades for boulders in UK context

### ISSUE THREAD

**Issue by jalonavens** [theCrag/website#3438]
There are 2 issues in the UK grade context when adding or editing a route's grade:
1. If an FR grade (e.g. "6a") is used for a sport route it is interpreted as a UKT grade when it should be interpreted as a FR grade.
1. If an FB grade (e.g. "6A") is used for a boulder route it is interpreted as a UKT grade when it should be interpreted as a FB grade.

To correct these issues:
1. Check whether any sport or boulder routes use UKT grades. If there are then the grade is likely to be a mistake, and if so correct the grade, otherwise if actually correct, update the grade to be a forced UKT grade by adding a "UKT:" prefix.
1. Remove UKT grade interpretation for sport & boulder routes in the UK context.
1. Add FR grade interpretation for sport routes in the UK context.
1. Remove FR context and system overrides ("{FR}" and "FR:") for any sport routes in the UK context.
1. Add FB grade interpretation  for boulder routes in the UK context (BLDV grades are already interpreted in the UK context for boulder routes).
1. Remove FB context and system overrides ("{FB}" and "FB:") for any boulder routes in the UK context.

Background on grades used in the UK:
- Sport routes: Only FR grades are used for sport routes.
- Boulder routes: Both FB and BLDV grade systems are both commonly used. Historically UKT grades were used as well but this is no longer the case in modern guidebooks.
- Top rope routes: Both FR and UKT grades are commonly used. Most top rope routes are in the Southern Sandstone area of Kent where more recent guidebooks ([Rockfax 2017](https://www.rockfax.com/climbing-guides/books/southern-sandstone-climbs/)) give both a FR and UKT grade. Older guidebooks ([Climbers' Club 2008](https://www.ukclimbing.com/logbook/books/southern_sandstone-25)) just give a UKT grade alone.
- Trad routes: A British adjectival  grade (UK) will always be given, often followed by a British technical grade (UKT).  The adjectival grade is always given first . Easier trad routes up to and sometimes including adjectival grade "S" (severe) are often not given any UKT grade. E.g. "M", "D", "HD", "VD", "HVD", "S". For adjectival grades "S" and above a UKT grade is almost always given after the adjectival grade, e.g. "S 4a".

References:
- Summary of grading systems commonly used in the UK on [startclimbing.uk](https://startclimbing.uk/2018/07/19/route-grades/)
- A brief explanation of UK traditional climbing grades at the [BMC](https://www.thebmc.co.uk/a-brief-explanation-of-uk-traditional-climbing-grades)
- UKClimbing's [explanation of British trad grades](https://www.ukclimbing.com/logbook/grades.html) and Rockfax's (UKClimbing owned guidebook brand) [comprehensive explanation of grading system used in their guidebooks as well as grade conversion charts](https://www.rockfax.com/publications/grades/).
- Examples of grades used in the UK:
  - Sport routes: [Blacknor North at Portland in Dorset](https://www.ukclimbing.com/logbook/crag.php?id=260)
  - Trad & boulder routes: [Stanage Popular in Derbyshire](https://www.ukclimbing.com/logbook/crag.php?id=104)
  - Top rope routes: [Harrison's Rocks near Tunbridge Wells in Kent](https://www.ukclimbing.com/logbook/crag.php?id=57)

Screenshots:
- Screenshot showing incorrect interpretation of a FR grade for a sport route:
![image](https://user-images.githubusercontent.com/13288347/57964125-4fe33100-7973-11e9-81d6-cfb07d63425f.png)
- Screenshot showing incorrect interpretation of a FB grade for a boulder route:
![image](https://user-images.githubusercontent.com/13288347/57964130-5ffb1080-7973-11e9-9282-77fbc6f5c575.png)

**Comment by scd** [comment]
I have made a change to dev configuration that means this will be fixed next release. Just to confirm 4x use cases

If the user types in `6a` in a UK context we have the following different interpretations for different gear styles

* As Trad it is interpreted as British Technical grade

<img width="426" alt="Screen Shot 2020-11-10 at 3 13 48 pm" src="https://user-images.githubusercontent.com/373058/98627167-a9a99900-2367-11eb-8167-7211b926a655.png">

 * As Sport it is interpreted as French grade

<img width="429" alt="Screen Shot 2020-11-10 at 3 13 30 pm" src="https://user-images.githubusercontent.com/373058/98627208-bd54ff80-2367-11eb-831e-420ed0a8e1de.png">

 * As boulder it is interpreted as a Font grade

<img width="448" alt="Screen Shot 2020-11-10 at 3 13 17 pm" src="https://user-images.githubusercontent.com/373058/98627227-d362c000-2367-11eb-9683-a27bef4b2126.png">

 * As Deep Water Solo (or any other style not mentioned above) it is interpreted as French grade but with a conflicting context indicator.

<img width="450" alt="Screen Shot 2020-11-10 at 3 14 13 pm" src="https://user-images.githubusercontent.com/373058/98627286-01480480-2368-11eb-8d4e-ba04c3650405.png">

**Comment by jalonavens** [comment]
Thanks @scd - great work! Looks good to me.

**Comment by rouletout** [comment]
Done for release 88
