### ISSUE TITLE
Import logbook line: Missing some UKClimbing tick types

### ISSUE THREAD

**Issue by jalonavens** [theCrag/website#3441]
During the import of a UKClimbing logbooks some UkClimbing mappings were not mapped into theCrag tick types.

All UKClimbing tick types have subsequently been identified in this spreadsheet [ukclimbing.com tick types.xlsx](https://github.com/theCrag/website/files/3193960/ukclimbing.com.tick.types.xlsx)..

For each UKClimbing tick type identified the spreadsheet lists both
- the current theCrag tick type mapped during import (if present)
- a proposed theCrag tick type (sometimes different)

Please add the missing tick type mappings and also update any changed mappings.

**Comment by nicHoch** [comment]
available with next release
