### ISSUE TITLE
Import logbook line: Reduce clicks required to action lines and improve display of searched for routes

### ISSUE THREAD

**Issue by jalonavens** [theCrag/website#3442]
Useability issues with the "Import logbook line" page:

For each import line there are too many clicks required to import a line - it gets very boring after several hundred lines! 

- [x]   Reduce the required clicks per line by removing the "Save and continue" button and replacing the "What to do?" radio buttons with buttons that can directly clicked - i.e. "Assign to node", "Skip import line", "Defer decision",  etc should be action buttons.

Sometimes none of the candidate routes pre-matched to the line are correct and the user performs a route search to find the correct route. After then using the "Route Search" feature and selecting one of the routes from the search results:

- [x]  Currently the route is appended at the end of the last pre-matched candidate route rather appended on a new line which can make it hard to find and select it. See screenshot below.

- [x]   Additionally, to reduce clicks again, if a routes has already been selected from the search results then its radio button should be automatically pre-selected so it becomes the preferred candidate route should "Assign to node" be subsequently chosen.

Screenshot showing how a route selected from search results is appended at the end of the last pre-matched candidate route rather appended on a new line: 
![image](https://user-images.githubusercontent.com/13288347/57968670-c2becd00-79b0-11e9-9ae7-f37ffa5113f9.png)

**Comment by nicHoch** [comment]
available with next release
