### ISSUE TITLE
Add Scottish Winter grade system for Alpine & Ice routes in UK context

### ISSUE THREAD

**Issue by jalonavens** [theCrag/website#3444]
**Issue**
In the UK winter routes (snow, ice or mixed) which would be entered as Alpine or Ice routes on theCrag are usually (always possibly?) given Scottish Winter grades. This applies in England,  Scotland, Wales and it seems Ireland as well after a bit of research (see examples below). Currently theCrag does not recognise this grade system.

**Solution**
- Add Scottish Winter Grades grade system support. Let's abbreviate it as SCTW for the overall grade and SCTWT for the optional technical grade (see below).
- Remove NCCS & FR_ALT grade interpretation from UK context (at least for for Alpine and Ice routes).
- Add SCTW/SCTWT grade interpretation in the UK context for Alpine and Ice routes.

**Background on the Scottish Winter grade system**
- Like UK traditional grades there is an overall/adjectival grade (in Roman numerals), as well as an optional technical grade (in Arabic numerals) - e.g. "V 6". The Alpinish below uses a comma between the 2 grades but this is commonly omitted. For easier routes up to the overall grade "III" often no technical grade is given.
- Conversion from WICE or MIXED grade: SCTWT = WICE/MIXED + 1. Also see [UKClimbing](https://www.ukclimbing.com/forums/winter_climbing/wi_grades_versus_scottish_grades-429667)
- Description on [alpinist.com](http://www.alpinist.com/p/climbing_notes/grades):
> These apply to ice and mixed conditions and are used primarily by climbers familiar with Scottish conditions. Roman numerals are the overall grades, while Arabic numbers are the technical grade of the hardest section. Scottish technical ratings are approximately 1 generous numeral higher than equivalent Water Ice or M-grades. Technical grade 5 is relatively straightforward, 6 is somewhat technical mixed climbing, and 7 and 8 are much more intricate, including harder snowed-up rock. The current range is 4-9. A complete grade is expressed as VI,8.
> I: Snow gullies and easy ridges.
> II: Steep snow where two ice tools may be required but technical difficulties are short. Possible difficult cornice exit.
> III: Mixed ascents of moderate rock routes; icy gullies; sustained buttresses.
> IV: Steep ice with short vertical steps or long pitches up to 70º, or mixed routes requiring advanced techniques.
> V: Sustained ice to 80º or mixed climbs with linked hard moves. Climbs are difficult, sustained, and/or serious.
> VI: Vertical ice and highly technical mixed routes. Grade VI and above routes have exceptional overall difficulties.
> VII:Multi-pitch routes with long sections of vertical or thin ice, or mixed routes with lots of highly technical climbing.
> VIII-IX: The hardest routes in Scotland. Canadian Winter
- Description on [americanalpineclub.org](http://publications.americanalpineclub.org/articles/13201212386/International-Grade-Comparison-Chart):
> These apply to ice and mixed conditions and are used primarily by climbers familiar with Scottish conditions.
> Grade I: Snow gullies and easy ridges.
> Grade II: Steep snow where two ice tools may be required but technical difficulties are short.
> Grade III: More sustained than Grade II. Mixed ascents of moderate rock routes.
> Grade IV: Steep ice with short vertical steps or long pitches up to 70º, or mixed routes requiring advanced techniques.
> Grade V: Sustained ice to 80º or mixed climbs with linked hard moves.
> Grade VI: Vertical ice and highly technical mixed routes.
> Grade VII: Multi-pitch routes with long sections of vertical or thin ice, or mixed routes with lots of highly technical climbing.
> Grade VIII and above: The hardest routes in Scotland.

**Examples**
Many winter routes using Scottish Winter grades are to be found at
- Great Gully in the Lake District of England on [UKClimbing](https://www.ukclimbing.com/logbook/crag.php?id=14923)
- Devil's Kitchen in Wales on [UKClimbing](https://www.ukclimbing.com/logbook/crag.php?id=2323)
- Ben Nevis in Scotland on [UKClimbing](https://www.ukclimbing.com/logbook/crag.php?id=16877)
- Kerry in Ireland at [kerryclimbing.ie](https://www.kerryclimbing.ie/rock-climbing-guides-ireland/)

**Comment by lordyavin** [comment]
+300 because I added 300+ Routes at Ben Nevis. A lot of them are Scottish Winter climbs and grade 

> The Scottish Winter grading system comprises two numbers the first, a roman numeral, tells you how hard the route is to lead, the second, a arabic numeral gives the tecnical difficulty. Grades go from I to XI, with technical grades going from 1-11, although both are open ended.

**Comment by rouletout** [comment]
+1 - the wrong interpretation of these gardes leads to misleading information in facets like this: https://www.thecrag.com/climbing/world/routes/with-gear-style/trad/assert/is-not-project/?sortby=grade,desc

**Comment by scd** [comment]
It is clear what the possible values are for adjectival grades, but what are the possible values for the technical grades?

**Comment by scd** [comment]
@lordyavin can you please find a reference that outlines the possible values for technical grades.

**Comment by jalonavens** [comment]
Sorry @scd have been on a break from climbing since raising a lot of issues but will try to help out with technical grades here!

From the [Alpinist](http://www.alpinist.com/p/climbing_notes/grades) (requote from OP - italics are mine):
> These apply to ice and mixed conditions and are used primarily by climbers familiar with Scottish conditions. Roman numerals are the overall grades, while _Arabic numbers are the technical grade of the hardest section. Scottish technical ratings are approximately 1 generous numeral higher than equivalent Water Ice or M-grades. Technical grade 5 is relatively straightforward, 6 is somewhat technical mixed climbing, and 7 and 8 are much more intricate, including harder snowed-up rock. The current range is 4-9_. A complete grade is expressed as VI,8.

I also found this on [ScottishClimbs.com](https://www.scottishclimbs.com/wiki/Grades.html#Winter_Climbing_Grades) (italics again are mine) which was quoted by @lordyavin in his "+300" comment above based on my email copy but he's subsequently edited it out apparently:
> The Scottish Winter grading system comprises two numbers the first, a roman numeral, tells you how hard the route is to lead, _the second, a arabic numeral gives the tecnical difficulty_. Grades go from I to XI, with _technical grades going from 1-11, although both are open ended_. 

I suspect the Alpinist's description is old and that ScottishClimbs' is more recent so that the technical grade range currently in use is more likely to be  1-11, but as ScottishClimbs states, I also suspect it is open ended.

**Comment by lordyavin** [comment]
Thanks @jalonavens

**Comment by scd** [comment]
Thanks :)

**Comment by scd** [comment]
I have mostly got this implementation working dev.

<img width="303" alt="Screen Shot 2020-04-28 at 3 22 59 pm" src="https://user-images.githubusercontent.com/373058/80450186-51c7b980-8964-11ea-8641-d330e298dbca.png">

It needs a full release to complete

**Comment by rouletout** [comment]
@scd please include the grade system in https://www.thecrag.com/en/article/grades

**Comment by scd** [comment]
I had missed a step in the release. Adding new grades has an extra unusual step which I did not fully complete.

It is now there and conversions working

Next step is working out how to fix the bad data in the system. Every Scottish Winter grade already input into the system has been interpreted and assigned incorrectly. It would be great to get an idea of how many there are. If there are only a couple of hundred then it will be more efficient to do this manually. If there are thousands then a script might be better. The problem with writing a script is finding the resource time to do this. Even if we decide to do a script we should probably still do key areas manually because it could take a fair while before the script is written.

**Comment by scd** [comment]
So we have come across our first issue with the new Scottish Winter Grades. In the following area, The Comb, the routes are all Trad routes with apparently Scottish Winter Grades.

https://www.thecrag.com/climbing/united-kingdom/ben-nevis/area/2940128697

According to the community  analysis in this issue Scottish Winter Grades are only used for Alpine and Ice types.

Should the routes in the above area be changed to Alpine or is the analysis here wrong?

**Comment by lordyavin** [comment]
I agree.

**Comment by scd** [comment]
@lordyavin do you agree with changing the routes to Alpine? (I think that is what you are agreeing with, but my question had an 'or' in it).

**Comment by lordyavin** [comment]
I agree with changing from Trad to Alpine (I-III) / Ice (IV-VIII).

**Comment by rouletout** [comment]
@lordyavin is this completed from your end?

**Comment by lordyavin** [comment]
Close it. If I discover issues I'll reopen it or create a new one.
