### ISSUE TITLE
Permission request Karma limit bypass

### ISSUE THREAD

**Issue by et15** [theCrag/website#3449]
Karma limit for crag permission request only in force for the button to get to the permit request page but it doesn't stop you to request the permission if you get on the page over the URL (link from wherever (could be sent by a friend like "just request your permission here") or by editing the URL/NID in the browser).

Example url(s) to reproduce the problem:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3APushReturnURL=%2Fclimbing%2Fnew-zealand&D%3ANetworkNodeID=11738251&C%3AState=18580&C%3AHideNavigation=1

Ideally also provide screenshots:

**What you expected:**
Nothing since it's a permission system issue and it's not concerning normal usage. Though, you may want to fix this issue.

**Comment by scd** [comment]
We are gradually removing the Karma auto permissions. I don't want to fix this. Closing
