### ISSUE TITLE
Route with location of 0,0 screws up map

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3453]
**What happened?**

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/australia/orroral-ridge/echidna-rocks/route/153400347

This route has a gps location of 0,0 which is obviously wrong and messes up the map. I think this may actually have a root cause related to #3452 

**What you expected:**

* [ ] when editing routes never save a 0,0 location

**Comment by DaneEvans** [comment]
Yesterday I did nothing different, at creation, I have no recollection though. 

I did have an Internet drop out when submitting some changes yesterday, but loooking at the route this morning on iPhone/safari it looks fine, with a normal lat/long

**Comment by scd** [comment]
updated system in simon's dev so you cannot save 0,0 for lat long route
