### ISSUE TITLE
Rename "Reparent <nodetype>" to "Reparent <nodetype> or children"

### ISSUE THREAD

**Issue by jalonavens** [theCrag/website#3456]
**Issue**
The `Edit <nodetype>/ Restructure <nodetype> / Reparent <nodetype>` menu item is misleading because the children of the node can also be reparented using this menu item.

**Solution**
Either:
* Rename this menu item to `Reparent <nodetype> or children`
* Add an additional item called `Reparent children`

**Screenshot**
![theCrag reparent node screenshot png](https://user-images.githubusercontent.com/13288347/58683460-d823f600-83b7-11e9-90db-b024329bc9e8.jpg)

**Comment by brendanheywood** [comment]
@scd I've already started down this process, can you let me know how to link to those and skip that step and I'll sort the rest splitting it into two menu items

**Comment by scd** [comment]
This has been hotfixed for english, but needs updating for other languages. This was purely a language translation fix for key `template.action-area.reparent-area-type`.

@rouletout can you organise updates for German, Spanish, French, Italian, Korean and Chinese. Once you have scheduled this work can you please close the issue. 

```
de/core.json:   "template.action-area.reparent-area-type" : "{areaType} neuer Mutter zuweisen",
es/core.json:   "template.action-area.reparent-area-type" : "Reubicar {areaType}",
fr/core.json:   "template.action-area.reparent-area-type" : "Réaffecter {areaType}",
it/core.json:   "template.action-area.reparent-area-type" : "Riassegna nodo padre per {areaType}",
ko/core.json:   "template.action-area.reparent-area-type" : "다시만들기 {areaType}",
zh_hans/core.json:   "template.action-area.reparent-area-type" : "重定{areaType}的父级",
```

**Comment by rouletout** [comment]
Done for FR and DE - others scheduled in translation management
