### ISSUE TITLE
Profile Page: Include a graph / stats on days climbed

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3457]
**What happened?**

A statistic in the sense of "how many days did I climb in a specific period" would be nice. 

Ideally also provide screenshots:

**What you expected:**

A bar graph similar to the number of ascents on the CPR graph? Any good idea is welcome to answer this question.

**Comment by brendanheywood** [comment]
This is mostly a duplicate of https://github.com/theCrag/website/issues/1220 so I'll close this and tidy that one up a little
