### ISSUE TITLE
Avatar overlapping name on profile page

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3461]
**What happened?**

See screenshot.

Example url(s) to reproduce the problem:

https://www.thecrag.com/climber/scd

Ideally also provide screenshots:
![Screenshot 2019-06-03 17 25 14](https://user-images.githubusercontent.com/54371/58813684-951a8a80-8624-11e9-8124-92c37157e5b8.png)

**Comment by brendanheywood** [comment]
thanks - but duplicate of: https://github.com/theCrag/website/issues/3458

**Comment by quaestor** [comment]
Ah, sorry. Had a quick look over the issues created since the latest release but I seem to have missed that one.
