### ISSUE TITLE
Typo in ascent listing

### ISSUE THREAD

**Issue by endolith** [theCrag/website#3463]
**What happened?**

Example url(s) to reproduce the problem:

https://www.thecrag.com/ascent/2534723493

Ideally also provide screenshots:

![image](https://user-images.githubusercontent.com/58611/58814470-c75fc400-85f3-11e9-8498-e2e74feeeac1.png)

**What you expected:**

* [ ] "Asent Length" should be "Ascent Length"

**Comment by scd** [comment]
hotfixed
