### ISSUE TITLE
Permalink to edits is broken

### ISSUE THREAD

**Issue by endolith** [theCrag/website#3464]
**What happened?**

Example url(s) to reproduce the problem:

https://www.thecrag.com/climbing/united-states/shawangunks/route/17324335

In the Activity section, if you click the datestamp of the edit, it goes to `https://www.thecrag.com/event/'2534730369` which is a 404

**What you expected:**

* [ ] It should go to `https://www.thecrag.com/event/2534730369`

**Comment by scd** [comment]
This is hotfixed
