### ISSUE TITLE
Locate page does not scroll map at same rate as overlay

### ISSUE THREAD

**Issue by endolith** [theCrag/website#3465]
**What happened?**

If I draw an area overlay (at maximum zoom), and then drag the map up, the overlay moves further than the map, and vice versa for dragging the map down.

Example url(s) to reproduce the problem:

https://www.thecrag.com/climbing/united-states/new-york/area/2537542443/locate

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/58611/58910233-ff920000-86e2-11e9-9e6c-106fd951f480.png)
![image](https://user-images.githubusercontent.com/58611/58910250-0d478580-86e3-11e9-8b64-0b3bff45bb1b.png)
![image](https://user-images.githubusercontent.com/58611/58910270-16d0ed80-86e3-11e9-8861-d5f4fdbb9562.png)

**What you expected:**

* [ ] Overlay should stay with the map when dragged

**Comment by brendanheywood** [comment]
This is a bug in openlayers. I probably won't fix this directly, we've rebuild the maps using leaflet and at some point we'll rebuild the editing of maps to also be done in leaflet.

Have a read through this for the master plan:

https://github.com/theCrag/website/issues/2767
