### ISSUE TITLE
Do not show the crag in the grouping row for default ascents account facet

### ISSUE THREAD

**Issue by scd** [theCrag/website#3467]
**What happened?**

The default facet for an ascents in an account groups by date, but also shows the first crag in the list of routes on that date. This looks like it is grouping wrongly by crag.

https://www.thecrag.com/ascents/by/robertbuschlinger

<img width="925" alt="Screen Shot 2019-06-07 at 12 22 40 am" src="https://user-images.githubusercontent.com/373058/59040689-8f3dd700-88ba-11e9-99f1-b5d395985ea3.png">

**What you expected:**

Group just by date and do not show the crag in the date row.

**Comment by brendanheywood** [comment]
I think the task here is wrong. We want the groupings with crag and date, this is a feature, we just need to fix the bug so the groupings are correct. There are two approaches:

1) The way it probably should have been working: The 1st level grouping should be on 'date + TLC' eg Sun 2nd Jun 2019 - Bärenbrunner Tal. The 2nd level grouping is the partial crumb from TLC to the cliff. The benefit of this approach is we never need to 'look behind', we can process each row as it comes.

In the example above there would be new 1st level grouping headers before 'Birkenkamin' and before 'Zwockel'

2) Similar to above, but we scan ahead and look at all rows for each day, and then find the common ancestor for all ticks on that day. It might be a cliff or it might be a region above the TLC's. This will become the 1st level grouping, and the 2nd level grouping will show from this common ancestor down to the cliff node. If the common ancestor is low I'm happy to cap it back to TLC, so the 1st level grouping is always going to be a TLC or higher.

In the example above the 1st level groupings would stay the same, but both would say 'Westpfalz'. There would be new 2nd level groupings before 'Birkenkamin' and before 'Zwockel'.

Option 1 is easier technically and should be very minor. Option 2 is I think a slightly better UI.

In either approach, and only if the sort order is date and we group by crag / cliff then the crag column is redundant and can be removed

**Comment by brendanheywood** [comment]
I've just fixed the bugs with the groupings, so approach 1. I've also removed the redundant tlc column when we are grouping by tlc (works way better on mobile now due to this)

![image](https://user-images.githubusercontent.com/187449/59141845-6d963a00-89f7-11e9-999a-88de2474fcca.png)
