### ISSUE TITLE
No space after bullet lists - articles (rest of the site?)

### ISSUE THREAD

**Issue by scd** [theCrag/website#3470]
**What happened?**

In article markdown there is no space after bullet lists. 

![no-space-after-bullet-list](https://user-images.githubusercontent.com/373058/59137249-2f365600-89ca-11e9-86bc-596e9708c9b3.png)

https://www.thecrag.com/en/article/loggingascents

 - [ ] check if this is site wide issue or just articles
 - [x] is a css one liner sufficient to fix this

**Comment by brendanheywood** [comment]
It depends on context, we want 'readable' things to have this margin. fixed in dev:

https://brendan.thecrag.com/en/article/loggingascents
