### ISSUE TITLE
Consistently wrong numbers in grade bar charts

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3476]
**What happened?**

The grade bar chart consistently displays wrong route counts.

E.g., for https://www.thecrag.com/climbing/germany/frankenjura/kolumbuswand which has only 4 routes (grades 6+, 8-, 8, 8+), the grade bar chart says it's 6+, 6+, 8-, 8-, 8, 8+, 8+ for a total of 7 routes. The height of the individual bars seems to be correct, though.

I say consistent, because it seems to be off by one more often than not, at least throughout the Frankenjura. Maybe it has to do with UIAA grades?

Might also be related to #3304.

**Comment by Mdemaillard** [comment]
merging into #3545 as duplicate
