### ISSUE TITLE
Extend markdown to detect gps coordinates

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3478]
**What happened?**

Given a set of numbers which look like they could be coordinates in markdown:

```
Walk to a cairn which is at (-34.074459, 150.860498)

The rap tree is at (-34.077876, 150.855652)
```

**What you expected:**

* [x] 1) Check it has enough digits, ie it must have at least 4 decimal places (11m accuracy) 
* [ ] 2) check if they are within the bounds of the current crag, with some extra margin (maybe actually use the tlc's boundary.
* [ ] 3) If it fails check is +/- is wrong in the wrong hemisphere and allow it
* [ ] 4) markup the link as a geo link see also https://github.com/theCrag/website/issues/3477

Examples:

* [ ] https://www.thecrag.com/climbing/france/gorge-du-tarn/area/350100249
* [ ] https://www.thecrag.com/climbing/australia/south-west/area/624385557

**Comment by brendanheywood** [comment]
I've got a fairly simpler version of this working here, check it out here:

https://brendan.thecrag.com/climbing/australia/south-west/area/624385557

**Comment by rouletout** [comment]
This is doen and widely used - closing
