### ISSUE TITLE
Missing new line in logbook import process

### ISSUE THREAD

**Issue by scd** [theCrag/website#3480]
**What happened?**

Reported from a user.

Bulk assignment of log book import.
When I search for a route the select radio button gets appended to the last line of the suggested routes. This is easy to overlook. Should be in a new line.
See screenshot to illustrate.

![logbook](https://user-images.githubusercontent.com/373058/59570594-0440b600-90de-11e9-9b5d-09b22aaabc91.png)

**Comment by nicHoch** [comment]
duplication of https://github.com/theCrag/website/issues/3696
closing this other has better description
