### ISSUE TITLE
Removing a photo shows as photo upload stream event

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#3484]
**What happened?**
I deleted an old and outdated image from the area "Amberg" and in the stream it shows that I uploaded a new photo:
https://www.thecrag.com/event/2574376065

**What you expected:**
When a photo is deleted, nothing should be displayed in the stream or for consistency reasons only the message: ... has removed a photo.

**Comment by rouletout** [comment]
I don't see that happening anymore - just tested and do not get the stream comment, closing. please re-open of you see this again.
