### ISSUE TITLE
Closed Tag - Icon not dispalyed on Map

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3485]
**What happened?**

E.g. here: https://www.thecrag.com/climbing/mexico/area/301024317 when you zoom in on the map to see "Yagul" (https://www.thecrag.com/climbing/mexico/area/921912165) the closed icon is not displayed. 

Also, if you click on Open Guide, the icon is not shown. 

This happens in Firefox and Chrome.

<img width="272" alt="Screenshot 2019-06-24 at 13 46 50" src="https://user-images.githubusercontent.com/19162952/60043859-b05a4200-9686-11e9-9487-0da1adc67ed4.png">
<img width="678" alt="Screenshot 2019-06-24 at 13 46 57" src="https://user-images.githubusercontent.com/19162952/60043873-b9e3aa00-9686-11e9-8148-3daf06e379d4.png">

<img width="715" alt="Screenshot 2019-06-24 at 13 48 59" src="https://user-images.githubusercontent.com/19162952/60043926-df70b380-9686-11e9-9d62-93167ed55674.png">

here in Chrome:

<img width="608" alt="Screenshot 2019-06-24 at 13 50 28" src="https://user-images.githubusercontent.com/19162952/60044077-39717900-9687-11e9-8ee3-85bfc02646ac.png">

Ideally also provide screenshots:

**What you expected:**

* [ ] item 1
* [ ] item 2

**Comment by scd** [comment]
I had a look at this and it was a really simple fix. It was a utf issue for the maps.js file, and I simply replaced the icon. Maybe a bad copy and paste originally.

Hotfixed

![Uploading Screen Shot 2019-12-17 at 2.18.10 pm.png…]()
