### ISSUE TITLE
Profiles removed due to spam still show in forum watching side bar

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3487]
**What happened?**

https://www.thecrag.com/discussion/2559368481/community-profiles---redpoints-marked-as-pinkpoints#m2579135190

![image](https://user-images.githubusercontent.com/187449/60267109-c852ef80-992c-11e9-92ec-d125b1d1cf1b.png)

But they've been deleted and their profile is a 404

https://www.thecrag.com/climber/shakungrover

**What you expected:**

* [ ] don't show the removed spam accounts

**Comment by Mdemaillard** [comment]
For the example above, the icon is correctly updated both in conversation and user list on the right.
the remaining link loops back to the conversation page.
![image](https://user-images.githubusercontent.com/60388146/77245960-82ad2400-6c2b-11ea-85f0-ea38a40973e2.png)
![image](https://user-images.githubusercontent.com/60388146/77245978-ab351e00-6c2b-11ea-95c9-e61e9d3ea856.png)

closing
