### ISSUE TITLE
Grade Distribution Chart: Japan does not show grade distribution (Firefox)

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3490]
**What happened?**

https://www.thecrag.com/climbing/japan does not show a grade distribution chart - it seems to be there (hover over is shown) - it works for other countries though and it works on mobile and on Chrome but not on Firefox.

<img width="1164" alt="Screenshot 2019-07-04 at 18 03 31" src="https://user-images.githubusercontent.com/19162952/60689724-0ea4d300-9e86-11e9-972a-3c8bb5f41dca.png">

Ideally also provide screenshots:

**What you expected:**

Grade Distribution Chart as for all other countries.

**Comment by rouletout** [comment]
here another one for Europe: https://www.thecrag.com/climbing/europe

<img width="895" alt="Screenshot 2019-07-31 at 18 01 25" src="https://user-images.githubusercontent.com/19162952/62254998-ffe80800-b3c0-11e9-9172-0f96d94b8148.png">

**Comment by rouletout** [comment]
and one for Zillertal: https://www.thecrag.com/climbing/austria/area/142177053

<img width="971" alt="Screenshot 2019-07-31 at 18 29 02" src="https://user-images.githubusercontent.com/19162952/62255034-2148f400-b3c1-11e9-9b0b-35184125997f.png">

**Comment by lordyavin** [comment]
I confirm this issue.

**Comment by scd** [comment]
@lordyavin it is only happening with some browsers. Do you have access to other browser versions. We do not know why some browsers do not display properly.

**Comment by lordyavin** [comment]
- Works not with Firefox 60.6.3esr and 68.0.1
+ Works with Internet Explorer 11.0.9600.19377

**Comment by lordyavin** [comment]
Why do use <b> tag to set the background and not the <span> tag that contains the grade text?

![grafik](https://user-images.githubusercontent.com/1528540/62284354-c0b6c700-b453-11e9-8870-a93423fe4c59.png)

**Comment by brendanheywood** [comment]
Fixed:

https://brendan.thecrag.com/climbing/japan
