### ISSUE TITLE
Red point vs pink point long term plans for feedback

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3494]
This is some high level thoughts for attempting to resolve the lack of global consensus on the red vs pink point debate. The aim here is not to force anyone into either side, but to let them be as specific, or not, as they want, and make the defaults simple, and the labels obvious to new climber (not just those new to thecrag)

1) In short term log community ascents as redpoint even though pink is more accurate (we will adjust the existing ones). This will be apples-to-apples with most real profiles.

2) Possibly introduce (or repurpose) a new tick type ("red point draws off") as counterpart to pink point and leave the redpoint as a more vague ascent type.

ie we would end up with:

* Redpoint  - (could be draws on or off, it is unclear)
* Redpoint draws off (a true red points)
* Pinkpoint (draws on)

We already have 'tick' and 'clean' which are vague so I don't think we need another vague one. So possibly we can repurpose 'clean' into 'redpoint' and then rename the current 'redpoint' into 'redpoint draws off'. The cpr for these would be adjusted to reflect the lower bound of certainty for the ascent.

3) Now the challenge and potentially contentious idea is if we bother migrating peoples ticks to the true redpoint or not. If when you look at someones logbook they have a mix of pink and red then it is a pretty clear indication that they care about the distinction, and so when they mean red, they actually mean 'redpoint draws off'. Everyone else we should assume to just mean a vague redpoint. This would affect people's cpr's

**Comment by lordyavin** [comment]
I'm not a fan of introducing "Redpoint draws off" because my logbook would be affected by the change as I care about the distinction between red and pink. I already told that @rouletout beforehand. I vote to educate the climbing community to use the terms as the Austrialians (pink = on, red = off) do because it feels right! No matter how Kurt Albert or Wolfgang Güllich defined it. Maybe I'm harsh about this but thats my opinion.

**Comment by rouletout** [comment]
We have introduced the "gear on" tag with the new ticking interface to allow for more options, also in other gear styles and ascent types. Closing therfore.
