### ISSUE TITLE
Routes as Sites

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3510]
**What happened?**

Climbs created at a level where there are only areas appear as areas and not routes.

Example :
https://www.thecrag.com/climbing/france/fontainebleau/area/445345899

![image](https://user-images.githubusercontent.com/187449/62214202-edcd9000-b3e7-11e9-9f45-3a0d931467a9.png)

**What you expected:**

* [ ] The word 'Area' should say 'Routes'
* [ ] The table actions at the top should be route actions

**Comment by brendanheywood** [comment]
@scd this was a regression from the collapsed node logic, fixed in dev

![image](https://user-images.githubusercontent.com/187449/62215238-e7401800-b3e9-11e9-8abd-2899c57a1ad3.png)
