### ISSUE TITLE
Annotations have no AKA

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3511]
**What happened?**

On creating or editing annotations there is no field for alternative names as for routes or areas.

Ideally also provide screenshots:

**What you expected:**

Same behaviour - alternative name field available

**Comment by brendanheywood** [comment]
Is this for an alternate name in the same language or for a translation? Please add the example where you wanted to use this

**Comment by rouletout** [comment]
It is for an alternate name AND a translation, here: https://www.thecrag.com/climbing/mexico/area/2631399486

I think for consistency there really shouldn't be any difference between Area, Route and Annotation Editing (applies to names, description)

**Comment by scd** [comment]
done
