### ISSUE TITLE
In list view markdown links to routes on the same page should scroll, not go to route detail page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3513]
**What happened?**

https://www.thecrag.com/climbing/australia/gara-gorge/upper-gara-gorge/the-fortress#n13344247

**What you expected:**

* [ ] The various links 'Pockets Full of Emptiness', 'Heaving Falcons', 'Morning Glory', PFOE should all be anchor links

**Comment by Mdemaillard** [comment]
Duplicate of #1542. closing here
