### ISSUE TITLE
Translate orientation tags of the crags into full words

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3514]
Currently, we can add S,N,E,W and SO, NO ... tags for one crag or sector.
It's not very clear that this is orientation.

**What you expected:**

Develop these tags : south instead of S etc ...

* [x] use the lang keys in places which don't (eg article) https://www.thecrag.com/article/tagging?lang=xx
* [ ] re-translate all tags to be full words not just the abbreviations

**Comment by brendanheywood** [comment]
@rouletout this is mostly a translation issue, this was already done in english a while ago:

dbconfig.tags.tag.se.label

There is a couple places the lang key is not being used which also need to be fixed

**Comment by brendanheywood** [comment]
The article is fixed and ready for translations, compare:

https://brendan.thecrag.com/en/article/tagging#N
![image](https://user-images.githubusercontent.com/187449/62441693-7d808f00-b798-11e9-90f3-25ae71d83e3c.png)

to

https://brendan.thecrag.com/en/article/tagging?lang=fr#N

![image](https://user-images.githubusercontent.com/187449/62441685-76598100-b798-11e9-8850-96237e09ace2.png)

Note: the rest of the article is NOT yet ready for translation, just the tags

**Comment by lordyavin** [comment]
Updated the German translation of the labels on sandpit.

**Comment by gui84** [comment]
Updated the French translation of the labels on sandpit.

**Comment by scd** [comment]
@rouletout have you checklisted the languages which need tags translated again. I would like to close this issue. Doing a scan I think it is just spanish and and Italian that needs translations modified.

```
es/core.json:   "dbconfig.tags.tag.n.label" : "N",
it/core.json:   "dbconfig.tags.tag.n.label" : "N",
```

I do not think github is the best way to manage translation checklists. So @rouletout can you either work out how you want to manage the final translations changes and close this issue when done.

**Comment by rouletout** [comment]
all done
