### ISSUE TITLE
Can't add area warnings anymore

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3515]
**What happened?**
Since a while the button to raise a warning for an area disappeared for me.

**What you expected:**

* [ ] The button to raise warnings

**Comment by brendanheywood** [comment]
What crag were you at?

**Comment by lordyavin** [comment]
Applicable to the all nodes. Checked it again for the [Donautal](https://www.thecrag.com/climbing/germany/schwaebische-alb/donautal) crag, sector, route. No warning button.

**Comment by brendanheywood** [comment]
No we want this to be low barrier to entry for reporting issues. I can see this as my non-admin account too no problems:

![image](https://user-images.githubusercontent.com/187449/62466674-3664bf00-b7d5-11e9-9f29-0513560cf701.png)

Where exactly are you expecting to see it? In the '...' menu?

**Comment by lordyavin** [comment]
Yeah found it in the menu.
