### ISSUE TITLE
Integrated map broken

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3516]
**What happened?**

Example url(s) to reproduce the problem:

https://www.thecrag.com/climbing/austria/baldwand
![grafik](https://user-images.githubusercontent.com/1528540/62446086-21027d00-b762-11e9-8a94-173cd04eeb96.png)

https://www.thecrag.com/climbing/switzerland/alpen/appenzeller-alpen/area/157688322
![grafik](https://user-images.githubusercontent.com/1528540/62446132-39729780-b762-11e9-8fff-ebc811462bd3.png)

**What you expected:**

* [ ] Working map

**Comment by brendanheywood** [comment]
Works for me? Got any more details, like dev tools network tab errors?

**Comment by lordyavin** [comment]
I deactivated the caching and it works again. Looks like an issue on my side.
