### ISSUE TITLE
Index on help article seems broken (web-covers)

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3519]
**What happened?**

https://www.thecrag.com/de/artikel/webcovers/?lang=es

This index is broken / not nice, especially on mobile.

![IMG_4922](https://user-images.githubusercontent.com/19162952/62650553-c6f9e700-b91c-11e9-8d92-49c8169be3f3.PNG)

Ideally also provide screenshots:

**What you expected:**

Nice index as for other help pages

**Comment by scd** [comment]
This was a translation issue. The Spanish version of the article translation changed the double hash `##` to a single hash `#` which changed the header level. It is now fixed and pushed to prod.

https://www.thecrag.com/es/article/webcovers
