### ISSUE TITLE
float clear bug with region layout + warning header

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3520]
**What happened?**

https://www.thecrag.com/climbing/mexico/la-huasteca/route/1921700112

Example url(s) to reproduce the problem:
![image](https://user-images.githubusercontent.com/187449/63636858-7a523200-c6b8-11e9-8956-347d51b79fec.png)

Css bug in the regions, 

.forum .discussion-header {
    /* clear: both; */  <<---

to reproduce make the right aside region very long (ie lots of ads / photos etc)

**What you expected:**

* [ ] item 1
* [ ] item 2

**Comment by scd** [comment]
I have hot fixed this buy removing the `clear: both`

I cannot see a broken url at the moment to verify.
