### ISSUE TITLE
Markdown shown in Forum Titles

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3524]
**What happened?**
The overview of forum messages shows the markdown which looks a bit awkward. See screenshot from here: https://www.thecrag.com/climbing/germany/forum

<img width="645" alt="Screenshot 2019-09-08 at 18 43 23" src="https://user-images.githubusercontent.com/19162952/64496245-93d2ac80-d268-11e9-84fc-0c18ce450c24.png">

Example url(s) to reproduce the problem:

Ideally also provide screenshots:

**What you expected:**

Markdown not shown

**Comment by brendanheywood** [comment]
Markdown is designed to be human readable in raw form, I think the better solution here is to just use the more natural raw words and links and let it link naturally ie:

```
**Reel Rock 14**

https://reel-rock.eu/en/tickets

blah blah
```

which will read well both in raw form and also look much nicer in html form:

**Reel Rock 14**

https://reel-rock.eu/en/tickets

blah blah

**Comment by rouletout** [comment]
Agree, more an editing question, closing
