### ISSUE TITLE
OSM as the default map, and map tab is open by default on mobile device 

### ISSUE THREAD

**Issue by bing-li** [theCrag/website#3533]
**What happened?**

- OSM may contains trails to the crag and crag location, which may not be seen on satellite map
- many new mobile users don’t know how to open map and switch to osm  

- I think the most important value of map is to help climbers approach the crag, gps tracking on osm is better for this purpose. 

**What you expected:**

* [x] OSM as the default map
* [x]  map tab is open by default on mobile device  Edit by Mddemaillard - wont do

**Comment by Mdemaillard** [comment]
There is value in being able to setup a default layer, somewhere in user profile probably.
I disagree with the second item, i have way more value having the index than the map in most usages.

**Comment by scd** [comment]
We will not be opening the map by default on the mobile layer. We need to keep tile usage down.

Default layers change from area to area. 

I think we need our own tile server.

**Comment by rouletout** [comment]
This has been changed to OSM (China) and will be available on next release. We would still like to add a real chinese map layer such as Baidu.... any other suggestions?

**Comment by bing-li** [comment]
the two main map providers in China are  https://map.baidu.com/  and  https://www.amap.com/

**Comment by scd** [comment]
@bing-li as I do not read Chinese I am having difficulty working out relevant sections for integrating with amap or baidu.

Some things I need to know. 

1. Are we able to use the map provider for free in there T&C? 
2. Do they have an attribution requirement (for example OSM is attribution: '© <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>  contributors')
3. How do we get their tiles in a url (for example OSM has the following format: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png )

**Comment by rouletout** [comment]
This has been implemented for all Chinese crags (now OSM China is default). Please open a new issue once you have info on how to implement Baidu and amap - closing
