### ISSUE TITLE
content issue, en/grades

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#3536]
**What happened?**
https://www.thecrag.com/en/article/grades

paragraph 5 is nonsensical. 

**What you expected:**

full sentences

**Comment by brendanheywood** [comment]
Can you be specific? Perhaps using full sentences? :stuck_out_tongue:

**Comment by DaneEvans** [comment]
I suppose, but I don't know that there aren't others, or what you want to
do about it.

Paragraph reads
"Together with the rock climbing community theCrag developed and continuous
to develop a comprehensive and intuitive coverage of grades in the system."

Now that just looks like a typo on continuous vs continues, but i
 thought it was more egregious yesterday, maybe a display issue with where
the line breaks were.

**Comment by brendanheywood** [comment]
thanks I've fixed the typo:

...community theCrag has developed and continues to develop a comprehensive...

vs

...community theCrag developed and continuous to develop a comprehensive...

will be in the next release
