### ISSUE TITLE
Inconsistent badges on photo page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3542]
**What happened?**

https://www.thecrag.com/photo/2006940105

![image](https://user-images.githubusercontent.com/187449/67631806-2bf72480-f8ef-11e9-863f-f67db010f1ee.png)

**What you expected:**

* [ ] both with pink badge

**Comment by rouletout** [comment]
Not a supporter anymore so both are the same - clsoing until we find an example to debug that
