### ISSUE TITLE
Area histogram route count off by one 

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#3545]
**What happened?**
Both entry and display are Ewbank, and it doesn't seem to be a grade fuzziness issue. 
Area has less routes than the histogram shows. Rounding error perhaps?
1x 25, histogram shows 2, 
1x 32, histogram shows 2 
4x 15's, histogram shows 5 

seems to be the same for most of them, except grade 7, which correctly shows 2. 

The histogram itself seems like it may be correct, so it might be an issue in the mouseover display. 

Example url(s) to reproduce the problem:

https://www.thecrag.com/climbing/australia/orroral-ridge/tower-rocks

![image](https://user-images.githubusercontent.com/22091505/67735022-e5243e80-fa56-11e9-8f99-ff0c44abab0f.png)

**What you expected:**

The count to match what is seen if you click on it.

**Comment by scd** [comment]
Hmmm I have reset stats and cache and it still seems wrong. This is weird, but because it is not critical I cannot do any further work on it for now.

**Comment by killakalle** [comment]
This is also happening at
https://www.thecrag.com/climbing/spain/valencia-cuenca-area/area/3067857549

What I found also interesting is that the filter seems not to function in an obvious way. When I click on one of the bars of the histogram, I see a filter that seems incorrect at first glance:
![image](https://user-images.githubusercontent.com/30682796/73742686-4130ea00-474d-11ea-9fe2-5d16f2918f49.png)

Are you internally matching boulder grades with French sport grades? e.g. 6B+ (FB) matches 7a+ (FR)?
But maybe that's a different issue.

**Comment by Mdemaillard** [comment]
Merging a duplicate:
From @quaestor What happened?

The grade bar chart consistently displays wrong route counts.

E.g., for https://www.thecrag.com/climbing/germany/frankenjura/kolumbuswand which has only 4 routes (grades 6+, 8-, 8, 8+), the grade bar chart says it's 6+, 6+, 8-, 8-, 8, 8+, 8+ for a total of 7 routes. The height of the individual bars seems to be correct, though.

I say consistent, because it seems to be off by one more often than not, at least throughout the Frankenjura. Maybe it has to do with UIAA grades?

**Comment by rouletout** [comment]
see also duplicate https://github.com/theCrag/website/issues/3793

**Comment by rouletout** [comment]
see also https://github.com/theCrag/website/issues/3560

**Comment by rouletout** [comment]
+1 from support forum

**Comment by MelwinQ** [comment]
Similar problem here: https://www.thecrag.com/en/climbing/germany/berlin/area/233883528
Shown top-grade routes in histogram do not exist.

**Comment by georg-d** [comment]
Issue reduced to the max at https://www.thecrag.com/en/climbing/spain/mallorca/area/931645020 – crag has 1 route, but grade band chart shows in 3 grades 1 route, summing up to 3 routes 🤪 

+1 to analyse possible root caused named in https://github.com/theCrag/website/issues/3560 (maybe the width of the grades makes them counted twice?) because it matches perfectly: According to [help](https://www.thecrag.com/en/article/grades#trad-and-sport-grade-systems), in theCrag _UIAA 5+_ overlaps with _FR 4c+, 5a and 5a+_ and for exactly these 3 grades, 1 route is shown, summing up to 3 routes.

**Comment by rouletout** [comment]
+1 from forum: I often search for a specific grad at a crag in the histogramm of the route grades in the overview of a crag/ sector. Those numbers don´t add up to the actual existing routes. Example: https://www.thecrag.com/de/klettern/switzerland/schauenburgfluh You see two 7c routes in the histogramm, but if you click on it, that there is only one of them.

**Comment by scd** [comment]
Notes to self when looking into this. In simon's dev the histogram for the following url has 2 grade 32's where there should be 1.

https://simon.thecrag.com/climbing/australia/orroral-ridge/tower-rocks

**Comment by scd** [comment]
Thanks everybody for your patience with this one. I have found an offending issue - the problem with computer division not doing exact calculations and getting small discrepancies. So there was 1.000000001 routes (something like that) which is rounded up to 2 for display. 

Internally we store the profile as fractions of a route for our internal grade system. This means we can convert to any grade system easily. As the fractions are sometimes not exact the sum can be off.

This obviously sucks as far as the human is concerned. 

Without addressing the the business rule of rounding up I have round the sum to the nearest two decimal places (ie one hundredth of a grade is enough to cover the precision of the internal grading system).

This does not address the business rule if a route, in it's native grading system, spans across two grades in your display grading system. You would then see this route double counted if there was only one route at the grade. The alternative is to show fractions (eg 0.5 routes).

**Comment by georg-d** [comment]
Oh my dear! Yeah, the primitive data types with their tiny fractions off the actual number are nasty, occasionally causing really strange symptoms – I already considered to round _all the time_ by around 7 fractions 😕

In all examples I looked at, number of routes do now match when routes and display grading system are the same 👏

But how do we handle when routes and display grading system differ? ❓🤔 Displaying "0.33333 routes" in the tooltip feels completely odd & buggy to me. But the same is true for showing more routes in chart's tooltip than route listing.

@scd At https://www.thecrag.com/en/climbing/spain/mallorca/area/931645020 the 3 bars are not same height despite all have same number of routes (1) written in the tooltip. Is the height calculated based on _how much_ the grades of different systems _overlap_? In the meaning one existing route is not evenly "distributed" to all display grades (so in this case, each FR grade 4c+ 5a 5a+ would get ⅓ of the one UIAA 5+ route), but instead each display grade gets a different big "share" of the route (as you can see in https://www.thecrag.com/en/article/grades#trad-and-sport-grade-systems UIAA 5+ has a bigger overlap with FR 5a than it has with 4c+ and 5a+).

If that is true, I've an idea for such "inexact" cases (i.e. route & display grading systems differ _and_ do not have exactly the same steps – so my idea is not for e.g. Ferrata French and Ferrata Schall but it is for e.g. UIAA and French):
* in the histogram, we show an "area chart" (think "gauss curve") instead a bar chart. Of course, this strongly depends on how easy it is with the library we use.
* in the tooltip, we don't show "5a 1 route" but a wording like "around 5a 1 route"

By that, we'd give _very clear and instantly recognizable hints_ whether displayed information is showing the native, exact numbers (=bar chart with "crisp edges" and clearly distinct bars, which are commonly used for discrete values) or it is an interpolation with uncertainty (=vague wording "around 1 route", "blurry" area chart, which is commonly used for continuous values).
