### ISSUE TITLE
When re-parent (a boulder area) the kid boulders still linked to the old parent structure. 

### ISSUE THREAD

**Issue by FredrikEckardt** [theCrag/website#3547]
I have re-parented Sweden / Tjörn and Orust / Skaftö. (https://www.thecrag.com/climbing/sweden/tjorn/area/2296650093) 

(Previously Sweden / Gothenburg / Skaftö). 

Skaftö is now located where I want it in the hierarchy. 
Skaftö have 5 kids. I can see the kids in "the list" and "in the hierarchy" (Under Skaftö). 

But, when I click on the kids .... I realise the kids are actually left in their old hierarchy. 
Example: Sweden > Gothenburg > Skaftö > Bökevik 
https://www.thecrag.com/climbing/sweden/gothenburg/area/2296650267

**Comment by scd** [comment]
This is an irritating temporary glitch where the node cache of the ancestors are not updated immediately. I just reset the cache for Bökevik and it seems ok.

FYI this not simple to fix and has low impact except for being irritating for some users who are unaware. This means it might be a while before it is fixed.

**Comment by scd** [comment]
This is a temporary caching issue. There is no current plan to fix this until caching is revamped. Closing
