### ISSUE TITLE
Japanese localization

### ISSUE THREAD

**Issue by dahu33** [theCrag/website#3551]
I live in Japan and would love to see thecrag.com getting more popular here. One of the thing that slow down the adoption by the locals is the lack of Japanese localization (most of Japanese people do not speak English).

Is it something that thecrag.com would like to support, and if yes how can we help?

**Comment by nicHoch** [comment]
Hi @dahu33 
yes we are currently working on a Japanese localization. I will contact you on theCrag for any help.

**Comment by dahu33** [comment]
> yes we are currently working on a Japanese localization. I will contact you on theCrag for any help.

This is a great news!!! After the Japanese localization is done for the application, it would be great to have #1748 in place so people can submit content in different languages.

**Comment by rouletout** [comment]
Hi Pierre,

Me chiming in. Are you in a position to help with translations? More help will result in quicker results ;-).

Thanks for using theCrag

Ulf

**Comment by rouletout** [comment]
Closing - Japanese is on the list as future language but so far no luck with translators...
