### ISSUE TITLE
Topo symbol explanations in help article and inline legend and editing menus

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3552]
**What happened?**

See Facebook discussion:

https://www.facebook.com/groups/rcibm/permalink/1207449666109463/

Example url(s) to reproduce the problem:
![image](https://user-images.githubusercontent.com/187449/68521393-ba5aa580-02f4-11ea-994c-843345c352c6.png)

**What you expected:**

* [x] the topo point type icons needs to be removed from the topo code and pulled in as standalone icons so we can reuse them in different places
* [x] when editing a topo the symbols should be inside the drop down menu along side the text
* [ ] swap all strings to lang strings
* [ ] mouse over a topo point should add that into to the tooltip as well as the route name
* [ ] in the topo view top right menu there should be a legend button which shows a similar drop menu showing all the points types. This could possibly be dynamic and only show the points in use in this topo

* [ ] have a help section showing all the topo point types

**Comment by lordyavin** [comment]
+1

**Comment by brendanheywood** [comment]
First half is done

![image](https://user-images.githubusercontent.com/187449/68527657-6cb65b00-033d-11ea-9ef3-b58908be362b.png)

**Comment by brendanheywood** [comment]
And now view mode is done too. If a topo doesn't have any special point types then nothing is different. If a topo does use any special point types then there is a custom legend which shows only those point types:

![image](https://user-images.githubusercontent.com/187449/68763335-4c074180-066c-11ea-8a08-555356fec9e9.png)

**Comment by nicHoch** [comment]
Fantastic!

just a minor edge case:

https://brendan.thecrag.com/climbing/spain/alto-mijares/casucho

![image](https://user-images.githubusercontent.com/2226714/68764501-1c7c1900-061b-11ea-9aeb-c5740f11821c.png)

the topo is not high enough to onclude the legend.
So it gets cutted and also some "strange" dots are shown.

**Comment by brendanheywood** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/187449/68765855-def6aa80-0671-11ea-8b83-ad8d202583ef.png)

Does that cliff really have a carrot bolt? In spain? :)
