### ISSUE TITLE
Pdf/html Crag Guide shows archived routes

### ISSUE THREAD

**Issue by lerad** [theCrag/website#3553]
I created a crag guide for a local climbing gym, and it also shows archived routes. The problem seems to be for pdf and html guides as well.

Example:

https://www.thecrag.com/climbing/germany/nordeifel/area/1606384398/guide

There are 79 routes in the crag, however 119 in the crag guide, as it also shows archived items.

My expectation would be that archived routes are not shown in the crag guide, otherwise it would become very fast unusable, especially with climbing gyms.

**Comment by lordyavin** [comment]
Probably the PDF guides where never meant to be used for gyms. But of course you are right.

**Comment by scd** [comment]
Crag guides were never intended for gyms. Of course it is not the first time theCrag get's used for reasons we did not predict.

I would like to explore the motivation and value of a crag guide for a climbing gym.

**Comment by lerad** [comment]
To be honest this was the first time I tried it, so I cannot say whether I will continue using it this way, but my two main motivations were:

1. Keeping the data in the crag in sync with the actual gym routes, so I can see which fraction of the routes I have already climbed. I can then note removals, additions on the crag guide.

2. Making sure that I have my ascents available at the gym. Sometimes I am also not sure whether I already successfully climbed a route or only partial, with hangs, etc. It is then good to have this list, on which I can note whether I was successful or not. Also this helps me to spot unconcious tendencies to only climb routes which I like (e.g. no overhangs, or no crimps, etc.)

**Comment by scd** [comment]
Did you know there is a route filter which can tell you which climbs you have and have not done in an area. Look for 'Been climbed by' and 'Never climbed by' filters in the following page:

https://www.thecrag.com/climbing/germany/nordeifel/area/1606384398/routes

**Comment by scd** [comment]
Interesting. The share text was done for gyms. In particular for sharing new routes. It saves a lot of typing.

Would you share the share text info, or would you just use the info. I am asking this because we are slowly working out different uses for the filter results. In some cases graphing, in other cases share texts. If there are different summaries that are useful then this is worth discussing.

**Comment by lerad** [comment]
I would just use the info, copying it into a closely spaced word document, which I then would print and carry to the gym to note my ticks.

(Alternatively I might also copy it into an editable text file on my phone and update it there. I have to try this out to see if it works.)

**Comment by Mdemaillard** [comment]
interestingly the HTML shows correct value of route in the node list i.e. without the archived routes.
But does display the route in the body.
![image](https://user-images.githubusercontent.com/60388146/76522280-09fdd900-646f-11ea-946e-f7d02e91fc3d.png)

![image](https://user-images.githubusercontent.com/60388146/76522383-33b70000-646f-11ea-8502-872b7857d655.png)

**Comment by rouletout** [comment]
+1 from https://github.com/theCrag/website/issues/4002

**Comment by PierreBau** [comment]
+1. We are a local associative gym and the route are not changed often, however we do archive them when changed. The PDF topo is used to print so the climbers can refer and know the diifficulty/grading.
So it is quite annoying that archived route appears on it.

**Comment by scd** [comment]
I have just removed archived routes from the pdf. You will have to regenerate. Please let me know if there are still problems.

Also did you know there are gym cards which are print friendly cards for printing route labels for gyms. 

Also when the gym resets some routes it would be cool to create a list of the the new routes so climbers can easily see what is new and easily promote and tick the new routes.
