### ISSUE TITLE
Top rope access

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3554]
**What happened?**

When you tick a route with toprope access, nothing (text or symbol) indicates that the route has foot access for installing a top-rope on the index or in the route page.

**What you expected:**
* Add a symbol for toprope access in the index and the route page.

**Comment by brendanheywood** [comment]
Is there an well understood UIAA symbol or something we can adopt?

**Comment by gui84** [comment]
<img width="193" alt="Capture d’écran 2020-04-08 à 08 02 50" src="https://user-images.githubusercontent.com/34114303/78730502-949efe80-796f-11ea-8625-f5e7e6f6aa12.png">
Something like this ?

**Comment by gui84** [comment]
Or this one : https://fontawesome.com/icons/arrow-alt-circle-down?style=regular

**Comment by rouletout** [comment]
What would be the advantage over the Top Rope access flag?

**Comment by Mdemaillard** [comment]
visibility. 
The project tickbox triggers a visible "project" flag both in route page and index.
The top rope tickbox doesnt shows any flag anywhere.

**Comment by scd** [comment]
Just so I understand, is the proposal to replace the top rope access flag?

**Comment by rouletout** [comment]
I don't think so but the comment was that the set flag doesn't show prominently - like the project flag ads the project tag the top rope access flag would set a tag. Don't think we have a solid conclusion.

**Comment by gui84** [comment]
The idea was to render this top rope access flag by something, a symbol or just a text like the project tag.

**Comment by lordyavin** [comment]
IMHO if there is top rope access this can be stated in the approach field of the sector.

**Comment by Mdemaillard** [comment]
I really like the idea of the top rope access flag per route, because sometimes individuals route have or have not TR access in a single node, and breaking it in 10s of sector would be unnavigable. IMO the flag just need fixing so it shows like the project one. We can add an icon if we want to, but that's secondary.

**Comment by rouletout** [comment]
This will be available from next release, closing
