### ISSUE TITLE
Corrupt stream layout

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3555]
**What happened?**
Just loaded my dashboard and got a weird lyout of the stream:

![grafik](https://user-images.githubusercontent.com/1528540/68653733-a4372a00-052c-11ea-8bf5-c597ef13c2a4.png)

**Comment by brendanheywood** [comment]
I've found the root cause of this and got a patch on the way

**Comment by lordyavin** [comment]
So it's not yet hotfixed, right?

Happened again:

![grafik](https://user-images.githubusercontent.com/1528540/69236373-a5530180-0b93-11ea-96f2-7f8a32992815.png)

**Comment by brendanheywood** [comment]
@lordyavin if we hot fix something we will update and close the github issue. This will be in the next release

**Comment by scd** [comment]
I am closing this because it should have been fixed for last release.
