### ISSUE TITLE
Route Page: Ascent History

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3556]
For some routes users try to enter a full route ascent history. For example here: https://www.thecrag.com/climbing/france/ceuse/route/15807193

Ideally also provide screenshots:

**What you expected:**

We should fill that information from the actual ascent history in a separate (but route history related) heading. This could e.g. shows the first 10 ascents for each and a button to go to the full list (advanced search).

**Comment by brendanheywood** [comment]
Closing this as a duplicate https://github.com/theCrag/website/issues/3411
