### ISSUE TITLE
Re-order function - change layout to new list view

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3558]
**What happened?**

When re-ordering long lists of routes and annotations it is very hard to see which is which (see screenshot for example).

![IMG_5365](https://user-images.githubusercontent.com/19162952/68954132-faa0a480-0788-11ea-81a5-b3cc0f84bf03.PNG)

Ideally also provide screenshots:

Use the same list view as e.g. for topo route selection.

<img width="624" alt="Screenshot 2019-11-15 at 09 20 26" src="https://user-images.githubusercontent.com/19162952/68954219-2f146080-0789-11ea-96e1-2600be232381.png">

**Comment by lordyavin** [comment]
+1

**Comment by nicHoch** [comment]
+1

**Comment by rouletout** [comment]
this is done, closing
