### ISSUE TITLE
Route grade distribution chart stats are wrong

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3560]
**What happened?**

Here for example: https://www.thecrag.com/climbing/france/buoux
the stats show 2 8c+ but if you click on them it only shows 1.

Issue seems to come from here: https://www.thecrag.com/climbing/france/buoux/area/14010169

Hint: this route (Brexit Exit) was moved from Buoux into the correct sector, no idea if this has an impact.

**What you expected:**

Correct number on distr. graph

**Comment by lordyavin** [comment]
Possible duplicate of #3545

**Comment by rouletout** [comment]
This might help, I just added 3 routes but the stats show 6 - the grades are YDS_ALT - maybe the width of the grades makes them counted twice?

https://www.thecrag.com/climbing/belize/area/3151372260

**Comment by rouletout** [comment]
Duplicate of https://github.com/theCrag/website/issues/3545 closing here
