### ISSUE TITLE
Request Permissions Form: Replace "Finish" button with "Cancel"

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3565]
**What happened?**

The button on the Request Permission form is labeled "Finish" but should rather be "Cancel". There is also no translation key for finish.

<img width="1088" alt="Screenshot 2019-12-02 at 10 02 26" src="https://user-images.githubusercontent.com/19162952/69974456-eb408b80-14ea-11ea-902c-d58690bd720b.png">

Example url(s) to reproduce the problem:

Ideally also provide screenshots:

**What you expected:**

Replace the "Finish" button with the available "Cancel" button and translation key.

**Comment by scd** [comment]
hotfixed
