### ISSUE TITLE
Topo: Select existing Image for Topo needs more info

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3569]
**What happened?**

For example in this area (https://www.thecrag.com/climbing/mexico/area/2567357517) I loaded a bunch of images for the individual cliff sections (on purpose as images and not as topos) and wanted to select them later to draw topos for some of them (and leave the others for other users to complete). As can be seen on the screenshot, it is close to impossible to decide which image is which from the selection list. 

<img width="1106" alt="Screenshot 2019-12-21 at 18 49 40" src="https://user-images.githubusercontent.com/19162952/71315426-aab99b00-2422-11ea-8597-ef7948b76c16.png">

Ideally also provide screenshots:

**What you expected:**

At least an image ID or name so that it is easier to select the right image. A zoom option would also work, whatever is easier.

**Comment by brendanheywood** [comment]
I think a better approach is browsing the list of photos, and then having a 'turn this photo into a topo' button / action. Some nodes will have hundreds of photos, browsing and choicing here will never be great

**Comment by rouletout** [comment]
I partially agree with that - but it would be counterintuitive to have to go to photos to create a topo. 
You should see what is there when you add a topo so that you choose the best pic available and maybe don't have to load one. An option would be to go to the foto view from the small selection if you wish to see more details and then click create topo from there.

However, this could be a second option.

BTW, what are the sort criteria for this foto selection? It doesn't seem to be upload date what makes it even harder to find.

**Comment by rouletout** [comment]
Fixed
