### ISSUE TITLE
Show trad instead of boulder ascents on profile page under 'Notable Ascents' if there are more of them

### ISSUE THREAD

**Issue by JoeyScarr** [theCrag/website#3570]
**What happened?**

I've been trad climbing many times, and only logged one session of bouldering ever. But the Notable Ascents part of my profile page contains only Sport and Boulder ascents (no trad).

Example url(s) to reproduce the problem:
https://www.thecrag.com/climber/joeyscarr

Screenshot:
![crag-profile-screenshot](https://user-images.githubusercontent.com/3654029/71339233-0dd43a80-25a7-11ea-9c0f-269e8d72b5af.png)

**What you expected:**

I'd much prefer the page to have all three styles, or at least pick the styles that I climb the most (which are sport and trad).

**Comment by lordyavin** [comment]
Maybe correlated with #3549

**Comment by rouletout** [comment]
As I see it now it also shows trad - is this ok?

**Comment by JoeyScarr** [comment]
Yep, looks like this is fixed.
