### ISSUE TITLE
Routing topo can not be edit in China

### ISSUE THREAD

**Issue by leomao10** [theCrag/website#3571]
**What happened?**

This is something I found in China, and I can't reproduce it now as I am back in Australia, but base on the error log in chrome console, I found that all js libs that use google's domain would be blocked in China, which include:
- `jquery.ui`, which using `ajax.googleapis.com`
- `analytics.js`, which using `google0-analytics`
- `linkid.js`, which using `google0-analytics`

**Comment by leomao10** [comment]
@lordyavin might be good to cross check if other functions get affected

**Comment by rouletout** [comment]
This was fixed, closing
