### ISSUE TITLE
TasMaps is broken in all of tassie

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3572]
**What happened?**

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/australia/coles-bay/area/3010923498

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/187449/71776880-d45eee80-2fec-11ea-9712-8f95e600bb24.png)

**What you expected:**

* [ ] just delete it that layer

**Comment by scd** [comment]
Done
