### ISSUE TITLE
Error toggling gym display style

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3573]
I have admin rights for this [gym](https://www.thecrag.com/climbing/germany/oberbayern/area/400652121). I tried to toggle display style from standard to flat, but I get a popup with the following error:

> api post error: Bad Request:error:{"data":{"flattenDisplay":1,"node":612780678,"submittor":356258205},"error":{"flattenDisplayError":"Insufficent permissions to set flattenDisplay"}})

Interestingly, I'm able to switch back from flat to standard without problems (Nicky was so friendly to demonstrate me this nice feature on one sector) but not back again.

**Comment by scd** [comment]
@birgander2 this should be hotfixed now. Can you please test and close the issue if it works.

**Comment by birgander2** [comment]
Perfect, thanks!
