### ISSUE TITLE
Ascent page, dates gone

### ISSUE THREAD

**Issue by proceedhhx** [theCrag/website#3575]
Is it a bug or a feature that the ascent page doesn't show any dates?

https://www.thecrag.com/ascents/by/tobiau/

![issue jan 19](https://user-images.githubusercontent.com/47369736/71812718-39abf180-3078-11ea-92c0-9519797086aa.JPG)

**What you expected:**
Ascent page showing dates of the ascents.

**Comment by lordyavin** [comment]
@proceedhhx actually it does but it is a little bit hidden:

![sketch-1578314726575](https://user-images.githubusercontent.com/1528540/71819233-97960480-308b-11ea-80ae-cf63f7bffbe5.png)

**Comment by proceedhhx** [comment]
oops, sorry. And when I change to sort by grade it shows them for every climb. THat was what I was searching for. sorry. Can be deleted.
