### ISSUE TITLE
Enable context menu for ascents in 'Full Stream Event' display

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3577]
**What happened?**

I wanted to edit a bunch of ascents form the last session and went to the ['full stream event'](https://www.thecrag.com/event/3015418056) display to avoid scrolling down my stream every time I finish the editing. Unfortunately the  'full stream event' page does not provide the context menu for ascents.

**What you expected:**

* [ ] Context menus for stream events on 'full stream event' page
* [ ] Bulk edit for ascents of a stream event

**Comment by Mdemaillard** [comment]
How do you navigate to the stream card page ?? I only found via Profile the full activity Stream:
https://www.thecrag.com/climber/mdemaillard/stream/mine

In there the context menu IS available, and individuals ascent can be edited.

**Comment by rouletout** [comment]
This is available now - closing
