### ISSUE TITLE
API: add support to delete routes

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3580]
Yet the endpoints for deleting routes are not a available.

**Comment by scd** [comment]
Why do you want to delete routes? There are only limited edge cases where
we allow this anyway.

**Comment by Acen** [comment]
Gyms are a pretty appropriate place to delete routes.

Currently drafting up the process of integrating nicely into gym management software and need this to have it work efficiently.

**Comment by rouletout** [comment]
@Acen there is a well established archiving process for gym routes, read here: https://www.thecrag.com/en/article/gymarchiveroute

**Comment by Acen** [comment]
> @Acen there is a well established archiving process for gym routes, read here: [thecrag.com/en/article/gymarchiveroute](https://www.thecrag.com/en/article/gymarchiveroute)

Tis' indeed why I made an edit.

**Comment by scd** [comment]
Archive routes in gyms, not delete.

**Comment by rouletout** [comment]
Closing as delte is not an option that works often
