### ISSUE TITLE
Default partner field missing when ticking multiple gym ascents

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3583]
**What happened?**

If you tick multiple ascents in a gym, there have been a field to set the "default partner". This field disappeared a while ago (only in gyms, on rock it's ok); now the partner needs to be added on each individual ascent . Would it be possible to bring this feature back? I anyway suppose it did not got deleted on purpose...

**Comment by lordyavin** [comment]
+1

**Comment by scd** [comment]
This is fixed in simons dev. Will be available from next release
