### ISSUE TITLE
No relative poplularity chart for gym routes

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3584]
**What happened?**

Different to natural routes, on gym routes this little polularity chart, showing how often a route has been ascended, is not shown. I think this feature is pretty interesting for gyms, too. 

Additonally, clicking on the chart usually leads to the list of ascents of a route. Currently, in gyms this information cannot be easily accessed, at least not on a route's level. Getting feedback on routes is interesting for gym owners, probably getting some beta for the climbers. 

**What you expected:**

* Relative popularity chart next to each gym route
* Linked to the list of ascents of this route

**Comment by scd** [comment]
This is fixed in simon's dev. Will be available from next release
