### ISSUE TITLE
System Wide Grade Conversion - Render Issue

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3585]
**What happened?**

Set the preferred grade system for sport routes to "UIAA" and enabled auto conversion. Looking at the index of the [Weigend Süd Wall](https://www.thecrag.com/climbing/germany/oberbayern/area/3047579388) I see that the conversion works but the rendering of the grade badges contains the grade context abbreviation "{FR}".

![grafik](https://user-images.githubusercontent.com/1528540/73436977-ca11e500-434b-11ea-8252-86b502907845.png)

**What you expected:**

* [ ] If conversion to preferred grade systems is enabled no context prefix should be displayed.

**Comment by scd** [comment]
fixed on simon dev. Will be available next release
