### ISSUE TITLE
Ascent Data: Block (real) Ascents with Future Dates? - Data Quality

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3586]
**What happened?**

It happens that users log (real) ascents with future dates, e.g. get the year wrong. 

This example query gave the following results (see screenshot):
https://www.thecrag.com/climbing/australia/ascents/between/2020+/?sortby=when-climbed,desc

with about 42 ascents in the future.

<img width="896" alt="Screenshot 2020-02-04 at 14 46 28" src="https://user-images.githubusercontent.com/19162952/73785641-4a29b780-475d-11ea-9e60-28df3ece7bd0.png">

Ideally also provide screenshots:

**What you expected:**

 lock the logging of ascents with future dates.

**Comment by quaestor** [comment]
Yes, this should be validated. Especially with contests going on; I think it happened a while back already that ascents that were obviously logged erroneously with future dates in the past were counted towards a contest.

**Comment by lordyavin** [comment]
+1 for input field validation on client side.

![grafik](https://user-images.githubusercontent.com/1528540/75328650-9e1c4d80-587e-11ea-9a6b-d51fd1612ecc.png)

**Comment by Mdemaillard** [comment]
Duplicate of #31  (grave digger award for me)

**Comment by scd** [comment]
Haha that is really funny. It has been a while since we have done a first
hundred issue. It will be a little longer

**Comment by Mdemaillard** [comment]
Duplicate of #2857

**Comment by rouletout** [comment]
Covered in #31, closing here
