### ISSUE TITLE
Ascent listed wrongly / too hard

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3588]
**What happened?**

In this list: https://www.thecrag.com/climbing/world/ascents/with-ascent-gear-style/sport/with-route-grade/FR:9a:9c/of-gender/female/?sortby=by,desc

on position 3 is a 7b (FR) - why is this? I checked the ascent and it is logged with FR 7b - any ideas?

Ideally also provide screenshots:

**What you expected:**

To NOT see this ascent with this advanced search filter.

**Comment by lordyavin** [comment]
Fixed it by updating setting the context to from UK to FR and removing the "FR" suffix from the registered grade field.

**Comment by rouletout** [comment]
Thanks!
