### ISSUE TITLE
Cannot add Route Setter / First Ascent on mobile

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3589]
**What happened?**
Trying to add Route Setter (or First Ascent) for a route on mobile phone. 
When I click on the "climbers" text input field nothing is happening. It seems like this field is not getting the focus (cursor) when clicking. The other fields, eg date, type drop down work fine. 
Sometimes when reloading the form or trying to click often enough I succeed and am eventually able to enter the climber's name. Seems to (not) work sort of random to me. 

I am on Android 10 and Chrome

Example url(s) to reproduce the problem:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?R=%2Fclimbing%2Fspain%2Fvalencia-cuenca-area%2Froute%2F3057171222;select=0;C%3APushReturnURL=%2Fclimbing%2Fspain%2Fvalencia-cuenca-area%2Froute%2F3057171222;C%3AState=18538;D%3AFieldSelection=0;D%3AFieldGroup=area_all;D%3AFieldGroup=route_all;D%3AFieldGroup=annotation_all;C%3AHideNavigation=1;D%3AN=3057171222&P%3A0%3AInformationNetworkID=7539484

Ideally also provide screenshots:
![Screenshot_20200218_204227_com android chrome](https://user-images.githubusercontent.com/30682796/74773848-f9ed4200-5292-11ea-9c46-801867f006f4.jpg)

**What you expected:**
Able to enter climber the first and every time I click the field

**Comment by scd** [comment]
I maybe this is specific to your os or there was some sort of performance
issue with the website. Worked fine on my phone  That field requires call
backs to the website. Can you try at different times and report back?

**Comment by killakalle** [comment]
Attempts:
2020-02-19, 08:20 GMT+1     field not accessible, same behavior as described
2020-02-19, 09:33 GMT+1     field not accessible, same behavior as described
device restart
2020-02-19, 09:38 GMT+1     field not accessible, same behavior as described
2020-02-19, 11:19 GMT+1     field not accessible, same behavior as described
2020-02-19, 15:52 GMT+1     field not accessible, same behavior as described

I believe it's not really related to the time of day. What I found out
meanwhile is that when I go like "tap-tap-tap-tap-tap-tap-tap-..." really
fast on the input field with my finger, it eventually receives the cursor
and then loads the names dropdown. Could be 20+ taps before cursor appears
in the field.

When I get a hold of someone else's mobile phone I can try out if that
issue is reproducible there as well.

**Comment by killakalle** [comment]
@scd 
I've tested on another mobile phone. And on this one it worked without a problem. While on my own it does not. I guess we can close this issue. Though, I'm sad it doesn't work on my phone. ;-)

**Comment by lordyavin** [comment]
Please note the manufacturers, models, OS versions and Browser versions.

**Comment by nicHoch** [comment]
also not working on my phone Samsung Galaxy S8 - Chrome

**Comment by Mdemaillard** [comment]
I had a few similar experiences on Desktop, using Chrome. 
Typical would be during a bulk edit, issue would happen randomly on a single first ascent field of a single route. all other functions working fine. I never tried clicking 16 times on the field. 
Then saving that bulk edit, and reediting the particular climb would allow normal editing on the first try.
I had attributed the issue to a dodgy internet connection.

**Comment by rouletout** [comment]
Works on iOS /iPhone 7 - user experience is not the best with all these edit fields (eg tags). Closing here as this specific issue but is generally covered by the re-work of the edit form.
