### ISSUE TITLE
System Wide Grade Conversion - to do

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3590]
List of new functions and fixes for the System Wide Grade Conversion. The order might be prioritised but is not binding. 

- [x] Mark any converted grade with a visual (border) that indicates that it is converted
- [x] Find a better name for Convert / Unconvert
- [x] https://github.com/theCrag/website/issues/3585
- [x] suppress converting (and labeling) if it is already the desired grade system: 
![image](https://user-images.githubusercontent.com/2226714/75114564-42bc4680-5657-11ea-99c7-3f89c70079a3.png)

- [x] include grade histogram in the conversion 
![image](https://user-images.githubusercontent.com/2226714/75114583-76976c00-5657-11ea-9045-43019d5aace4.png)

- [x] include profile pages headers in the conversion 
![image](https://user-images.githubusercontent.com/2226714/75114596-a21a5680-5657-11ea-84e9-ab90b629b41d.png)

- [x] include notable ascents in the conversion
![image](https://user-images.githubusercontent.com/2226714/75436880-8e236d00-5955-11ea-82dc-a89700257f70.png)

- [ ] possibility to turn the option on/off while browsing the site, i.e. not having to go to the profile settings (I would probably have it off most of the time, but then while browsing some crags that are set in a system I'm not comfortable with, I would like to enable it for a short while and not have to press the "convert" button)

- [x] enable the conversion for all users - leave auto conversion as premium 

- [ ] as more grades will be included in the conversion the convert/unconvert button should go to a more prominent place. "Floating action button"? 
![image](https://user-images.githubusercontent.com/2226714/75114653-3e445d80-5658-11ea-94af-46bc97c8ea7f.png)

- [ ] include grade conversion in gym list view 

- [x] include grade conversion in message stream

- [ ] add mory gearstyles to conversion like "alpine" "top rope" ...
- [x] support multi pitches breakdown for conversion 
![image](https://user-images.githubusercontent.com/2226714/76070770-62c40200-5f95-11ea-9b1e-fa6854c81c99.png)

**Comment by rouletout** [comment]
I add the hardest routes article: https://www.thecrag.com/de/artikel/hardestroutes

**Comment by rouletout** [comment]
Closing this for release 88 as most is done. Create new issues for stuff that comes up.
