### ISSUE TITLE
Annotations not displayed (anymore)

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3594]
**What happened?**

Not sure if this is new, but the title of annotations are not displayed anymore. See for exampe [here](https://www.thecrag.com/climbing/spain/mallorca/las-perxes/area/1003799160), there are 4 annotations, but only an empty bar is displayed. If the annotation has a text body, only the body is displayed.

**Comment by scd** [comment]
I see the annotations. Here is a screenshot

<img width="826" alt="Screen Shot 2020-03-05 at 9 44 59 am" src="https://user-images.githubusercontent.com/373058/75930190-2aa1be00-5ec6-11ea-931f-adb2cb1f330e.png">

Can you provide a screenshot of what you see?

**Comment by birgander2** [comment]
Ok, I found out the reason, this was due some of my browser settings (to be precise a greasemonkey script going wild, which shouldn't be active). Sorry for bothering.
