### ISSUE TITLE
Broken link - Private stream URL

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3596]
**What happened?**
In Account settings, Streams, Private stream url, the listed URL https://www.thecrag.com/stream
 leads to a E503 - Doh! Something has failed!

(The public stream URL does work)

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/60388146/76142252-61b5d200-6074-11ea-95c6-7dc76dddebe8.png)

**What you expected:**
Working link

**Comment by scd** [comment]
Hot fixed.
