### ISSUE TITLE
Add openstreetmap contour map tiles to maps

### ISSUE THREAD

**Issue by scd** [theCrag/website#3597]
From user...

I am recently adding some alpine routes on thecrag. At the same time I am also adding some mountain peaks in openstreetmap and they will also show up in thecrag map if we choose the right layer. But I have found the openstreetmap layer used in thecrag is the basic one which has no contour line.

So, my suggestion is adding the cycle map layer of openstreetmap to thecrag. How do you think of it?

**Comment by lordyavin** [comment]
+100

**Comment by scd** [comment]
This is now hotfixed thanks to a new dev - Burak.

<img width="301" alt="Screen Shot 2020-03-19 at 9 44 57 am" src="https://user-images.githubusercontent.com/373058/77014516-9ad03980-69c6-11ea-8262-6d8dca9dcd26.png">

Please review and close

**Comment by hemind** [comment]
That's awesome! But how about also adding this layer to the edit location page?
![image](https://user-images.githubusercontent.com/7596172/77021961-9127e100-6988-11ea-9850-3be62db8fb03.png)

**Comment by scd** [comment]
It is a different code base which we are replacing. I doubt we will have the capacity to also do it on the edit location page until we replace the code base.

**Comment by Mdemaillard** [comment]
More Dev capacity ! \o/

**Comment by rouletout** [comment]
This is done, clsoing, the Edit Map is a separate issue
