### ISSUE TITLE
Triaging progress

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3599]
- [x] 1st pass done for labeling every issue, mostly placing a "Type" (Bug, enhancement, new feature...) and an "Area" each. 
- [x] information from Dev needed which topic is deprecated. Currently : 
- Trip
- Cite Publication

- [x] need admin help to correct typo in Label "Area : Forum and **messgaging**"
- [x] need admin help to implement new Labels, because missing or bloated (Content editing). My proposals:

- Trip
- List
- Publisher/copyright/publication - currently inflate "Content Editing"
- Sponsor/Stakeholder - currently in "Social"
- Karma - currently in "profile". can also be lumped with "permission"
- Reparent/Merge (to release "content editing")
- Feature:TLC

- [x] 2nd pass to implement the above decisions, 
- [x] 3rd global pass to review all labeling, start weeding out duplicates, test & close already implemented stuff
- [x] 4th pass to eliminate duplicates & improve cross-link 

Feel free to point out if i misinterpreted some labeling (Internal ?)

- [x] propose priorities for closing. Possible criteria: common support request. Mostly done. Idea: 
- select 1 "New feature" or Major work required.
- select 1 or 2 "clusters" of issues : identify areas where combined medium effort could close multiple issues
- highlight low-hanging fruits, that should be possible to close with minimum effort.

**Comment by scd** [comment]
Trip is indefinitely deprecated. We need to get more dev resources to support that kind of feature. I would love to, but I cannot see it happening with our current resources.

List is on our medium term target of work. It is a rebranding of circuit and will be used to replace target ascents.

Cite Publication is in a holding pattern. We have not made final decisions.

**Comment by scd** [comment]
@Mdemaillard I have separated Trip and List as two new labels, otherwise I have made the updates you wanted. Please review.

**Comment by Mdemaillard** [comment]
Is the app deprecated, or simply on long term goal for the moment ?

**Comment by scd** [comment]
We are actively trying to get the app going

**Comment by Mdemaillard** [comment]
I would like the following label modifications please:
- [ ] a label for the App, 
- [ ] 8: Gym should be rename as Area, rather than type.
- [ ] 8: Supporter should be rename as Area, rather than type. 
There already is a label for "10 common support issue" which should be fine covering both if the interpretation is "raised by"

**Comment by scd** [comment]
@Mdemaillard new labels done

**Comment by Mdemaillard** [comment]
The most used label is currently Enhancement, with 449 issues.
Would it be of value to Devs to split it between the following 2 ?
- Enhancement = Functional incremental improvement
- Polishing = improvement in display, ease of use, help text, consistency, reducing redundancy
If yes, please create "5: polishing" (or better named)

**Comment by scd** [comment]
Polishing added

**Comment by lordyavin** [comment]
Wow, @Mdemaillard want to thank you very much for the great effort to get through all of the backlog!

**Comment by Mdemaillard** [comment]
closing as established.
