### ISSUE TITLE
Forum navigation bug when changing page

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3603]
**What happened?**
When navigating through multiple pages on a forum, the first navigation works (appends a ?threadPage=x to url)
A second navigation using the page buttons does not work, as it appends another ?threadPage=y instead of replacing x to y in the url.

Example url(s) to reproduce the problem:
https://www.thecrag.com/forum/1201457451?threadPage=2?threadPage=3

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/60388146/76313871-772e3480-62de-11ea-8630-d88f65f012a9.png)

Modifying manually the url does work in loading whatever page.

**What you expected:**
Usable navigation

**Comment by Mdemaillard** [comment]
Merging from duplicate:

Hey Again :)

Noticed another bug. When you select descendants on the forum, hitting a different page (ie 2) breaks the descendants filter because the page is directly appended with the query string separator

Repro:

Go to
https://www.thecrag.com/climbing/australia/new-south-wales-and-act/forum?nodeFilter=descendants

Click second page, end up on:
https://www.thecrag.com/climbing/australia/new-south-wales-and-act/forum?nodeFilter=descendants?threadPage=2

Note ?threadPage=2, should be concatenated with & instead. Manually changing the URL fixes it.

Thanks :)

**Comment by Mdemaillard** [comment]
+1 from  new user

**Comment by georg-d** [comment]
+1. Especially inconvenient in inherently long forums like e.g. https://www.thecrag.com/forum/release with 9 pages.

**Comment by scd** [comment]
Fixed for next release.
