### ISSUE TITLE
Improve help page on repeated ascents

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3605]
Modify Tick Types help page 

Red point 
 I led this route, without falling or resting, but not on my first attempt
**(or on a repeated ascent)**

Pink point
 I led this sport route, without falling or resting, but not on my first attempt **(or on a repeated ascent)**, using pre-placed gear.  If you do this on a trad route then it will be considered a sport route. For harder sport routes it has generally become acceptable to also call this a red point.

**Comment by Mdemaillard** [comment]
"not on my first attempt" is for me already synonymous with "on any later attempt, including repeats", but i saw the forum discussion:
https://www.thecrag.com/discussion/3131974173/lead-repeat
Maybe "this include any lead repeat sends"

**Comment by gui84** [comment]
Maybe "this include any lead repeat sends"
+1

**Comment by rouletout** [comment]
Included in new help after next release.
