### ISSUE TITLE
World Forum listed twice in drop down (GUI issue)

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#3606]
**What happened?**
The drop down has 'World Forum' listed twice. 
They both work, so it's just a display issue. 

Example url(s) to reproduce the problem:
Any seem to do it. 
https://www.thecrag.com/climbing/australia/blue-mountains/echo-point/route/15320683

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/22091505/76374525-96d56380-6397-11ea-8d60-a38fe70ac091.png)

**What you expected:**
Only list World Forum once

**Comment by Mdemaillard** [comment]
I only see it once:
![image](https://user-images.githubusercontent.com/60388146/76384708-5dd1ca80-6368-11ea-953c-27adfbd00a6f.png)

**Comment by DaneEvans** [comment]
Agreed, doesn't seem to be happening now on the same computer and browser. 

Win 10, chrome, I'd spent some time clicking around the site. 
Maybe a pre-cached result or something?

**Comment by rouletout** [comment]
gone, closing
