### ISSUE TITLE
World discussions show up at lower levels

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#3607]
**What happened?**
If you click into a forum (including country, state and route levels) then it defaults to the 'All' option, which shows Parent discussions. 

Example url(s) to reproduce the problem:
Any seem to do it. 
https://www.thecrag.com/climbing/australia/blue-mountains/echo-point/route/15320683/forum
https://www.thecrag.com/climbing/australia/forum

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/22091505/76374989-cf297180-6398-11ea-8827-b34a1a28b013.png)

**What you expected:**
- A default to Descendents/Direct maybe the n+1 level parent / first region at most 
- Not to see a bunch of irrelevant clutter from the 'world' level at  a single routes discussion page

**Comment by scd** [comment]
hotfixed
