### ISSUE TITLE
Typos in Help

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3610]
Multiple typos. (How can i correct these myself ?)

Example url(s) to reproduce the problem:
https://www.thecrag.com/article/SensitiveCrags

Guidelines
- [x] the only guide available is the official**LY** published one
- [x] strong reasons to not do this. -->  strong reasons **not to** do this.
- [x] if content is actually removed, then inevitabl**Y** someone later thinks
- [x] has organised an accepted line of responsibil**I**ty then 

INFORMATION RESTRICTIONS
- [x] so we have developmed capability --> developped

REMOVING DESCRIPTIONS
- [x] therefore we have the capabiltiy to explicitly restict -->therefore we have the capabil**it**y to explicitly rest**r**ict

RENAMING AREAS
- [x] is counter productive accept for cases --> except

DELETING AREAS
- [x] Tecnically --> Technically 
- [x] Note that if a crag is a dup then  --> duplicate

DISABLE PDF DOWNLOADS
- [x] you will not need to download --> you will not be able to download

How to make changes

- [x] please send us an email requestion permissions -->please send us an email requesting permissions

**Comment by scd** [comment]
@Mdemaillard I have made the changes. They are all in our english text of our translation db. Please check.

**Comment by Mdemaillard** [comment]
Thanks you. 2 more before closing this:

capabiltiy  --> capability

It is possible to rename an area to something like 'Cliff name - CLOSED'. It makes it way obvious that it is closed, but in the long term we would like to create a tag for this. 
-->
Instead of renaming a cliff 'cliff name - CLOSED', add the tag "closed" to the access field. This will not only display closed in the name, but add warning in multiple places, including the map.

**Comment by Mdemaillard** [comment]
In Help: ticktypes

All free with rest : I climbed this route all free but had a rest **of** fall.
or a

**Comment by scd** [comment]
@Mdemaillard can you change your bullet points to a check list and tick what is done so we can easily review what is outstanding.

**Comment by Mdemaillard** [comment]
@scd changed to bullets

**Comment by gui84** [comment]
- [ ] In Grades on theCrag help page
change 

"Hong Kong uses UK technical system for boulder routes."
-->
"Hong Kong uses V-Scale for boulder routes."

**Comment by Mdemaillard** [comment]
Done, @gui84 you can tick the box
