### ISSUE TITLE
Add Information Box does not open new Add/Edit Area Form

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3614]
**What happened?**

If an area has no information, a yellow info box is shown that has the call to action "Add information". This button does not open the Add & Edit Area form with structured tags etc. but a different version of the form.

<img width="749" alt="Screenshot 2020-03-14 at 17 24 08" src="https://user-images.githubusercontent.com/19162952/76692216-f7bf9e80-6618-11ea-9df9-cc92296e44b0.png">

**What you expected:**

That the complete Add & Edit Area form opens in order to provide a consistent user experience and ensure that as much info is collected as possible.

**Comment by Mdemaillard** [comment]
duplicate of #3280. closing here

**Comment by rouletout** [comment]
This is not closed, the "wrong" form opens - see screenshot:

<img width="1111" alt="Screenshot 2020-03-20 at 13 21 08" src="https://user-images.githubusercontent.com/19162952/77199014-ba8e5d00-6aad-11ea-9fd4-fcf0218c1d54.png">

**Comment by Mdemaillard** [comment]
correct, but it still is a fully duplicate bug report ?

**Comment by rouletout** [comment]
This might be - but I saw you closing the duplicate too, no?

**Comment by Mdemaillard** [comment]
nope, 3280 is untouched opened. not a problem, both are yours, you can choose which one you prefer to close

**Comment by rouletout** [comment]
Resolved, closing
