### ISSUE TITLE
Water Ice Grades above WI8+ not supported

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3617]
**What happened?**

Elite climbers has raised the bar in climbing water ice since a while. New milestones were established this winter season and before:

* [Mission to Mars (WI13)](https://www.thecrag.com/climbing/canada/british-columbia/route/3120440241)
* [Interstellar Spice (WI12)](https://www.thecrag.com/climbing/canada/british-columbia/route/3120443112)

See also the other routes at [Helmcken Falls](https://www.thecrag.com/climbing/canada/british-columbia/area/3120434679).

![grafik](https://user-images.githubusercontent.com/1528540/76735470-45492200-6765-11ea-9e3c-26afc4c459e8.png)

Unfortunately WI grades above 8+ are not supported and not stored by the system if entering them as registered grade.

**What you expected:**

* [ ] Support WI grades above 8+

**Comment by scd** [comment]
I have implement up to WI14+ for next release

**Comment by scd** [comment]
I am not sure about Alpine ice

<img width="599" alt="Screen Shot 2020-11-14 at 1 01 27 pm" src="https://user-images.githubusercontent.com/373058/99136749-f26c9500-267a-11eb-8efc-6907de52bccd.png">

**Comment by rouletout** [comment]
Fixed with release 88
