### ISSUE TITLE
CPR graph bug: Privat profiles

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#3622]
**What happened?**
There are two, most likely, bugs regarding the CPR graph:

1. When a profile is set to "Private" of a friend (in my case it was @moxifloxi) then I see everything of her profile, except the CPR graph. I suppose this shouldn't be the case.

_2. I ticked some routes on the 1.April (2nd quartal) from some days in the past (25.03-28.03), but in my CPR graph this ascents are shown in the 2nd quartal instead the 1st. Maybe this will fix itself after some time, but this is kinda irritating._

**Comment by scd** [comment]
It is easier if different issues are separated. @Mdemaillard can you please separate these issues once I get a chance to review one of the ascents.

@Drazhar can you send a URL of an ascent that you think should be in Q1. There is something I want to check.

**Comment by Drazhar** [comment]
I just checked the accents and saw that it was an error from my side... Instead of 27.03 the date os set to the 27.04... I think the issue was that I used the little arrows in google chrome next to the ascent date to go 5 days into the past. Strangely, it seems it only changed the days and not the month.

So I can edit this issue away and only leave the privacy issue.

**Comment by scd** [comment]
There is a log of noise in this issue so I am closing. I have done a bit of investigation and the only thing I can see that is an issue is that you cannot see CPR graphs of a private profile that you have permissions to see. I have logged a separate issue for this.

https://github.com/theCrag/website/issues/3828
