### ISSUE TITLE
Grade contributions not interpreted correctly (multi-pitch) / data cleaning

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3624]
**What happened?**

In several areas we have grade contributions of the type 3p(6a, 6b, 7a) which result in an empty first pitch grade and the 3rd pitch grade being lost.

An example is here (I left it on purpose): https://www.thecrag.com/climbing/italy/spiaggia-delle-lucertole/route/15967303

Ideally also provide screenshots:

<img width="702" alt="Screenshot 2020-04-01 at 15 59 49" src="https://user-images.githubusercontent.com/19162952/78190890-2b306480-7432-11ea-82bf-9ebcd410e0f4.png">

**What you expected:**

A clean-up of these data using a script as manual edits are super time consuming (open route, update grade contribution, ....). All that needs to be done is to delete the e.g. 3p and parantheses.

**Comment by Mdemaillard** [comment]
I assume this will be mostly limited to input from publications ?

**Comment by scd** [comment]
Yes, early days inputs

**Comment by rouletout** [comment]
Here another set of routes: https://www.thecrag.com/climbing/italy/pietramurata/transatlantico

**Comment by Mdemaillard** [comment]
oh wow. this is hidden deep. only hint is the first pitch with no grade, then it is hidden both on page view and edit route. only visible by modifying the grade contribution...

**Comment by rouletout** [comment]
More here: https://www.thecrag.com/climbing/italy/arco/mandrea-i-pilastri-povero-and-afgano

**Comment by gui84** [comment]
@rouletout How did you get this "Imput grade contributions" frame ?

**Comment by rouletout** [comment]
@gui84 go on the route page, click the 3 dots next to edit route and select update or edit grade contribution. This is admin only.

<img width="324" alt="Screenshot 2020-04-15 at 18 30 56" src="https://user-images.githubusercontent.com/19162952/79401834-690bad80-7f47-11ea-967b-3c6d31f0c97c.png">

**Comment by gui84** [comment]
I have admin rights on this area but I didn't get this "route grade" option.

**Comment by Mdemaillard** [comment]
You see the admin frame on your profile picture, but did you select your
admin role too? I had same "problem". Log out, then log in again. You'll
get a rôle selection screen.

**Comment by nicHoch** [comment]
fixed with script
