### ISSUE TITLE
Mobile - No expanded menus

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3627]
On Firefox, Android 11

It's not possible to expand menus (Forum, Help ...)

When you click on Help, you get this page :
![Screenshot_20200409-074313](https://user-images.githubusercontent.com/34114303/78843658-080b4380-7a36-11ea-8d83-910615dfe806.png)

Also it could be useful to have a summary (with links) of help pages on this page.

**Comment by rouletout** [comment]
+1 - this is a great idea and actually was always theintention but got lost. That this shows the Contact Us page was just a quick  fix to put something there. I'll write up an "article" with a high-level Help-Index structure.

**Comment by rouletout** [comment]
Help menu was introduced with top level page, other issue is logged elsewhere, closing
