### ISSUE TITLE
Implement Date Check on Ascent import

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3630]
**What happened?**
We routinely have users that import their ascents with the current date. I assume often this is the case because they don't realize that they have to pick the date format from the drop down (I did that myself wrong for community accounts). Can we implement an alert that says "if you continue your ascents will be imported with the current date" or similar?
It also messes up our Seasonality and other stats btw.

Note: the 8a export uses the default date format of our import so the user has to select nothing and it will work.

Ideally also provide screenshots:
it happened with Laura Rugora (community profile: https://www.thecrag.com/climber/laura2001) 
and bronco; https://www.thecrag.com/climber/bronco

**What you expected:**

* [ ] Make sure if there is no date the current date is not assigned as ascent date.

**Comment by Mdemaillard** [comment]
from @brendanheywood 
Adding extra help text won't help, we need to just actually attempt to parse the dates and then show them what is happening and ask them if it was interpreted correctly.

In any given file all the dates will almost certainly have the same format. We should be able to just throw the dates at the date parse and let it figure it out. The only common point of ambiguity is american dates which swap the day of month and month, but for any large batch import we'll have a heap of dates to test, so as soon as we parse a date with has a month of the 13th to the 31st then we know the format is the other way around and then we can re-do the whole batch with the swapped month and day and retest it. So in most cases we should be able to detect the format automatically with no input at all.

Worst case, we should never import anything with todays date. It should have no date and be a historic tick with no date. Only it's submitted date will be today.

**Comment by nicHoch** [comment]
implemented as discussed:

auto detect the date format on the majority of all provides dates in the import file.
Reject import files with date errors > 5%
default date if error: no date

**Comment by nicHoch** [comment]
available with next release
