### ISSUE TITLE
Map pan should rewrite top menu context

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3641]
**What happened?**
Panning the map away doesnt update navigation.

**What you expected:**

* [ ] context should update and navigate as the map moves.

**Comment by rouletout** [comment]
@Mdemaillard I'm not sure I get what you mean - can you please provide a screenshot and / or URL's?

**Comment by Mdemaillard** [comment]
@rouletout that point was a transfer from either a mail or message i believe.
The expectation was a dynamic recognition of the closest area viewable in the map port - that would be used to update the currently opened node.
e.g. : navigating the index via map movement only, without clicking on the node and actively using "open guide"

It cannot be the default user experience, since i expect lots of users regularly select a node, then move the map around but don't want to change the selected nod.

It could possibly be a kind of "explore map" alternative mode, but i don't see the added value since it is so easy to open any visible node from the map with 2 clicks. Plus i suspect it would require heavy processing and increased bandwidth if nodes keep being loaded during map navigation.

I would close.

**Comment by rouletout** [comment]
Got it thanks - I'm closing this.
