### ISSUE TITLE
target routes in activity

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3649]
**What happened?**

When you tick a route as a target, activity indicates "logged an ascent from the past".
<img width="608" alt="Capture d’écran 2020-04-19 à 07 50 33" src="https://user-images.githubusercontent.com/34114303/79674553-c8531180-8216-11ea-963d-836f96f52800.png">

**What you expected:**

- activity indicates "targets an ascent". 

- target routes doesn't count in routes ascents.

**Comment by scd** [comment]
We are not going to fix this directly. Rather we are going to remove target ascents and replace them with  personal route lists so you can set you multiple aspirational goals.

**Comment by Mdemaillard** [comment]
Duplicate of #2836

**Comment by rouletout** [comment]
Closing thgis as this will be replaced by "wishlist" rather sooner than later
