### ISSUE TITLE
Grades: E-Grades not displayed correctly for multi-pitch routes

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3651]
**What happened?**

E.g. here https://www.thecrag.com/climbing/united-kingdom/orkney-isles/route/3227380218 the pitch grades were entered as E-Grade but are parsed as French and thus wrong!

<img width="875" alt="Screenshot 2020-04-20 at 10 07 58" src="https://user-images.githubusercontent.com/19162952/79773564-d96f5180-82ee-11ea-92e1-ee17b79f64ea.png">

Ideally also provide screenshots:

**What you expected:**

Correct display of individual pitch grades.

**Comment by Mdemaillard** [comment]
Hum, the gradea re douvle entered for each pitch UK & FR. Still should choose to display UK as the context is UK.

**Comment by lordyavin** [comment]
https://www.thecrag.com/climbing/united-kingdom/llanberis-area/dinorwic-quarries/route/2264715702

**Comment by scd** [comment]
This issue is because we choose to display CPR assigned components of the grade. However this may not have been an ideal decision. I have expanded to show the full interpreted pitch grade. In dev.

![Uploading Screen Shot 2020-11-10 at 5.00.40 pm.png…]()

**Comment by rouletout** [comment]
Fixed with release 88
