### ISSUE TITLE
Assigned grade not displayed 

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#3655]
**What happened?**
Sometimes, the assigned grade is not displayed in route listing and details, instead an older user contribution is shown. [Example here]:(https://www.thecrag.com/climbing/germany/oberbayern/route/252582177)
8,8+ is shown instead of the new 7,8+. An editor cannot ressolve this wrong display. 

Strangely, this does not happen always. The [neighboring route](
https://www.thecrag.com/climbing/germany/oberbayern/route/252579309) has similar entries, but is displayed correctly.

I think there was a similar issue when merging routes, but I cannot find it here.

**What you expected:**

That the assigned grade is shown.

**Comment by Mdemaillard** [comment]
similar to #3587

**Comment by rouletout** [comment]
To me that looks ok now, do i miss something?

**Comment by birgander2** [comment]
Seems so. Maybe still happens when merging routes, but I don't have an example. Let's close, can be reopened if it happens again somewhere.
