### ISSUE TITLE
Photo stream event wrong wording

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3657]
**What happened?**

I have removed the webcover for a user here: https://www.thecrag.com/climbing/australia/arapiles/kitten-wall-area/area/11972473and disabled the photo (https://www.thecrag.com/photo/1343094918).

The stream event states "I uploaded a photo" - see screenshot. Stream event: https://www.thecrag.com/event/3247988226

<img width="653" alt="Screenshot 2020-04-29 at 07 56 37" src="https://user-images.githubusercontent.com/19162952/80604786-63a26e80-89ef-11ea-8f77-8171998ef72e.png">

Ideally also provide screenshots:

**What you expected:**

Correct wording - removing a web-cover should be stated as such.

**Comment by Mdemaillard** [comment]
to tackle with #3370

**Comment by rouletout** [comment]
fixed, closing
