### ISSUE TITLE
Boulder field should have same/similar fields as crag. 

### ISSUE THREAD

**Issue by FredrikEckardt** [theCrag/website#3659]
Suggestion for improvement:

It should be possible to add (edit) same or similar information for a boulder fields as for a crag. At least the following fields: 

- Access issues (highest priority)
- Where to stay 
- Ethic

**Comment by Mdemaillard** [comment]
from https://www.thecrag.com/discussion/3245977665/access-info-for-a-boulder-field

**Comment by scd** [comment]
I have done this in my dev system. It will be ready after next release.

<img width="1193" alt="Screen Shot 2021-01-18 at 1 25 50 pm" src="https://user-images.githubusercontent.com/373058/104865740-e362d580-5990-11eb-9eb9-6582753b5735.png">

**Comment by FredrikEckardt** [comment]
Hi Simon,

Looks great.
Thank you!


/Fredrik

**Comment by killakalle** [comment]
@scd 
To me this looks still unchanged / buggy. See bulk edit
![image](https://user-images.githubusercontent.com/30682796/105410402-2becee00-5c32-11eb-9ef8-7d736ab37b00.png)

Another example, Lliria is already a boulder field. When I click on Edit, the additional fields disappear in an instant:
https://www.thecrag.com/es/escalar/spain/valencia/area/3841337841

![image](https://user-images.githubusercontent.com/30682796/105410907-f1378580-5c32-11eb-8267-0fa327884199.png)

**Comment by killakalle** [comment]
Oh wait, just reading that it should be there after the next release. I guess that hasn't happened, yet, then. Just disregard my comment if this is still scheduled for release.

**Comment by scd** [comment]
Only updated in dev. Please check again after next release
