### ISSUE TITLE
Photo topo icons missing in a menu when editing photo topo

### ISSUE THREAD

**Issue by scd** [theCrag/website#3660]
When editing a photo topo the icons should be in the menu for selecting a topo point type

<img width="182" alt="Screen Shot 2020-05-04 at 5 48 30 pm" src="https://user-images.githubusercontent.com/373058/80946259-fba9b900-8e30-11ea-8c50-7b8dfa4dc5b3.png">

**Comment by Mdemaillard** [comment]
they are in on desktop now (and it isnt new).
![image](https://user-images.githubusercontent.com/60388146/81788292-988be680-9502-11ea-8d44-1c94187b0bd9.png)
they load a few seconds after the menu appear on my side (2s tops)

**Comment by dtweedle** [comment]
@Mdemaillard I believe the issue relates to the select menu that appears in the blue palette window, If you look closely at the screenshot from @scd you'll notice that the bottom 3 actions from the select list are missing when compared to the menu from your image, they are in fact two separate dropdowns. The one with the missing images is the browsers native `<select>` menu which only supports images in some versions of firefox. Whereas the in context editor you screenshotted is a custom one that is generated in the photo-topo lib.

I'm part way through implementing an update which will replace the `<select>` menu which doesn't support images.
