### ISSUE TITLE
Move doesn't work

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3666]
**What happened?**

I tried to move a route from one sector to another as well as a boulder from one field to another - both times nothing happens - no error, no move, no nothing - the page is just displayed as nothing ever happened.

This was using Spanish and German as profile language. With English as profile language it works.

Ideally also provide screenshots:

**What you expected:**

That the move operation works in all languages.

**Comment by scd** [comment]
I have hot fixed this. Please test and close if it works

**Comment by Mdemaillard** [comment]
Tested in FR and DE as working, for both single route and area. closing.
