### ISSUE TITLE
PDFs are completely broken

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3667]
**What happened?**

[Gabriele G](https://www.thecrag.com/climber/grattino) [wrote on the 10.05.2020](https://www.thecrag.com/discussion/3274594647/issues-with-pdf-guides):

> In the last few weeks, pdf guides seem not to work for me. I tried to experiment a bit and I get two issues consistently:
>
> 1. the pdf is generated with delays of even more than 24 hours.
> 2. the comes up weird: the pictures are not the topos they should be.
>
> Let me know if there is any more info/experimentation I should do that could help solving the issue.

**What you expected:**

* [ ] Working generation of PDF guides
* [ ] Working generation of custom PDF guides

**Comment by lordyavin** [comment]
@scd  replied:

> PDFs are completely broken at the moment. I have spend half a day trying to work out why, but no joy.
> 
> As best I can see is some third party software is no longer working properly in our operating system. It may not be even possible to fix this in the existing server.
> 
> We are in the process of upgrading operating systems and cutting over to a new server. It seems to work fine in the new server and operating system.
> 
> I think the best thing to do is wait and cross your fingers that it works after we cut over.

**Comment by Mdemaillard** [comment]
Both instant and personalized working now after server move-over.

**Comment by lordyavin** [comment]
Generation works, but link in Email does not open the PDF in the correct app on mobile.

**Comment by Mdemaillard** [comment]
Both links in the mail work for me both on desktop and mobile - android ? what does it does on your side ?
