### ISSUE TITLE
add specific options/icons/poi for boulders in topo tool

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3685]
As some boulders are very specific defined (eliminations) where exactly to start where to finish ...
it would be good to add more specific boulder point types. 

Most of them should not define where the routes (line) is seen but should be more floating around (next to the line). 

As a full block with many "marks" might become very  unclear. The additional points should only be visible if the route is selected.

All lines
![image](https://user-images.githubusercontent.com/2226714/82810117-f4088d80-9e8d-11ea-99b0-be8e7f28a5b8.png)

One selected:

![image](https://user-images.githubusercontent.com/2226714/82810372-94f74880-9e8e-11ea-8336-0df29b67ba92.png)

The icons for the point types are open for discussion. In this example Blue stands for start red for "do not use". 

see also: #1614 

As the list of point types might become very long we could think about different editor modes (perspectives) for different gear style of routes (boulder, trad, sport ...).

**Comment by Mdemaillard** [comment]
Can you check how much overlap this is with #515 ?
(If appropriate you can paste that post there, and ill close here as duplicate, but im happy to keep both if required)

**Comment by nicHoch** [comment]
kind of duplicate / extension of #515
