### ISSUE TITLE
8a.nu import not working, should be fixed ASAP (;

### ISSUE THREAD

**Issue by FreddieChopin** [theCrag/website#3688]
Probably most people know the situation, but if not, here's a brief summary. Last week 8a.nu finally implemented their update which was in the works for 3-5 years. Overwhelming majority of 8a.nu users are extremely negative about the changes, because the update removed A LOT of useful features (following friends, following crags, advanced search options) and introduced A LOT of problems (missing ascents, duplicate ascents, inability to add new routes and so on). The update of their website obviously breaks automatic import into thecrag.

With such huge dissatisfaction of the 8a.nu users, there's a great possibility to "win" them and convince them to come to thecrag. But this will not happen if they cannot easily import their ascents other than manually entering them one-by-one. I even spoke with a friend of mine who has logged over 3000 ascents on 8a.nu and said to me exactly that - that he will have to deal with 8a.nu because transferring this database to a different platform manually is just too much work.

I'm not the one to say what the priorities are, but I think that - if possible - this should be done really quick, as it's just one of those very unique opportunities that doesn't happen too often.

**Comment by Mdemaillard** [comment]
Thank you Freddie, we are aware that the functionality broke during their release, and have taken the task to try and make it functional again.
I don't believe their current interface allows anymore for an export at the moment, and realistically it won't be the first thing they try & fix.

Also i might add, completely independently from thecrag, the 8a.nu current situation is not one i wish anybody managing a website and a community, even Lars.

I actually just had an idea of looking if the internet archive / way back machine allows using the old export function... that or something similar might be worth a try.

**Comment by FreddieChopin** [comment]
Disclaimer - I'm an embedded programmer myself and I speak mostly C++, so forgive me if my question is stupid (;

Couldn't thecrag just implement some kind of data scraping directly from the rendered website? It would switch user's logbook to show all years, select sorting in the fashion which would be most convenient for import, make sure everything is displayed (as when the user scrolls to the bottom and clicks "Load all") and then just harvest the data directly from the table? If I would like to export my data from 8a.nu I would probably do it like this - just copy the table from the generated HTML and transform it with a script to whatever I want.

**Comment by Mdemaillard** [comment]
Hum, while probably technically possible, that is not something i would personally condemn without serious consideration on liability, copyright and so on.

I mean, if i was a 8a user right now, i would fight hard to get access to my data, as is my right (hopefully not denied by the Ts and Cs of the website i chose to use). That is one thing.

Now from a concurrent website going and creating a scraping mechanism to obviously poach users, that is a very different thing.

Possibly if sufficient 8a users see the need for it and cannot get access to their data in a timely manner, that is a 3rd thing again.

**Comment by FreddieChopin** [comment]
Well, I know that this is a bit of a grey area, but I'm not suggesting you mass-harvest all the data from 8a.nu, just the data of single user and only on explicit request from that user.

Another option - instead of having "import from 8a.nu" functionality, you could implement an "export 8a.nu data to a CSV file", which would not be stored on thecrag, just given to the user for download. Whatever the user does with that (maybe decides to import it into thecrag?) is a completely different thing. Want to make it even more legal - post a python script that does this, or some other script which could be easily turned into an online service by anyone (other than you) and given to users.

Also please note that ascent list on user profile is publicly available, without logging in, so I don't think any strange legal spells can prevent anyone from taking it and doing whatever they want with it.

**Comment by rouletout** [comment]
@FreddieChopin thanks also from my side for raising this here. As Marc explained, the update has also broken the export functionality. We are evaluating what can be done technically. In the meantime, please make your friends and others aware that it is their legal right to obtain THEIR dat from 8a.nu (or any other platform), at least if they are European. According to GDPR (General Data Protection Rules) a user can request his data and the provider must either offer a function to export them or provide them to the user. I'll send you a PM on that.

**Comment by Mdemaillard** [comment]
Export functionality has been fixed, and provides a csv download to be used at the discretion of the data's owner. Closed.
