### ISSUE TITLE
Wrong GPS coordinate impact Map display

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3689]
These two German boulder problems are located in Africa :
https://www.thecrag.com/climbing/germany/pfaelzerwald/route/963675240
https://www.thecrag.com/climbing/germany/pfaelzerwald/route/3308041791

This affect the whole area 
https://www.thecrag.com/climbing/germany/pfaelzerwald/area/963081012/

**Comment by Mdemaillard** [comment]
hum, known type of issue. For every node, the system calculates a behind the scene Map Boundary box to display every located elements in map display (drawn areas location AND GPS coordinates).

When a really wrong GPS value is input, it stretches then the map display of all ancestor nodes in the index. This is really easy to do if forgetting the "-" character for longitude in south hemisphere for example.

Simply deleting the wrong GPS values is not working (and a known bug). Modifying them to a approx value does work, but requires time for the boundary box and map display to be reupdated.

i have taken the following steps to recover:
- from the area node, edit location -> hover over map inside the area -> grab approximate GPS values from the dynamic display at the bottom right of the map -> cancel location edit
- edit the 2 routes and input approximate GPS location, and text to notify that the values are not precise
- refresh the cache for the area in question (unfortunately doesnt refresh the map component)

**Comment by scd** [comment]
I have written a SQL statement which works out outliers. There is still a
bit of work to integrate it, but it is in my to do list.

**Comment by Mdemaillard** [comment]
the bbox & visible map accessible from the specific boulders is now corrected.
the issue affecting the ancestors is not, as there is to my knowledge no manual way to refresh / recalculate / update the affected bbox

**Comment by Mdemaillard** [comment]
also affected 
origin ? didnt spend the time to look down further than:
https://www.thecrag.com/climbing/australia/north-shore
rolling up to australia

**Comment by Mdemaillard** [comment]
Correction of the single route level coordinate now automatically resize all ancestors Bboxes :-) Problem above in Australia solved.

Seems not to work on the german issue. 
- All 3 routes in the area had wrong corrdinates (8 ,0)
- The wrong coords were then deleted from the route input form. That did NOT update the location value visible on the route index.
- I input now approximate coords on all 3 routes. The area BBox is not immediately update, as ws the case on the Australian issue.

**Comment by Mdemaillard** [comment]
update on the german topic: 

- all routes of all boulders in Kalmit had wrong coordinates displaying at route level, even if not present (maybe erased ?) in the coordinate edit field

- A single batch edit per boulder, with entry of approximate coordinates in a single route updates the coordinates of all routes in the boulder, visible in route page. (still not impacting the coordinates input in the edit field for all additional routes in the boulder). This also gives the boulder a "partially located" status, and update the map of the specific boulder.

- After all boulders received that "correction", Kalmit map was still not reseting. A slight edit of Kalmits boundary shape triggered a recalculation of its map display box ; and also updated its ancestors.

-> problem manually solved for Kalmit

**Comment by rouletout** [comment]
Problem fixed, a script is in place to identify outliers but requires manual fix, closing
