### ISSUE TITLE
Ascent Bulk Import: Very long comment gets truncated and effects ascent style 

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3694]
**What happened?**
When importing this example logbook 

[logbook_david.zip](https://github.com/theCrag/website/files/4733949/logbook_david.zip)

the comment of the first line (ascent of Crazy Belly) is very long. 
the csv reading works well as the full comment is shown at the matching process:

![image](https://user-images.githubusercontent.com/2226714/83838149-b4953900-a6f8-11ea-8bd7-1794f3524e7b.png)

the correct detected style is : redpoint

after creation of the ascent the ascents looks as follow:

![image](https://user-images.githubusercontent.com/2226714/83838280-02aa3c80-a6f9-11ea-9fa5-d8f1bd6a23e2.png)

the comment is truncated but the style is correct "redpoint".

If i click edit ascents the comment is still truncated but the ascent type changed to "onsight":

![image](https://user-images.githubusercontent.com/2226714/83838385-53ba3080-a6f9-11ea-8ebc-014afc5b6a26.png)

**What you expected:**

* [ ] not truncated comment
* [ ] correct ascent style while editing

**Comment by davidheerema** [comment]
Note, I have since modified the tick in my logbook to have the correct tick type so you'll want to reproduce the issue to see it first hand.

**Comment by nicHoch** [comment]
fixed with next release
