### ISSUE TITLE
Polish grades conversion are off at the lower end when compared to French

### ISSUE THREAD

**Issue by FreddieChopin** [theCrag/website#3695]
The table which compares Polish rock climbing grades is off for climbs at the lower end. All grades from (and including) Polish VI.3 - converted to French 7a - seem to be more-or-less the same as the "universal conversions" used in Poland. However for lower grades the situation is different. For years Polish VI was converted to French 6a, however theCrag's table converts that to French 5c.

Here's what the converter produces and what I would propose:

Polish | French (by theCrag) | French (proposal)
-- | -- | --
VI | 5c | 6a
VI+ | 6a | 6a+
VI.1 | 6a+ | 6b
VI.1+ | 6b | 6b+
VI.2 | 6b+ | 6c
VI.2+ | 6c+ | 6c+
VI.3 | 7a | 7a

Couple of references which are 1:1 with each other on the lower end (small differences around 7c and above), so I would say that the standard is pretty consistent:

- "Jura Północna", G. Rettinger, 2020
![rettinger](https://user-images.githubusercontent.com/1139038/83893309-1339d180-a750-11ea-880b-2c49dab0034a.jpeg)

- "Jura 2", P. Haciski, 2016
![haciski](https://user-images.githubusercontent.com/1139038/83893361-23ea4780-a750-11ea-9062-c40529266a3b.jpeg)

- "Góry Sokole", W.T. Wajda, A. Sobczyk, 2007
![sokoliki](https://user-images.githubusercontent.com/1139038/83893571-66ac1f80-a750-11ea-89fa-f73aa7f614c7.jpeg)

- "Rudawy Janowickie", K. Burzawa, A. Sobczyk, 2006
![rudawy](https://user-images.githubusercontent.com/1139038/83893633-7c214980-a750-11ea-99a2-3369880ee2e9.jpeg)

- "Podzamcze", M. Czubak, R. Klećko, 2009
![czubak](https://user-images.githubusercontent.com/1139038/83893471-44b29d00-a750-11ea-9620-dcd7c320755e.jpeg)

- [page on Wikipedia about Polish grading system](https://pl.wikipedia.org/wiki/Skala_trudno%C5%9Bci_dr%C3%B3g_skalnych)

If you need more, I'm sure I can find some more sources.

BTW - there are two slash-grades  which are sort-of-a-standard in Poland, most likely due to the fact that they translate to full Franch grades (; These would be:
- VI.4/4+ (not so common) - 7b+
- VI.5+/6 (very common) - 8a+

**Comment by rouletout** [comment]
We might start working on this sooner than later, any updates?

**Comment by FreddieChopin** [comment]
> any updates?

I'm not sure whether this is a question for me or for the development team (;

**Comment by rouletout** [comment]
@FreddieChopin sorry, yes for you. Just want to make sure the above is the latest info :-)

**Comment by FreddieChopin** [comment]
While working with grades you may consider also this one - https://github.com/theCrag/website/issues/3715

Apart from that, nothing has changed, the  conversions are still a controversial topic, but I believe the sources I listed above mostly agree that Polish "VI" is similar to French "6a" (;

**Comment by scd** [comment]
In our dev system I have updated polish conversions so that

VI+ = 6a+
V1.1 = 6b
V1.1+ = 6b+
V1.2 = 6c
V1.2+ = 6c+
V1.3 = 7a

This will be available in next release.

@FreddieChopin if this is not right then please let me know asap.

**Comment by FreddieChopin** [comment]
@scd
> @FreddieChopin if this is not right then please let me know asap.

In my opinion this is more than correct! Thanks!

**Comment by rouletout** [comment]
Fixed with release 88
