### ISSUE TITLE
CSV importer - missing newline between manually added entries on the list of route matches

### ISSUE THREAD

**Issue by FreddieChopin** [theCrag/website#3696]
1. Try to import some routes with the CSV importer. Do that manually, with no "bulk assessment", so just upload a CSV file and click "next" next to the number of pending lines.
2. You should see something like this:
![Screenshot from 2020-06-05 17-33-13](https://user-images.githubusercontent.com/1139038/83895654-4af64880-a753-11ea-80f4-9ac99e1dac4c.png)
Each entry in "Candidate routes" is on separate line.
3. Add something manually - select "none", and in the newly shown "Route search" just write anything, click "Get route matches" and add whichever you choose.
4. Now you should see something like this:
![Screenshot from 2020-06-05 17-33-55](https://user-images.githubusercontent.com/1139038/83895850-8bee5d00-a753-11ea-9b1e-39c105edd197.png)
**Note that there is no newline between the last proposal and the newly added entry.**
5. Repeat step 3, just add some different route. Now it should look like this:
![Screenshot from 2020-06-05 17-34-26](https://user-images.githubusercontent.com/1139038/83895960-b7714780-a753-11ea-8c8b-568c72da6a9e.png)
**There's no newline between the newly added entry and the one added in step 3.**

The same happens if the system proposes nothing (the "Candidate routes" has just "none"):
![Screenshot from 2020-06-05 17-42-46](https://user-images.githubusercontent.com/1139038/83896167-0323f100-a754-11ea-9cfc-889ad2901252.png)

I would expect that each added entry should be prefixed with a newline.

**Comment by nicHoch** [comment]
available after next release
