### ISSUE TITLE
Quality Rating not showing for a route

### ISSUE THREAD

**Issue by scd** [theCrag/website#3699]
Crap quality rating not showing for this route

https://www.thecrag.com/climbing/norway/bergen/route/2328427251#

<img width="508" alt="Screen Shot 2020-06-06 at 1 48 28 pm" src="https://user-images.githubusercontent.com/373058/83935378-6cf7d580-a7fc-11ea-80c7-28982527a8a5.png">

**Comment by EndreVerden** [comment]
Nor for this route at the same crag:

https://www.thecrag.com/climbing/norway/bergen/route/2328429042

**Comment by Mdemaillard** [comment]
+1 need to check that graph/stat. 
I wanted to comment on the following rather opiniated route edit, but it's not comfortable to use the star system to argue about it until it can be relied on :-(

 https://www.thecrag.com/event/3390541977

**Comment by georg-d** [comment]
@Mdemaillard: For the route Loki, the logic appears to work fine: According to https://www.thecrag.com/climbing/australia/blue-mountains/medlow-bath/route/15340027#quality a lot of people recorded ascents with quite positive quality rating. This shall translate into 2 stars according to https://www.thecrag.com/en/article/stars --> works as designed!?

**Comment by Mdemaillard** [comment]
Fully agree, it works for this route. But the functionality IS shaky for
other.

**Comment by rouletout** [comment]
Looks ok for the examples given, closing until more issues are reported for this
