### ISSUE TITLE
Big Stat convert grade from Bouldering to Sport

### ISSUE THREAD

**Issue by Mdemaillard** [theCrag/website#3704]
**What happened?**

User @happyharibo reported not understanding the big stat reporting higher grade than the logbook contained.
The issue is that its highest send was boulder, and it seems the big stat displayed an "equivalent" sportsgrade conversion of it.

Ideally also provide screenshots:

![image](https://user-images.githubusercontent.com/60388146/84594323-add19900-ae51-11ea-80fe-bafe92acd103.png)

**What you expected:**
* [ ] if big stat is about bouldering, keep the grade in appropriate grading system

**Comment by rouletout** [comment]
User confirms this is ok now, closing
