### ISSUE TITLE
Topo: Annotations not displayed correctly

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3707]
**What happened?**

For example here: https://www.thecrag.com/climbing/mexico/area/3410875836

Annotations have titles and long descriptions. When selecting Annotations, the description is shown instead of the title. This is alos true when trying to draw the topo, the label is using the description text and not the title.

<img width="710" alt="Screenshot 2020-06-20 at 06 43 04" src="https://user-images.githubusercontent.com/19162952/85202148-92d3ae80-b2c1-11ea-909e-b8638a9e27f5.png">

<img width="714" alt="Screenshot 2020-06-20 at 06 43 41" src="https://user-images.githubusercontent.com/19162952/85202190-dc23fe00-b2c1-11ea-8a97-72e3bdce5756.png">

Ideally also provide screenshots:

**What you expected:**

Display of annotation title, not description in slection and label.

**Comment by rouletout** [comment]
The same is true in case of "Resorting" - the form dispalys the description and not the title.

<img width="922" alt="Screenshot 2020-06-20 at 06 52 04" src="https://user-images.githubusercontent.com/19162952/85202300-a92e3a00-b2c2-11ea-83fd-84bd45d6a4e9.png">

**Comment by rouletout** [comment]
These annotations are also not "drawn" on topos. Meaning only the label (or better description) is displayed and dots are drawn but no yellow lines between the dots (see screenshot).

<img width="713" alt="Screenshot 2020-06-20 at 06 50 54" src="https://user-images.githubusercontent.com/19162952/85202494-02e33400-b2c4-11ea-9719-54f6e0870413.png">

However, if I add a new annotation or change the title of one of them forth and back it behaves correctly. What is wrong with these annotations?

**Comment by rouletout** [comment]
Found one more area: https://www.thecrag.com/climbing/belize/area/3149753298

If you click on reorder you will see 2 annotations displayed with their description instead of title and one correctly. 

<img width="782" alt="Screenshot 2020-06-20 at 09 22 39" src="https://user-images.githubusercontent.com/19162952/85205524-10ef7f80-b2d9-11ea-93ac-6f785675cbee.png">

**Comment by scd** [comment]
I have fixed this, but it will not be ready until next release. @Mdemaillard can you please test and close after next release.

**Comment by Mdemaillard** [comment]
confirmed working on prod !
