### ISSUE TITLE
There's a dummy topo at "World" level, someone with appropriate permissions should remove it

### ISSUE THREAD

**Issue by FreddieChopin** [theCrag/website#3710]
**What happened?**

At the level of "World" there's a dummy topo, no idea how it got there. Someone with appropriate permissions should just delete it or move it to Virtual/...

It could be a good idea to also check how it got there and maybe prevent such actions in the future.

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/world

Ideally also provide screenshots:
![Screenshot from 2020-06-21 12-54-19](https://user-images.githubusercontent.com/1139038/85222812-60f44200-b3be-11ea-838c-c734ad018c33.png)

**Comment by Mdemaillard** [comment]
seems sorted. thanks for the notification.
