### ISSUE TITLE
Make 'Route setter' default selection

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3712]
**What happened?**
Small UX improvement request:  

In the route editing form, make the `Route setter` the default selection.

Why?  
Only for the top 1% hard routes in the world, the first ascensionist is known. For all the other 6s and 7s the first ascensionist is not known (or at least not documented). However, guidebooks usually know the route setter.

Hence, for me as a crag editor, every time I have to switch this input field to route setter which is a small annoyance for me.

**Ideally, also provide screenshots:**
`First ascent` is current default
![image](https://user-images.githubusercontent.com/30682796/85387741-7f387a00-b545-11ea-9c9a-5c6ea7a6f668.png)

`Route setter` is only third option - but IMO should be default option.
![image](https://user-images.githubusercontent.com/30682796/85387824-96776780-b545-11ea-9338-0e88cdaf8662.png)

**What you expected:**
* `Route setter` is the default value

**Comment by scd** [comment]
Can I get input from more climbers as this is new info for me.

**Comment by Mdemaillard** [comment]
Hi there, i believe this is highly country dependent. 

In South Africa the guidebook lists the FA, and sometimes mention the setter if different. (usually the setter is the FA as well...). I am happy as is, but wouldn't really mind the change either. And South Africa is marginal in the climbing picture.

If the case made above (Setter as default) applies and helps for a majority of climbing countries, why not. I don't have foreign guidebooks to check if that is the case.

(Perfect would be to allow a selection of the default per user account, but i recon it is far too much work for what it is worth.)

**Comment by rouletout** [comment]
This is +1 for me as this is the practice in AT and CH - there the priority is rather Route Setter, FFA and then FA if ever known.

**Comment by DaneEvans** [comment]
The only place I'd use setter would be for eliminates, and they rarely
warrant a write up anyway.
If you're thinking bolter/equiper/gardener then it would be concerning
information to get into the hands of land managers in many places where
development is not entirely legal.


If there is a change to this it should be regional or individual, not world
wide

**Comment by killakalle** [comment]
I don't know what 'eliminates' are. Can you explain, @DaneEvans ?

>If you're thinking bolter/equiper/gardener then it would be concerning
information to get into the hands of land managers in many places where
development is not entirely legal.
I am thinking `bolter/equipper` when I select `Route setter` because that seems the most appropriate. How ever, I don't think that your argument is related to UX. If you bolt a new route where it's not allowed, then your concern should not be the order of the dropdown field on theCrag.

However, after reading your and other people's comments above, I believe that my UX request was mainly from a sport climber's perspective.

It seems to me that as a __sport climber__, I will often find the route setter (or bolter) named in guide books - hardly ever, the first ascensionist. It can be assumed that oftentimes the bolter may also be the first ascensionist.

As a __trad climber__, I will usually find the information of the first ascensionist of a route.  
I can confirm this for the area 'Pfalz' in Germany, a very old and traditional climbing area. The guide book I have lists always the first ascensionist.

Going by theCrag route numbers it looks like different continents are dominated differently by different styles, e.g.

- Australia - Trad
- Europe - Sport 60%, Trad 40%
- Asia - Sport
- Africa - Trad 55%, Sport 45% 

Then the default could follow the main style of the area, and/or update in a similar way like `Grade context` is automatically defaulted to the corresponding value after a few routes have been entered.

**Comment by Mdemaillard** [comment]
The help isn't obvious about it but i also always consider bolter/equiper for the field route setter
![image](https://user-images.githubusercontent.com/60388146/85543554-76fe3e80-b61a-11ea-8a6c-039637c33498.png)

An eliminate is usually an alternate version of an existing route which specifically exclude = eliminates some holds (or face in a corner,...) to increase difficulty. I understand it is more a common practice in bouldering than in rope climbing.

**Comment by nicHoch** [comment]
here is a temporary fix for users with a bit IT background.
this userScript can be run via greasemonkey or tampermonkey
and will set the input field of the history to "Route setter"

https://gist.github.com/nicHoch/e90df6bcbc55484164c23e69fc507333

**Comment by rouletout** [comment]
This seems way to controversial to change - clsoing
