### ISSUE TITLE
String Search results sorting is unhelpful (matches of sub strings) 

### ISSUE THREAD

**Issue by DaneEvans** [theCrag/website#3714]
**What happened?**
Searching for routes with FA 'name'  results in hits that have none of the words in question 

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/world/routes/by/Rick%20Phillips/?sortby=at,desc

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/22091505/85517824-fa338a80-b642-11ea-8b61-3cc17b45e65d.png)

**Comment by DaneEvans** [comment]
actually, it's found the 'rick' in Hendricks, so not completely bogus, just a failure in ranking

**Comment by lordyavin** [comment]
Problem is that the search searches for Rick or Phillips  it and. Remove the Rick search term and you should get better results.

**Comment by Mdemaillard** [comment]
i suggest to close here in favor of #2584

**Comment by rouletout** [comment]
agree, closing here
