### ISSUE TITLE
Error when removing photo

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#3716]
**What happened?**

Example url(s) to reproduce the problem:

https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3APushReturnURL=%2F2471559291;C%3AState=16159;C%3AHideNavigation=1;D%3APhotoID=2471559291

Ideally also provide screenshots:

```
Error

Cannot continue process: local file '/opt/CIDS/files/cas-image/41/26/41262a09ef7a136aeb2a2fc7ec55b184ddd01ee0' not found

State: 8626

Error Code: 4

CodeReference: CIDS::Process::SupplyInformation::ReviewPhoto, /opt/CIDS/perllib/CIDS/Process/SupplyInformation/ReviewPhoto.pm, 1216 
```
**What you expected:**

That the photo got deleted.

**Comment by scd** [comment]
I have hot fixed this, but some photos may be left in a funny state. It will be a while before we get a script going to close the photos where images were partially deleted. In the meantime you can stop the photo record from showing by disabling the photo.
