### ISSUE TITLE
theCrag can hardly be discovered when searching for crag topos in Spanish

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3717]
**What happened?**

In the area of Valencia, Spain theCrag is mostly unknown, although a lot of the local crags are listed on theCrag. An increasing number meanwhile including also drawn topos. Although theCrag is available in the Spanish language, I believe one of the problems is that a Spanish speaking person is unlikely to discover theCrag on their own.

A typical scenario here is that people search for topos for a particular crag online. Searching in Spanish will usually show them results from either of those local websites:

- elev-arte.com
- enlavertical.com
- valenciaclimb.com

Whereas, theCrag is usually not among the search results - or at least not on the front page. I've illustrated the problem below with local search terms for a well documented local crag [Gestalgar](https://www.thecrag.com/climbing/spain/valencia-cuenca-area/area/2561059722).

In case it matters:  

- I'm based in Spain
- I set my Chrome preferred language to Spanish
![image](https://user-images.githubusercontent.com/30682796/85992954-e64aa880-b9f5-11ea-847e-28b06952a22d.png)

__Example url(s) to reproduce the problem:__

__1 - Gestalgar Climbing__  
EN
Google search: gestalgar climbing
https://www.google.com/search?q=gestalgar+climbing
Rank: 2

ES
Google search: gestalgar escalada
https://www.google.com/search?q=gestalgar+escalada
Rank: not listed within 10 first pages of search results (strangely enough, I saw theCrag listed once or twice on this search, but when trying to reproduce, the listing was gone completely)

__2 - Gestalgar Topo__

In Spanish you can usually find topos by searching for crag name + [topo(s) | reseñas | croquis]

EN/ES
Google search: gestalgar topo
https://www.google.com/search?q=gestalgar+topo
Rank: 6+7
![image](https://user-images.githubusercontent.com/30682796/85990964-0e84d800-b9f3-11ea-8390-47acc8429a27.png)

ES
Google search: gestalgar reseñas
https://www.google.com/search?q=gestalgar+rese%C3%B1as
Rank: 15 (although keyword 'reseñas' is not found)
![image](https://user-images.githubusercontent.com/30682796/85991167-586dbe00-b9f3-11ea-9cc2-58a154559d7b.png)

ES
Google search: gestalgar escalada resenas
https://www.google.com/search?q=gestalgar+escalada+resenas
Rank: not found
![image](https://user-images.githubusercontent.com/30682796/85992775-a4b9fd80-b9f5-11ea-96a0-759e8a59cd46.png)

ES
Google search: gestalgar croquis
https://www.google.com/search?q=gestalgar+croquis
Rank: theCrag not listed in search results

**What you expected:**

theCrag shows on first page on Google Search when searching for either
* gestalgar escalada resenas
* gestalgar croquis

**Comment by killakalle** [comment]
SEO is also discussed in https://github.com/theCrag/website/issues/1306

**Comment by rouletout** [comment]
@killakalle thanks for that input - we have some international SEO activities planned that should address this problem. Area pages (in contrast to article pages) are currently not indexed per language - we might use Spanish as a first "test case" rather sooner than later.

**Comment by rouletout** [comment]
@killakalle a few weeks back we introduced a new URL structure to allow for better multi-language indexing by Google (and others). Would be curious to hear if you aleready see certain changes. Please be aware that these changes take time to take effect in search ranking...

**Comment by killakalle** [comment]
@rouletout 

It seems that search ranking has improved. Here are a few test search results:

`#1`  
Search `escalada jerica`  
Browser set to Spanish, Google set to Spanish.  
theCrag shows up on page 2, but with **English** text
![image](https://user-images.githubusercontent.com/30682796/92253210-837efd00-eecf-11ea-81d1-706881000ee4.png)

`#2`    
Search `escalada jerica`  
Browser set to English, Google set to German
theCrag shows up on page 1
![image](https://user-images.githubusercontent.com/30682796/92253577-f5efdd00-eecf-11ea-81d0-d097f45f3938.png)

`#3`  
Search `escalar jerica`  (not escala**da**)
Browser set to English, Google set to German
theCrag is **not** within first 5 pages


Is the URL structure change related to this?

Good URL
![image](https://user-images.githubusercontent.com/30682796/92252334-6269dc80-eece-11ea-9963-39a42103bdd7.png)
https://www.thecrag.com/es/climbing/spain/jerica

Bad URL
![image](https://user-images.githubusercontent.com/30682796/92252199-30587a80-eece-11ea-8bb7-ff2d544ab9b1.png)
https://www.thecrag.com/en/climbing/spain/valencia-cuenca-area/area/2561059722

If yes, then in the second case it seems not updated, yet.

**Comment by rouletout** [comment]
Thanks for checking @killakalle - let's look at that for a while. I'm not sure I understand how you ended up at https://www.thecrag.com/en/climbing/spain/valencia-cuenca-area/area/2561059722 ? This is simply the English version of the new URL but if you clicked on it coming from a URL with ../es/.. this shouldn't happen. Can you please check that?

**Comment by killakalle** [comment]
@rouletout 
I was actually referring to sth. else. The URL for Jerica is nicely readable, it contains the name `Jerica` in the URL. On the other hand, the URL for Gestalgar is not nicely readable, it's just numbers. I.e. for Jerica, you can tell by the URL which crag it is, for Gestalgar you cannot. That's just something I've noticed.

> ...but if you clicked on it coming from a URL with ../es/.. this shouldn't happen. Can you please check that?
I was actually just copying the URL from how I use theCrag normally - in English. But while looking into it just now, I think I have found a bug:

To reproduce:

1. Open https://www.thecrag.com/es/climbing/spain/area/1846162401
Notice you are in Spanish now
2. Through the left sidebar navigate to "Castellon Area - Jerica"
Notice how the link of the child is not in Spanish anymore
3. You end up at https://www.thecrag.com/climbing/spain/jerica which is now English - but should be Spanish

![image](https://user-images.githubusercontent.com/30682796/92328152-05516080-f05f-11ea-86af-f435fb2773fd.png)

**Comment by rouletout** [comment]
@killakalle I can confirm this - we'll look into that. As you might have noticed, we have also changed the wording now for "climbing" in the URL to be in local language. This will help as well.

**Comment by rouletout** [comment]
@killakalle this is fixed with the latest release. When navigating through the left menu the language stays the same.

As for the URL's, we can manually set "human readable" URL stubs. If it is a few just provide them to us, if it is many we must find a way so that we can give you the rights to do so.

I close this for now as the bugs are fixed. Please re-open or create a new issue if you encounter more regarding SEO.
