### ISSUE TITLE
Search does not find merchandise shop

### ISSUE THREAD

**Issue by georg-d** [theCrag/website#3724]
Shall be changed ASAP because users currently get a box notifying them about the Merchandise Shop, but if they don't have the time at the moment and want to go to it later on, it's quite difficult to find it (at least _I personally_ would expect it in pages Donation, Sponsorship or the like but not in help).

**What happened?**

Example url(s) to reproduce the problem:

1. Open https://www.thecrag.com/
2. On top right, enter "Merchandise" or "Shop" into search box and start searching
3. No results found.
4. In the drop down next to the search icon, choose whatever you like, still 0 results

**What you expected:**

[ ] Page [Merchandise Shop](https://www.thecrag.com/en/article/merchandise#!/) is shown as result. As this page is currently only visible in help area, it means implementing https://github.com/theCrag/website/issues/2477 

[ ] Page [Supporting theCrag](https://www.thecrag.com/en/article/supporter) names [Merchandise Shop](https://www.thecrag.com/en/article/merchandise#!/) as one way to support/donate. I probably can add it technically, but I'd like to have a "go!" from the core team :)

**Comment by rouletout** [comment]
I suggest we put it in the footer as well in the column "About theCrag" @nicHoch

**Comment by rouletout** [comment]
Search does and will not but it is now in the footer.
