### ISSUE TITLE
Auto-update route history if user logs FA/FFA

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3727]
**What happened?**

A user logged his [first ascent](https://www.thecrag.com/ascent/3492325023) and the [route history](https://www.thecrag.com/climbing/germany/schwaebische-alb/donautal/route/249473730) still does not display the FA.

**What you expected:**

* [ ] Display the logged FA/FFA in the route history

Of course there are two approaches to fix this issue:

1. Always search the routes ascents for FA/FFA entries and populate the route history section with result or
2. Automatically update the route history entries.

**Comment by Mdemaillard** [comment]
see somehow related #101 and #508 (but no duplicate)

**Comment by lordyavin** [comment]
How is #508 related to this issue?

**Comment by Mdemaillard** [comment]
My bad i found 2 nicely related but now cant find the second one anymore ??

**Comment by rouletout** [comment]
FA as tick type is being retired in new interface, closing
