### ISSUE TITLE
Strange wording on stream event

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3729]
**What happened?**
Strange wording on stream event. The event was triggered because I added a new comment. The stream event reads "discuss 21 hours ago". Should rather be something like "new comment added 21 hours ago" or "was discussed 21 hours ago".

In the same stream event you'll also see a strange wording for route name renaming. It reads "Changed name from 'Neoclásicos' name 'Neoclásicos L1'." Should rather be "Changed name from X to Y".

Example url(s) to reproduce the problem:
This is in my dashboard, I don't think I can provide a link to this.

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/87912370-8af85d00-ca6d-11ea-92c8-bba4738400ed.png)

**What you expected:**

* See description above

**Comment by Mdemaillard** [comment]
https://www.thecrag.com/event/2969385306
the URL can be found using the arrow menu "full stream event comments"

the "discuss" should be linked with the translation key:
system.db-interaction.discuss

the "name" topic should be linked with the translation key:
template.stream.detail.renamed-child

**Comment by killakalle** [comment]
Here is another one:
![image](https://user-images.githubusercontent.com/30682796/90988472-46437280-e593-11ea-89c9-1508b0f54602.png)

Link:
https://www.thecrag.com/event/3765909384

All of the ascends/attempts are on the same route. To me the stream event text sounds as if it were different routes.

Expected:

- "Dominik [climbed | attempted] __one__ route [5 | several] times..."

**Comment by killakalle** [comment]
Another one
![image](https://user-images.githubusercontent.com/30682796/90990796-937c1000-e5a4-11ea-9381-4386140814b5.png)


URL:
https://www.thecrag.com/event/3765927678

I did change the grade to `6a+`. However, since the gear style is `boulder` the grade is automatically interpreted as `6A+` which is what should be displayed.
![image](https://user-images.githubusercontent.com/30682796/90990833-d2aa6100-e5a4-11ea-802f-169454ac1cf5.png)


Expected:

- "Changed route grade from '6C' to '6A+'."

**Comment by scd** [comment]
fixed:

![Uploading Screen Shot 2021-01-18 at 1.02.52 pm.png…]()
