### ISSUE TITLE
Community Profile for deceased climbers

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3734]
**What happened?**
Just checked H. J. Auer's profile. Stumbled over the snippet. "If you are H. J. Auer and want to claim this profile...." 
Example url(s) to reproduce the problem:
https://www.thecrag.com/climber/hansjoergauer

Ideally also provide screenshots:
![Screenshot_20200804_083415_com android chrome](https://user-images.githubusercontent.com/30682796/89260864-697ea000-d62d-11ea-8753-148e7963207b.jpg)

**What you expected:**
Different text for deceased climbers. 
Maybe "if you are a relative or related to H. J. Auer and want to manage this profile..."

**Comment by lordyavin** [comment]
Front and back end are still missing the date of death field I assume.

**Comment by rouletout** [comment]
Covered by https://github.com/theCrag/website/issues/3815 - closing
