### ISSUE TITLE
Sudden language switch?

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#3735]
**What happened?**

Example url(s) to reproduce the problem:
On https://www.thecrag.com/en/climbing/bosnia-herzegovina/area/3717788808 I clicked "add information", added a parking spot, clicked save and found myself suddenly in the German site: https://www.thecrag.com/de/climbing/bosnia-herzegovina/area/3717788808

My profile still showed English.

**What you expected:**

* [ ] the English page again, not the German one.

**Comment by scd** [comment]
Can you please confirm whether this was a once off or it happens each time you edit?

**Comment by matozoid** [comment]
I could repeat it when I had that page open, but it no longer happens (although I'm testing on another machine now.) It did happen again on another edit action in another crag though, so maybe once every 25 edits?.

**Comment by nicHoch** [comment]
i also noticed some strange behavior with the current language.

**Comment by killakalle** [comment]
I've also experienced language switches to e.g. Spanish yesterday. Normally everything is in English for me

**Comment by matozoid** [comment]
I got Italian now?!

**Comment by matozoid** [comment]
French now!

**Comment by scd** [comment]
When you report language swap I need to know the context otherwise it does not add anything to help me diagnose. So I need to know what was the previous page and the action you undertook.

At the moment I think it is only happening at when returning from pressing save when editing area information.

**Comment by matozoid** [comment]
Okay, after adding routes here: https://www.thecrag.com/2007312180 with this edit url: https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?routes=10&D%3ANetworkNodeID=2007312180&C%3APushReturnURL=%2Fko%2Fclimbing%2Fbosnia-herzegovina%2Farea%2F2007312180&C%3AHideNavigation=1&D%3ASkipCite=1&D%3ANumberClimbs=10&C%3AState=2059 and pressing save and finish, I ended up with Korean this time.

**Comment by scd** [comment]
Thankyou this is a good summary. The language looks like it switched when pressing edit (see the return url). This gives me an area to look into.

If you notice different scenarios where it is switching then please outline the context as done by @matozoid

**Comment by lordyavin** [comment]
Experienced the language swap just now. Added description to [University Wall](https://www.thecrag.com/en/climbing/canada/alberta/canmore/area/3726942309) and finished the bulk edit form. Then I got forwarded to the [Italian version](https://www.thecrag.com/it/climbing/canada/alberta/canmore/area/3726942309) of the index page.

**Comment by lordyavin** [comment]
And now [got forwarded](https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?routes=20&D%3ASkipCite=1&C%3AState=2059&D%3ANumberClimbs=20&D%3ANetworkNodeID=3726943638&C%3APushReturnURL=%2Fzh_hans%2Fclimbing%2Fcanada%2Falberta%2Fcanmore%2Farea%2F3726943638&C%3AHideNavigation=1) to zh_hans :thumbsdown:

**Comment by nicHoch** [comment]
It also happened while logging an ascent!

**Comment by scd** [comment]
I have hotfixed something here. Please let me know if it still happens. @lordyavin or @matozoid please close this issue in a week if it is no longer happening.

I hope you all have had a chance to learn some climbing terms in new languages :)

**Comment by matozoid** [comment]
I've edited a lot of stuff in the last few hours and things seem stable! @lordyavin - if you see nothing either feel free to close :-)

Thanks @scd !

**Comment by lordyavin** [comment]
Did not happen again during last edits.
