### ISSUE TITLE
Alter Description of Aid Solo Ticktype

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#3738]
User suggestion:

Aid solo = I soloed this route, using fixed or placed protection to make upward progress, using a lead solo device, anchor rope at the bottom.

**Comment by lordyavin** [comment]
If we change the description as proposed we need another tick type: "Aid Roped Solo". IMHO it is irrelevant where the rope is fixed. Important is that you soloed and aided the route. I assume solo aiding a route is quite rare and it is not worth the effort to change semantics and possibly add another tick type.

**Comment by rouletout** [comment]
The current description does not exclude what is described above. In total we have just short over 200 ascents of this style in the DB. I'm closing this.
