### ISSUE TITLE
Cannot change "sport" to "mixed trad"

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#3739]
I understand there's some magic under the hood, converting "trad" into "mixed trad", as soon as bolts are added.
I encountered the opposite case: routes with bolts, currently tagged as "sport", which in my opinion should not be considered sport, as they require additional pro for the average climber. However, "mixed trad" is not in the dropdown list, when I want to change this.
I propose adding it.

OK, just discovered that I can likewise choose "trad", which will turn to "mixed-trad" if bolts had been entered.
Still, I think "mixed trad" should be directly accessible - I may not know the number of bolts, but want to make sure users are aware that they need to take gear.

**Comment by nicHoch** [comment]
change it to trad and it will become "mixed trad"

**Comment by nicHoch** [comment]
please close if it is working as described

**Comment by MelwinQ** [comment]
sorry for not being clear:
As stated, I am aware of the implicit conversion. However, I would suggest to be able to select  "mixed trad" straight away - when adding a route or modifying one. Currently, the dropdown doesn't contain this option. For justification, see above.
Not closed.

**Comment by rouletout** [comment]
As mixed trad is not a state that can be selected manually this would require a bigger change that is not on the to do list for longer.

**Comment by rouletout** [comment]
This is as designed and explained in help, closing here. There is a separet issue on making it a bit more generic if you do not know the exact number of bolts.
