### ISSUE TITLE
"Inherited from" link expands text instead of following link

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3741]
**What happened?**
The `Inherited from` link does not open the target when clicked. Instead, it works as `Show more` / `Show less`

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/spain/costa-blanca/area/3742530222

Ideally also provide screenshots:
![Show_more_inherited](https://user-images.githubusercontent.com/30682796/90227902-9ee97180-de15-11ea-8b16-6482ac43e6cb.gif)

**What you expected:**

* [ ] The `Inherited from` link takes you to the target.

**Comment by killakalle** [comment]
PS:
As a workaround, you can use Right click - Open in new tab.

**Comment by nicHoch** [comment]
fixed with next release
