### ISSUE TITLE
Ascent icons not always loading on mobile

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3744]
**What happened?**
Wondering if this is an issue on my device only, or if other people experience the same:

Every now and then ascent icons in the routes list are not loading for me when browsing theCrag on mobile.

I then have to go into "Clear browsing data" and clear "Cached images and files" for thecrag.com. Then ascent icons are loading properly again - for a while.

This is for Android, Chrome browser.

I remember having this issue also on my Desktop browser. For a couple of months now I have not been experiencing this issue on Desktop browsers anymore, though.

Ideally also provide screenshots:

- Left side: ascent icons not loading
- Right side: ascent icons loading properly after clearing cached images and data.

![image](https://user-images.githubusercontent.com/30682796/91297058-f1277c80-e79d-11ea-8b00-bccddf8ae74f.png)

**What you expected:**

* [ ] Ascent icons always loading correctly on mobile

**Comment by rouletout** [comment]
This only happens with poor network quality. Not sure we can do anything about it.
