### ISSUE TITLE
topo editor: make icons smaller

### ISSUE THREAD

**Issue by georg-d** [theCrag/website#3747]
EDIT: This comment was edited - mainly resolved parts striked through - after comment by nicHoch that CTRL supresses auto joining of 2 points.

**What happened?**

**For wide but high rock faces** like [Carrière in Gueberschwihr](https://www.thecrag.com/en/climbing/france/gueberschwihr-ancien/area/190958196/topo#t3776489115) or even worse [Hornberger Platte](https://www.thecrag.com/en/climbing/germany/schwarzwald/area/1378471509/topo#t3448196184), **photos taken from ground level have a perspective distortion** (my translation guess for DE "perspektivische Verzerrung") and thus appear "compressed" in the top compared to the middle or bottom. This can be reduced to a certain degree by doing perspective transformation, so e.g. the panorama for below screenshot is _by intention not correct_ in the sense vertical features are not vertical but bent to the top outside (see large tree at right), because that incorrectnes reduces the "compression" at top compared to the "more correct" panorama for [Hornberger Platte](https://www.thecrag.com/en/climbing/germany/schwarzwald/area/1378471509/topo#t3448196184), but this problem reduction is limited as too strong perspective transformation creates a very artificial look most people reject/dislike. Similar for photos taken not in approximately 90° angle to the rock face but a much lower angle (so "along" the rock); then, "compression" happens at left or right instead of top. **This distortion reduces the available space in the topo editor so much that it is impossible to place points for bolts etc a) at all (because the amount of points with their current icon size ~~and paddings~~ does not fit into the available space, i.e. overlap each other) or b) where they belong (because they are "too nearby each other" for their size** ~~and thus automatically joined~~). This is true not only on tiny screens but also on a 27" display with 2560x1440 pixels resolution, so a display allowing to recognize the bolts in the photo underlaying the topo - even without zooming in.

Example screenshot ![20200827 125247 New Issue theCrag topo](https://user-images.githubusercontent.com/45993293/91434366-fef40500-e864-11ea-824f-47ed14bb094a.jpg)
Aspect a) Between the arrow and the top, there need to be placed 4 points but only 2-3 fit.
Aspect b) The center of the currently edited point needs to be where the arrow indicates (there's the bolt), but moving the currently edited point even slightly down joins it with the point below. 

**What you expected:**

**As long as bolts can be recognized in the underlaying photo, so the resolution / size of the photo is high enough for single bolts, it is possible to draw a) all bolts and b) at the correct location in a way they can be clearly recognized. Ways to improve the situation:**
* ~~Points are allowed to overlap more before they are automatically joined. Probably quick to implement (just changing a number), but driving this too far demolishes another UI feature (comfortable way to join points).  Probably, we could gain here some 25% to 50%, considerably improving the situation.~~ EDIT: Already possible, CTRL supresses auto joining of 2 points, see comment by nicHoch.
* **Points are smaller.** Probably also relatively quick to implement, but can't be driven too far as it makes "grabbing" a point difficult - especially for touch devices with their low pointing device resolution. If we can reliably tell apart mobile and desktop browsers, for desktop users, a point size as big/small as the mouse pointer shall be OK as that is used all day long and would reduce point size by roughly 66% to 75%, so considerably improve the situation.
* **A region of the topo photo can be zoomed in, thus, more space is available.** Probably considerable implementation effort but offering also other benefits, e.g. solution for blurred display https://github.com/theCrag/website/issues/1911

If you've more ideas how to improve the situation or how to work around, please share :)

**Comment by killakalle** [comment]
+1 from me

Not for drawing bolts, though, but for drawing routes that are close to each other. Mostly for 'steep' photos where you are standing too close to the cliff, of for photos taken from too far away.

The following __workaround__ gets you most of the way. You can actually draw points really close to each other - within their 'snap distance' if you click them into the right spot on the first try. However, you cannot move or adjust them anymore, because they will instantly snap. With this workaround, you cannot add points, though,  that would fall within the circle of another point. See an example screenshot below.

![image](https://user-images.githubusercontent.com/30682796/91842236-fd0ab700-ec53-11ea-91b9-1aa56dd74a52.png)

@georg-d 
Do you think there is actually a lot of added value by drawing bolts on steep distorted images, e.g. 
[Hornberger Platte](https://www.thecrag.com/en/climbing/germany/schwarzwald/area/1378471509):
![image](https://user-images.githubusercontent.com/30682796/91841959-78b83400-ec53-11ea-9686-ae912140a876.png)? Wouldn't it be sufficient for people if they knew the total number of bolts for that route which can be provided in the respective field?

This issue and potential solution are actually very related in my opinion:
https://github.com/theCrag/website/issues/1701

**Comment by georg-d** [comment]
> Not for drawing bolts, though, but for drawing routes that are close to each other. 

Yes, different aspect of same issue.

> The following **workaround** gets you most of the way. You can actually draw points really close to each other - within their 'snap distance' if you click them into the right spot on the first try. 

Yes, it's a viable workaround for the aspect you mentioned, i.e. when you only want the line (which is already quite thin compared to icons like "lower off") but you _can't place it properly_ just because the "handles" do auto snap. For all other shapes, in my experience, the mentioned workaround turned out to be only seldomly viable because the quite big icons hide each other or the line (e.g. [Carrière in Gueberschwihr](https://www.thecrag.com/en/climbing/france/gueberschwihr-ancien/area/190958196/topo#t3776489115) number lables 15+16 hide the line, or in below screenshot, top left of number 19 the point icons overlap). 

> @georg-d
> Do you think there is actually a lot of added value by drawing bolts on steep distorted images, e.g.
> [Hornberger Platte](https://www.thecrag.com/en/climbing/germany/schwarzwald/area/1378471509):
> ![image](https://user-images.githubusercontent.com/30682796/91841959-78b83400-ec53-11ea-9686-ae912140a876.png)? Wouldn't it be sufficient for people if they knew the total number of bolts for that route which can be provided in the respective field?

This leads off the topic, hence here only the summary: At this part of the cliff, the only _clearly recognizable_ landmarks are the bolts, that's why they do IMHO add considerable value in this case. More details in https://www.thecrag.com/photo/3448195608 - I'd be happy to get ideas leading to a good solution! 😄 

> This issue and potential solution are actually very related in my opinion:
> #1701

The issues are related, yes, but not the same: #1701 is about _viewing_ topos where too much overlay hides the actual rock. For that, I never felt a need for action because you can hide/show the overlay via a button, so you can toggle between the rock structure and the route overlay. But we have no solution for _within_ the route overlay, so 1) for space conflicts _between the single icons_ and the lines of the overlay layer and 2) the padding issue (auto snap) while _editing_ - that is the issue  #3747. Funny that #1701 descibes a solution for issue #3747 :-)

**Comment by nicHoch** [comment]
there are other good points in the issue but the official method to avoid snapping points is to pres CTRL while moving the points around.

**Comment by killakalle** [comment]
@nicHoch great tip! Why haven't I thought of trying this?!

This solves the issue described in this ticket for me. (Though, not https://github.com/theCrag/website/issues/1701 but that's anyhow another ticket.)

**Comment by georg-d** [comment]
> the official method to avoid snapping points is to pres CTRL while moving the points around.

After reading that, I did not find it in text & video in https://www.thecrag.com/en/article/topotutorial - does anyone sees a reason why it shall not be mentioned? If not, I'd add it for DE and I will create a task/trello for EN, so someone with permission can change EN.

I updated issue title and original post accordingly.

**Comment by rouletout** [comment]
Task is / will be in trello to create missing key in EN, closing here.
