### ISSUE TITLE
Topo view - Missing navigation to child elements of current node

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3748]
**What happened?**
When you are in topo view at a current node, it is not possible to view or navigate to its child nodes. However, this is possible for sibling nodes of the current node.

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/spain/jerica/area/2795693538/topo

Ideally also provide screenshots:

For the current node there is no drawer with its children displayed, nor are the children displayed in a tree-like fashion:
![image](https://user-images.githubusercontent.com/30682796/91634098-0d215d00-e9ee-11ea-9be7-9f3357c2d7ba.png)

For a sibling node, its children are shown on mouse-over. And it is possible to navigate to them:
![image](https://user-images.githubusercontent.com/30682796/91634133-45c13680-e9ee-11ea-9d42-bc25683a551a.png)

As a workaround I have to go to the Index, then navigate to the respective child, then go into topo edit view.

**What you expected:**

* [ ] Possibility to see and navigate to child nodes of the current node

**Comment by rouletout** [comment]
This looks like a bug - I can reproduce.

**Comment by scd** [comment]
hotfixed
