### ISSUE TITLE
Topos without drawn route shown out of place

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3752]
**What happened?**
Today(?) - @scd - a system update(?) has completely destroyed the nicely organized boulder venue [Setas en Parque Central](https://www.thecrag.com/en/climbing/spain/valencia-cuenca-area/area/2912905038).

Topo images now are all on top without context. Routes are listed all at the bottom. Association of topo image and route is not possible anymore.

I figured out that drawing a single topo dot on the image, puts the topo images back in their original place. So, there must be some check in place that looks for drawn routes?

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/spain/valencia-cuenca-area/area/3067857549

Ideally also provide screenshots:

All topo images now sit on top without context
![image](https://user-images.githubusercontent.com/30682796/91758741-c770ba00-ebd0-11ea-8aca-17ac7de64b90.png)

Route list follows below - although each route has an assigned topo
![image](https://user-images.githubusercontent.com/30682796/91758812-e1120180-ebd0-11ea-8f19-7ec86836d90f.png)

A single drawn dot puts the topo image back in its place above the corresponding route
![image](https://user-images.githubusercontent.com/30682796/91758004-90e66f80-ebcf-11ea-8472-517869385924.png)

The closest, to how it used to be is the Topo edit view: Topo image + associated route right below
![image](https://user-images.githubusercontent.com/30682796/91759012-3c43f400-ebd1-11ea-9a8a-7a2c62388d49.png)

**What you expected:**

* [ ] Topo images for single routes are shown next to routes in route list - even if route is not (yet) drawn.

**Comment by scd** [comment]
Yes, there is a check for drawn routes. Maybe we should take this check off?

**Comment by killakalle** [comment]
@scd are there situations where this check for drawn routes makes sense?
Does this check prevent strange behaviour on other crags?

I'd personally vote for putting that check back in - but I may not be aware of the reasoning why it was introduced in the first place.

**Comment by scd** [comment]
I have removed the check. I did not come across valid use cases when testing the check. However this is a clear valid use case. When we have the ability to draw circles on topos this use case will no longer be valid. But for now I agree that we should remove the check for drawn routes.

Thanks for finding this one. I am closing the issue.

**Comment by killakalle** [comment]
Thanks for understanding and very quickly fixing this, Simon!
