### ISSUE TITLE
Grade display strange

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3755]
**What happened?**

In this list: https://www.thecrag.com/ascents/by/laura2001/?sortby=route-grade,desc the ascent for Sitting Bull (https://www.thecrag.com/de/climbing/italy/central-and-southern-italy/rome-area/route/1774698552) is shown with a grdae of 8c+/9aa but i can't see a contribution with 9aa.

<img width="1073" alt="Screenshot 2020-09-06 at 12 06 38" src="https://user-images.githubusercontent.com/19162952/92323504-9e6d8080-f039-11ea-8283-ee49069103a4.png">

Ideally also provide screenshots:

**What you expected:**

Correct grade display.

**Comment by scd** [comment]
This is because of an earlier error which stored the display grade wrongly. I wrote a script a while ago which corrected most grades, but this route may not have been triggered for some reason.

This was fixed by by updating the grade manually.
