### ISSUE TITLE
Ascents database not working for Sporting complex area

### ISSUE THREAD

**Issue by Channass** [theCrag/website#3758]
Looks like the entire Sporting complex doesn't load any recorded ascents and comments. 

[Life of Riley ](https://www.thecrag.com/en/climbing/australia/blue-mountains/medlow-bath/route/15342967) 

![Screenshot_20200914-061520_Chrome](https://user-images.githubusercontent.com/54959990/93027762-9376a980-f652-11ea-985b-138f203e2c0c.jpg)

**Comment by rouletout** [comment]
Fixed
