### ISSUE TITLE
Spanish translation missing on Contributors page

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3761]
**What happened?**
Spanish translations missing in many places (screenshot 1)

Many links in navigation bar are missing `/es/` in URL (screenshot 2)

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/world/contributors

Ideally also provide screenshots:

Screenshot 1
![image](https://user-images.githubusercontent.com/30682796/94440399-f4999380-01a1-11eb-96be-326397634295.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/30682796/94440775-4b06d200-01a2-11eb-877c-43e5933b0494.png)

**What you expected:**

* [ ] Spanish translations in marked ares
* [ ] Links to Spanish pages

**Comment by rouletout** [comment]
Actually the translation keys are missing on this page, so it is not trabnslated In any language. I put the in the translation queue.

**Comment by rouletout** [comment]
Keys implemented, now in the translation queue - closing here.
