### ISSUE TITLE
Regression with map labels centering

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#3763]
**What happened?**

Very recently there has been a regression with the map 'stalks' which connect the point on the map to the white bubble label:

![image](https://user-images.githubusercontent.com/187449/94889519-cd073b80-04bf-11eb-8452-4f8cec8152d5.png)

All of those labels above should be centered with the stalk underneath

![image](https://user-images.githubusercontent.com/187449/94889580-02ac2480-04c0-11eb-97b5-c84f2b82ac75.png)

The issue also happens when the label is south of the point, but the ones east and west appear mostly ok

**What you expected:**

* [ ] the labels are left aligned / too far right - they should be centered (where the crag doesn't have explicit aspect tags)

**Comment by rouletout** [comment]
Fixed in release 87
