### ISSUE TITLE
Spanish language - Feed should use Preterite instead of wrong Present Perfect

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3768]
**What happened?**
"Tom replied 7 days ago." should be translated to "Tom respondió hace 7 días." Instead it reads "Tom respondido hace 7 días" which is incorrect - both in terms of wrong tense being used as well as the tense used not being used correctly.

More examples that are incorrect:

- "Dominik actualizado algunas vías en Benialí. • 20  • aprox. hace un día"   -->  "Dominik actualizó ..."
- "Añadido etiqueta "5-10 min"." --> "Añadió etiqueta ..."
- "Dominik editado una zona y algunas vías en..." --> "Dominik editó ..."
- "Dominik subido una foto en Chulilla." --> "Dominik subió ... "
- "Kai empezado esta discusión hace 5 días" --> "Kai empezó ... "
- "Dominik comentado en la discusión... " --> "Dominik comentó ..."
- "Dominik creado una cubierta web en Los Rosildos" - - > "Dominik creó una..." 

There are probably more examples, these were just the ones I could find while scrolling through my feed.
You may want to get a second opinion, as I am not a native Spanish speaker.

Example url(s) to reproduce the problem:

- Switch profile to Spanish
- Check feed 

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/95590223-13bbdf00-0a46-11eb-83cc-f0ddcabf3984.png)

![image](https://user-images.githubusercontent.com/30682796/95629729-cf016980-0a80-11eb-981c-7c45144a3629.png)

Arrows show the form that should be used. Red line shows what is actually being used. But is being used incorrectly as the auxiliary verb _haber_ is missing.

**What you expected:**

* [ ] Feed uses Preterite

**Comment by rouletout** [comment]
Forwarded to translation team for review

**Comment by rouletout** [comment]
This has been tackled, there still might be one or the other in Present Perfect but the majority is done. Please report if you see anything else.
