### ISSUE TITLE
Invisible child nodes prevent creation of sun-areas 

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3769]
**What happened?**

Wanted to create 8 boulders as sub-areas to a Boulder field. I was adding the 8 areas in bulk, upon Save, there was an unhandled error. I started the process of adding the sub-areas again. Upon hitting Save this time, I got an error that the areas already exist. 

When I enter the crag Bulk edit form, the subareas are visible and I even can change their names. However, they are not visible in the crag overview. 

Example url(s) to reproduce the problem:
https://www.thecrag.com/climbing/spain/castellon/area/3915770334

Ideally also provide screenshots:
![Screenshot_20201012_152040_com android chrome](https://user-images.githubusercontent.com/30682796/95751640-3268e280-0c9f-11eb-8c9c-9ae421b02d5e.jpg)

![Screenshot_20201012_152017_com android chrome](https://user-images.githubusercontent.com/30682796/95751749-54fafb80-0c9f-11eb-91d4-510c57707db2.jpg)

**What you expected:**

* [ ] Invisible child objects deleted or made visible

**Comment by scd** [comment]
@killakalle did the area fix itself or did you do something. The Bloque 1 area is now visible

<img width="708" alt="Screen Shot 2020-10-13 at 8 36 26 am" src="https://user-images.githubusercontent.com/373058/95792530-668be400-0d2f-11eb-92cc-36e43c51b829.png">

**Comment by killakalle** [comment]
@scd must have fixed itself. I didn't do anything.

**Comment by scd** [comment]
The failure was probably in the last step which meant the cache was not reset. So once the cache got reset (ie another update) or some time goes by (time is days though) it comes back.
