### ISSUE TITLE
Unlocated routes on the map

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3770]
**What happened?**

On this area :
https://www.thecrag.com/fr/grimper/france/occitanie/area/1511457951

20 unlocated routes are showed on the embed map. 
<img width="656" alt="Capture d’écran 2020-10-13 à 13 28 49" src="https://user-images.githubusercontent.com/34114303/95819213-0cebdf80-0d58-11eb-9fd4-f9403f94d249.png">

However, there are no unlocated crags in this area children.

Also this area (Gard) is not findable in the search tool.

**Comment by rouletout** [comment]
This is gone, closing
