### ISSUE TITLE
Spanish translation issues

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3772]
**What happened?**
There are many Spanish translations issues. I'll collect them all in here when I come across them.

- Move routes - Mandatory field
![image](https://user-images.githubusercontent.com/30682796/96322898-35573080-101b-11eb-9d8f-866d0f953c44.png)

- Topo overlay buttons not translated
![image](https://user-images.githubusercontent.com/30682796/96323207-6a17b780-101c-11eb-913f-acb09ba1ea45.png)

- Topo edit view not translated (see screenshot)
![image](https://user-images.githubusercontent.com/30682796/96323303-d5618980-101c-11eb-9a2c-1d4ba303e9a1.png)
See respective translation keys
![image](https://user-images.githubusercontent.com/30682796/96336363-741ed200-107f-11eb-92a2-473b38bc7ab7.png)

- Topo admin not translated
![image](https://user-images.githubusercontent.com/30682796/96323364-23768d00-101d-11eb-8bfa-d305317b5b2f.png)

- "Your mentions" is not translated
![image](https://user-images.githubusercontent.com/30682796/96323771-f4f9b180-101e-11eb-940b-8e5b1d82a8ec.png)

- Map Locate not translated
![image](https://user-images.githubusercontent.com/30682796/96323922-6a658200-101f-11eb-86f7-7ef25417af00.png)

- Toast message not translated; In Map, locate hit the green Save button. A toaster message pops up. It's in English.

- Offensive names button has no key and is not translated
![image](https://user-images.githubusercontent.com/30682796/96337773-b9e09800-1089-11eb-8e42-535c939320e5.png)

See also https://github.com/theCrag/website/issues/3768

**What you expected:**

* [x] "Mandatory field" --> "Campo obligatorio"
* [ ] Topo overlay buttons translated
* [ ] Topo edit view translated
* [ ] Topo admin translated
* [x] "Your mentions" is translated
* [ ] Map Locate translated
* [ ] Toaster messages translated
* [ ] Offensive names translated

**Comment by Kuruchy** [comment]
Can I help you with the translation?

**Comment by killakalle** [comment]
> Can I help you with the translation?

@Kuruchy I'm just a user reporting the issues - and not a native Spanish speaker. I guess this question is for @rouletout

**Comment by Kuruchy** [comment]
Well then @rouletout if you need help, I am a Spanish, developer and climber ;)
Happy to help.

**Comment by rouletout** [comment]
@kuruchy well help is always welcome :-) - I'll send you an email

**Comment by rouletout** [comment]
Moved to the translation board, @killakalle if you find more, please create new issues as it is easier to manage than one that grows over time, thanks.

**Comment by rouletout** [comment]
This is done and in the workflow - additional "Mandatory Field" could pop up as it is used in many forms. Please report if you see one once translated.
