### ISSUE TITLE
Spanish translations - Name variable not resolved

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3774]
**What happened?**
see screenshot

Example url(s) to reproduce the problem:
https://www.thecrag.com/climber/kikoaura

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/96496447-8a788980-1249-11eb-8f71-c868c597477c.png)

**What you expected:**

* [ ] Name displayed instead of variable

**Comment by rouletout** [comment]
fixed, the value in brakets was also translated which shouldn't be :-)
