### ISSUE TITLE
Spanish translations - Grade system not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3775]
**What happened?**
See screenshot

Example url(s) to reproduce the problem:
https://www.thecrag.com/climber/kikoaura/?lang=yy

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/96496835-0a065880-124a-11eb-88fd-eaa7dbe56e0a.png)

**What you expected:**

* [ ] Grade context translated

**Comment by rouletout** [comment]
done
