### ISSUE TITLE
Photo upload should inform about max file size

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3776]
**What happened?**
Tried to upload an image of 22.5MB. I was not allowed to upload due to file size, but information about permissible file size is neither on the upload page nor in the error message

Example url(s) to reproduce the problem:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?R=https%3A%2F%2Fwww.thecrag.com%2Fes%2Fescalar%2Fspain%2Fvalencia%2Farea%2F3927257532%2Fphotos&D%3ANetworkNodeID=3927257532&C%3APushReturnURL=https%3A%2F%2Fwww.thecrag.com%2Fes%2Fescalar%2Fspain%2Fvalencia%2Farea%2F3927257532%2Fphotos&C%3AState=17416&C%3AHideNavigation=1

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/96516145-e8679a00-1266-11eb-8831-b960a32b823f.png)

**What you expected:**

* [ ] information about permissible file size available to user

**Comment by rouletout** [comment]
This was done a while ago, closing
