### ISSUE TITLE
Spanish translations - Tags not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3778]
**What happened?**
The following tags are not translated to Spanish:

- No dogs
- Not kid friendly
- Noon sun 

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/96701925-7049c300-1391-11eb-915c-78ea08468b03.png)

**What you expected:**

* [ ] tags translated to spanish

**Comment by rouletout** [comment]
done, will be available after next translation push
