### ISSUE TITLE
Spanish translations - Add topo workflow in English

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3779]
**What happened?**
Entire add topo workflow is in English although starting from a Spanish crag page

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/area/3020974173
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3AHideNavigation=1&C%3APushReturnURL=%2F3020974173%2Ftopo&D%3ANetworkNodeID=3020974173&C%3AState=17236

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/96769760-d6f5cd80-13df-11eb-87b5-c05383db357f.png)

![image](https://user-images.githubusercontent.com/30682796/96769842-f856b980-13df-11eb-8493-f9db20f6b10f.png)

also alt text
![image](https://user-images.githubusercontent.com/30682796/96769911-13292e00-13e0-11eb-9983-064565b5a691.png)

![image](https://user-images.githubusercontent.com/30682796/96769957-276d2b00-13e0-11eb-823c-e9b298a939d6.png)

![image](https://user-images.githubusercontent.com/30682796/96770008-3ce25500-13e0-11eb-9031-bee7546bb00b.png)

"Done Editing" gets you back to the Spanish crag overview.

**What you expected:**

* [ ] Entire add topo workflow in Spanish

**Comment by rouletout** [comment]
this is all done and in transaltion workflow with the exception of some Java code that requires translations but this is also in the queue, closing. Reamrk: some photo upload parts are non-translatable, 3rd party tool
