### ISSUE TITLE
Spanisch translations - antes + de; Add annotation not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3780]
**What happened?**
I believe this should be "antes __de__". See screenshot

Just seeing that also a number of texts on this page are not translated.

Example url(s) to reproduce the problem:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3AHideNavigation=1&C%3APushReturnURL=%2F3020974173&D%3ANetworkNodeID=3020974173&C%3AState=19747

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/96771948-b0856180-13e2-11eb-9d7c-13672e972ac7.png)

![image](https://user-images.githubusercontent.com/30682796/96772056-da3e8880-13e2-11eb-829c-6b20ea65b34e.png)
![image](https://user-images.githubusercontent.com/30682796/96772330-45885a80-13e3-11eb-9884-6d4c85a22647.png)

**What you expected:**

* [x] antes de
* [x] Rest of add Annotation is in Spanish

**Comment by rouletout** [comment]
This is done
