### ISSUE TITLE
Spanish translations - Missing translations and keys in Crag list

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3781]
**What happened?**
Missing translations and keys

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/
https://www.thecrag.com/es/escalar/spain/valencia/?lang=yy

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/97229304-6fbd8c00-17d8-11eb-9f62-82ef8dc23a1f.png)

**What you expected:**

* [ ] Node types translated
* [ ] "and" translated
* [ ] quantifier translated

**Comment by rouletout** [comment]
Done, in translation workflow
