### ISSUE TITLE
Spanish translations - ascent stream event typo and mixed tenses

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3782]
**What happened?**
Encountered a few translation errors

Example url(s) to reproduce the problem:
https://www.thecrag.com/event/3955513716

Ideally also provide screenshots:

In English three times the same verb tense.
![image](https://user-images.githubusercontent.com/30682796/97229859-46e9c680-17d9-11eb-8ba1-8a62e05efbd6.png)

In Spanish, the last one has a different tense.
![image](https://user-images.githubusercontent.com/30682796/97229988-7698ce80-17d9-11eb-9e53-d22c91269ac0.png)

I think the sentence should be:

Recce Rob encadenó 7 vías a vista y escaló 4 vías más en El Chorro y __mencionó__ Levi Hampton.

And there is also a typo: mencinado -> mencionado

In the stream event, there is another typo: registro --> registró
![image](https://user-images.githubusercontent.com/30682796/97230337-0dfe2180-17da-11eb-848d-bf0ac0091845.png)

And a missing translation:
![image](https://user-images.githubusercontent.com/30682796/97230502-5584ad80-17da-11eb-9a99-3e042f9c70e5.png)

See also https://github.com/theCrag/website/issues/3768

**What you expected:**

* [ ] consistent use of Preterite
* [ ] no typos
* [ ] "First ascents" translated

**Comment by rouletout** [comment]
moved to translation, closing
