### ISSUE TITLE
Spanish translations - Profile and Edit profile

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3783]
**What happened?**
Encountered missing translations on Profile and Edit profile page. The translation keys are present.

Example url(s) to reproduce the problem:
https://www.thecrag.com/climber/killakalle
https://www.thecrag.com/settings/profile

Ideally also provide screenshots:

Key available, only translation missing
![image](https://user-images.githubusercontent.com/30682796/97230655-9bda0c80-17da-11eb-8e17-77321bef6ba8.png)

![image](https://user-images.githubusercontent.com/30682796/97230821-e9567980-17da-11eb-947c-c82291926ba9.png)

![image](https://user-images.githubusercontent.com/30682796/97230952-13a83700-17db-11eb-80d1-c4bd876ffc77.png)

**What you expected:**

* [ ] No missing translations

**Comment by rouletout** [comment]
All put in the workflow, closing
