### ISSUE TITLE
Spanish Translations - Todo Escalada deportiva

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3784]
**What happened?**
There's an article where it shouldn't be.

It should read "Todo Escalada deportiva" instead of "Todo los Escalada deportiva"

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/jerica/area/2795426874

Ideally also provide screenshots:
https://www.thecrag.com/photo/3955545912

**What you expected:**

* [ ] article removed

**Comment by rouletout** [comment]
Fixed, will be visible with next push
