### ISSUE TITLE
Spanish Translations - Missing translation for "excluding anchors"

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3787]
**What happened?**
Missing translation, see screenshot

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/castellon/area/2407873854

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/97607929-f14c2e80-1a11-11eb-8370-409e22866389.png)

**What you expected:**

* [x] translated

**Comment by killakalle** [comment]
Maybe this is a very similar case:

Sport -> Deportiva

https://www.thecrag.com/es/escalar/spain/valencia/area/3962177763
![image](https://user-images.githubusercontent.com/30682796/97676382-db318300-1a90-11eb-93b6-5448dd59a07a.png)

**Comment by rouletout** [comment]
Item one is done, item 2 needs a release but done on dev, closing
