### ISSUE TITLE
Spanish translations - Stream event not fully translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3789]
**What happened?**
Stream event not fully translated

Example url(s) to reproduce the problem:
https://www.thecrag.com/event/3970828689

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/97980522-320cc480-1dd1-11eb-87ef-26895953da4d.png)

![image](https://user-images.githubusercontent.com/30682796/97980714-857f1280-1dd1-11eb-90c3-4b81b0b5239d.png)

**What you expected:**

* [ ] Stream event fully translated

**Comment by kleiren** [comment]
There are quite a few typos, bad and missing translations, at least in Spanish. 
Is there a translation tool or some place where we can help?

**Comment by rouletout** [comment]
Ping me at ulf@thecrag.com and we can bring you on if you wish :-)

**Comment by rouletout** [comment]
Fixed, available on next push
