### ISSUE TITLE
Generation of text for style of crags broken - displays some internal code `getText('system.and')`

### ISSUE THREAD

**Issue by FreddieChopin** [theCrag/website#3790]
Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/poland/area/1443078771

Check "Style" column of most of the cliffs here. Instead of typical "Sport climbing and Trad climbing" or sth like that I see `Sport climbing ' . getText('system.and') . '  Trad climbing`.

Ideally also provide screenshots:
![Screenshot from 2020-11-03 22-38-39](https://user-images.githubusercontent.com/1139038/98043642-da4c7880-1e25-11eb-86bf-cbda7ae06c16.png)

**Comment by scd** [comment]
Thanks, this is now fixed.
