### ISSUE TITLE
The "format with thecrag markdown" link on photo pages points to wrong page

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3791]
**What happened?**

Next to the comments textarea, there is a link to the markdown help page, but it points to the wrong page.

Example url(s) to reproduce the problem: Any photo page, e.g. https://www.thecrag.com/photo/3892381800

**What you expected:**

Point to https://www.thecrag.com/en/article/formattingtext

**Comment by rouletout** [comment]
Fixed on dev, will be available with next release
