### ISSUE TITLE
Spanish translations - "Select fields" not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3796]
**What happened?**

- Have Spanish selected as your language
- Go to https://www.thecrag.com/climbing/spain/valencia/area/3391732779
- Click on "Edición en bloque " (Bulk edit)
- Click on "filtro de campo."
- Note the entire page is now in English

Example url(s) to reproduce the problem:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?expand=descendants;select=1;C%3AHideNavigation=1;D%3AN=3391732779;D%3AFieldGroup=area_all;D%3AFieldGroup=route_all;D%3AFieldGroup=annotation_all;C%3AState=18538;D%3ANodeExpansion=descendants;D%3AFieldSelection=1;C%3APushReturnURL=%2Fclimbing%2Fspain%2Fvalencia%2Farea%2F3391732779&P%3A0%3AInformationNetworkID=7539484

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/100166767-c5f81a80-2ebd-11eb-9bc4-9310ad89ebe9.png)

**What you expected:**
* [ ] "Select fields" translated to Spanish

**Comment by rouletout** [comment]
put into queue

**Comment by rouletout** [comment]
Implemented - just some new keys are pending translation - closing
