### ISSUE TITLE
delete a route

### ISSUE THREAD

**Issue by gui84** [theCrag/website#3797]
**What happened?**

When I tried to delete a route (with editor rights), 

I was redirected to this page :

https://www.thecrag.com/article/merging#deleting

Only some routes are affected :
https://www.thecrag.com/fr/grimper/france/occitanie/route/1956048627 

not this one : 
https://www.thecrag.com/fr/grimper/france/occitanie/route/1882413195

**Comment by rouletout** [comment]
This is correct behaviour - if you can't delete it sends you to the help page that explains why this is happening.

**Comment by gui84** [comment]
It's not normal. The routes doesn't have any ascents, and I created them.
I think it's a bug.

**Comment by rouletout** [comment]
It's not necessarily an ascent that blocks the delete process. There are multiple ways a route can be referenced in the system and thus being blocked from deleting.

**Comment by gui84** [comment]
I think for this one :
https://www.thecrag.com/fr/grimper/hong-kong/lantau-island/route/3056411844
it's because it was linked with the topo. I unlinked it but without results. 
Should I ask editor privileges to delete this one ?

**Comment by rouletout** [comment]
I can't even delete it as admin, this can only be removed by merging...

**Comment by rouletout** [comment]
Yes, that wa sthe reason, you can just remove it by merging. I close again as the behaviour is correct.
