### ISSUE TITLE
"x ascents by you" not showing on leaf node

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3801]
**What happened?**
I think the "x ascents by you" feature is really useful. However, it does not seem to work on leaf level, i.e. on the level where the routes reside. Only if I go to the parent node or hight, can I see the link that takes my to the filter view with my ascents.

I don't understand why you would not show the link on leaf level, too. E.g. as a workaround you can go to the parten, click the "x ascents by you", then you are at the filter. Now with the left-hand menu, you navigate down to the leaf node and the filter automatically adjusts to your climbed routes on that node.

Example url(s) to reproduce the problem:
Crag:
https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/area/3878775477

Sector:
https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/area/2561079678

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/101108147-3563bd80-35d4-11eb-9fa7-26724be54f8a.png)
![image](https://user-images.githubusercontent.com/30682796/101108176-43194300-35d4-11eb-8c11-1cc0ebd3d99b.png)

**What you expected:**

* [ ] "x ascents by you" on every level including leaf nodes

**Comment by scd** [comment]
Do you mean on a route when you say leaf node?

I just tested this in my account on a route and it worked. It is possible it does not work for a little while after a reparent.

When you click the broken link it takes you to a page. Can you please report this url here?

**Comment by nicHoch** [comment]
No it does nor work on the last area node before a route.

here an other example: https://www.thecrag.com/en/climbing/switzerland/alpen/zentralschweiz/area/219577512
i was not able to find any "last" area where it is working.

**Comment by killakalle** [comment]
"Last área node before a route" is what it meant with leaf. Thanks for clarifying, Nicky.

**Comment by rouletout** [comment]
+1 from https://github.com/theCrag/website/issues/3833 with detailed analysis showing it is always missing on the first level above routes

**Comment by scd** [comment]
fixed on simons dev. It was a param confict.
