### ISSUE TITLE
Spanish translations missing - your discussions

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3802]
**What happened?**
Translations missing

Example url(s) to reproduce the problem:
https://www.thecrag.com/climber/killakalle/messages

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/101108684-5f69af80-35d5-11eb-90c0-c85f69784a5e.png)
![image](https://user-images.githubusercontent.com/30682796/101108736-7a3c2400-35d5-11eb-87fa-9067f6d83bdb.png)

**What you expected:**

* [ ] translated to Spanish
* [ ] item 2

**Comment by rouletout** [comment]
Keys need to be added

**Comment by rouletout** [comment]
This is done / in the translation queue
