### ISSUE TITLE
UI Suggestion to encourage more information.

### ISSUE THREAD

**Issue by jparsert** [theCrag/website#3803]
I think it is unfortunate that people when logging ascent rarely add a comment. In other websites for climbing people usually add a comment. Either about their struggles or some small beta trick or sometimes just a small story detailing how nice the day was. While of course not very "important" I really enjoy reading this more than just a grade of 0 to 3 stars etc.
    
I think it is not surprising that people usually don't add a comment. The reason being the rather poor UI when logging an ascent. The field (the whole area really) for the comment is below everything else and greyed out. I think it should be higher up and given higher priority so that people are encouraged to add a comment. 

Adding to this, when looking at a route it would be nice to have a list of all comments so that I don't always have to go on "load more" all the time. Just a simple table with:  name | date | comment |grade or something like this seems to be the most straightforward way of going about it.

Just a small suggestion.

**Comment by rouletout** [comment]
@jparsert thanks for your feedback - we have plans to address the ticking interface sometimes next year and this is certainly part of it :-)

**Comment by FF-Flo** [comment]
+1 to UI change to encourage ticking comments.

If rework the ticking interface please also remember the suggestions to encourage user grading from this discussion:
https://www.thecrag.com/discussion/4889263512/route-grade-adjustments

**Comment by scd** [comment]
I am closing so we can review comments in terms of new tick flow
