### ISSUE TITLE
Spanish translations - Two different tags translated the same 

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3805]
**What happened?**
Tags "Allowed" and "Tolerated" are both translated to the same Spanish word. That doesn't seem correct

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/101267238-d4b0be00-3756-11eb-8ebe-24100639ab45.png)

**What you expected:**

* [ ] Translated differently, to be able to distinguish the tags

**Comment by rouletout** [comment]
fixed
