### ISSUE TITLE
Spanish translations - Route detail page

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3809]
**What happened?**
Many places on a route detail page are not translated to Spanish. See the two screenshorts

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/route/1460736942

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/101994603-e4368680-3cc3-11eb-909f-4e43feb0990f.png)

![image](https://user-images.githubusercontent.com/30682796/101994661-4c856800-3cc4-11eb-80c3-030d2bae1aa0.png)

See in this screenshot also the missing "Hide", "Legend", "Edit" buttons on the topo image

![image](https://user-images.githubusercontent.com/30682796/101994750-fa911200-3cc4-11eb-85ad-465392bf617a.png)

The mouse-over on routes shows style "Sport" instead of "Deportiva"
![image](https://user-images.githubusercontent.com/30682796/101994810-b81c0500-3cc5-11eb-849e-c8f467314ac4.png)

![image](https://user-images.githubusercontent.com/30682796/101994754-1ac0d100-3cc5-11eb-87e5-eba910b2d06d.png)

**What you expected:**

* [ ] Entire route detail page translated to Spanish

**Comment by rouletout** [comment]
Keys will be added, we will not do the remark to circuits as it is obsolete.

**Comment by rouletout** [comment]
This is done, will be available on next push.
