### ISSUE TITLE
Missing Spanish Translations - Open Guide, Unlocated Routes

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3811]
**What happened?**
Missing Spanish translations see screenshot

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/corbera

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/102267146-c06c7e00-3f19-11eb-8433-3317ded8d80d.png)

![image](https://user-images.githubusercontent.com/30682796/102267284-f873c100-3f19-11eb-8e5a-6cc9307ea31f.png)

**What you expected:**

* [x] "Open Guide" in Spanish
* [x] "Unlocated routes" in Spanish

**Comment by rouletout** [comment]
Done, visible on next push.
