### ISSUE TITLE
Missing Spanish Translations - Stream event card + wrong translation

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3812]
**What happened?**
Some missing Spanish translation and a wrong Spanish translation

Example url(s) to reproduce the problem:
https://www.thecrag.com/event/4225603107

Ideally, also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/102267450-3670e500-3f1a-11eb-8342-3729ea5c51f8.png)
![image](https://user-images.githubusercontent.com/30682796/102267528-52748680-3f1a-11eb-94a2-eaef23e45274.png)

**What you expected:**

* "y" -> "a"
* Stream event card translated
* Updated areas translated

**Comment by rouletout** [comment]
Available on next push, @killakalle please observe as the grammer could be an issue. I leave this open.

**Comment by rouletout** [comment]
This is done, the change from y to a will only be visible after next push, closing

**Comment by killakalle** [comment]
@rouletout 
Not sure I mentioned this in another ticket, yet. 
This one should also be changed:
actualizado -> actualizó

![image](https://user-images.githubusercontent.com/30682796/104759224-e3c85a00-575f-11eb-877d-cb69b286584f.png)

Was apparently also missed in 
https://github.com/theCrag/website/issues/3768

**Comment by rouletout** [comment]
Thanks, found a few more "cambiados" and changed them - wait for tomorrow to see it - please keep going :-)
