### ISSUE TITLE
Route filter page with messed up display (after reparenting?)

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3813]
**What happened?**
On the routes filter page of Montesa crag, the result view is a bit broken (highlighted by pink arrows). I have seen this issue on only one other crag. On both crags I have recently reparented a couple of nodes to reorganize or enlarge the areas.

Example url(s) to reproduce the problem:

Example from screenshot:
https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/routes?page=2

Similar example:
https://www.thecrag.com/es/escalar/spain/valencia/area/4179649881/routes

Example, where everything looks good:
https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/routes?page=2

Ideally also provide screenshots:

![image](https://user-images.githubusercontent.com/30682796/102424392-50d6bb80-400b-11eb-826b-45521d259a2b.png)

**What you expected:**

* [ ] Filter view of crag's routes loads properly (as in Gestalgar example)

**Comment by rouletout** [comment]
This does not look like that on my end - can you try to reproduce and list browser / OS etc?

**Comment by killakalle** [comment]
@rouletout 
The first link should have actually been this one:
https://www.thecrag.com/es/escalar/spain/valencia/area/4215341982/routes

Anyway, I've had a look just now and it looks normal again. I feel I encounter these types of issues often in combination with reparenting/restructuring. Then some days go by and they fix themselves after a while.

Closing.
