### ISSUE TITLE
Spanish translations - Add route information banner

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3819]
**What happened?**
Route has no information banner should be translated to Spanish

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/castellon/route/787146306

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/103515765-9c90be00-4e6f-11eb-856c-27b2eff121f5.png)

![image](https://user-images.githubusercontent.com/30682796/103515898-d9f54b80-4e6f-11eb-80c8-70f0fbe138c7.png)

**What you expected:**

* [x] Route has no information banner should be translated to Spanish
* [x] Route history label should be translated to Spanish
* [x] Quality rating label should be translated to Spanish

**Comment by rouletout** [comment]
These are all fixed now, closing
