### ISSUE TITLE
Ability to add First Ascent with Onsight

### ISSUE THREAD

**Issue by JolleJolles** [theCrag/website#3822]
Currently when selecting "First Ascent" as tick type it shows as "send" in the climbing logbook. As some (easier) first ascents could also be onsighted this option should be given such that the logbook grade pyramid does not show "sends" for all those climbs that were actually onsight first ascents.

**Comment by scd** [comment]
We plan to remove the First Ascent tick type as it crosses logic contours. Instead we may implement it as a flag and create a FA field on the route.

Given this direction I don't plan to change the pyramid.

**Comment by rouletout** [comment]
Just to re-iterate. The FA and FFA tick types will be "retired" as they are rerplaced by the history fields on routes. In your case it will be best to change the tick type to onsight or flash and record your FA as a history firld on the route. That way you can also easily see which routes you FA'ed from your profile. Hope that helps, closing here.

**Comment by JolleJolles** [comment]
Thanks, this is indeed a good solution! Thanks for the quick feedback

**Comment by JolleJolles** [comment]
One last point, which maybe requires this threat to be opened/renamed. 

The person who finds or cleans a line may need multiple trials to establish it, even for easier climbs he/she would normally easily onsight. These climbs now appear as "send" in the grade pyramid, giving the wrong impression that one cannot onsight those easier grades.

It would therefore be good if somehow the grade pyramid would distinguish between first ascents and other climbs with a unique color or at least when you hover above the individual bars for each grades. An alternative could be a filter option to show all first ascents. I don't think people care really if the first ascent was onsighted or not, but it just looks weird to have many "sends" for easier climbs and it would be nice to distinguish the climbs that are First Ascents as it shows extra effort.

Thanks for your consideration!
