### ISSUE TITLE
Spanish website - Ascent column label too long

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3825]
**What happened?**
When using theCrag in Spanish, the labels are too long, they overlap each other. See screenshot

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/area/1846162401

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/104126413-a7aa8900-535c-11eb-81cb-df9735b431e8.png)

**What you expected:**
* [ ] Labels don't overlap

**Comment by rouletout** [comment]
There was a mistake in the abbreviated translation - fixed, will be available on next push
