### ISSUE TITLE
Delete button for a route is not available

### ISSUE THREAD

**Issue by ivioi2e2** [theCrag/website#3829]
I went to the sector https://www.thecrag.com/en/climbing/spain/corbera/area/1443743907 and tried to delete some routes, but the delete button redirects me to "/article/merging#deleting" explaining how to delete, instead of deleting the route.

Steps:
 - Go to route
 - Open dropdown on the right of "Edit route"
 - Click on delete
 
Expected result:
 - Redirect to delete route

Actual result:
 - Redirect to the help on how to delete a route

I also tried to modify the link "/article/merging#deleting" to "/processmap/deletenode/[route_id]" and I get redirected to request permissions to delete (I already have permissions to edit on that crag and it has been some weeks since I requested the permissions and is still asking to request for permissions)

**Comment by rouletout** [comment]
@ivioi2e2 this means the route can't be deleted. This is why it redirects you to the help expalong it. We normally don't allow  deletes as thsi would break references, impact other user's logbooks, etc. Which route do you try to delete? Why do you want to delete a route?

**Comment by ivioi2e2** [comment]
I went to a sector nearby to make photos for topos, and from left to right I couldn't find a route that seemed graded 4, that was the first one there. So that confused me and trying to relate the routes on thecrag to the ones I saw on the photos I did and an old topo, I thought the routes missing were removed and they added new ones. Thinking that I added new routes.

I searched again some days after, because I was going to go again, with the old topo and saw that the reference on the wall that I used was similar to a another one on the side.
So I did the route relation again but from right to left and that led me to find the routes missing that were a bit hidden.

In the end I added some routes that are now named "Sin nombre X" without grade and sorted last on that sector, I thought that as I created them I could be able to delete them but no.

The link to the sector is in the issue description.
________________________________
De: rouletout <notifications@github.com>
Enviado: miércoles, 13 de enero de 2021 11:02
Para: theCrag/website <website@noreply.github.com>
Cc: Alfredo Moises Boullosa Ramones <moisesbulhosa@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [theCrag/website] Delete button for a route is not available (#3829)


@ivioi2e2<https://github.com/ivioi2e2> this means the route can't be deleted. This is why it redirects you to the help expalong it. We normally don't allow deletes as thsi would break references, impact other user's logbooks, etc. Which route do you try to delete? Why do you want to delete a route?

**Comment by rouletout** [comment]
OK I see - there are several triggers that prevent routes to be deleted once they were "used" somehow in the system. These can't be deleted anymore - so best is to merge them "away". Let me knwo if you need help with that. Thanks for contributing!!

**Comment by rouletout** [comment]
Closing
