### ISSUE TITLE
Closed tag only shown for some routes in closed crag

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3830]
**What happened?**
The "closed" tag gets inherited by all routes of a crag if the latter obtains said tag. However, the index only displays this sporadically.

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/germany/frankenjura/grosser

**Comment by rouletout** [comment]
Strangely enough the tag is shown on the route pages...

**Comment by quaestor** [comment]
Yes, seems like the inheritance is working, but the display in the index is messed up.

**Comment by quaestor** [comment]
This seems to be a deeper issue:

https://www.thecrag.com/climbing/germany/frankenjura/stifterfels

This crag had the "closed" tag removed (only the right part of the crag is closed), but the change isn't reflected in the display. The routes up to "leatherhead" are shown as closed, even if the tag is not set.

**Comment by scd** [comment]
Yes this is a bit of a problem. The core bug is that that we don't have a good way to cache bust nodes with cached info when their ancestor node changes. Mostly this does not matter, but there are a couple of functions such as locking a node, default grading context and closed tags where this is really important.

I spent some time today working out an ancestor node cache busting algorithm for particular fields. This works in my dev and will be available next release.

**Comment by rouletout** [comment]
Fixed with release 90, @quaestor please re-open if you find anything not working

**Comment by quaestor** [comment]
Thanks for the quick fix. The issue seems to be gone, but I'll keep an eye on it.
