### ISSUE TITLE
Spanish translations - stream event text broken

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3832]
**What happened?**
Some of the recent translations must have broken stream event texts in Spanish. See screenshots

Example url(s) to reproduce the problem:
https://www.thecrag.com/event/4365655392

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/104778028-f7ce8480-577c-11eb-8883-f6f89142454b.png)

This is how it looks like in English
![image](https://user-images.githubusercontent.com/30682796/104778147-32382180-577d-11eb-8042-617fe11d3f23.png)

**Comment by rouletout** [comment]
Thanks! Should be fixed within a few hours - was a "user mistake" by a translator - closing but please keep an eye open from tomorrow on if more stream translations are gone, thanks
