### ISSUE TITLE
Aspirational ascents shown in stream as "logged ascents from the past"

### ISSUE THREAD

**Issue by quaestor** [theCrag/website#3835]
Aspirational ascents, like "Hit" or "Target", are displayed in the stream as "logged x ascents from the past". It would be nice to show them as "ascents from the future" instead. :wink: Or more seriously, formulate it in a way that doesn't make people think the ascents already happened, like "planned x ascents for the future" or "wants to take a shot at x routes".

**Comment by rouletout** [comment]
The aspirational ascents will be retired very soon and will be replaced by a new "wish list" feature. This will also eliminate this issue, closing.
