### ISSUE TITLE
Spanish translations - Añadido --> Añadió

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3836]
**What happened?**
Should be
Añadido --> Añadió

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/105239665-2aa5bd80-5b6d-11eb-836f-29a6847e7aca.png)

Some more examples
![image](https://user-images.githubusercontent.com/30682796/105241063-85d7b000-5b6d-11eb-8c27-d52e696c4f90.png)

![image](https://user-images.githubusercontent.com/30682796/105241220-a273e800-5b6d-11eb-8778-fab80c000ae7.png)

![image](https://user-images.githubusercontent.com/30682796/105241312-c6cfc480-5b6d-11eb-8c18-130f2c298e61.png)

![image](https://user-images.githubusercontent.com/30682796/105241380-e1a23900-5b6d-11eb-86a4-6f9ce19bea1f.png)

![image](https://user-images.githubusercontent.com/30682796/105241555-1f06c680-5b6e-11eb-85e3-e0946739d76d.png)

**What you expected:**

* [ ] Añadió etc

**Comment by rouletout** [comment]
Thanks @killakalle - found a bunch more and changed them, will be available on next push. Please keep going :-)
