### ISSUE TITLE
Spanish translations - Merging of areas not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3850]
**What happened?**
1. Use Spanish
2. Merge two areas
3. Merge screen is in English instead of Spanish

Example url(s) to reproduce the problem:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?C%3APushReturnURL=%2Fclimbing%2Fspain%2Fmontanejos%2Fmontan%2Farea%2F350094561&C%3AHideNavigation=1&D%3ANetworkNodeID=350094561&C%3AState=16417

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/107288258-71e3e780-6a63-11eb-8def-4f09cde3c2b4.png)

**What you expected:**

* [x] Merge screen in Spanish

**Comment by rouletout** [comment]
Nice catch @killakalle - this refers to an old page that shouldn't be used anymore and thus is not translated. Fixed for next release.
