### ISSUE TITLE
Spanish translations - Node relocation

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3852]
**What happened?**
Just relocated an area. The stream event text (in Spanish) somehow looks odd.

Example url(s) to reproduce the problem:
https://www.thecrag.com/event/4460864868

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/107889150-11e0bb80-6f11-11eb-9539-10be32b6db4d.png)

**What you expected:**

* [x] Stream event text meaningful

**Comment by rouletout** [comment]
Thanks, fixed on next push
