### ISSUE TITLE
Spanish translations - Based on x ratings

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3855]
**What happened?**
"Based on x ratings" not translated to Spanish

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/route/3436712214

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/107995620-e7f5ca80-6fde-11eb-85e9-8cb2b5646e9b.png)

![image](https://user-images.githubusercontent.com/30682796/107995678-03f96c00-6fdf-11eb-9723-d79fa3110fde.png)

**What you expected:**

* [ ] Translated to Spanish
* [ ] item 2

**Comment by rouletout** [comment]
This is in the queue, available on next push, closing
