### ISSUE TITLE
Are retreats not considered for Quality rating?

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3857]
**What happened?**
A user logged a retreat with quality rating "Crap". It is not considered in the star rating.

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/chulilla/route/1122000033

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/108609551-e22d2a00-73ce-11eb-9b0c-fe72f6fda70f.png)

**What you expected:**

* [ ] All logged ascents considered in Quality rating

**Comment by scd** [comment]
For some reason stats got out of sync with route. Reruning stats for route fixed this.
