### ISSUE TITLE
Spanish translations - "Offensive names" not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3858]
**What happened?**
Initially highlighted in this issue. Still not fixed.
https://github.com/theCrag/website/issues/3772

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/109305219-b29e7780-783d-11eb-970a-e13c9c7879f3.png)

**What you expected:**

* [ ] Offensive names translated

**Comment by rouletout** [comment]
As this leads to an English discussion I doubt the value of translating it - anyways this topic should be removed rather sooner than later once the policy is up. ok @killakalle ?
