### ISSUE TITLE
Spanish translations - "ascents by you" not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3859]
**What happened?**
See screenshot

Example url(s) to reproduce the problem:
Find a crag where you climbed

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/109305466-0ad57980-783e-11eb-8111-94389b4e2ecd.png)

**What you expected:**

* [ ] translated

**Comment by rouletout** [comment]
note for self, this is key template.count-by-you

**Comment by rouletout** [comment]
in translation queue, closing
