### ISSUE TITLE
Spanish translations - "Start a discussion" not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3860]
**What happened?**
See screenshot

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/bellus/forum

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/109305725-6ef83d80-783e-11eb-9c39-04e86cb90ff1.png)

**What you expected:**

* [x] Subject
* [x] Example
* [x] Button

**Comment by rouletout** [comment]
in translation queue, closing
