### ISSUE TITLE
Spanish translations - Quality indicator not translated in friend's ascents

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3861]
**What happened?**
See screenshot

Example url(s) to reproduce the problem:
https://www.thecrag.com/ascents/by-friends-of/killakalle/

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/109306113-fb0a6500-783e-11eb-9a64-6bf4e4504d52.png)

**What you expected:**

* [x] translated

**Comment by rouletout** [comment]
Available since last release, closing
