### ISSUE TITLE
Spanish translations - "Project" not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3863]
**What happened?**
See screenshot

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/routes

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/109306681-ca76fb00-783f-11eb-8d2f-43f7998a82a7.png)

**What you expected:**

* [x] translated

**Comment by rouletout** [comment]
Available since last release, closing
