### ISSUE TITLE
Spanish translations - "Search discussions and more" not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3864]
**What happened?**
See screenshot

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/topos

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/109306918-29d50b00-7840-11eb-82b6-1961cdbbfbb1.png)

**What you expected:**

* [ ] translated

**Comment by rouletout** [comment]
put in translation queue, closing
