### ISSUE TITLE
Spanish translations - Ascent filters

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3865]
**What happened?**
I believe the translation of "Has" should rather be "Tiene" instead of "Ha". A Spanish native should take a look here, though.

Additionally, there are a couple of translations missing, see screenshot.

And one more suggestion: add high-commas to the title when you add the filter options. For better readability.

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/ascents/has/with/?sortby=when-climbed,desc
https://www.thecrag.com/en/climbing/spain/valencia/ascents/has/with/?sortby=when-climbed,desc

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/109307694-52113980-7841-11eb-9205-67f6310700cd.png)

**What you expected:**

* [ ] Ha -> Tiene  (?)
* [ ] Filter options translated in title
* [ ] All filter options translated

**Comment by rouletout** [comment]
In translation queue, closing - but please keep en eye open as these are constantly expanded and sometimes the translations lag behind
