### ISSUE TITLE
Odd grade system in gym makes grades disappear

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#3866]
**What happened?**

A very old Dutch climbing wall uses UIAA grades. It looks terrible because the {UIAA} part pushes the grade out of the grade box.

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/netherlands/area/2494402569

**What you expected:**

No {UIAA} prefix to the grade. I guess setting the whole wall to UIAA would work, but I'm not sure if that is possible. Converting everything to FR is possible, but I'd rather keep the grades.

**Comment by matozoid** [comment]
I see that it has been set to UIAA now, so the immediate problem is gone.

**Comment by rouletout** [comment]
Context changed, closing
