### ISSUE TITLE
Boulder grade is sports grade in overview

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#3868]
**What happened?**

In a boulder-only area, the grades at the top of the crag are using non-boulder grades.

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/netherlands/area/4512640071
Grades are FB 4B to 6B+, but the overview shows "FR" and goes to 7a+.

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/55701/109848153-3ac2b980-7c50-11eb-987e-a6a0a9d17f50.png)

**What you expected:**

I expect a bouldering area to consistently use bouldering grades.

**Comment by rouletout** [comment]
This seems weird - it is correct for some areas but not for others. We will assess that.

**Comment by rouletout** [comment]
This is fixed, closing
