### ISSUE TITLE
Spanish translations - Renombrar

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3878]
**What happened?**
Spanish uses infinitive instead of conjugated verb

Example url(s) to reproduce the problem:
https://www.thecrag.com/event/4579127724

Ideally also provide screenshots:

English is correct:
![image](https://user-images.githubusercontent.com/30682796/112136232-fd0ddc80-8bce-11eb-83e8-43af55d4b45e.png)

Spanish uses infinitive
![image](https://user-images.githubusercontent.com/30682796/112136425-3b0b0080-8bcf-11eb-8898-ee7f47f462bb.png)

**What you expected:**

* [x] Renombrar -> Renombró

**Comment by rouletout** [comment]
Fixed with next push, closing
