### ISSUE TITLE
Forums: World Forum

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3881]
Support request: make it possible to unsubscribe from World Forum / make it harder to post on world forum.

Too many messages are posted on world level either by novices or as spam. Something should be done about it.

Ideally also provide screenshots:

**What you expected:**

Yes, mostly annoyed by the spam posts... but even good posts shouldn't give notifications when users aren't subscribed to a forum, imho.
Making posting harder will definitely improve the content and trigger less notifications but I can imagine people still wanting to know ongoing discussions unless they are about the crags they subscribed to.

**Comment by DaneEvans** [comment]
Same as #3650

**Comment by rouletout** [comment]
Dup, closing
