### ISSUE TITLE
Wrong update activity

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3883]
**What happened?**
The update activity shows that I **uploaded** a photo. However, I **deleted** a photo - at least that's what I believe triggered the event, because I did not upload any photo.

Example url(s) to reproduce the problem:
https://www.thecrag.com/event/4629101751

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/113896080-e3bd8080-97c9-11eb-9d8e-b7ac8a42695c.png)

**What you expected:**
Not quite sure here. Either one of the following would probably be better
* [ ] Indicate that a photo was deleted, or
* [ ] Do not show a stream event at all

**Comment by rouletout** [comment]
+1, same for this event: https://www.thecrag.com/event/4707651255

I disabled a photo for someone and now it says I added it.

<img width="627" alt="Screenshot 2021-04-29 at 16 05 41" src="https://user-images.githubusercontent.com/19162952/116618655-f3ca0b00-a904-11eb-9070-e56a756f75ac.png">

**Comment by rouletout** [comment]
this is fixed, closing
