### ISSUE TITLE
Spanish translations - Typo "registro" o -> ó

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3885]
**What happened?**
It should be "registró"

Example url(s) to reproduce the problem:
https://www.thecrag.com/event/4626229521

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/113896854-9ab9fc00-97ca-11eb-96a2-3b3f624f1091.png)

![image](https://user-images.githubusercontent.com/30682796/113897127-e10f5b00-97ca-11eb-893b-076035234370.png)

**What you expected:**

* [x] registro -> registró

**Comment by rouletout** [comment]
Fixed, available on next push, closing
