### ISSUE TITLE
Route has 3 stars but shouldn't have any - reason unclear

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#3886]
**What happened?**

Kia ora: https://www.thecrag.com/en/climbing/new-zealand/lake-taupo/route/4303397283

<img width="742" alt="Screenshot 2021-04-08 at 10 26 50" src="https://user-images.githubusercontent.com/19162952/114053864-f16c1800-9854-11eb-8ab9-4ec1f50794b1.png">

<img width="825" alt="Screenshot 2021-04-08 at 10 27 16" src="https://user-images.githubusercontent.com/19162952/114053929-0183f780-9855-11eb-8923-efd9dc20990b.png">

**What you expected:**

No stars and understanding why this route has 3 stars...

**Comment by scd** [comment]
I don't know what is going on here. It is not ok so may have been fixed with other fixes.
