### ISSUE TITLE
Spanish translations - "set by" not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3890]
**What happened?**
The "Set"/ "Set by" for routesetters is not translated to Spanish. Not sure what it should be, though.

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/area/2561080014

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/115305071-13736d80-a166-11eb-8b34-80ce959622eb.png)

![image](https://user-images.githubusercontent.com/30682796/115305324-6b11d900-a166-11eb-9863-a429c3a11e2e.png)

**What you expected:**

* [ ] "Set" translated to Spanish
* [ ] "Set by" translated to Spanish

**Comment by rouletout** [comment]
keys added, in translation queue

**Comment by rouletout** [comment]
done, closing
