### ISSUE TITLE
Photo deletion errors

### ISSUE THREAD

**Issue by Poppy28** [theCrag/website#3892]
**Photos still viewable after deletion**

After deleting a photo it is still able to be viewed by at least the user who uploaded it, unsure of others. This is a privacy risk for photos that need to be removed. When trying to delete again it comes up with the following error.

Example url(s) to reproduce the problem:

https://www.thecrag.com/photo/1866828126

Ideally also provide screenshots:

![Screenshot_20210423-095247_Chrome](https://user-images.githubusercontent.com/83044835/115798541-d8996000-a419-11eb-8a62-448e175dc986.jpg)

**What you expected:**

* [ remove deleted photos from profile -> photos section ] item 1
* [ remove deleted photos from any other area they may pop up. Eg. Preview photos for area ] item 2

**Comment by rouletout** [comment]
@Poppy28 thanks for this - can you please explain how you tried to delete it? It doesn't seem to have happened at all. The correct process would be:

1) Click Edit Foto
2) Click Remove Foto
3) Confirm deletion

Cheers

**Comment by Poppy28** [comment]
Yes, this is the problem I am reporting.

Your profile -> Photos -> [Select Photo] -> Edit Photo -> Remove Photo -> [Confirm Delete? Yes] Next -> ERROR

**Comment by killakalle** [comment]
Problem already reported a while ago here:
https://github.com/theCrag/website/issues/3708

**Comment by rouletout** [comment]
@Poppy28 I have disabled the photo for you while we work on the issue

**Comment by Poppy28** [comment]
> @Poppy28 I have disabled the photo for you while we work on the issue

Thanks for that! Can I ask for one more photo to be removed?
https://www.thecrag.com/photo/1034946945

Cheers!

**Comment by rouletout** [comment]
such a great pic :-) - I stll disabled it...
