### ISSUE TITLE
Commenting on update activity of secret crag makes topo public

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3897]
**What happened?**

1. Update a topo in a hidden crag
2. Comment on the activity stream 
3. Log out and go to your profile

Observe that the activity, the comment and also the topo(!) is now public.

Example url(s) to reproduce the problem:
https://www.thecrag.com/event/4730474370

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/117124955-3ffbcc00-ad99-11eb-9199-dd30827b035e.png)

**What you expected:**

* [ ] Topo not visible to public
* [ ] Activity not visible to public
* [ ] Comment not visible to public

**Comment by killakalle** [comment]
Maybe just updating a hidden topo is sufficient to expose information. I deleted my comments and the activity plus topo are still shown on the public profile link:

![image](https://user-images.githubusercontent.com/30682796/117132794-9bcb5280-ada3-11eb-9dfc-507cc2b59a2a.png)

**Comment by scd** [comment]
Commenting on an event creates a second discussion event which is the source of the issue. There is probably some missing logic with the second discussion event.

I have used an admin function to hide both events.  The problem is still there but exposed event is no longer there.

**Comment by scd** [comment]
I have done a bit of work on this but it is really complex. In the stream query the permissions to see comes from the area which the stream event is associated with, which is typically top level crag. In this case the garage is not the top level crag so the permissions test misses from the point of view of filtering out the overall event. 

I have fixed a number of edge cases but not the core failure case.

So the next thing I will look at is how to filter the activity items.

**Comment by scd** [comment]
Should be fixed now, closing
