### ISSUE TITLE
Lists: Missing List for migrated circuit

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3899]
I believe at least one of mine circuits is not migrated. I had a circuit of must climbs in the Donautal.

![Screenshot_20210511-181148.png](https://user-images.githubusercontent.com/1528540/117849559-b8c0c380-b284-11eb-8c49-413fc572f278.png)

**Comment by scd** [comment]
Probably a bug I will look into this as release followup. Maybe next week as I am on my paying job until the end of this week now.

**Comment by scd** [comment]
Thanks for the heads up with this bug. It looks like I only migrated one list for each account. I have rerun the migration with the script fixed. 

So there are now two more lists for @lordyavin 

https://www.thecrag.com/lists/by/@captainhook

Note that you can also still see your old circuits if you know the url structure.

https://www.thecrag.com/circuits/by/@captainhook

We will keep this url and circuits data for a little while, but eventually they will be removed.
