### ISSUE TITLE
Lists: Private list can be accessed by everyone

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3903]
I set my [whish list](https://www.thecrag.com/en/list/4751397522) to be private but knowing the URL everyone can access the list.

![grafik](https://user-images.githubusercontent.com/1528540/117861160-6a65f180-b291-11eb-9cab-93d2bc41b833.png)

**What I expected:**

* [ ] Private lists are really private! Only the owner is able to access the list.
* [x] Private lists don't appear in the [search](https://www.thecrag.com/lists/by/@captainhook)
* [ ] Private lists don't appear in external search engines

**Comment by scd** [comment]
Definitely a bug.

**Comment by scd** [comment]
I have hot fixed this
