### ISSUE TITLE
Lists: Reload route details page after adding to list

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3905]
**What happened?**

After adding route to a list, the lists info ![grafik](https://user-images.githubusercontent.com/1528540/117873378-00087d80-b2a0-11eb-9ff2-2b43d9a67568.png) is not updated.

**What you expected:**

* [x] Instant update of the info without manual reload

**Comment by scd** [comment]
Can you outline the workflow. Have you got two tabs open?

**Comment by lordyavin** [comment]
Actually I had more than one tab open but I'm not expecting to reload other tabs. Just the one where I made the change. I will upload a screen video.

**Comment by lordyavin** [comment]
https://user-images.githubusercontent.com/1528540/117928466-e1d06b00-b2fb-11eb-8b09-814c81d5734e.mp4

**Comment by scd** [comment]
Oh I get it. 

We do not have such a great frontend framework so it is really painful to update the UI. I will just reload for now.

**Comment by scd** [comment]
I have fixed this in dev but i don't think this will be hotfixed.

**Comment by lordyavin** [comment]
Tick the task cemheck box 😉

**Comment by scd** [comment]
Hah, I just assumed you would not want reload because it is totally unacceptable in another project I am in.
