### ISSUE TITLE
Control what is visible in feed

### ISSUE THREAD

**Issue by Channass** [theCrag/website#3909]
Thank you for the new 'lists' feature but is there any way I can disable showing the routes I'm adding to my lists to be visible in my feed. I found the feature very useful so will use it often but that is going to spam mine and others feed? 
![Screenshot_20210512-060321](https://user-images.githubusercontent.com/54959990/117878260-e9d2df80-b2e8-11eb-8d22-b482948b7966.png)

**Comment by scd** [comment]
If it is private then only people you permit will see it on the feed

**Comment by rouletout** [comment]
These lists are public - this is why they show on your feed. Closing.

**Comment by Channass** [comment]
How come? I see them as private. Can you double check for me please? 
Best regards 
Martin 
--
Sent from myMail for Android Wednesday, 12 May 2021, 09:23am +10:00 from rouletout  ***@***.*** :

**Comment by rouletout** [comment]
Yes they are private (see above) - so only users that follow your ascents will see it
