### ISSUE TITLE
List sequence messed up

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3910]
**What happened?**
I played around with the list a bit (adding/removing routes, changing sequence). Somehow I ended up with a list where two items have the same sequence number. When I try to change the sequence of the third item from 2 to 3, it still keeps showing 2. So, unable to change the sequence.

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/lista/4751775198

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/117919335-1ab51380-b2ed-11eb-97d5-21510f0cfad8.png)

![image](https://user-images.githubusercontent.com/30682796/117919379-2bfe2000-b2ed-11eb-87f6-0d10ba743249.png)

**What you expected:**

* [ ] No double usage of sequence numbers
* [ ] Assigned sequence number gets successfully saved and displayed

**Comment by scd** [comment]
It looks like the backend was not rebasing sequences after deleting an item. This is hotfixed. @killakalle can you please validate with your list and close.

Note that I have not migrated your bad list sequencing. This should just fix itself after you add another list item or remove a list item. You will have to reload after removing a list item.

**Comment by killakalle** [comment]
Fixed.
