### ISSUE TITLE
Photos can't be edited anymore 

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3911]
**What happened?**
According to Ulf I should be able to see this:
![image](https://user-images.githubusercontent.com/30682796/117921765-96b15a80-b2f1-11eb-90da-12c4568806fa.png)

However I don't - see screenshot below

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/117921698-7b464f80-b2f1-11eb-938b-f0eb057b4086.png)

**What you expected:**

* [ ] Can set photo as profile webcover

**Comment by lordyavin** [comment]
Looks like we got a general issue with editing photos. Even if I uploaded it I don't see the "edit" button! @killakalle I propose to rename the issue accordingly and set the corresponding regression label.

**Comment by birgander2** [comment]
Same for me, I see only the "Done" button.

**Comment by lordyavin** [comment]
@birgander2 so do you agree that it is an regression of photo editing?

**Comment by birgander2** [comment]
Hard to say, but quite likely yes

**Comment by scd** [comment]
Yes there was regression. I have hot fixed the bug.
