### ISSUE TITLE
Spanish translations - Update ascents not translated fully

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3916]
**What happened?**
Edit an ascent
See screenshot

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/118414083-f4072c00-b6a2-11eb-8f5d-0f55b13ac5f0.png)

**What you expected:**

* [x] Title in Spanish
* [x] Quality indicators in Spanish

**Comment by rouletout** [comment]
fixed, closing
