### ISSUE TITLE
Subareas not appearing

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#3917]
**What happened?**

The sub-area's of Le Grand Poirier do not appear in the left box.

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/belgium/area/4768154160

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/55701/118536351-ef4a8280-b74b-11eb-9ce6-00570117679a.png)

**What you expected:**

The three sub-areas in the white box.

They are in existence for over 24 hours now, so I assume it is not a caching issue.

**Comment by scd** [comment]
Le Grand Poirier is flagged with our sensitive area access restrictions. 

https://www.thecrag.com/climbing/belgium/area/2683773003

If you have permissions you should still be able to see the nav links so that is a bug.

**Comment by scd** [comment]
hotfixed the issue
