### ISSUE TITLE
Spanish translations - Add Route title not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3920]
**What happened?**
Add a new route, title not translated
See screenshot

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/119243018-6ffdea00-bb63-11eb-9d97-8fa6003764b5.png)

**What you expected:**

* [x] Title in Spanish

**Comment by rouletout** [comment]
Fixed, closing
