### ISSUE TITLE
Changing gear style implicitly changes grading context

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#3922]
**What happened?**
Gear style implicitly changes grading context: When changing the gear style from "Sport" to "boulder", the original UIAA-rating is interpreted in another fashion (fb-scale?). I know, UIAA is not *usually* used for boulder problems, still this behaviour somewhat unexpected.

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/germany/berlin/route/2670475854

**What you expected:**
Also accept boulder problems to be rated in UIAA.

**Comment by scd** [comment]
Context stays the same, but the grade system priorities may be different for gear types. So this means a 4c can be interpreted as a UIAA grade for a trad route and a FB grade for a boulder route.

To see exactly what the priorities are go to: 

https://www.thecrag.com/en/article/gradesonthecrag#article.gradesonthecrag.header.grade-contexts

Context was introduced so we could provide a way of distinguishing between two different grading systems when they have the same text. It is not possible to know what 4c means without context.

Context must be set so there are no conflicts in interpretation. Any grading system directly assigned to a context will be used first for interpretation of raw text.

You can assign UIAA grade to a boulder problem, but you need to prefix the grade text with UIAA:4c so the system knows how to explicitly interpret it. So technically the system already does what you have asked for in this issue.

@MelwinQ can you please look at the rules and let me know if there is an explicit change to the context grade assignment rules. 

If we can find new configuration then we are good, but there is no technical fix here.

**Comment by MelwinQ** [comment]
I guess I perfectly understand the need for setting "context" as the "unit system", a number has to be interpreted with.
What I find irritating is that in the abovementioned example the grade context is set to "UIAA", still, the interpretation of "7-" changes from "7- (UIAA)" to "7 (fb)". I would expect that the selected grade context "UIAA" would have priority over the implicit assumption "this is a boulder problem, so the grading is likely in FB". But perhaps I got somthing wrong.
I can only force the correct behaviour with setting the grade to "UIAA:7-" (as suggested in the help page). As said, I would have expected this prefix to be already set by the selection in the "grade context" dropdown.

**Comment by rouletout** [comment]
I'm closing this as it works as designed. @MelwinQ if you have a specific context change request (eg changing the boulder system for a specific context) please open a separate issue, thx

**Comment by MelwinQ** [comment]
I think the way of inferring the context grade is well thought of, no complaints, so I will not open another issue.
As I understand it, currently the context for the example above was determined by the rules to be "UIAA", changing to style "boulder" switched this to "Fb", right? What I find confusing is that the context "UIAA" is/appears still explicitly selected in the "context dropdown menu, while it apparently overrun by a different internal choice.
Could it be an option to
a) mark the context as "unset", "inferred" or "inherited", to show that it was not selected in this case, but inferred
OR
b) interactively change the context in the dropdown when changing the gear style (for the coloured grade label next to the grade field this already happens: 7- (orange) changes to 7 (red)).
Apologies for being so pesky, just trying to help.

**Comment by scd** [comment]
I think I know the confusion now. The context selection of UIAA is
different from the grading system UIAA. I think it was an unfortunate
decision that we made for these to share the same name.

To manage your rare exception please type in 'UIAA:4a' into the grade.
