### ISSUE TITLE
Empty route section

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#3927]
**What happened?**

The Liege area has had a useless empty "routes" section for quite a while now.

Example url(s) to reproduce the problem:
https://www.thecrag.com/en/climbing/belgium/area/2206140393

![Screenshot_2021-06-03_18-50-32](https://user-images.githubusercontent.com/55701/120682361-abba7d00-c49c-11eb-8bc8-1350c14519ac.png)

**What you expected:**

No routes section, since there are no routes.

**Comment by rouletout** [comment]
This is due to the annotation and listed as an issue here: https://github.com/theCrag/website/issues/3661 - I referecne the area there and close this.
