### ISSUE TITLE
No change activities logged for specific area 

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3929]
**What happened?**
I've just made quite a few changes in La Jarra - Buñol. None of the updates are shown in the Dashboard or on the area node.

Example url(s) to reproduce the problem:

Area where changes were made (La Jarra)
https://www.thecrag.com/es/escalar/spain/valencia/area/1452163398

E.g. here. I've just created those two routes; Nothing shows in the Activity log.
![image](https://user-images.githubusercontent.com/30682796/122131340-55085800-ce39-11eb-8c1e-8247e4832df9.png)

On the route itself the activity is shown
https://www.thecrag.com/es/escalar/spain/valencia/route/4912482708
![image](https://user-images.githubusercontent.com/30682796/122131743-eb3c7e00-ce39-11eb-8617-b31f05bf43d5.png)

I don't know if it's a general issue or just specific to that sector. Just to test I also changed something somewhere else, and this update does show in the feed
![image](https://user-images.githubusercontent.com/30682796/122132312-e1674a80-ce3a-11eb-91ce-74b257d22c9a.png)

Not sure if related, but Simon made some hotfix on what updates are shown where in this issue
https://github.com/theCrag/website/issues/3912

Ideally also provide screenshots:

**What you expected:**

* [ ] Activity logs shown on affected areas
* [ ] Activity logs shown on Dashboard

**Comment by killakalle** [comment]
Changes made today are logged again. 

![image](https://user-images.githubusercontent.com/30682796/122251846-2aff7600-cecb-11eb-89ff-9afd60b01fd6.png)

However, the changes from yesterday have not appeared. Maybe temporary glitch(?). Closing again

**Comment by killakalle** [comment]
Made changes today in the same area. Again no updates in the stream. Reopening the issue

**Comment by rouletout** [comment]
@killakalle is it only invisble for you or for everyone?

**Comment by killakalle** [comment]
@rouletout 
I don't see the logs either while not logged in.

**Comment by rouletout** [comment]
@killakalle we are struggling to fidn what is going on here. We have heard similar input from one more user but can't locate it. if you have anything that could help, please put it here. We will continue to look into that.

**Comment by killakalle** [comment]
@rouletout 

Just to confirm for you. I logged in with a different user than my own and the situation looks the same. None of my recent update activities in the area La Jarra are shown:

![image](https://user-images.githubusercontent.com/30682796/123387046-a03c0c80-d597-11eb-911e-0b85e8540f20.png)

Other than that I'm afraid I have no clue what additional information  I could provide

**Comment by rouletout** [comment]
@killakalle thanks - I don't know either - just more examples if you encounter them I guess....

**Comment by skomaroff** [comment]
I can report a past example of what seems to be the same bug.  These changes didn't show up for about a day after I made them (but do now): https://www.thecrag.com/event/4913162628

**Comment by scd** [comment]
The not appearing for a day issue may be a timezone thing. There is a potentially confusing design aspect to streams where stream events are assigned to a day based on the timezone of the area where the climbs are located. This means that stream events can be assigned to the previous day relative to some users.

**Comment by scd** [comment]
Hmmm, this seems like a common issue but I cannot work out what is missing.

One thing that you can do to help is identify the activity which was missing by typing /activity after the area. For example

https://www.thecrag.com/en/climbing/spain/valencia/area/1452163398/activity

Circle the activity in a screen shot and provide URLs. Then find the event (as per @skomaroff ) where you think the activity is missing from. If you cannot find the event at all then the area you think the event should be shown.

**Comment by killakalle** [comment]
Here are two stream events that are missing from the stream updates on area "La Jarra"
https://www.thecrag.com/en/climbing/spain/valencia/area/1452163398

Missing stream events
- https://www.thecrag.com/event/4917219294
- https://www.thecrag.com/event/4912458714

![image](https://user-images.githubusercontent.com/30682796/126968177-7273de20-31f3-417f-abf4-fddae0e29f60.png)

**Comment by scd** [comment]
Thankyou @killakalle that is explicit enough to investigate.

**Comment by scd** [comment]
Notes for self. I have found something really weird when querying on dates

The following url finds the event on the 18th:

https://www.thecrag.com/en/climbing/spain/valencia/area/1427301387/stream?startDate=2021-06-10&endDate=2021-06-18

But this one does not

https://www.thecrag.com/en/climbing/spain/valencia/area/1427301387/stream?startDate=2021-06-11&endDate=2021-06-18

**Comment by scd** [comment]
OMG, this was pretty subtle interaction between two sections of code making slightly different assumptions. It was a systemetic issue when events were summarised, however if there was another non-summarised update to any of the same routes in the stream chunk then it would work. This made it appear random.

Hot fixed.
