### ISSUE TITLE
"?" in route edit form not working

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#3932]
Small bug fix:

The "?" left of "bolts" in the edit route form is not working (small black "?" instead of the other 2 working bigger blue "?").

You probably could add much more "?" on nearly every field, bit i guess not much people will click it anyway...

**Comment by lordyavin** [comment]
@FF-Flo are you using the form on desktop or mobil?

**Comment by FF-Flo** [comment]
Both, Desktop (Linux) and mobil (Android).
In the route edit form you have the dropdown menu for the numer of bolt. Above stands "bolts" and left of this is the not working black "?". But right of "Grades" and "Structured tags" are blue "?" which leads you to the help pages. I guess that was the intention for the "?" at bolts too.

**Comment by rouletout** [comment]
This is not a link but just a pop up saying without anchor - does that show for you?

**Comment by FF-Flo** [comment]
Okay, the popup is working. Because the other blue "?" are leading to links, it was not obvious to me, that the black "?" is only a hint to the popup.
