### ISSUE TITLE
Are there plans for a Kudos feature?

### ISSUE THREAD

**Issue by kleiren** [theCrag/website#3933]
Are there plans for a kudos feature "a la" Strava? Strava allows kudos in every run to show encouragement and activity in the community, it would be nice to have something similar in theCrag for ascents and contributions.

**Comment by rouletout** [comment]
Did you see that you get CPR points for all ascents you log? this is very close to what you suggest, no?

**Comment by kleiren** [comment]
@rouletout I mean a way for other users to acknowledge lazily your ascents or contributions. In Strava that's kudos, in Facebook it would be the likes.
