### ISSUE TITLE
Change route number

### ISSUE THREAD

**Issue by iocast** [theCrag/website#3935]
Is it possible to change the route numbers (not sequence)?
![image](https://user-images.githubusercontent.com/1773589/123599538-fe662b00-d7f5-11eb-8fab-c16163d204e5.png)

When you delete routes (e.g. 1, 2 and 3 like in the pic). then you have no chance to change the route numbers.
Maybe in the topo admin a new functinoality to change the numbering of routes would be nice or something like automatic renumbering starting from 1.

**Comment by scd** [comment]
There is currently a bug where deleting does not automatically change the route numbers. There is a daily script which cleans this up.

Please let me know if it is still a problem in 24 hours

**Comment by lordyavin** [comment]
![2021-07-01_01h26_27](https://user-images.githubusercontent.com/1528540/124043476-5fb31780-da0b-11eb-990d-679e1b0e98eb.png)
