### ISSUE TITLE
Spanish translations - Follow a forum

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3939]
**What happened?**
Seems strangely translated:

Ver - See
Seguir - Follow

Example url(s) to reproduce the problem:
https://www.thecrag.com/forum/how-to

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/124239062-9aa37100-db19-11eb-81aa-7c119d394455.png)

**What you expected:**

* [x] Check translations by native / agency - correct if needed

**Comment by rouletout** [comment]
Fixed, will be available on next push, closing
