### ISSUE TITLE
Photo upload broken

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3943]
**What happened?**
Cannot upload photos anymore. Upload remains at 0%

Example url(s) to reproduce the problem:
Chrome:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?R=https%3A%2F%2Fwww.thecrag.com%2Fphotos%2Fuploaded-by%2Fkillakalle&C%3AState=17416&D%3ANetworkNodeID=7546063&C%3APushReturnURL=https%3A%2F%2Fwww.thecrag.com%2Fphotos%2Fuploaded-by%2Fkillakalle&C%3AHideNavigation=1

Safari:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?R=https%3A%2F%2Fwww.thecrag.com%2Fphotos%2Fuploaded-by%2Fkillakalle&C%3AState=17416&D%3ANetworkNodeID=7546063&C%3APushReturnURL=https%3A%2F%2Fwww.thecrag.com%2Fphotos%2Fuploaded-by%2Fkillakalle&C%3AHideNavigation=1

Ideally also provide screenshots:
Left Chrome, right Safari
![image](https://user-images.githubusercontent.com/30682796/124920000-270cd280-dff7-11eb-8709-36aa063fd147.png)

**What you expected:**

* [ ] Can upload photos

**Comment by rouletout** [comment]
works for me, is this a specific area?

**Comment by killakalle** [comment]
Could not upload a picture to a forum post nor to photos in my profile.

Let me check again from my end on some other areas.

**Comment by killakalle** [comment]
I have the same issue when I try to upload a photo to a climbing area, e.g. here
https://www.thecrag.com/es/escalar/spain/jerica/area/166592070/photos

https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?R=https%3A%2F%2Fwww.thecrag.com%2Fes%2Fescalar%2Fspain%2Fjerica%2Farea%2F166592070%2Fphotos&C%3AState=17416&D%3ANetworkNodeID=166592070&C%3APushReturnURL=https%3A%2F%2Fwww.thecrag.com%2Fes%2Fescalar%2Fspain%2Fjerica%2Farea%2F166592070%2Fphotos&C%3AHideNavigation=1

**Comment by killakalle** [comment]
Works again. Closing
