### ISSUE TITLE
Spanish translations - La calidad general X de las Y valoraciones

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3949]
**What happened?**

I think it should be translated:
"La calidad general 67 de las 5 valoraciones."

instead of currently:
"La calidad general 67 de las valoraciones 5."

Example url(s) to reproduce the problem:
English:
https://www.thecrag.com/en/climbing/spain/cavallers/route/346200783

Spanish:
https://www.thecrag.com/es/escalar/spain/cavallers/route/346200783

Ideally also provide screenshots:
English:
![image](https://user-images.githubusercontent.com/30682796/125929310-ddb3c92b-d523-4fb6-8c2a-8f73929af351.png)

Spanish:
![image](https://user-images.githubusercontent.com/30682796/125929430-d58ba42d-f301-43b1-bc94-ab0da5a1ef0e.png)

**Comment by rouletout** [comment]
Fixed on next push.
