### ISSUE TITLE
How to forum links broken or wrong

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3950]
**What happened?**
Several links to the How to forum are broken or wrong

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/126677612-5d54b68d-9218-4eb7-81f5-f52b3e0337e0.png)

![image](https://user-images.githubusercontent.com/30682796/126677682-adef4b3a-4876-47f0-8fe6-e3cf61fa687d.png)

https://www.thecrag.com/discussion/5034200493/thecrag-user-scripts#m5037055602
![image](https://user-images.githubusercontent.com/30682796/126678031-ee6fa454-976b-4501-b8e2-4ea171c1d5da.png)

Some id number is used instead of readable name
![image](https://user-images.githubusercontent.com/30682796/126678266-6be5573f-83e7-43f3-8940-24216cd2c233.png)

**Comment by killakalle** [comment]
Another one:
![image](https://user-images.githubusercontent.com/30682796/126678499-8f943af9-7d49-4a71-948c-31c597cac4f8.png)

**Comment by scd** [comment]
I think I hot fixed these.
