### ISSUE TITLE
Spanish translations - Ascent detail page not translated

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3951]
**What happened?**
The entire details of that page are not translated to Spanish

Example url(s) to reproduce the problem:
https://www.thecrag.com/ascent/2861070954

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/126781907-055c8b35-aaee-499c-8433-559575988739.png)

**Comment by rouletout** [comment]
This and the missing keys will be available with next release, closing
