### ISSUE TITLE
Acknowledgment of country

### ISSUE THREAD

**Issue by BahBes** [theCrag/website#3953]
Hi everyone, 
I'm new here, I've read the guidelines but sorry if I haven't done this perfectly.
I think it would be great to have an acknowledgment of country feature added for all locations in Australia. This could either be through an extra box to fill in alongside 'description' and 'summary' etc or a seperate box entirely. 
Could it even be linked with established databases of traditional owners and GPS to be autofilled? I am no programmer so imagine this could be challenging.
I also think it is important that Indigenous people are involved or consulted about this.

This addition would be a positive and proactive step to repair the currently difficult relationship between climbing, indigenous sites and land managers in Australia.

**Comment by rouletout** [comment]
Hi @BahBes thanks for raising this. We actually have a statement on the page for Australia: https://www.thecrag.com/en/climbing/australia 

We also have separate statements on certain areas that were created by members of the First Nation community. I'm happy to put you in contact with the main editors if you are interested.

Please contact us via support if you wish to do so.

Thanks again!
