### ISSUE TITLE
New Tag: destroyed 

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3954]
A route, sector or a whole crag can be destroyed by erosion or humans. The closed tag has not the correct semantic to use it this context. Therefore I request a new tag for access: destroyed

**Comment by rouletout** [comment]
Shall we put that in Access (Legality) or "Condition" ?

**Comment by lordyavin** [comment]
Condition fits better I assume

**Comment by lordyavin** [comment]
Any updates on this? This should be  matter of configuration only, isn't it?

**Comment by scd** [comment]
It is next on my list, probably after a planed release on Monday.

Some of it is configuration. There are also translations. I will not be
doing an image at this stage.

**Comment by lordyavin** [comment]
Unfortunately I am on vacation and can't provide an icon too. Sorry next time I will create one in the first place.

**Comment by scd** [comment]
Done
