### ISSUE TITLE
Couldn't assign Webcover to more then one node

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#3956]
Tried to set an image as webcover to a node and one of it ancestors. The second assignment (to the node) removed the first one (from the ancestor). Is this a regression?

**Comment by rouletout** [comment]
@lordyavin can you please post the photo URL and teh URLs of teh areas? Makes it easier to investigate, thanks

**Comment by lordyavin** [comment]
https://www.thecrag.com/event/5139118878

Ancestor : https://www.thecrag.com/en/climbing/austria/area/518688360

**Comment by rouletout** [comment]
Just assigned it to both, Walgau and Bürser Platte and works fine - please check again

**Comment by lordyavin** [comment]
I see that it worked for you but why didn't it in the first place for me?

**Comment by rouletout** [comment]
No idea - we can't reproduce the error. Please open again if it occurs elsewhere....
