### ISSUE TITLE
Annoying popup when changing names

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3958]
**What happened?**
I tried correcting a few typos in route names. I noticed that there is now an annoying pop-up that makes this simple workflow now a bit annoying.

The new behavior is
1. Edit
2. Change name
3. Save
4. Click OK on annoying popup
5. Save again

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/130809039-b0bd4ea8-24af-460a-bffb-baf1047b9a0e.png)

**What you expected:**

* [ ] No pop-up when changing a route name

**Comment by killakalle** [comment]
Wow, try changing the names of multiple routes through bulk edit. You get an individual pop-up for every single route!?!

**Comment by quaestor** [comment]
Would be interesting to know what the incentive was? Are too many users changing names when they shouldn't?

Karma threshold sounds a bit arbitrary. When is a contributer considered "mature" enough to make the right decision?
I would be in favour of  an alternative to showing an ugly `alert()` style box;  some good suggestions are already in in @FF-Flo's list.
