### ISSUE TITLE
[SX ]Saxon grade XIIIa is not working

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#3963]
This route is graded XIIIa, but when I add the grade, it still shows an empty grade field. Edit it again again and the grade is not there anymore.

https://www.thecrag.com/de/klettern/germany/sachsische-schweiz/gebiet-der-steine/route/4455534999

(up to grade XIIc it is working fine: https://www.thecrag.com/de/klettern/germany/sachsische-schweiz/gebiet-der-steine/route/4455536742)

**Comment by rouletout** [comment]
Fixed, closing
