### ISSUE TITLE
For crags, add explicit field describing how/where to contibute resources (funding + voluntary work) for crag set-up + maintenance

### ISSUE THREAD

**Issue by georg-d** [theCrag/website#3966]
Note: Reading only the bold text is giving you the summary.

**What happened?**

**As soon as it's not about gyms but rock crags, many climbers are not aware where the resources 1) financial funding for** 
* bolts, screws, dowels, etc. for routes as well as fixing in place loose flakes etc. 
* rungs, metal rods & tiles, steel cables, ladders, etc. to make access paths etc. secure & stable & easy to use, but also for protection from rocks etc. falling down from higher up the cliff
* experts like e.g. lawyers (e.g. for discussion with government agencies or contracts with land owners) or geologists (e.g. to evaluate whether a cliff is secure/stable enough to be officially open for climbing)

**and 2) work by volunteers**, sometimes with special know-how like e.g. bolting, sometimes without (e.g. pure muscle power multiplied with time for shovelling, gardening, scrubbing,...) **come from and how to contribute - despite ensuring a sufficient minimum of these resources is a core interest of all climbers:** Without them, the climbers' personal health is at risk and their sport is questioned. New crags won't be set up & officially opened for climbing. Existing crags cannot be maintained properly, might become hard to access, dangerous to use, and - e.g. after accidents with severe consequences - ultimatively closed. 

**This is not only true for visiting climbers, but also for locals.** There's a number of reasons:
* _Resource information is little visible._ How many crags have an information board? How many of them inform how you can contribute money & voluntary work? Now compare to gyms - there's nearly always a clear sign who's managing these resources and how & where you can or must contribute, so it is easy.
* _The ways to contribute to resources and how they are organized varies_ between countries, within countries, and even within regions or areas. For example for the crags in 1 hours range from my home, AFAIK there are 5 different ways for funding - ranging from governmental body, over a club of clubs or a club of individual persons, to individual bolters requesting funding by companies benefitting from crags like shops selling climbing gear or offering accommodation or paper guidebook publishers. Consequently,  very different authorities do manage the funds and they are granted according to quite differing rules.
* _The organization often has a complicated structure, making it difficult to find out on the internet how to contribute._ Usually, you'll come across several subject related clubs like "interest group climbing in region R" or "climbing association XY" or "alpine club XY" or "friends of crag ABC" - but how much which of them is related to set-up & maintenance of routes, and how much other parties like governmental offices, companies or touristic marketing clubs, is usually not understandable at one glace. 
* _Ways to contribute and organisation change over time._

So it's unclear to many climbers whom you can send money in which way to help re-bolting of that great route you climbed yesterday.

**It's also in theCrag's interest to make users come across that topic _and_ to make it easy for users to contribute to these resources.** While writing this, I am fully aware theCrag itself is not bathing in money like Donald Duck's uncle (his name differs across languages, e.g. Scrooge McDuck or Dagobert Duck), so why shall theCrag not only ask for it's own funding but additionally for others? Because
* theCrag's existence is quite dependant on set-up and maintenance of crags, i.e. without crags to climb at, most of theCrag is redundant
* many users may contribute to theCrag what they think it is worth (depending on usage intensity etc), so contributing for set-up and maintenance of crags is not reducing contribution to theCrag but is another, additional budget
* some users may not want to contribute to theCrag for various reasons, e.g. because they feel it's in the long run killing paper guidebooks that fund local maintainers, or because they don't have enough trust into a 'Pty Ltd' ('proprietary limited') type of private company structure in Australia to send money to, but into the local climbing club's guys seen yesterday bolting.
* By making users aware how to & ease the act to contribute to resources, theCrag would have a _very clear_ argument against organizations etc. discouraging Internet topos like theCrag because they leverage developed crags without giving back to crag maintenance. In fact, in the eyes of these formerly criticizing organisations etc. theCrag's support could surpass paper guidebook publishers donating "something" of their revenue, which is often a quite vague promise - even an specific one like 2% can hardly be verified by externals as virtually no publisher provides fully transparently all financial details - and the intertwisting of book purchase & bolt funding is de facto limiting the resource contribution of people that so not need/want to buy another topo of the same crags but only want to contribute to bolting - which they can easily do when both topo & bolt funding is clearly seperated.
* theCrag's users are obviously caring about the topic, as e.g. the intensity & length of discussions like [ Alternatives to support crag development and bolting](https://www.thecrag.com/discussion/3322830909/alternatives-to-support-crag-development-and-bolting#m3498461610) shows

**What you expected:**

**I suggest to add _an explicit field_ describing how/where to contribute resources for set-up + maintenance** for crags and maybe more data object types like regions, areas, or cliffs. An explicit field because
* _It can be easily inherited_ from higher hierarchy levels down. In contras, having resource information in e.g. description field means the resource information will only be visible as long as the description is _exactly identical_ across multiple levels of hierarchy - to my observation, that is very limited - or as it is manually repeated on each hierarchy level, but this is high introduction & maintenance effort.
* _People editing e.g. a crag are actively reminded by the system_ about missing resource information: They see the field name and that there is no content behind. In contrast, when resource information is e.g. in description field, the editors need to "see something is _not_ visible".
* _Editors can efficiently search for missing information_ and thus concerted actions to fill gaps become possible
* _We have more possibilities_, e.g. use the field to display the prices for a gym, define special right requirements to edit this field, show this field also when it's empty not only to editors but also to viewing users  (to remind them that bolts cost money and how to fund them is missing here, so they might research and add that), later refine into dedicated sub-fields,...

**Comment by georg-d** [comment]
Loosely relating to https://github.com/theCrag/website/issues/396 as sometimes, paper guidebook purchase funds bolts etc.

**Comment by scd** [comment]
I think this needs to be driven by local advocacy groups and where they ask for this kind of support we are very receptive to their ideas.  

Without any enhancements to the site this can be added to the general description and access fields. This should be happening now. 

Nobody should be holding off on these initiatives to wait for a new field.

Just to be clear, we are totally on board with the sentiment.

**Comment by rouletout** [comment]
Closing as per explanation by @scd

**Comment by georg-d** [comment]
IMHO it's a little sad adding a single field with absolutely standard implementation is too much DEV effort seeing that this decision massively increases the manual efforts to maintain the description field of areas - alone 340 to be checked in the small black forest...

**Comment by georg-d** [comment]
No, the arrangement does not differ between all areas, exactly that's one major point why I suggested a dedicated field.

You said funding info shall go to description or access field of the area (region/crag/cliff/sector). Typically, each area's description field contains text _specific for that single area_ - amenities like BBQ, comfort like snow/sun/shadow, climbing character, etc. Same applies for the access field - each crag, often each cliff is approached differently. Hence, both texts cannot be equal across hundreds of areas. Thus the text cannot be inherited from region "Black Forest" down to the lowest hierarchy level - while the proposed dedicated "funding field" could be (see 1st bullet in "What you expected"). So each single area's description and access fields must be _manually_ checked whether funding info already exists (would be automated with dedicated field, see 3rd bullet in "What you expected"), and if not, added, if yes, checked whether it's correct & up to date. And the latter task shall be repeated every few years. As the Black Forest has around 340 areas, roughly 340 descriptions & access texts need to be checked. For a small country like Switzerland (the most distant points are 350 km apart so like the distance Cairns-Townsville), it's already roughly 5500 areas. If checking description & acccess just takes 20 seconds, that's 30 hours of work - every few years and only for that one small country. Now calculate that on global scale. That's what I mean by your proposed solution _"massively increases the manual efforts"_ compared to a dedicated field where I expect <10 edits are sufficient for hundreds of areas.

**Comment by scd** [comment]
Access field is inherited? I think funding could reasonably fit there for trial purposes.

**Comment by georg-d** [comment]
I don't get your question, maybe we have a misunderstanding :-/ I just checked in the system. At least with my rights in the areas I looked at, I was unable to find a field named "access" in the GUI. I do find "approach"; this is what I wrote about - I wrongly remembered it's English name as "access" - and it does definitely not inherit (e.g. [Birkenwändle](https://www.thecrag.com/en/climbing/germany/schwarzwald/area/458182707) has empty field & shows nothing but parent has it filled). I also do find "access issues" which is definitely inherited (e.g. [Harzloch](https://www.thecrag.com/climbing/germany/schwarzwald/area/251616084) shows content from Germany). For both fields, funding information does semantically not match the [definition/description](https://www.thecrag.com/en/article/documentingacrag#adding-areas), for "access" also not the name, for "approach" it halfway matches the name because of the ambigouity of the EN term - but DE name "Zustieg" does not match at all.

I have the impression you want to avoid introducing a new field but prefer to use an existing one. IMHO field "ethic" is a candidate: Semantically, funding info would IMHO match the EN+DE names and the [definition/description](https://www.thecrag.com/en/article/documentingacrag#adding-areas). It does inherit, but inheritance is limited because e.g. policies concerning magnesia usage, wildlife protection, etc vary strongly - so quite a number of areas have the field filled, which breaks inheritance and requires to put funding information into that single area. I tried to find out a rough number of required edits, but [GUI search](https://www.thecrag.com/en/climbing/germany/schwarzwald/areas/?sortby=kudos,desc) does not allow to search for that field and from API help for [area](https://www.thecrag.com/en/article/api#areas) and [text completion](https://www.thecrag.com/en/article/api#515-text-completion) I was not able to understand whether the _search directives_ allow to search for `<fieldname> != null` - but I got the impression [bulk index query](https://www.thecrag.com/en/article/api#81-bulk-index-queries) may do the trick. I assume it's quicker for you to execute the query than to create an API key for me :)

**Comment by scd** [comment]
I am ok with ethic being used for a trial. 

Note that we have similar issues with other concepts such as 'welcome to country' for Australian crags which pays respect to indigenous Australians. There may be a whole set of fields we need.

Please note that we also already offer advocacy groups free sponsorships which enable them to communicate any message they want in an image.

I think the next steps is to some advocacy groups to commit to trial using theCrag for putting some information in the ethic field.

It is much better for us to collaborate with the relevant stakeholders as we end up getting a much better result.

Using ethic would be better because it means the content would get to our content partners where new fields would just be lost. For example our mobile app partners.

Also we are completely hammered with a huge amount of work and very little resources to get things done, so I strongly encourage that you do not wait until we make enhancements but rather get the avocacy groups doing something now.

**Comment by georg-d** [comment]
I understand both, your interest for limiting the sheer number of fields, and the benefit concerning visibility at partners. IMHO ethic is feasible & semantically matching - also for "welcome to country" and other aspects.

IMHO it would be good to mention the possibility of free sponsorship at https://www.thecrag.com/en/article/advocacygroups because I did not expect this exists: I sometimes saw an advocacy group displayed as an area's sponsor and looking through the help pages for the term "sponsor", I found [Business sponsorship](https://www.thecrag.com/en/article/business) & [Ad specifications](https://www.thecrag.com/en/article/adspecifications) mentioning budget, $ etc. and highlighting exactly the place I saw the advocacy group's banner being displayed. Hence, I assumed these advocacy groups are paying to theCrag for displaying their banner.

I will contact some organizations in my region about funding of bolts etc., and mentioning in ethics field, and report back here.

**Comment by rouletout** [comment]
@georg-d good point, I wasn't aware that the first bullet on teh Advocacy Group page isn't clear enough that this is free :-) - we'll include that in the next re-work...

**Comment by georg-d** [comment]
@rouletout Welcome :) Payed ads to raise funds would not surprise me as "good causes organizations" obviously often need to pay for info letter postage, flyers, etc that help to raise funds - elsewise they'd not waste 5-15% of their budget for that stuff ;)
