### ISSUE TITLE
Is this page dead, or at least the development?

### ISSUE THREAD

**Issue by Lars-jnk** [theCrag/website#3967]
Hi *,
I'm just curious if the page will be extended/improved or not.

Thanks for your answer,
ladida

**Comment by nicHoch** [comment]
have a look here: https://github.com/theCrag/website/pulse/monthly
and here: https://www.thecrag.com/forum/release

**Comment by Lars-jnk** [comment]
Ok, it's dead.
Look here: https://github.com/theCrag/website/issues

thanks!

**Comment by matozoid** [comment]
In a less offensive way: the source code in this repository doesn't seem to get updated. If this is an outdated place for the source code, it might be a good idea to remove it completely.
