### ISSUE TITLE
Wrong route sections in area with only sub areas

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#3968]
In this region ( https://www.thecrag.com/en/climbing/germany/area/5282200506 ) are only sub areas,  no routes. It is structured with annotations. It wrongly shows the route section above every annotation:

![wrong route section](https://user-images.githubusercontent.com/86301133/134642658-fcd1985e-03cf-4cdd-948a-c86f771488bb.png)

**Comment by rouletout** [comment]
This is covered here: https://github.com/theCrag/website/issues/3661 - closing
