### ISSUE TITLE
Boulder statistics in european grade context wrong in V-Skala

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#3969]
In most of the european bouldering areas the little statistic is wrongly shown in the american V-scale instead of the FB-scale which used everywhere in europe and should be defaut for these grade contexts.

UIAA (example: https://www.thecrag.com/climbing/germany/area/520311507 )
![uiaa](https://user-images.githubusercontent.com/86301133/134644473-4b0316d3-4154-4d84-b758-ec86950bdcd7.png)

UK (example: https://www.thecrag.com/climbing/united-kingdom/wales/south-wales/area/344100222 )
![uk](https://user-images.githubusercontent.com/86301133/134644548-34c3ed37-83df-4784-b428-2d86439605b1.png)

SWE (example: https://www.thecrag.com/climbing/sweden/area/722177532 )
![swe](https://user-images.githubusercontent.com/86301133/134644618-8a429c36-633b-447d-b539-921ba620eeea.png)

SX (example: https://www.thecrag.com/de/klettern/germany/sachsische-schweiz/erzgebirgsgrenzgebiet/area/13992157 )
![sx](https://user-images.githubusercontent.com/86301133/134644664-f087548e-6287-4cfa-8828-d4e642ffe630.png)

**Comment by FF-Flo** [comment]
Similiar with UIAA and wrong YDS statistic for this area (and others too): https://www.thecrag.com/en/climbing/germany/hohenzollernbrucke
![Bildschirmfoto vom 2021-09-26 19:37:23](https://user-images.githubusercontent.com/86301133/134817917-c70fd6a0-3fe3-4af7-9e9c-e2b0d4e1b5a7.png)

**Comment by scd** [comment]
Closing as I have fixed all these except for top roping. I have made a note internally to consider top roping so if that is not fixed please create a new card.

**Comment by scd** [comment]
Actually don't worry about relogging Top Roping because it is covered in the following card:

https://github.com/theCrag/website/issues/3978
