### ISSUE TITLE
Expose and rework publications / website ref's workflow and template

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#397]
For many areas, good information sources on the web are already available. I wished links to these had a separate field for entering and were inherited by children.
I once briefly touched that that issue in a mail to Campbell. From his reply I gathered that you want to avoid steering people away from your site. True enough.
On the other hand, for the user it is a great plus to locate the desired information - be it elsewhere, as long as is not yet contained in thecrag. In the long run, thecrag will also benefit, as entering route information is also much easier when you have something to help you ;-)

**Comment by rouletout** [comment]
(re-)Introduced in release 101 in the Plan your trip section, closing
