### ISSUE TITLE
Uploaded photos of private users not visible on area

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3970]
**What happened?**

When private users (= user profile set to private) upload photos to crags, those photos are not visible to other users. This seems odd to me. To me adding a photo to a crag is just another contribution - just like editing the description. Seems a bug to me.

If that was instead intentional behavior, it would be like implementing a private distributed photo gallery for private users. To me, that doesn't seem to make sense.

How to reproduce:

- Set your profile to private or log in with a private profile
- Upload a photo to a crag
- Log in with a different user and navigate to the same crag
- Look at the photos

Expected:
The previously uploaded photo is visible

Actual:
The photo is not visible

However, the photo is visible if you have the direct link to the photo

Example url(s) to reproduce the problem:

- Crag, photos list: https://www.thecrag.com/es/escalar/spain/valencia/area/1427314716/photos
- Direct photo link: https://www.thecrag.com/photo/5305880226
- Private profile: https://www.thecrag.com/climber/123john 

Ideally also provide screenshots:

Photo uploaded by a private user
![image](https://user-images.githubusercontent.com/30682796/135068384-e11b6322-2aa5-4449-9741-8109daf3b225.png)

Profile is set to private
![image](https://user-images.githubusercontent.com/30682796/135068499-308219ac-2fb3-4852-9ece-5b5d4d2f3fdb.png)

Photo not visible in list of photos by another user
![image](https://user-images.githubusercontent.com/30682796/135068608-4ed9146f-00ba-45d4-a9a6-db3d73b68955.png)

Photo however is visible by another user with direct URL
![image](https://user-images.githubusercontent.com/30682796/135068737-196378a2-ec11-489a-969d-9208fd7df99b.png)

**What you expected:**

* [ ] Photos uploaded to areas visible to all users - regardless of uploaded profile visibility

**Comment by rouletout** [comment]
Photos are considered as being part of "ticks" and thus stay private. This is not the case for topos or web-covers where they become contributions and are public.

**Comment by rouletout** [comment]
@killakalle were you able to see if a "private foto" shows as a web-cover for everyone as it should?

**Comment by killakalle** [comment]
Yes, photos configured as webcovers do show correctly.

**Comment by rouletout** [comment]
OK, so I sugges to close that - ok?

**Comment by killakalle** [comment]
@rouletout happy to close this issue.
But I believe there is a more general issue with when and how photos are shown. I created a new ticket to describe the issue properly:
https://github.com/theCrag/website/issues/4012
