### ISSUE TITLE
Member since date shown incorrectly for private profiles

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3971]
**What happened?**
For private profiles, it seems that "Member since" always shows _before 2004_ regardless of the actual join date.

If that is supposed to be not revealed as part of the user's privacy then it's better not to show this at all, rather than showing the wrong date.

Example url(s) to reproduce the problem:
https://www.thecrag.com/climber/123john

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/135069965-f2474a6a-7553-4ae3-9866-5ecbf863d58c.png)

**What you expected:**

* [ ] Show actual join date

**Comment by lordyavin** [comment]
I agree that with @killakalle that the current display is somehow irritating. I vote to hide this information completely.

**Comment by scd** [comment]
@fixed for next release
