### ISSUE TITLE
Preview photos not shown for some crags

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3972]
**What happened?**

Example url(s) to reproduce the problem:
https://www.thecrag.com/es/escalar/spain/valencia/area/5251066080
https://www.thecrag.com/es/escalar/spain/valencia/area/3359630451

Ideally also provide screenshots:
No preview photos shown
https://www.thecrag.com/es/escalar/spain/valencia/area/3841337841
![image](https://user-images.githubusercontent.com/30682796/135071862-758ccab9-d87e-4d21-a308-ba80b3d0e862.png)

But photos exist if you browse photos directly
https://www.thecrag.com/es/escalar/spain/valencia/area/3841337841/photos
![image](https://user-images.githubusercontent.com/30682796/135071968-991aa947-3280-4dfb-b5ff-550678dc4938.png)

How it should look like if there are photos
https://www.thecrag.com/es/escalar/spain/valencia/area/1428366324
![image](https://user-images.githubusercontent.com/30682796/135072192-f80b1a65-1849-4bc6-8dbc-a04cc0992ea3.png)

**What you expected:**

* [ ] Preview photos always shown on all crags

**Comment by rouletout** [comment]
Photos are being classified by "quality" to be shown in certain places (eg dashboard, area) - if the classification is not high enough, they do not show on the area page but only when you look at all fotos of an area. - closing
