### ISSUE TITLE
Topo locked in offline mode

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3977]
**What happened?**
In the app I downloaded an area where cellular coverage is non-existent.
When I was at the crag, I could not look at the topos

I'm a theCrag website supporter. Is this intentional, that I don't have access to offline topos?
And if it's intentional, why bother letting people download content that they cannot access?

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/137979312-48593070-9c41-43ea-aa10-b67780fd12c6.png)

**What you expected:**

* [ ] theCrag website supporters have access to offline topos
* [ ] otherwise clear communication on this matter

**Comment by rouletout** [comment]
@killakalle thansk for that - I know there is an ongoing issue with the Apple Store on that but if this occurs it should block you from downloading... Can you please log that in the App Issue tracking so that TopoGuru can answer on it. Thanks. I'm closing here....
