### ISSUE TITLE
Wrong grade histogram for deep water solo crags

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3978]
**What happened?**
Deep water solo crags seem to always display YDS grade histogram, despite different grade context of crag

Example url(s) to reproduce the problem:
Most famous DWS crag / route of the world:
https://www.thecrag.com/es/escalar/spain/mallorca/area/123206286

Another example:
https://www.thecrag.com/es/escalar/spain/mallorca/area/123206214

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/138336478-245899e6-1239-4d8d-ad40-01d96250fb29.png)

**What you expected:**

* [ ] Histogram follows configured grade context

**Comment by rouletout** [comment]
@killakalle thanks - we also have to fix some boulder issues, nice catch as this can be done together now (https://github.com/theCrag/website/issues/3969)

**Comment by scd** [comment]
This is also with top roping: https://www.thecrag.com/en/climbing/germany/hohenzollernbrucke

**Comment by scd** [comment]
Hot fixed this

**Comment by georg-d** [comment]
For people running into such issue, FYI: Same symtom as https://github.com/theCrag/website/issues/4051 but different cause: In 4051 all routes have unknown style (thus the correct grading schema cannot be determined), in 3978 + 3969 the style and thus grading scheme is known.
