### ISSUE TITLE
Asking for route description although it is already provided

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3979]
**What happened?**
For a number of routes the websites asks the user to provide a route description although it is already provided.

Example url(s) to reproduce the problem:
Most famous DWS route in the world:
https://www.thecrag.com/es/escalar/spain/mallorca/route/1844736528

Another example:
https://www.thecrag.com/es/escalar/spain/mallorca/tijuana/route/554674674

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/138337202-7d6ad420-e7db-4324-badd-5fe045dd092e.png)

**What you expected:**

* [ ] Yellow box not shown if description is already filled in.

**Comment by rouletout** [comment]
This is covered in https://github.com/theCrag/website/issues/3579 closing
