### ISSUE TITLE
Spanish translations - Tag: No apto para ninos

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3982]
![image](https://user-images.githubusercontent.com/30682796/139555208-6ede0510-0ffc-4440-b77d-5f322bfad4f4.png)

![image](https://user-images.githubusercontent.com/30682796/139555292-759fe9cd-eec2-44af-9388-200d0417c6c4.png)

**Comment by rouletout** [comment]
Thanks, fixed on next push, closing
