### ISSUE TITLE
Discrepancy with german translations

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#3984]
A non english speaking user contacted and asked me to point out some discrepancy in the german version, one word would be more consistent. I agree.

When ticking multiple routes at the same time the words "Begehungstyp" and "Begehungsstil" are used:
![a](https://user-images.githubusercontent.com/86301133/139674080-647c8401-958c-4a8f-a8ca-c0dd69dd0103.png)

The help page (https://www.thecrag.com/de/artikel/ticktypes) uses the word "Begehungsart":
![b](https://user-images.githubusercontent.com/86301133/139674095-7929a6ad-88e3-4934-b799-2d065a88aa1a.png)

**Comment by rouletout** [comment]
Thanks! Fixed on next push, closing.
