### ISSUE TITLE
broken help examples

### ISSUE THREAD

**Issue by urandom2** [theCrag/website#3992]
props for using production data in your docs, makes things a bunch more discoverable; unfortunately, it also means a few examples have broken over time:
- on https://www.thecrag.com/en/article/accounttypes#inactive the https://www.thecrag.com/climber/alexanderhuber profile is now community managed, but listed in the inactive section
![image](https://user-images.githubusercontent.com/2526260/144239847-161ad09a-78d3-4cc0-884e-2f635fbdd434.png)
- on https://www.thecrag.com/en/article/cprtimeline#floating-cpr https://www.thecrag.com/ascents/aggregate/graph-sport-cpr/has/sport-cpr/by/vwills/ chart is now blank
![image](https://user-images.githubusercontent.com/2526260/144239697-427766ff-712b-404d-b867-6d0d5cf3ae77.png)
- on https://www.thecrag.com/en/article/cpr#flexible-technology the arapiles graph https://www.thecrag.com/ascents/aggregate/graph-trad-cpr/has/trad-cpr/at/11740915 is blank
![image](https://user-images.githubusercontent.com/2526260/144239552-f5347007-9137-4bfe-b49d-a2ea0a06fc24.png)

**Comment by rouletout** [comment]
fixed, closing

**Comment by urandom2** [comment]
awesome: the first and third look great, but vanessa wills is still pretty bare: (is that on purpose?)
https://www.thecrag.com/en/article/cprtimeline#floating-cpr

**Comment by rouletout** [comment]
Looks good to me? ![image](https://user-images.githubusercontent.com/19162952/146108153-6e75e7e6-9d1b-424b-8e66-9d7e46d8bfb6.png)

**Comment by urandom2** [comment]
oh, interesting, I think it may be a perms issue, as it is still empty for me (and when I log out)

 ![IMG_20211215_020014.jpg](https://user-images.githubusercontent.com/2526260/146109243-be5c7d5a-b6f6-46ef-be57-559bec511985.jpg)
