### ISSUE TITLE
static content silent failures

### ISSUE THREAD

**Issue by urandom2** [theCrag/website#3993]
when browsing theCrag on a vpn, sometimes static resouces e.g. https://static.thecrag.com/flags/png/ch.png, will silently fail because the background request fetching them cannot pass the captcha check that your cdn (?) needs

**Comment by rouletout** [comment]
Can you explain more please? We use VPN a lot and do not experience this.

**Comment by urandom2** [comment]
by vpn, I mean tor, however any ip with a sufficiently low reputation can trigger the failure. the symptoms are that all www.thecrag.com resources load fine, but images never show up, and dev tools shows a bunch of 403 failures from static.tnecrag.com. if you manually load one of the static.thecrag.com links it will automatically resolve the cloudflare check, set a cookie, and allow all further requests to work, thus pictures load.

**Comment by arnottcr** [comment]
I am also seeing direct `403`s from the backed on occasion, not from cloudflare; something that cannot be resolved by solving the captcha.

**Comment by lordyavin** [comment]
Interesting use case. May I ask why you are using TOR to access thecrag? BTW IMHO TOR is not a VPN.

**Comment by urandom2** [comment]
I would rather my isp not know about my internet traffic, but my reasoning is orthogonal to the existence of the bug. I can confirm that the core issue is not with tor, just failing a cloudflare ip reputation check.

And yeah, tor is not a virtual private network, but most vpn providers are not either (they just mask ip addresses). Trying to explain tor as an overlay network seemed confusing, and that distinction can be lost on people.

**Comment by lordyavin** [comment]
@urandom2 is this issue still valid? 

Since this seems to be a rather rare problem and the use case is not common, I suggest to close the issue without investigating the problem further.

Additionally I don't know if this should be treated as a bug or an enhancement.

**Comment by scd** [comment]
I am closing for now as I doubt we will get time to investigate this further.

**Comment by urandom2** [comment]
yeah, I can still reproduce it trivially
