### ISSUE TITLE
Cannot delete new tick style ascent

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#3997]
Reproduce:

- Log a climb with a new tick style
- Try to delete it again
- It's not possible but should be.

I created a few random ascents to try out the new tick style. Afterward, I wanted to delete them again because they were no real ascents. Apparently, this is not implemented, yet.

![image](https://user-images.githubusercontent.com/30682796/144984167-450dc6ab-5996-4b2e-9168-a61ef108a8b7.png)

https://www.thecrag.com/ascent/5564800851

**Comment by scd** [comment]
Do it from your logbook. Menu item next to each ascent. Appreciate the
feedback that it is difficult to find

**Comment by killakalle** [comment]
Thanks, found it @scd 

![image](https://user-images.githubusercontent.com/30682796/145028397-a830a20d-fd86-41f3-a1dc-dea32c26215c.png)

I basically never use the logbook, that's why it hadn't occurred to me looking there.
I got confused because the "old" ascent type has a delete function in "Edit ascent" - and the new one doesn't

![image](https://user-images.githubusercontent.com/30682796/145030134-2cc784d2-6850-4a03-b5d8-98920028b7d1.png)

**Comment by lordyavin** [comment]
The context menu is definitively missing the entry to instantly delete an ascent shown in a stream event. IMHO this not polishing. This is an regression.

**Comment by rouletout** [comment]
Delete Ascent context menu is available wherever Edit Ascent is available from next release on, closing
