### ISSUE TITLE
Duplicate ascent data by clicking Save multiple times

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4000]
I've noticed that every now and then users create duplicate ascents and have even experienced this myself before.

It's easy to reproduce.

1. Log an ascent
2. Fill out the ascent data
3. Click "Save" multiple times
4. Notice how a lot of duplicate ascents are created.

Examples:
![image](https://user-images.githubusercontent.com/30682796/145528897-eb4acd02-838b-4abe-8afe-d50b63b073c5.png)

![image](https://user-images.githubusercontent.com/30682796/145528936-18a52e5c-c72f-4974-a329-64b8c1c09926.png)

![image](https://user-images.githubusercontent.com/30682796/145529459-c345b318-ab15-48e7-871e-289cf21ec071.png)

![image](https://user-images.githubusercontent.com/30682796/145529715-879718a6-aa12-4639-9c68-b16c5ebd2aaf.png)

I can imagine that this is related to #3976

Expected

- [ ] Users can submit ascent data only once regardless of how many times they click

**Comment by rouletout** [comment]
Thanks for reporting - will most likely not be fixed as it is not happening with the new ticking interface

**Comment by killakalle** [comment]
Any idea how long till the new interface will be available to everyone?

Here's another example where the same 4 routes were ticked eleven(!) times:
https://www.thecrag.com/event/6031651074
![image](https://user-images.githubusercontent.com/30682796/166290989-1742b4ca-a1cb-457d-b828-464cda0f5fba.png)

This is generating a lot of skewed data!
https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/route/3079212984/ascents
![image](https://user-images.githubusercontent.com/30682796/166291475-704e0174-3b71-4733-8fa8-773b5e2defa6.png)

**Comment by rouletout** [comment]
Closing now that the new ticking interface is available
