### ISSUE TITLE
archived routes show up on html guide

### ISSUE THREAD

**Issue by urandom2** [theCrag/website#4002]
when viewing an html gym guide (and presumably others), archived routes show up when in reality this is probably not desired?

e.g. https://www.thecrag.com/en/climbing/new-zealand/auckland/route/3299699637 in https://www.thecrag.com/en/climbing/new-zealand/auckland/area/1689419706/guide

**Comment by rouletout** [comment]
already covered in https://github.com/theCrag/website/issues/3553 - closing

**Comment by urandom2** [comment]
oh, no; terribly sorry about the dupe
