### ISSUE TITLE
Location not showing on map

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#4004]
https://www.thecrag.com/en/climbing/belgium/area/2683773003

For me, that shows no area. Just the map with no marking on it. When you edit the location it does show.

Please make it reappear :-)

**Comment by lordyavin** [comment]
Looks like a general issue:

https://www.thecrag.com/climbing/germany/schwaebische-alb/donautal/area/691710498

![grafik](https://user-images.githubusercontent.com/1528540/148929728-23916cea-418b-4e2c-ab81-437a1a3e1ff3.png)

Nothing is rendered here too.

**Comment by lordyavin** [comment]
Okay that is strange. I did something else, switched tabs and so on and got back to the tab with the are above and magically the area is rendered:

![grafik](https://user-images.githubusercontent.com/1528540/148930182-91938bae-ece4-4daa-a53d-44144d77687d.png)

**Comment by rouletout** [comment]
This information is hidden on purpose - let us know if this crag can be shown to the public again, closing

**Comment by matozoid** [comment]
The one I reported has reopened as you can see in the description.

**Comment by nicHoch** [comment]
I updated the area to be fully public again

**Comment by matozoid** [comment]
Thanks!
