### ISSUE TITLE
Australian PayID for donations not recognised

### ISSUE THREAD

**Issue by artlessconstruct** [theCrag/website#4006]
Tried to make a donation to theCrag's Australian bank account using PayID following the [donation instructions](https://www.thecrag.com/donate#title.australia) but the PayID payments@thecrag.com was not accepted by [Up bank](https://up.com.au/). I got an error pop up message "The PayID does not exist" when clicking on "Check PayID" in the Up bank Android mobile app.

Up bank did accept the Westpac bank account BSB & account number listed in the donation instructions as valid however so I just donated to this bank account using an Osko payment instead.

**Comment by scd** [comment]
Hi Jalon,

Thanks for the heads up. I honestly don't know what is going on with PayID
for our westpac account. I have looked and it only seems to be an ABN payID
they offer. We will investigate further but probably take the email payid
off the payment options.

I have set your account supporter status, please let me know if there are
any issues.

--
cheers
Simon

_____________________
<http://thecrag.com/>
Simon Dale
Chief Executive Officer @ theCrag
***@***.***
www.thecrag.com

Follow us on Facebook <https://www.facebook.com/thecragcom/?fref=ts>
Follow us on Instagram <https://www.instagram.com/thecrag_worldwide/>
Follow us on Linkedin
<https://www.linkedin.com/company/thecrag?trk=biz-companies-cym>

**Comment by artlessconstruct** [comment]
Not an expert on PayIDs but perhaps Westpac don't allow an email address as a PayID for a business as an extra precaution, or possibly to avoid the extra work required to verify the address. From a quick check other banks such as [ANZ](https://www.anz.com.au/ways-to-bank/more/pay-id/) do allow an email address as a PayID for a business. Thanks for the supporter status in any case :-)

**Comment by scd** [comment]
Yes I think you are right. I have set up an ABN payid yesterday. My
confusion is how we thought it was set up in the first place. Anyway there
is so much going on that I will not dwell on this for to long. Thanks for
your payment and help.

**Comment by rouletout** [comment]
Added new one, closing
