### ISSUE TITLE
Cannot delete topo images that were uploaded?

### ISSUE THREAD

**Issue by NickFoulds** [theCrag/website#4008]
Hi, I uploaded a couple duplicate images and one I just didn't want to use at "The Drain" location in Yeppoon/Capricorn Coast - Rosslyn bay. Found here: https://www.thecrag.com/en/climbing/australia/queensland/area/3862988514

After uploading them (as I have many times before) I can usually just delete what is excess and unwanted. This time round however the uploaded topos are refusing to go away after I instruct the to be deleted.

Any help please?

Many thanks
Nick

**Comment by lordyavin** [comment]
Which one should be removed?

**Comment by NickFoulds** [comment]
There are 2 duplicates of the main image and one that has no routes on it. So 3 in total.Thanks!On 11 Jan 2022 20:44, Kai ***@***.***> wrote:
Which one should be removed?

**Comment by NickFoulds** [comment]
So it is the 1sr 2nd and 3rd images when you go here: https://www.thecrag.com/en/climbing/australia/queensland/area/3862988514All are without routes on themNick.On 11 Jan 2022 21:57, Nick Foulds ***@***.***> wrote:There are 2 duplicates of the main image and one that has no routes on it. So 3 in total.Thanks!On 11 Jan 2022 20:44, Kai ***@***.***> wrote:
Which one should be removed?

**Comment by lordyavin** [comment]
Okay deleted (removed) two of them. The last is for your practice 😉: Click edit, then topo admin, then choose remove...

**Comment by scd** [comment]
I think there might be a permissions issue

**Comment by lordyavin** [comment]
@scd, the user that uploaded should always be able to delete his/her topos, isn't it?

**Comment by lordyavin** [comment]
@NickFoulds feel free to reopen this issue if you don't see the UI elements to remove the mentioned topos.

**Comment by NickFoulds** [comment]
Hi guys, sorry I didn't reply before, some reason I missed the emails!
I didn't have the option to do the usual delete topos that I have previously had. It did seem to me like a permissions issue somehow. 
Thanks for the prompting to learn @lordyavin ;) but I have not had issues with doing it in the past, don;t think I totally forgot how to do it! but who knows it is always possible! 

The areas looks correct now anyway. But perhaps ther is a lasting permissions issue with the node/region? Worth checking the back end of for someone who can?

Cheers again guys!
