### ISSUE TITLE
Broken link - area type

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4011]
Clicking on this link...
![image](https://user-images.githubusercontent.com/30682796/149421774-2d3bc445-33d8-4c22-97b8-5a261fe7cd2b.png)

...results in 404:
![image](https://user-images.githubusercontent.com/30682796/149421851-183cfab9-1cae-46dd-83de-48b7e27749e1.png)

Example:
https://www.thecrag.com/es/escalar/spain/gandia/area/2911286172

My guess for the correct link is this:
https://www.thecrag.com/es/articulo/documentingacrag#tipos-de-zonas

**Comment by scd** [comment]
Just a quick triage. The link is

https://www.thecrag.com/es/articulo/areatypes

We have a url system for translations, but it looks like something is missing for spanish.

**Comment by scd** [comment]
Fixed
