### ISSUE TITLE
Numbers of sequences not updated after item removal

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4013]
When an item (sector, route...) is removed, the former number keeps reserved for that route and the numbering jumps that value:

![2022-01-17 17_33_46-Window](https://user-images.githubusercontent.com/17315806/149809039-f420b0a0-ca50-4137-8752-d91b8509dfcc.png)
(here, the sector number 10 has been removed)

![2022-01-17 17_45_47-Window](https://user-images.githubusercontent.com/17315806/149809094-9b31446b-1aee-445d-b618-b6f53173350d.png)
(here, the route number 20 has been removed)

UPDATE:
When editing location, in the summary of sectors, the numbers are shown properly:
![2022-01-17 17_52_08-Window](https://user-images.githubusercontent.com/17315806/149809922-513871ae-d1eb-4b45-a9b5-af7218209085.png)

**Comment by rouletout** [comment]
Can you please provide links to these areas? Thanks

**Comment by Arzorth** [comment]
Sure!
https://www.thecrag.com/en/climbing/spain/madrid-area/area/1859698611

https://www.thecrag.com/en/climbing/spain/madrid-area/area/1859707446

**Comment by rouletout** [comment]
This just takes a few hours to update - all good now. Closing.
