### ISSUE TITLE
Add "ecopoint" as approch tag for ascents

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#4016]
From support:

I want to introduce the term Ecopoint in the climbing community (Climbing a route by public transport, by bike, or by feet, see also : https://lenamueller.com/the-ecopoint-concept/)

**Comment by rouletout** [comment]
Done, closed

**Comment by JosephineRoper** [comment]
I like the feature, thanks.

Could there be a way to search/filter ascents by this tag? (Or does it exist and I can't find it?) Would be helpful for finding crags that are most likely to be accessible by these means.
