### ISSUE TITLE
Make climbing style tags visible and clickable on ascent logging screen

### ISSUE THREAD

**Issue by stavzi222** [theCrag/website#4019]
Add on the bigger part of the screen (2/3) 

Please select the climbing style that describes this route best:

VERTICAL / SLAB / OVERHUNG / ROOF (show visible tags in the ascent details already without user needing to type or click on the field)

How did it feel?

Technical, Sustained, Bouldery

This can help to populate a more accurate database of different climbing styles available in crags / sektors / areas.

Such data can assist in creating better and richer insights for climbing styles for each climber (separate issue I opened is mentioning this).

**Comment by rouletout** [comment]
Duplicate of https://github.com/theCrag/website/issues/1713 - closing here
