### ISSUE TITLE
Connection to Facebook and Google not working

### ISSUE THREAD

**Issue by nucce** [theCrag/website#4026]
Im tried to connect my theCrag profile with Facebook and Google, but with both of them retrun with **500 Internal Server Error**:

### Facebook
![image](https://user-images.githubusercontent.com/1042743/153222291-b71e296c-9ce5-4cef-9022-b5d0d5bd98a7.png)

### Google
![image](https://user-images.githubusercontent.com/1042743/153222454-3df3f92f-d0d3-4100-9895-086dfc35bee5.png)

**Comment by rouletout** [comment]
fixed, closing
