### ISSUE TITLE
New tick style - ascent description does not fit gear style bouldering

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4028]
The tick description for onsight is written with (sport) __lead climbing__ in mind. It does not match completely with the gear style __bouldering__.

![image](https://user-images.githubusercontent.com/30682796/153934460-762774e9-6a78-42d1-b413-a0e5fef474cf.png)

Potentially, similar issues with other ascent/gear combinations. Haven't gone through all of them

**Comment by rouletout** [comment]
Fixed, closing
