### ISSUE TITLE
Topo editor - shape not drawn

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4029]
The shape of one of the areas is not drawn on a topo image despite polygon points added.
![image](https://user-images.githubusercontent.com/30682796/154024036-8aff7901-293e-4c5c-a075-97891f15f90e.png)

The shape that is missing is a "boulder" just like all the other areas.
![image](https://user-images.githubusercontent.com/30682796/154023755-c17ad217-b27b-4333-9083-e1022354f5db.png)

The topo in question
https://www.thecrag.com/es/escalar/spain/valencia/area/3302089788/topo#t5781218724

**Comment by rouletout** [comment]
There was a point on the top left outside the topo - removed it and now it is ok, closing
