### ISSUE TITLE
Private profile's "member since" & inactivty depend on context

### ISSUE THREAD

**Issue by skomaroff** [theCrag/website#4033]
I have noticed that the "member since" date for private profiles is shown differently in different contexts. Likewise, the inactivity flag is shown differently.

This is how the "member since" date appears when I view a private profile that does not follow me, regardless of whether I follow them:
![Screenshot 2022-03-01 at 15-55-21 Kalidae - Climber, theCrag](https://user-images.githubusercontent.com/84152181/156248180-dfd07620-88c2-42f7-9635-f23036b1a2d0.png)

Here is how it appears when viewing a stream event by that profile:
![Screenshot 2022-03-01 at 15-54-58 Stream event theCrag](https://user-images.githubusercontent.com/84152181/156248176-d4006aa1-29d0-4f65-8da6-a722c6e3b9ec.png)

Here is how it appears in the list of profiles I follow:
![Screenshot 2022-03-01 at 16-06-54 People you are following theCrag](https://user-images.githubusercontent.com/84152181/156249126-3bbb8998-fb63-417a-9381-5f1570a85b3a.png)

I can see why this would make sense - knowing how long a profile has existed or been inactive can be useful when viewing a stream event.   This makes it clearer if the user is quite new or if I should assume they won't respond to queries about their edits.

However, it might be good if this is displayed uniformly so that users have a clearer understanding of what data is private.

**Comment by skomaroff** [comment]
Related: https://github.com/theCrag/website/issues/3971

**Comment by scd** [comment]
This was concerning enough for me to jump in and fix. I have fixed in dev so it will be ready for next release.

**Comment by skomaroff** [comment]
:+1: 

It looks like one might also be able to see number of ascents in the list of followed profiles - not sure if you caught that already with you fix.

**Comment by skomaroff** [comment]
I think this can be closed now?  Everything looks fine to me.

**Comment by scd** [comment]
Caught that.
