### ISSUE TITLE
Lists: Missing translations / missing text in search

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4034]
- [ ] First two items not translated to Spanish
- [x] radio buttons - missing text
- [ ] Dropdown - not fully translated

https://www.thecrag.com/es/escalar/spain/area/1846162401/lists/permissions-model/privado/?sortby=when,desc

![image](https://user-images.githubusercontent.com/30682796/156374807-7859968d-c40f-497d-81ec-824c42b7763c.png)

**Comment by killakalle** [comment]
PS:
Selecting any of the three radio buttons has no impact on the search results. It always shows both pulic and private lists in the results

**Comment by scd** [comment]
@rouletout the radio buttons was a bug (double translation) which I have hot fixed. The rest is translation texts that need to be provided by translators.

@killakalle fixing the radio button also fixed the search

**Comment by rouletout** [comment]
Put into translation queue - closing
