### ISSUE TITLE
Lists: Sort by index leads to error 503

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4035]
Sorting lists by index leads to error 503

![image](https://user-images.githubusercontent.com/30682796/156375274-60181a83-637f-45f3-a994-962aac13b49e.png)

![image](https://user-images.githubusercontent.com/30682796/156375167-b16ef270-6790-4eaf-a3c3-45a65cc2a26c.png)

https://www.thecrag.com/es/escalar/spain/area/1846162401/lists/?sortby=at,asc

**Comment by scd** [comment]
I have not done anything to fix this but it seems to be working for me. @killakalle can you please confirm that it is either working for you or still broken.

**Comment by killakalle** [comment]
@scd 
Still broken for me.

https://www.thecrag.com/es/escalar/spain/area/1846162401/lists/?sortby=at,asc

The above link leads to 503 when I'm logged in. In an incognito tab (logged out) it loads fine for me.
![image](https://user-images.githubusercontent.com/30682796/157754029-c2da0d12-5126-42b8-a8d8-3486b64fc0b3.png)

**Comment by scd** [comment]
Ahh that looks like I tested two of the three permissions cases and the third one failed - superadmin and not logged in were tested. I have now hot fixed the normal login test. 

Note that permissions is super complex and therefor sql is generated differently depending on the underlying permissions of users.
