### ISSUE TITLE
Deleting ascents has triple confirmation

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4036]
Try to delete an ascent. The steps are

After you open the ascent details
1. Click "Delete ascent"
2. Confirm Delete
3. Click "Delete"

That seems like overkill. I suggest to remove the radio button.

![image](https://user-images.githubusercontent.com/30682796/156948513-3426eb1e-bb93-40da-8797-b6faec3cb260.png)

![image](https://user-images.githubusercontent.com/30682796/156948482-bbb22808-ce80-4305-bae4-43dccc8a61ae.png)

**Comment by rouletout** [comment]
While the 2.5x confirmation seems a bit of an overkill removing the radio button would also remove it from other menus where we want it (or create a lot of effort) for a relatively rare case of deleting ascents. Will not be changed in the near future - closing.
