### ISSUE TITLE
Search filter for boulders with French grades shows wrong results

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4040]
When searching for boulders and filtering by (French) grade, the applied filter seems to be that of (French) sport?

Filter:
https://www.thecrag.com/es/escalar/europe/routes/with-grade/FR:9a:9c/with-gear-style/boulder/?sortby=at,desc&page=8
![image](https://user-images.githubusercontent.com/30682796/159241559-c68ca8db-3274-4560-a973-566a67279b76.png)

https://www.thecrag.com/es/escalar/europe/routes/with-grade/FR:6a:6a/with-gear-style/boulder/?sortby=at,desc
![image](https://user-images.githubusercontent.com/30682796/159242439-08f8f8b7-d7e2-4080-a974-341a98f64a3e.png)

Expected:

- [ ] Filter grade and result grade are the same (or at least close)

**Comment by rouletout** [comment]
You need to filter for FB for this search, eg https://www.thecrag.com/es/escalar/europe/routes/with-grade/FB:9A:9C+/with-gear-style/boulder/?sortby=at,desc and it works correctly

Closing
