### ISSUE TITLE
Tag: "dries quickly"

### ISSUE THREAD

**Issue by skomaroff** [theCrag/website#4043]
Current tags relating to rain are

- Wet in rain
- Brittle when wet
- Dry in the rain
- Dries slowly

A "dries quickly" tag would be a very helpful complement to these.  When looking for a route to climb after rain, it's most helpful to know which routes typically either stay dry or dry quickly.

**Comment by rouletout** [comment]
That makes sense - we'll look into that

**Comment by rouletout** [comment]
Here some ideas, feedback welcome:

![dries-quickly-2](https://user-images.githubusercontent.com/19162952/170768841-80c6c7a4-6307-41f0-bb59-e46d2dd52abd.png)
![dries-quickly-3](https://user-images.githubusercontent.com/19162952/170768843-99d0fd6b-de41-48d6-b9c8-8f0e5f226beb.png)
![dries-quickly-1](https://user-images.githubusercontent.com/19162952/170768846-c69b196f-e1cf-4232-9067-9181753ac14b.png)

**Comment by skomaroff** [comment]
The hairdrier is most obvious to me, but having a searchable key is my main request.

**Comment by rouletout** [comment]
Done, closing
