### ISSUE TITLE
Colors in route type pop up

### ISSUE THREAD

**Issue by skomaroff** [theCrag/website#4045]
When a route's type is "Unknown", hovering over it gives a pop-up from which the route type can be set.  Most of the options are color coded the same way as elsewhere on the website.  The "top rope" option is not: it is grey instead of purple.

![Screenshot from 2022-04-09 16-09-36](https://user-images.githubusercontent.com/84152181/162590493-8e6bcc4a-7cfd-4752-9813-2ba9d501c699.png)

**Comment by scd** [comment]
This is fixed in dev
