### ISSUE TITLE
PDF Guid - Topo image quality inadequate

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4046]
The topo image quality on generated PDF guides is so poor it's hardly usable.

Compare the following three images with decreasing topo quality:

1. Best - Topo on theCrag website
2. Okay - Topo in TopoGuru app
3. Poor - Topo in generated PDF guide

![image](https://user-images.githubusercontent.com/30682796/162592336-3b6d4254-fd37-4f4b-bed6-30351b04e95c.png)

![image](https://user-images.githubusercontent.com/30682796/162592338-34b00426-83b3-4611-a640-585f91495888.png)

![image](https://user-images.githubusercontent.com/30682796/162592348-4b9ba54c-52db-4af7-9162-4b3c5f4c7c0a.png)

The topo is from:
https://www.thecrag.com/es/escalar/spain/valencia/area/1447606131

Please, provide a better quality for the generated PDF guides.

**Comment by nicHoch** [comment]
@scd should be fixed with https://bitbucket.org/thecrag/cids/commits/c46ff7669f7ab5e1a43e71805369abe728fecc8c
in next release.

**Comment by rouletout** [comment]
closing
