### ISSUE TITLE
ascents missing from pyramid

### ISSUE THREAD

**Issue by skomaroff** [theCrag/website#4047]
I have some ascents missing from my pyramid.  

https://www.thecrag.com/climber/gmkwk
![image](https://user-images.githubusercontent.com/84152181/162837835-fc08fec8-e18c-43cf-ab86-a204a2fe591a.png)

On the left you can see that I have one V5 ticked.  On the right,  the pyramid does not have a blue mark in V5

I may have tracked down the root cause.  Searching my ascents gives different results depending on whether I filter by grade.

Search with no grade filter: https://www.thecrag.com/en/climbing/united-states/lincoln-woods-state-park/area/12688855/ascents/between/2022+/by/gmkwk/?sortby=when-climbed,desc
![image](https://user-images.githubusercontent.com/84152181/162838903-0f9ab95a-40c2-4047-963f-95c4ed72668c.png)

Search with grades filtered to VB- to V17 (a superset of the intended ascent grades):
https://www.thecrag.com/en/climbing/united-states/lincoln-woods-state-park/area/12688855/ascents/with-ascent-grade/BLDV:VB-:V17/between/2022+/by/gmkwk/?sortby=when-climbed,desc
![image](https://user-images.githubusercontent.com/84152181/162838389-a34e9972-afc6-44aa-bca9-7af004a095be.png)

Ascents were logged with new tick flow.

**It appears that editing an ascent causes it to disappear from the a search that is filtered by grade.**  After taking the second screenshot above I edited the Noontime Moss ascent. It has now disappeared from that search:

![image](https://user-images.githubusercontent.com/84152181/162839631-3e2299b1-cd18-4df1-88d5-2bf9d6cc855d.png)

**Comment by rouletout** [comment]
Thanks, we'll put that on the list to investigate before the next beta release

**Comment by fritz-raphael** [comment]
I can confirm @skomaroff's case: One of my ascents logged with the new tick flow **doesn't appear on the route pyramid**: 

<img width="466" alt="image" src="https://user-images.githubusercontent.com/85614992/164165005-d5e28012-6ebb-46b5-a289-7fd3cf2cb290.png">

<img width="199" alt="image" src="https://user-images.githubusercontent.com/85614992/164166022-bd78662f-7d58-4bd9-8b49-b17dccbae42b.png">

I might have edited this ascent, but am not sure about it. 

It does appear both in the Notable Ascents section of my profile, in the CPR timeline, and in all ascents with no grade filter. **When I filter my ascents by grade, though, it doesn't appear:** 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/85614992/164165822-6f0fafee-413b-445b-90d7-1adb923bfd04.png">

And **when I edit a route ticked with the new tick flow, is disappears from the route list** (just tried it with another ascent). 

---
I am aware that this information might be redundant, I just thought it might support the search for the bug and thus a possible fix =)

**Comment by scd** [comment]
Sorry I missed this for the last release but the bug has now been hotfixed. 

However for ascents you have edited you will have to resave them for the fix to take effect.

**Comment by skomaroff** [comment]
I can confirm that this works after editing the missing ascents.   Now to remember which ones I've edited...

**Comment by skomaroff** [comment]
This bug was fixed, but has reemerged sometime in the last month or so.

Compare the following two searches:

First, filtering by grade 5.0 to 5.15d
https://www.thecrag.com/ascents/with-ascent-grade/YDS:5.0:5.15d/with-ascent-gear-style/trad/in-setting/natural/by/gmkwk/?sortby=when-climbed,desc
![image](https://user-images.githubusercontent.com/84152181/187314595-bbf8838d-2b0e-4a93-a71a-a1ffdd3024e7.png)

Second, with no filter on the grade.  More ascents show up.
https://www.thecrag.com/ascents/with-ascent-gear-style/trad/in-setting/natural/by/gmkwk/?sortby=when-climbed,desc
![image](https://user-images.githubusercontent.com/84152181/187314686-bd2944e8-cda3-4d67-8597-9b5cbe6e25db.png)

The affected ascents were logged with the new tick flow.
As before, editing an ascent causes it to disappear from the first search.

**Comment by scd** [comment]
I have just investigated and this was a temporary bug a few releases ago. If you re-edit the missing ascents using the new tick flow then they will appear back. I just did one to demostrate.

**Comment by skomaroff** [comment]
Thanks for looking into this!

I can see that you fixed [one tick](https://www.thecrag.com/ascent/6418241373), but editing the others myself doesn't seem to do anything.

Here's an example of a still-missing tick: https://www.thecrag.com/ascent/6414100434

**Comment by scd** [comment]
Weird, I wonder why it worked for one ascent.

**Comment by skomaroff** [comment]
I just went through all of the missing ascents and tried editing each one. Again.

The one that didn't show up yesterday does now.  As far as I can tell I didn't do anything differently.

Two are still missing:
- https://www.thecrag.com/ascent/6398983431
- https://www.thecrag.com/ascent/6414100434

I don't see what makes them different from the 8 that did work.

**Comment by scd** [comment]
@skomaroff both of those ascents only have an adjectival grade. This is a different issue all together and has nothing to do with editing in the new tick flow but rather a more fundamental issue of assigning a difficulty for UK adjectival grades. The problem is with both the old tick flow and the new tick flow for both logging and editing ascents.

I have made a change which takes into account adjectival grades if no technical grades are provided. Combining British adjectival and technical grades is a difficult area which we have not got on top of yet. There is considerable work to still do here so any fix I do now is likely to be temporary.

Please note I have updated your ascents and they are now in the list.

**Comment by skomaroff** [comment]
Thanks @scd!

that does sound like a tricky problem to sort out!
