### ISSUE TITLE
Overriding inheritance of access tag "closed"

### ISSUE THREAD

**Issue by TillF** [theCrag/website#4053]
I newly entered this cliff (https://www.thecrag.com/en/climbing/germany/harz-mountains/area/6009710295). It is Child to Blankenburger Teufelsmauer, which is tagged as "closed". However, currently some of its children became legal again, so I tagged the newly entered cliff accordingly as "allowed". Still, the cliff is displayed as closed.
I imagine it makes sense to override access tags of children when I a new restriction is imposed on the parent. However, when access is explicitly tagged as "allowed", I would suggest different behaviour.

**Comment by scd** [comment]
I don't think this is something we will do as it is very difficult to support throughout our features. 

What is wrong with just changing the closed tags for parent and siblings.

**Comment by rouletout** [comment]
Fully agree - if it is not manageable on higher level then it needs to be done on lower ones individually. It would become also hard to understand what is inherited, overridden or set at lower level otherwise. Closing.

**Comment by MelwinQ** [comment]
Decision accepted, just to explain my thoughts:
Of course changing siblings solves the issue, but requires a lot of clicking. I would have imagined that exactly this could be automatically accomplished: When a tag is set for one child (e.g. "allowed") which contradicts its parent's tag (e.g. "closed"), its siblings explicitly get the tag "closed" set, and the parent loses the tag "closed", as it does no longer apply for all its children.

Generally, I would expect direct tags always to override inherited ones (e.g. a"overhang" route of course is overhanging, even if located on a cliff tagged with "slab").

**Comment by rouletout** [comment]
This actually happens. If eg a cliff has tag vertical and you add a overhang to a route on this cliff only the overhang is displayed for this route.

**Comment by MelwinQ** [comment]
I don't think its works this way in the case TillF describes above: The node he mentions is explicitly tagged as "allowed", but itself and its children displayed as "closed" (red frame, label "closed" in the listings) because of its parent's tag. Just the icon "allowed" appears very unobtrusively.

**Comment by rouletout** [comment]
I referred to your comment on overhanging vs slab ;-) - CLOSED is a very sensitive issue and thus handled as it is
