### ISSUE TITLE
How to display and filter out via ferrata/ klettersteig types of routes on the World Map ?

### ISSUE THREAD

**Issue by clownfishnemoGitHub** [theCrag/website#4056]
How to display and filter out via ferrata/ klettersteig types of routes on the World Map ?

Hello is it possible to introduce a filter menu option for the World Map
where we can filter out routes to display as circular poi pins
by their types of route, like via ferrata/ klettersteig, or sportclimbing, or roches, etc

thanks

**Comment by rouletout** [comment]
It is currently not possible - this is part of issue https://github.com/theCrag/website/issues/69 - linking and closing here.
