### ISSUE TITLE
I can't merge nor delete routes

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4057]
Hi there!

I'm trying to merge these routes (2 by 2):

https://www.thecrag.com/en/climbing/spain/oviedo-area/teverga/route/724393728
https://www.thecrag.com/en/climbing/spain/oviedo-area/teverga/route/725596056

https://www.thecrag.com/en/climbing/spain/oviedo-area/teverga/route/1845325143
https://www.thecrag.com/en/climbing/spain/oviedo-area/teverga/route/3022799406

https://www.thecrag.com/en/climbing/spain/oviedo-area/teverga/route/725597754
https://www.thecrag.com/en/climbing/spain/oviedo-area/teverga/route/1845325422

but the merge option appears grayed out for all of them

I'm also trying to delete this annotation by leaving its name in blank:
https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?select=0;R=%2Fen%2Fclimbing%2Fspain%2Foviedo-area%2Flas-bovedas;D%3AFieldSelection=0;D%3AFieldGroup=area_all;D%3AFieldGroup=route_all;D%3AFieldGroup=annotation_all;D%3AN=3022836363;C%3AHideNavigation=1;C%3AState=18538;C%3APushReturnURL=%2Fen%2Fclimbing%2Fspain%2Foviedo-area%2Flas-bovedas&P%3A0%3AInformationNetworkID=7539484

(In case you can't open it, it is the TBR annotation at the end of this sector: https://www.thecrag.com/en/climbing/spain/oviedo-area/las-bovedas)

but I get this error:

{ "canError" : "must be a coordinator for sensitive updates in this crag" }

I am editor of the whole region (https://www.thecrag.com/en/climbing/spain/oviedo-area) so I don't understand why I can't edit that.

Thanks for the support!

**Comment by scd** [comment]
The canError is because some features require a higher level of permissions. I think we should change this for deleting annotations.

Merging requires a higher level of permissions. One of us will get onto this shortly.

**Comment by Arzorth** [comment]
It could be useful to have a merge request option, so that plain editors can suggest admins to merge routes.

**Comment by nicHoch** [comment]
i merged the routes and deleted the annotation. we will also fix the bug in the permission model.

**Comment by scd** [comment]
Fixed permissions model so that a normal editor can delete an annotation.
