### ISSUE TITLE
Duplicated sectors

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4059]
I’ve found 2 duplicated sectors with duplicated routes but I can’t merge them:

 https://www.thecrag.com/en/climbing/spain/oviedo-area/teverga/area/2665815216

https://www.thecrag.com/en/climbing/spain/oviedo-area/teverga/area/1845255570

Regards!

**Comment by nicHoch** [comment]
cleaned thx for the report.
Nicky
