### ISSUE TITLE
Error in moving routes from an area to a sub-area

### ISSUE THREAD

**Issue by LucioVirzi** [theCrag/website#4063]
Hi everyone, I was trying to move some routes from an area to a sub area, and after that merging, but I'm having an issue:

Software error:
 at /opt/CIDS/perllib/BSIS/Db.pm line 2394.
	BSIS::Db::handleError("DBD::mysql::st execute failed: Lock wait timeout exceeded; tr"..., DBI::st=HASH(0x7f663c261060), undef) called at /opt/CIDS/perllib/BSIS/Db.pm line 1053
	BSIS::Db::createBSISRecord("InformationSupply/reparentqueue", 6089284521, HASH(0x7f667d3f80a0), HASH(0x7f667d4170f8), HASH(0x7f663c0919a8), "ReparentQueueOrder", "MySQL", HASH(0x7f6698154488), ...) called at /opt/CIDS/perllib/CIDS/Table/InformationSupply/ReparentQueue.pm line 414
	CIDS::Table::InformationSupply::ReparentQueue::createReparentQueueRecord(6089284521, HASH(0x7f663c0919a8), "SystemContext", HASH(0x7f669843e608)) called at /opt/CIDS/perllib/CIDS/Table/InformationSupply/ReparentQueue.pm line 482
	CIDS::Table::InformationSupply::ReparentQueue::actionCreateReparentQueue(HASH(0x7f663c0919a8), "SystemContext", HASH(0x7f669843e608)) called at /opt/CIDS/perllib/BSIS/Transact.pm line 157
	BSIS::Transact::processLiveTransaction("actionCreateReparentQueue", CODE(0x7f667d3f7e30), HASH(0x7f663c0919a8), "SystemContext", HASH(0x7f669843e608)) called at /opt/CIDS/perllib/CIDS/Process/Standard/Tools.pm line 114
	CIDS::Process::Standard::Tools::createDynamicRecord(HASH(0x7f669849f378), "ReparentQueueID", "actionCreateReparentQueue", CODE(0x7f667d3f7e30), HASH(0x7f667d3f80a0), HASH(0x7f667d4030f0), HASH(0x7f667d4170f8), HASH(0x7f663c0919a8), ...) called at /opt/CIDS/perllib/CIDS/Application/ReparentNode.pm line 188
	CIDS::Application::ReparentNode::reparentNodes(HASH(0x7f669849f378), 7503118, 2521544427, 3926145813, undef, ARRAY(0x7f66401f9140)) called at /opt/CIDS/perllib/CIDS/Application/API/Area.pm line 1431
	CIDS::Application::API::Area::updateArea(HASH(0x7f6698487a78), "auth", HASH(0x7f66984d88c0)) called at /opt/CIDS/perllib/CIDS/Process/SupplyInformation/ReparentNode.pm line 968
	CIDS::Process::SupplyInformation::ReparentNode::processStateReparentNodeSaveReparent(HASH(0x7f6640286820), HASH(0x7f6640293360), "SystemContext", HASH(0x7f6640131fa8), "ProcessContext", ARRAY(0x7f664012f650), "SessionContext", HASH(0x7f663c424f80), ...) called at /opt/CIDS/perllib/BSIS/Process.pm line 108
	BSIS::Process::processState(HASH(0x7f6640286820), HASH(0x7f6640293360), "SystemContext", HASH(0x7f6640131fa8), "ProcessContext", ARRAY(0x7f664012f650), "SessionContext", HASH(0x7f663c424f80), ...) called at /opt/CIDS/perllib/BSIS/Process.pm line 376
	BSIS::Process::processBSISStateMachine(HASH(0x7f6640286820), HASH(0x7f6640293360), "SessionContext", HASH(0x7f663c424f80), "ProcessContext", ARRAY(0x7f664012f650), "SystemContext", HASH(0x7f6640131fa8), ...) called at /opt/op/CIDS/cgi-bin/cids.cgi line 221
	ModPerl::ROOT::ModPerl::Registry::opt_op_CIDS_cgi_2dbin_cids_2ecgi::handler(Apache2::RequestRec=SCALAR(0x7f667ad86630)) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/ModPerl/RegistryCooker.pm line 207
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.24/ModPerl/RegistryCooker.pm line 207
	ModPerl::RegistryCooker::run(ModPerl::Registry=HASH(0x7f6668881650)) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/ModPerl/RegistryCooker.pm line 173
	ModPerl::RegistryCooker::default_handler(ModPerl::Registry=HASH(0x7f6668881650)) called at /usr/lib/x86_64-linux-gnu/perl5/5.24/ModPerl/Registry.pm line 32
	ModPerl::Registry::handler("ModPerl::Registry", Apache2::RequestRec=SCALAR(0x7f667ad86630)) called at -e line 0
	eval {...} called at -e line 0
For help, please send mail to the webmaster ([scd@thecrag.com](mailto:scd@thecrag.com)), giving this error message and the time and date of the error.

The main area from where I'm moving is: https://www.thecrag.com/it/arrampicar/italy/central-and-southern-italy/rome-area/area/2521544121

The child destination area is: https://www.thecrag.com/it/arrampicar/italy/central-and-southern-italy/rome-area/area/2521544427

I was able to move just one route, and then tried to move all the remainings.

Another issue is that the one that I was able to move I cannot merge with another one in the same area, the merge command is grayed out as you can see in the attachment

<img width="868" alt="Schermata 2022-05-20 alle 15 55 26" src="https://user-images.githubusercontent.com/61590146/169543273-da597507-8348-4ecc-8a5d-a7500aa22943.png">

LV

**Comment by rouletout** [comment]
Done closing
