### ISSUE TITLE
Quality Icons in stream show graphic and text

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#4065]
![grafik](https://user-images.githubusercontent.com/1528540/169706997-9f8997aa-d993-43e1-bd90-af49bac8a67f.png)

See https://www.thecrag.com/event/6096914721

The image texts shall not be visible or the text should be aligned left or right of the image.

**Comment by lordyavin** [comment]
Logged with new ticking interface

**Comment by scd** [comment]
The closing span around the icon is for some reason including text. But it is not doing this in my dev.

**Comment by lordyavin** [comment]
Did a quick cross check with other browsers. Same result with chromium based browsers (chrome, edge)

**Comment by scd** [comment]
I have to work out whether it is fixed in dev or there is something about
your stream event that is different. I ran out of time last night to do
anything but a quick triage.

If it is fixed in Dev then it is a coincidence because we have not worked
on fixing it.

**Comment by lordyavin** [comment]
Awaiting your results. Thanks in advance.

**Comment by scd** [comment]
This is now fixed
