### ISSUE TITLE
Missing some unicode characters in generated PDFs

### ISSUE THREAD

**Issue by pbradaric** [theCrag/website#4066]
**What happened?**

Personalized PDFs are not showing unicode characters (i.e. č, ć, š, ž).

![Screenshot_966](https://user-images.githubusercontent.com/355627/169713919-ba2d9e19-eec8-4cfa-a56e-150685f80a7f.png)
![Screenshot_967](https://user-images.githubusercontent.com/355627/169713923-9cdb4e93-3bb5-49d2-959d-83407af81589.png)

**What you expected:**

Letters č, ć, š, ž and special characters from other languages should be displayed.

**Example:**

https://www.thecrag.com/en/climbing/serbia/area/3809179194

Click on "Downloads" button, then click on "Custom PDF".

**Comment by pbradaric** [comment]
I've examined generated PDF and here are some findings.
It looks like generated PDF is using _NotoSansCJKTC Regular_ (and bold) font - this one https://github.com/indigofeather/fonts/blob/master/NotoSansCJKtc-Regular.ttf.

However, this font seems to be missing various European characters. The following languages have the following characters missing:
- Greek: ς
- Macedonian: Ѓ ѓ, Љ љ, Њ њ, Ќ ќ, Џ џ
- Polish: Ć ć, Ś ś, Ź ź, Ł ł, Ż ż, Ą ą, Ę ę
- Serbian: Š š, Č č, Ć ć, Ž ž
- Ukrainian: Ґ ґ, Є є, І і, Ї ї

Besides these languages, I've also tested German, Spanish, Bulgarian and Russian alphabets - they all seem to be working fine.

Regular _Noto Sans_ font (https://fonts.google.com/noto/specimen/Noto+Sans) has all of the European characters.
It seems that including this font family in a comma separated list is the way to go (solution reference: https://stackoverflow.com/questions/35101439/displaying-unicode-characters-in-pdf-produced-by-apache-fop).

Thoughts?

**Comment by rouletout** [comment]
Same issue as https://github.com/theCrag/website/issues/3362 - closing here and linking back to 3362 as it is well described here.
