### ISSUE TITLE
Missing Spanish translation - New log ascent view

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4069]
![image](https://user-images.githubusercontent.com/30682796/169716456-a081d11e-3177-4de9-907b-d2629e8d99e2.png)

![image](https://user-images.githubusercontent.com/30682796/169716660-a451b6d2-51ce-4717-a67c-093640dff011.png)

See highlights in screenshots

**Comment by rouletout** [comment]
Thanks, in the queue and / or fixed.
