### ISSUE TITLE
New log ascent - texts overlap in Spanish

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4070]
In Spanish some of the texts are too long and overlap with neighbors (see screenshots)

![image](https://user-images.githubusercontent.com/30682796/169716540-933ec950-2f8c-48d7-b8cb-48a7c20aa554.png)

Also a problem on mobile (with boulder)
![image](https://user-images.githubusercontent.com/30682796/169716565-abdc5a17-a640-45f6-a6ca-ceec997c8a64.png)

**Comment by rouletout** [comment]
Thanks for that - we will look at that again once we cleaned up the tick types

**Comment by rouletout** [comment]
This is still true for "Hang Dog" and "Ascension registrada" - we should find something new instead of  "Colgandose"

**Comment by rouletout** [comment]
I think this is fixed - @killakalle if you see more instances of that please let me know
