### ISSUE TITLE
Typed text "2. SL" rendered as "① SL" so wrong start for numbered list 

### ISSUE THREAD

**Issue by georg-d** [theCrag/website#4073]
In German, "2." equals to English "2nd", so "2nd rope length" is often written as "2. SL" (spoken "Zweite Seillänge"). If you start a route description with e.g. `2. SL` (or any other number before the dot) it will be rendered as `① SL`
![grafik](https://user-images.githubusercontent.com/45993293/170888508-8007611d-2567-4e89-8e5c-0a551b1a13dd.png)
This shift of the numbers in the numbered list is not only annoying but potentionally dagerous, e.g. if warnings, routefinding instructions etc. appear to be written for a completely different rope length than intended. 

Workaround: Whenever I recognize such a paragraph start, I re-word it to e.g. `Die 2. SL` 

Desired solution: Numbered list item uses the defined number, not always 1.

**Comment by scd** [comment]
This may be super hard because the functionality comes from a third party
module.

Please throw in all your work around ideas.

**Comment by lordyavin** [comment]
Just write "Zweite" and the issue is solved. I would not change anything here. Too much work. It's probably not worth the efforts.

**Comment by georg-d** [comment]
As we can easily work around using many different wordings and it seems quite difficult to fix it in the used library, IMHO we can close it. If anyone sees it different, just re-open 🙂
