### ISSUE TITLE
Duplicated pitch

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4074]
This route:
https://www.thecrag.com/en/climbing/spain/el-chorro/frontales-medias-cueva-poema-de-roca/route/14172415

should be integrated into this multipitch:
https://www.thecrag.com/en/climbing/spain/el-chorro/frontales-medias-cueva-poema-de-roca/route/14172469

Regards

**Comment by nicHoch** [comment]
@Arzorth thx for reporting this. normally we would agree to merge that. but to merge a single pitch with so many existing ascents into another multi pitch route could really effect the logbook of all that users - as our current implementation is not 100% correct.
