### ISSUE TITLE
Region tagged as Crag

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4077]
This should be a region:
https://www.thecrag.com/en/climbing/spain/area/825082161

Regards!

**Comment by killakalle** [comment]
@Arzorth 
I've changed it to region.

Do you think it would make sense to rename either this node or its parent? They are both called "Jaén" and both are regions. Seems a bit confusing.

![image](https://user-images.githubusercontent.com/30682796/171880655-296a5198-2443-4f57-8709-b9f74c0623d9.png)

**Comment by Arzorth** [comment]
The upper most is the province of Jaén and the other one is the main municipality of the province, which is also called Jaén.

I can change the smaller to “Jaén municipio” to make it clearer.

**Comment by nicHoch** [comment]
@Arzorth and @killakalle thx for taking care
