### ISSUE TITLE
Route order not preserved in bulk edit

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4081]
The screenshot shows...

left: wrong order of routes during bulk edit
right: correct order of routes in route list

![image](https://user-images.githubusercontent.com/30682796/172256633-69903929-ca11-41f8-8f29-f6360d219522.png)

Sector link:
https://www.thecrag.com/es/escalar/spain/jerica/area/164284014

I would consider this issue critical, as you easily edit the wrong route if 
- you are not aware that there is a problem in bulk edit
- you don't pay attention to the route name, but are just editing the "second" and "third" route of the sector.

This issue was first mentioned in https://github.com/theCrag/website/issues/3915 though is unrelated according to Simon.

**Comment by scd** [comment]
I am looking into this, but it seems right. So I did some further investigation by auditing the code and there is an edge case for about 10 minutes after a re-order where the data fields have not been fully synced. For that period of time the order can be strange. It is impossible to say if this was the problem, but highly likely.

I have hot fixed this so please keep an eye out for it happening again.
