### ISSUE TITLE
New log ascent - counting of ascents incorrect/misleading

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4085]
In the [Release forum](https://www.thecrag.com/discussion/6084829995/release-98---new-tick-flow-part-4#m6173714613) Simon wrote:

_"If you have one attempt and it is successful then you should log 1. If you have 2 attempts and the second is successful then 2, etc."_

**To reproduce**

1. Log a climb with the new log interface
2. Select redpoint - which is a successful ascent
3. For "Number of attempts" select 2
4. Save

**Expected**
The confirmation modal reads: "You have 2 ascents. 1 successful and 1 failed."

**Actual**
The confirmation modal reads: "You have 3 ascents. 1 successful and 2 failed."

Apparently, the ticked ascent, e.g. redpoint counts as 1. And the number of attempts counts as additionally failed ascents. Probably it should rather be 

- Total ascents = number of attempts (or 1 if left empty)
- Failed ascents = number of attempts - 1

![image](https://user-images.githubusercontent.com/30682796/173787470-dfd22b78-2348-45f7-96fc-28bef1a5d653.png)

![image](https://user-images.githubusercontent.com/30682796/173787602-2697219f-ff45-483e-8490-26897a6618e1.png)

![image](https://user-images.githubusercontent.com/30682796/173788019-5efc3cc1-dfe1-4e42-85e9-02bd8ab3c836.png)

Link to ascent:
https://www.thecrag.com/ascent/6191197554

**Comment by scd** [comment]
I have hot fixed this.

**Comment by killakalle** [comment]
@scd 

I still think there is a need to clarify terminology or to update the confirmation message.

![image](https://user-images.githubusercontent.com/30682796/178733903-26480440-97b2-4628-9b22-44f34120e62d.png)

- Individual routes climbed: 2
- Attempts total: 3
- Attempts successful: 1
- Attempts failed: 2

**Comment by rouletout** [comment]
Re-opened, looks like number of attempts is not taken into account if all failed?

**Comment by scd** [comment]
@killakalle thanks for re-analysing. I have fixed this in my dev. After next release please test again.
