### ISSUE TITLE
Spanish translations - Route feedback - No te molestes / Don't bother

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4086]
The correct Spanish translation of "Don't bother" is "No te molestes"

however, on the platform it's everywhere as "Ni te molestes"

![image](https://user-images.githubusercontent.com/30682796/174307103-8e8d0d36-24ca-434a-95b4-9fa2bc8152e2.png)

**Comment by rouletout** [comment]
Ni te molestes means: " Don't even bother." and no te molestes "Don't bother." Closing.
