### ISSUE TITLE
Ascent doesn't appear in list of ascents

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4088]
This ascent (pink point):
https://www.thecrag.com/ascent/6207190461

Does not appear in the list of my ascents of the sector
https://www.thecrag.com/en/climbing/netherlands/amsterdam-city/area/6180792414/ascents/by/jositogg

This other ascent appears instead (hang dog):
https://www.thecrag.com/ascent/6207177912

![image](https://user-images.githubusercontent.com/17315806/175667605-a9eae85e-f4a4-4d13-8359-60dd68decefd.png)

Regards!

**Comment by tbm-git** [comment]
Hi, same here with an other route: https://www.thecrag.com/de/klettern/germany/ruhrtal/avalonia/route/5868871404
![route](https://user-images.githubusercontent.com/108337454/176161879-6d84ecb8-15f8-4f2b-ba6a-f73d814b4aea.png)

When retrieving for https://www.thecrag.com/ascents/by/thomasmertens/with-ascent-gear-style/boulder/in-setting/natural/has/distinctroute/with-ascent-grade/fb:6A+:6A+?sortby=tick-type,desc , the route is not displayed: 
![list](https://user-images.githubusercontent.com/108337454/176162490-d956ec2c-6651-44f4-a100-84438b97abe0.png)

**Comment by rouletout** [comment]
The ascent is actually on the list, just 3 lines above. You might be confused as it is shown in orange (you logged it with the old interface which created an ascent grade and 6c is orange). Closing.

**Comment by Arzorth** [comment]
You are right, sorry
