### ISSUE TITLE
Annotations don't conserve relative position when moving childrens between nodes.

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4089]
I've moved some routes and annotations from one node to another and the annotations went to the end of the list:

![image](https://user-images.githubusercontent.com/17315806/176623456-2741e512-cda1-4c93-bd58-e5423d48e728.png)

https://www.thecrag.com/en/climbing/netherlands/the-hague/area/6255713220

(I've reordered them manually)

Regards,

José María

**Comment by rouletout** [comment]
This is a known bug, listed here: https://github.com/theCrag/website/issues/1351 - I'm closing here and link to it.
