### ISSUE TITLE
Empty ascent date leads to ugly error message

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4095]
Reproduce

1. Log a route with the new ascent log
2. Clear date field
3. Save

Expected

- form validation points user to missing input OR
- just save ascent with date of TODAY

Actual

- too much information for regular user

![image](https://user-images.githubusercontent.com/30682796/178735466-bfb927a4-99aa-4c26-90ab-02dffef8ef55.png)

**Comment by scd** [comment]
Fixed in my dev.
