### ISSUE TITLE
Receiving warnings and discussion notifications I have not signed up for

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4097]
I'm receiving warnings and discussions that I have not signed up for. Or at least it's not clear to me why I receive them. And I have not found any way to turn them off.

Example:
![image](https://user-images.githubusercontent.com/30682796/179204026-9f8c60f5-af7c-4fed-9010-3ef42c51c1cc.png)

- the first is a warning in a crag somewhere in Spain
- the second is a discussion somewhere in Spain.

My country is set to Spain, but I don't want to receive notifications and warnings for all of Spain
![image](https://user-images.githubusercontent.com/30682796/179204457-64cec260-4e1e-48e4-ac87-8f2b7c5bd0a4.png)

![image](https://user-images.githubusercontent.com/30682796/179204564-283c55cf-d999-44bb-93b4-ae583538e39f.png)

Issues
- [ ] receiving discussion notification within Spain although Spain is excluded 
- [ ] receiving warning notification within Spain and I cannot deactivate it (is a warning more or less the same as a discussion?)

Related to this ticket of the category "Stuff, I don't want to see any more"
https://github.com/theCrag/website/issues/4087

**Comment by rouletout** [comment]
Did you check what the stream event says if you click on the arrow (see screenshot). It should say why you see it.
<img width="508" alt="Screenshot 2022-07-17 at 09 35 41" src="https://user-images.githubusercontent.com/19162952/179403399-af967f2d-6115-483c-a62d-ace243bedefe.png">

**Comment by killakalle** [comment]
@rouletout 

The warnings don't even have that option

![image](https://user-images.githubusercontent.com/30682796/179429375-0813177f-4cef-4ee0-a6c8-c457bee37f9a.png)

**Comment by scd** [comment]
Are you subscribed to any ancestor node from the warning node?

**Comment by rouletout** [comment]
@killakalle you need to look in the stream, not the messages - there you have the option to see WHY you see it...

**Comment by killakalle** [comment]
I've discovered that I was actually subscribed to the Spain forum. I have unsubscribed now and expect this to resolve the issue.

**Comment by killakalle** [comment]
Not that I know of.
Is there any way to find out for sure?
