### ISSUE TITLE
Mentions not updated

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4099]
Hi! I mentioned one Arwin by mistake and then I changed to the proper one but the mention still points to the wrong Arwin:

![image](https://user-images.githubusercontent.com/17315806/179728635-537ca73d-83c4-4177-acb3-5e4691843f23.png)

Regards,

José María

**Comment by rouletout** [comment]
This is a bug recorded here: https://github.com/theCrag/website/issues/2442 - I close here and add a reference
