### ISSUE TITLE
Suggested grade in new ascent logger not erased once ascent deleted.

### ISSUE THREAD

**Issue by vardy** [theCrag/website#4102]
I noticed when testing out the new ascent logger that after deleting the 'dummy' ascents I made, the suggested grade I inputted for a route remained after the new log was deleted.

In this photo, you see a log I made using the old system with no suggested grade. It visually updated after I made the dummy logs and did not revert. (I've since fixed the issue for myself by logging the route again with a suggested grade of 18)

![Screenshot_2022-07-26-19-26-04-66_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/31592255/180974457-4cd3b34b-420c-48dd-9b02-d3085c1f9387.jpg)

**Comment by vardy** [comment]
This may or may not be worth your guys' time to address, it just felt like a fair UX hiccup. Probably won't affect many.

**Comment by scd** [comment]
I think this needs more information to properly respond.

Adding a grade opinion is associated with a grade on a route. We only accept one opinion for one route/grade per account. In other words you cannot say a route is both hard and easy for the grade.  

We use ascent logging for adding that opinion. It applies to all your ascents of that route. So if you have two ascents and delete one, it will still apply to the other ascent.

If you want it removed then you need to remove it via an ascent. There could be some edge cases we have not defined business logic. It may also be fine once the feature is understood.

**Comment by rouletout** [comment]
We looked at that again and we think the suggested grade should stay, even if you delete your ascent. in the rare case where you entered something wrong, you can still create a new ascent, correct the suggestion and then delete it. Closing.
