### ISSUE TITLE
Inconsistent assigning of CPR points?

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4105]
Today I was climbing the same route and logging the same tick (red point) as my climbing partner. However, she got different CPR points than me. What is the reason for this?

![image](https://user-images.githubusercontent.com/30682796/182049001-49cbcc1d-e0f4-4772-8cbb-680e45a7876e.png)

Partner profile: https://www.thecrag.com/ascents/has/sport-cpr/by/saraconnorr?sortby=rating,desc
My profile: https://www.thecrag.com/ascents/by/killakalle/has/sport-cpr/between/2022+2022?sortby=rating,desc

I've noticed that some of my redpoint ascents don't get the +220 points adjustment, e.g. ascent of Thor, while others do, e.g. ascent of Tirant lo Blat.

**Comment by scd** [comment]
One is a flash and one is a red point:

https://www.thecrag.com/ascent/6377034639
https://www.thecrag.com/ascent/6377576811

**Comment by killakalle** [comment]
True.

Though then there was a glitch with the ascent icons. Might be related to this:
https://github.com/theCrag/website/issues/3744

The question is why a redpoint icon was shown instead of a flash icon.
