### ISSUE TITLE
Feature Request - Private ascents

### ISSUE THREAD

**Issue by Dane-2pi** [theCrag/website#4106]
I could have sworn I'd seen this on here before, but a search revealed nothing.

While I like having the majority of my account public, I'm one of those that logs everything, if only to jog my memory of what I did a decade ago. 

However there are certain ascents that I'd rather not be visible( eg. solo's, the days you throw a sickie, ones with access issues, ones where you bailed on someone because you got a better offer) ... 
Being able to suppress them from a public stream would be great. 

In my case, I'd love to have them just be suppressed from the stream, and appear again magically without fanfare a few months later. 
Although any with access issues would be best suppressed entirely

**Comment by Dane-2pi** [comment]
Nevermind, I see it is in the "new tick interface" - I'd never managed to figure out how to access that before I went digging through the back catalog of release messages

**Comment by scd** [comment]
Actually this is not in the new ticking interface. The new ticking interface has the ability to store a private comment in a public ascent.

**Comment by lordyavin** [comment]
@scd so why didn't you reopen the issue. I would love to have this feature.
