### ISSUE TITLE
New tick flow: editting boulder ascents added pitches

### ISSUE THREAD

**Issue by skomaroff** [theCrag/website#4109]
I have three ascents of boulders that somehow acquired pitch information.

I can't say for sure, but believe that this happened when I edited their ascent dates over a slow/spotty connection, and that the incorrect pitch information is copied from the ascent I edited immediately before.  

![image](https://user-images.githubusercontent.com/84152181/183943176-4b2993a0-d9d9-475b-a441-5877fadf2bd4.png)

These are the ascents in question:
https://www.thecrag.com/ascent/6400672347
https://www.thecrag.com/ascent/6399785103
https://www.thecrag.com/ascent/6399783804

I'll leave them as is for now, so you can try to track down what happened.

**Comment by scd** [comment]
Thanks for that. There was a bug, which is now fixed.
