### ISSUE TITLE
editing multipitch ascents

### ISSUE THREAD

**Issue by skomaroff** [theCrag/website#4110]
When adding mulipitch ascents with the new tick flow, there is an option to tick only the first or last _n_ pitches.

However, when editing an ascent logged this way, the dialog defaults to all pitches being ticked.   I would expect that which pitches are ticked would by default be the same as in the initial ascent.

**Comment by scd** [comment]
Can I just paraphrase what you are asking to make sure I understand.

You want the default pitch tick type to match the main tick when you open pitch ticking.

Is this correct?

**Comment by skomaroff** [comment]
The initial defaults are fine, the issue is with editing an existing ascent.  

When I log an ascent of a subset of multipitch route, I check the box "Log pitch fields (pitch N to M)" and then use the slider to select remove pitches from the beginning or the end.  This is fine.

The issue arises if I later edit that ascent: all pitches are selected again unless I use the slider to remove them again.

To reproduce

- log an ascent of pitches 1 and 2 of a 3 pitch route
- edit the ascent and add a comment
-  press "Log ascent"  to save

Now the ascent has all 3 pitches although I made no changes there.  One has to deselect pitch 3 before saving.

**Comment by skomaroff** [comment]
Hopefully this is clearer now!

**Comment by scd** [comment]
Fixed for next release.

**Comment by skomaroff** [comment]
Looks good to me!
