### ISSUE TITLE
Green points have trad CPR but are in sport pyramid

### ISSUE THREAD

**Issue by skomaroff** [theCrag/website#4111]
I have noticed an inconsistency.  This appears to happen only with the old tick flow.

When I log a green point ascent of a sport route, the ascent shows up in my sport pyramid and in my trad CPR timeline.  I would expect either trad for both (more intuitive) or sport for both (less intuitive, but at least consistent).

Here is an example.  I logged (and have since deleted) an ascent of a route far harder than I can actually climb so it would be obvious where it is in each graph.

![image](https://user-images.githubusercontent.com/84152181/187318170-9d126d98-b9ab-42f2-a179-f955d8ab6acd.png)

This shows up as the only 5.13c in my sport pyramid.
![image](https://user-images.githubusercontent.com/84152181/187318291-d06b85cb-a394-40ee-85b4-7b622ab9af5e.png)

In my CPR timelines, it appears as trad instead.
![image](https://user-images.githubusercontent.com/84152181/187318432-f2bdadf1-b691-4f5c-aee8-153ffa32d2f6.png)

Likewise, it is missing from the search generated by clicking the 5.13c row in my pyramid
![image](https://user-images.githubusercontent.com/84152181/187318635-05f3b304-addc-4f5c-8ae3-25df57de68cf.png)

These are the actual ascents that lead to me looking for this inconsistency in the first place:
- https://www.thecrag.com/ascent/3928861314
- https://www.thecrag.com/ascent/3928867290

**Comment by skomaroff** [comment]
Related issues:

https://github.com/theCrag/website/issues/2770
https://github.com/theCrag/website/issues/1585
https://github.com/theCrag/website/issues/3544

**Comment by scd** [comment]
The old flow is not supportable for issues regarding different route and ascent gear styles. Just move to the new flow.

**Comment by skomaroff** [comment]
These are the actual ascents that lead to me looking for this inconsistency in the first place:

- https://www.thecrag.com/ascent/3928861314
- https://www.thecrag.com/ascent/3928867290

They were logged a couple years ago, so there are probably many affected ascents that were logged before the new flow existed.

I'll re-log my ascents with the assumption that others' will be taken care of during the transition to the new flow.

**Comment by scd** [comment]
At some point we will do a data migration but there is still an uncertain period while both flows will be available.

If you want to correct anything then don't relog, just edit using the new flow.

**Comment by skomaroff** [comment]
> don't relog, just edit using the new flow.

I hadn't seen that option before, nice!
