### ISSUE TITLE
New tick flow: Can't log an via ferrata ascent as "via ferrata"

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#4113]
Using the new tick flow I just can log a generic tick on a via ferrata:
![grafik](https://user-images.githubusercontent.com/1528540/189232827-ac0dcc86-49dd-4211-8a8e-2d1649ec5f74.png)
and the stream does not show the same icon as if logging with the old interface:
![grafik](https://user-images.githubusercontent.com/1528540/189232558-c1e81dee-bd48-4399-a834-140264b7cf79.png)

What I expect:
* [ ] same tick types as in the old UI

**Comment by nicHoch** [comment]
one of the drivers for the new ticking interface was the overdue cleanup of the tick types. 
the via ferrata tick type will become deprecated.

you should be able to find all your via ferrata ascents in searches anyway - why do you feel that this tick type can not be replaced with ascent-gear-style via ferrata in combination with ascent-tick-type "tick"?

**Comment by lordyavin** [comment]
Just because I wasn't aware of that. The requirements and design decisions for the feature are not public, or are they?

**Comment by lordyavin** [comment]
This issue is not complete. Please close issue as 'won't fix'
