### ISSUE TITLE
PDF crag guide: Add update-button or auto-updates for guide

### ISSUE THREAD

**Issue by Elnoggernog** [theCrag/website#4117]
When downloading the instant-pdf crag guide, many of the new routes are not visible. The instant-pdf crag guide is pretty old on most crags

**Comment by Elnoggernog** [comment]
As example: 
https://static.thecrag.com/pdf/518688876.pdf is missing multiple routes in many sectors of "Hängender Stein" (https://www.thecrag.com/en/climbing/austria/area/518688876)

**Comment by Elnoggernog** [comment]
In this sector the routes are missing even though they exist in the original list:
dont exist here:
![image](https://user-images.githubusercontent.com/115220517/194526254-f02deee8-8a12-416f-93ca-47683116b648.png)

exist here:
![image](https://user-images.githubusercontent.com/115220517/194526761-9c80959e-2cc9-428c-be8c-70e8e77c8733.png)

**Comment by rouletout** [comment]
There is a routine for that - you can also create a Custom PDF which updates immediately - does that help?

Closing, re-open if you need further help.
