### ISSUE TITLE
Bug - a negative number of ratings

### ISSUE THREAD

**Issue by willmonks** [theCrag/website#4118]
Bloodline at Bardens is showing as having no stars.  https://www.thecrag.com/climbing/australia/blue-mountains/adults-only-cave/route/145128789

But it's definitely a 2-3 star route. It has 33 ascents of which I can see at least 5 have given quality ratings.  But the quality histogram only shows 3 ratings. And below that it says "Based on -3 ratings." Obviously a route can't have a negative number of ratings. And clearly this route deserves stars even just on this data. So there seems to be a bug.

**Comment by rouletout** [comment]
Stats needed an update - done and closing
