### ISSUE TITLE
Private Comment when logging ascent

### ISSUE THREAD

**Issue by flmann** [theCrag/website#4120]
When viewing ascents there is a field called „private comment“ (see screenshot). This field does not seem to be editable. 

Being able to log private comments, only visible for myself would be a useful feature for me and other friends as well.

![PNG image](https://user-images.githubusercontent.com/23436033/195387597-5228f361-af8b-4332-bd2a-e7d184ed81ca.png)

**Comment by scd** [comment]
This is available in the new tick flow. You can also edit an ascent from the old tick flow using the new flow and it will be converted.
