### ISSUE TITLE
Hardest ascents not well reported in profile

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4122]
Hi there,

I’ve found out that at least one of my ascents is not shown properly in the profile summary.

https://www.thecrag.com/climber/jositogg

![86D36142-3FD0-4FEE-81F7-0E03E952F8D9](https://user-images.githubusercontent.com/17315806/197389372-7925286a-507a-4381-b4e7-48991ba01990.jpeg)
![DA8F7E52-DC01-4D45-9D55-8BDF258DC330](https://user-images.githubusercontent.com/17315806/197389376-5306b6be-7955-47e0-8fe8-b3c2d1b6d166.png)

That route should appear in the on sight list.

Regards!

**Comment by rouletout** [comment]
This is most likely a cut over issue as the onsight was logged with the old interface and the others with the new one which took priority in the profile... not much we plan to do here, closing. If you want that updated please edit the ascent with the new interface - this should fix it.

**Comment by Arzorth** [comment]
It did, although I had to update a considerable number of routes logged with the old interface.

The problem beneath this is that old interface top rope ascent were logged with this tick:  ![image](https://user-images.githubusercontent.com/17315806/217304075-3a5a94e8-6657-4f1c-b42f-46d1df16b490.png)

While new interface top rope ascents are logged with this other tick: ![image](https://user-images.githubusercontent.com/17315806/217304519-efac1fe0-659c-4855-a17c-2aae27edbbd1.png)

Maybe these two types of ticks that represent the same concept should be computed together in the user profile.

.

By the way, to find top rope hang dog and on sight ascents logged with the new interface, the users have use "lead ascents" filters, which is a weird behaviour:

![image](https://user-images.githubusercontent.com/17315806/217305444-b2329883-6b93-4bcc-88a4-6d6e51a22822.png)
