### ISSUE TITLE
New log ascent - Private comments not visible enough

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4123]
The new log ascent allows to record private ascent comments. That's nice for recording personal beta or progress. 

Problem:
Once recorded, private comments are too hidden away to be useful. There is a lack of indicators or search capabilities to find your own private comments. At the moment you have to open each individual ascent to see if there is a private comment or not.

In the stream event, there is no indication whatsoever, that there is an additional private comment
![image](https://user-images.githubusercontent.com/30682796/197465387-fa9fd20f-8bf3-4a01-83ab-48f6df3d6954.png)

Also in the list of ascents I don't have any reference to the existence of a private comment
![image](https://user-images.githubusercontent.com/30682796/197466008-4d3d0d42-41dc-493d-8fef-b304a13ad0a9.png)

Only when I open the individual ascent do I find the private comment
![image](https://user-images.githubusercontent.com/30682796/197466154-a6add896-839f-4eba-b616-70e9ae799cd5.png)

For reference

- Stream event: https://www.thecrag.com/event/6732282762
- Ascent with private comment: https://www.thecrag.com/ascent/6732378282

Expected
- (at least) show an indicator in the stream event and/or search facet that there is a private comment per route
- (even better) show the private comment in the stream event and search facet directly

PS:
I think that's a kind of similar issue as https://github.com/theCrag/website/issues/4012 where users are just not aware of available content

**Comment by rouletout** [comment]
Fixed with latest release - closing
