### ISSUE TITLE
New tick flow does not distinguish tick icons sufficiently

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4127]
To Reproduce

1. Log a climb as Sport - Flash
2. Log a climb as Second - Flash
3. Log a climb as Toprope - Flash
4. Look at the Stream event and try to figure out which ascent was in which style

In the new tick flow, all flash ticks seem to have the same icon
![image](https://user-images.githubusercontent.com/30682796/198900090-3fd70e60-0525-43b8-970d-e4d48c0a18c9.png)

They were distinguished better using the old tick flow.

In the following situations, I would like to see a distinction between the icons

~~Looking at stream event, because I want to know if I or others led a route or toproped it~~

Browsing the route list of a crag, I want to know which of the routes here are "unfinished" for me. I consider a toprope flash not equal to a lead flash, thus for me the route is still "unfinished"

**Comment by killakalle** [comment]
I'm just seeing that there is actually a distinction in the stream event. The style is at the end of the line. (Which is still weird, because you need to look at the start and at the end of line at the same time to know how a route was climbed)

However, the second problem that I've listed is still valid: 
in the route list a "toprope flashed" route looks the same as a "lead flashed" route.

**Comment by scd** [comment]
The old tick types will eventually go. They were only ever there because we had no way of dealing with differences between tick types of different gear styles. Now we do.

The old tick types are really problematic as they have translation issues in the image and they are ad hoc and don't even cover all the gear styles.

**Comment by endolith** [comment]
> I'm just seeing that there is actually a distinction in the stream event. The style is at the end of the line. 

This isn't a solution, either.  It shows "trad":

![image](https://user-images.githubusercontent.com/58611/200230401-de78522d-b79d-47fa-94bd-5288aa6173f9.png)

even though it was entered as a TR ascent:

![image](https://user-images.githubusercontent.com/58611/200230447-cd492a16-cef7-470a-9f47-1cab299435db.png)

> (Which is still weird, because you need to look at the start and at the end of line at the same time to know how a route was climbed)

Agreed.  The tick type icon should show the style and type like it used to: 

![image](https://user-images.githubusercontent.com/58611/200227815-41a6b7d0-7dd7-4c02-ac56-9425d885dfe8.png)

**Comment by rouletout** [comment]
1+ from https://github.com/theCrag/website/issues/4137

**Comment by quaestor** [comment]
+1 from me. It's annoying that your eyes need to go from the very left all the way to the very right of the page in order to see whether someone "onsighted" a route or he did it first try on top rope …

**Comment by rouletout** [comment]
Ascent gear style icons added, closing
