### ISSUE TITLE
Routes can not be deleted

### ISSUE THREAD

**Issue by bernt-matthias** [theCrag/website#4129]
I noticed that deleting a route does not work. Instead clicking delete redirects to the help.

Accidentally created this one https://www.thecrag.com/en/climbing/italy/sardinia/cala-gonone/route/6766963167 and can't delete it.

**Comment by scd** [comment]
All the routes in the area have the same name. Normally the names would be `Senza nome 1`, `Senza nome 2`, ...

Rather than deleting we prefer to merge.

**Comment by bernt-matthias** [comment]
Hi @scd .. these are (unfortunately) the official route names according to guide books.

**Comment by bernt-matthias** [comment]
Main point is the the `delete` functionality did nothing ..

**Comment by rouletout** [comment]
See corresponding help - we don not delete in general but merge - this area was cleaned up, closing
