### ISSUE TITLE
Greater then symbol in forum post changes to &gt;

### ISSUE THREAD

**Issue by Beakerboy** [theCrag/website#4135]
If a forum post begins with >, the preview area renders this paragraph with a left bar and indented, as is typical in markdown to indicate quoting text. However, when the post is submitted, the greater than is replaced with &amp;gt;, preventing the formatting from taking place.

https://www.thecrag.com/discussion/6782661252/how-to-add-a-structured-tag-to-a-route

**Comment by rouletout** [comment]
Dup of https://github.com/theCrag/website/issues/2967 - closing here
