### ISSUE TITLE
Descriptions and icons are wrong for New Log Ascent

### ISSUE THREAD

**Issue by endolith** [theCrag/website#4137]
All of these descriptions are wrong:

![2022-11-06 23_33_43-South Wall, Lower Level, Sport climbing _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227517-e8dfc38a-2ef3-443a-937e-9c06315135e0.png)
![2022-11-06 23_33_35-South Wall, Lower Level, Sport climbing _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227519-b66467f2-802a-4901-816a-3f31b200f299.png)
![2022-11-06 23_33_27-South Wall, Lower Level, Sport climbing _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227520-2c9c196f-ab8b-4bd8-b039-d822394e95c9.png)
![2022-11-06 23_33_16-South Wall, Lower Level, Sport climbing _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227522-444a2f23-3517-4bdc-8aeb-320335ae484d.png)
![2022-11-06 23_33_04-South Wall, Lower Level, Sport climbing _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227523-8201b268-7b34-411a-aedb-73ef97104c76.png)
![2022-11-06 23_32_55-South Wall, Lower Level, Sport climbing _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227525-c812765e-1a18-4b1b-b6c7-4f783a248e1c.png)

And this one is missing:

![2022-11-06 23_30_17-South Wall, Lower Level, Sport climbing _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227526-c7504249-f9bd-4eef-ab16-d54fde2e80a5.png)

And it should show TR or 2nd-specific icons, instead of lead icons:

![2022-11-06 23_37_53-Ascents_ Ascents by Jonathan Bright _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227813-1891ee82-c78b-4e01-9bd5-1aa160c76cc3.png)
![2022-11-06 23_38_36-Ascents_ Ascents by Jonathan Bright _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227815-41a6b7d0-7dd7-4c02-ac56-9425d885dfe8.png)
![2022-11-06 23_38_31-Ascents_ Ascents by Jonathan Bright _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227816-91040925-08e0-420d-ac5d-33349a718aed.png)
![2022-11-06 23_38_01-Ascents_ Ascents by Jonathan Bright _ theCrag — Mozilla Firefox](https://user-images.githubusercontent.com/58611/200227817-eebf1b51-0f98-43d9-aa01-aff1fff62da5.png)

These generic lead icons are even being shown in the Ascents list, which is not correct:

![image](https://user-images.githubusercontent.com/58611/200227902-f978f231-f922-4abb-8436-5629134a564b.png)

Most of these are TR, not lead.

**Comment by killakalle** [comment]
I've reported a similar issue on #4128

**Comment by rouletout** [comment]
Descriptions will be updated with next release - rest is dup of https://github.com/theCrag/website/issues/4127 closing
