### ISSUE TITLE
Ascent comments too squeezed on mobile view

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4139]
To reproduce:

[On mobile]
1. Open a route with verbose ascent comments
2. Open the list of ascents, e.g. [this](https://www.thecrag.com/es/escalar/spain/chulilla/route/616986339/ascents)
3. Read the ascent comments

Expected:
- Ascent comments are easily readable
- No unnecessary scrolling needed

Actual:
- Ascent comments are squeezed into too narrow column
- Lot of scrolling needed
- Lot of space wasted
- There even is an (unused?) column: Difficulty

![image](https://user-images.githubusercontent.com/30682796/200426795-2ab0ea25-ad4c-4b6d-8c0d-d5d12b795ad1.png)

Example:
https://www.thecrag.com/es/escalar/spain/chulilla/route/616986339/ascents

**Comment by killakalle** [comment]
Same issue on Desktop meanwhile

![image](https://user-images.githubusercontent.com/30682796/208353929-282f8bef-0f13-4770-9e40-d5626f4c0538.png)

**Comment by rouletout** [comment]
Fixed with latest release - closing
