### ISSUE TITLE
Search facet - Cannot search for ascent type "De segundo" (seconding)

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4141]
As far as I can see, the search facet has not been adapted yet, to fully support the new tick flow. "Ascent type" and "Style" are still oriented to the old ticking.

I've found one problem in particular:
It is now not possible to search for ascents of style "De segundo" (seconding). This entry is missing from the list.

![image](https://user-images.githubusercontent.com/30682796/201619069-1eb67967-937f-4c18-a8fa-90299e15ef12.png)

**Comment by rouletout** [comment]
Fixed with next release, closing
