### ISSUE TITLE
Unacceptable long loading times

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4147]
Hi guys, it's me again.

I already told you privately when I first paid my supported donation, but I consider relevant mentioning it again, because I've seen the effects it has in real life and in the loss of revenue for the company/team it means.

### Context
The web loads EXTREMELY low, it most of the times takes about 5-10 seconds (in some, even 30) to load one crag page, which is unacceptable for most of the potential users (not for me, I'm a patient person).

### Example
I maintain pretty much alone the gym page of my local gym (which doesn't have any other ascent record system, so there is no competence at all for TheCrag, so it is a good opportunity to position as "gym ascent recording tool"), to log my own ascents and with the idea of providing my friends and the people climbing at the gym a method to log their ascents.

To advertise a little bit the page, I created a QR code and I printed some papers that I distributed around the gym.

After this, I've seen a lot of people scanning the QR code, waiting for the page to load for about 5-10 seconds and, with no result, locking the cellular, leaving it in a table and continuing climbing.

### Consequences
This means that TheCrag has already lost many potential long term users just because it lost its window of opportunity (10 seconds).

This causes loss of potential users, which means less potential donors and ads clicks, which means less potential money for TheCrag, which means less resources to improve the page itself.

Imagine Facebook or Google taking 10 seconds to load a query, nobody would use them.

### Suggestion
Invest money in making the site fast and user friendly, otherwise you are going to lose more and more users and it will become a nice and complete but unuseful database.

Regards,

José María

**Comment by lordyavin** [comment]
Duplicate of #3976

**Comment by lordyavin** [comment]
@Arzorth please add your input to #3976 and close this issue. Let me know if I'm wrong that this issue is a duplicate.

**Comment by Arzorth** [comment]
indeed it is duplicated, closing
