### ISSUE TITLE
Ascent facet regression, extra columns in wrong places messes up the layout

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#4151]
hi guys, there has been a recent regression which messes up the column layout, there is an empty wrong column header on the left which forces a blank column on the right and all the columns and headers to not line up which messed up the widths of the columns

![image](https://user-images.githubusercontent.com/187449/208218897-3fc9ec79-c4dc-4876-a44b-194a7547f35c.png)

https://www.thecrag.com/en/climbing/australia/gara-gorge/upper-gara-gorge/route/3260125449/ascents

**Comment by killakalle** [comment]
I've reported this also here
https://github.com/theCrag/website/issues/4139
