### ISSUE TITLE
The 'Log x ascents' button is broken on mobile and desktop

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#4152]
If you are on mobile and you select a couple routes to tick, then the button at the bottom is now partially transparent (which I like) but the button is no longer clickable so you can't tick at all using this method.

![image](https://user-images.githubusercontent.com/187449/208219527-f6a2b1ea-60ce-4d5c-a206-7378ee719902.png)

the button is disabled:

![image](https://user-images.githubusercontent.com/187449/208219480-96cb69de-7c84-4f6a-a148-6eee642fa6c6.png)

**Comment by brendanheywood** [comment]
I tried to log routes yesterday on mobile and had to wait til today to log on desktop, and now I've realized that it is also broken on desktop:

![image](https://user-images.githubusercontent.com/187449/208219688-24b56a73-e074-44cf-811e-bda7a8230b57.png)

**Comment by rouletout** [comment]
Fixed, closing
