### ISSUE TITLE
Zero points are translated to 1 grade (but 1 point to 0.01 grade)

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4155]
![image](https://user-images.githubusercontent.com/17315806/207267601-c166fb3f-7e32-4eb3-9542-3b4f14d551db.png)
![image](https://user-images.githubusercontent.com/17315806/207271248-c42aedfa-f902-4a94-953e-f514562aeea9.png)

**Comment by scd** [comment]
I have fixed this on Simon's dev. Will be available from next release:

<img width="291" alt="Screen Shot 2023-09-04 at 3 27 25 pm" src="https://github.com/theCrag/website/assets/373058/511e978e-1a13-46c0-8203-364aa2b21b5e">
