### ISSUE TITLE
Impossibility to log sport ascents in routes set for top rope (but trad and free solo yes)

### ISSUE THREAD

**Issue by Arzorth** [theCrag/website#4156]
This is interesting for gyms that have some routes with the top rope attached (hence, marked as top rope type) but they also have quickdraws in case a client wants to do it lead.

![image](https://user-images.githubusercontent.com/17315806/209193883-35422753-5fcc-4f0b-ba3d-daa574430f78.png)

**Comment by rouletout** [comment]
This is as designed - this should be recorded as a Sport route and ticked as a top rope if climbed top rope, closing
