### ISSUE TITLE
Duplicate stream events (caused by commenting?)

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4163]
I believe that commenting on ascents in the stream results in a duplicate display in the stream.

To reproduce:

1. Open the stream https://www.thecrag.com/dashboard
2. Comment on one of the ascents
3. (wait some time.... hours? (a day?)
4. Look at the stream again

Expected
- One stream event

Actual
- Two stream events

![image](https://user-images.githubusercontent.com/30682796/209647773-c685d37c-06ad-4ba8-ad03-066865a9f230.png)

![image](https://user-images.githubusercontent.com/30682796/209647879-153ebe24-5e24-42ad-b17f-517e4dc8e454.png)

Reference:

- https://www.thecrag.com/event/7006298460
- https://www.thecrag.com/event/7007539371

**Comment by scd** [comment]
This is intentional. Discussing an event creates a new discussion event. Discussion events move in time with the last comment but the original event stays.
