### ISSUE TITLE
Coordinates in map wrong

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#4164]
The coordinates of this area (https://www.thecrag.com/en/climbing/portugal/area/6990966183) are wrongly in Africa instead of in Madeira island. So the first map section is half the world and you have to zoom in a lot to get to Madeira.

Reason might be, that i entered a route coordinate firstly wrong (longitude without "-"), but later corrected it, but there are no crag coordinates to change. How can I do it myself, or you do it please.

Thx!

**Comment by rouletout** [comment]
Fixed itself (probably?)
