### ISSUE TITLE
Remove spam accounts after a while

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#4174]
This search: https://www.thecrag.com/en/climbing/croatia/dalmatia/area/983281410/search?S=505

... showed these accounts:
https://www.thecrag.com/climber/505011586qqcom
https://www.thecrag.com/climber/505115925qqcom
https://www.thecrag.com/climber/505157260qqcom
https://www.thecrag.com/climber/505865960qqcom

... and that's really not necessary. Either don't show suspected spam accounts in the search, or delete these after a while (they were created in 2019.)

**Comment by rouletout** [comment]
Thanks, they must have fallen between the cracks - we have a process in place but these were created before... removed now
