### ISSUE TITLE
Full size image opens as plain text

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#4180]
When I click "view full size" here:
https://www.thecrag.com/photo/7220475573

I get a lot of binary crap on my screen. I think the content-type header is missing in the response.

**Comment by skomaroff** [comment]
Was reported here too: https://www.thecrag.com/discussion/7172482902/release-106-new-image-server#m7194571794

Seems to be fixed?

**Comment by scd** [comment]
Yes fixed.

**Comment by matozoid** [comment]
Thanks!
