### ISSUE TITLE
activity feeds of people who don't follow me are empty

### ISSUE THREAD

**Issue by skomaroff** [theCrag/website#4183]
I have noticed today that many activity feeds are empty.  It seems to be those of people who don't follow me.
I can see activities of people who follow me.

For example, Alex Megos doesn't follow me.  I don't see anything below his CPR timelines even though I have in the past.

https://www.thecrag.com/climber/alexmegos
![Screenshot 2023-03-07 at 08-53-45 Alex Megos - Sport climber Germany theCrag](https://user-images.githubusercontent.com/84152181/223442594-05a638ca-7f93-4c45-8ef9-2015918bb289.png)

One profile even had an error instead of an activity feed. This error went away after refreshing the page, but there are still no activities listed.

https://www.thecrag.com/climber/marcofvb
![Screenshot 2023-03-07 at 08-44-38 Marco Lefebvre - Boulderer New Zealand theCrag](https://user-images.githubusercontent.com/84152181/223441762-f2e99fbf-accf-4d52-9e28-1a0b633de4ed.png)

Most profiles are currently loading slowly for me. This may be related?

**Comment by skomaroff** [comment]
I can do more checks if helpful.

**Comment by skomaroff** [comment]
I have since seen a similar "Internal Server Error" on the dashboard too.  It also disappeared upon refreshing the page.  

I created a separate issue for that error: #4184

**Comment by scd** [comment]
We have tightened up privacy so you can have a public profile without being tracked.

**Comment by skomaroff** [comment]
Ok, so it sounds like most of this is intentional but unannounced?

**Comment by killakalle** [comment]
@scd was that a necessary move?

 I've often looked into people's activity feed to get an impression of what they're up to - both in terms of climbing as well as content contributions.

I also used this information to judge how much I want to "trust" their quality assessment of routes. Unfortunately, I climb in an area where many routes have few or no ascents on theCrag. If there is now one ascent with Megaclasic, I want to see if this person rarely or frequently assigns this rating. 

Unfortunately, there are a few climbers in my area that put the tag Megaclassic under each of their ascents. So if I only see their rating under a route, I just dismiss it as unreliable information.

**Comment by scd** [comment]
Yes it was. Sorry no undo.

I think the next step is to collect use case examples like this so we can look at alternatives.

BTW I think the give everything 5 stars fad is not helpful for us and has much wider implications we need to get our heads around.

**Comment by skomaroff** [comment]
@killakalle, you can still get a sense of how liberal people are with stars by looking at their tick list.
