### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by skomaroff** [theCrag/website#4184]
I have been seeing sporadic cases of "500 Internal Server Error" over the last 8 hours.

Here's a screenshot of the latest occurrence, 
![image](https://user-images.githubusercontent.com/84152181/223538188-5a661387-7bef-44b2-b90e-4c98761ff3e0.png)
This came from navigating to https://www.thecrag.com/photo/1535330175 after clicking the banner on https://www.thecrag.com/en/climbing/new-zealand/wanaka/area/817422393

I saw the same when loading https://www.thecrag.com/dashboard earlier

The second example in #4183 may be related.

Also reported by [Danny van Bruggen](https://www.thecrag.com/climber/macumbamacaca) and [Christoph Rauch](https://www.thecrag.com/climber/quaestor) @ https://www.thecrag.com/discussion/7270129182/anonymous-traffic-limit-trial#m7274972523

**Comment by rouletout** [comment]
Should be fixed by now - please continue reporting if it occurs - leave it open for a while longer

**Comment by skomaroff** [comment]
Yes, seems to be fixed!
