### ISSUE TITLE
Unfavorite -> NaN

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#4185]
I unfavorited Spain, and it shows this:

![afbeelding](https://user-images.githubusercontent.com/55701/224657810-963e948f-6cb8-48e3-aa61-0db8e1be5167.png)

... a refresh fixes it.

**Comment by frikiluser** [comment]
It works for other crags.

I've reproduced the issue with Spain. Fav gives NaN (reload show the favs number), then Unfav and again NaN.

No errors seen on browser javascript console.
POST to `https://www.thecrag.com/api/climber/update?cookieAuth=1` seems correct.

Probably a low priority bug.
Hope it helps.

**Comment by scd** [comment]
FIxed in dev. This was a comma in the UI count not converting when incrementing and decrementing
