### ISSUE TITLE
Borrar vias

### ISSUE THREAD

**Issue by edu314** [theCrag/website#4187]
Buenas, soy creador y editor de las vias de Huelva, Calañas https://www.thecrag.com/es/escalar/spain/area/7196291685

Cree las vias pero se duplicaron al reorganizar los sectores (error mio de novato, perdon), las vias duplicadas las he renombrado como Borrar 1, Borrar 2... algun editor con mas rango o mas habilidades puede borrarlas para que no aparezcan? 

Muchas gracias

**Comment by frikiluser** [comment]
This is a request to remove routes named using the pattern "Borrar X" in the linked sector.

**Comment by nicHoch** [comment]
Done
Thx for your contributions
