### ISSUE TITLE
Custom PDF Status=Error

### ISSUE THREAD

**Issue by frikiluser** [theCrag/website#4191]
I've tried to generate a custom PDF and didn't work.
Tested with different sectors and got same error result.

Hope it's temporary 🤞🏾

**Comment by lordyavin** [comment]
Please provide screenshots,links

**Comment by frikiluser** [comment]
After some days it's working fine.

I can't attach any snapshot because the `Errors` in the `PDF crag guides` section disappeared.

Consider closing. Thanks!

**Comment by frikiluser** [comment]
Snapshot showing `Your Crag Guide PDFs` web section with recent errors: https://ibb.co/zRzXWLJ

Comuna de Caimari: https://www.thecrag.com/en/climbing/spain/mallorca/las-perxes/area/1003799160
Puig St. Marti: https://www.thecrag.com/en/climbing/spain/mallorca/area/123205494

**Comment by rouletout** [comment]
Fixed
