### ISSUE TITLE
Weird formatting in timeline

### ISSUE THREAD

**Issue by matozoid** [theCrag/website#4192]
Using firefox:

![afbeelding](https://user-images.githubusercontent.com/55701/230375772-d3ad8d61-af5d-41cc-bdb5-11d49feeb5dc.png)

**Comment by lordyavin** [comment]
Is your feed still showing this?

**Comment by matozoid** [comment]
Looks okay now:
![afbeelding](https://user-images.githubusercontent.com/55701/233287856-dd4a09a0-6507-4d7b-aa2f-27dd60f9f7f8.png)

(blue part is my selection from searching, never mind that)
