### ISSUE TITLE
Internal conversion of Swedish grades is slightly off

### ISSUE THREAD

**Issue by fritz-raphael** [theCrag/website#4195]
The **internal grade conversion of the Swedish grading systems seems slightly off**, considering some mapping tables from Swedish guidebooks and my own experience. This issue has been opened in [this discussion on theCrag's forum](https://www.thecrag.com/discussion/7525626117/swedish-grades-are-slightly-off---please-adjust-in-relation-to-other-grades) and a similar case has been made a few years ago for the Norwegian Grading System (issue #1004). 

All guidebooks diverge a little bit on some grades (see the pictures below), but I tried to compile a consensus of the examples I had. 

FR | SWE as mapped on theCrag | SWE according to Guidebooks
---|---|---
-|-|**bold** if uniform across guidebooks
3a|3|3
3b|3+|3+
3c|4|3+/4-
4a|4+|4-
4b|5-|4
4c|5|4+
5a|5+|5-
5b|5+|5
5c|6-|5+
6a|6-|6-
6a+|6|6
6b|6/6+|6+
6b+|6+|6+/7-
6c|7-|7-
6c+|7-/7|**7**
7a|7|**7+**
7a+|7+|**7+/8-**
7b|7+/8-|**8-**
7b+|8-|**8**
7c|8|8/8+
7c+|8|**8+**
8a|8+|**9-**
8a+|9-|**9-/9**
8b|9-/9|**9**
8b+|9|9/9+
8c|9+|9+
8c+|10-|9+/10-

So while the differences are relatively minor and not even uniform across guidebooks up until `FR 6c`, **from `FR 6c+` on , the guidebooks all agree on a mapping that's slightly different from theCrag's current one**. 

Can you change the internal mapping so that climbs logged in Swedish grading system (even historical ones) are mapped correctly? 

---

Here are pictures of the mapping tables from the guidebooks I used: 

- **Klättring på Kullaberg** (2014): 
![IMG_0037](https://user-images.githubusercontent.com/85614992/232401450-f0352c2c-13e7-4842-8885-a591f8ca2a9f.jpeg)

- **Klättring i Göteborg** (2020): 
![IMG_0036](https://user-images.githubusercontent.com/85614992/232401764-22bfcc68-ee5d-4174-ae0c-e3d4bf38d2f8.jpeg)

- **Klättring i Bohuslän** (2015): 
![IMG_0035](https://user-images.githubusercontent.com/85614992/232402068-3c52778f-314d-49d7-87f3-44c9735cc1bf.jpeg)

**Comment by rouletout** [comment]
Thanks for that - we'll look into that on our net "grade clean up"

**Comment by scd** [comment]
This card is really well done and now makes it possible for us to have a proper discussion relative to established references. Thank you for putting the time into this.

Just so we are all on the same page, we are using the UIAA grade as a reference to map to our internal grading system. So we need to work out where we are out relative to the UIAA system. Typically we get a new grading system in by referencing it to another grading system, so assuming the other grading system is correct the new one is also correct. For Swedish grades we choose UIAA as our reference grading system. This choice cannot be changed at this point as it is too much work.

I have done a quick audit of references vs theCrag and come up with this

```
SWE 1-  => UIAA I-
SWE 4  => UIAA IV [looks correct in one reference but different in another]
SWE 5  => UIAA V [looks like it should be UIAA VI- for both references]
SWE 6-  => UIAA VI+ [looks correct]
SWE 7+  => UIAA VIII+ [looks like it should be UIAA VIII for both references]
SWE 9  => UIAA X+ [looks like it should be X/X+ for both references]
```

In the above mapping theCrag maps the upper side of Swedish grade to the upper side of the UIAA grade and assumes grades in between are linear. 

Can you do independent analysis and confirm what we should change the mappings to with reference to UIAA? It is essential we get the mapping relative to UIAA for Swedish grades. Relative to French should be done as a sanity check, not a specification.

**Comment by fritz-raphael** [comment]
> Thank you for putting the time into this.

Same goes out to you: Thank you for all your work and dedication! 

> SWE 1-  => UIAA I-
SWE 4  => UIAA IV [looks correct in one reference but different in another]
SWE 5  => UIAA V [looks like it should be UIAA VI- for both references]
SWE 6-  => UIAA VI+ [looks correct]
SWE 7+  => UIAA VIII+ [looks like it should be UIAA VIII for both references]
SWE 9  => UIAA X+ [looks like it should be X/X+ for both references]

Yes, the references you cite in square brackets seem right to me (I don't have any references directly comparing SWE to UIAA, but with FR as an intermediate and my own experience, this seems correct). 

I'm quite confident that the mapping of UIAA to SWE as shown in the below table is correct for the intermediate grades from UIAA 6 to 9+. Below and above that range, however, I don't have any personal or external reference points; I'd have to translate UIAA to FR and FR to SWE. So I marked the UIAA grades where I'm confident of the mapping towards Swedish grades in bold letters again. 

To complete the above mapping table: 

FR | SWE as mapped on theCrag | SWE according to Guidebooks | UIAA
---|---|---|---
-|-|**bold** if uniform across guidebooks| **bold** if confident mapping to SWE
3a|3|3|
3b|3+|3+|
3c|4|3+/4-|
4a|4+|4-|4
4b|5-|4|5-
4c|5|4+|5
5a|5+|5-|5+
5b|5+|5|6-
5c|6-|5+|**6**
6a|6-|6-|**6+**
6a+|6|6|**7-**
6b|6/6+|6+|**7**
6b+|6+|6+/7-|7/7+
6c|7-|7-|**7+**
6c+|7-/7|**7**|**8-**
7a|7|**7+**|**8**
7a+|7+|**7+/8-**|**8+**
7b|7+/8-|**8-**|**8+/9-**
7b+|8-|**8**|**9-**
7c|8|8/8+|**9**
7c+|8|**8+**|**9+**
8a|8+|**9-**|9+/10-
8a+|9-|**9-/9**|10-
8b|9-/9|**9**|10
8b+|9|9/9+|10+
8c|9+|9+|11-
8c+|10-|9+/10-|11

**Comment by scd** [comment]
I made the following changes

- SWE 4- maps to UIAA 4 (was SWE 4 maps to UIAA 4)
- SWE 5 maps to UIAA VI- (was SWE 5 maps to UIAA V)
- SWE 7+ maps to UIAA VIII (was SWE 7+ maps to UIAA VIII+)
- SWE 9 maps to UIAA X (was SWE 9 maps to UIAA X+)

Now updated in production.
