### ISSUE TITLE
Numbering mismatch in HTML guide

### ISSUE THREAD

**Issue by isaac-aa** [theCrag/website#4202]
Hello, thanks for the amazing website!

I think that there is a bug in the HTML guide, at least for this area: https://www.thecrag.com/es/escalar/spain/tenerife/area/4312783332

The first route is numbered "2" and correctly identified in the topo:
![Captura de pantalla 2023-05-31 a las 13 14 12](https://github.com/theCrag/website/assets/19895420/d5c9746a-f771-4342-a5aa-ebc830b59be7)
However, in the generated HTML guide: https://www.thecrag.com/es/escalar/spain/tenerife/area/4312783332/guide the first number is 1 although in the topo image that route is still labelled as 2:
![Captura de pantalla 2023-05-31 a las 13 13 29](https://github.com/theCrag/website/assets/19895420/c91c3fb3-b187-43b5-848e-aaa893e8e731)

This implies that all the routes in this area are off by one (which caused us to try climbing the wrong routes...)

This does not seem to happen when generating the PDF, but I generally use the HTML guide and "print it as pdf" from my web browser for offline access.

Thanks!

**Comment by killakalle** [comment]
@isaac-aa 

In my experience, this happens on crags where annotations are used. Somehow the HTML guide does not use the same logic when generating route numbers as the regular page.

Here's another example:

<img width="875" alt="Screen Shot 2023-06-01 at 17 46 06" src="https://github.com/theCrag/website/assets/30682796/886efd81-91c0-43cd-b48d-e384d3e94038">

Source: https://www.thecrag.com/es/escalar/spain/valencia/gestalgar/area/2561079750/guide

As a result, it makes using the HTML guide quite awkward and cumbersome.

Might be related to this... ? https://github.com/theCrag/website/issues/3753

**Comment by scd** [comment]
This is a pretty serious bug. I have jumped in and done an emergency fix. Thanks for bringing to our attention.

@isaac-aa can you please verify that it is fixed. And @killakalle can you please verify your example.

**Comment by isaac-aa** [comment]
I confrm that the HTML guide is now correctly generated. Thanks!
