### ISSUE TITLE
Wrong display in notable ascents for K4 - no gym 

### ISSUE THREAD

**Issue by whatsername88** [theCrag/website#4212]
I have recently changed K4 - Der Kletterfelsen from gym to crag, however on my notable acsents overview the ascents I made there are still listed under "gym sport" and "gym top rope", but it must be all listed under "sport" now, since K4 is no gym at all. 
Could you please fix this?
<img width="443" alt="Screenshot 2023-07-11 174609" src="https://github.com/theCrag/website/assets/139253000/b0cbb861-98c4-4912-8692-77b6d006c5cd">

**Comment by scd** [comment]
Unfortunately this is not fixable as the ascents are recorded with the gym status of the area when logged. You have to remove and re-log the ascents.

**Comment by braeuni** [comment]
Isn't this a structure with artificial holds? So why did you change the type in the first place?
The ascents should be listed under gym, I suggest changing it to "Künstliches Gebiet".

**Comment by whatsername88** [comment]
Yes, you are right. I just changed it back to artificial area - "Künstliches Gebiet". But does that count under gym as well? For me a gym is a place where I go inside climbing like a hall, but K4 is a place outside.

**Comment by lordyavin** [comment]
gyms may be outside as well.
