### ISSUE TITLE
French translation wrong (boulder)

### ISSUE THREAD

**Issue by gui84** [theCrag/website#4216]
French translation is wrong :

Boulder/Send

should be
"J'ai réussi ce bloc, sans chute, après un ou plusieurs essais"

instead of 
"J'ai réussi ce bloc, sans chute ni repos dans le baudrier, après plusieurs essais"

![Screenshot_20230710-154548](https://github.com/theCrag/website/assets/34114303/5fa4ff1a-7b42-4009-bdb9-3a2f8378431c)

**Comment by rouletout** [comment]
Thanks, fixed, will be available on next release

**Comment by gui84** [comment]
Others French translations problems (Boulder) :
 
- Onsight : "j'ai grimpé ce bloc lors de mon premier essai ... "
should be "j'ai réussi ce problème lors de mon premier essai ..."

- Flash : "j'ai grimpé ce bloc lors ... "
should be "j'ai réussi ce problème lors ..."

- Send : "j'ai réussi ce bloc ..."
should be "j'ai réussi ce problème ..."

- Repeat : "j'ai grimpé cette voie auparavant"
should be "j'ai réussi ce problème auparavant"

- Project : "je travaille cette voie ou ce problème en tant que projet"
should be : "je travaille ce problème en tant que projet"

- Attempt : "j'ai essayé, mais je n'ai pas réussi cette voie"
should be "j'ai essayé, mais je n'ai pas réussi ce problème"

**Comment by rouletout** [comment]
All fixed with the exception of Project and Attempt as they are used also for routes. Available on next translation push.
