### ISSUE TITLE
Lead ascends filter bug.

### ISSUE THREAD

**Issue by EIMANTASDA** [theCrag/website#4222]
I have a bug when filtering my logs to see leads.
I have logged some seconding and it shows up on my leads. I'm adding pics. I think it might be because of ability to choose the type of seconding you did
![Screenshot_20230825_183652_Chrome](https://github.com/theCrag/website/assets/143214513/830ec1ac-3880-4d67-bfd4-88c3197c110f)
![Screenshot_20230825_183843_Chrome](https://github.com/theCrag/website/assets/143214513/a9275f4e-e34f-47d1-a697-07265fe67283)
![Screenshot_20230825_183854_Chrome](https://github.com/theCrag/website/assets/143214513/c4e28b45-44ae-4c1b-9347-869033c38c6e)
![Screenshot_20230825_183900_Chrome](https://github.com/theCrag/website/assets/143214513/d1c061db-4ae6-4f24-84f3-417f9717f47e)

Let me know if it needs more explanation.

**Comment by quaestor** [comment]
Hi, the *lead* ascent of "RIGHT CRACK" showing up in the list is from August 20. The ascent in the first screenshot (August 25) hasn't been logged at all, I cannot see it in your list of ascents.

**Comment by scd** [comment]
Can you post a link to your logbook.

Basically the tick type dropdown is for the old ascent flow but for the new ascent flow you need to also select the gear style.

<img width="776" alt="Screen Shot 2023-09-04 at 5 41 34 pm" src="https://github.com/theCrag/website/assets/373058/b8420f16-bcbb-4c19-b1b1-5ce16d07fbc4">

So we need to finish the migration of the old tick flow ascents and update to the new tick types.

**Comment by scd** [comment]
Internal notes when fixing this. 

We want a revised tickStructure function which maps the gear styles in the new ticking interface. Maybe just create a new function. We have to get the tick ids so we still need to call the database.

**Comment by scd** [comment]
This is now done.
