### ISSUE TITLE
Order of climbs logged not reflected in ticklist

### ISSUE THREAD

**Issue by RichardFlinn** [theCrag/website#4228]
The order that ascents are logged are not appearing in the same order when I view my profile. 

I like to do this so I can see what I warmed up on and what I projected at a glance. 

I admit it’s not a massive thing, but this bug seems to have arisen since a recent update.
This is my first entry on GitHub so my apologises if this has been covered by someone else.

Cheers!

**Comment by rouletout** [comment]
This is included in https://github.com/theCrag/website/issues/1121 - closing here
