### ISSUE TITLE
Privacy issues 1

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#4234]
There are still privacy leaks which caused real trouble between users. Please fix them urgently! Thank you.

In my profile - 'climbs with' also private users are displayed who climbed with me. But they are private, nobody should see on my public profile that i am their climbing partner!

**Comment by scd** [comment]
@FF-Flo thanks for finding this issue. I have hot fixed so that you should only be able to see accounts that you are permitted to see. Please check.
