### ISSUE TITLE
Privacy Issues 2

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#4235]
There are still privacy leaks which caused real trouble between users. Please fix them urgently! Thank you.

On my public profile - section 'mentioned' there are also private discussions listed. Nobody should see any details of PRIVATE discussions at all.

Example: There is a private discussion between UserA and UserB about UserX. The title of this discussion is "First ascents UserX". UserB invited me in this private discussion. Now UserX looked at my 'mentioned' section and see:

"In the discussion 'First ascents UserX', comment by UserA, 4 weeks ago
"In the discussion 'First ascents UserX', comment by UserB, 4 weeks ago
"In the discussion 'First ascents UserX', comment by Me 3days ago

So UserX sees that there is a private discussion about his first ascents and got really angry (that happened indeed).

Nobody should see that there are PRIVATE discussions at all!

**Comment by scd** [comment]
@FF-Flo thankyou for pointing this out. It seems as though there is a general flaw in showing mentions unless the logged in account is directly involved in them either as the mentionee or the mentioner. 

I have hot fixed this change. Can you please check your account that the mentions page is not sufficiently restricted.
