### ISSUE TITLE
Privacy Issues 3

### ISSUE THREAD

**Issue by FF-Flo** [theCrag/website#4237]
There are still privacy leaks which caused real trouble between users. Please fix them urgently! Thank you.

On my public profile - section 'mentioned' there are also ticks from private users who climbed with me, public for everybody, with comment, whole name of climbing partners, even children. Nobody should see any details of ticks of PRIVATE users at all.

**Comment by scd** [comment]
I think it is best if you send us email so we can share links and screen shots.

Your public profile looks different for different people. Have you tried looking at your public profile while not logged in?

**Comment by FF-Flo** [comment]
Hey Simon,attached you find 3 screenshots from my ***@***.***) public profile. I did them while logged in with test account ***@***.***) and with no user logged in - no difference.On screenshot 1 you see github 'privacy issue 1': that i climbed with the users Frieder and TT, but they are private, nobody should see that they climbed with me.On screenshot 2 you see github 'privacy issue 2': on my 'mentions' page the private discussion "Erstbegehungen Eisbär" is listed with comments from users Christoph Rauch and Alma. Nobody should see any mention of this private discussion, especially not user Eisbär who really got upset when he found out that we discussed his first ascents in a private discussion.On screenshot 3 you see github 'privacy issue 3': on my 'mentions' page ascents of users Frieder and TT with me are listed with comments and other climbing partners. User Frieder and TT are private, nobody should see their ascents at all.Thank you for asking. I have huge respect for your work and the whole project and the open data philosophy. Thats why i contribute so much time and effort, over 2 mio. Karma in the last 3 years...All the best to you down under! Cheers, FloPS: A minor question: I deleted all ascents (i climb more free nowadays ;-) and only mainly coontribute. But on my profile are still 2 ascents, also on profile map, but when you click it, there is nothing?
-------- Ursprüngliche Nachricht --------Von: Simon Dale ***@***.***> Datum: 04.12.23  21:18  (GMT+01:00) An: theCrag/website ***@***.***> Cc: FF-Flo ***@***.***>, Author ***@***.***> Betreff: Re: [theCrag/website] Privacy Issues 3 (Issue #4237) 
I think it is best if you send us email so we can share links and screen shots.
Your public profile looks different for different people. Have you tried looking at your public profile while not logged in?

**Comment by scd** [comment]
@FF-Flo did you mean to respond to the git hub issue. Github automatically adds email responses to an issue to the issue discussion. Just in case you were wanting this to go to us personally I have deleted your comment from GitHub issue discussion. The attachments were not included.

Please send email to support@thecrag.com

**Comment by scd** [comment]
@FF-Flo please check that this issue has also been fixed.
