### ISSUE TITLE
Pink Point stuck in Sport CPR

### ISSUE THREAD

**Issue by troymcandrew** [theCrag/website#4239]
Logged a route that is a Mixed Trad line but is still stuck in Sport CPR even though it doesn't show in grade piromid.

![Screenshot_20231205_134333_Chrome](https://github.com/theCrag/website/assets/152945175/87277f6a-7eb4-4d5a-a0b6-be1d2aee9c4f)
![Screenshot_20231205_134255_Chrome](https://github.com/theCrag/website/assets/152945175/1707da64-5aa4-4aed-a981-f0330ee316eb)
![Screenshot_20231205_134306_Chrome](https://github.com/theCrag/website/assets/152945175/1b5e666d-951c-4e50-8995-581866e8d1f6)

**Comment by scd** [comment]
From a CPR point of view Pink Point is a sport route.

**Comment by fritz-raphael** [comment]
The same issue was described in #4125

**Comment by rouletout** [comment]
From CPR point of view it is sport, from a route perspective it is a trad route (pyramid), closing

**Comment by musoke** [comment]
> From CPR point of view it is sport, from a route perspective it is a trad route (pyramid), closing

I understand why it gets sport CPR.  Why doesn't the same argument apply to the pyramid?
