### ISSUE TITLE
Personal crag profile unable to be viewed

### ISSUE THREAD

**Issue by jsonlu1** [theCrag/website#4245]
Hi, 

I created an account on theCrag with the profile name 'json', following the email address I used. When I try to view my profile or anything related (lists, logbook, activity), the page returns the info in JSON format.
![Screenshot_2024-01-03-15-02-52-348_com android chrome](https://github.com/theCrag/website/assets/155508262/0c693164-1677-4d5c-8675-d1910f6b5bf2)

Other users on theCrag get the same result when they try to view anything related to my profile. 

Could this please be looked into?

Thanks,
Jason

**Comment by scd** [comment]
Please change your profile name as json is not a valid profile name. We should have barred it, but alas we did not.
