### ISSUE TITLE
new ticking interface is loosing ascent data if navigation between ascents is used

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#4251]
I've logged three ascents using the new UI. Though, only two ascents are showing. The tick type and ascent comment of the second ascent are actually from the third ascent (route 'Pepestroika'), which is missing. The tick type and ascent comment of my second ascent are missing.

I believe the steps to reproduce are this:

1. Log first ascent
2. Log second ascent
3. Arrow back to second ascent
4. Arrow forward to third ascent
5. Log ascent

more details:

https://www.thecrag.com/discussion/8696800995/release-110---list-enhancements#m8767056108

**Comment by scd** [comment]
I have hot fixed this. Please test.

**Comment by killakalle** [comment]
@scd @nicHoch 
Following the (assumed) steps to reproduce, the issue looks fixed now.

![image](https://github.com/theCrag/website/assets/30682796/1a0c2bac-78eb-46e3-b4c1-76d1c739f14d)

Note: the order of ascents shown in the stream event is different from the order of logged ascents as described here:
https://github.com/theCrag/website/issues/4240

**Comment by lordyavin** [comment]
I selected three routes and logged as described. All three ascents are recorded:

![image](https://github.com/theCrag/website/assets/1528540/bf13a558-709c-4b20-857c-68a7838c90cc)
