### ISSUE TITLE
Ascent icons in ascents list overlay each other on mobile 

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4253]
On mobile:
1. Open route detail view
2. Click on ascents

The icons and the grade field are on top of each other

Android, Chrome

![Screenshot_20240131_090934](https://github.com/theCrag/website/assets/30682796/360e7526-ba46-4688-96a8-dbe0fdba226b)

**Comment by killakalle** [comment]
Related?

A route detail page when you have ticked the route already
![image](https://github.com/theCrag/website/assets/30682796/ea7d8683-9172-4dba-a272-29edacaf6445)

**Comment by braeuni** [comment]
Also when viewing ascents (on desktop)

![grafik](https://github.com/theCrag/website/assets/7069305/01f86fd7-1475-4ebf-bcc0-0bc420870ee2)



On a side note, there are not ascents listed although there should be.

**Comment by nicHoch** [comment]
![image](https://github.com/theCrag/website/assets/2226714/465f1c53-e5c0-40ad-a9a0-0dc69de65b85)

![image](https://github.com/theCrag/website/assets/2226714/3135ecb7-0fd7-400a-9186-283af1feffd3)

will be fixed with next release
