### ISSUE TITLE
Deleted Climber Activity still throughout website

### ISSUE THREAD

**Issue by troymcandrew** [theCrag/website#4259]
A trace of Climbers that have deleted their profile still show up in many places. If they are someone you have climbed with a lot in the past they still show up as a blank Icon on your profile or If they commented on posts you can still see the message box. Suggested grade data is still present on routes too.

![image](https://github.com/theCrag/website/assets/152945175/3e24afed-94ed-467e-9013-613a351e0a06)

![image](https://github.com/theCrag/website/assets/152945175/a1c0ab18-35c4-46f1-9f5a-b8932bb557ad)

![image](https://github.com/theCrag/website/assets/152945175/4f7e401c-48cd-4393-b7e5-9c98c3a0b5f6)

I believe If someone deletes their account a complete wipe of their paper trail should be deleted too. Except for routes they have created of course.

**Comment by scd** [comment]
This should be ok now. Please raise another issue if you see deleted climber somewhere else.
