### ISSUE TITLE
Hardest Ascent/ distance/ hardest ascents by area broken on Profile Page.

### ISSUE THREAD

**Issue by troymcandrew** [theCrag/website#4262]
Whilst viewing my profile page recently I can see that my profile does not show hardest accent and hardest ascent by area tables. Is this because of the recently deleted old ticking types. Is there a fix in the background I don't know about? I'm not a supporter and recently clicked "Free Pass" on a pop-up recently, does this have something to do with it?

![image](https://github.com/theCrag/website/assets/152945175/f383051a-9c65-409d-8346-61be7d7d8b17)

![image](https://github.com/theCrag/website/assets/152945175/70f30fdb-e441-4ac7-971c-3bcb77760fbc)

**Comment by scd** [comment]
I think there is a bug. Hardest ascent is missing from my profile too.

**Comment by scd** [comment]
The data still seems to being generated:

<img width="364" alt="Screen Shot 2024-03-04 at 11 03 20 am" src="https://github.com/theCrag/website/assets/373058/a9deae91-87f7-43ab-b93a-e87e449aad16">

**Comment by scd** [comment]
Ahh, I found that I accidentally introduced a new regression bug when fixing another bug over the weekend. I have hot fixed and am rebuilding all the account stats now. This will take some hours.

**Comment by troymcandrew** [comment]
Thanks for all your help Simon
