### ISSUE TITLE
Emojis not displayed anymore

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4264]
Since a couple of days emojis are not displayed anymore.

![image](https://github.com/theCrag/website/assets/30682796/7deb13c8-4d33-4c89-959f-da3577c9bffe)

https://www.thecrag.com/es/escalar/spain/valencia/area/3827531739

I tried with different browsers and incognito mode. They were not shown anywhere for me.

**Comment by lordyavin** [comment]
same [here](https://www.thecrag.com/discussion/9407813862/die-strae-am-fels-ist-aktuell-fr-den-durchgangsverkehr-gesperrt-hinfahren-darf-man-aber-am-heut#m9430189518): 
![grafik](https://github.com/theCrag/website/assets/1528540/8f4539e9-c2e7-4108-a9d1-24d29c2fd217)

**Comment by nicHoch** [comment]
![grafik](https://github.com/theCrag/website/assets/2226714/d9260009-695b-4915-9d87-dab6f250ea9a)

fixed will come back with next release
