### ISSUE TITLE
Deleted Climber still showing up in photos 

### ISSUE THREAD

**Issue by troymcandrew** [theCrag/website#4269]
This may not be something that can be removed but deleted climber is still showing up on photo tags. A few weeks ago it was requested that when someone deletes their profile, their paper trail on thecrag be removed to I believe this is still part of that paper trail

![image](https://github.com/theCrag/website/assets/152945175/52da13ec-d398-498c-ad46-1ef3da0cd945)

**Comment by scd** [comment]
@troymcandrew this should now be fixed.

Please let me know if it is still a problem.
