### ISSUE TITLE
Inconsistency in private crags (related to #3295)

### ISSUE THREAD

**Issue by Drazhar** [theCrag/website#4270]
For quite a long time, there is the nice feature to have private crags and crags where the location/access description is hidden. An example would be Magletsch:

https://www.thecrag.com/en/climbing/switzerland/alpen/sarganserland/area/1398617799

There the location and access description is correctly hidden:
![Screenshot from 2024-05-14 11-17-30](https://github.com/theCrag/website/assets/3040689/7d4ce9d2-0ede-4c02-a993-aa70851bb074)

But if the access description is changed, it will show up in the stream:
![Screenshot from 2024-05-14 11-17-10](https://github.com/theCrag/website/assets/3040689/39d20a92-5090-4533-af5a-5da18348434e)

It would be better if it's hidden everywhere ;)

ps.: Magletsch is now published in the new guidebook for the region, so it doesn't have to be private/hidden anymore.

**Comment by nicHoch** [comment]
the update showed up in the stream because it was not hidden:

![grafik](https://github.com/theCrag/website/assets/2226714/72c0240a-1006-4a6f-b9ce-b87d9a517e44)

**Comment by nicHoch** [comment]
i removed all restrictions now
