### ISSUE TITLE
"{FB}" showing in grade label

### ISSUE THREAD

**Issue by mchampanis** [theCrag/website#4279]
I'm not sure if this is working as intended. I am intermittently getting an `{FB}` prefix before some grade labels.

## Activity feed ##

<img width="708" alt="image" src="https://github.com/theCrag/website/assets/45290/b3dc0457-b415-4341-b41a-2949786318c1">

`7C` here but not the `6C` or `6B`.

## An area I uploaded ##
<img width="755" alt="image" src="https://github.com/theCrag/website/assets/45290/5990360e-945e-43d2-be90-6fb0a4a41935">

## My grade display settings ##

<img width="260" alt="image" src="https://github.com/theCrag/website/assets/45290/89761734-644a-438d-95b8-31badf6f9171">

**Comment by scd** [comment]
If you see the curly brackets it means that the grading system assigned to the route is not consistent with the grading context of the area. Nothing to do with your personal settings.

Grade text can mean something different for different grading systems.

**Comment by killakalle** [comment]
@mchampanis 
This usually happens when the crag has grade context "FB: French" and the route has grade context "FB: Fontainebleau".

To fix this for everyone, change the affected route's grade context to "FB: French"

![image](https://github.com/user-attachments/assets/ba6a2762-0176-4ae2-918d-af9f09ce5e0b)

**Comment by mchampanis** [comment]
Thanks both.

I tried changing between FR and FB and it just inverted the problem (started showing `{FR}` instead). I ultimately fixed it by leaving the area's grade context as is (in this case `SA`) and setting the boulder problem grade context to `SA` too, but then forcing the FB context on routes by prefixing with `FB:`.

In South Africa we have our own sport/trad grade system, but usually use Font grading for boulders. Our boulder areas would need to be changed to FB which I believe only an admin can do.

Some other links on similar topics, for people who might find this on Google:
 - https://www.thecrag.com/discussion/3744157161/change-grade-context-of-an-areacrag
 - https://www.thecrag.com/discussion/4777189335/uiaa-default-bouldering-grade-context
 - https://www.thecrag.com/en/article/grades
