### ISSUE TITLE
Add a topo to the tooltip in map view

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#428]

**Comment by Mdemaillard** [comment]
What is the point here ? Increased attractiveness of the crag when clicking on them on the map view ?
You could get ugly topos or topo showing only a single route.
If that is the purpose, i'd rather add the webcover.

**Comment by scd** [comment]
I think we should close it. Web cover is good idea

**Comment by lordyavin** [comment]
+1 for closing
