### ISSUE TITLE
Add more options to historical dates

### ISSUE THREAD

**Issue by Beakerboy** [theCrag/website#4294]
Old climbing routes don’t have as well documented provenance as modern routes. Guidebooks would list first ascents with “circa 1994” or “Spring 1982”. It would be nice to have these options.

**Comment by scd** [comment]
You can add partial dates, eg 1994 or Sep 1994

There is no support in our native database for something like Spring 1982, and besides Spring 1982 means different things in different parts of the world.

You can always add the "circa 1994" in the comments.

I am closing as not doing.
