### ISSUE TITLE
Bug when trying to edit an old ascent

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#4298]
eg in this event

https://www.thecrag.com/event/2714916942

editing an old ascent I don't get the normal popup modal, instead I go to a new page with this error:

Software error:
processStateReviewAscentBranchIfOperatorAccount at /opt/CIDS/perllib/CIDS/Process/SupplyInformation/ReviewAscent.pm line 234.
For help, please send mail to the webmaster (email), giving this error message and the time and date of the error.

**Comment by scd** [comment]
I am pretty sure that this has already been fixed in dev. Check again after next release

**Comment by brendanheywood** [comment]
Yup fixed thanks!
