### ISSUE TITLE
PDF Crag Guide chinese / korean / japanese characters don't work

### ISSUE THREAD

**Issue by scd** [theCrag/website#430]
Failing in 

* [ ] Korean https://www.thecrag.com/climbing/south-korea/area/928765131
* [ ] China https://www.thecrag.com/climbing/china-mainland/beijing/area/155656800

**Comment by brendanheywood** [comment]
I think we can close this, but we should do a quick check with the new korean lang packs

**Comment by scd** [comment]
Keep this open. Actually I have not looked at PDF templates for translations.

I am pretty sure we have done nothing about missing PDF character sets, so I imagine this is still a problem

**Comment by brendanheywood** [comment]
This appears to be coming through the first stage and the glyphs are missing from the font when producing the final pdf. More digging

**Comment by scd** [comment]
My understanding is that we need to include fonts in the pdf. I am not sure about that process though.

**Comment by brendanheywood** [comment]
I'm knee deep in that trying to install some custom fonts

**Comment by brendanheywood** [comment]
Alrighty I now have a custom font loaded, it's still missing the glyphs but some progress

**Comment by scd** [comment]
There are two work flow issues here which potentially make this a difficult issue. One is the mechanics of installing custom fonts in PDFs in perlland. I never worked this out. The other is working out which fonts to install. We should really only be installing fonts we need.

**Comment by scd** [comment]
cool I just saw your post after I pressed save. Too quick :)

**Comment by brendanheywood** [comment]
Ok this is now working with Chinese Japanese and Korean glyphs in a prototype way.

Lato does not support everything we needs, my prototype was done using Noto Sans https://www.google.com/get/noto/

For reference, with the fonts embeded in my test pdf:

* No fonts at all is 318K
* Only Noto CJK 327K
* Noto CJK + Bold 336K

Given that the original fonts are several meg each it's clearly doing the correct thing and only embedded the glyphs it used regardless of what fonts are registered.

Some temporary test files:

https://brendan.thecrag.com/pdf/korea.pdf

https://brendan.thecrag.com/pdf/ebor.pdf

**Comment by brendanheywood** [comment]
should be fully sorted but need post release checks
