### ISSUE TITLE
Getting "blocked" on theCrag

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#4302]
Hi guys! I'm using a Python script to update the routes of my local gym. Now I have the problem that my script doesn't work anymore, because the update process throws a "You have been blocked on theCrag" webpage. I don't really get blocked as a person, using theCrag in the normal way in a new browser session is no problem, but I cannot update my gym anymore.

What I'm doing is to use  Selenium to do all the updates automatically via a remote controlled browser session. Among other things I use the "processmaps" for easy access to some of the functionality. It's hard to say for me what triggers the blocking, maybe the remote controlled browser, maybe the usage of processmap?

**Comment by nicHoch** [comment]
this is due to our integration with CloudFlare. We can define exceptions so that defined applications get not blocked.

 so if anybody needs an exception: get in contact with: support@thecrag.com
