### ISSUE TITLE
Adding country borders by default

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#437]
Not important, but probably worth considering:
Many political borders have already been mapped in thecrag, but it is a labourous process, especially at the larger scale. Especially ineffective, when a borderline between two adjacent countries has to be traced twice. Couldn't the borders be imported from some free available source? Here are some suggestions, though I don't know which one would be best suited to the internal needs of thecrag:
http://downloads.cloudmade.com/ - Openstreetmap data, which also allows including further administative levels like federal states, etc.
http://www.naturalearthdata.com/ - already simplified vector data, more suitable for viewing at coarser scales
http://thematicmapping.org/downloads/world_borders.php

cheers, Melwin

**Comment by Mdemaillard** [comment]
merging in #2187
