### ISSUE TITLE
sponsor welcome emails

### ISSUE THREAD

**Issue by cgome** [theCrag/website#438]
links to list view in sponsor welcome menu should ensure that sonsor's banner is displayed.

I think it should be fairly simple to add an argument to the url page
area/1234?sponsor=4567
However the other issue is that they might not have been allocated yet. If we have a sponsor argument it could force the sponsor to be returned.
If you think this is a good idea then add it to the issues list.

**Comment by rouletout** [comment]
Sposnors are managed in CRM, no need, closing
