### ISSUE TITLE
Discourage multiple FFAs on same route, be able to change FA to FFA / Set or back

### ISSUE THREAD

**Issue by scd** [theCrag/website#443]
Tasks:

* [x] review api changes - Audit says none
* [x] review backend support method for creating update atom - Audit says no changes
* [x] review bulk edit backend support for merging ui fields with data - Audit says that ui fields should be renamed and include data type, for example _FADate becomes _HistoryDate
* [x] Change the history type to be selectable
* [x] Bulk edit UI javascript to add a new history item
* [x] UI opens with spare history type
* [x] be able to delete history with an X icon

Opposite side of the same coin: https://github.com/theCrag/website/issues/3275

Lee's Facebook comment ...

> We're back to that same issue I logged on Nov 23. Two sets of FFA fields? Why? There can be only one first free ascent of a route.

My comment ...

I don't think we are back from this issue - we have never left it. Back in Nov 23 there were a whole lot of technical issues logged all at once, which I think we got to the bottom of. 
Are you commenting on the logic of allowing two first free ascents. In which case I would answer I cannot think of any valid reason why we allow multiple first free ascents. However there are reasons why we need to allow multiple first ascents, otherwise we would not be able to merge with external databases such as ACA. For example:
http://www.thecrag.com/route/13015939
It's the same code which deals with FA and FFA. At this stage I'm not so keen to spend time doing special coding, which in fact limits functionality on the site. Before I do special FFA coding I want to be absolutely sure that there is no valid reason for having multiple FFAs, otherwise we may find ourselves not being able to merge data from an external site.

**Expected**
* [x] Instead of 3 fields for FA, FFA, Set just have a single field for a new empty route like this. The 'type' of history is a drop down allowing it to be set to FA or FFA:
* [x] When editing you see the same dropdown so you can change an existing route instead of having to delete a record and recreate it
* [x] You can have a (-) or (+) button (like the pitch add / removal) to add or remove history records
* [x] when loaded and displayed, all records are ordered by date

![image](https://user-images.githubusercontent.com/187449/45987532-68859a80-c0b5-11e8-8de8-e293b8b700ba.png)

**Comment by brendanheywood** [comment]
See also https://www.thecrag.com/discussion/1383572694/dreaming-frog--set-by

**Comment by brendanheywood** [comment]
I'm just extending the scope of this slightly so that when we are editing the FA / FFA / Set, we can also easily change an FA to FFA or back. At the moment you have to copy all the data over which can be quite tedious. For batch edits it's really onerous.

**Comment by brendanheywood** [comment]
+1 related issue to editing route history is that it's really tedious to remove an entry, you have to manually empty 4 different fields to remove a history item. It should just be an X for that line
