### ISSUE TITLE
Extending functionality of "trip" concept

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#447]
I know, I know: The help says "We plan to implement some additional trip features in the near future.", which means that you probably have already thought all this out. But I cannot help it but spew some more stuff onto the wishlist ;-)
- [ ] the trip duration could be used to set default dates in the "log ascent" form (likewise, for non-trip related ticks, the last date could be used)
- [ ] when logging an ascent on a trip, these ticks could be prepared for the other trip members, so they just confirm them if they have participated in that climb (even better: let me assign who lead/ followed me up that climb that I log. This may also make sense to non-trip related)

**Comment by rouletout** [comment]
While not addressing all points above, the wish list feature is as close as we will get to trips... closing
