### ISSUE TITLE
Located routes are draggable too easily on map locate page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#471]
Kinda a hangover from the first implementation. If a route is already lcoated then it can be dragged around on the map without first entering an edit mode making it too easy to move a route when you meant to pan the map and lose data.

This needs to be fixed along with re-implementing the map based location of routes themselves.

**Comment by Mdemaillard** [comment]
on desktop currently fine, dragging only pans the map view. 

On the other end, routes ARE draggable by mistake while editing the location of their parent node.

**Comment by rouletout** [comment]
Not possible anymore - being able to drag them in edit mode is actually good for fine tuning, closing
