### ISSUE TITLE
crowd source image / photo quality assessment

### ISSUE THREAD

**Issue by cgome** [theCrag/website#474]
Ultimately what we'll want is a user rating system for photos (1-5 star for quality, with the option to flag offensive or inappropriate material).

List View, PDF Guides etc will only choose from highly rated photos (so blurry photos, bum shots, people at the base of the crag, won't make it onto the cover of the guide).

Administrators will review images flagged as offensive or inappropriate and either mark them as 'private' (so only the person uploading it can see it) or delete them. In either case the submittor would be informed.

**Comment by Mdemaillard** [comment]
more and better covered by already mentioned dups. closing here.
