### ISSUE TITLE
Migrate away from google qrcode / chart api deprecated April 20, 2015

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#513]
https://developers.google.com/chart/image/

Also the charts fail on 3G on Telstra. 
- [x] Seasonality - redo as css
- [ ] QR codes
- [x] route qualty chart
- [x] lead style chart

Charts may be disappearing on April 20, 2015

**Comment by brendanheywood** [comment]
So April came and went, Google is still leaving it up indefinitely but reserves to right to can at any time.

**Comment by brendanheywood** [comment]
This is almost done. The only thing left is the qr codes which we can easily migrate to the pictograph server

https://github.com/catalyst/moodle-local_qrlinks/issues/14#issue-359698621

**Comment by rouletout** [comment]
Closing as the remaining item seems to be an non-issue
