### ISSUE TITLE
Signup checklist

### ISSUE THREAD

**Issue by scd** [theCrag/website#518]
From issue #492

perhaps a better thing is a sort of dynamic extension of the tour - like when you join dorp box there is a box which tells you what you need to do with a check list:

```
follow some people
add some favouties
tick some routes
link to dropbox/facebook etc
```

Campbell suggested:

Maybe a little checklist like you propose could be added as a note at the top of a new account's dashboard for their first few visits, like the one you've just added for existing memenrs when they are first taken to their dashboard?

**Comment by rouletout** [comment]
Many of these are covered in the welcome email, more will be covered using campaigns and user engagement, closing
