### ISSUE TITLE
In guide view if a branch of nodes is smaller than 100 then renumber

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#522]
ie instead of 1.1, 1.2 ... 4.1, 4.2, just number in one long sequence. Will make the topos and everything much simpler. Tripple digits is where the topos labels look crap

**Comment by Mdemaillard** [comment]
I would say rather drop the initial 1. for the top level. 
I tried playing a bit but a guide is always from whichever node down (i couldn't select 2 top nodes to view in 1 guide), meaning that first digit is 1 for every item in the guide, and so useless clutter.
