### ISSUE TITLE
When creating a new area the area type should be order by rough size

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#53]
They are:

 Sector   Cliff   Crag   Region   Area   Feature   Boulder

they should be:??

 Region   Area    Crag  Cliff    Sector   Feature   Boulder

It should also filter them on what is actually valid at this node, eg you can't add a crag to a cliff etc.

**Comment by Mdemaillard** [comment]
Correct order is implemented, with Artificial Area & Gym at the far right.
Filtering not implemented. (and not necessary in my opinion)

**Comment by lordyavin** [comment]
Marc the grave digger :wink: or should we say house keeper? +1 for closing this.

**Comment by Mdemaillard** [comment]
It is actually interesting to see the complexity raised in all these points... and if i can provide a tiny bit of support this way, i'm for it ;-) Any time saved allows more programming to be done so quicker releases :p

**Comment by scd** [comment]
Thankyou. Grooming and clearing backlog issues is very helpful. Our dev capacity is signficantly reduced at the moment, which I am trying to rectify. I keep an eye on catestrophic bugs and simple regressions after a release, but generally don't have time to get through the backlog. Our plan is to get some other devs helping in specific areas, but this takes time.

Well groomed issues means we can get through the issues quicker when we get around to it. Also linking the issues means we may be able to resolve multiple related issues with a single dev effort.

We have got a general release plan which we are months behind, but Nicky pulls in related backlog issues when they are related to our release plan.
