### ISSUE TITLE
Nodes facet search result page has duplicating records ids

### ISSUE THREAD

**Issue by scd** [theCrag/website#540]
https://www.thecrag.com/nodes/at/11811439/fuzzy-search/Dysentery?S=Dysentery&ST=a

Has '19 R ★ Dysentery DF' twice

**Comment by brendanheywood** [comment]
Merging duplicate from @dnnr

https://github.com/theCrag/website/issues/2780

**What happened?**

When searching for a route, the same node shows up twice in the results:

Example:
https://www.thecrag.com/nodes/fuzzy-search/stecklessriss?S=stecklesriss
![image](https://cloud.githubusercontent.com/assets/2630359/26765240/f75cb27c-4977-11e7-9ad3-67a23583b491.png)

Both results have the exact same link, so it's not a duplicate in the tree:
https://www.thecrag.com/climbing/germany/frankenjura/right-tower/route/19712419

Note that I mistyped the route name in my search query, but that doesn't seem to matter.
When typed correctly, other matches appear in the result (not duplicated), but the Steckelsriss still appears twice at the top.

**What you expected:**
I expected any matching node to only appear once in the results.

**Comment by dnnr** [comment]
For what it's worth: I just tried and wasn't able to reproduce my original issue.

**Comment by Mdemaillard** [comment]
Does not occur with the current "search" function.
Does still occur with the "fuzzy-search", which i am not sure how to start from the UI (without hacking the url)

Proposal to close

**Comment by dnnr** [comment]
Agreed. It's bummer though that we do not seem to have a fuzzy search anymore. Was that removed on purpose?

**Comment by rouletout** [comment]
Closing as per comments above
