### ISSUE TITLE
Corrupted layout in Opera

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#556]
For some (and only some) nodes (eg Italy https://www.thecrag.com/area/11747371) the "Crag Karma/CragGuru" block appears below everything else, not at the right side when viewed with Opera 11.61. Works OK in IE.
I know, I am using exotic browsers.Still wanted to let you know.

**Comment by brendanheywood** [comment]
Given that opera has swapped rendering engines to blink since I'm gonna kill this one
