### ISSUE TITLE
chat fail on iPhone

### ISSUE THREAD

**Issue by cgome** [theCrag/website#568]
I think this is an iPhone bug. Can't visit an account page and leave a message.

i. Data entry is tricky (can't really see the text you're entering) because of the floating header

ii. Error msg as per Ben's screenshot when you click start discussion

Seems to work OK from a crag page (i still occurs but at least ii doesn't).

Cheers
Campbell

**Comment by brendanheywood** [comment]
Just tested and works, not sure when fixed, closing
