### ISSUE TITLE
IE6/7 and maybe 8 feature detection

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#583]
use code from here:

https://github.com/h5bp/html5-boilerplate/blob/master/index.html

and make some decisions about what browsers we offically support and throw up a message if they don't make the grade.

**Comment by Mdemaillard** [comment]
anything starting with IE should be served the message.
on a serious note, if implemented that will be something to regularly update (long term view here). Worth the bother ?

**Comment by scd** [comment]
I think this will be worth while doing eventually, but I cannot see myself finding time to ever do this work. The trigger will be when we can properly afford a dev team.

**Comment by rouletout** [comment]
Things from the past.... closing
