### ISSUE TITLE
Get photo date data from EXIF or file date

### ISSUE THREAD

**Issue by MelwinQ** [theCrag/website#606]
...to save uploaders from entering it in the form (btw. the date form is still one that should be reversed).

**Comment by brendanheywood** [comment]
Just had another person (Henning) request this.

Re:

> I am getting EXIF date from the photo, but stopped at automatically populating the photo date in the form. The image is processed after the form pops up.

This ajax processing is relatively heavy and is really for the resizing which is why it's done asynchronously. The EXIF extraction however could be done first synchronously before you even get to that step in the process as it's super fast regardless of how big the image is as it only parses the file header.

As a horrible worst case shelling out and calling 'exif' only takes a couple milliseconds:

```
brendan@silverbirch:~/Downloads$ time exif Eruption_1954_Kilauea_Volcano.jpg 
EXIF tags in 'Eruption_1954_Kilauea_Volcano.jpg' ('Motorola' byte order):
--------------------+----------------------------------------------------------
Tag                 |Value
--------------------+----------------------------------------------------------
Orientation         |Top-left
X-Resolution        |2700
Y-Resolution        |2700
Resolution Unit     |Inch
Software            |Adobe Photoshop 7.0
Date and Time       |2003:06:11 15:47:52
Compression         |JPEG compression
X-Resolution        |72
Y-Resolution        |72
Resolution Unit     |Inch
Colour Space        |sRGB
Pixel X Dimension   |1400
Pixel Y Dimension   |920
Exif Version        |Exif Version 2.1
FlashPixVersion     |FlashPix Version 1.0
--------------------+----------------------------------------------------------
EXIF data contains a thumbnail (4073 bytes).

real	0m0.005s
user	0m0.000s
sys	0m0.000s
```

**Comment by brendanheywood** [comment]
+1 from @lordyavin  via https://github.com/theCrag/website/issues/2885

**Comment by lordyavin** [comment]
Sorry for creating the duplicate ticket. Searched for this one but obviously chose the wrong keywords. Please increase the priority of this. Looks like it isn't on the schedule at all.

**Comment by scd** [comment]
This is fixed in simon's dev

**Comment by lordyavin** [comment]
yet no milestone?

**Comment by scd** [comment]
It is done on my dev server. Next release

**Comment by brendanheywood** [comment]
@lordyavin if any issue is done it will be in the next release, we bundle them up at release time
