### ISSUE TITLE
consider making multiple publishers descriptions simultaneously available

### ISSUE THREAD

**Issue by scd** [theCrag/website#617]
Neil re-entered a lot of routes because he did not know about the multiple publisher fields.

From Neil: 

In the 'bulk edit' view it must be clear that there is two descriptions available - and that these two choices be visible. I predict that most people will edit using this bulk edit feature as its way more productive - so hiding one is counterproductive. I spent two days not even knowing they were there and reentering data! You would then set (individually for each route) whether it displays version A or version B. Having a bulk edit mode which makes ALL route descriptions below a certain level either A or B sounds dangerous to me. It overides a lot of work instantly

**Comment by rouletout** [comment]
See also https://github.com/theCrag/website/issues/339 - multiple descriptions are available in bulk edit, closing
