### ISSUE TITLE
Consistently use bulk edit process for add / edit single route functionality everywhere

### ISSUE THREAD

**Issue by scd** [theCrag/website#635]
We will remove a whole lot of duplicated code maintenance issues if editing a single route used the bulk edit process.

If we are going to go down this path, we should put a warning message on the old process in case it is still linked from somewhere.

Also it needs to be done for single area updates which has already been mostly replaced, except for regions.

To make this happen I think the following things must be looked into:
- [ ] warning message on single route edit process
- [ ] warning message on single route edit process
- [x] action button update in area page
- [x] action button update in route page
- [x] index view 'edit route' re-linking
- [x] inline editing of routes and areas to link to bulk edit process
- [ ] bulk edit should be able to edit regions - maybe just the region node, but no children
- [ ] relink region area update to bulk edit for regions
- [ ] bulk edit should be able to update areas and routes that do not belong to any top level crags
- [ ] make sure the merge process links back into the bulk edit rather then single edit process.

Add new routes process:
* [ ] can we make this exactly the same? If not then at least match the layout
* [ ] test with adding new routes in gyms with color picker

**Comment by brendanheywood** [comment]
Make sure #1891 is fixed with this one

**Comment by brendanheywood** [comment]
I've just fixed all links to the single route edit page. I think the editing side is largely solved.

The creation side is not and is the same regardless of number of routes with a bad gym swatch layout

https://brendan.thecrag.com/processmap/createclimbnode/1116443808?routes=1

https://brendan.thecrag.com/processmap/createclimbnode/1116443808?routes=10

**Comment by brendanheywood** [comment]
+1 the new route process, both single routes and multiple routes, is missing the field for dairy entries for a FA

**Comment by nicHoch** [comment]
+1 in general there should not be 4 types of form for the same data. 

1) creat route/area 
2) edit route/area
3) bulk edit route/area 
4) admin for route/area

all first 3 forms should be the very same.
the 4 form should be a joining of the general form (1-3) and some additional form entries below.

**Comment by rouletout** [comment]
This is done since quite a while, closing
