### ISSUE TITLE
New attributes

### ISSUE THREAD

**Issue by scd** [theCrag/website#644]
Open issue for new attribute suggestions (attributes not completed from #564 )
- altitude

**Comment by Baschdl** [comment]
Integrating a digital elevation model could add the altitude for this issue and it could be used in #3800

**Comment by Baschdl** [comment]
Just done a quick experiment using [ALOS World 3D - 30m](https://www.eorc.jaxa.jp/ALOS/en/dataset/aw3d30/aw3d30_e.htm) which has a very permissible [license](https://earth.jaxa.jp/policy/en.html).

AW3D30 has an altitude of 698m for the exemplary crag from #3800 where ESRI has ~690m, MapTiler ~710m, ThunderForest ~680m and a commercial guidebook has 570m. AW3D30 with an RMSE (Root Mean Square Error) of 4.40m should be fine for all of our purposes (See http://www.int-arch-photogramm-remote-sens-spatial-inf-sci.net/XLI-B4/157/2016/isprs-archives-XLI-B4-157-2016.pdf).
