### ISSUE TITLE
review logging ascent for route with trad and boulder grade

### ISSUE THREAD

**Issue by scd** [theCrag/website#710]
http://www.thecrag.com/route/187420155

**Comment by brendanheywood** [comment]
I've moved this into the ticking release just to force a decision to either ignore this edge case, or take it into account when we filter tick types somehow

**Comment by Mdemaillard** [comment]
this area is now all boulder grades.
The milestone has been deleted.
Proposal to close issue, either an ascent is boulder or sport, not both ?

**Comment by rouletout** [comment]
Agree, it can't be both but it can have different ascent styles (e.g. free soloing a route is essentially a "boulder").
