### ISSUE TITLE
Edit forms fields visibility &/or access based on permissions ?

### ISSUE THREAD

**Issue by cgome** [theCrag/website#725]
Should all Edit forms show all available fields but those fields you don't have permissions to change are greyed out/locked with an explanation (eg. 'Editors only. Click here to request Editor permissions)? This would avoid the confusion where someone wants to update a field (eg height) and can't see the height field because they have insufficient permissions to change it.

**Comment by Mdemaillard** [comment]
I believe this has been implemented on the premises of:
all fields visible to all
fields greyed out based on permission.

candidate for closure ?
