### ISSUE TITLE
refactor url routing

### ISSUE THREAD

**Issue by scd** [theCrag/website#734]
As this is topical I thought I would make a collector issue for when we are ready to refactor url routing.

URL routing should be amalagmated to a single process. At the moment there are three processes controlling url routing:
- apache configuration
- mod perl (Rewrite.pm custom perl module)
- cgi-bin/cids.cgi

Evaluate using 3rd party routing engine / framework like Catalyst?

Properly integrate cgi-bin/cids.cgi into mod_perl. This requires a couple of things to be done:
- Turn automatically generated state perl modules into JSON config as that is all they are doing anyway
- cids.cgi routing is done using a stateID as a parameter, turn this into a uri (eg /process/1234?param1=X...)
- make sure file upload works with mod_perl (there use to be an issue with this for our version of Debian, but this may have been resolved). Worst case scenario we may have to put Debian upgrade on the dependency list for this issue.
- assess and replace all instances of 'use CGI()' in the library code.

I have not emotionally committed to any start time for this work. It's pretty big so I want to clear the decks of other high priority issues before getting into it.

**Comment by brendanheywood** [comment]
done
