### ISSUE TITLE
preferred grading system for an account in the api

### ISSUE THREAD

**Issue by scd** [theCrag/website#741]
This is currently not configurable in the users profile although there is a database field for it. 

Before this is implemented we need to understand the use cases????

You can get the registered country for the account and from that a list of grading systems used by that country:

http://dev.thecrag.com/api/country/id/7478254

And the the specifics of a grading system:

http://dev.thecrag.com/api/config/grade/system

**Comment by lordyavin** [comment]
+1 for this feature

**Comment by lordyavin** [comment]
Additionally it would be great to get all "foreign" grade systems converted automatically.

**Comment by Mdemaillard** [comment]
I believe implemented in release 81- Universal Grade Conversion update
Candidate for closure
