### ISSUE TITLE
bulk edit ideas for route faceted search

### ISSUE THREAD

**Issue by scd** [theCrag/website#743]
Idea 1: Preselect to bulk edit form. Cool for smaller searches but when the list is long there is a lot of overhead.

Idea 2: Bulk edit just routes on the page. There are 100 routes so this would cover most of the use cases without the overhead.

Idea 3: Inline javascript edit (as per unknown gear style). I think this makes sense for certain types of missing data.

Idea 4: Bulk inline javascript edit applied to multiple routes. If you do a search for all routes with missing height information, and you know all routes in a cliff are 10m then you should just be able to set this for all the routes on the page.

**Comment by brendanheywood** [comment]
This has been implemented long ago
