### ISSUE TITLE
Multipitch: fixed vs natural anchors for belay

### ISSUE THREAD

**Issue by SyntaxPickax** [theCrag/website#745]
This is, I suppose, a feature request for phototopos.  I'd like to be able to specify whether a pitch is belayed from fixed anchors or a natural anchor.  Often this is just indicated by XX on a hand-drawn topo for 2 bolts. 

(Sometimes it's a mixed anchor, e.g., one [sketchy] bolt + pro, so this could get complicated.)

**Comment by Mdemaillard** [comment]
Implemented, except for explicitely natural anchor ?
![image](https://user-images.githubusercontent.com/60388146/76220547-5901ff00-6220-11ea-9fcd-a1a146bc2796.png)

**Comment by lordyavin** [comment]
If you need extra gear to lower off this is crucial information. So I think we should not close this issue.

**Comment by Mdemaillard** [comment]
So should we just had a general "Natural anchor", or a bit more ? Like "Tree", "chokestone", "Tat required", "Gear required" ??

**Comment by rouletout** [comment]
If we have space for it, add them - can't seem to locate the UIAA paper referecned above anymore...

**Comment by Mdemaillard** [comment]
i cannot either. their website is pretty, but the navigation is horrendous

**Comment by dtweedle** [comment]
@Mdemaillard @rouletout

https://web.archive.org/web/20120920095540/www.theuiaa.org/guidebook_standards.html

The way back machine has archived some snapshots of the UIAA site as it was when this issue was initially raised.

**Comment by scd** [comment]
@Mdemaillard this is mostly fixed in the last release. We need to finalise an icon for this. Can you organise feed back for the icon.

Once we know what the icon should like like we will either get it designed or get Duncan to do it if is simple enough.

**Comment by rouletout** [comment]
Natural anchor is available, closing
