### ISSUE TITLE
Allow private guides / crags

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#753]
Some basic thoughts:
- Crag name and really basic stats could be visible but clearly marked as private - mostly to stop people duplicating the crag? A simple button / process to ask for access
- editors or some other role can add people to the crag
- seems like a good candidate for a premium feature - ie all private crags must be sponsored. Private crags I'd guess fall into either a crag on private property where the info isn't wanting to be shared public, but a guide still has value, or a newly developing area where lots of projects are being worked.
- probably could inter-mesh with a privacy setting on certain copyright data. ie if we do a deal with a print guide, we import their data but it is only visible to certain people. But the routes could have community descriptions which are visible. I had a vague feeling the DB could handle this but I've never seen it in action??

**Comment by Mdemaillard** [comment]
closing so possible comments get aggregated on 1354
