### ISSUE TITLE
Allow "on-the-fly" photo creation

### ISSUE THREAD

**Issue by adam-g-pullen** [theCrag/website#758]
It would be nice to allow the api client to specify the image size

i.e. 
http://dev.thecrag.com/image/photo/00002/<width>/<height>/190639932.jpg
-or-
http://dev.thecrag.com/image/photo/00002/190639932.jpg?w=<width>&h=<height>

Rational:
Fetching a photo for a climber involves 3 calles
1) Fetch the climber
2) Fetch the photo details
3) Fetch the photo

The second call is needed to determine what sizes are available
It is not guaranteed that a specified size is present

The sizes are not always relevant to the elements present in the mobile client
i.e. Thumbnails and full views

**Comment by brendanheywood** [comment]
I think we can close this?
