### ISSUE TITLE
Show weather forecast for each node

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#77]
we have geo -> grab the nearest address and then give to google again:

http://www.google.com/ig/api?weather=armidale

Do it all after page load ideally

**Comment by nicHoch** [comment]
That could be a very nice low hanger i would like to volunteer for:
the following Greasemonkey script will add weather forecast at client side for each area node:

[TheCragWeather.js.txt](https://github.com/theCrag/website/files/120444/TheCragWeather.js.txt)

it should be very simple and straight forward to use and integrate the meteoblue widget:

https://www.meteoblue.com/en/weather/widget/setupday/46.829667N-8.649553E

and meteoblue provides the best weather anyway ;-)

**Comment by scd** [comment]
I just read the API for Meteoblue and it is only free for non-commercial and even that has limited number of calls. 

https://content.meteoblue.com/en/products/meteoblue-api

The Widget seems like it is free, which I guess we could just tack on somewhere. Are we happy with the widget above the streams.

It seems like the 7 day forecast is the most useful. 

What is the rules for including it server side. Clearly not at the world level, probably not at the country level and probably not at the region level. 

I recon we should embed on the following conditions:
  * Top Level Crag or below
  * Not on routes
  * Must have a direct location boundary drawn.

**Comment by lordyavin** [comment]
Just a short comment on the forecast quality of meteoblue. For the Danube Valley crags their forecast is definitively the best. Don't know how good their forecasts are for other regions but a weather widget on a crag page would be nice.

**Comment by scd** [comment]
this is done in repo. after @brendanheywood pulls from repo you can see it on dev.

**Comment by scd** [comment]
just fixed a bug

**Comment by brendanheywood** [comment]
Hmm, kinda ok but not super happy with this. It's another 34k of content and 2 seconds worth of load time. It also feels very tacked on stylistically - I'm wondering whether this should be tucked away under one of the a new 'Weather' section heading at the top? Ideally loaded on demand if on mobile and the menu item defaults closed (same issue we currently have with google maps see #915 #1176 #1379)

**Comment by scd** [comment]
Yup I think I agree, please reopen.

**Comment by scd** [comment]
I have now added to it's own url

http:/dev.thecrag.com/climbing/australia/arapiles/weather

This is linked below the custom guidebook
