### ISSUE TITLE
Unable to add new climbers to a message on reply

### ISSUE THREAD

**Issue by adam-g-pullen** [theCrag/website#782]
When replying to a message and adding new climbers to the message i send through the toAccounts: []
however the new climbers are not being added to the message on the web site.

Endpoint: message/send

{"data":
  {
    "content":"here is the json",
    "toAccounts":[9517495,210228100,7727431,9068185,117975117],
    "fromAccount":9517495,
    "responseTo":210229660
  }
}

**Comment by brendanheywood** [comment]
Closing this, if there are outstanding issues Nicky will find them at some point
