### ISSUE TITLE
Email templates makeover

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#793]
- add styling, typography, footer etc
- add google analytics campagne tokens to links
- add a google analytics read beacon
- link from email footer into profile / notification settings page

**Comment by brendanheywood** [comment]
I'm gonna work through each of the templates and review / rewrite the copy starting with signup:

![image](https://cloud.githubusercontent.com/assets/187449/6314174/b3181ba6-ba27-11e4-8e53-59391de5f8a8.png)

**Comment by scd** [comment]
Cool. Also note any landing pages that need a makeover.

**Comment by brendanheywood** [comment]
![image](https://cloud.githubusercontent.com/assets/187449/6317389/e8a4c784-baa3-11e4-9070-cfe7ea32f47f.png)

**Comment by brendanheywood** [comment]
![image](https://cloud.githubusercontent.com/assets/187449/6317472/a7579c38-baa9-11e4-84ba-234d92d05b9f.png)

**Comment by scd** [comment]
add Jim's karma to the template for following somebody. Also, there remove forum posts in the first sentence as this is not a function of following somebody.

**Comment by brendanheywood** [comment]
hhmm, can you swap the email template data over to use the atomAccount for the FollowBy email?

**Comment by scd** [comment]
Simon task list:
 - [ ] swap over to atomAccount for the FollowBy email.

**Comment by scd** [comment]
I have swapped over the followedBy template data to come from atomAccount in the FollowBy email. Please confirm it works and add the persons karma to the followed by email.

**Comment by brendanheywood** [comment]
How do I test this properly? I'm using a static json file and I've made the json data in it match what I expect from atomAccount but I don't fully trust this. Also I've noticed the emails have ->{firstName} but this isn't in atomAccount or even stored anywhere, how does this work?

**Comment by scd** [comment]
I have kept the same variables that are not in atomAccount, so the template
should work the same way. I test it by unfollowing then following myself
from my test account and getting the email. I have tested the changes with
the existing template.

On Wed, Feb 25, 2015 at 6:17 PM, Brendan Heywood <notifications@github.com>
wrote:

> How do I test this properly? I'm using a static json file and I've made
> the json data in it match what I expect from atomAccount but I don't fully
> trust this. Also I've noticed the emails have ->{firstName} but this isn't
> in atomAccount or even stored anywhere, how does this work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theCrag/website/issues/793#issuecomment-75916290>.
>



-- 
http://thecrag.com/

**Comment by brendanheywood** [comment]
What about first name?

**Comment by scd** [comment]
yes firstName should still be there unless there is a bug.

On Wed, Feb 25, 2015 at 6:42 PM, Brendan Heywood <notifications@github.com>
wrote:

> What about first name?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theCrag/website/issues/793#issuecomment-75918364>.
>



-- 
http://thecrag.com/

**Comment by brendanheywood** [comment]
This one looks pretty done, and more done recently with the lang stuff. Anything stopping this from being closed?
