### ISSUE TITLE
Align / merge site text search with faceted search

### ISSUE THREAD

**Issue by scd** [theCrag/website#799]
This is a very complex area and needs a full discussion and it seems as though a number of issues are dependent on making headway here.
# Types

There are three general types of search undertaken in different contexts on the site:
- fuzzy-search: roll-your-own framework using third party library, but works outside MySQL. Generally reasonable performance with some edge cases not so good (eg search for 'arete' worldwide)
- prefix-search: fully integrated with standard faceted search, matches the beginning characters of area/route names. Useful for predictive searches / text completion. Search pretty slow for worldwide, but could be some optimization that improves things.
- search: exact matches of partial text, works inside faceted search. Fundamentally slow because MySQL has to compare every record and cannot make use of any indexes.

The most useful search is fuzzy search so you can match with close spelling. I'm pretty sure the performance of implementing this in MySQL will be pretty dismal. So until I have the courage to test this we will be stuck with the roll-your own.
# UI

UI should have a similar feel to the faceted search results?

The current UI is no right because the closest matches are not necessarily at the top.
# Nodes faceted search end-point

There is now backend code for a Nodes faceted search end point (but not yet exposed in a template). Are we ready to commit to this style for site search: eg

/nodes/id/1234/fuzzy-search/bard

Note that Nodes faceted search works across both areas and routes so is limited to attributes that are common to both areas and routes (eg node name).

If we decide on implementing fuzzy search this way then the first version will be based on our roll-your-own framework which is outside MySQL. This means that the 'fuzzy-search' facet will only work with the 'at' facet. Is this OK?
# Business decisions

Before we go forward I think we should make some business decisions so we don't go around in circles.
1. Do we want to commit to facet search style interface for site text search (eg /nodes/id/1234/fuzzy-search/bard)?
2. Should the UI output be similar to the existing faceted search output?
3. Do we want to commit to continuing fuzzy search matching?
4. Can we live with the roll-your-own limitations of fuzzy search matching until benchmarking has been done in MySQL (ie 'fuzzy-search' will only work with 'at' facet)?

**Comment by brendanheywood** [comment]
Closing as won't be done. There will be a new simple universal search page, and then links from that to the 'advanced search' aka the facets
