### ISSUE TITLE
Suggest friends to follow based on FB

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#834]
1. get proper facebook OAuth2 login working with account linking nice and smooth
2. Encourage existing users to link their thecrag account to FB
3. Suggest new friends to follow
4. Possibly an 'autofollow' setting so if you become friends on FB and you both have accounts on tC then auto follow them.

**Comment by rouletout** [comment]
Due to privacy concerns we have reduced the use of FB to strictly login. no friends info is passed along. Closing this therefore.
