### ISSUE TITLE
Bing and OpenStreetMap broken

### ISSUE THREAD

**Issue by cgome** [theCrag/website#841]
Attached are some screenshots of how aerial views are currently rendering with Bing and OpenStreetMap for Yosemite in Chrome and Safari on my MacBook. I'm on my way out the door, but if you like I'll file a bug report when I'm back.

http://www.thecrag.com/climbing/united-states/yosemite-national-park/area/20698633/locate

Cheers,

Brandon

**Comment by MelwinQ** [comment]
Issue seems to be back, although differently. Please re-open.
Found at https://www.thecrag.com/climbing/germany/oberbayern/area/449279844/locate
Encountered with Firefox 68.0.1 (64-Bit), Ubuntu.
![Bildschirmfoto von 2019-08-12 22-39-13](https://user-images.githubusercontent.com/808326/62896920-560a6300-bd52-11e9-8a58-62b0cc8fa8ff.png)

**Comment by brendanheywood** [comment]
That looks unrelated to the original issue. Either way I could not reproduce it in FF + ubuntu or any other combination, I doubt this is anything under our control.

**Comment by MelwinQ** [comment]
Probably unrelated in terms of technical reason, but exactly matching the title, therefore, I put it here.

The problem persists for me: different network (work), different OS (windows 10), same browser (FF).
It worked fine under Edge, though.

**Comment by brendanheywood** [comment]
In future please open a new issue. Are you able to provide any extra info like the browser dev tools > network tab, showing what images are failing to load and why?

**Comment by MelwinQ** [comment]
After some experienting, it turned out that the behaviour was associated to having Ghostery (a tracker blocker extension) activated. It used to work earlier, though.
Anyway, I guess this is my personal problem then. Thanks for calling back.
