### ISSUE TITLE
msg fail on iPhone

### ISSUE THREAD

**Issue by cgome** [theCrag/website#849]
Morning lads, hope your well

I have been meaning to tell you for a while but it hasn't been that much of a drama.
When I write a msg on my iPhone on someone's profile the text doesn't show.
If I write a heading the cursor drops down and the text doesn't show until I click on the story box. Text doesn't show here either until I click back on the heading. So I makes for some fun writing in the dark.
I hope this makes sense?

Cheers, Ben JengA

**Comment by brendanheywood** [comment]
Old duplicate
