### ISSUE TITLE
Define and implement business rules for getting a topo GPS point to an unlocated area.

### ISSUE THREAD

**Issue by scd** [theCrag/website#853]
Topos with GPS in the EXIF will have the GPS recorded in the topo record. 

We need to convert this to a location record if one does not exist for that area.

But what are the business rules?

For example we could just assign a square about 50x50m ?

I think this is a reasonable business rule, but we need to consider two factors:
- the topo image could have been taken a fair way away from the cliff
- if the cliff is a lot wider than the boundary suggests then this is going to provide a misleading 'locatedness' score for the area.

If we make the default square more like 200x200m then this would lesson the impact of the above two points.

**Comment by Mdemaillard** [comment]
related #163

**Comment by rouletout** [comment]
Rather encourage users to record the correct location of theCrag using Campaigns, closing.
