### ISSUE TITLE
JS error in discussion page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#885]
one more thing: On the first attempt to post this comment I got a JavaScript error, second try it worked flawlessly:

api post error: Bad Request:error:{"error":{"fromAccountError":"cannot be empty"},"data":{"fromAccount":"","responseTo":"246011580","content":"Hi Brendan,\nthanks for

On this page:

http://www.thecrag.com/discussion/246011580/topo-stuff#m246107142

This API call should not even require the fromAccount

**Comment by scd** [comment]
Closing for now as this is old and not causing recent issues.
