### ISSUE TITLE
Overhead maps on route page

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#886]
Backend work done, needs from end UI:

"I think it should work the same in the routes page. ie if on the route page in the left menu it shows the current cliff as selected, with the uncle cliffs. The area topos and map topos should behave the same. 

So yes please add it but on the route page it will be added to
 $data->{ancestors}[-2]->{children}
"

Also leftover issues from original issue:
- show current node as well - especially if there is no children, perhaps show the current node as selected similar to the subarea topos
- handle region shapes properly
- at high zoom levels if no sat data swap to street map view automatically
- zindex the selected label higher than others
- handle world node
- make child higher z index than parents
- Need to fix major 'maps' tab to deep link into map, ie prezoomed

**Comment by scd** [comment]
Closing as we have refactored maps code since this issue.
