### ISSUE TITLE
Merge issue with geolocation

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#899]
If I merge two areas, one is located, one is not, the location should carry across.

Not sure how to handle where both are located.

**Comment by nicHoch** [comment]
i assume this is still missing.
would be very helpful for the after import grooming if the geolocation gets not lost.
@scd any plans here?

**Comment by scd** [comment]
Given that we are losing data I have upped the priority to must be fixed and assigned it to the current release.

**Comment by scd** [comment]
@nicHoch this is done on my dev, but not hotfixed. This means it will not be effective until next release.
