### ISSUE TITLE
More facets for searching for crags by tlc and price type

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#922]
maybe extend of-area-type to supprt showing just TLC's

/of-area-type/tlc/

to allow the special case of 'TLC' 

And in addition filter for price level's so we could link to this directly from the marketing site:

/price/emerging/
/price/low/
/price/merdium/
/price/high/
/price/premium/

**Comment by Mdemaillard** [comment]
Price does not currently get entered with any detail
Only "Paid" structured tag is available, and in the list of tags accessible to the facet search.
![image](https://user-images.githubusercontent.com/60388146/76325455-fd06ab80-62ef-11ea-9c8b-bc5f5069e032.png)
