### ISSUE TITLE
cannot delete thecrag description if other publisher selected

### ISSUE THREAD

**Issue by scd** [theCrag/website#923]
from Cameron Roy:

Simon, I had a play around and worked out that if I delete a description attributed to thecrag and check the "Cameron Roy" radio box it doesn't actually delete the description. Only works if I have the "Thecrag.com" radio box selected. This is a little counter-intuitive.

**Comment by Mdemaillard** [comment]
I believe this is fixed, as i had the following behaviour (2019)
- when bulk editing content with 2 attributions (thecrag / publisher), you can initially select back and forth using radio button
- as soon as either attribution is modified, the radio is disabled with a message that you can only edit 1 attribution at a time.
- saving and reediting allow to select the other one again

candidate for closure
