### ISSUE TITLE
Show 'd' 'm' 'year' as the default option in the FA date chooser selects

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#938]
Too may people are putting dates into the name field. Needs to be clearer where they should go

**Comment by Mdemaillard** [comment]
![image](https://user-images.githubusercontent.com/60388146/76292404-d298fc00-62b7-11ea-890d-39f7427e7cd7.png)

Very obvious now with date field separated and full drop-down entry, and name field with prompt "climbers". Closing.
