### ISSUE TITLE
Global stats page across the board

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#942]
Just saw this and liked it:

http://codepen.io/stats

Because these are all simple counts with no node rollups or whatever I reckon this could even be a live query.

**Comment by Mdemaillard** [comment]
Is this about that or something else entirely ?
https://www.thecrag.com/climber/mdemaillard/statistics

**Comment by scd** [comment]
I think this was internal. I think we can close as not doing.

**Comment by lordyavin** [comment]
Label: "won't fix" or something else?

**Comment by Mdemaillard** [comment]
German bean counter ;-) in this case it's a closed discussion, but i hear you. I really would like to reduce the quantity of open, for usability.

What about one open issue (that we keep open) on which we can link each (closed) issues that we decided to not implement ? 
That would keep them relatively close at hand, but won't bug down the visibility when filtering.

**Comment by lordyavin** [comment]
The label "won't fix" is a standard label e.g. in Gitea. Just wondered if we should introduce a label a like. Closing is okay.

**Comment by scd** [comment]
I have added the label

**Comment by brendanheywood** [comment]
We already have a 'release' called 'Won't be done, as well as another one for duplicates. Then when it's closed its much easier to see that it wasn't part of a normal release
