### ISSUE TITLE
Dogs showin up in ticks stats

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#973]
Just noticed on my profile in prod that I've done a V7 which I don't remember doing:

http://www.thecrag.com/climber/brendanheywood

![image](https://f.cloud.github.com/assets/187449/147866/b2306d40-74da-11e2-8b24-f6aa192f0b4f.png)

If I edit that tick it is a dog:

![image](https://f.cloud.github.com/assets/187449/147869/cd1c1636-74da-11e2-81d2-800617f8f8b3.png)

This shouldn't be showing up as a 'tick'. This one is a bit funny as it's a bit semantic but it feels wrong. It is the very first thing that catches your eye at the top of the table and makes it seem like I'm really good which I aint.

Maybe the solution is something else like moving that row to the bottom and calling it 'Other ticks'. This also appears in all the other charts, in the other charts I think it should be filtered.

**Comment by scd** [comment]
I think this is fixed
