### ISSUE TITLE
Allow a crag to have a webcover photo

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#974]
Useful in places like:
- [ ] use avatar as icon for bookmarked webapps for gym's
- [ ] icons for crag download
- [ ] recently update list of crags
- [ ] app icon if we ever do standalone apps

![Arapiles theCrag - Chromium_237](https://f.cloud.github.com/assets/187449/148168/50e7c15e-74f4-11e2-902a-3b414cead229.png)

Tasks:
* [x] get thumbor to resize a good image for use as a panoramic web cover in node view
* [ ] upgrade thumbor to get access to the focal() filter see http://thumbor.readthedocs.io/en/latest/focal.html
* [x] get thumbor to reuse the same pic, with focal point, for 2:3 crag cards
* [x] make a new button for coordinators only to set a picture as a web cover, need to choose which crag or node it's for (ie could have web covers at each cliff + crag + mega crag)
* [x] add the web cover to template data, completely kill the old template data
* [x] make a new template / helpers as needed to render the web cover

See also #2240 (og image url bugs)

**Comment by brendanheywood** [comment]
Another few mockups:

![image](https://cloud.githubusercontent.com/assets/187449/20237471/43d490d0-a927-11e6-95e7-d3cb044513b3.png)

![image](https://cloud.githubusercontent.com/assets/187449/20237523/c016d92c-a928-11e6-9bea-71ec1b38da4f.png)

**Comment by scd** [comment]
+1

**Comment by brendanheywood** [comment]
Ok I now have a working prototype of this on all 4 crags we've recently done the fb promos on:

https://dev.thecrag.com/climbing/japan/joyama

https://dev.thecrag.com/climbing/turkey/datca

https://dev.thecrag.com/climbing/greece/kalymnos

https://dev.thecrag.com/climbing/australia/arapiles

**Comment by brendanheywood** [comment]
Ok so this is now live with the hard coded version. We should really nut out the proper replacement process for who and how to set this inside the platform. I think anyone with coordinator privs should be able to do this. I see it as:

* [ ] On the photo detail page make, have 'Make this the web cover for this' button. If there are nested crags then have a split button with one option for each crag. I'd also have some sort of check that the photo is at least X x Y which is enough to accommodate most different cropping sizes.

* [ ] After that I think we do need one extra step which is to choose which part of the photo to prioritize. At this stage the only easy practical options are 'top', 'bottom' and 'none', and this would work in almost all cases. 

* [ ] Or we could implement the full blown solution which is where we have a cropping tool and select the focal point on the image, and then when we crop it it ensure that part is visible.

* [ ] add a stream event

* [ ] also in the same menu have a 'set as my web cover' - I think people should be able to do this for photos which are not theirs, as they may include them, or it may just be a pic of their fav crag they like. I still think this is a nice thing only for sponsor accounts (but happy if for everyone too).

* [ ] we need to make a decision around what metadata we display overlaid on the photo, photographer at minimum. You can click on it to get the rest. It probably makes the most sense for the title, if any shown, is actually part of the webcover link, and not the photo title. ie you can override it. This covers the use case of when you are using someone else crag pic, but don't want the title, of if you want to fine tune the text.

**Comment by nicHoch** [comment]
That sounds very good.
+1 for the personal webcover only for supporters.

Am 1. Februar 2017 13:07:36 MEZ schrieb Brendan Heywood <notifications@github.com>:
>Ok so this is now live with the hard coded version. We should really
>nut out the proper replacement process for who and how to set this
>inside the platform. I think anyone with coordinator privs should be
>able to do this. I see it as:
>
>* [ ] On the photo detail page make, have 'Make this the web cover for
>this' button. If there are nested crags then have a split button with
>one option for each crag. I'd also have some sort of check that the
>photo is at least X x Y which is enough to accommodate most different
>cropping sizes.
>
>* [ ] After that I think we do need one extra step which is to choose
>which part of the photo to prioritize. At this stage the only easy
>practical options are 'top', 'bottom' and 'none', and this would work
>in almost all cases. 
>
>* [ ] Or we could implement the full blown solution which is where we
>have a cropping tool and select the focal point on the image, and then
>when we crop it it ensure that part is visible.
>
>* [ ] add a stream event
>
>* [ ] also in the same menu have a 'set as my web cover' - I think
>people should be able to do this for photos which are not theirs, as
>they may include them, or it may just be a pic of their fav crag they
>like. I still think this is a nice thing only for sponsor accounts (but
>happy if for everyone too).
>
>* [ ] we need to make a decision around what metadata we display
>overlaid on the photo, photographer at minimum. You can click on it to
>get the rest. It probably makes the most sense for the title, if any
>shown, is actually part of the webcover link, and not the photo title.
>ie you can override it. This covers the use case of when you are using
>someone else crag pic, but don't want the title, of if you want to fine
>tune the text.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/theCrag/website/issues/974#issuecomment-276641942

-- 
www.thecrag.com

Nicky Hochmuth
www.thecrag.com/climber/nickyhochmuth

**Comment by brendanheywood** [comment]
Splitting off account webcovers into https://github.com/theCrag/website/issues/2816

@scd I think we can probably close this issue?

**Comment by lordyavin** [comment]
Please reflect the spin off with an update of title and description too.

**Comment by brendanheywood** [comment]
I've just checked that everything not yet done is in #2816, we are good to close this now
