### ISSUE TITLE
create sample favorite on signup

### ISSUE THREAD

**Issue by scd** [theCrag/website#976]
There is code for this in the server but it is currently disabled until we get through the discussion.

This issue has been created from a discussion starting in issue #910 - please read that for more background

Pros:
- Andriod app gets default content so that it looks more interesting after creating an account.

Cons:
- Subverts work on the website teaching people how to create favorites themselves
- Skews stats, activity log, karma and credits. This has long term unknown side effects that cannot be undone.

Upon reflection the cons are actually pretty bad, and the pros are about picking the easy way out in the app, which given how pushed we are for time seems reasonable.

To me the question becomes, do we wait until we get time to implement 'select locale favorite crags' page on signup process or accept the cons and just hack a solution.

**Comment by brendanheywood** [comment]
closing
