### ISSUE TITLE
Investigate clustered pie charts in google maps to show gear type style

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#985]
Just reading a blog and came across this cool map visualization:

![image](https://cloud.githubusercontent.com/assets/187449/22910551/cd2c9cd0-f2ae-11e6-998d-47c506306dfd.png)

https://batchgeo.com/map/92ad350a9800f91f03b3862c64f3593f

Ages ago I was trying to come up with a suitable representation of the gear types on the map and this seems perfect. Is this something others reckon we should do? (later!)

Did some reverse engineering and it's not that hard, only a few more lines of JS. The only backend change we'd need is to push through the break down of each gear type which would be roughly a 15% or 8kb, increase in the json data feed.

The map would be more information dense so, I'd suggest tuning the clustering so it forms less larger clusters.

Just had a bit of a think about the data change if we decide we want this:

Current format (~35 chars per node)

```
[11740963,146774778,-36706165,783],
```

Suggested format (~40 chars per node)

```
"11740963,146774778,-36706165,200,50,20",
```

It's a string, instead of a json array, so that empty strings are allowed between commas, and order the break down by the global average most common gear types in descending order. So above example would represent "Trad 200, Sport 50, Bouldering 20". If the less used gear types are zero they are not present.

Boulder only area

```
"11740963,146774778,-36706165,,,20",
```

Ice only area

```
"11740963,146774778,-36706165,,,,,,,20",
```

So most single type areas would just be a couple comma's larger, it's the really mixed areas which would be the worse case.

**Comment by brendanheywood** [comment]
New mountain project page:
http://www.mountainproject.com/scripts/Factoids#factoid9

**Comment by Drazhar** [comment]
This would be really cool and is mostly don't for over 2 years :D

In my opinion, the option for coloring for example by rock type as Simon siggested isn't really needed and would make to many options for the user. 

What isn't mentioned here yet, is the ability to not only color, but hide certain things. For example to show only boulders.

**Comment by Drazhar** [comment]
But this was already mentioned at #1610.

**Comment by brendanheywood** [comment]
Yeah the reason it's 'mostly done' is due to some unrelated stuff with the way the stats are calculated, and since then we've gather some other unrelated maps things we want to do which means we a re planning on a full rewrite. So we are not that keep to add stuff before the rewrite so we don't do it twice.

But please bear with us, there is a lot on our plate and we are grinding through it, cool stuff is in the pipeworks...
