### ISSUE TITLE
Account presence last active indicator

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#990]
Add a presence:

* [ ] if online right now, a green dot or something?
* [ ] if not active, how long ago?
* [ ] must be able to opt out in settings page

Old desc:

Mostly note to self.  Just a new bit of forum kit that has some great ideas I'd like to mull over:

http://meta.discourse.org/t/presence-features-for-forums/12

**Comment by scd** [comment]
@brendanheywood can we close this

**Comment by brendanheywood** [comment]
I've renamed this to make more sense, this was primarily around:

1) a presence indicator (ie when you were last active on the site) and
2) in the context of forums (up to what message in the thread have you actually seen?)

Both have privacy implications so if we implement this we'd need a setting to disable it. On reflection I think 1 is the most value and 2 it a lot more complexity and privacy issues. So I've change this to only focus on the first part now.

**Comment by lordyavin** [comment]
-1 because this info is visible the users activity already. IMHO no need for additional info display.

**Comment by rouletout** [comment]
We added the inactive account a while back, the other stuff has too many privacy implications for its value, closing
