### ISSUE TITLE
More override fields trip, with, facebook on the log multiple ascents form

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#999]
So far only the date can be set for all ascents. It would be also nice to override the "trip" and "with" field. (+ facebook Jed / Brendan)

**Comment by lordyavin** [comment]
So what is the status of trips? If I can't assign them during ascent logging, they are not useful.

**Comment by scd** [comment]
We are most likely going to discontinue trips.

**Comment by lordyavin** [comment]
Will be there than a general migration to hash tags? 

---- Simon Dale schrieb ----

**Comment by scd** [comment]
What would you like to see for migration?

**Comment by lordyavin** [comment]
Automatic migration of existing trips title to hash tag. Camelcase names. A default field for tags if logging would be helpful too.

Is there a view where I can search for all tagged data? Is it possible to tag pictures?

---- Simon Dale schrieb ----

**Comment by scd** [comment]
Yes you can tag photos. Tagging is done by typing a #sometag in the description of a photo, ascent, route or area.  A hash tag search option should be available for each of the respective facet searches.

I think more rules need to be created for migration. The tags will end up in the descriptions of the ascents, so maybe it needs to be on a per user basis.

If you think we should keep trips then please expand on why. Trips has been something I had high hopes for, but really bombed. I think it is just too much of a niche of a niche.

**Comment by lordyavin** [comment]
I like the idea and concepts behind trips. One may use it to organize a trip together with other theCrag members. The trip members may log targets for the trip so every participant sees what the others want to climb. After the trip is over there is a central place to review and sum up the ascents and photos. 

Addtionally the "open trip" feature is nice if you want to climb in a specific region and need a rope partner or want to join a group. But I didn't use this feature so far.

**Comment by brendanheywood** [comment]
I think trips are a great idea but it has to be executed really well, and in it's current state we're a long way from what other generic 'event' tools offer which I think we'd need to get to before the climbing specific value added features would really make a difference. It's a tough call to scrap it vs spend the effort to fix it up. At this stage it is just limping along quietly in the background.
